### ISSUE TITLE
Volcano scheduler panic if not set minResources in podgroup

### ISSUE THREAD

**Issue by DeliangFan** [volcano-sh/volcano#1001]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Volcano scheduler panic if not specific the minResources in podgroup when scheduling.

goroutine 186 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1692540, 0x27565c0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
volcano.sh/volcano/pkg/scheduler/plugins/proportion.(*proportionPlugin).OnSessionOpen(0xc0005af0e0, 0xc0002c0a00)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/pkg/scheduler/plugins/proportion/proportion.go:107 +0x51d
volcano.sh/volcano/pkg/scheduler/framework.OpenSession(0x1b5f340, 0xc0003e6c00, 0xc000558c30, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/pkg/scheduler/framework/framework.go:48 +0x190
volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc00030d570)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/pkg/scheduler/scheduler.go:76 +0x15b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005884d0)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005884d0, 0x1b04c40, 0xc000558ae0, 0x1, 0x0)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005884d0, 0x3b9aca00, 0x0, 0x1, 0x0)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005884d0, 0x3b9aca00, 0x0)
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run
        /opt/tiger/compile_path/src/code.byted.org/tce/volcano/pkg/scheduler/scheduler.go:66 +0xd4

**What you expected to happen**:

The volcano scheduler works happy.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a podgroup without minResource.
2. The volcano scheduler panic.

**Anything else we need to know?**:

**Environment**:
- Volcano Version:

91e94ae75083316e14d7ecd529860849f5fa41b8

- Kubernetes version (use `kubectl version`):

1.14

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`):
Linux 4.14.81.bm.7-amd64
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
please provide your volcano version. Let me have a try

**Comment by Thor-wl** [comment]
@DeliangFan I've tried once with the latest version and volcano works happy. Can you provide more detail about test environment and version info?
my test case:
`
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: test-pg
  namespace: default
spec:
  minResources:
    cpu: "3"
  queue: default
`
my volcano version: v1.0

**Comment by DeliangFan** [comment]
> @DeliangFan I've tried once with the latest version and volcano works happy. Can you provide more detail about test environment and version info?
> my test case:
> `apiVersion: scheduling.volcano.sh/v1beta1 kind: PodGroup metadata: name: test-pg namespace: default spec: minResources: cpu: "3" queue: default`
> my volcano version: v1.0

all commits before 91e94ae

**Comment by DeliangFan** [comment]
> @DeliangFan I've tried once with the latest version and volcano works happy. Can you provide more detail about test environment and version info?
> my test case:
> `apiVersion: scheduling.volcano.sh/v1beta1 kind: PodGroup metadata: name: test-pg namespace: default spec: minResources: cpu: "3" queue: default`
> my volcano version: v1.0

This patch 8fbcd7dc5 makes it panic

**Comment by Thor-wl** [comment]
I've pulled the newest code with the pr you mentioned and tried again as the scene you describe. But scheduler still works happy. Is it possible that thers's some problem with your environment or error operation？
