### ISSUE TITLE
delay pod creation feature not consider resourcequota

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1014]
/kind feature

As mentioned in [delay pod design](https://github.com/volcano-sh/scheduler/blob/master/doc/design/delay-pod-creation.md),  scheduler should watch resourcequota to decide whether podGroup has enough resource quota to create.
```
Quota
To delay pod creation, both kube-batch and PodGroupMinResources will watch ResourceQuota to decide which PodGroup should be in queue firstly. The decision maybe invalid because of race condition, e.g. other controllers create Pods. In such case, PodGroupMinResources will reject PodGroup creation and keep InQueue state until kube-batch transform it back to Pending. To avoid race condition, it's better to let kube-batch manage Pod number and resources (e.g. CPU, memory) instead of Quota
```
But now in the implementation, the enqueue action controls the quota by queue.Spec.Capability instead of k8s resourcequota, so I am curious about the reason why not use resourcequota to control quota。 Is there any consideration？

**Environment**:
- Volcano Version: v0.4.2

**Comment by hzxuzhonghu** [comment]
The queue is cluster scoped not namespace scoped, and it is a set of podgroups in different namespaces. And different queues can include podgroups of the same namespaces too. 

As the resourcequota, it is the kube-apiserver that use it to intercept the pod creation

**Comment by k82cn** [comment]
> scheduler should watch resourcequota to decide whether podGroup has enough resource quota to create.

+1, it's better to avoid enquing an `PodGrouop` which does not have enough quota :)

Would you like to create a PR for that?

**Comment by merryzhou** [comment]
> Would you like to create a PR for that?

ok，I‘d like to have a try.

**Comment by k82cn** [comment]
Let's keep this issue open :)
