### ISSUE TITLE
the label i marked on the job doesn't inherit pod

### ISSUE THREAD

**Issue by ruanxingbaozi** [volcano-sh/volcano#1032]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
the label i marked on the job doesn't inherit pod
```golang
# volcano/pkg/controllers/job/job_controller_util.go: createJobPod
templateCopy := template.DeepCopy()
Labels:      templateCopy.Labels,
Annotations: templateCopy.Annotations,
```
**What you expected to happen**:
i expect to find labels on the pod

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
@ruanxingbaozi It is expected, the job's label is not propagated to the pod. You can set the labels in `PodTemplateSpec`.

**Comment by ruanxingbaozi** [comment]
thanks, use PodTemplateSpec it's work. but i think the job's label  propagated to the pod would be more better.

**Comment by hzxuzhonghu** [comment]
The behavior is consistent with Kubernetes native resource, like deployment/job.
