### ISSUE TITLE
Support hierarchy queue

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#1033]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

 /kind feature

In order to better support fairshare scheduling, propose to support hierarchy queue.

There are two types of queues: parent queues and leaf queues.

```
Parent queues enable the management of resources across organizations and sub- organizations. They can contain more parent queues or leaf queues. They do not themselves accept any application submissions directly.

Leaf queues are the queues that live under a parent queue and accept applications. Leaf queues do not have any child queues, and therefore do not have any configuration property that ends with ".queues".

There is a top-level parent root queue that does not belong to any organization, but instead represents the cluster itself.

Using parent and leaf queues, administrators can specify capacity allocations for various organizations and sub-organizations.
```

**Comment by william-wang** [comment]
It's an important feature. With this feature, volcano can support more scenarios. Do we have a design document right now ?

**Comment by hzxuzhonghu** [comment]
No, just file it as a task of cncf community bridge

**Comment by championshuttler** [comment]
Hi @hzxuzhonghu , I'm interested in working on this project as part of community bridge. I also applied on the website for the same.
Thanks.

**Comment by hzxuzhonghu** [comment]
@championshuttler Welcome, it is better to send me a resume.

**Comment by danijak** [comment]
Hello, @hzxuzhonghu 
I have applied for the CNCF community bridge volcano project. I would love to contribute to the open-source volcano community.

**Comment by hzxuzhonghu** [comment]
@danijak Would want to know which project are you interested in and also expect a resume

**Comment by championshuttler** [comment]
> @championshuttler Welcome, it is better to send me a resume.

@hzxuzhonghu , sent the resume on the email id you mentioned in your github bio.  thanks

**Comment by hzxuzhonghu** [comment]
FYI: https://blog.cloudera.com/yarn-capacity-scheduler/

**Comment by danijak** [comment]
> @danijak Would want to know which project are you interested in and also expect a resume

@hzxuzhonghu I have sent my resume and project proposal on mail id(zhhxu2011@163.com) the same day. I want to work on the project "Implement hierarchy queue to better support fair-share".  Please let me know if you have any questions, I hope the above is useful.
