### ISSUE TITLE
Werid Resource Less behavior

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1036]
/kind bug

**What happened**:

I want to compare to `Resource`, here is the code

```go
package main

import (

	"volcano.sh/volcano/pkg/scheduler/api"
	"volcano.sh/volcano/pkg/scheduler/util"
)


func main() {
	resource1 := api.NewResource(util.BuildResourceList("0m", "0"))
	resource2 := api.NewResource(util.BuildResourceList("101m", "0"))
	println(resource1.Less(resource2))  // output is `flase`
}
```

**What you expected to happen**:
I think this should be `true`

**How to reproduce it (as minimally and precisely as possible)**:
Just run the code

**Comment by hzxuzhonghu** [comment]
Thanks for reporting

**Comment by k82cn** [comment]
it's better to replace `float64` with `big.Rat` in `Resource`

**Comment by hzxuzhonghu** [comment]
/reopen
This is not fixed yet

**Comment by Thor-wl** [comment]
I've analysed this bug. The root reason as follows:
1. Ignoring the comparison: 0=0
2. Ignoring the comparison: default argument `minMilliScalarResources` with 0
