### ISSUE TITLE
When some tasks failed, some tasks succeeded, Job Phase should be Failed rather than Completed

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1046]
I submit one job with 2 tasks.

If 2 tasks both `failed`, the Job status phase display **Failed**!

If 2 tasks both `succeeded`, the Job status phase display **Completed**!

If 1 task `failed`, 1 task `succeeded`, the Job status phase display **Completed**!
It's werid. I think any task failed, the Job status phase should be **Failed** rather than **Completed**

**Comment by Thor-wl** [comment]
please show me your job and podgroup definition with YMAL style. Perhaps minAvailable field setting is incorrect

**Comment by zen-xu** [comment]
I found the reason!

pkg/controllers/job/state/running.go
```go
	default:
		return SyncJob(ps.job, func(status *vcbatch.JobStatus) bool {
			jobReplicas := TotalTasks(ps.job.Job)
			if jobReplicas == 0 {
				// when scale down to zero, keep the current job phase
				return false
			}
			if status.Succeeded+status.Failed == jobReplicas {
				if status.Succeeded >= ps.job.Job.Spec.MinAvailable {
					status.State.Phase = vcbatch.Completed
				} else {
					status.State.Phase = vcbatch.Failed
				}
				return true
			}
			return false
		})
	}
}
```

But I can't understand why `if status.Succeeded >= ps.job.Job.Spec.MinAvailable` job state will be `Completed`, even if some tasks may failed.

**Comment by Thor-wl** [comment]
> I found the reason!
> 
> pkg/controllers/job/state/running.go
> 
> ```go
> 	default:
> 		return SyncJob(ps.job, func(status *vcbatch.JobStatus) bool {
> 			jobReplicas := TotalTasks(ps.job.Job)
> 			if jobReplicas == 0 {
> 				// when scale down to zero, keep the current job phase
> 				return false
> 			}
> 			if status.Succeeded+status.Failed == jobReplicas {
> 				if status.Succeeded >= ps.job.Job.Spec.MinAvailable {
> 					status.State.Phase = vcbatch.Completed
> 				} else {
> 					status.State.Phase = vcbatch.Failed
> 				}
> 				return true
> 			}
> 			return false
> 		})
> 	}
> }
> ```
> 
> But I can't understand why `if status.Succeeded >= ps.job.Job.Spec.MinAvailable` job state will be `Completed`, even if some tasks may failed.

In some scenes, we just expect part of tasks succeed and that's enough to treat the job is successful. As a general partform, Volcano takes it into consideration. It's resonable.

**Comment by zen-xu** [comment]
But we expect all tasks should succeed.
We set `minAvailable` to 1, because we don't need all tasks can allocate resource to run. Some tasks running, some tasks pending this is OK. But we should confirm each task will succeed. So if any task failed, Job display `Completed`, it looks werid.

**Comment by Thor-wl** [comment]
> But we expect all tasks should succeed.
> We set `minAvailable` to 1, because we don't need all tasks can allocate resource to run.
> Some tasks running, some tasks pending this is OK.
> But we should confirm each task will succeed. So if any task failed, Job display `Completed`, it looks werid.

IC, what you need is not **minAvailable** but **policies**

**Comment by k82cn** [comment]
it's better to enhance policy to work together for zen-xu@'s case :)

**Comment by zen-xu** [comment]
You mean use under policy?
```
policies:
- event: PodFailed
  action: AbortJob/TerminateJob
```

But  all Pod of Job will be evicted with this policy.
We need the normal pod not affected by the failed pod.
But if any pod failed, the Job state phase should be Failed.
