### ISSUE TITLE
Support auto scaling memory if Container Terminated Reason is OOMKilled

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1047]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

It's hard to guess how much memory we need.
If request memory is not enough, the task will OOMKilled, then we need to correct it again and again.

**What you expected to happen**:

We hope volcano can auto scaling memory for the job when task OOMKilled, then we needn't correct it by hand, volcano will help us for it.

**Comment by hzxuzhonghu** [comment]
The OOM maybe caused by memory tension of just one node, i think it is hard to say that cluster is lack of memory now.

**Comment by zen-xu** [comment]
> The OOM maybe caused by memory tension of just one node, i think it is hard to say that cluster is lack of memory now.

For some reasons，our task limits resources equeal requests resources，so if one task use memory over requests memory，the task will OOMkilled

**Comment by hzxuzhonghu** [comment]
Yeah, this is more of your own scene, it can be another case:  other pods reside in same node with your task, but they are using more than requested but they may have higher priority. In this case oom killer will first kill the low priority process(maybe your task)

**Comment by Thor-wl** [comment]
In essence, container resource dynamic expansion and reduction is a problem in resource management and K8s has not supported it yet. It will bring unpredictable complexity and risk such as zombie containers for malicious preemption of resources. Volcano mainly foucses on job scheduling and tasks relationship managerment, not resource management.

**Comment by zen-xu** [comment]
Such a pity 😥
