### ISSUE TITLE
xpu-plugin

### ISSUE THREAD

**Issue by ProgramerGu** [volcano-sh/volcano#1048]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
Kubernetes has supported a variety of heterogeneous device management plugins, such as GPU plugin and GPU share. This issuse mainly focuses on the Kunlun chip device XPU developed by Baidu company
**What you expected to happen**:
A new device-plugin for xpu
**How to reproduce it (as minimally and precisely as possible)**:
XPU Device-plugin deploy by DaemonSet
**Anything else we need to know?**:
Need Baidu self research drive support
**Environment**:
- Volcano Version:to add
- Kubernetes version (use `kubectl version`):1.10+
- Cloud provider or hardware configuration:baidu-xpu
- OS (e.g. from /etc/os-release):centos:7 and ubuntu:16.04
- Kernel (e.g. `uname -a`):4.15.0-72-generic
- Install tools:insmod ubuntu_1804_xpu_driver.ko
- Others:

**Comment by ProgramerGu** [comment]
@tizhou86

**Comment by tizhou86** [comment]
@k82cn

**Comment by k82cn** [comment]
I'm ok with that, please create PR to https://github.com/volcano-sh/devices

**Comment by ProgramerGu** [comment]
> I'm ok with that, please create PR to https://github.com/volcano-sh/devices
Copy that～Thanks～
Should I move the existing files （about gpu）to the directory volcano-sh/devices/gpu or just add xpu stuff to the same directory ?

**Comment by k82cn** [comment]
> Should I move the existing files （about gpu）to the directory volcano-sh/devices/gpu or just add xpu stuff to the same directory ?

Prefer to move current code to `volcano-sh/devices/gpu` and create xpu stuff in `volcano-sh/devices/xpu` :)

**Comment by ProgramerGu** [comment]
> > Should I move the existing files （about gpu）to the directory volcano-sh/devices/gpu or just add xpu stuff to the same directory ?
> 
> Prefer to move current code to `volcano-sh/devices/gpu` and create xpu stuff in `volcano-sh/devices/xpu` :)

Got it，thanks～
