### ISSUE TITLE
Task will OutOfMemory/OutOfCPU cause of scheduler cache node info is different from k8s node info

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1052]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We have meet task **OutOfMemory/OutOfCPU** many times, but have no idea why at first.
Then we add some logs to display node info when session open. 
We found some node infos were different from the k8s allocatable node infos when OutOfMemory/OutOfCPU occurs.

**What you expected to happen**:
They should always be the same.

**How to reproduce it (as minimally and precisely as possible)**:
I have no idea how to reproduce it.

**Anything else we need to know?**:
```go
// create informer for node information
sc.nodeInformer = informerFactory.Core().V1().Nodes()
sc.nodeInformer.Informer().AddEventHandlerWithResyncPeriod(
	cache.ResourceEventHandlerFuncs{
		AddFunc:    sc.AddNode,
		UpdateFunc: sc.UpdateNode,
		DeleteFunc: sc.DeleteNode,
	},
	0,
)
```
I found node informer `AddEventHandlerWithResyncPeriod` **disable resync period**, maybe this was the reason made it 🧐.

**Environment**:
- Volcano Version: 0.4.2

**Comment by hzxuzhonghu** [comment]
> We found some node infos were different from the k8s allocatable node infos when OutOfMemory/OutOfCPU occurs.

Can you elaborate a little bit more and paste your logs if possible?


>I found node informer AddEventHandlerWithResyncPeriod disable resync period, maybe this was the reason made it 🧐.

Resync period will retrigger event for the local cached resources, it has nothing to do with this. The list-watch is level triggered

**Comment by zen-xu** [comment]
> > We found some node infos were different from the k8s allocatable node infos when OutOfMemory/OutOfCPU occurs.
> 
> Can you elaborate a little bit more and paste your logs if possible?
> 
> > I found node informer AddEventHandlerWithResyncPeriod disable resync period, maybe this was the reason made it 🧐.
> 
> Resync period will retrigger event for the local cached resources, it has nothing to do with this. The list-watch is level triggered

pkg/scheduler/framework/session.go
```go
func openSession(cache cache.Cache) *Session {
	ssn := &Session{
		UID:        uuid.NewUUID(),
		kubeClient: cache.Client(),
		cache:      cache,

		podGroupStatus: map[api.JobID]scheduling.PodGroupStatus{},

		Jobs:   map[api.JobID]*api.JobInfo{},
		Nodes:  map[string]*api.NodeInfo{},
		Queues: map[api.QueueID]*api.QueueInfo{},

		plugins:           map[string]Plugin{},
		jobOrderFns:       map[string]api.CompareFn{},
		queueOrderFns:     map[string]api.CompareFn{},
		taskOrderFns:      map[string]api.CompareFn{},
		namespaceOrderFns: map[string]api.CompareFn{},
		predicateFns:      map[string]api.PredicateFn{},
		bestNodeFns:       map[string]api.BestNodeFn{},
		nodeOrderFns:      map[string]api.NodeOrderFn{},
		batchNodeOrderFns: map[string]api.BatchNodeOrderFn{},
		nodeMapFns:        map[string]api.NodeMapFn{},
		nodeReduceFns:     map[string]api.NodeReduceFn{},
		preemptableFns:    map[string]api.EvictableFn{},
		reclaimableFns:    map[string]api.EvictableFn{},
		overusedFns:       map[string]api.ValidateFn{},
		jobReadyFns:       map[string]api.ValidateFn{},
		jobPipelinedFns:   map[string]api.ValidateFn{},
		jobValidFns:       map[string]api.ValidateExFn{},
		jobEnqueueableFns: map[string]api.ValidateFn{},
	}

	snapshot := cache.Snapshot()

	ssn.Jobs = snapshot.Jobs
	for _, job := range ssn.Jobs {
		// only conditions will be updated periodically
		if job.PodGroup != nil && job.PodGroup.Status.Conditions != nil {
			ssn.podGroupStatus[job.UID] = job.PodGroup.Status
		}

		if vjr := ssn.JobValid(job); vjr != nil {
			if !vjr.Pass {
				jc := &scheduling.PodGroupCondition{
					Type:               scheduling.PodGroupUnschedulableType,
					Status:             v1.ConditionTrue,
					LastTransitionTime: metav1.Now(),
					TransitionID:       string(ssn.UID),
					Reason:             vjr.Reason,
					Message:            vjr.Message,
				}

				if err := ssn.UpdatePodGroupCondition(job, jc); err != nil {
					klog.Errorf("Failed to update job condition: %v", err)
				}
			}

			delete(ssn.Jobs, job.UID)
		}
	}

	ssn.Nodes = snapshot.Nodes
	ssn.Queues = snapshot.Queues
	ssn.NamespaceInfo = snapshot.NamespaceInfo

	klog.V(3).Infof("Open Session %v with <%d> Job and <%d> Queues",
		ssn.UID, len(ssn.Jobs), len(ssn.Queues))

	for _, node := range ssn.Nodes {
		klog.V(4).Info(
			"Node (%s): idle <%v>, used <%v>, releasing <%v>, state <phase %s, reason %s>, taints <%v>",
			node.Name, node.Idle, node.Used, node.Releasing, node.State.Phase, node.State.Reason, node.Node.Spec.Taints)
	}
	
	return ssn
}
```

Node **used** resource is different from k8s Node **allocated** resources.

**Comment by hzxuzhonghu** [comment]
Where do you get `Allocated` resource?

**Comment by zen-xu** [comment]
> Where do you get `Allocated` resource?

```bash
kubectl describe node $target_node
```
![image](https://user-images.githubusercontent.com/38552291/93302993-60d4d880-f82d-11ea-9fa6-a735b7ff654f.png)

**Comment by hzxuzhonghu** [comment]
IC, there is some latency between volcano and kubelet, volcano calculates the used differently. It add pods bound to a node but in pending status.

**Comment by zen-xu** [comment]
> IC, there is some latency between volcano and kubelet, volcano calculates the used differently. It add pods bound to a node but in pending status.

I have read the cache logic, it's truely no matter with node informer.

But if restart the scheduler, is it possible some tasks may not be added to node info, then volcano cache node info  Allocated resource will be different from k8s Allocated resource.

Because we found OutOfMemory/OutOfCPU always occurs after scheduler restarted.

**Comment by hzxuzhonghu** [comment]
Can we talk in slack or WeChat more instantly?

**Comment by zen-xu** [comment]
![7f1f74f9b037b991a007a7d486ee066](https://user-images.githubusercontent.com/38552291/93416368-4277e700-f8d8-11ea-81a3-e93752c27107.jpg)

**Comment by algs** [comment]
Hi @zen-xu , has this issue been solved?

**Comment by lowang-bh** [comment]
Recently, I also find that OutOfxxx ERROR, due to kube-batch scheduler's cached node infor is not correspoding with kubelet's allocated.   When this error occur, I checked the kubelet's describe and kube-batch's cached node resource, kube-batch's is less than kubelet's used.

I can not find where cause this issue.

**Comment by lowang-bh** [comment]
if there are multiple scheduler, will cause the outofsync error sometimes when pods by different scheduler bind to a node which snapshoted by kube-batch/vocalno scheduler
