### ISSUE TITLE
Some suggestion or doubt about volcano certificate and secret key

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1054]
**These maybe some security issue about volcano **:

about gen-admission-secret.sh file
1. Volcano product certificate and secret key in "/tmp", but the Directory's right is not 600. So I suggest to put certificate and secre in /tmp/volcano and make the rigth 600, owner volcanor.
2. The secret key is stored in clear text.  It should be encrypt and its encryption strength is not less than the algorithm itself.
3. The secret key and certificate should be update periodly.

Pls affirm above issue.

**Environment**:
- Volcano Version:v0.4.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
As I know we are using a job to create certs and secret, and when it is done, the container exit. IIUC,  there is no security issue


>The secret key and certificate should be update periodly.

Agree it should be rotated automatically. And the Webhookconfiguration should be updated at the same time.
