### ISSUE TITLE
volcano documentation bug or suggestion

### ISSUE THREAD

**Issue by yushanjin** [volcano-sh/volcano#1055]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

1、介绍里最好补充下volcano这个词的由来，我拼写这个词每次都得看好几遍，另外我看到gitbub上有volcano/volcano这个项目，容易让人产生歧义
2、建议简介里增加一句总结性的语句，如：volcano是xxxxx调度引擎
3、https://volcano.sh/zh/docs/vcjob/这里面提到vcjob和k8s job的区别，可以指定调度器，而实际上k8s中应该也可以指定自定义的调度器吧
4、我个人觉得还是得增加一些注意事项，比如普通的k8s job甚至其他资源对象，如果指定了volcano调度器，会产生什么后果
5、关于cli命令，说明下kubectl 与vcctl使用上的区别，比如：kubectl get vcjob 和 vcctl job list 有什么本质上的区别？

PS：我个人，其实对volcano不是特别了解，完全是站在一个初学者的角度，我之前对volcano的了解就知道它是一个机器学习场景下的调度引擎，看过kubeflow on volcano文章

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
Thanks for your reporting 

cc @Thor-wl

**Comment by Thor-wl** [comment]
Thank you for your advice.
1. Make a brief introudction of the name "Volcano" is meaningful. It is good for newers to understand the role of the system.
2. We do have a summary for intrduction. Please have a look at "About" section title.
3. K8S sets default-scheduler as default, no custom scheduler filed as far as i know.
4. I think it's a good advice to introduce how to run native job on Volcano. Can you give a pr?
5. We will update all the Cli section.
