### ISSUE TITLE
no reason or message when vcjob status updated

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1067]
when vsjob failed, the status is as following:

```
status:
  failed: 1
  minAvailable: 3
  state:
    lastTransitionTime: "2020-09-25T07:01:07Z"
    phase: Terminated
  version: 7
```
it‘s not friendly to find the failed reason, is it ok to set reason and message in JobState when update JobPhase? 

Environment:

Volcano Version: v1.0.1

**Comment by Thor-wl** [comment]
I'm ok about the advice.
/feature
