### ISSUE TITLE
Pods with overlarge resource requests were scheduled but kept status `OutOfmemory`.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#1068]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

When I applied a job with resource requests more than the idle reources in the cluster, in most cases the job will be pending, waiting for enough resources to run itself. But in some cases, the pods will show status like this:

```shell
NAME                     READY   STATUS        RESTARTS   AGE
lm-mpi-job-mpimaster-0   0/1     OutOfmemory   0          4m38s
```
and the pod description reported this:

```shell
Status:         Failed
Reason:         OutOfmemory
Message:        Pod Node didn't have enough resource: memory, requested: 4850880512, used: 1564475392, capacity: 6414331904
```

so I made some tests, set the requested memory large than idle memory currently, and checked the scheduler log, it shows like this:

```shell
I0925 09:37:45.049703       1 scheduler_helper.go:88] Considering Task <default/lm-mpi-job-mpimaster-0> on node <192.168.11.143>: <cpu 500.00, memory 4850880512.00> vs. <cpu 3060.00, memory 4849856512.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00, attachable-volumes-csi-disk.csi.everest.io 58000.00, cce/eni 11000.00>
I0925 09:37:45.049821       1 allocate.go:202] Binding Task <default/lm-mpi-job-mpimaster-0> to node <192.168.11.143>
I0925 09:37:45.049837       1 statement.go:227] After allocated Task <default/lm-mpi-job-mpimaster-0> to Node <192.168.11.143>: idle <cpu 2560.00, memory -1024000.00, cce/eni 11000.00, hugepages-1Gi 0.00, hugepages-2Mi 0.00, attachable-volumes-csi-disk.csi.everest.io 58000.00>, used <cpu 1360.00, memory 6415355904.00>, releasing <cpu 0.00, memory 0.00>
```
It seems that Volcano scheduler permits jobs with overlarge resources requests to be allocated, while K8s cannot afford this pod, so the status turned to be  `OutOfmemory`.

**What you expected to happen**:

In my opinion, if the idle resource cannot meet the requests of the job, the pods should just be pending and not allocated.

**How to reproduce it (as minimally and precisely as possible)**:

In my test, as long as `job requested memory - cluster idle momory` is no large than 10MB, the job can be allocated successfully, and the pods will be in `OutOfmemory` status.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: latest & release-0.4
- Kubernetes version (use `kubectl version`): 1.15.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOs
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by jiangkaihua** [comment]
I think this questions may refer to the [`func (r *Resource) LessEqual(rr *Resource) bool`](https://github.com/volcano-sh/volcano/blob/3b8662e0e6e4302a633123ae453b842532e93e71/pkg/scheduler/api/resource_info.go#L286) 

 It will compare the difference value of `requested memory` and `idle memory` with `minMemory`, which is set [`var minMemory float64 = 10 * 1024 * 1024`](https://github.com/volcano-sh/volcano/blob/3b8662e0e6e4302a633123ae453b842532e93e71/pkg/scheduler/api/resource_info.go#L72) which is 10MB, just as the same value in my test. 

Change `var minMemory float64 = 1` will assure the pods to be pending.

**Comment by hzxuzhonghu** [comment]
I am thinking about removing these completely. It looks kind of useless.
