### ISSUE TITLE
suggest to support kubectl explain (podgroup queue vcjob) command

### ISSUE THREAD

**Issue by yushanjin** [volcano-sh/volcano#1070]
**Is this a BUG REPORT or FEATURE REQUEST?**:  FEATURE REQUEST

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What happened**:
podgroup resource is created automatically, we can aslo assign podgroup when define vcjob. So i use kubectl explain query syntax how to assign podgroup when define vcjob,  but it's empty or non-exist.

```
root@ubuntu-001:/home/ubuntu/volcano-v1.0.1-linux-gnu# kubectl explain podgroup
KIND:     PodGroup
VERSION:  scheduling.volcano.sh/v1beta1

DESCRIPTION:
     <empty>
root@ubuntu-001:/home/ubuntu/volcano-v1.0.1-linux-gnu# kubectl explain queue
KIND:     Queue
VERSION:  scheduling.volcano.sh/v1beta1

DESCRIPTION:
     <empty>

root@ubuntu-001:/home/ubuntu/volcano-v1.0.1-linux-gnu# kubectl explain vcjob

```

**What you expected to happen**:

support kubectl explain command

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.0.1
- Kubernetes version (use `kubectl version`): v1.18.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 19.10 
- Kernel (e.g. `uname -a`): 5.3.0-64-generic
- Install tools: kubeadm helm
- Others:

**Comment by Thor-wl** [comment]
Thank you for the advice? Can you give a PR for that?
