### ISSUE TITLE
Can a program bind pod with cpu in a plugin pod(DaemonSet pod)

### ISSUE THREAD

**Issue by ProgramerGu** [volcano-sh/volcano#1071]
> /kind feature

**What happened**:
I want to bind pod to Designated cpu,(cpu-manager can't meet all my needs )，so I need a program(or a agent) on each node to do this job
**What you expected to happen**:
I wish my program can run in a plugin pod,so I can just deploy it by DaemonSet,Can it be realized technically?To bind pod with cpus in other pod?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wangxf1987** [comment]
If you want the pod bind specifty cpu, you can use the NUMA.

**Comment by ProgramerGu** [comment]
> If you want the pod bind specifty cpu, you can use the NUMA.

In our online environment, there are a few machines with NUMA on, but machines without NUMA also have the need to bind the specified CPU to the pod. From a technical point of view, I listen to the creation of the pod in a plugin pod, and then execute the command in the plugin-pod to bind the specified CPU to the target pod. Is this feasible?

**Comment by ProgramerGu** [comment]
> > > If you want the pod bind specifty cpu, you can use the NUMA.
> > 
> > 
> > In our online environment, there are a few machines with NUMA on, but machines without NUMA also have the need to bind the specified CPU to the pod. From a technical point of view, I listen to the creation of the pod in a plugin pod, and then execute the command in the plugin-pod to bind the specified CPU to the target pod. Is this feasible?
> 
> Why not achieve the goal in kubelet? Another Problem is how do you allocate CPU for the processes of the Pod? I don't think the plugin pod has the privilege to sense the processes.

Wu...On the whole, it is really the best way to do some work in kubelet. Thank you for your advice～
