### ISSUE TITLE
Is vcjob name's length limited?

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1074]
> /kind bug
> /kind feature

When I create a name i found it same no rules for name length.

And the code same only judge the 0.

Guys, do you have the same issue?

**Environment**:
- Volcano Version:v0.4.0
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):unbuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
is there any issue for that? I'm ok to also check the max length of job name :)

**Comment by Thor-wl** [comment]
As what i tested, the name length of vcjob is not admitted to be more than 63 character.
![Uploading 截图.PNG…]()
