### ISSUE TITLE
Resolve the golint issues

### ISSUE THREAD

**Issue by TommyLike** [volcano-sh/volcano#108]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Resolve all the golint issues ignored in the file of `.golint_failures`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
I think mostly fixed.
