### ISSUE TITLE
need more info when job pending

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1094]
> /kind feature

**What happened**:

when pod of volcano job pending, there is no actual reason in events/status of job、podgroup and pod.

```
kubectl describe vcjob test
...
Status:
  Min Available:  1
  Pending:        1
  State:
    Last Transition Time:  2020-10-14T02:17:58Z
    Phase:                 Pending
Events:                    <none>

kubectl describe pg test
...
Status:
  Conditions:
    Last Transition Time:  2020-10-15T09:01:46Z
    Message:               1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable.
    Reason:                NotEnoughResources
    Status:                True
    Transition ID:         a6e36d8a-1672-406e-a9f5-f113174114fe
    Type:                  Unschedulable
  Phase:                   Inqueue
Events:
  Type     Reason         Age                    From     Message
  ----     ------         ----                   ----     -------
  Warning  Unschedulable  69s (x78789 over 26h)  volcano  1/1 tasks in gang unschedulable: pod group is not ready, 1 Pending, 1 minAvailable.

kubectl describe pod test-xxx
Events:          <none>
```

expect more detailed info in events/status, for example: xx resources not enough（expect：5， idle：3）

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.0.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
I'm ok about the feature. Let me take it into consideration in v1.2 design. /assing @Thor-wl

**Comment by mikechengwei** [comment]
I can do this pr and assign it to me, ok?

**Comment by Thor-wl** [comment]
> I can do this pr and assign it to me, ok? @Thor-wl

Of course! Thanks for your contribution! I'll update the roadmap and assgin this feature to you. According to plan, v1.2 will be released at the middle of 1st 2021, so please note it.

**Comment by Thor-wl** [comment]
@mikechengwei roadmap updated done. https://github.com/volcano-sh/volcano/pull/1133
