### ISSUE TITLE
can not update PriorityClassName in job.spec 

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1097]
> /kind feature

**What happened**:

when update job.spec.PriorityClassName,  i got the error:

 job updates may not change fields other than `minAvailable`, `tasks[*].replicas` under spec

can you tell me the reason? and can we support it?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Modification of PriorityClass may bring a lot of managerment problems. Do you have the custom scene?

**Comment by merryzhou** [comment]
> Modification of PriorityClass may bring a lot of managerment problems. May i have your custom scene?

My scene is simple:  when jobs in pending status，it's priority can be modified，so that it can be scheduled first

**Comment by Thor-wl** [comment]
The scene is reasonable. The feature has been listed into v1.2 for discussion.
