### ISSUE TITLE
when not use  proportion plugin, all job in the queue created first  will be scheduled first

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1098]
> /kind feature

**What happened**:

my scenario：

Jobs in different namespaces should be sorted by created time, and jobs in the same namespace should be sorted by priority。

for example:
1. ns A has job a1 which priority  is 2,  job a2 with priority 1,  we expect a1 will be scheduled first； --- volcano can do it 
2. ns A has job a, and ns B has job b, and job a created first, we expect a will be scheduled first;    --- we cannot find a proper config for this scenario

other info:
we bind a queue to each namespace, and unset proportion plugin( https://github.com/volcano-sh/volcano/issues/1083#issuecomment-707443694).

After unset  proportion plugin, all job in the queue created first  will be scheduled first, that means in the above example, all jobs in ns A will be scheduled first。 

**What you expected to happen**:
1. is there any way to achieve example 2
2. is it unreasonable all job in the queue created first  will be scheduled first when unset proportion plugin?

**Environment**:
- Volcano Version: v1.0.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Accord to the logic of allocate action, the requirement cannot be satisfied currently. I'll take it into consideration of v1.2 feature design. /assign @Thor-wl

**Comment by shinytang6** [comment]
I wonder why the default `QueueOrder` behavior(without plugins) is by CreationTimestamp & UID? I don't think it's meaningful and instead it should be the same as the default `NamespaceOrderFn` behavior, maybe just schedule queue one by one, let jobs dominate the scheduing order?

**Comment by alcorj-mizar** [comment]
> while not having to select a queue first and then decide which job to schedule
There are some misunderstanding, we do not select a queue first.Instead, all jobs are schedule by job's creation timestamp between namespaces and queues will ensure the fair schedule.
Scheduling system is always make a balance between fairness and high efficiency.
The example above is not complex enough, let's think more deeper.
There are 5 jobs to be scheduled by 2 queue(namespace).
1. ns A has job a1 with priority 2, creation timestamp is 8:05AM, job a2 with priority 1 creation timestamp is 8:10AM, job a3 with priority 3 timestamp is 8:30AM.
2. ns B has job b1 with priority 1 timestamp is 8:25AM, b2 with priority 2 timestamp is 8:35AM.

the default order by timestamp is a1 > a2 > b1 > a3 > b2. If priority > create early, a3 > a1 > b2 > a2 > b1, else if priority < create early, a2 > a1 > b1 > a3 > b2. Two different configuration.

**Comment by k82cn** [comment]
We usually keep same order for both job, queue and namespace in different session to make behaviour consitant. So we usually order them by other properties, e.g. priority, but if the properties are "equal", we use creation timestamp as latest property.

Back to your case, job's priority only take effect within a Queue, it's not global :) 

> ns A has job a, and ns B has job b, and job a created first, we expect a will be scheduled first; --- we cannot find a proper config for this scenario

We will allocate resoruce to Queue firstly, then allocate resource to job; so what's your business scenarios for this case?

**Comment by shinytang6** [comment]
l think the current implementation is not reasonable to be the default allocate behavior, it's just for achieving fair scheduling right? Or why not we only consider Job order globally. So l think it's better to be made into a plugin form to support different scenarios of allocate. E.g., maybe we can add parameters to allocate action to specify the regulation of allocation?

**Comment by merryzhou** [comment]
> so what's your business scenarios for this case?

we do not care about the queue resources fairness, we care about maximize resource utilization more。And according to https://github.com/volcano-sh/volcano/issues/1083#issuecomment-707443694,  we removed the proportion plugin 

Besides，we expect jobs in different queue should be sorted by created time, and jobs in the same namespace should be sorted by priority

**Comment by k82cn** [comment]
> Besides，we expect jobs in different queue should be sorted by created time, and jobs in the same namespace should be sorted by priority

If so, it's better to use only one queue.

**Comment by merryzhou** [comment]
> > Besides，we expect jobs in different queue should be sorted by created time, and jobs in the same namespace should be sorted by priority
> 
> If so, it's better to use only one queue.

i don't understand how to use one queue to achieve that, can you explain more?
