### ISSUE TITLE
Configurable Job Retries

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#1104]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

xref: https://aws.amazon.com/about-aws/whats-new/2020/10/aws-batch-supports-configurable-job-retries/

**Comment by XuHaoIgeneral** [comment]
**I hope job retries settng by user, in the future we can decide the retries policy when our function watch event sign.**

**Comment by Thor-wl** [comment]
That's interesting! Let's put it into v1.3 as an option.
