### ISSUE TITLE
a problem when use resourcequota and volcano at the same time

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1105]
**What happened**:

Precondition：
1. there are 3 nodes in the cluster, each node has 1 gpu
1. there is 1 ns in the cluster, and resourcequota of this ns is 2GPU
(suppose all other resources are sufficient)

Reproduce step：
1.  create  a  job with one pod which require 2GPU  --> this pod will be created and stay in pending status because of no node has enough gpu
2. create another job with one pod which require 1GPU  --> this pod cannot be created because of resource quota limit

Maybe we need to find a way to handle this situation

**Environment**:
- Volcano Version: v1.0.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
So any pod who are not bound to node should not take the share of resource quota. It shoud be judged in allocate action. Can you give a PR?

**Comment by zen-xu** [comment]
Since you know there is no node has 2 GPU, why try to create a pod with 2GPU?

**Comment by zen-xu** [comment]
Since there is no node has 2GPU, why try to create one pod with 2GPU?

**Comment by k82cn** [comment]
meet resource quota does not mean schedulable; so it's better to set more resource quota than cluster resources, e.g. twice, and let schedule to dispatch them :)

**Comment by hudson741** [comment]
my ideas are like this:
1： the default k8s ResourceQuota + Namespace is more like the hard way to isolate the cluster resources. but where the volcano  works is more like the train k8s cluster. the train cluster is more value of resource's  sharing and  utilization,so the hard way to do the isolating is not recommend。

2：with some plugin in the volcano like propertion  backfill and some concept in the queue and so on ....they work on the idea that when your  resource is idle,other tenancy will take your resource to improve the train cluster's utilization. so here is my suggest：

1）remove the Quotalimit  from the k8s Admission Control or don't set the namespace's resourceQuota. 
2)  move the resourceQuota to volcano to handle this ,but used the soft way ,not hard way.
