### ISSUE TITLE
add a task when its node not in cache may lead node info always wrong

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1106]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When starting the scheduler, the `SchedulerCache` will sync pods, nodes and other resources.
But if adding a running pod into cache, but its node not in cache, the `addTask` func will create a **empty** `NodeInfo`.

```go
// pkg/scheduler/cache/event_handlers.go

func (sc *SchedulerCache) addTask(pi *schedulingapi.TaskInfo) error {
	job := sc.getOrCreateJob(pi)
	if job != nil {
		job.AddTaskInfo(pi)
	}

	if len(pi.NodeName) != 0 {
		if _, found := sc.Nodes[pi.NodeName]; !found {
			sc.Nodes[pi.NodeName] = schedulingapi.NewNodeInfo(nil)
		}

		node := sc.Nodes[pi.NodeName]
		if !isTerminated(pi.Status) {
			return node.AddTask(pi)
		}
	}

	return nil
}
```

Then the **empty** `NodeInfo` will add this `TaskInfo`

```go
// pkg/scheduler/api/node_info.go

func (ni *NodeInfo) AddTask(task *TaskInfo) error {
	if len(task.NodeName) > 0 && len(ni.Name) > 0 && task.NodeName != ni.Name {
		return fmt.Errorf("task <%v/%v> already on different node <%v>",
			task.Namespace, task.Name, task.NodeName)
	}

	key := PodKey(task.Pod)
	if _, found := ni.Tasks[key]; found {
		return fmt.Errorf("task <%v/%v> already on node <%v>",
			task.Namespace, task.Name, ni.Name)
	}

	// Node will hold a copy of task to make sure the status
	// change will not impact resource in node.
	ti := task.Clone()

	if ni.Node != nil {
		switch ti.Status {
		case Releasing:
			if err := ni.allocateIdleResource(ti); err != nil {
				return err
			}
			ni.Releasing.Add(ti.Resreq)
			ni.Used.Add(ti.Resreq)
		case Pipelined:
			ni.Pipelined.Add(ti.Resreq)
		default:
			if err := ni.allocateIdleResource(ti); err != nil {
				return err
			}
			ni.Used.Add(ti.Resreq)
		}
	}

	// Update task node name upon successful task addition.
	task.NodeName = ni.Name     // ni.Name == ""
	ti.NodeName = ni.Name       // so ti.NodeName == task.NodeName == "", WTF????
	ni.Tasks[key] = ti

	return nil
}
```

The wrong logic is the empty NodeInfo's Name is "", so this lead the `ti.NodeName` also be ""

**How to reproduce it (as minimally and precisely as possible)**:
I have a demo picture
![image](https://user-images.githubusercontent.com/38552291/96818157-7b652780-1453-11eb-92e9-0362f4995b81.png)

And this is a pictrue when scheduler restarted cause OutOfCPU, you can see pod `posapply` always running between 17:50 - 18:50，But scheduler cannot add this pod into cache. This cause the node missing this pod，So the node info will be always wrong.
![image](https://user-images.githubusercontent.com/38552291/96736113-db75b280-13ee-11eb-9e04-83290caf6920.png)

So maybe I think scheduler should sync nodes info before sync pods info

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 0.4.0

**Comment by Thor-wl** [comment]
Good job!
