### ISSUE TITLE
TaskSpec should support something like dependon

### ISSUE THREAD

**Issue by shinytang6** [volcano-sh/volcano#1117]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What you expected to happen**:

Imagine a scenario, when a task must precede another task, volcano now only supports raising the priority of the task to prioritize scheduling, but this is not guaranteed. Therefore, a mechanism is needed to ensure that one task precedes another task for sure.

**Comment by Thor-wl** [comment]
Can you provide a real scenario for that?

**Comment by k82cn** [comment]
We'd like to leverage Argo to do that :)

Anyway, if there's any scenario is not covered, task dependency is also ok to me :)

**Comment by shinytang6** [comment]
> Can you provide a real scenario for that?

l'm not requesting this feature for real scenario, just thought of this feature maybe useful in some non-ml/hpc scenario like CI? I'm not sure if anyone uses it like this.
