### ISSUE TITLE
Broken links in doc

### ISSUE THREAD

**Issue by daixiang0** [volcano-sh/volcano#1124]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

The link in example/integrations/mxnet/train/README.md is broken.

**Comment by william-wang** [comment]
Thanks, the old link does not exist any more. We need to update it.

**Comment by william-wang** [comment]
/ assign @ Thor-wl
