### ISSUE TITLE
Support to mpi job in no root user

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#1128]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, the mpi job has to set `--allow-run-as-root` to run in kubernetes; it's better to have a user management in k8s/volcano. For example, create a `/etc/passwd` for each pod, and set username when submit the mpi job.

**Comment by shinytang6** [comment]
l can help with that :) /assign @shinytang6

**Comment by acmore** [comment]
!1340 added a mpi plugin to run mpi job without privileges
