### ISSUE TITLE
Update kube-batch dependency to master

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#114]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

**Description**:

We'd like to dependent on [volcano-sh/kube-batch](http://github.com/volcano-sh/kube-batch) master branch, and use upstream-master branch for kuberentes-sigs/kube-batch.

Sorry for the inconvenient :)

**Comment by TommyLike** [comment]
I refuse to handle this today :)

**Comment by k82cn** [comment]
that's ok to me :)
