### ISSUE TITLE
Queue changes to `unknown` status, then can not be deleted

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/volcano#1150]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Close a queue with a running 
Queue changes to `unknown` status, then can not delete that queue

**What you expected to happen**:
Queue can be deleted

**How to reproduce it (as minimally and precisely as possible)**:
1) create a test queue
2) submit a volcano job into test queue
3) use `vcctl` to close test queue. Because there is a running job, test queue status will change to `closing`
4) delete the running volcano job, then this test queue status will change to `unknown`

Can not `delete` or `update` this `unknown` queue.

![image](https://user-images.githubusercontent.com/10152842/99245825-360ffc00-283f-11eb-9127-b3bb7540feab.png)

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master

**Comment by k82cn** [comment]
fixed by #1151
