### ISSUE TITLE
Request volcano to support k8s 1.19

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#1155]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature
As more and more customers upgrade their cluster to k8s  to 1.19 version. We hope volcano can support k8s 1.19 as soon as possible.

**Anything else we need to know?**:

**Comment by k82cn** [comment]
it's better to move api to `volcano-sh/apis` and build client for different version.

**Comment by Thor-wl** [comment]
V1.1.1 is planed to be launched as a bug fix version around late December.

**Comment by Thor-wl** [comment]
This feature has already been supported: https://github.com/volcano-sh/volcano/pull/1444
