### ISSUE TITLE
[Bug] Volcano Queue can create or update when queue capacity exceed the cluster resource capacity

### ISSUE THREAD

**Issue by zhangshuiyong** [volcano-sh/volcano#1162]
In my k8s cluster, only one node have 2 gpu

And I post a create queue request or patch a update queue request to k8s with setting queue capacity "nvidia.com/gpu" to "5"，but this is no error return.

 Is it a bug?

![image](https://user-images.githubusercontent.com/1655233/100322499-5427ea00-2fff-11eb-9cf3-f249bfcb86da.png)

![image](https://user-images.githubusercontent.com/1655233/100323025-14153700-3000-11eb-946d-55b2a6929c2e.png)

**Comment by wpeng102** [comment]
I do not think this is a bug. The `capacity` describes the max resource queue can use, currently there is only 2 GPU in cluster, but scheduler do not know when  to add more GPU resource into cluster, maybe in next minute. 
And Queue should be managed by cluster administrator, they have a whole picture of cluster resources.

**Comment by XuHaoIgeneral** [comment]
job status is pending;

**Comment by Thor-wl** [comment]
I agreee with @wpeng102. As to the  queue capability and cluster total resource, there is no necessary relationship between them.
