### ISSUE TITLE
distribution training jobs with mindspore/tensorflow/pytorch  cannot stop

### ISSUE THREAD

**Issue by jxfruit** [volcano-sh/volcano#1163]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
Distribution training with mindspore/tensorflow/pytorch cannot stop,  only master can be a completed status, and the worker will be always running whatever the master status is. The master will be CrashLoopBackOff status in a few minutes.
![image](https://user-images.githubusercontent.com/11846449/100355684-28bbf400-302d-11eb-8257-f9948de22908.png)
The log of master is good, no error or warning.

**What you expected to happen**:
I am confused about how to stop the jobs.
**How to reproduce it (as minimally and precisely as possible)**:
here is the zip file including yaml, training code and training data
[demo.zip](https://github.com/volcano-sh/volcano/files/5603264/demo.zip)

And here is the relate issues(https://github.com/volcano-sh/devices/issues/10) (https://github.com/volcano-sh/volcano/issues/1136)

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.0.1
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): ubuntu18.04
- Kernel (e.g. `uname -a`): Linux dls1 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: cuda10.1 driver version: 418.87.00
- Others:

**Comment by william-wang** [comment]
@jxfruit Reproduced the issue.  You make wrong configuration for "restartPolicy: Never" field in master task of volcano job.  Two spaces missing before "restartPolicy: Never".

**Comment by jxfruit** [comment]
that's right, tks
