### ISSUE TITLE
MaxResource of Queue

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#117]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Support MaxResource of queue by admission controller & queue controller. 

xref https://github.com/kubernetes-sigs/kube-batch/issues/452

- [ ] Update `Queue` API (https://github.com/volcano-sh/volcano/issues/131)
- [ ] Added QueueController (https://github.com/volcano-sh/volcano/issues/16)
- [ ] ~~Added Queue admission controller~~

**Comment by k82cn** [comment]
I'm thinking whether we should enhance `enqueue` action to consider queue's capability, so we can enqueue "high priority" jobs. And leverage https://github.com/volcano-sh/volcano/issues/135 to make sure the pod will not be create if not enough resources.

**Comment by jiaxuanzhou** [comment]
> I'm thinking whether we should enhance `enqueue` action to consider queue's capability, so we can enqueue "high priority" jobs. And leverage #135 to make sure the pod will not be create if not enough resources.

yeah, agree with u, but the behaviors of the queue controller better be designed to support the dynamic changes of the specs(either the pg number or the resource quota), so the update func of queue controller and admission controller could work together to notify the changes to make the decision whether to create or delay the creation of the pods.

**Comment by hzxuzhonghu** [comment]
I am not sure what does `spec.Capability ` and `MaxResource` mean? And also how does it cooperate with `spec.Weight`. I have no context at all.

**Comment by jiaxuanzhou** [comment]
@hzxuzhonghu
1, the `weight` means the  weight of resource of  the whole cluster for one queue
2, `MaxResource `  is manual defined by the end-user for the queue may be less or more than the `weight` of the queue

**Comment by hzxuzhonghu** [comment]
Then these two fields are both optional, and if both specified, how to deal with the conflict?

**Comment by jiaxuanzhou** [comment]
> Then these two fields are both optional, and if both specified, how to deal with the conflict?

`maxResource` often used for scenario of resource overmatching, but the `weight` is for cluster scope, so by my side, `weight` has higher privilege.

**Comment by hzxuzhonghu** [comment]
So I would expect  a detailed design doc.
