### ISSUE TITLE
Not  found Python API，Can you provide a Python based API

### ISSUE THREAD

**Issue by liudonggang** [volcano-sh/volcano#1172]
Can you provide a Python based API

**Comment by k82cn** [comment]
what's kind of API do you need? k8s python client can be used to submit jobs :)

**Comment by liudonggang** [comment]
I need to create, delete, get all pod information, monitor POD logs, Job status information, and other Python versions of the interface

**Comment by liudonggang** [comment]
When I got the Pod status information, the job was Pending in the scheduler, but Instead of getting this status, I got the wrong status information

**Comment by k82cn** [comment]
for such kind of requirement, python client of k8s is ok :)

xref https://github.com/kubernetes-client/python

**Comment by liudonggang** [comment]
Yes，k8s CustomObjectsApi() Can meet my needs, thank you for your answer！
