### ISSUE TITLE
Hi，i wanna to know what's  the relationship or differences between volcano and opendatahub?

### ISSUE THREAD

**Issue by zhuhb1** [volcano-sh/volcano#1173]
Since volcano and opendatahub are both AI & Bigdata platform based on k8s.
So what's  the relationship or differences between volcano and opendatahub? i got a bit confused

any help will be highly appreciated. thanks

**Comment by Thor-wl** [comment]
Well, i know little about opendatahub. According to the doc of two websites, the differences are as follows:
1. Open Data Hub is based on Kubeflow while Volcano design benefits from lots of existing platform.
2. AI application works with Open Data Hub must be within OpenShift Container Platform. Volcano has no limit.
3. Open Data Hub aims to add more AI tools while Volcano aims to provide general and flexible scheduling ability for high performance workloads including AI.
