### ISSUE TITLE
Design a lightweight storage solution for Volcano

### ISSUE THREAD

**Issue by mikechengwei** [volcano-sh/volcano#1178]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Currently Volcano is friendly to job processing, but the storage requirements also require users to integrate themselves.
I think we can provide a lightweight solution to make Job stateful and friendly.

**Ideas**:

1.  Use one pv and multiple pods share the pv , and use ReadWriteMany access mode.
2. Support a sidecar container and sync data to remote S3 storage.

I think first way is not a good idea , WriteMany is not friendly to write performance and some public clouds also prohibit the use of this mode, such as GCE(Google Compute Engine).If we use this solution , we need to solve one pv and multiple volcano job relationships , for example every pod create a subpath and we have the path of pv and the subpath of pod to get our output address.Users need to maintain the storage relationship between PV and Pod by themselves.

The second way we can provide a sidecar container and a storage proxy service，users can control storage through a pluggable way. We can support s3 storage.

Spec like:
```
spec:
  storage:
    baseImage: sync-xxx
    version: 0.1
    objectStorageConfig:
      key: objectstorage.yaml
      name: objectstorage
```
```
apiVersion: v1
kind: Secret
metadata:
  name: objectstorage
type: Opaque
stringData:
  objectstorage.yaml: |
    type: S3
    config:
      bucket: "volcano"
      endpoint: ""
      region: ""
      access_key: ""
      insecure: true
      signature_version2: true
      secret_key: ""
      put_user_metadata: {}
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 2m
      trace:
        enable: false
      part_size: 41943040
```

**Comment by XuHaoIgeneral** [comment]
I have a control service;  the server create vcJob and pv-pvc;
