### ISSUE TITLE
add 2 or more allocatable devices to a pod

### ISSUE THREAD

**Issue by jxfruit** [volcano-sh/volcano#1181]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind feature
Currently, only one gpu device will be allocated, but in most scenarios, we hope two or more device on the same server or a few devices on servers can be allocated to a pod.
Thank u!

**Comment by k82cn** [comment]
that is great ideal, we can add more devices into https://github.com/volcano-sh/devices :)

**Comment by jxfruit** [comment]
Is there some plans?

**Comment by k82cn** [comment]
which device do you need ? Currently, we only got requirement on GPUs :)

**Comment by jxfruit** [comment]
gpu devices

**Comment by k82cn** [comment]
> gpu devices

refer to https://github.com/volcano-sh/devices for more detail about GPU support. If any requirement on enhancements, please let me know.

**Comment by jxfruit** [comment]
> > gpu devices
> 
> refer to https://github.com/volcano-sh/devices for more detail about GPU support. If any requirement on enhancements, please let me know.

I have commited a requirement in https://github.com/volcano-sh/devices/issues/13.
I am looking forward to your plans

**Comment by summerisc** [comment]
saw this got reopened, any plan to support assign multiple GPU from one node to a pod?

**Comment by Thor-wl** [comment]
> saw this got reopened, any plan to support assigning multiple GPUs from one node to a pod?

Yes.
