### ISSUE TITLE
Schedule jobs only on certain nodes

### ISSUE THREAD

**Issue by SkinyMonkey** [volcano-sh/volcano#1188]
/kind feature

**What happened**:
We'd like to schedule jobs only on certain nodes

**What you expected to happen**:
We would expect to use node selectors to be able to do this through volcano.

**Comment by k82cn** [comment]
that's reasonable to me, we can add a `--node-selector` parameter to the scheduler, and only use those nodes: only create snapshort for those nodes.

/cc @Thor-wl @william-wang

**Comment by william-wang** [comment]
It's a useful case, I'll put this feature in the pipeline.
@SkinyMonkey  Would you like to make a contribution for this feature in volcano?

**Comment by SkinyMonkey** [comment]
@k82cn This is a good idea. I would also add  when creating a job?

@william-wang I would have liked to contribute, sadly we're on a very busy schedule (pun intended) with my company
If it's an easy fix and you guide me I can try but otherwise I won't be able to work on it for a month at least

**Comment by SkinyMonkey** [comment]
I noticed that I can already provider a NodeSelector in the PodTemplateSpec, wouldn't that be enough?

**Comment by k82cn** [comment]
> I noticed that I can already provide a NodeSelector in the PodTemplateSpec, wouldn't that be enough?

Yes, that also works; but you need to add NodeSelector/NodeAffinity to every Pod, e.g. PodTemplate in Deployment.

**Comment by william-wang** [comment]
@SkinyMonkey Thanks for your reply.  We will develop this feature as your are busy on a busy schedule :)

**Comment by SkinyMonkey** [comment]
Thank you @k82cn, @william-wang

We'll try with the nodeSelector by hand first and we'll use the option as soon as you have the time to work on it.

Thanks again for your fast answers and support!

**Comment by k82cn** [comment]
> We'll try with the nodeSelector by hand first and we'll use the option as soon as someone have the time to work on it.

Great! Thanks for your understand :)
 
> Thanks again for your fast answers and support!

My pleasure :)

**Comment by Thor-wl** [comment]
This feature has been adopted to v1.3.0

**Comment by ChAnYaNG97** [comment]
I would like to help, but I am not sure if the method is right or not. Could you please give some suggestions?
1. Add `node-selector` flag in the form of "<key>:<value>"
2. In `newScheduler()`, when building cache, use node selector to filter nodes in `cache.ResourceEventHandleFuncs`: `AddNode`, `UpdateNode` and `DeleteNode`

**Comment by k82cn** [comment]
> 
> 1. Add `node-selector` flag in the form of "<key>:<value>"
> 2. In `newScheduler()`, when building cache, use the node selector to filter nodes in `cache.ResourceEventHandleFuncs`: `AddNode`, `UpdateNode` and `DeleteNode`

That's ok to me overall :)

**Comment by ChAnYaNG97** [comment]
> I would like to help, but I am not sure if the method is right or not. Could you please give me some suggestions? @k82cn @william-wang
> 
> 1. Add `node-selector` flag in the form of "<key>:<value>"
> 2. In `newScheduler()`, when building cache, use the node selector to filter nodes in `cache.ResourceEventHandleFuncs`: `AddNode`, `UpdateNode` and `DeleteNode`

> that's reasonable to me, we can add a `--node-selector` parameter to the scheduler, and only use those nodes: only create snapshort for those nodes.
> 
> /cc @Thor-wl @william-wang

After reading the source code again, I found, just as @k82cn said, it is better to filter node in building snapshot. To filter when building cache makes the problem complex. :)
