### ISSUE TITLE
Improve resource calculation accuracy

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#1196]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

Current volcano is lack of high accurate resource calculation. This leads to some unexptected behaviors.
We already found the Less function and proportion OveruseFn are impacted. Suggest use big.RAT package to 
improve resource calculation accuracy in Volcano.

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wpeng102** [comment]
Suggest use big.float to replace float64:
1)  big.float provide 53bit precision, this is enough for schedule resource.
big.float also provide `Cmp` function to compare two big.float 
```
// Cmp compares x and y and returns:
//
//   -1 if x <  y
//    0 if x == y (incl. -0 == 0, -Inf == -Inf, and +Inf == +Inf)
//   +1 if x >  y
//
```

2) big.float is more efficient than big.Rat. Compare `float64`, `big.float`, `big.Rat` add function cost. I `big.float` is 80+ times slower than `float64`, but much faster than `big.Rat` 
```
var fa, fb float64
	fa = 1.12345678
	fb = 1.12345678
	start := time.Now().UnixNano()
	for i := 1; i < 1000000; i++ {
		fa = fa + fb
	}
	end := time.Now().UnixNano()
	fmt.Printf("float64 cost is: %d\n", (end-start)/1000)

	ba := big.NewFloat(1.12345678)
	bb := big.NewFloat(1.12345678)
	start = time.Now().UnixNano()
	for i := 1; i < 1000000; i++ {
		ba.Add(ba, bb)
	}
	end = time.Now().UnixNano()
	fmt.Printf("big.float cost is: %d\n", (end-start)/1000)

	ra := big.NewRat(112345678, 100000000)
	rb := big.NewRat(112345678, 100000000)
	start = time.Now().UnixNano()
	for i := 1; i < 1000000; i++ {
		ra.Add(ra, rb)
	}
	end = time.Now().UnixNano()
	fmt.Printf("big.rat cost is: %d\n", (end-start)/1000)
```

![image](https://user-images.githubusercontent.com/10152842/102299955-e8e28f80-3f8e-11eb-9d21-abde470e00f2.png)

3) Change `float64` to `big.float` is much more easier than `big.Rat`. For `big.Rat` we need provide numerator  and denominator to create a  `big.Rat`.  But `big.float` only need provide  float to create a new  `big.float` value

**Comment by wpeng102** [comment]
@william-wang @k82cn @Thor-wl please help review the above proposal.

**Comment by k82cn** [comment]
> @william-wang @k82cn @Thor-wl please help review the above proposal.

 How are we sure `big.float` is enough for our cases?

**Comment by william-wang** [comment]
What is the minimum CPU/MEMORY/GPU value if we use big.float? @wpeng102

**Comment by Thor-wl** [comment]
> What is the minimum CPU/MEMORY/GPU value if we use big.float? @wpeng102

@wpeng102 Same doubt to me

**Comment by wpeng102** [comment]
`big.float` still is a float, can not resolve `01+02 == 0.3` issue. We need to use `big.rat`

**Comment by k82cn** [comment]
> `big.float` still is a float, can not resolve `01+02 == 0.3` issue. We need to use `big.rat`

let's use Rat :)
