### ISSUE TITLE
volcano-introduction.pptx problem

### ISSUE THREAD

**Issue by fffffreedom** [volcano-sh/volcano#1206]
hi

when i open the pptx, it shows the following messages, and pictures is unreadable, thks

  型号名称：	MacBook Pro
  型号标识符：MacBookPro14,3
  系统版本：	macOS 10.13.6 (17G65)
  内核版本：	Darwin 17.7.0

PowerPoint 在文件 volcano-introduction.pptx 的内容中发现问题。PowerPoint 可以尝试修复该文件。如果您信任此文件的来源，请单击“修复”。

PowerPoint 无法读取 volcano-introduction [已修复] 中的一些内容，已将其删除。
请检查您的演示文稿以查看其余内容是否正常。

![image](https://user-images.githubusercontent.com/26200904/102703780-46881c00-42ae-11eb-91c4-15eba547ef33.png)

**Comment by k82cn** [comment]
hm.... let me upload a PDF version of this introduction :)

**Comment by fffffreedom** [comment]
appreciate it
