### ISSUE TITLE
allocation bug: high priority queue block others

### ISSUE THREAD

**Issue by wstian** [volcano-sh/volcano#1210]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
In a namespace, job ``j1``(request 3 cpu)  in queue ``q1``, job ``j2`` (request 1 cpu) in queue ``q2``.  queue ``q1`` has high priority, and there are only a node ``n1`` with 2cpu
when allocation,  ``j1`` in ``q1`` will be allocated first, but there are no enough cpu for it, so it failed. 
but before ``j2`` has chance to be allocated, the ``allocation`` action exit. 
``j2`` also failed to be allocated on to ``n1``

**What you expected to happen**:
``j2`` should be able to be allocated on to the node ``n1``

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.1.0

**Comment by Thor-wl** [comment]
@merryzhou You have mentioned this bug, yes?
