### ISSUE TITLE
Support customer implementing plugins, and the scheduler loads these plugins dynamically

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1215]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind feature

**What happened**:

Until now, plugins like `binpack`, `drf`, `gang` are provided by official. 
But some users may want to implement the plugin by themself. So if scheduler can dynamicly load plugins, that will make it more flexible when handling different business scenarios.

**What you expected to happen**:

1. Implement  the plugin

```go
// magic.go

package main  // package must be main

import (
    "volcano.sh/volcano/pkg/scheduler/framework"
)

type magicPlugin struct {}

func (mp *magicPlugin) Name() string {
    return "magic"
}

func New(arguments framework.Arguments) framework.Plugin {  // `New` is PluginBuilder
    return &magicPlugin{}
}

func (mp *magicPlugin) OnSessionOpen(ssn *framework.Session) {}

func (mp *magicPlugin) OnSessionClose(ssn *framework.Session) {}
```

2. Build the plugin to .so
```bash
# Example
go build -buildmode=plugin -o plugins/magic.so magic.go
```

3. Since each plugin builder has the same type `framework.PluginBuilder`,  then we can use [plugin](https://golang.org/pkg/plugin/) package to dynamicly load these .so plugins.

**Comment by k82cn** [comment]
That's interesting feature, I like that so much!!!!
@zen-xu would you help on this feature?

**Comment by zen-xu** [comment]
@k82cn 
No problem

**Comment by k82cn** [comment]
> /assign @zen-xu

Thanks very much :) 

BTW, AFAIK, Golang does not support `.so` well, so please also add a feature gate if someone want to disable it :)

**Comment by zen-xu** [comment]
I will add a cli option `--plugins-dir` to vc-scheduler, so if no custom plugin in this dir, scheduler logic will be consistent with the present

**Comment by Thor-wl** [comment]
related PR: 
Doc https://github.com/volcano-sh/volcano/pull/1219
Implementation https://github.com/volcano-sh/volcano/pull/1218
