### ISSUE TITLE
Can volcano support create pod by deployment, not vcjob?

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1221]
**FEATURE REQUEST**:

I want create  pods by deployment not vcjob. How can i do, or volcano is not support?

> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:v1.0.1
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
> I want create pods by deployment not vcjob. How can i do, or volcano is not support?

Volcano already support that; `PodGroupController` will help to create `PodGroup` for K8s Kinds, e.g. `Deployment`, `ReplicaSet`.

AFAIK, this feature was already used in [Huawei Cloud CCI](https://www.huaweicloud.com/product/cci.html) service more than one year :)

**Comment by zishen** [comment]
> > I want create pods by deployment not vcjob. How can i do, or volcano is not support?
> 
> Volcano already support that; `PodGroupController` will help to create `PodGroup` for K8s Kinds, e.g. `Deployment`, `ReplicaSet`.
> 
> AFAIK, this feature was already used in [Huawei Cloud CCI](https://www.huaweicloud.com/product/cci.html) service more than one year :)

thanks a lots， I will try it

**Comment by k82cn** [comment]
> And can you give me an example yaml to create pods?

@Thor-wl , would you help to show an example for that?

**Comment by Thor-wl** [comment]
> > And can you give me an example yaml to create pods?
> 
> @Thor-wl , would you help to show an example for that?

OK. /asign @Thor-wl

**Comment by Thor-wl** [comment]
please refer to https://github.com/volcano-sh/volcano/pull/1222

**Comment by zishen** [comment]
> please refer to #1222 as an example @zishen

Thanks， I have done it，it 's work.
This is my faml:
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-with-volcano
  labels:
    app: tf
  namespace: vcjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf
  template:
    metadata:
      labels:
        app: tf
    spec:
      schedulerName: volcano  # set spec.schedulerName to 'volcano' instead of 'default-scheduler' for deployment
	  nodeSelector:
        host-arch: huawei-x86
      containers:
        - image: tf_x86:20.2.b060
          imagePullPolicy: IfNotPresent
          name: tf
          command:
          - "/bin/bash"
          - "-c"
          #- "chmod 777 -R /job;cd /job/code/ModelZoo_Resnet50_HC; bash train_start.sh"
          args: [ "sleep 200000000; return 1"  ]
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 1
          volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime`
