### ISSUE TITLE
Pod volcano-scheduler-xxxxxxx CrashLoopBackOff error occurred after upgrading volcano to v1.1.1

### ISSUE THREAD

**Issue by bobyu9527** [volcano-sh/volcano#1242]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
In my k8s 1.15 environment, I encountered an error after upgrading volcano version from v1.1.0 to v1.1.1.
pod `volcano-scheduler-xxxxxxx` is always in the CrashLoopBackOfff state, and the following error message appears:
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
standard_init_linux.go:211: exec user process caused "no such file or directory"
...
```
Rolling back to the old version is normal.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
It can be reproduced at any time

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.1.1
- Kubernetes version (use `kubectl version`): v1.15.11
- Cloud provider or hardware configuration: OpenStack instances
- OS (e.g. from /etc/os-release): CentOS Linux 7.8 x86_64
- Kernel (e.g. `uname -a`): 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by shinytang6** [comment]
lt may have something to do with the discussion in [PR1218](https://github.com/volcano-sh/volcano/pull/1218)

**Comment by Thor-wl** [comment]
https://github.com/volcano-sh/volcano/pull/1225 has fixed the bug. And i will launch v1.1.2 to fix it

**Comment by Thor-wl** [comment]
https://github.com/volcano-sh/volcano/releases/tag/v1.1.2 v1.1.2 has fixed it and new image has pushed to dockerhub
