### ISSUE TITLE
Cli installation on documentations

### ISSUE THREAD

**Issue by vot4anto** [volcano-sh/volcano#1244]
Hi, 
following the guide for installing the cli: https://volcano.sh/en/docs/cli/
But I can't find on the last release https://github.com/volcano-sh/volcano/releases/tag/v1.1.2 the path that are mentioned in the guide: path volcano-{version}-linux-gnu\bin\amd64.

**Comment by Thor-wl** [comment]
Sorry for not update the doc. And you can execute `make vcctl` to get the executable file after unziping the release package.

**Comment by vot4anto** [comment]
I have to clone the github repo ? Because I try to do make but without success with zip package.

**Comment by Thor-wl** [comment]
> I have to clone the github repo as you say on documentation? Because I try to do make but without success with only the zip package.

What's the failure reason? I've unziped the release and it's the whole source code.

**Comment by vot4anto** [comment]
This is what I have:

/k8s/volcano-1.1.2$ make vcctl
mkdir -p _output/bin
mkdir -p _output/release
go build -ldflags " -X 'volcano.sh/volcano/pkg/version.GitSHA=`git rev-parse HEAD`' -X 'volcano.sh/volcano/pkg/version.Built=`date "+%Y-%m-%d %H:%M:%S"`' -X 'volcano.sh/volcano/pkg/version.Version=v1.1.1'" -o=_output/bin/vcctl ./cmd/cli
fatal: not a git repository (or any of the parent directories): .git

**Comment by vot4anto** [comment]
I clone the github repo and from the top of it I do make vcctl and I can compile with success, and I can see the job

./_output/bin/vcctl job list
Name    Creation       Phase       JobType     Replicas    Min   Pending   Running   Succeeded   Failed    Unknown     RetryCount
job-1   2021-01-08     Completed   Batch       1           1     0         0         1           0         0           0

**Comment by Thor-wl** [comment]
> fatal: not a git repository (or any of the parent directories): .git

oh, you're right, git repository is necessary indeed.

**Comment by vot4anto** [comment]
We can close the issue, thanks
