### ISSUE TITLE
e2e has some error info

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1250]
https://github.com/volcano-sh/volcano/pull/1214/checks?check_run_id=1593227368

![image](https://user-images.githubusercontent.com/2818395/104706441-0e151a00-5756-11eb-90d0-cd3fee43a995.png)

```
root@dev:~# kubectl get pod -n kube-system | grep kube-sta
kube-state-metrics-f5f758966-wbgvm                  0/1     Pending     0          3m56s

root@dev:~# kubectl describe pod kube-state-metrics-f5f758966-wbgvm  -n kube-system
....
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  47s (x4 over 3m43s)  default-scheduler  0/5 nodes are available: 5 node(s) didn't match node selector.
```

and kube-state-metric deployment here: https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/templates/kubestatemetrics.yaml#L172
```
      nodeSelector:
        node.kubernetes.io/instance-type: controlpanel
```

but in e2e cluster:
```
root@dev:~# kubectl get node  -l node.kubernetes.io/instance-type=controlpanel
No resources found
```

**Environment**:
- Volcano Version: master branch

**Comment by Thor-wl** [comment]
Yes, it's uncompleted in e2e cluster.

**Comment by huone1** [comment]
we can add enable flag in helm values.yaml to void the  nodeSelector #1262  to  resolve

**Comment by Thor-wl** [comment]
This bug has been fixed and close the issue
