### ISSUE TITLE
some e2e tests failed

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1251]
1. https://github.com/volcano-sh/volcano/blob/master/test/e2e/schedulingaction/predicates.go#L106

![image](https://user-images.githubusercontent.com/2818395/104711201-00629300-575c-11eb-864c-8ffd6b586aaa.png)

2. https://github.com/volcano-sh/volcano/blob/master/test/e2e/schedulingaction/preempt.go#L119
![image](https://user-images.githubusercontent.com/2818395/104711339-30119b00-575c-11eb-8f10-2867a19f5f6a.png)

**Comment by huone1** [comment]
predicate e2e May be resloved by #1243

**Comment by huone1** [comment]
> /cc @huone1 Can you help for that?
predicate e2e May be resloved by #1243

**Comment by Thor-wl** [comment]
It seems not appear after some CI fix recently. Close the issue
