### ISSUE TITLE
example for queue resource reservation function 

### ISSUE THREAD

**Issue by ldd91** [volcano-sh/volcano#1252]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
> Uncomment only one, leave it on its own line:
> /kind feature
/kind feature

**What happened**:
We are  interested in  queue resource reservation function,and plan to use it in our production environment.However i only find design doc in github,anyone else have example about have use this function.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
v1.15.1
- Volcano Version:
- 1.1.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Queue resource reservation is on the way and will be merged to v1.2 as planed. V1.2 will be released around late January according to the shedule

**Comment by ldd91** [comment]
Looking forward to it.
