### ISSUE TITLE
support split out fixed quantity CPU from GPU node

### ISSUE THREAD

**Issue by zyyqqq** [volcano-sh/volcano#1259]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What you expected to happen**:
Support split out fixed quantity CPU cores from GPU node to run CPU tasks,  motivations:
-  CPU utilization is low on GPU node sometimes
- GPU is not required for data processing tasks
- Distrubuted training job may need CPU task, for example, Parameter server

**Comment by k82cn** [comment]
> Support split out fixed quantity CPU cores from GPU node to run CPU tasks

We did not bind CPU to GPU; if the task only requires CPU, it's ok to dispatch to a GPU node.

**Comment by Thor-wl** [comment]
> > Support split out fixed quantity CPU cores from GPU node to run CPU tasks
> 
> We did not bind CPU to GPU; if the task only requires CPU, it's ok to dispatch to a GPU node with CPU resources.

Perhaps the issue provider didn't describe his requirement clearly. He wants to reserve part of CPU resource in GPU node for directional scheduling.

**Comment by k82cn** [comment]
So the requirements is: a task may require both CPU & GPU; we need to reserve some CPU in the GPU node for such kind of tasks; right?

**Comment by zyyqqq** [comment]
> > > Support split out fixed quantity CPU cores from GPU node to run CPU tasks
> > 
> > 
> > We did not bind CPU to GPU; if the task only requires CPU, it's ok to dispatch to a GPU node with CPU resources.
> 
> Perhaps the issue provider didn't describe his requirement clearly. He wants to reserve part of CPU resource in GPU node for directional scheduling. Right? @zyyqqq

yes, I want reserve part of CPU resource in GPU node

**Comment by zyyqqq** [comment]
> So the requirements is: a task may require both CPU & GPU; we need to reserve some CPU in the GPU node for such kind of tasks; right?

I want run task only need CPU, but if use default CPU resource by 'limit.cpu' and 'request.cpu', All CPU resource may  allocated in GPU node, GPU will not be used, so I want reserver fixed quantity CPU resource for CPU task.

**Comment by zyyqqq** [comment]
I fount a project similar to my requirement: https://github.com/nokia/CPU-Pooler

**Comment by Thor-wl** [comment]
This feature has been implemented at https://github.com/volcano-sh/volcano/pull/1527
