### ISSUE TITLE
config "overcommit-factor"  less than 1 leads scheduler crash

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/volcano#1261]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug

**What happened**:
scheduer crash

**What you expected to happen**:
scheduler works well

**How to reproduce it (as minimally and precisely as possible)**:
1. config `overcommit-factor` less than 1, like:
```
actions: "enqueue, elect, allocate, backfill, reserve"
configurations:
- name: enqueue
  arguments:
    "overcommit-factor": 0.75
```
2. submit workload, which request all the idle resource.

3. scheduler crash
![image](https://user-images.githubusercontent.com/10152842/105427165-86fd0000-5c87-11eb-9164-460940936325.png)

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.1.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wpeng102** [comment]
a.Sub(b) when `a` less than `b`, then it will lead panic.

https://github.com/volcano-sh/volcano/blob/793a1cf6b848884bd85600007dea1e4e46917cf3/pkg/scheduler/actions/enqueue/enqueue.go#L106

https://github.com/volcano-sh/volcano/blob/793a1cf6b848884bd85600007dea1e4e46917cf3/pkg/scheduler/api/resource_info.go#L156

**Comment by Thor-wl** [comment]
Sorry for lack of validation of `overcommit-factor`. It should be no less than `1.0`.

**Comment by huone1** [comment]
> Sorry for lack of validation of `overcommit-factor`. It should be no less than `1.0`.

if overcommit-factor is less then 1.0， change it to minOverCommitFactor（1.0）

is the method OK ？

**Comment by huone1** [comment]
fix it at PR #1267

**Comment by Thor-wl** [comment]
> > Sorry for lack of validation of `overcommit-factor`. It should be no less than `1.0`.
> 
> if overcommit-factor is less then 1.0， change it to minOverCommitFactor（1.0）
> 
> is the method OK ？

OK

**Comment by wpeng102** [comment]
@huone1 please add log to print `overcommit-factor` value.
