### ISSUE TITLE
Where to Use musl-libc in code at branch master？？

### ISSUE THREAD

**Issue by huone1** [volcano-sh/volcano#1264]
Where to Use musl-libc in code at branch master？？

currently， make image （scheduler）need  musl-libc， but  musl-libc is NO Exist at the Common compilation environment；
It's very unfriendly for new students.
branch： master

**Comment by huone1** [comment]
@zen-xu

**Comment by zen-xu** [comment]
The default base image of `scheduler` is alpine, which only provides `musl-libc`. 
If your want to build the image on ubuntu system by youself, you can specify the base image like `ubuntu` in Dockerfile.

**Comment by k82cn** [comment]
is there any way to disable that by default? Most of user does not care about the compiler :)

**Comment by huone1** [comment]
OK
