### ISSUE TITLE
Seperate Volcano to three major repos

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#1270]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we combine everything in one repo to make them aligh with each other, but there're some new requirements recently:

* Build customized plugins in-house: some users would like to build customized plugins themself which is not suitable to open source
* Integrate with Volcano: build an operator to work with Volcano based on different k8s version, e.g. k8s.1.5 vs. k8s.1.19 in volcano

Based on those requirements, prefer to seperate Volcano into three repos:

* apis: including all related CRDs, e.g. PodGroup, Job, Queue; so the operator can build client-go based on different k8s version
* framework: the framework of scheduler which make customized plugin easier
* volcano: the other part are still in this repo; and this repo will import the other two repos (apis & framework) for related feature, e.g. scheduler

**Comment by k82cn** [comment]
> framework: the framework of scheduler which make customized plugin easier

One potential issue is the k8s version in framework :)

**Comment by gaocegege** [comment]
Thanks for the issue!

Will we keep clientset with apis or volcano?

**Comment by k82cn** [comment]
Keeping clientset align with `volcano.sh/apis` is fine; volcano-sh/volcano will also import that repo :)

**Comment by gaocegege** [comment]
SGTM, thanks.

**Comment by zhsj** [comment]
With Go module nowadays, it's possible to publish different modules in one monorepo. 

For example, etcd recently adopts this approach. https://github.com/etcd-io/etcd/pull/12204
