### ISSUE TITLE
why volcano has four images, can make it in one?

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1271]
> /kind feature

**What happened**:

Volcano has four pod now, also need four images. Can I make mages into one? Is there have any effect?
Is it to consider what problem,when designing？

**Environment**:
- Volcano Version: v1.0.1
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu 18.04.3
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
1. those components maybe deployed in different host 
2. there maybe several admission controllers to align with apiserver in HA mode

Anyway, that's ok to combine them together in one Pod with four containers.

**Comment by zishen** [comment]
> 2\. admission controllers

Ok, thanks a lot.
