### ISSUE TITLE
update deployment.yaml example

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/volcano#1272]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
https://github.com/volcano-sh/volcano/blob/master/example/deployment.yaml is not accurate. It is a `BestEffort` case, currently the `allocate` action will skip `BestEffort` case. Then `backfile` action fill the `BestEffort` into nodes.

**What you expected to happen**:
https://github.com/volcano-sh/volcano/blob/master/example/deployment.yaml  example allocate pod in `allocate` action

**How to reproduce it (as minimally and precisely as possible)**:
apply  https://github.com/volcano-sh/volcano/blob/master/example/deployment.yaml
check the scheduler log, the deployment pod are not `Bind` in `allocate` action but in `backfile` action.

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wpeng102** [comment]
https://github.com/volcano-sh/volcano/blob/8a9b873bf14ba74ad6865cf29f8521ff9e1e717b/pkg/scheduler/actions/allocate/allocate.go#L180-L185

In https://github.com/volcano-sh/volcano/blob/master/example/deployment.yaml it does not have resource request, so the pods are `BestEffort`, it will skip BestEffort task in 'allocate' action

**Comment by k82cn** [comment]
> scheduler plugin should works for deployment which use volcano scheduler.

hm... AFAIK, we already support all kind of k8s API in volcano; is there any specific case for Deployment?

**Comment by wpeng102** [comment]
code has merged. close this issue.
