### ISSUE TITLE
Dynamic Scaling of Queue

### ISSUE THREAD

**Issue by Roca93** [volcano-sh/volcano#1273]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> kind bug
> /kind feature

**What happened**:

Dynamically upscaling of queues works fine, downscaling limits running to one vcjob.

**What you expected to happen**:

Downscaling would not use all available resources depending on queue capabilities.

**How to reproduce it (as minimally and precisely as possible)**:

resource quota defined allowing 90% of the resources. With a queue having as much capability as the resource quota. The vcjobs get queued, having 6 running. 

After this, downscaling the resource quota to 60% of the resources and the capabilities of the queue as well to match those. This will only give 1 running vcjob as a result. Where the expected running is 4 in this example.

When we scale the volcano queue back to 90% but leave the resource quota at 60%, we get the expected 4 running vcjobs.

**Anything else we need to know?**:

The dynamic resource scaling is currently in place to maximize our resource utilization. 

**Environment**:
- Volcano Version: v1.1.0
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: 
- Others:

**Comment by Thor-wl** [comment]
Well, `Queue` is a cluster level cencept and not corresponing to `namespace`. You can submit jobs from different namespace into one queue. So volcano cannot make the resource relationship between namespace and queue. But as a recommanding practice, you can map a namespace to a queue.

**Comment by Roca93** [comment]
I understand. In my example we have specific queues for different namespaces (mapping 1-1). The problem is there are enough resources available cluster wide, but when we scale the queue capabilities down we are limited. 

As the example described, we scale to 60% (resource quota of the ns + corresponding queue), we are limited to 12,5% usage. Upscaling the queue to its original capabilities and leaving the original downscale of the resource quota gives us the expected result of 60% utilization.

Is there some behaviour from the queue regarding dynamic scaling where we need to be aware of? For upscaling there is no issue at all.
