### ISSUE TITLE
vcjob support update image/resources

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1275]
> /kind feature

https://github.com/volcano-sh/volcano/blob/master/pkg/webhooks/admission/jobs/validate/admit_job.go#L241

> job updates may not change fields other than `minAvailable`, `tasks[*].replicas under spec`

is there any reason?   

i wonder to know, if  image, resources  and other fields can be updated?

**Comment by Thor-wl** [comment]
It's a lack of pod update ability for vcjob controller manager. But i think it's a good idea.

**Comment by k82cn** [comment]
> i wonder to know, if image, resources and other fields can be updated?

it's considered as a new job if image/resources changed :)
