### ISSUE TITLE
[feature] Remove direct dependency k8s.io/kubernetes

### ISSUE THREAD

**Issue by gaocegege** [volcano-sh/volcano#1281]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364

It affects lots of downstream projects like tf-operator.

**What you expected to happen**:

Do not depend on k8s.io/kubernetes directly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
I'll take it into consideration together when update volcano to k8s v1.19

**Comment by k82cn** [comment]
xref https://github.com/volcano-sh/volcano/issues/1270

**Comment by shinytang6** [comment]
Can we remove the k8s.io/kubernetes dependency firstly? Otherwise, there will be some errors with downstream project references currently. @k82cn @Thor-wl

**Comment by k82cn** [comment]
> Can we remove the k8s.io/kubernetes dependency firstly? Otherwise, this will block downstream projects references currently. 

hm... we import k8s.io/kubernetes for the algorithms of default scheduler; https://github.com/volcano-sh/apis is used for  downstream projects.

**Comment by adamwoolhether** [comment]
This is becoming a problem when i recently updated some of my deps.

 k8s.io/kubernetes isn't supposed to be imported, read here: https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364

**Comment by Thor-wl** [comment]
> This is becoming a problem when i recently updated some of my deps.
> 
> k8s.io/kubernetes isn't supposed to be imported, read here: [kubernetes/kubernetes#90358 (comment)](https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364)

I've met the same problem when update the dependencies. The way I solved it is that add the indirect dependency and the version to the `replace` module and then try again.
