### ISSUE TITLE
【community bridge】Volcano reading materials improvement

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#1285]
In order to make Volcano easy to use and understand, you task is to improve reading materials. The details are as follows:
* Supplementary examples about how to use Volcano for all northbound computing frameworks. Cases can be referred to are under  volcano-sh/volcano/examples.
* Supplementary examples about how to use Volcano for all southward heterogeneous devices. Current case is only for GPU.
* Make introductions for all Actions and Plugins both in Chinese and English, including how it works and best practices.
* Make instructions about SDK for developers both in Chinese and English. Follow your steps they can write custom Actions and Plugins.
* Update Volcano official docs to date both in Chinese and English.

Idea detail: https://github.com/cncf/mentoring/pull/336/files

**Comment by Dharna5599** [comment]
Hey @Thor-wl ,
This issue seems to be quite interesting, I will like to take it up for lfx mentorship program. Can you please tell me the next step which I need to take. If you want then I can draft a proposal for the project having a solid road-plane.

**Comment by Thor-wl** [comment]
> Hey @Thor-wl ,
> This issue seems to be quite interesting, I will like to take it up for lfx mentorship program. Can you please tell me the next step which I need to take. If you want then I can draft a proposal for the project having a solid road-plane.

Please send me a profile and your work plan about the topic.

**Comment by Dharna5599** [comment]
Sure

**Comment by Nivedita-coder** [comment]
Hey @Thor-wl  I would like to work on this issue. Can I draft proposal for the project.

**Comment by Thor-wl** [comment]
> Hey @Thor-wl I would like to work on this issue. Can I draft proposal for the project.

Of course. Just send your resume and work plan to me as the email address above, please.

**Comment by Thor-wl** [comment]
Some supplements:
* Please show me your skills or practice about Kubernetes, Docker and Volcano in the resume.
* Please make an introduction about your skills or practice on AI and Big Data for Volcano is a scheduling platform designed for high performance workloads.
* It's an option but a highlight point if you can express in Chinese (technological article writing) becase most users and developers of Volcano are Chinese, American and European. Just as what you can see on official website of Volcano, it support both English and Chinese.
* Anyone, who meet requirements of CNCF community bridge and is interested in the issue , can send a resume and work plan to **wulei34@huawei.com** as a apply. I'll response as soon as possible.Thanks!

**Comment by Nivedita-coder** [comment]
Hey @Thor-wl  I want to know is there any cloud lab like Katacoda for Volcano.

**Comment by Thor-wl** [comment]
> Hey @Thor-wl I want to know is there any cloud lab like Katacoda for Volcano.

No, It's very easy to install and test for Volcano. Installation script has already been provided within the project code,

**Comment by k82cn** [comment]
Katacoda seems a good place for Volcano tutorial; prefer to add some classes there :)

/cc @william-wang @Thor-wl

**Comment by Mayank4git** [comment]
Hey @Thor-wl  I want to work on this project. Would you please help me where to start for this project

**Comment by Thor-wl** [comment]
> Hey @Thor-wl I want to work on this project. Would you please help me where to start for this project

Have you sent your resume and work plan?

**Comment by renhuanyu** [comment]
This issue is interesting, I want to challenge~

**Comment by william-wang** [comment]
Is there a plan when the following materials can be ready? @Thor-wl 
- Make instructions about SDK for developers both in Chinese and English. Follow your steps they can write custom Actions and Plugins.

**Comment by Thor-wl** [comment]
> Is there a plan when the following materials can be ready? @Thor-wl
> 
> * Make instructions about SDK for developers both in Chinese and English. Follow your steps they can write custom Actions and Plugins.

Not yet. We plan to take this item at last of the activity and discuss the detail then.

**Comment by william-wang** [comment]
We'd better seperate the items with priority and provide the output stage by stage.

**Comment by Thor-wl** [comment]
This project is ongoing and near completed. Close this issue
