### ISSUE TITLE
WaitForCacheSync should wait all event processed, otherwise may cause OutOfCPU or OutOfMemory

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1289]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Current `WaitForCacheSync` only use `Informer.HasSynced` method to determine whether all resources has synced.

https://github.com/volcano-sh/volcano/blob/2d03377e712aaedb9dfafd7ae7ec66f9276bf92a/vendor/k8s.io/client-go/tools/cache/fifo.go#L149-L153

https://github.com/volcano-sh/volcano/blob/2d03377e712aaedb9dfafd7ae7ec66f9276bf92a/vendor/k8s.io/client-go/tools/cache/fifo.go#L155-L171

From client-go, I found if any event has been called, the Informer will be marked `Synced`. This will cause some problems, If Event `AddPod` has not processed all pods before scheduling, **the Pods which already scheduled on the node** will fail to be added to the `Cache` sometimes, because scheduler may allocate Pending Pods to these node first.

**Comment by Thor-wl** [comment]
Got it! That's interesting. Let's work together for that. 
/assign @Thor-wl @zen-xu

**Comment by huone1** [comment]
func (f *FIFO) Add(obj interface{})   ---- just set   f.populated to true；
but  HasSynced() is  also attention to the "f.initialPopulationCount == 0"

**Comment by git-yww** [comment]
Is this problem solved? @Thor-wl
