### ISSUE TITLE
small resource request job can not be scheduled when a bigger resource request submitted first 

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1294]
> /kind bug

**What happened**:
I have meet the same thin like [issue](https://github.com/volcano-sh/volcano/issues/1119)，but happened on cpu.
I want to know the resolve version.

**Environment**:
- Volcano Version: v1.0.1
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration: A800/9000
- OS (e.g. from /etc/os-release): ubuntu18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
I think we already fixed this issue in latest release, and starvation will be handled by `reservation` feature :)

**Comment by zishen** [comment]
> I think we already fixed this issue in latest release, and starvation will be handled by `reservation` feature :)

ok，I will use v1.1.2
