### ISSUE TITLE
Job always pending and can not failed, when it's require resource over nodes.

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1295]
> /kind bug

**What happened**:

I have a node:72 CPUs. And I create a job which use 73 cpus.
So job pending.

I found this is judged by enqueue time.
`		inqueue := false

		if job.PodGroup.Spec.MinResources == nil {
			inqueue = true
		} else {
			minReq := api.NewResource(*job.PodGroup.Spec.MinResources)
			if ssn.JobEnqueueable(job) && minReq.LessEqual(idle) {
				idle.Sub(minReq)
				inqueue = true
			}
		}

		if inqueue {
			job.PodGroup.Status.Phase = scheduling.PodGroupInqueue
			ssn.Jobs[job.UID] = job
		}
`

I want to know how to solve these case, and can volcano make it failed when job created?

**Environment**:
- Volcano Version:v1.0.1
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration: A800/9000
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
That turn the status of jobs, which stay starvation because of resource limit , to be failed is not reasonable for Volcano, a general scheduling platform for high performance computing. But your can custom timeout feature in your scenario.
