### ISSUE TITLE
The image version in release v1.1.2 pacakge is not correct

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#1299]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Downloaded volcano release v1.1.2 package and install from installer/volcano-deployment.yaml. 
However an old volcano images called "volcanosh/vc-scheduler:latest" was installed finally.

The image version in release 1.1.2 pacakge is not correct.
- The scheduler image in following released files is "image: volcanosh/vc-scheduler:latest", This should be updated to
"image: volcanosh/vc-scheduler:v1.1.2".  This will cause user install an unexpected volcano version.
  volcano-development.yaml
  volcano-development-arm64.yaml
notes: The admission and controller have the same issue.
 
- The "image: volcanosh/vc-scheduler:latest" in dockerhub is not the latest, it is an old image. 

**What you expected to happen**:
Download volcano release v1.1.2 package and install from installer/volcano-deployment.yaml. The volcano v1.1.2 images
is installed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Download volcano v1.1.2 from website.
2. Install volcano from installer/volcano-development.yaml, the old image volcanosh/vc-scheduler:latest is installed.
3. Bugs that already fixed in volcano v1.1.2 happened again in the environment.
for example:
https://github.com/volcano-sh/volcano/pull/1176

**Environment**: 
- Volcano Version: v1.1.2
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):  centos
- Kernel (e.g. `uname -a`): 3.10.0-1062.1.1.el7.x86_64

**Comment by william-wang** [comment]
@Thor-wl please help to operate the image and 1.1.2 package.
1. Remove the latest image on dockerhub to avoid more user pull latest image while installing v1.1.2.
2. The v1.1.2 release package needs to be refreshed as well.

**Comment by Thor-wl** [comment]
> @Thor-wl please help to operate the image and 1.1.2 package.
> 
> 1. Remove the latest image on dockerhub to avoid more user pull latest image while installing v1.1.2.
> 2. The v1.1.2 release package needs to be refreshed as well.

OK

**Comment by Thor-wl** [comment]
This bug has been fixed and close the issue
