### ISSUE TITLE
Cherry pick .spec.Capability of Queue

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#131]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

We need cherry pick https://github.com/kubernetes-sigs/kube-batch/pull/841 to volcano-sh/kube-batch:master, and rebase upstream-master to k-sigs/kube-batch:master.

**Comment by asifdxtreme** [comment]
https://github.com/volcano-sh/kube-batch/pull/5 https://github.com/volcano-sh/kube-batch/pull/4

**Comment by k82cn** [comment]
@asifdxtreme , thanks, please also update volcano's vendor for that.
