### ISSUE TITLE
volcano does not support horovordrun 

### ISSUE THREAD

**Issue by davidstack** [volcano-sh/volcano#1321]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
i want to run horovod job using horovodrun,just like this

```
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  MPI_HOST=`cat /etc/volcano/mpiworker.host | tr "\n" ","`;
                  mkdir -p /var/run/sshd; /usr/sbin/sshd;
                  horovodrun --hosts ${MPI_HOST} -np 2 python tensorflow_mnist.py;
              image:   tensorflow:1.14
              name: mpimaster

```

but it failed with this message:

```
> Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run.run()
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/run.py", line 611, in run
    raise ValueError('Invalid host input, please make sure it has '
ValueError: Invalid host input, please make sure it has format as : worker-0:2,worker-1:2.
```

**What you expected to happen**:
the horovod job will run successfully

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

horovodrun will use this format to run job,just like this

```
horovodrun  -np 2 -H mpi-d3ec808b-worker-0:1,mpi-d3ec808b-worker-1:1  python tensorflow_mnist.py
```

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidstack** [comment]
maybe we should get the gpu number of the pod ,and set this to the hostfile

**Comment by Thor-wl** [comment]
What's the output of `cat /etc/volcano/mpiworker.host | tr "\n" ","`? @davidstack

**Comment by davidstack** [comment]
same as run mpi job,the output is 
`
lm-mpi-job-mpiworker-0.lm-mpi-job,lm-mpi-job-mpiworker-1.lm-mpi-job

`

**Comment by shinytang6** [comment]
Does `mpi-d3ec808b-worker-0:1` means you want to run one process on that worker? l think it can be hacked by yourself while not persist to hostfile 🤔

**Comment by davidstack** [comment]
@shinytang6  you are right, change some volcano code can  run horovod job.

**Comment by goodqinjin** [comment]
@shinytang6  ping
