### ISSUE TITLE
overcommit plugin may cause core dump when MinResources is nil.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#1323]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

in overcommit plugin:
https://github.com/volcano-sh/volcano/blob/4c7780b9378b5e501758ad67f52d5dab0c7371aa/pkg/scheduler/plugins/overcommit/overcommit.go#L93
`api.NewResource()` call `*job.PodGroup.Spec.MinResources`. when `MinResources` is nil, it will range a nil pointer and cause `invalid memory address or nil pointer dereference`, then scheduler crash.

**What you expected to happen**:

check `job.PodGroup.Spec.MinResources != nil`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
fixed by https://github.com/volcano-sh/volcano/pull/1324
