### ISSUE TITLE
provide a plugin to support default scheduler http extender 

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/volcano#1327]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What you expected to happen**:
For some latency scheduler extender, they also use HttpExtender to work with default scheduler, we need provide a plugin to support them.

**Comment by k82cn** [comment]
Let's work together with upstream sig-scehduling team :)

xref https://github.com/kubernetes/kubernetes/issues/99302
