### ISSUE TITLE
Can't delete Volcano Queue

### ISSUE THREAD

**Issue by Roca93** [volcano-sh/volcano#1329]
**What happened**: Can't delete a volcano queue

**What you expected to happen**: Volcano queue deleted

**How to reproduce it (as minimally and precisely as possible)**:

- Create a queue
- Delete queue with kubectl ("not possible because open")
-  Try to change queue status to closed with kubectl edit -> fails.
- Installed vcctl and tried to delete queue -> same issue.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.1
- Kubernetes version (use `kubectl version`): v1.18.9
- Cloud provider or hardware configuration: DGX cluster (1 & 2)
- OS (e.g. from /etc/os-release): RHEL
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Roca93** [comment]
We added the following to the vcctl command and it works:  **vcctl queue operate --action close --name queuename**

We interpreted this from the code. However no documentation can be found. Is this ongoing? Or where can we find the necessary documentation for this?

Thanks!

**Comment by wpeng102** [comment]
Only `closed` can be deleted by `vcctl`. Refer `queue` lifecycle in https://github.com/volcano-sh/volcano/blob/master/docs/design/queue/queue-state-management.md

**Comment by wpeng102** [comment]
@Thor-wl suggest add  `queue` lifecycle introduction in https://volcano.sh/en/docs/

**Comment by Thor-wl** [comment]
> @Thor-wl suggest add `queue` lifecycle introduction in https://volcano.sh/en/docs/

OK！

**Comment by wpeng102** [comment]
@Roca93 you can use `vcctl queue operate -n queueName -a close` to close a queue. The queue state is `closing` if any `Inqueue` `Pending` `Running` jobs in that queue. After the jobs became final state, the queue will became `closed`.  Then you can use `kubectl delete q queueName` to delete it.

**Comment by Roca93** [comment]
Perfect, thanks all!

**Comment by Thor-wl** [comment]
> @Thor-wl suggest add `queue` lifecycle introduction in https://volcano.sh/en/docs/

@rhy Please help for that
