### ISSUE TITLE
Support PodAntiAffinity

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1335]
#### What would you like to be added:

Support job with `PodAntiAffinity`.

#### Why is this needed:
We have some tasks which can't be scheduled on the same node, this will reduce machine load.

**Comment by shinytang6** [comment]
Maybe related to [issue 1231](https://github.com/volcano-sh/volcano/issues/1231)

**Comment by zen-xu** [comment]
I think job should implement `podManagementPolicy` like `StatefuleSet`. If `podManagementPolicy=OrderedReady`, tasks will be created one by one rather than parallelly be created.

**Comment by k82cn** [comment]
> I think job should implement `podManagementPolicy` like `StatefuleSet`. If `podManagementPolicy=OrderedReady`, tasks will be created one by one rather than parallelly be created.

Any use case for that?

**Comment by zen-xu** [comment]
We have a lot of tasks to read data, the e efficiency of reading data will limit by node IO if multi tasks run in same node. So we want to each node only run one task.

**Comment by Thor-wl** [comment]
IC, I'm ok about the feature. 
/assign @Thor-wl

**Comment by Thor-wl** [comment]
After https://github.com/volcano-sh/volcano/issues/1567 has been fixed, pod antiAffinity should work. Please have a try.

**Comment by Thor-wl** [comment]
If no feedback, close this issue temporarily.
/close
