### ISSUE TITLE
can you support MinAvailable for tasks level

### ISSUE THREAD

**Issue by damon008** [volcano-sh/volcano#1337]
#### What would you like to be added:

add MinAvailable for tasks，Let most pods of the job can be running.

**Comment by shinytang6** [comment]
l am trying to implement that in [PR 1193](https://github.com/volcano-sh/volcano/pull/1193) 🤔

**Comment by Thor-wl** [comment]
> @shinytang6 In training scene, user create one job with two tasks(or more tasks), each of them contains more pod. In one task,strong dependence between pods. In the job,strong dependence between tasks. we should set `MinAvailable`for job, but also for task.
> 
> This kind of similar scenario is also common in big data.

I'm sorry for not get the meaning of the requirement. What's the relationship between `MinAvailable` for tasks and the dependency in tasks? I think what you need is `Support task topology scheduling`. Perhaps you can provide an example.
