### ISSUE TITLE
Using deployment to apply pod, pg MinResources is nil and proportion plugin cause core

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1338]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

**What happened**:
When use deployment to create pod(s), the pg's MinResources  is nil, and proportion plugin will call this.
![1-core](https://user-images.githubusercontent.com/7522079/109464299-6f444300-7aa1-11eb-8472-98e1ba4ec334.png)
![2-pg](https://user-images.githubusercontent.com/7522079/109464323-79664180-7aa1-11eb-8595-669cc6aa3d74.png)
![3-proportion](https://user-images.githubusercontent.com/7522079/109464333-7cf9c880-7aa1-11eb-93d3-06a9c312a632.png)

**How to reproduce it (as minimally and precisely as possible)**:
It is happened necessarily, when I use default namespace. But not in my selft creat namepaces . I donot kown why.
I found my case is same in [https://github.com/volcano-sh/volcano/issues/1323](url)

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.01
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jiangkaihua** [comment]
> /cc @jiangkaihua , do we fix that?

Yes, the same error occured in #1001 and we have already fixed it in commit: [fix panic if minResource not set](https://github.com/volcano-sh/volcano/commit/75dea003d8d52c026cc1fc484d406c48f5022cb4#diff-7897f2665be7cba3e8936d1cde487e812ee9bb8e29c89c276a2e575ce3b83b9d).

**Comment by zishen** [comment]
@jiangkaihua @k82cn Thanks a lot.
