### ISSUE TITLE
Support task topology scheduling

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#1349]
#### What would you like to be added:
Support task topology scheduling. user can define the affinity or anti-affinity between different role of tasks.
The scheduler can schedule tasks based on the task topology information.

#### Why is this needed:
There are multiple roles of tasks in one job and there are data exchange/communication between some roles of tasks.
For example, the ps and worker tasks in tensorflow. if these tasks are scheduled on the same node, they can use the internal bandwidth of the node to reduce the latency.

**Comment by Thor-wl** [comment]
related PR: https://github.com/volcano-sh/volcano/pull/1353

**Comment by damon008** [comment]
In the training scene, hope most of interdependent pods can be running in a job. support like issue #1337
