### ISSUE TITLE
Maybe a mismatch in allocate action?

### ISSUE THREAD

**Issue by yzs981130** [volcano-sh/volcano#1358]
In action allocate, there are two approaches to allocate job resources, according to allocate idle or releasing resource. Namely

https://github.com/volcano-sh/volcano/blob/b09b8aff7ee930028e9515535baec9b2e4e51bf9/pkg/scheduler/actions/allocate/allocate.go#L232

https://github.com/volcano-sh/volcano/blob/b09b8aff7ee930028e9515535baec9b2e4e51bf9/pkg/scheduler/actions/allocate/allocate.go#L246

So is there any reason for not using `stmt.Pipeline` in the later occasion?

And will later `ssn.Pipeline` cause status mismatch when gang is not met and `stmt.Discard` is called, because the `Pipeline` operation has not been recorded in `stmt`?

**Comment by k82cn** [comment]
I think that's a bug although no impact to the result.

**Comment by Thor-wl** [comment]
Thanks for your reporting! @yzs981130
