### ISSUE TITLE
Support queue info

### ISSUE THREAD

**Issue by damon008** [volcano-sh/volcano#1359]
#### What would you like to be added:

Support the num of resources in the queue

Support the remaining resources in the queue

#### Why is this needed:

In training scene, we need create a job in one queue,so we need know the remaining resources in the queue.

**Comment by Thor-wl** [comment]
Do you mean you want to get the allocated resource and the capability of a queue when get queue information with API?

**Comment by k82cn** [comment]
> Support the num of resources in the queue
> Support the remaining resources in the queue

Those info may changed after submitting jobs, add new queue; are you going to add an informer for that?

**Comment by Thor-wl** [comment]
> > Support the num of resources in the queue
> > Support the remaining resources in the queue
> 
> Those info may changed after submitting jobs, add new queue; are you going to add an informer for that?

We can take the implementation as a topic in the next weekly meeting.
