### ISSUE TITLE
Support federation for batch workload

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#1376]
#### What would you like to be added:

Make Volcano support federation feature which will forward job/podgroup to multi-clusters.

#### Why is this needed:

For some best-effort batch workloads, it's better to find a one of 'idle' clusters to run them :)

**Comment by Thor-wl** [comment]
ref: https://github.com/volcano-sh/federation

**Comment by k** [comment]
Can we reopen this? That repo does not exist anymore.

**Comment by k82cn** [comment]
> Can we reopen this? That repo does not exist anymore.

Sure & done; let's continue to discuss this topic :)

**Comment by Sharathmk99** [comment]
@k82cn Any update on this? We are looking similar to this.

**Comment by Thor-wl** [comment]
It's an important feature that we are considering to support this year.

**Comment by k82cn** [comment]
> @k82cn Any update on this? We are looking similar to this.

Let me draft a design doc for this feature :) And we're going to handle this feature at https://github.com/volcano-sh/federation .
