### ISSUE TITLE
Failed to install Volcano v1beta1 CRD with Kubernetes over v1.18

### ISSUE THREAD

**Issue by rudeigerc** [volcano-sh/volcano#1377]
**What happened**:

```text
Error: CustomResourceDefinition.apiextensions.k8s.io "jobs.batch.volcano.sh" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[tasks].items.properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[tasks].items.properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

**What you expected to happen**:

Install successfully.

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/volcano-sh/volcano/runs/2158966680

**Anything else we need to know?**:

According to https://kubernetes.io/zh/docs/setup/release/notes/#api-change-2,

> CustomResourceDefinition schemas that use x-kubernetes-list-map-keys to specify properties that uniquely identify list items must make those properties required or have a default value, to ensure those properties are present for all list items. See https://kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy for details.

After #1374 was merged, with controller-gen v0.4.1, `protocol` in CRD of `apiextensions.k8s.io/v1` is set to TCP as default, but CRD of `apiextensions.k8s.io/v1beta1` does not support defaults since they are imported in v1. As a result, `protocol` must be set as `required` with `apiextensions.k8s.io/v1beta1` over Kubernetes v1.18, or the installation would fail.

Since the e2e script uses Kubernetes v1.16.3 as the default version currently, the tests do not encounter this issue. 

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: e2e tests with Kubernetes v1.20.2

**Comment by Thor-wl** [comment]
Let's disscuss how to reslove it. @zen-xu

**Comment by zen-xu** [comment]
If you want to deploy over Kubernetes v1.18,  you can run the below command to generate `v1` version rather than `v1beta1`

```yaml
make TAG=latest CRD_VERSION=v1 RELEASE_DIR=installer generate-yaml 
```

**Comment by zen-xu** [comment]
And I will add a pr to fix this problem
