### ISSUE TITLE
Support set completions/backoffLimit to the task 

### ISSUE THREAD

**Issue by chenyangxueHDU** [volcano-sh/volcano#1379]
#### What would you like to be added:
Like natvie job.Completions. As pods successfully complete, we tracks the successful completions. When a specified number of successful completions is reached, the task is complete.
Like natvie job.BackoffLimit
#### Why is this needed:
More flexible

**Comment by Thor-wl** [comment]
That's interesting! Suggest to take it as a topic as the weekly meeting.

**Comment by zen-xu** [comment]
We have implemented it, users can specify `minSuccess` to control when job is completed.

**Comment by Thor-wl** [comment]
> I have implemented it in my company , users can specify `minSuccess` to control when job should be completed.

Great! Do you have a plan to contribute to community?

**Comment by chenyangxueHDU** [comment]
> I have implemented it in my company , users can specify `minSuccess` to control when job should be completed.

你是港仔？

**Comment by zen-xu** [comment]
> > I have implemented it in my company , users can specify `minSuccess` to control when job should be completed.
> 
> 你是港仔？

上海人

**Comment by chenyangxueHDU** [comment]
> > > I have implemented it in my company , users can specify `minSuccess` to control when job should be completed.
> > 
> > 
> > 你是港仔？
> 
> 上海人

不好意思，我有个大学同学跟你名字一样

**Comment by Thor-wl** [comment]
PR: https://github.com/volcano-sh/volcano/pull/1384
