### ISSUE TITLE
enable-gang-scheduling not work

### ISSUE THREAD

**Issue by chenwenjun-github** [volcano-sh/volcano#1387]
**What happened**:
I use the kubeflow/tf-operator with --enable-gang-scheduling = true, it run on k8s, I have different namespace.
When I submit two same tfjobs at the same time and the resourcequota of namespace is only enough for one tfjob, I find the two tfjob still start to occupy the resources and cause deadlock.

And I try to submit only one tfjob with more resource but the resourcequota of namespace is not enough
![image](https://user-images.githubusercontent.com/46237364/112727324-04c9da00-8f5d-11eb-88d5-c1d66da23b9f.png)
I find although podgroup show that  the resouce is not enough for all pods of tfjob, but there still have several pod which has been created and pod's status is pending

**What you expected to happen**:
when the resouce is not enough for all pods of tfjob, all the pods of tfjob shouldn't be created,
because the pod which status is pending still will be distribute resource.

**How to reproduce it (as minimally and precisely as possible)**:
like the describe above 

**Anything else we need to know?**:
tf-operator version is recently either.

**Environment**:
- Volcano Version:1.2.0
- Kubernetes version (use `kubectl version`):1.13
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
xref: [https://github.com/kubeflow/tf-operator/issues/1264](https://github.com/kubeflow/tf-operator/issues/1264)

**Comment by william-wang** [comment]
OK, Let me have a check and investigation in my environment.

**Comment by Thor-wl** [comment]
According to the discussion of community weekly meeting, adivice as follows:
* switch the use of tf-operator to volcano job api. There will not meet this problem.
* submit an issue to tf-operator to consider gang-scheduling when creating pods.
