### ISSUE TITLE
Propose moving volume claim validation&generate logic into admission hook

### ISSUE THREAD

**Issue by TommyLike** [volcano-sh/volcano#139]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

Now it's handled in job controller [here](https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/job/job_controller_actions.go#L368) which I think should be moved into admission hook, comment if there is something missing.

**NOTE**: hard to think of the case of conflict when generating new names. Since there are 12 random alphabets.

**Comment by k82cn** [comment]
> Since there are 12 random alphabets

We need to make sure that'll not happen in any case.

**Comment by TommyLike** [comment]
give up
