### ISSUE TITLE
I think we should close unit-test `-v` flag

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1392]
**What happened**:

https://github.com/volcano-sh/volcano/blob/fd7a7f2cf7498432297129eca2e1d433bda0e803/Makefile#L120-L122

If set `-v` flag, we will get a lot of useless logs which makes it hard to find error cases

**What you expected to happen**:

remove `-v` flag

**Comment by zen-xu** [comment]
```bash
# this command will only test module which contains "*_test.go"

go test -p 8 -race `find pkg -type f -name '*_test.go' | sed -r 's|/[^/]+$||' | sort | uniq | sed 's/^/volcano.sh\/volcano\//'
```

**Comment by zen-xu** [comment]
If any test case failed, I can quickly get the error position.

![image](https://user-images.githubusercontent.com/38552291/113269910-829a3680-930b-11eb-9145-8de9c8a19a8d.png)

**Comment by Thor-wl** [comment]
I'm ok about it.
