### ISSUE TITLE
podgroup 资源minresource支持nodeselector

### ISSUE THREAD

**Issue by yiyuanyu17** [volcano-sh/volcano#1393]
#### What would you like to be added:
希望podgroup在定义minresource的时候支持每种resource添加nodeselector（optional），在调度的时候判断任务是否可调度的时候结合nodeselector一起考虑判断
#### Why is this needed:
深度学习集群中可能存在多种不同算力的显卡，在判断任务可调度是用整个集群的资源来判断的，但是实际调度的时候指定了nodeselector，无法满足gang调度的需求

**Comment by shinytang6** [comment]
l think we can support this in the overcommit plugin :)
WDYT? /cc @Thor-wl @jiangkaihua

**Comment by jiangkaihua** [comment]
Great, your contribution will be very appreciated! I think we can select available nodes by node selector in `overcommit` plugin, and estimate whether the selected nodes can afford this podgroup by register `overcommit` plugin in `enqueue` action.

**Comment by Thor-wl** [comment]
Sounds reasonable. I'm ok about it. Can you give a design doc about that? @yiyuanyu17

**Comment by Thor-wl** [comment]
Please make an detail introduction of your scenario @yiyuanyu17

**Comment by yiyuanyu17** [comment]
we have a big cluster for different  teams，and each team has different label for node, so we use nodeselector to scheduler our tasks. and when we use spark operator to deal with sparkapplcaiton ,we need to scheduler driver task to CPU node and scheduler executor task to GPU node, but now, whether the task could be scheduled depends on the total resource, not the resource of node matching the nodeselector, which could lead to the deadlock。so, we want to solve this problem in the overcommit plugin, when calculate total resource, judge if nodeselctor is setted and calculate relevant resources。

**Comment by Thor-wl** [comment]
IC, so your main requirement is ** how to ensure scare resource such as GPU to be fully utilized **, right?

**Comment by yiyuanyu17** [comment]
yes, but ensure scare resource is just one side,  in this issue, we want to find a solution to solve the deadlock problem in the condition with node selector
