### ISSUE TITLE
mpi  worker pods ,-np 2 and -np 1 are roughly the same times when assigned to a node

### ISSUE THREAD

**Issue by zhenxiu** [volcano-sh/volcano#1405]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhenxiu** [comment]
![QQ截图20210408184535](https://user-images.githubusercontent.com/14161887/114137315-944c9100-993e-11eb-8cea-85c50ce58f72.png)

**Comment by Thor-wl** [comment]
Well, perhaps you can refer to mpi-operator and there seems to some configurations. I think it's not a question about Volcano
