### ISSUE TITLE
policy.exitCode not work when pod.restartPolicy is OnFailure

### ISSUE THREAD

**Issue by chenyangxueHDU** [volcano-sh/volcano#1407]
**What happened**:
policy.exitCode not work when pod.restartPolicy is OnFailure

**What you expected to happen**:
policy.exitCode work when pod.restartPolicy is OnFailure

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zen-xu** [comment]
Could you please explain what `policy.exitCode not work` means?
