### ISSUE TITLE
Support for Kubernetes v1.18+

### ISSUE THREAD

**Issue by fbalicchia** [volcano-sh/volcano#1413]
Hi there, applying
kubectl  apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml on k8s 1.18.x i retrieve these errors
The CustomResourceDefinition "jobs.batch.volcano.sh" is invalid:
* spec.validation.openAPIV3Schema.properties[spec].properties[tasks].items.properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
* spec.validation.openAPIV3Schema.properties[spec].properties[tasks].items.properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
In CRD v1beta1 , a property specified as a list-map item key must be a required property.

Thanks for help

**Comment by Thor-wl** [comment]
Yes, we have separated apis to volcano.sh/apis repository and k8s 1.18 has already supported. Please refer to https://github.com/volcano-sh/apis

**Comment by zen-xu** [comment]
You can use helm to install volcano

```bash
git clone https://github.com/volcano-sh/volcano.git
cd volcano
helm install installer/helm/chart/volcano --namespace volcano-system --name-template volcano --set basic.crd_version=v1
```

**Comment by fbalicchia** [comment]
Ok it works for me
Thanks

**Comment by Thor-wl** [comment]
> Ok it works for me
> Thanks

fbalicchia, We are sorry for not taking a full communication with you at the latest community meeting. Don't hesitate to leave messages about any use problems in community and let me know.
