### ISSUE TITLE
is there a plan to support GPU topology awareness？

### ISSUE THREAD

**Issue by yiyuanyu17** [volcano-sh/volcano#1415]
#### What would you like to be added:
will it work like a plugin ,when a task choose node to schedule, juge the GPU topology and choose the best node and gpus to schedule. 
#### Why is this needed:
in deep learning train , if one pod need two or more GPUS, it will accelerate the train speed if the scheduler choose the gpus which use nvlink.

**Comment by Thor-wl** [comment]
Yes, it is planed to be developed and released in the second half of the year.

**Comment by Thor-wl** [comment]
Do you have some ideas about that? Maybe we can do some work ahead about that. @peiniliu

**Comment by yiyuanyu17** [comment]
> Yes, it is planed to be developed and released in the second half of the year.

will this issue be discussed in this weekly meeting? i'm interested in  gpu topology awareness  and i will join this weekly meeting if i have time.

**Comment by Thor-wl** [comment]
> > Yes, it is planed to be developed and released in the second half of the year.
> 
> will this issue be discussed in this weekly meeting? i'm interested in gpu topology awareness and i will join this weekly meeting if i have time.

OK, you can prepare some materials about scenarios or design about that.
