### ISSUE TITLE
JobEnqueueable of overcommit plugin issue

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#1416]
**What happened**:

in overcommit plugin， if the idle resources is sufficient that means job can Enqueueable，the plugin adds job min resources to inqueueResource immediately：https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/overcommit/overcommit.go#L110；

but actually whether the job can be enqueued has not yet been decided, may be it's too early to calculate the inqueueResource.

Besides if the scheduler config is:
```
  tiers:
    - plugins:
      - name: sla
    - plugins:
      - name: overcommit
```
and sla plugin returns permit, the overcommit plugin will never be called.

so the JobEnqueueable decision made by overcommit plugin is inaccurate, sometimes it returns *Permit* when idle resource is insufficient, and sometime it returns *Reject* when idle resource is sufficient.

**Comment by shinytang6** [comment]
> **What happened**:
> 
> in overcommit plugin， if the idle resources is sufficient that means job can Enqueueable，the plugin adds job min resources to inqueueResource immediately：[https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/overcommit/overcommit.go#L110；](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/overcommit/overcommit.go#L110%EF%BC%9B)
> 
> but actually whether the job can be enqueued has not yet been decided, may be it's too early to calculate the inqueueResource.
> 
> Besides if the scheduler config is:
> 
> ```
>   tiers:
>     - plugins:
>       - name: sla
>     - plugins:
>       - name: overcommit
> ```
> 
> and sla plugin returns permit, the overcommit plugin will never be called.
> 
> so the JobEnqueueable decision made by overcommit plugin is inaccurate, sometimes it returns _Permit_ when idle resource is insufficient, and sometime it returns _Reject_ when idle resource is sufficient.

lf the scheduler config is as described, l think even if sla plugin returns permit, the overcommit plugin will also be called?
If overcommit return reject, the job still can't be enqueued.

ref: [https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/framework/session_plugins.go#L333](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/framework/session_plugins.go#L333)

**Comment by merryzhou** [comment]
> lf the scheduler config is as described, l think even if sla plugin returns permit, the overcommit plugin will also be called?
> If overcommit return reject, the job still can't be enqueued.

when sla plugin returns permit ==> hasFound = true ==> jobEnqueueable will returns true

ref：https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/framework/session_plugins.go#L356

**Comment by shinytang6** [comment]
> https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/framework/session_plugins.go#L356

ok, l missed that, because you define the plugins in different tiers. What about defining them in the same tier?

**Comment by merryzhou** [comment]
what i expected is： when cluster resources is sufficient, and my job reached sla waiting time, scheduler can reserved some resources for my job. so my job must be Enqueueable，and the pod must be created.

**Comment by shinytang6** [comment]
> what i expected is： when cluster resources is sufficient, and my job reached sla waiting time, scheduler can reserved some resources for my job. so my job must be Enqueueable，and the pod must be created.

Sounds like it related to resource reservation, l think it is not implemented at all.
what l mean is if you configure is like this
```
 tiers:
    - plugins:
      - name: sla
      - name: overcommit
```
at least it will not skip overcommit plugin even if sla jobEnqueueableFns return true.

**Comment by merryzhou** [comment]
> > l think sla waiting time it is not considered in reserve plugin now

according to the [sla doc](https://github.com/volcano-sh/volcano/blob/master/docs/design/sla-plugin.md) and related code,  resources will be reserved after reached sla waiting time
