### ISSUE TITLE
Added job description/source field

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#142]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we can only distinguish different type of job by its name; it's better to have label for different job, e.g. `volcano.sh/job-type=Tensorflow` or `volcano.sh/job-type=MPI`. And we also need to show this info in command line.

**Comment by TommyLike** [comment]
who is responsible for adding this label? end user?

**Comment by k82cn** [comment]
end user or related operators.

**Comment by TommyLike** [comment]
@asifdxtreme would you please help on this?

**Comment by asifdxtreme** [comment]
cc @thandayuthapani
