### ISSUE TITLE
I lost ssh files when I updated my job(<pluginOnJobUpdate>: ssh on jo)

### ISSUE THREAD

**Issue by jingxiang95** [volcano-sh/volcano#1420]
**What happened**:
pkg/controllers/job/plugins/ssh/ssh.go
```golang
// TODO: currently a container using a Secret as a subPath volume mount will not receive Secret updates.
func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {
	data, err := generateRsaKey(job)
	if err != nil {
		return err
	}
	
	if err := helpers.CreateOrUpdateSecret(job, sp.client.KubeClients, data, sp.secretName(job)); err != nil {
		return fmt.Errorf("update secret for job <%s/%s> with ssh plugin failed for %v",
			job.Namespace, job.Name, err)
	}

	return nil
}
```
```golang
	for i, c := range pod.Spec.Containers {
		vm := v1.VolumeMount{
			MountPath: sp.sshKeyFilePath,
			SubPath:   SSHRelativePath,
			Name:      secretName,
		}

		pod.Spec.Containers[i].VolumeMounts = append(c.VolumeMounts, vm)
	}
```
[Mounted Secrets are updated automatically](https://kubernetes.io/docs/concepts/configuration/secret/)
Note: A container using a Secret as a **subPath** volume mount will not receive Secret updates.

-------

when run mpi job,such as horovod elastic job, when i delete pod or update job... ,it's while `Starting to execute plugin at <pluginOnJobUpdate>: ssh on job`,and the ssh secret mount with subPath, when update secret, the ssh file while be remove. This caused the ssh communication to fail and the training exited

`Why do we have to update the ssh secret every time we update the job`

**What you expected to happen**:

I have to delete this code.
```golang
func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {

	return nil
}
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
This problem does exist, the ssh key will disappear when the job is updated/expanded. Your modification can solve the scenes of updating & scale down jobs, but it still cannot solve the expansion scenario.

**Comment by shinytang6** [comment]
> **What happened**:
> pkg/controllers/job/plugins/ssh/ssh.go
> 
> ```go
> // TODO: currently a container using a Secret as a subPath volume mount will not receive Secret updates.
> func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {
> 	data, err := generateRsaKey(job)
> 	if err != nil {
> 		return err
> 	}
> 	
> 	if err := helpers.CreateOrUpdateSecret(job, sp.client.KubeClients, data, sp.secretName(job)); err != nil {
> 		return fmt.Errorf("update secret for job <%s/%s> with ssh plugin failed for %v",
> 			job.Namespace, job.Name, err)
> 	}
> 
> 	return nil
> }
> ```
> 
> ```go
> 	for i, c := range pod.Spec.Containers {
> 		vm := v1.VolumeMount{
> 			MountPath: sp.sshKeyFilePath,
> 			SubPath:   SSHRelativePath,
> 			Name:      secretName,
> 		}
> 
> 		pod.Spec.Containers[i].VolumeMounts = append(c.VolumeMounts, vm)
> 	}
> ```
> 
> [Mounted Secrets are updated automatically](https://kubernetes.io/docs/concepts/configuration/secret/)
> Note: A container using a Secret as a **subPath** volume mount will not receive Secret updates.
> 
> when run mpi job,such as horovod elastic job, when i delete pod or update job... ,it's while `Starting to execute plugin at <pluginOnJobUpdate>: ssh on job`,and the ssh secret mount with subPath, when update secret, the ssh file while be remove. This caused the ssh communication to fail and the training exited
> 
> `Why do we have to update the ssh secret every time we update the job`
> 
> **What you expected to happen**:
> 
> I have to delete this code.
> 
> ```go
> func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {
> 
> 	return nil
> }
> ```
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Volcano Version:
> * Kubernetes version (use `kubectl version`):
> * Cloud provider or hardware configuration:
> * OS (e.g. from /etc/os-release):
> * Kernel (e.g. `uname -a`):
> * Install tools:
> * Others:

This problem does exist, the ssh key will disappear when the job is updated/expanded. Your modification can solve the scenes of updating & scale down jobs, but it still cannot solve the expansion scenario.

**Comment by jingxiang95** [comment]
> This problem does exist, the ssh key will disappear when the job is updated/expanded. Your modification can solve the scenes of updating & scale down jobs, but it still cannot solve the expansion scenario.

@shinytang6 "The expansion scenario" you mean update job and add worker replicas or other scenario? I tested that adding worker replicas can also train normally. Because the new pod just mounts the ssh secret.
such as:
```
[3]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker1-1.horovod-imagenet-job,10.42.65.103' (ECDSA) to the list of known hosts.
[1]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker2-0.horovod-imagenet-job,10.42.65.105' (ECDSA) to the list of known hosts.
[2]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker2-0.horovod-imagenet-job,10.42.65.105' (ECDSA) to the list of known hosts.
[0]<stderr>:2021-04-20 01:24:40.648511: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
[0]<stderr>:Train Epoch     #86:  70%|███████   | 210/300 [00:50<00:21,  4.16it/s, loss=0.607, accuracy=83.1]
[4]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker2-1.horovod-imagenet-job,10.42.65.123' (ECDSA) to the list of known hosts.
[0]<stderr>:Train Epoch     #86: 100%|██████████| 72/72 [00:21<00:00,  3.42it/s, loss=0.615, accuracy=82.6]
```

**Comment by shinytang6** [comment]
> > This problem does exist, the ssh key will disappear when the job is updated/expanded. Your modification can solve the scenes of updating & scale down jobs, but it still cannot solve the expansion scenario.
> 
> @shinytang6 "The expansion scenario" you mean update job and add worker replicas or other scenario? I tested that adding worker replicas can also train normally. Because the new pod just mounts the ssh secret.
> such as:
> 
> ```
> [3]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker1-1.horovod-imagenet-job,10.42.65.103' (ECDSA) to the list of known hosts.
> [1]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker2-0.horovod-imagenet-job,10.42.65.105' (ECDSA) to the list of known hosts.
> [2]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker2-0.horovod-imagenet-job,10.42.65.105' (ECDSA) to the list of known hosts.
> [0]<stderr>:2021-04-20 01:24:40.648511: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> [0]<stderr>:Train Epoch     #86:  70%|███████   | 210/300 [00:50<00:21,  4.16it/s, loss=0.607, accuracy=83.1]
> [4]<stderr>:Warning: Permanently added 'horovod-imagenet-job-worker2-1.horovod-imagenet-job,10.42.65.123' (ECDSA) to the list of known hosts.
> [0]<stderr>:Train Epoch     #86: 100%|██████████| 72/72 [00:21<00:00,  3.42it/s, loss=0.615, accuracy=82.6]
> ```

but the old workers will not update the ssh config of the new worker.

**Comment by jingxiang95** [comment]
> but the old workers will not update the ssh config of the new worker.

@shinytang6  Yes, ssh config does not update.I didn't notice its effect, the ssh config is not used in my job. I am using volcano **/etc/volcano/*.host** files. 

> horovodrun -np 2 --min-np 1 --max-np 5 --host-discovery-script /code/discover_hosts.sh python main.py
./discover_hosts.sh
horovod-imagenet-job-worker1-0.horovod-imagenet-job:1
horovod-imagenet-job-worker1-1.horovod-imagenet-job:1
horovod-imagenet-job-worker2-0.horovod-imagenet-job:2
horovod-imagenet-job-worker2-1.horovod-imagenet-job:2

```bash
for hostFile in $(ls /etc/volcano/ | grep .host);do
    for line in $(cat /etc/volcano/$hostFile);do
        gpuNum=$(ssh -q -o StrictHostKeyChecking=no $line "ls /dev/nvidia* | grep "[0-9]$" | wc -l")
        if [ -n "$gpuNum" ];then
            echo "$line:$gpuNum"
        fi
    done
done
```

**Comment by shinytang6** [comment]
> > but the old workers will not update the ssh config of the new worker.
> 
> @shinytang6 Yes, ssh config does not update.I didn't notice its effect, the ssh config is not used in my job. I am using volcano **/etc/volcano/*.host** files.
> 
> > horovodrun -np 2 --min-np 1 --max-np 5 --host-discovery-script /code/discover_hosts.sh python main.py
> > ./discover_hosts.sh
> > horovod-imagenet-job-worker1-0.horovod-imagenet-job:1
> > horovod-imagenet-job-worker1-1.horovod-imagenet-job:1
> > horovod-imagenet-job-worker2-0.horovod-imagenet-job:2
> > horovod-imagenet-job-worker2-1.horovod-imagenet-job:2
> 
> ```shell
> for hostFile in $(ls /etc/volcano/ | grep .host);do
>     for line in $(cat /etc/volcano/$hostFile);do
>         gpuNum=$(ssh -q -o StrictHostKeyChecking=no $line "ls /dev/nvidia* | grep "[0-9]$" | wc -l")
>         if [ -n "$gpuNum" ];then
>             echo "$line:$gpuNum"
>         fi
>     done
> done
> ```

make sense. If you use it like this, there will be no problem because the configmap(/etc/volcano/*.host) will be updated when job updating.

**Comment by shinytang6** [comment]
> > but the old workers will not update the ssh config of the new worker.
> 
> @shinytang6 Yes, ssh config does not update.I didn't notice its effect, the ssh config is not used in my job. I am using volcano **/etc/volcano/*.host** files.
> 
> > horovodrun -np 2 --min-np 1 --max-np 5 --host-discovery-script /code/discover_hosts.sh python main.py
> > ./discover_hosts.sh
> > horovod-imagenet-job-worker1-0.horovod-imagenet-job:1
> > horovod-imagenet-job-worker1-1.horovod-imagenet-job:1
> > horovod-imagenet-job-worker2-0.horovod-imagenet-job:2
> > horovod-imagenet-job-worker2-1.horovod-imagenet-job:2
> 
> ```shell
> for hostFile in $(ls /etc/volcano/ | grep .host);do
>     for line in $(cat /etc/volcano/$hostFile);do
>         gpuNum=$(ssh -q -o StrictHostKeyChecking=no $line "ls /dev/nvidia* | grep "[0-9]$" | wc -l")
>         if [ -n "$gpuNum" ];then
>             echo "$line:$gpuNum"
>         fi
>     done
> done
> ```

@jingxiang95 could you make a pr for that? The current implementation seems to have more disadvantages than benefits.

**Comment by jingxiang95** [comment]
@shinytang6 How can I make pr? Submit an example of horovod elastic scaling?

**Comment by shinytang6** [comment]
> @shinytang6 How can I make pr? Submit an example of horovod elastic scaling?

l mean the modification you pasted:
```
func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {
	return nil
}
```

**Comment by jingxiang95** [comment]
> > @shinytang6 How can I make pr? Submit an example of horovod elastic scaling?
> 
> l mean the modification you pasted, and it's better to add some more comments of the reason why we skip here :)
> 
> ```
> // TODO: currently a container using a Secret as a subPath volume mount will not receive Secret updates.
> func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {
> 	data, err := generateRsaKey(job)
> 	if err != nil {
> 		return err
> 	}
> 	
> 	if err := helpers.CreateOrUpdateSecret(job, sp.client.KubeClients, data, sp.secretName(job)); err != nil {
> 		return fmt.Errorf("update secret for job <%s/%s> with ssh plugin failed for %v",
> 			job.Namespace, job.Name, err)
> 	}
> 
> 	return nil
> }
> ```

no,I don't see any positive impression of this code.

**Comment by shinytang6** [comment]
> > > @shinytang6 How can I make pr? Submit an example of horovod elastic scaling?
> > 
> > 
> > l mean the modification you pasted, and it's better to add some more comments of the reason why we skip here :)
> > ```
> > // TODO: currently a container using a Secret as a subPath volume mount will not receive Secret updates.
> > func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {
> > 	data, err := generateRsaKey(job)
> > 	if err != nil {
> > 		return err
> > 	}
> > 	
> > 	if err := helpers.CreateOrUpdateSecret(job, sp.client.KubeClients, data, sp.secretName(job)); err != nil {
> > 		return fmt.Errorf("update secret for job <%s/%s> with ssh plugin failed for %v",
> > 			job.Namespace, job.Name, err)
> > 	}
> > 
> > 	return nil
> > }
> > ```
> 
> no,I don't see any positive influence of this code.

Is there any misunderstanding? I mean to delete this block of code and add some comments

**Comment by jingxiang95** [comment]
之前提了一个pr是fork的volcano项目然后在master分支上修改的，还没有close。我现在不知道该怎么操作了。我本地已经重新编译过了，不会影响到我的使用。
```
// TODO: do nothing, until k8s support secret updates with subPath.
func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {

	return nil
}
```

**Comment by shinytang6** [comment]
> 之前提了一个pr是fork的volcano项目然后在master分支上修改的，还没有close。我现在不知道该怎么操作了。我本地已经重新编译过了，不会影响到我的使用。
> 
> ```
> // TODO: do nothing, until k8s support secret updates with subPath.
> func (sp *sshPlugin) OnJobUpdate(job *batch.Job) error {
> 
> 	return nil
> }
> ```

好的没事，那我来帮忙 fix 下吧

**Comment by jingxiang95** [comment]
好的，谢谢大佬。
