### ISSUE TITLE
怎么更改调度器的配置策略呢

### ISSUE THREAD

**Issue by winder-source** [volcano-sh/volcano#1424]
对于不同的任务我想要使用不同的调度策略，怎么去更改默认的调度策略呢(我是个新手，还不太会)
可以在不同的调度策略之间随意切换吗？怎么切换呢？还是说我可以在任务中指定相应的调度策略呢？

**Comment by william-wang** [comment]
1. Currently scheduling policy is cluster level.  The policy is working on all jobs. It is planed to support per-queue policy in future.
2. The scheduling policy is changed by editing scheduler configmap.  Please refer volcano website.
https://volcano.sh/zh/docs/schduler_introduction/
3. Can you explain  the scenario and background about using different policy for different job?

**Comment by winder-source** [comment]
好的谢谢您！
