### ISSUE TITLE
when one resource(GPU) is overused in queue, other resources (CPU) instances in the queue cannot be scheduled

### ISSUE THREAD

**Issue by hacker-qian** [volcano-sh/volcano#1425]
**What happened**: In volcano proportion plugin, when we run out of one resource (e.g. gpu-tesla-p4)，instances that use other resource (CPU, memory, dont use the gpu) also cannot be scheduled.

**What you expected to happen**:
CPU instance can be scheduled

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/6950081/115172128-23079d80-a0f7-11eb-87c4-92a3481313f6.png)

testcase:
1.创建p4类型gpu的负载，使该集群的p4类型的gpu耗尽

2.创建v100类型gpu的负载

3.创建cpu负载

预期结果
1.p4类型gpu耗尽，其余gpu有余

2.v100类型gpu的负载下pod调度成功

3.cpu负载下pod调度成功

实际结果
1.p4类型gpu耗尽，其余gpu有余

2.v100类型gpu的负载下pod调度失败，报集群资源不足

3.cpu负载下pod调度失败，报集群资源不足

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by william-wang** [comment]
The cause is similar with #1373.

**Comment by william-wang** [comment]
@shinytang6 please help to have a investigation.

**Comment by shinytang6** [comment]
The reason is when judging whether a queue is overused, as long as one kind of resource is overused, we consider the queue as overused. Then in allocate action, we will skip these overused queues.

It seems unreasonable indeed, but I did not think of a good solution, because our current implementation must select an available queue firstly before scheduling a job.

**Comment by Thor-wl** [comment]
@hudson741 It seems to be the problem we have discussed.

**Comment by Thor-wl** [comment]
If cpu or memory is oversued, no later jobs should be added into the queue for any job must request cpu or memory to run. If scalable resources are overused such as GPU, later jobs only requesting cpu and memory can still be added into the queue. So i think we should add the logic.
