### ISSUE TITLE
volcano job was terminating when volcano clustrer was deleted

### ISSUE THREAD

**Issue by ldd91** [volcano-sh/volcano#1438]
**What happened**:
I exec kubectl delete -f  volcano.yaml in my kubernetes platform,However all vcjobs in all namespace  was deleted.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:1.1.2
- Kubernetes version (use `kubectl version`):1.15.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ldd91** [comment]
![微信图片_20210426095644](https://user-images.githubusercontent.com/29392150/116019099-0aa6fe00-a676-11eb-9940-e26a7adfcfb3.png)
![微信图片_20210426095708](https://user-images.githubusercontent.com/29392150/116019104-0c70c180-a676-11eb-96df-ece4d54e663d.png)
![微信图片_20210426095714](https://user-images.githubusercontent.com/29392150/116019112-0ed31b80-a676-11eb-87c6-2b8bd6dd97b5.png)

**Comment by huone1** [comment]
is the volcano job CRD  "jobs.batch.volcano.sh" deleted？？？

**Comment by ldd91** [comment]
@huone1  Yes,It was deleted

**Comment by huone1** [comment]
> @huone1 Yes,It was deleted

so it is right to delete the test-job because the pod is the CR object of the CRD "jobs.batch.volcano.sh" .

it is no problem.

**Comment by ldd91** [comment]
Thanks,So if we want to upgrade version of volcano  we should not delete CRD
