### ISSUE TITLE
【summer2021】Support specify GPU number for pod resource request

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#1440]
Currently, Volcano only support specified GPU share memory. Specified GPU number is not supported. Your task is to support 'volcano.sh/gpu-number' just like nvidia gpu plugin to support specify GPU number for pod resource request. You can refer to https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_gpu_sharing.md for more details.

Notes:
* These are competitions set for Summer2021. The Summer2021 official website: https://summer.iscas.ac.cn/
* Anyone who satisfies the requirement of the activity can submit application for the competition you are interested in. Please remind that the activity is only for college and graduate students. More details please refer to https://summer.iscas.ac.cn/help/student/
* The schedule of the activity refers to https://summer.iscas.ac.cn/help/timeline/

**Comment by ChAnYaNG97** [comment]
Hi, I am interested in this issue. I have sent my resume and basic introduction to @Thor-wl @william-wang by e-mail.
Now I am working on the design and plan and will send in the near future.

**Comment by Thor-wl** [comment]
> Hi, I am interested in this issue. I have sent my resume and basic introduction to @Thor-wl @william-wang by e-mail.
> Now I am working on the design and plan and will send in the near future.

I've received your resume. Thanks!
