### ISSUE TITLE
CRD validation error

### ISSUE THREAD

**Issue by pangbingqiang1** [volcano-sh/volcano#1445]
**What happened**:
The CustomResourceDefinition "jobs.batch.volcano.sh" is invalid:
![截图](https://user-images.githubusercontent.com/48078129/116209601-aae34c80-a774-11eb-9e58-b2b255e1f52d.PNG)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`): 1.18.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Thank you for your report. We've already discovered this bug recently. Bug fix is on the way.

**Comment by huone1** [comment]
fix it in PR #1446

**Comment by huone1** [comment]
you can resolve it by  “make update-development-yaml CRD_VERSION=v1”  to  updating volcano-development.yaml

**Comment by Thor-wl** [comment]
This bug is fixed and close this issue.
