### ISSUE TITLE
[feature] enable gang-scheduler for workloads.

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#1454]
#### What would you like to be added:

When a new workload is created, it is converted to a podgroup to make it scheduled by gang-scheduler

The way it can be done: identify workloads with special annotations added.

#### Why is this needed:

making the scheduling method more flexible. Conform to user habits.

**Comment by Thor-wl** [comment]
Do you mean only scheduling workloads with specify annotation in gang-scheduleing while scheduling other workloads with another scheduling algorithm?

**Comment by hwdef** [comment]
What I want to achieve is, When I deploy a workload(like deployment), the pods in workload will be scheduled according to Gang-Scheduler. The method I can think is to establish it with Podgroup.

Does Volcano have such a function ?

**Comment by Thor-wl** [comment]
> What I want to achieve is, When I deploy a workload(like deployment), the pods in workload will be scheduled according to Gang-Scheduler. The method I can think is to establish it with Podgroup.
> 
> Does Volcano have such a function ?

Can you provide the scenario? Why do you need to deploy a deployment with Gang-sheduling?

**Comment by hwdef** [comment]
I just want to comply with the user's usage habits. Users may get used to creating deployments, but is not familiar with Task in vcjob.

**Comment by Thor-wl** [comment]
Well, as far as we can see now, if users create deployments with volcano, they just need to define the deployment with `schedulerName: Volcano` without concern about what scheduling algorithms used behind.

**Comment by hwdef** [comment]
In this case, can I use the function of vcjob or podgroup?Such as gang-scheduler ,priorityClassName.

**Comment by hwdef** [comment]
I try to deploy a deployment with `schedulerName: Volcano`, I found it create a podgroup for this deployment, but this podgroup does not have a queue.What can I have to specify queue for it?

And I found some unsuitable log output. 
![image](https://user-images.githubusercontent.com/13084946/117404305-49716980-af3c-11eb-9307-1c000905b267.png)

It seems that there is a problem with the logic here
![image](https://user-images.githubusercontent.com/13084946/117404347-627a1a80-af3c-11eb-9340-e897d5f5405d.png)

**Comment by shinytang6** [comment]
> I try to deploy a deployment with `schedulerName: Volcano`, I found it create a podgroup for this deployment, but this podgroup does not have a queue.What can I have to specify queue for it?
> 
> And I found some unsuitable log output.
> ![image](https://user-images.githubusercontent.com/13084946/117404305-49716980-af3c-11eb-9307-1c000905b267.png)
> 
> It seems that there is a problem with the logic here
> ![image](https://user-images.githubusercontent.com/13084946/117404347-627a1a80-af3c-11eb-9340-e897d5f5405d.png)

The default queue should be `default`, does it created in the cluster?

**Comment by hwdef** [comment]
![image](https://user-images.githubusercontent.com/13084946/117408187-277ae580-af42-11eb-8cea-9dd60160d923.png)

@shinytang6 yes, I have it.

**Comment by hwdef** [comment]
```yaml
[centos@master volcano-demo]$ kubectl get pg podgroup-8a45e77c-5802-42f7-9047-302eb5eccd79 -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2021-05-07T05:53:28Z"
  generation: 3
  name: podgroup-8a45e77c-5802-42f7-9047-302eb5eccd79
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: deploy-with-volcano-64d577d6b9
    uid: 8a45e77c-5802-42f7-9047-302eb5eccd79
  resourceVersion: "2205060"
  uid: 2512499e-1178-4e95-9923-a8facfbfc309
spec:
  minMember: 1
status:
  conditions:
  - lastTransitionTime: "2021-05-07T05:53:23Z"
    reason: tasks in gang are ready to be scheduled
    status: "True"
    transitionID: 8fac2517-7fc2-4f09-b512-a50029b3ed73
    type: Scheduled
  phase: Running
  running: 1
```

```yaml
[centos@master volcano-demo]$ kubectl get deploy deploy-with-volcano -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"volcano.sh/queue-name":"demo"},"labels":{"app":"nginx"},"name":"deploy-with-volcano","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:latest","name":"nginx","ports":[{"containerPort":80}]}],"schedulerName":"volcano"}}}}
    volcano.sh/queue-name: demo
  creationTimestamp: "2021-05-07T05:53:28Z"
  generation: 1
  labels:
    app: nginx
  name: deploy-with-volcano
  namespace: default
  resourceVersion: "2205052"
  uid: 57b0e3e4-9dde-4eb2-833e-6c970b575b9c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: volcano
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-05-07T05:53:34Z"
    lastUpdateTime: "2021-05-07T05:53:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-05-07T05:53:28Z"
    lastUpdateTime: "2021-05-07T05:53:34Z"
    message: ReplicaSet "deploy-with-volcano-64d577d6b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

The above is the detailed information of deployment and podgroup, I tried to specify the queue in the annotation in deployment, it seems to have no effect

**Comment by shinytang6** [comment]
> ```yaml
> [centos@master volcano-demo]$ kubectl get pg podgroup-8a45e77c-5802-42f7-9047-302eb5eccd79 -o yaml
> apiVersion: scheduling.volcano.sh/v1beta1
> kind: PodGroup
> metadata:
>   creationTimestamp: "2021-05-07T05:53:28Z"
>   generation: 3
>   name: podgroup-8a45e77c-5802-42f7-9047-302eb5eccd79
>   namespace: default
>   ownerReferences:
>   - apiVersion: apps/v1
>     blockOwnerDeletion: true
>     controller: true
>     kind: ReplicaSet
>     name: deploy-with-volcano-64d577d6b9
>     uid: 8a45e77c-5802-42f7-9047-302eb5eccd79
>   resourceVersion: "2205060"
>   uid: 2512499e-1178-4e95-9923-a8facfbfc309
> spec:
>   minMember: 1
> status:
>   conditions:
>   - lastTransitionTime: "2021-05-07T05:53:23Z"
>     reason: tasks in gang are ready to be scheduled
>     status: "True"
>     transitionID: 8fac2517-7fc2-4f09-b512-a50029b3ed73
>     type: Scheduled
>   phase: Running
>   running: 1
> ```
> 
> ```yaml
> [centos@master volcano-demo]$ kubectl get deploy deploy-with-volcano -o yaml
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   annotations:
>     deployment.kubernetes.io/revision: "1"
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"volcano.sh/queue-name":"demo"},"labels":{"app":"nginx"},"name":"deploy-with-volcano","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:latest","name":"nginx","ports":[{"containerPort":80}]}],"schedulerName":"volcano"}}}}
>     volcano.sh/queue-name: demo
>   creationTimestamp: "2021-05-07T05:53:28Z"
>   generation: 1
>   labels:
>     app: nginx
>   name: deploy-with-volcano
>   namespace: default
>   resourceVersion: "2205052"
>   uid: 57b0e3e4-9dde-4eb2-833e-6c970b575b9c
> spec:
>   progressDeadlineSeconds: 600
>   replicas: 1
>   revisionHistoryLimit: 10
>   selector:
>     matchLabels:
>       app: nginx
>   strategy:
>     rollingUpdate:
>       maxSurge: 25%
>       maxUnavailable: 25%
>     type: RollingUpdate
>   template:
>     metadata:
>       creationTimestamp: null
>       labels:
>         app: nginx
>     spec:
>       containers:
>       - image: nginx:latest
>         imagePullPolicy: Always
>         name: nginx
>         ports:
>         - containerPort: 80
>           protocol: TCP
>         resources: {}
>         terminationMessagePath: /dev/termination-log
>         terminationMessagePolicy: File
>       dnsPolicy: ClusterFirst
>       restartPolicy: Always
>       schedulerName: volcano
>       securityContext: {}
>       terminationGracePeriodSeconds: 30
> status:
>   availableReplicas: 1
>   conditions:
>   - lastTransitionTime: "2021-05-07T05:53:34Z"
>     lastUpdateTime: "2021-05-07T05:53:34Z"
>     message: Deployment has minimum availability.
>     reason: MinimumReplicasAvailable
>     status: "True"
>     type: Available
>   - lastTransitionTime: "2021-05-07T05:53:28Z"
>     lastUpdateTime: "2021-05-07T05:53:34Z"
>     message: ReplicaSet "deploy-with-volcano-64d577d6b9" has successfully progressed.
>     reason: NewReplicaSetAvailable
>     status: "True"
>     type: Progressing
>   observedGeneration: 1
>   readyReplicas: 1
>   replicas: 1
>   updatedReplicas: 1
> ```
> 
> The above is the detailed information of deployment and podgroup, I tried to specify the queue in the annotation in deployment, it seems to have no effect

is the deployment running? I remember that the created pg will set the default queue by default when scheduling, but it will not be reflected in pg.spec, but normally it will not affect the scheduling.

**Comment by hwdef** [comment]
![image](https://user-images.githubusercontent.com/13084946/117410667-5181d700-af45-11eb-8c72-996f49125b44.png)

yes, it is running. I want to know, using the podgroup created in this way, can it use vcjob capabilities, such as specified queue and priority?

**Comment by hwdef** [comment]
![image](https://user-images.githubusercontent.com/13084946/117418384-ef799f80-af4d-11eb-95e1-580d95acb975.png)

I seem to find what I want in the code, thank you very much!😃😃
@shinytang6  @Thor-wl

**Comment by hwdef** [comment]
I found some missing annotation.
podgroup has four key fields. Now there is only one field `queueName` in the code,  should we add `minMember`, `priorityClassName`, and `minResources`. 

If need help, I can add these codes and submit PR.

**Comment by Thor-wl** [comment]
> I found some missing annotation.
> podgroup has four key fields. Now there is only one field `queueName` in the code, should we add `minMember`, `priorityClassName`, and `minResources`.
> 
> If need help, I can add these codes and submit PR.
> 
> @shinytang6 @Thor-wl

I'm sorry for not understanding. Where do you think we should add these annotations?

**Comment by Thor-wl** [comment]
> @Thor-wl
> It may be that I misunderstood the function of this piece of code, sorry.
> I thought the logic of this code was that I created a workload(deployment), specified the `schedulerName: Volcano`, and volcano would generate a podgroup for the deployment. So, now I can specify queue for podgroup by deployment `spec.template.metadata.annotations`, but I can't specify minMember, minResource, priorityClassName.
> 
> But after I tested this code, I found that the code doesn't seem to be for this function...The podgroup created by this code does not seem to be intercepted by the webhook, and the podgroup will be scheduled even if the queue is closed, or if the queue is low on resources...
> 
> Sorry to bother you with these questions.

That's all right.
