### ISSUE TITLE
A feasible way to modify CRDs in plugins or actions?

### ISSUE THREAD

**Issue by yzs981130** [volcano-sh/volcano#1455]
#### What would you like to be added:
Is there a feasible way to modify CRDs (e.g. volcano batch jobs/volcano podGroups) in plugins or actions? 

I believe that if only `jobInfo.PodGroup` is updated in actions or plugins, it will not be populated to Kubernetes.
#### Why is this needed:

Some scheduling results are needed to be added as something like annotation or spec to objects (e.g. vcJob/PodGroup/Pod) in Kubernetes, which can be only determined in actions/plugins. I found that the GPU share plugin also need this feature, and it utilizes the `ssn.Kubeclient` and updates pod spec in the plugin: 
https://github.com/volcano-sh/volcano/blob/364ac9e26e8b68686ceec26f65e8d0776a73b75e/pkg/scheduler/plugins/predicates/predicates.go#L126

I suppose that a feasible way to update other CRDs controlled by volcano in plugins/actions is also reasonable.

**Comment by shinytang6** [comment]
> #### What would you like to be added:
> Is there a feasible way to modify CRDs (e.g. volcano batch jobs/volcano podGroups) in plugins or actions?
> 
> I believe that if only `jobInfo.PodGroup` is updated in actions or plugins, it will not be populated to Kubernetes.
> 
> #### Why is this needed:
> Some scheduling results are needed to be added as something like annotation or spec to objects (e.g. vcJob/PodGroup/Pod) in Kubernetes, which can be only determined in actions/plugins. I found that the GPU share plugin also need this feature, and it utilizes the `ssn.Kubeclient` and updates pod spec in the plugin:
> https://github.com/volcano-sh/volcano/blob/364ac9e26e8b68686ceec26f65e8d0776a73b75e/pkg/scheduler/plugins/predicates/predicates.go#L126
> 
> I suppose that a feasible way to update other CRDs controlled by volcano in plugins/actions is also reasonable.

Not sure if l understand your question, usually like you said, we can use kubeclient to interact with apiserver to update the k8s resource information.

**Comment by ChAnYaNG97** [comment]
> #### What would you like to be added:
> Is there a feasible way to modify CRDs (e.g. volcano batch jobs/volcano podGroups) in plugins or actions?
> 
> I believe that if only `jobInfo.PodGroup` is updated in actions or plugins, it will not be populated to Kubernetes.
> 
> #### Why is this needed:
> Some scheduling results are needed to be added as something like annotation or spec to objects (e.g. vcJob/PodGroup/Pod) in Kubernetes, which can be only determined in actions/plugins. I found that the GPU share plugin also need this feature, and it utilizes the `ssn.Kubeclient` and updates pod spec in the plugin:
> https://github.com/volcano-sh/volcano/blob/364ac9e26e8b68686ceec26f65e8d0776a73b75e/pkg/scheduler/plugins/predicates/predicates.go#L126
> 
> I suppose that a feasible way to update other CRDs controlled by volcano in plugins/actions is also reasonable.

Maybe `vcClient` in `SchedulerCache` is what you need?

**Comment by yzs981130** [comment]
> > #### What would you like to be added:
> > Is there a feasible way to modify CRDs (e.g. volcano batch jobs/volcano podGroups) in plugins or actions?
> > I believe that if only `jobInfo.PodGroup` is updated in actions or plugins, it will not be populated to Kubernetes.
> > #### Why is this needed:
> > Some scheduling results are needed to be added as something like annotation or spec to objects (e.g. vcJob/PodGroup/Pod) in Kubernetes, which can be only determined in actions/plugins. I found that the GPU share plugin also need this feature, and it utilizes the `ssn.Kubeclient` and updates pod spec in the plugin:
> > https://github.com/volcano-sh/volcano/blob/364ac9e26e8b68686ceec26f65e8d0776a73b75e/pkg/scheduler/plugins/predicates/predicates.go#L126
> > 
> > I suppose that a feasible way to update other CRDs controlled by volcano in plugins/actions is also reasonable.
> 
> Not sure if l understand your question, usually like you said, we can use kubeclient to interact with apiserver to update the k8s resource information.

In short, I'm looking forward to having a `ssn.vcClient` for `Session`, just like the `ssn.kubeClient`, in order to control vcJobs/PodGroups in plugins/actions.

**Comment by yzs981130** [comment]
> > #### What would you like to be added:
> > Is there a feasible way to modify CRDs (e.g. volcano batch jobs/volcano podGroups) in plugins or actions?
> > I believe that if only `jobInfo.PodGroup` is updated in actions or plugins, it will not be populated to Kubernetes.
> > #### Why is this needed:
> > Some scheduling results are needed to be added as something like annotation or spec to objects (e.g. vcJob/PodGroup/Pod) in Kubernetes, which can be only determined in actions/plugins. I found that the GPU share plugin also need this feature, and it utilizes the `ssn.Kubeclient` and updates pod spec in the plugin:
> > https://github.com/volcano-sh/volcano/blob/364ac9e26e8b68686ceec26f65e8d0776a73b75e/pkg/scheduler/plugins/predicates/predicates.go#L126
> > 
> > I suppose that a feasible way to update other CRDs controlled by volcano in plugins/actions is also reasonable.
> 
> Maybe `vcClient` in `SchedulerCache` is what you need?

Sure it is. 

I wonder if there are other elegant but feasible ways under current design or any plans to add a `ssn.vcClient` for `Session` from `SchedulerCache`. I will send a pr if the latter is better.
