### ISSUE TITLE
运行tensorlflow例子时出现问题

### ISSUE THREAD

**Issue by winder-source** [volcano-sh/volcano#1456]
您好，我在使用volcano运行tensorflow案例的时候，出现了一点问题，
我用的例子是volcano/example/integrations/tensorflow/dist-mnist/tf-dist-mnist-example.yaml这个例子。
它的三个pod都能够成功run起来，如图：
![image](https://user-images.githubusercontent.com/54299847/117394840-7e27f580-af29-11eb-9fd6-ada4eac9ba16.png)
但是在查看pod日志的时候，显示了几个warning，read_data_sets等几个函数被弃用了，所以看不见模型训练时的相关数据信息了。
![image](https://user-images.githubusercontent.com/54299847/117394616-0c4fac00-af29-11eb-8829-bb77fb901b8b.png)
请问，我应该怎么去解决这个问题呢？

**Comment by shinytang6** [comment]
@Thor-wl Is there any places for the dockerfile in the example in our project?

**Comment by Thor-wl** [comment]
> @Thor-wl Is there any places for the dockerfile in the example in our project?

I'm sorry for not find the dockerfile.

**Comment by Thor-wl** [comment]
@renhuanyu Please take a look as well.
