### ISSUE TITLE
no matches for kind "CronJob" in version "batch.volcano.sh/v1alpha1"

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1458]
maybe a bug

**What happened**:
When I apply CronJob as [issue](https://github.com/volcano-sh/volcano/pull/47), I get the flowing result:
![image](https://user-images.githubusercontent.com/7522079/117446070-252e8080-af6e-11eb-9c4d-536467a036df.png)

**What you expected to happen**:
Run the CronJob

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.2.0
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 18.06
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
Currently volcano does not support this cr , but I think this feature is quite interesting 🤔

**Comment by Thor-wl** [comment]
Why not use CornJob in "batch/v1beta1"?

**Comment by zishen** [comment]
> Currently volcano does not support this cr , but I think this feature is quite interesting 🤔

yes, I get the same error, when apply the "volcano-monitoring     kube-state-metrics".

![image](https://user-images.githubusercontent.com/7522079/117522965-d1ad4880-afe8-11eb-8a65-0efc3a965698.png)

**Comment by Thor-wl** [comment]
Got it. Thanks for the report.
/assign @Thor-wl

**Comment by liz1989** [comment]
still no cronjob. Do I need to use "batch/v1beta1" CronJob？If so, does gang scheduler work?
