### ISSUE TITLE
Queue cannot reclaim resource

### ISSUE THREAD

**Issue by ldd91** [volcano-sh/volcano#1461]
**What happened**:
In our test scenario,there  are 10 GPUs in our cluster.I create a queue name test (weight:3  Capability:nvidia.com/gpu:  10    Reclaimable:  true),so there are two queue total,one is test,another is default.
I create 4 podgroups:
* job-1(belonq to queue:test)
*  job-2(belonq to  queue:test)
*  job-default(belonq to queue:default)
*  job-default-2（belonq to queue:default）

Then I create 4 vcjobs in the following order:
 (1) job-default（use PodGroup: job-default，request  2 GPUs）-----------> Running
 (2) job-default-2 (use PodGroup: job-default-2，request  2 GPUs）-----------> Running
 (3) job-1 (use PodGroup: job-1，request  3 GPUs）-----------> Running
 (4) job-2 (use PodGroup: job-2，request  3 GPUs）-----------> Pending

**What you expected to happen**:
job-2 should reclaim GPUs in default queue

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.2.0
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`): Linux version 3.10.0-1127.13.1.el7.x86_64
- Install tools: deployment.yaml
- Others:

**Comment by ldd91** [comment]
![1](https://user-images.githubusercontent.com/29392150/117646490-674e0100-b1be-11eb-8ba2-c3826aa0ccf5.png)
![2](https://user-images.githubusercontent.com/29392150/117646497-687f2e00-b1be-11eb-97d6-c0f35018163d.png)
![3](https://user-images.githubusercontent.com/29392150/117646502-6ae18800-b1be-11eb-8da1-b412cedc360d.png)

**Comment by ldd91** [comment]
@Thor-wl  What is the progress of this issue

**Comment by Thor-wl** [comment]
> @Thor-wl What is the progress of this issue
Can you provide more information about the nodes and GPU distribution?

**Comment by Thor-wl** [comment]
I think it is the same reason with https://github.com/volcano-sh/volcano/issues/1485

**Comment by Thor-wl** [comment]
fix: https://github.com/volcano-sh/volcano/pull/1550

**Comment by ldd91** [comment]
Thank you,i will have a look
