### ISSUE TITLE
Preemption storm of low-priority pods when using hierarchical queues with pending high-priority pods

### ISSUE THREAD

**Issue by Robert-Christensen-visa** [volcano-sh/volcano#1464]
**What happened**:
When using preemption and hierarchical queues, higher priority jobs can a preemption storm of low priority jobs under the right conditions.  This results in the low-priority jobs getting preempted as they start.  The low-priority jobs will be in this preemption storm until no high-priority jobs are queued.

**What you expected to happen**:
I would expect if a high-priority job preempts a low-priority job, it should only do so if the high-priority job will run after the low priority job finishes terminating.  I would expect if the high-priority job can't run, it should not preempt low-priority jobs

**How to reproduce it (as minimally and precisely as possible)**:

When using preemption and hierarchical queues, higher-priority jobs can cause a preemption storm of low-priority jobs under the right conditions.  The following code does the following.

1) Create a high-priority and low-priority priorityClass.
2) Create an "A" and "B" queue, where "A" and "B" queues have equal weight using hierarchical queues, so if there are many jobs half the resources will be used by each queue.
3) Submit several low-priority jobs that use "A" queue.
4) Sleep for several seconds to allow the jobs to start running.
5) Submit several "high-priority" jobs to the "B" queue.

What I expect should happen when this is done is several low-priority jobs in the small queue will be preempted and high-priority jobs will start.  Since the queues are setup such that each queue will have equal weight, I would expect when things stabilize half of the running jobs will be from "A" queue and half will be from the "B" queue.

What happens is if there exists a pending high-priority job in the "B" queue, it will preempt the running jobs from the "A" queue, but the pending jobs in the "B" queue will not start.  The scheduler tries to schedule a low-priority job from the "A" queue, but once the job begins it is quickly preempted because there exists a pending high-priority job.  This causes a preemption storm.  In this situation, nothing in the "A" queue will be able to run as long as a high-priority job is queued in the "B" queue.

To run this test, I have a job_template file and a script to use the template to launch several vcjobs

job_template.json
``` json
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob-job-<id>
spec:
  minAvailable: 1
  priorityClassName: <priority>
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 5
  queue: <queue>
  tasks:
    - replicas: 1
      name: "x"
      template:
        metadata:
          name: core
        spec:
          containers:
            - image: ubuntu
              imagePullPolicy: IfNotPresent
              name: ubuntu
              command: ['sh', '-c', "sleep 120"]
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure
```

This is the script I use to setup the cluster and run the jobs:

``` bash
# create priorityclass
cat <<EOF | kubectl apply -f -
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
EOF

# create queues
cat <<EOF | kubectl apply -f -
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: a-queue
  annotations:
    "volcano.sh/hierarchy": "root/dev/p"
    "volcano.sh/hierarchy-weights": "1/1/5"
spec:
  weight: 1
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: b-queue
  annotations:
    "volcano.sh/hierarchy": "root/dev/d"
    "volcano.sh/hierarchy-weights": "1/1/5"
spec:
  weight: 1
EOF

TEMP_FILE=$(mktemp)

# launch low priority jobs
for id in $(seq 8)
do
    sed 's/<queue>/a-queue/g' < job_template.json | \
    sed "s/<id>/slow-$id/g" | \
    sed "s/<priority>/low-priority/g" | \
    kubectl apply -f -
done

sleep 10

# launch high priority jobs
for id in $(seq 8)
do
    sed 's/<queue>/b-queue/g' < job_template.json | \
    sed "s/<id>/fast-$id/g" | \
    sed "s/<priority>/high-priority/g" | \
    kubectl apply -f -
done
```

The configmap I am using for my volcano scheduler:

``` json
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, reclaim, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
        enableHierarchy: true
      - name: predicates
      - name: nodeorder
      - name: binpack
kind: ConfigMap
```

**Anything else we need to know?**:
It is important that the enough jobs are submitted that some high-priority jobs are queued.  In my case, my local kubernetes cluster has 10CPUs and 6GB memory.  If I had more resources I may need to increase the number of jobs launched by the script to make sure not all the pods can be running at the same time.

I found the issue when using hierarchical queues, but this issue might also be present between non-hierarchical queues.

**Environment**:
- Volcano Version: 1.2.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: running using docker with kubernetes on mac.
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: This experiment was done on my local mac machine.  This issue can be replicated on other systems though.  It is not specific to the hardware used.

**Comment by k82cn** [comment]
/assign @wpeng102 

please help on this issue.

**Comment by wpeng102** [comment]
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, reclaim, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
        enableHierarchy: true
      - name: predicates
      - name: nodeorder
      - name: binpack
kind: ConfigMap
```
For the above config, when high-priority job pending, in `reclaim` action `gang` plugin will trigger  high-priority job reclaim low-priority job. But when next scheduling period, `allocate` action will select a low-priority pending pod to dispatch. 

So, should config `drf` plugin in tier1(same tier with gang), then both `gang` and `drf` plugin will make `reclaim` decision togather. 

```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, reclaim, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
      - name: drf
        enableHierarchy: true
    - plugins:
      - name: predicates
      - name: nodeorder
      - name: binpack
kind: ConfigMap
```

**Comment by Robert-Christensen-visa** [comment]
That seems to resolve the issue.  Placing both drf and gang plugins in the same tier will prevent a preemption storm from taking place and will result in expected behavior.

Thanks for your help!
