### ISSUE TITLE
args for volcano to connect k8s

### ISSUE THREAD

**Issue by hudson741** [volcano-sh/volcano#1465]
**What happened**:
volcano call  client-go  slow

**What you expected to happen**:
volcano call client-go to connect to k8s should be fast 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
args in  cmd/sheduler/app/options/options  in default 
	defaultQPS   = 50.0
	defaultBurst = 100
should be bigger like 
        defaultQPS   = 2000.0
	defaultBurst = 2000

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
+1

**Comment by Thor-wl** [comment]
These parameters can be configured at the command when starting scheduler. Users can adjust them to custom scenarios.

**Comment by Thor-wl** [comment]
As the discussion of the community weekly meeting, we will do that.

**Comment by Thor-wl** [comment]
fix: https://github.com/volcano-sh/volcano/pull/1480
