### ISSUE TITLE
possible to disable default queue

### ISSUE THREAD

**Issue by nolimitkun** [volcano-sh/volcano#1467]
#### What would you like to be added:
possible to modify/disable default queue

#### Why is this needed:
suppose several team work in same cluster, each team use one queue . so nobody should use default queue.
that's why volcano should give possibility to modify weight/capacity queue even disable it.

**Comment by Thor-wl** [comment]
IC, so what you need is the ability of closing default queue, right?

**Comment by Thor-wl** [comment]
If default queue can be closed, what if someone submit a job without queue filed?

**Comment by nolimitkun** [comment]
in this case, scheduler refuse this job and tell user to mention a queue name, user should always be aware of which queue his is using in administrator point of view. otherwise, nobody will really care about control of resource until queue full.

**Comment by nolimitkun** [comment]
default queue could be modify, change title.

**Comment by wpeng102** [comment]
you can build `vcctl` from volcano code and try `vcctl queue operate queue -n default -a close` command to close `default` queue

```
[root@wangpeng yaml]# vcctl queue list
Name                     Weight  State   Inqueue Pending Running Unknown 
default                  1       Closed  0       0       0       0       
queue1                   1       Open    0       0       0       0       
queue2                   1       Closed  0       1       0       0       
queue4                   1       Open    0       0       0       0       
queue7                   1       Open    0       0       0       0       
test                     1       Open    0       0       0       0  
```

**Comment by nolimitkun** [comment]
Yes, exactly what I need , it works.
```
Error from server: error when creating "vcjob2.yaml": admission webhook "validatejob.volcano.sh" denied the request: can only submit job to queue with state `Open`, queue `default` status is `Closed`
```
Thank you
Maybe we should add this in doc or somewhere?

**Comment by wpeng102** [comment]
> Yes, exactly what I need , it works.
> 
> ```
> Error from server: error when creating "vcjob2.yaml": admission webhook "validatejob.volcano.sh" denied the request: can only submit job to queue with state `Open`, queue `default` status is `Closed`
> ```
> 
> Thank you
> Maybe we should add this in doc or somewhere?

Sure, @Thor-wl maybe we need add more CLI usage for https://volcano.sh/en/docs/cli/

**Comment by Thor-wl** [comment]
@wpeng102 Yes, @renhuanyu is working on that.
