### ISSUE TITLE
How to bypass VolcanoJob to use Volcano scheduler directly.

### ISSUE THREAD

**Issue by umialpha** [volcano-sh/volcano#1469]
Hello there, the Volcano scheduler is great for batch workload, but how to use it directly without VolcanoJob.

Here is our scenario,

We have our own job definition out of k8s, each time a job is added, we translate it to a group of pods and submit them to the k8s. ( We may make it k8s-native later). W . e don't want to introduce another job definition, just want to leverage the scheduler's features.

**Comment by shinytang6** [comment]
You need to create a podGroup for each of your jobs, you can refer to the implementation of tf-operator

**Comment by umialpha** [comment]
@shinytang6 , thx for your reply. Yeah, I am reading tf-operator's implementation now. Also, i am reading volcano scheduler's implementation. It would be helpful if someone could give me an example.

**Comment by umialpha** [comment]
@shinytang6, from my inspectation, there are some Inconsistency in volcano scheduler. 
e.g.
When a pod is added, the scheduler tries to createOrUpdate a JobInfo from the `pod.Annnotations[v1beta1.KubeGrupNameAnnotationKey]`, but when a PodGroup is added, the scheduler tries to link it to a JobInfo by `schedulingapi.JobID(fmt.Sprintf("%s/%s", pg.Namespace, pg.Name))` .

**Comment by shinytang6** [comment]
Simply put, you need to create a podgroup for your job. Volcano will check the podgroup to determine whether it can start scheduling pods. The combination of tf-operator and volcano is achieved by creating pg

**Comment by Thor-wl** [comment]
Agree with @shinytang6 's ideas. Another solution is to develop a translater which can swtich your CRD job to VCjob according to the API automatically.

**Comment by shinytang6** [comment]
> @shinytang6, from my inspectation, there are some Inconsistency in volcano scheduler.
> e.g.
> When a pod is added, the scheduler tries to createOrUpdate a JobInfo from the `pod.Annnotations[v1beta1.KubeGrupNameAnnotationKey]`, but when a PodGroup is added, the scheduler tries to link it to a JobInfo by `schedulingapi.JobID(fmt.Sprintf("%s/%s", pg.Namespace, pg.Name))` .

do you mean JobID? `v1beta1.KubeGroupNameAnnotationKey` should be the same with pg.Name in your scenes.
