### ISSUE TITLE
volcano  queue  api in master branch 

### ISSUE THREAD

**Issue by hudson741** [volcano-sh/volcano#1470]
**What happened**:

I am working with the queue reserved  feather . and getting to merge it in master branch. please  merge the queue attribute like:
queue.Spec.Guarantee  and  QueueStatus.Reservation  to the master branch. 

type QueueSpec struct {
	Weight     int32
	Capability v1.ResourceList

	// Depreicated: replaced by status.State
	State QueueState
	// Reclaimable indicate whether the queue can be reclaimed by other queue
	Reclaimable *bool
	// Guarantee indicate the queue's Guarantee resource.
	Guarantee  v1.ResourceList

}

// QueueStatus represents the status of Queue.
type QueueStatus struct {
	// State is status of queue
	State QueueState

	Reservation ReservationStatus
	// The number of 'Unknown' PodGroup in this queue.
	Unknown int32
	// The number of 'Pending' PodGroup in this queue.
	Pending int32
	// The number of 'Running' PodGroup in this queue.
	Running int32
	// The number of `Inqueue` PodGroup in this queue.
	Inqueue int32
}

// ReservationStatus represents the status of the reservation
type ReservationStatus struct {
	Nodes		 []string
}

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
As the discussion in the community weekly meeting, we will follow K8s API management and add stagging folder
