### ISSUE TITLE
【summer2021】Investigation about GPU Topology Awareness

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#1472]
Description:
Your task is to take an investigation about existing design and implementation of GPU topology awareness, output the report and give the design about how to achieve it for Volcano.

Notes:
* These are competitions set for Summer2021. The Summer2021 official website: https://summer.iscas.ac.cn/
* Anyone who satisfies the requirement of the activity can submit application for the competition you are interested in. Please remind that the activity is only for college and graduate students. More details please refer to https://summer.iscas.ac.cn/help/student/
* The schedule of the activity refers to https://summer.iscas.ac.cn/help/timeline/

**Comment by shinytang6** [comment]
Let's record progress here.
/cc @muyu-dev

**Comment by muyu-dev** [comment]
ok, working on it.

**Comment by muyu-dev** [comment]
> Let's record progress here.
> /cc @muyu-dev
OK, working on it.

**Comment by muyu-dev** [comment]
Firstly start with device plugin

**Comment by muyu-dev** [comment]
Firstly start with device plugin

**Comment by muyu-dev** [comment]
> Firstly start with device plugin
![plugin device](https://user-images.githubusercontent.com/84866251/124778888-e91a9a80-df73-11eb-9de4-bccf71c4a270.png)
