### ISSUE TITLE
Proposal for the performance testing

### ISSUE THREAD

**Issue by rudeigerc** [volcano-sh/volcano#1479]
Related to #1284 

According to the roadmap, the community would like to introduce performance testing for enhance the stability of Volcano scheduler. The issue is for tracking and discussion.

## Proposal

The initial proposal of the performance testing is to refer to the [scheduler performance framework](https://github.com/kubernetes/kubernetes/tree/master/test/integration/scheduler_perf) of Kubernetes. 

Although Kubemark has been introduced to evaluate the performance of Kubernetes cluster with hollow nodes, it requires setting up and bootstrapping the whole Kubernetes cluster. As a result, the framework mentioned above is designed to cooperate with the integration testing framework of Kubernetes and provide a *lightweight* solution to evaluate the performance of kube-scheduler, since it only starts several necessary components (e.g., etcd, kube-apiserver and kube-scheduler) during the testing.

The framework can be configured with a YAML file that specifies the testing workload with corresponding operations such as `createNodes` and `createPods`. Then it can collect the metrics defined in `kubernetes/pkg/scheduler/metrics/metrics.go`.

In the case of Volcano, we also want to focus on the performance of the scheduler itself without the influence of corresponding controllers, so I believe it is an appropriate solution for us to refer to. 

## Design

For the ease of testing, we can just start the Volcano scheduler for testing. Since we would like to focus on the performance of the scheduler, we should use `PodGroup` as the basic scheduling unit during the testing instead of `Pod`. In this case, we could have two solutions:

1. Define a `Pod` in the template, and create a fake `Pod` controller, then use informer to create the corresponding `PodGroup` as the process in `PodGroupController`. The benefit of this solution is that we could adapt the original code easily without significant changes, but we could not have more elastic configurations.
2. Define a `VolcanoJob` in the template, and create a fake `VolcanoJob` controller, then use informer to create the corresponding `PodGroup`. With this solution, we have more control over the composition of test cases but more modification is required.

After defining the workload, we could collect the metrics according to metrics defined in `pkg/scheduler/metrics/metrics.go`. Currently, an essential metric could be `e2e_scheduling_latency_milliseconds`, we can import more metrics if needed.

## Implementation

Since the test suite has to start kube-apisevrer from the code directly, and kube-apisevrer requires loading OpenAPI definition when starting, we have to generate the definition from the Kubernetes repository currently. Moreover, since the original OpenAPI definition does not include the definition of CRDs, we cannot start kube-apisevrer directly without modification.

As far as I know, the parsing of CRDs is the responsibility of apiextensions-apiserver of kube-apisevrer in Kubernetes. Since the integration testing suite of Kubernetes is not adaptable for CRDs natively, we have to find a new way to implement the import of CRDs from the code, and it maybe requires certain modification of the original testing suite of Kubernetes.

## References

- https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_perf_test.go

Any feedback or suggestion is welcomed :)

/cc @Thor-wl @william-wang @shinytang6

**Comment by k82cn** [comment]
xref: https://github.com/volcano-sh/kubesim

**Comment by william-wang** [comment]
@rudeigerc Thanks for your proposal.  Volcano has introduced a simulator named kubesim for performace testing. Here is the repo. Some performance test is done based on kubesim in the past year.
https://github.com/volcano-sh/kubesim
For the issue #1284, the original intention is to improve the UT/e2e coverage and introduce some stress test cases.
