### ISSUE TITLE
bug in proportion plugin:  if a resource (Except CPU and mem) doesn't configure in queue capability, it will be seen as Zero in resources comparation.

### ISSUE THREAD

**Issue by Megan96** [volcano-sh/volcano#1485]
**What happened**:
if we don't configure the capability of all resources in cluster in queue config file,  the resources (except CPU and mem) of capability will be Zero.
see comparation `!attr.deserved.LessEqualStrict(attr.capability) ` in https://github.com/volcano-sh/volcano/blob/v1.2.0/pkg/scheduler/plugins/proportion/proportion.go
see function `LessEqualStrict`  in  https://github.com/volcano-sh/volcano/blob/v1.2.0/pkg/scheduler/api/resource_info.go
```
// if  one type of resource exists in r but does't exists in rr,  rr.ScalarResources[rName] will get Zero
for rName, rQuant := range r.ScalarResources {		
      if !lessFunc(rQuant, rr.ScalarResources[rName]) {			
          return false		
      }	
}
```
**What you expected to happen**:
if a resource doesn't configure in queue capability,  it will be seen as unlimitied instead  of Zero.

**How to reproduce it (as minimally and precisely as possible)**:
add a new resource in cluster and don't configure it in queue capability. 
see log of  volcano-scheduler, you will find `queue <test> is meet cause of the capability` so even there are free resources of other type, it can't be allocate to queue.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.2.0
- Kubernetes version (use `kubectl version`): 1.18.15
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Thanks for your report. I've reviewd the code in proportion.go and got the following logic:
https://github.com/volcano-sh/volcano/blob/ed9e9cd09acfcd92a9e57a08210f91a00108ae72/pkg/scheduler/plugins/proportion/proportion.go#L173
As what i analysesed, if a queue is without the capability configuration, it will get false because the first judgement is `attr.capability != nil`. So it will not jump into the following logic:
https://github.com/volcano-sh/volcano/blob/ed9e9cd09acfcd92a9e57a08210f91a00108ae72/pkg/scheduler/plugins/proportion/proportion.go#L177
Well, that's just the code review, and i've not tried to reproduce it. Did i miss something else?

**Comment by Megan96** [comment]
> Thanks for your report. I've reviewd the code in proportion.go and got the following logic:
> https://github.com/volcano-sh/volcano/blob/ed9e9cd09acfcd92a9e57a08210f91a00108ae72/pkg/scheduler/plugins/proportion/proportion.go#L173
> 
> 
> As what i analysesed, if a queue is without the capability configuration, it will get false because the first judgement is `attr.capability != nil`. So it will not jump into the following logic:
> https://github.com/volcano-sh/volcano/blob/ed9e9cd09acfcd92a9e57a08210f91a00108ae72/pkg/scheduler/plugins/proportion/proportion.go#L177
> 
> 
> Well, that's just the code review, and i've not tried to reproduce it. Did i miss something else?

Suppose there are three types of resources(CPU, MEM, GPU) in cluster. If capability configuration of a queue just set limitation of CPU and Mem,  `attr.capability != nil` will be True.

**Comment by Thor-wl** [comment]
fixed: https://github.com/volcano-sh/volcano/pull/1621
/close
