### ISSUE TITLE
The arm deployment cannot find arm  images.

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1487]
**What happened**:

when i  use makefile and  make generate-yaml to product and install volcano on arm machine. I found the generate-yaml use the wrong images.

**What you expected to happen**:
install by yaml succussfully.

**How to reproduce it (as minimally and precisely as possible)**:

1、the makefile add the postfix named "arm64‘’
![1-makefile](https://user-images.githubusercontent.com/7522079/119460823-a741e600-bd71-11eb-8222-a84a60613287.PNG)
2、the generate-yaml not use "arm64"
![2-生成的yaml](https://user-images.githubusercontent.com/7522079/119460891-b9bc1f80-bd71-11eb-99ab-61a78bdbc418.PNG)

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.2.0
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration:arm
- OS (e.g. from /etc/os-release):centos
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
The generate-yaml is only for x86 machine now. You can install volcano in arm machine with the following way:
`
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development-arm64.yaml
`

**Comment by zishen** [comment]
> The generate-yaml is only for x86 machine now. You can install volcano in arm machine with the following way:
> `kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development-arm64.yaml`
> Readme records the installation guide, please refer to: https://github.com/volcano-sh/volcano/blob/master/README.md

I made some custom changes for images and define some values, I want to generate my own volcano-development.yaml.
So how can i do?

**Comment by Thor-wl** [comment]
Not sure what you have modified. But after executing `make generate-yaml`, bash script /hack/generate-yaml.sh will be executed and deployment and monitor-deployment yaml will generated(more details can be seen in the script). This step is noting to do with image. If you want to generate new images, you can do the above modifitions and execute `make images`.

**Comment by zishen** [comment]
> Not sure what you have modified. But after executing `make generate-yaml`, bash script /hack/generate-yaml.sh will be executed and deployment and monitor-deployment yaml will generated(more details can be seen in the script). This step is noting to do with image. If you want to generate new images, you can do the above modifitions and execute `make images`.

I have changes the helm->templates->scheduler.yaml, so I need generate  new developmen yaml.
