### ISSUE TITLE
mount from configMap not working as kubernetes.

### ISSUE THREAD

**Issue by berlinsaint** [volcano-sh/volcano#1495]
**What happened**:
![image](https://user-images.githubusercontent.com/10629930/119957351-9644df00-bfd4-11eb-871b-74c225c0b855.png)

get the errory log when kube create -f /

![image](https://user-images.githubusercontent.com/10629930/119957870-0e130980-bfd5-11eb-96ee-ca4e52dc45ea.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Please paste complete yaml files and error log. It' hard to get the details.

**Comment by berlinsaint** [comment]
> Please paste complete yaml files and error log. It' hard to get the details.

`kind: Job
metadata:
  name: test-pytorch-job
  namespace: easy-deep-learning
  labels:
    "volcano.sh/job-type": "pytorch"
spec:
  minAvailable: 1
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
    env: []
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: cv-train
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          hostIPC: true
          containers:
            - command:
              - bash
              - k8s-start.sh
              image: cv/classificaiton-p4:V1.1.1
              name: cv-classify
              workingDir: /home/user/image-classification
              resources:
                requests:
                  nvidia.com/gpu: "1"
                  cpu: "16"
                  memory: "8Gi"
                limits:
                  nvidia.com/gpu: "1"
                  cpu: "16"
                  memory: "16Gi"
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: SERVICE_POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: SWIFT_DOWNLOAD_PREFIX_PATH
                  value: cv/dataSet/base_data1395553048230629377/cv_data_type1395553048469704706/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553087854219265/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553131424649218/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553244029128705/,cv/dataSet/base_data1395553048230629377/cv_data_type1395553283799519234/,cv/dataSet/base_data1395553048230629377/mappingInfo/
                - name: SWIFT_UPLOAD_PREFIX_PATH
                  value: cv/model/base_mode1395743218322116609/cv_train_history1398177983046356993/trainResult/
                - name: UTIL_SAVE_PATH
                  value: /home/user/original_data
                - name: CV_TRAIN_INPUT
                  value: /home/user/input
                - name: MAP_FILE
                  value: "0"
                - name: UTIL_UPLOAD_PATH
                  value: /home/user/output/best/
                - name: ULTRON_D_ENDPOINT
                  value: http://easy-d-service.easy-service:8167/apis/v1/utils/status/
                - name: LM_SERVING_ID
                  value: "11981"
              volumeMounts:
              - mountPath: /etc/localtime
                name: local-time
              - mountPath: /home/user/image-classification/k8s-start.sh
                name: cv-start-train-script
                subPath: k8s-start.sh
              - mountPath: /home/user/image-classification/swift_util
                name: swift-util
              securityContext:
                capabilities:
                  add: ["ALL"]
                privileged: true
          volumes:
            # cv train 启动脚本
            - name: cv-start-train-script
              configMap:
                defaultMode: 420
                type: ""
                items:
                  - key: train-start.sh
                    path: k8s-start.sh
            # swift 上传、下载工具集
            - name: swift-util
              hostPath:
                path: /data/easy/easycv/swift_util
            # 本地时间
            - name: local-time
              hostPath:
                path: /etc/localtime
                type: ""`

**Comment by Thor-wl** [comment]
Please make sure the yaml you provided is formated. As what I test, it is not correct.

**Comment by Thor-wl** [comment]
BTW, I've tested a case with configmap and everything goes well.
``` job-with-cm.yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-with-cm
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: job-with-cm
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  sleep 10m
              image: nginx:latest
              name: job-with-cm
              resources:
                requests:
                  cpu: 1000m
                  memory: 2G
              imagePullPolicy: IfNotPresent
              volumeMounts:
              - mountPath: /home/
                name: host-path
              - mountPath: /usr/
                name: test-cm
          restartPolicy: OnFailure
          volumes:
            - name: test-cm
              configMap:
                name: test-cm
                items:
                  - key: train-start.sh
                    path: k8s-start.sh
            - name: host-path
              hostPath:
                path: /home/
```
``` test-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  train-start.sh: "k8s-start.sh"
```
