### ISSUE TITLE
CI: k8s.io/klog cannot pass the `make verify`

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#1500]
**What happened**:
CI cannot pass when execute `make verify` due to the k8s.io/klog checks fails
**What you expected to happen**:
CI passed
**How to reproduce it (as minimally and precisely as possible)**:
 Submit a PR and CI fails. The log looks like : https://github.com/volcano-sh/volcano/pull/1499/checks?check_run_id=2699268538

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by huone1** [comment]
the  workround PR is #1508

**Comment by Thor-wl** [comment]
> the workround PR is #1508

That works. Thanks!
