### ISSUE TITLE
Adding more status/events for measurement

### ISSUE THREAD

**Issue by TommyLike** [volcano-sh/volcano#151]
/kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
please also add description for this issue, including which kind of event/status we'd like to update.

**Comment by TommyLike** [comment]
@k82cn  sure

**Comment by TommyLike** [comment]
**Description**:
Now the a lot of job details are missed which makes end user or developer hard to measure and debug, for instance. when running  our tf/mpi examples, users are hard to find out when job starts to scheduler/run/complete/fail. As a developer I also want to know more details about the volcano job such as whether & when plugins have been successfully executed. We need to add more traces on our job API resources.

**Comment by TommyLike** [comment]
**Proposes**:
1. Add more event for tracing such as when job plugin execute, configmap/service/pods are created.
2. Update our job state attribute to condition which can provide more details.

```go
type JobCondition struct {
  // Type of job condition.
  Type JobConditionType `json:"type"`
  // Status of the condition, one of True, False, Unknown.
  Status v1.ConditionStatus `json:"status"`
  // The reason for the condition's last transition.
  Reason string `json:"reason,omitempty"`
  // A human readable message indicating details about the transition.
  Message string `json:"message,omitempty"`
  // The last time this condition was updated.
  LastUpdateTime metav1.Time `json:"lastUpdateTime,omitempty"`
  // Last time the condition transitioned from one status to another.
  LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty"`
}
```


@k82cn  & @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
Sounds good

**Comment by k82cn** [comment]
LGTM :)
