### ISSUE TITLE
apply as reviewer

### ISSUE THREAD

**Issue by huone1** [volcano-sh/volcano#1514]
My contribution as follows:

module contribution include:

1）add feature: predicate with equivalence cache .
2)  CI optimize .
3)  support taintToleration preferNoschdule .
4) numa-aware plugin design and coding

bugs:

#1291 
#1256 
#1363 

Take part in weekly community meeting, feature design.

Totally, i've contributed 16merged PRs and 4 is on the way, hope to contribute more to the community.

**Comment by Thor-wl** [comment]
Thanks for your continuous contribution! I'm OK about that.

**Comment by k82cn** [comment]
LGTM, please open a PR for that.

**Comment by Thor-wl** [comment]
refer: https://github.com/volcano-sh/volcano/pull/1515
