### ISSUE TITLE
The document needs to be updated.

### ISSUE THREAD

**Issue by kissingleman** [volcano-sh/volcano#1518]
For example, there is a `failed` state in the state transition.

**Comment by renhuanyu** [comment]
I'm sorry I didn't understand. Could you give me a more detailed description?

**Comment by Thor-wl** [comment]
> I'm sorry I didn't understand. Could you give me a more detailed description?

Perhaps what users need is the state transition diagram for job and podgroup

**Comment by renhuanyu** [comment]
The nodes in the state transition DAG include failed/succeed/pipeline/pending/allocated/binding/bound/running/releasing/unknow.
I will complete the part about job state in the document and add the DAG of state transition.
