### ISSUE TITLE
VolcanoJob maxRetry does not take effect

### ISSUE THREAD

**Issue by kissingleman** [volcano-sh/volcano#1519]
The retry feature does not take effect.
```
spec:
  maxRetry: 3
```

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:  1.2.1
- Kubernetes version (use `kubectl version`): 1.13.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Jonathanbenilan** [comment]
Hello, 
Seems to be related but I can open a new ticket if not.
MaxRetry=-1 should give  unlimted retries until job success or is cancel. Same with MaxRetry=0. 
But it will always end after 7 retries. 

Let me know if you want more detail.

**Comment by Thor-wl** [comment]
Suggest to give more details include reproduce steps and environment. It works normally ever.
