### ISSUE TITLE
Add staging to repository to simplify the dependency debug

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#1524]
#### What would you like to be added:
add stagging directory to simplify the dependency debug
#### Why is this needed:
Since volcano.sh/apis repository has created and volcano.sh/volcano depends on it, It's hard for developers to debug new features.

**Comment by william-wang** [comment]
The ability would improve the efficiency for developers. And the vendor directory can be also removed after the staging is added.
