### ISSUE TITLE
Enhancement about resource comparision functions according to different scenarios

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#1525]
According to backfeed from community, current resource comparasion functions at resource_info.go cannot meet all scenarios and introduce some bugs. We should reorganize the scenarios and optimize the resource comparasions

**Comment by k82cn** [comment]
Wow, that's really long time since last time we raised this concern :(

**Comment by shinytang6** [comment]
A collection of typical problems:

Less function logic bug: https://github.com/volcano-sh/volcano/issues/1036
If a resource (Except CPU and mem) doesn't configure in queue capability, it will be seen as Zero in resources comparation: https://github.com/volcano-sh/volcano/issues/1485
when one resource(GPU) is overused in queue, other resources (CPU) instances in the queue cannot be scheduled: https://github.com/volcano-sh/volcano/issues/1425

**Comment by Thor-wl** [comment]
As what i ananlysed last week, bugs of resoure comparision logic mainly lies at the following aspects:
* When comparing resourceList in L and R, the blank item should be regarded as infinity value instead of zero, especially comparing queue.capability with others. For example, L=queue.deserved = {CPU: 1c, memory:2G, GPU: 10}, R=queue.capability={GPU: 2}.
* Lack of resource comparision functions such as LessInSomeDemision, we should supply them.
* Because of lack of definition comments for comparision functions, developer may misunderstand the real meaning and use them by mistake, which introduce some bugs.

**Comment by Thor-wl** [comment]
Based on the above discovery, I give the following suggestions and will put them into practice as bug fix:
* List all resource comparision scenarios and give the correctly recommanded function.
* Add `defaultValue` as a parameter for all resource comparison funciton, its value can only be one between `zero` or `infinity`
* Fix existing resource comparision bugs in all plugins, especially in `proportion` and `preempt`

**Comment by Thor-wl** [comment]
Recommanded Resource Comparision Functions:
| Name | Comment | Example | Original function | Used plugins/actions |
| :----:| :----: | :----: | :----: | :----: |
| l.LessInAllDimension(r *api.Resource, defaultVaule string) | Values in all demisions in `l` are less than that in `r` | L{cpu:1c, memory:2G} < R{cpu:2c, memory:4G} | Less(rr *Resource) | proportion |
| l.LessEqualInAllDimension(r *api.Resource, defaultVaule string) | Values in all demisions in `l` are less than or equal with that in `r` | L{cpu:1c, memory:2G} < R{cpu:1c, memory:4G} | LessEqual(rr *Resource)/LessEqualStrict(rr *Resource) | allocate/preempt/reclaim/overcommit/proportion/reservation/topology |
| l.LessInSomeDimension(r *api.Resource, defaultVaule string) | Values in part demisions in `l` are less than that in `r` | L{cpu:4c, memory:2G} <| R{cpu:2c, memory:4G} | * | topology |
| l.LessEqualInSomeDimension(r *api.Resource, defaultVaule string) | Values in part demisions in `l` are less than or equal with that in `r` | L{cpu:4c, memory:2G} <=| R{cpu:2c, memory:2G} | * | * |
| l.Equal(r *api.Resource, defaultVaule string) | Values in all demisions in `l` are equal with that in `r` && values in all demisions in `r` are equal with that in `l` | L{cpu:1c, memory:2G} = R{cpu:1c, memory:2G} | * | * |
| l.GreaterInAllDimension(r *api.Resource, defaultVaule string) | Values in all demisions in `l` are greater than that in `r` | L{cpu:2c, memory:4G} > R{cpu:1c, memory:2G} | * | * |
| l.GreaterEqualInAllDimension(r *api.Resource, defaultVaule string) | Values in all demisions in `l` are greater than or equal with that in `r` | L{cpu:2c, memory:4G} >= R{cpu:2c, memory:2G} | * | * |
| l.GreaterInSomeDimension(r *api.Resource, defaultVaule string) | Values in part demisions in `l` are greater than that in `r` | L{cpu:4c, memory:2G} >| R{cpu:2c, memory:4G} | * | * |
| l.GreaterEqualInSomeDimension(r *api.Resource, defaultVaule string) | Values in part demisions in `l` are greater than or equal with that in `r` | L{cpu:2c, memory:2G} <=| R{cpu:2c, memory:4G} | * | * |

**Comment by wpeng102** [comment]
show a example about using `zero` and `infinity` as parameter. 
Such as  
`L{cpu:1c, memory:2G}, R{gpu:16}` 
`L.LessInAllDimension(R, "zero")` return `false` but `L.LessInAllDimension(R, "infinity")` return `true`

**Comment by Thor-wl** [comment]
> show a example about using `zero` and `infinity` as parameter.
> Such as
> `L{cpu:1c, memory:2G, gpu:2}, R{gpu:16}`
> `L.LessInAllDimension(R, "zero")` return `false` but `L.LessInAllDimension(R, "infinity")` return `true`

Yes. Thanks for the supplyment.
* When use `L.LessInAllDimension(R, "zero")`, it means R={cpu:0c, memory:0G, gpu:16}, so `cpu` and `memory` in L is larger than that in R. It returns `false`.
* When use `L.LessInAllDimension(R, "infinity")`, it means R={cpu: max c, memory: max G, gpu:16}, so all dimensions in L is less than that in R. It returns `true`.

**Comment by Thor-wl** [comment]
BTW, part of functions list above can be transformed from other functions. For example, a.GreaterEqualInSomeDimension(b *api.Resource, defaultVaule string) is equal with !b.LessInAllDimension(a *api.Resource, defaultVaule string)

**Comment by Thor-wl** [comment]
ref： https://github.com/volcano-sh/volcano/pull/1612
ref：https://github.com/volcano-sh/volcano/pull/1611
