### ISSUE TITLE
Add the function of viewing the podgoup in the queue

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#1532]
#### What would you like to be added:

Add a field in queue status, this field displays the podgroups that are in the queue in the order they are scheduled.

#### Why is this needed:

This feature provides a clear view of the scheduling order of podgroups and provides a more friendly display of information

**Comment by k82cn** [comment]
/hold

If there's no schedule decision, the scheduler will also update its status which increase the overload of apiserver.

**Comment by hwdef** [comment]
Get the podgroup status before updating, if it is consistent, then do not update.will reduce the pressure on the apiserver.

And most deep learning jobs have a long run time and the queue does not change frequently, (I guess)

**Comment by k82cn** [comment]
Usually, we do not add such monitor info into status :) IMO, it's better to handle this in metrics, e.g. promethus.

**Comment by hwdef** [comment]
Or we can store it in memory,Get it through vcctl. 

Obtaining through prometheus is also a good way,But I still don’t know how prometheus stores arrays of strings.

**Comment by k82cn** [comment]
> Obtaining through prometheus is also a good way,But I still don’t know how prometheus stores arrays of strings.

please refer to the related code about metrics in volcano/scheduler for that, it should be ok to add a new metrics for that :)

**Comment by hwdef** [comment]
@k82cn 

I read some of the volcano code and I noticed that volcano doesn't seem to have a global queue internally. Each action has a heap of its own, so is there any way we can get a global queue that indicates how jobs are queued?

**Comment by Thor-wl** [comment]
> @k82cn
> 
> I read some of the volcano code and I noticed that volcano doesn't seem to have a global queue internally. Each action has a heap of its own, so is there any way we can get a global queue that indicates how jobs are queued?

Not yet. You can list all podgroups and get the status.

**Comment by hwdef** [comment]
@Thor-wl 

But the podgroup obtained in this way does not have a scheduling order, and does not know which podgroup should be scheduled next

**Comment by k82cn** [comment]
> I read some of the volcano code and I noticed that volcano doesn't seem to have a global queue internally. Each action has a heap of its own, so is there any way we can get a global queue that indicates how jobs are queued?

nop, different queue may also have algorithm to do the scheduling; it's hard to have a global queue for that.

**Comment by hwdef** [comment]
I see, it seems that this function is very difficult to implement. So I close this issue. Thank you very much
