### ISSUE TITLE
A Bug about Terminated Pod In Node

### ISSUE THREAD

**Issue by quanguachong** [volcano-sh/volcano#1533]
**What happened**:

I encounter warning when deleting a completed pod(Succeeded or failed).

**What you expected to happen**:

No warning!

**Anything else we need to know?**:

For completed pod:

1. [addTask](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/cache/event_handlers.go#L63). [isTerminal](https://github.com/volcano-sh/volcano/blob/f203e26c357cebdacfe528a2269aeafb6655e418/pkg/scheduler/cache/event_handlers.go#L41) check leads to that It's banned to be added to node. 
2. [deleteTask](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/cache/event_handlers.go#L137). Skip [isTerminal](https://github.com/volcano-sh/volcano/blob/f203e26c357cebdacfe528a2269aeafb6655e418/pkg/scheduler/cache/event_handlers.go#L41) check, so you will always encounter err [here](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/cache/event_handlers.go#L152)

**Comment by shinytang6** [comment]
So maybe `addTask` should not skip terminated pods and still add it to cache.
