### ISSUE TITLE
preempt the tasks with the lowest priority

### ISSUE THREAD

**Issue by shuaiyy** [volcano-sh/volcano#1534]
#### What would you like to be added:

i hope if preempt lower priority tasks is ok,  higher priority tasks should not be  preempted.

in my test, i defined tasks with priority class: high、middle、low， high-priority tasks may randomly preempt middle-priority or low-priority tasks

#### Why is this needed:

try evict the lowest-priority tasks may has less impact and more acceptable in some case.

In our usage scenario,  the offline-offline colocation job(**gpu-ai-job**  VS **gpu-decode-job**) will have different priority classs, the lowest-priority colocation job should be evicted first when preemption happened

**Comment by Thor-wl** [comment]
Thank you for you feedback.
https://github.com/volcano-sh/volcano/blob/f203e26c357cebdacfe528a2269aeafb6655e418/pkg/scheduler/actions/preempt/preempt.go#L228
Let me debug the ssn.TaskOrderFn function

**Comment by Thor-wl** [comment]
Well, after a short discussion, i got your scenario. You want to evict victimsQueue from the lowest priority to highest priority without considering nodes first. Right?

**Comment by shuaiyy** [comment]
> Thank you for you feedback.
> https://github.com/volcano-sh/volcano/blob/f203e26c357cebdacfe528a2269aeafb6655e418/pkg/scheduler/actions/preempt/preempt.go#L228
> 
> 
> Let me debug the ssn.TaskOrderFn function.
> /assign @Thor-wl

maybe the problem is  **NodeOrderFn**, i hope node with most low-priority tasks should be selected first in my case.

**Comment by shuaiyy** [comment]
> Well, after a short discussion, i got your scenario. You want to evict victimsQueue from the lowest priority to highest priority without considering nodes first. Right?

yes, i want to find a best node to do preemption,   it should has little higher-priority tasks, cause evict higher priority will pay more  in my scenario.

**Comment by Thor-wl** [comment]
Got it. Sounds reasonable. Let me take a discussion in the community.

**Comment by shuaiyy** [comment]
> Got it. Sounds reasonable. Let me take a discussion in the community.

thank you ！
it seems add a **NodeOrderFn** may work in the preemption， but it will also affect the allocation. 

the preemption Strategy should be Configurable，on node level and task level，maybe：
the least victim; the lowest priority victim; default/random or other things;

**Comment by Thor-wl** [comment]
> > Got it. Sounds reasonable. Let me take a discussion in the community.
> 
> thank you ！
> it seems add a **NodeOrderFn** may work in the preemption， but it will also affect the allocation.
> 
> the preemption Strategy should be Configurable，on node level and task level，maybe：
> the least victim; the lowest priority victim; default/random or other things;

Good advice. After a review with other members yesterday, we all think you are right. And i decide to reconstruct the logic recently. Thanks again!
/assign @Thor-wl
