### ISSUE TITLE
Preemptable function select intersection of each plugin, which does not align with default scheduler.

### ISSUE THREAD

**Issue by umialpha** [volcano-sh/volcano#1539]
**What happened**:
Preemptable function select intersection of each plugin, it does not behave as expected, here is an example.

scheduler configMap is as follows,
``` yaml
- plugins:
  - name: priority
  - name: drf
```
There are two pods PodA(req: 1core) and PodB(req: 0.5core), and a NodeN(1 core), where

- PodA.Priority > PodB.Priority
- PodA.DRF > PodB.DRF.
- PodB is running on NodeN.

When PodB is running on Node, PodA is supposed to preempt PodB because PodA.Priority > PodB.Priority. But current logic does not preempt because PodA.DRF > PodB.DRF.

**What you expected to happen**:

Volcano use `TaskOrderFn` or `JobOrderFn` as `PreemptableFn`

**Anything else we need to know?**:
Although we could set `drf.EnabledPreemptable == false` to avoid such scenario, it is still not a best practice because,
1. When comparing TaskOrderFn(), the first plugin wins, e.g. if PodA.Proirity > PodB.Prriority, PodA.TaskOrder() > PodB.TaskOrder(). But when preemption occurs, it does not behave as the same.
2. Admin has to dig into source code  to correctly config `drf.EnabledPreemptable == false` to make Volcano behave as expected. At least There should be some official doc to point it out.

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
The configuration needs to be intersection under the same tier (all plugins need to satisfied), you can try to configure to a different tier, it can also solve your problem.

But of course, the documentation for plugin arguments is indeed missing.

**Comment by umialpha** [comment]
@shinytang6 thanks, it solves my problem. Indeed, I do not know the usage of tiers until now. BTW, `TaskOrder` cannot solve my problem because if plugins ties two task, `TaskOrder` select one by creationTime or even UID.

**Comment by shinytang6** [comment]
> @shinytang6 thanks, it solves my problem. Indeed, I do not know the usage of tiers until now. BTW, `TaskOrder` cannot solve my problem because if plugins ties two task, `TaskOrder` select one by creationTime or even UID.

Suppose you configure multiple tiers, if the previous tier produces a result, it will return in advance and not pass all the tiers.
