### ISSUE TITLE
K8s Deployment resource request exceed Queue capability still can be scheduled

### ISSUE THREAD

**Issue by brucexyz1234** [volcano-sh/volcano#1542]
**What happened**:
when K8s Deployment resource request exceed Queue capability , the deployment still can be scheduled by volcano

1. queue
spec:
  capability:
    cpu: "1"
    memory: "1024Mi"
2. deployment
  request:
    cpu: "2"
    memory: "2048Mi"

**What you expected to happen**:

deployment exceed the queue capability, should not be scheduled by volcano

**How to reproduce it (as minimally and precisely as possible)**:

create a queue and deployment with specific queue capability and deployment resource request and limit value

**Anything else we need to know?**:

no

**Environment**:
- Volcano Version: 1.2.x
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Thanks for your report! The root reason is minsource in podgroup for deployment is `nil`, which takes no share of queue capability. I'll try to fix it.

**Comment by huone1** [comment]
> Thanks for your report! The root reason is minresource in podgroup for deployment is `nil`, which takes no share of queue capability. I'll try to fix it.

For kubernetes native resource such as deployment/daemonSet， volcano  can set minrRsource  to  the request resource of one pod； If user need promise more than one pod to run， users can create  a podgroup to set minNumber and minResource， then associate it with the workload by add the annotation “scheduling.k8s.io/group-name”

**Comment by Thor-wl** [comment]
> > Thanks for your report! The root reason is minresource in podgroup for deployment is `nil`, which takes no share of queue capability. I'll try to fix it.
> 
> For kubernetes native resource such as deployment/daemonSet， volcano can set minrRsource to the request resource of one pod； If user need promise more than one pod to run， users can create a podgroup to set minNumber and minResource， then associate it with the workload by add the annotation “scheduling.k8s.io/group-name”

Agree with this solution.

**Comment by brucexyz1234** [comment]
the result look fine now, great thanks for the community guys!

**Comment by shinytang6** [comment]
> > Thanks for your report! The root reason is minresource in podgroup for deployment is `nil`, which takes no share of queue capability. I'll try to fix it.
> 
> For kubernetes native resource such as deployment/daemonSet， volcano can set minrRsource to the request resource of one pod； If user need promise more than one pod to run， users can create a podgroup to set minNumber and minResource， then associate it with the workload by add the annotation “scheduling.k8s.io/group-name”

that's reasonable, l think it better to provide a typical example for that scenary.
