### ISSUE TITLE
when edit deploy to change the deployment replica from 1 to  10, the new pods pending

### ISSUE THREAD

**Issue by brucexyz1234** [volcano-sh/volcano#1545]
**What happened**:
when edit deploy to change the deployment replica from 1 to  10, the new pods pending,

when I edit another deployment replica from 1 to 10,

then, all pods of these 2 deployment got scheduled and running again, amazing.

**What you expected to happen**:

either these 2 deployment pods got pending due to no node available
or the first deployment pods got scheduled  at the first

**How to reproduce it (as minimally and precisely as possible)**:

1. run 2 deploy with volcano, the edit first deployment replica to larger,  the new pods got pending
2. then edit second deploy to larger replica

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
I've tried to reproduce the scenario but got everyting going well. Perhaps you should provide more details about the evnironment and test steps.

**Comment by brucexyz1234** [comment]
the result look fine now, great thanks for the community guys!
