### ISSUE TITLE
v1.3.0 has no "volcano.sh/apis/pkg/apis/"

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1548]
Maybe a bug.

**What happened**:
When I  build v1.3.0, the volcano.sh/apis/pkg/apis/ is missing.
The screenshot is flowed：
v1.2.0:
![1 2 0版本存在](https://user-images.githubusercontent.com/7522079/122636790-ab1d1a00-d11d-11eb-9caa-5de4cd734faa.PNG)
v1.3.0
![1 3 0版本不存在](https://user-images.githubusercontent.com/7522079/122636782-9fc9ee80-d11d-11eb-899e-71f84ff34b47.PNG)
v1.3.0
build error：
![1 3 0版本不存在-编译不过](https://user-images.githubusercontent.com/7522079/122636805-c1c37100-d11d-11eb-8ee2-22bc4e036f71.PNG)

**Environment**:
- Volcano Version: v1.3.0
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: go 1.14.3

**Comment by shinytang6** [comment]
In release v1.3, api def is moved to https://github.com/volcano-sh/apis

**Comment by zishen** [comment]
> In release v1.3, api def is moved to https://github.com/volcano-sh/apis

oh,my God.
I use so file. So my so while not support after v.1.2.0.

And volcano need change pod_group_info.go to make it build successfull.

**Comment by shinytang6** [comment]
> > In release v1.3, api def is moved to https://github.com/volcano-sh/apis
> 
> oh,my God.
> I use so file. So my plugins not support after v.1.2.0.

Can you describe more specifically? https://github.com/volcano-sh/apis is referenced by gomod, it seems that you are not using gomod in your IDE.

**Comment by Thor-wl** [comment]
It's not a bug and you can get volcano.sh/apis in vendor
