### ISSUE TITLE
How to support Spark dynamic allocation scaledown?

### ISSUE THREAD

**Issue by dipanjank** [volcano-sh/volcano#1551]
Is there a (programmatic) way to kill a specific replica (say replica #2 of 4) within a task managed by volcano? 

The context is that my team at work is building volcano support in Spark (https://issues.apache.org/jira/browse/SPARK-35623). When dynamic allocation is enabled, spark adjusts the number of executors depending on how many Spark tasks can be allocated on the currently running executor. After a scaleup event, as load goes down and executors become idle, spark attempts to kill specific executors that cross the idle timeout threshold. Is there a way to achieve this using volcano?

**Comment by k82cn** [comment]
@dipanjank that's interesting, I'd like to work with you on that :)

**Comment by hiboyang** [comment]
Just curious how do you plan to support dynamic allocation scaledown, like how to restore shuffle files from those removed executors? We built [Remote Shuffle Service](https://github.com/uber/RemoteShuffleService) a while back ago to support such scenario. Not sure whether you might try that.

**Comment by holdenk** [comment]
Oh yeah we've done a few different things, there's also block migration new in Spark 3.1.

**Comment by k82cn** [comment]
> Just curious how do you plan to support dynamic allocation scaledown, like how to restore shuffle files from those removed executors? We built [Remote Shuffle Service](https://github.com/uber/RemoteShuffleService) a while back ago to support such scenario. Not sure whether you might try that.

That's great to work together with RSS :) Currently, Volcano focus on the resources allocation, e.g. CPU/Mem; so that's great to work with RSS as a e2e solution :)

**Comment by k82cn** [comment]
> Oh yeah we've done a few different things, there's also block migration new in Spark 3.1.

Can you help to share related work? That'll help to identify how to work together :)

**Comment by hiboyang** [comment]
> Oh yeah we've done a few different things, there's also block migration new in Spark 3.1.

Yes, there are a few options here, including the block migration.

**Comment by hiboyang** [comment]
> > Just curious how do you plan to support dynamic allocation scaledown, like how to restore shuffle files from those removed executors? We built [Remote Shuffle Service](https://github.com/uber/RemoteShuffleService) a while back ago to support such scenario. Not sure whether you might try that.
> 
> That's great to work together with RSS :) Currently, Volcano focus on the resources allocation, e.g. CPU/Mem; so that's great to work with RSS as a e2e solution :)

Yes, will be excited to see progress here :)

**Comment by holdenk** [comment]
Sure the block migration work is in https://github.com/apache/spark/blob/0d900b6cfa3b8b39cc240c2f6691bfe700ed3271/core/src/main/scala/org/apache/spark/storage/BlockManagerDecommissioner.scala

**Comment by william-wang** [comment]
@holdenk It's great. Thanks for your sharing.

**Comment by k82cn** [comment]
@all, we're going to have a prototype at https://github.com/spark-volcano for this enhancement :)
