### ISSUE TITLE
Publish combine images to support mixed arm & x86 clusters

### ISSUE THREAD

**Issue by holdenk** [volcano-sh/volcano#1554]
#### What would you like to be added:

Right now you have to select either arm or x86 images, but with buildx and other tools we can produce combined images.

Alternatively you could add nodeSelector to the two examples.

#### Why is this needed:

Some people have clusters with both arm and x86 and otherwise they need to use CPU label selectors.

**Comment by Thor-wl** [comment]
OK. I'd like to have a try.
