### ISSUE TITLE
Document how to get invited to the volcano slack

### ISSUE THREAD

**Issue by holdenk** [volcano-sh/volcano#1555]
#### What would you like to be added:

A link to an auto inviter for the volcano slack

#### Why is this needed:

Not everyone has access to it.

**Comment by k82cn** [comment]
We're using `#volcano` channel of http://cloud-native.slack.com for online discussion :)

@Thor-wl , please help to update readme for that :)

**Comment by Thor-wl** [comment]
> We're using `#volcano` channel of http://cloud-native.slack.com for online discussion :)
> 
> @Thor-wl , please help to update readme for that :)

OK. @renhuanyu is working on docs now. Can you help add the guidance?

**Comment by renhuanyu** [comment]
Fine , I will take a look.

**Comment by renhuanyu** [comment]
@holdenk 
Step1:You need to have a Google ID or Apple ID to log on to Slack, so use your work email.
Step2:Visit  `slack.cncf.io/`   and login.
Step3:Join the CNCF workspace.
Step4:Search for "Volcano" by adding channel and join it.

**Comment by renhuanyu** [comment]
Step1:You need to have a Google ID or Apple ID to log on to Slack, so use your work email.
Step2:Visit  `slack.cncf.io/`   and login.
Step3:Join the CNCF workspace
Step4:Search for "Volcano" by adding channel and join it.

**Comment by Thor-wl** [comment]
> Step1:You need to have a Google ID or Apple ID to log on to Slack, so use your work email.
> Step2:Visit `slack.cncf.io/` and login.
> Step3:Join the CNCF workspace
> Step4:Search for "Volcano" by adding channel and join it.

Let's submit a process to volcano.sh/community @renhuanyu
