### ISSUE TITLE
VolcanoJob does not appear to automatically create a podgroup

### ISSUE THREAD

**Issue by holdenk** [volcano-sh/volcano#1557]
**What happened**:

Deployed volcano on k3s 1.21, created examples from example dir & https://volcano.sh/en/docs/vcjob/ , saw jobs get created but no podgroups.

```
(base) holden@hkdesktop:~/repos/volcano/example/hierarchical-jobs$ kubectl get "job.batch.volcano.sh" -n volcano-test
NAME           AGE
eng-prod-job   3m53s
sci-dev-job    3m53s
sci-prod-job   3m53s
eng-dev-job    3m53s
test-job       22s
(base) holden@hkdesktop:~/repos/volcano/example/hierarchical-jobs$ kubectl get "podgroup" -n volcano-test
No resources found in volcano-test namespace.
(base) holden@hkdesktop:~/repos/volcano/example/hierarchical-jobs$ grep -i podgroup bloop.yaml 
(base) holden@hkdesktop:~/repos/volcano/example/hierarchical-jobs$ kubectl get "podgroup" --all-namespaces
No resources found
```

**What you expected to happen**:

I expected podgroups to be created since "If no PodGroup is specified when a VolcanoJob is created, Volcano will create a PodGroup with the same name as the VolcanoJob." is what it says in https://volcano.sh/en/docs/podgroup/

**How to reproduce it (as minimally and precisely as possible)**:

Apply the example in `volcano/example/hierarchical-jobs`

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
"latest" image as of `Wed Jun 23 16:00:52 PDT 2021`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:36Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
```

- Cloud provider or hardware configuration:
Mixed (arm64 & amd64)
- OS (e.g. from /etc/os-release):
Mixed (Ubuntu versions)
- Kernel (e.g. `uname -a`):
Mixed (5 & 4)
- Install tools:
kubectl
- Others:

**Comment by k82cn** [comment]
@huone1 , please help to check this one :)

**Comment by huone1** [comment]
please check whether  the volcano controller log  contain errors info  and give the job yaml you use @holdenk

**Comment by holdenk** [comment]
Sure, I'll take a look tomorrow (I'm in meetings all day today).

**Comment by aravindhank11** [comment]
The PodGroup is created, but seems to be created with the JobName + some hex values.
