### ISSUE TITLE
To become a community member

### ISSUE THREAD

**Issue by renhuanyu** [volcano-sh/volcano#1558]
#### What would you like to be added:
1.More scheduling features.
2.Continuous updating of documentation.

**Comment by Thor-wl** [comment]
Great! Welcome to join Volcano org and Thanks for you contribution.
@kevin-wangzefeng @k82cn Please help to send a invitation to @renhuanyu . Thanks!

**Comment by k82cn** [comment]
done :) 

Welcome to Volcano community :)
