### ISSUE TITLE
是否直接支持kubegene

### ISSUE THREAD

**Issue by Zhu-Ying** [volcano-sh/volcano#1560]
#### What would you like to be added:
是否直接支持kubegene

#### Why is this needed:
基因测序行业，数据分析流程，之前看文档volcano是支持cromwell的，实际测试时valcano并不能识别cromwell提交的shell script，只支持yaml文件。
转而选择kubegene，请问valcano是否能直接识别kubegene 的genectl  command提交的yaml文件？
毕竟valcano官网上的生态是有kubegene，但无实践指南。

**Comment by k82cn** [comment]
@kevin-wangzefeng is that ok to migrate kube-gene? so we can put more effort to improve the integration?

**Comment by kevin-wangzefeng** [comment]
I'm supportive on providing deeper integration with KubeGene, and for the long term, KubeGene would make use of more advanced capabilities from Volcano.
If no objections from both two community members, we can go ahead the migration.

**Comment by Thor-wl** [comment]
Agree with the integration.

**Comment by k82cn** [comment]
> If no objections from both two community members, we can go ahead the migration.

That's great :)

@Thor-wl , would you help to send an email to google group for more feedback?

**Comment by Thor-wl** [comment]
> > If no objections from both two community members, we can go ahead the migration.
> 
> That's great :)
> 
> @Thor-wl , would you help to send an email to google group for more feedback?

OK!

**Comment by william-wang** [comment]
I have completed the migration.
