### ISSUE TITLE
Support detailed queue info in scheduler cache

### ISSUE THREAD

**Issue by shinytang6** [volcano-sh/volcano#1562]
#### What would you like to be added:

Currently, the queue info stored in cache is as follows:
```
// QueueInfo will have all details about queue
type QueueInfo struct {
	UID  QueueID
	Name string

	Weight int32

	// Weights is a list of slash sperated float numbers.
	// Each of them is a weight corresponding the
	// hierarchy level.
	Weights string
	// Hierarchy is a list of node name along the
	// path from the root to the node itself.
	Hierarchy string

	Queue *scheduling.Queue
}
```

I think more information(such as allocated/inqueued/request), should also be stored here instead of calculated in the specific plugin (such as proportion), which can help make better decisions when scheduling.

**Comment by huone1** [comment]
Does the queue crd  need to extend QueueStatus for more detai？

**Comment by shinytang6** [comment]
> Does the queue crd need to extend QueueStatus for more detai？

I think this can be optional(TBD). If these fields are placed in crd, they will be updated frequently and increase the overload. WDYT？

**Comment by Thor-wl** [comment]
I think current fields in QueueStatus is enough temporarily.
