### ISSUE TITLE
Create multi-arch images

### ISSUE THREAD

**Issue by holdenk** [volcano-sh/volcano#1570]
#### What would you like to be added:

Multi-arch images (e.g. use docker buildx or similar)

#### Why is this needed:

So we can avoid having to use node selectors and to better support mixed arch clusters.

**Comment by shinytang6** [comment]
Thanks for your work @holdenk , I think this feature is still useful, if you are not available I can help take a look based on your work, much thanks!

/cc @ccchenjiahuan, pls also help take a look at this!

**Comment by odidev** [comment]
Hi Team,

As this PR <https://github.com/volcano-sh/volcano/pull/2049#issuecomment-1212690038> has been closed, may I know, if is there any other PR/work available to release multi-arch docker images? I am interested in the Linux/ARM64 Docker Images official release.

**Comment by hwdef** [comment]
> Hi Team,
> 
> As this PR [#2049 (comment)](https://github.com/volcano-sh/volcano/pull/2049#issuecomment-1212690038) has been closed, may I know, if is there any other PR/work available to release multi-arch docker images? I am interested in the Linux/ARM64 Docker Images official release.

I don't know if this is the PR you need
https://github.com/volcano-sh/volcano/pull/2435
