### ISSUE TITLE
lastProcessedNodeIndex may have some weakness because GetNodeList retrun node list from a map range

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#1572]
GetNodeList return a node list with no certain order because it is range from a map.
So there is a case that some nodes are not processed and others may process more than once  when lastProcessedNodeIndex loops one cycle
#### What would you like to be added:
GetNodeList may need to be sorted.

**Comment by lowang-bh** [comment]
k8s node list is from the nodeInfoSnapshot.NodeInfos().List()
```go
allNodes, err := g.nodeInfoSnapshot.NodeInfos().List()
```

```
// List returns the list of nodes in the snapshot.
func (s *Snapshot) List() ([]*schedulernodeinfo.NodeInfo, error) {
	return s.nodeInfoList, nil
}
```

```
func (cache *schedulerCache) UpdateSnapshot(nodeSnapshot *Snapshot) error {
        ...
       //  if node number change, refresh nodeInfoList
	if len(nodeSnapshot.nodeInfoList) != cache.nodeTree.numNodes {
		errMsg := fmt.Sprintf("snapshot state is not consistent, length of NodeInfoList=%v not equal to length of nodes in tree=%v "+
			", length of NodeInfoMap=%v, length of nodes in cache=%v"+
			", trying to recover",
			len(nodeSnapshot.nodeInfoList), cache.nodeTree.numNodes,
			len(nodeSnapshot.nodeInfoMap), len(cache.nodes))
		klog.Error(errMsg)
		// We will try to recover by re-creating the lists for the next scheduling cycle, but still return an
		// error to surface the problem, the error will likely cause a failure to the current scheduling cycle.
		cache.updateNodeInfoSnapshotList(nodeSnapshot, true)
		return fmt.Errorf(errMsg)
	}
        return nil
}

func (cache *schedulerCache) updateNodeInfoSnapshotList(snapshot *Snapshot, updateAll bool) {
	snapshot.havePodsWithAffinityNodeInfoList = make([]*schedulernodeinfo.NodeInfo, 0, cache.nodeTree.numNodes)
	if updateAll {
		// Take a snapshot of the nodes order in the tree
		snapshot.nodeInfoList = make([]*schedulernodeinfo.NodeInfo, 0, cache.nodeTree.numNodes)
		cache.nodeTree.resetExhausted()
		for i := 0; i < cache.nodeTree.numNodes; i++ {
			nodeName := cache.nodeTree.next()
			if n := snapshot.nodeInfoMap[nodeName]; n != nil {
				snapshot.nodeInfoList = append(snapshot.nodeInfoList, n)
				if len(n.PodsWithAffinity()) > 0 {
					snapshot.havePodsWithAffinityNodeInfoList = append(snapshot.havePodsWithAffinityNodeInfoList, n)
				}
			} else {
				klog.Errorf("node %q exist in nodeTree but not in NodeInfoMap, this should not happen.", nodeName)
			}
		}
	} else {
		for _, n := range snapshot.nodeInfoList {
			if len(n.PodsWithAffinity()) > 0 {
				snapshot.havePodsWithAffinityNodeInfoList = append(snapshot.havePodsWithAffinityNodeInfoList, n)
			}
		}
	}
}
```

**Comment by shinytang6** [comment]
> GetNodeList return a node list with no certain order because it is range from a map.
> So there is a case that some nodes are not processed and others may process more than once when lastProcessedNodeIndex loops one cycle
> 
> #### What would you like to be added:
> GetNodeList may need to be sorted.
> 
> #### Why is this needed:

great catch !

**Comment by lowang-bh** [comment]
may be another elegant fix is to use a OrderMap in stead of a normal Map of Nodes and a NodeList. That will have more code changes.

**Comment by jasonliu747** [comment]
> may be another elegant fix is to use a OrderMap in stead of a normal Map of Nodes and a NodeList. That will have more code changes.

You could submit another PR, and let's discuss which one is more feasible. :smile:

**Comment by lowang-bh** [comment]
> > may be another elegant fix is to use a OrderMap in stead of a normal Map of Nodes and a NodeList. That will have more code changes.
> 
> Would you like to submit another PR? We could discuss which one is more feasible. 😄

I can submit that PR at weekend.

**Comment by lowang-bh** [comment]
> > may be another elegant fix is to use a OrderMap in stead of a normal Map of Nodes and a NodeList. That will have more code changes.
> 
> Would you like to submit another PR? We could discuss which one is more feasible. 😄

I try to use a self define type orderMap, but found it can not iterate over elements gracefully.

I found the kubernetes also use a map and a list to cache the snapshot, so last commit with an additional nodelist may be the  finnally solution.

```go
type Snapshot struct {
	// nodeInfoMap a map of node name to a snapshot of its NodeInfo.
	nodeInfoMap map[string]*schedulernodeinfo.NodeInfo
	// nodeInfoList is the list of nodes as ordered in the cache's nodeTree.
	nodeInfoList []*schedulernodeinfo.NodeInfo
	// havePodsWithAffinityNodeInfoList is the list of nodes with at least one pod declaring affinity terms.
	havePodsWithAffinityNodeInfoList []*schedulernodeinfo.NodeInfo
	generation                       int64
}

```

**Comment by shinytang6** [comment]
> > > may be another elegant fix is to use a OrderMap in stead of a normal Map of Nodes and a NodeList. That will have more code changes.
> > 
> > 
> > Would you like to submit another PR? We could discuss which one is more feasible. 😄
> 
> I try to use a self define type orderMap, but found it can not iterate over elements gracefully, and will need to modify much other codes.
> 
> I found the kubernetes also use a map and a list to cache the snapshot, so last PR 1574 with an additional nodelist may be the finnally solution.
> 
> ```go
> // Snapshot is a snapshot of cache NodeInfo and NodeTree order. The scheduler takes a
> // snapshot at the beginning of each scheduling cycle and uses it for its operations in that cycle.
> type Snapshot struct {
> 	// nodeInfoMap a map of node name to a snapshot of its NodeInfo.
> 	nodeInfoMap map[string]*schedulernodeinfo.NodeInfo
> 	// nodeInfoList is the list of nodes as ordered in the cache's nodeTree.
> 	nodeInfoList []*schedulernodeinfo.NodeInfo
> 	// havePodsWithAffinityNodeInfoList is the list of nodes with at least one pod declaring affinity terms.
> 	havePodsWithAffinityNodeInfoList []*schedulernodeinfo.NodeInfo
> 	generation                       int64
> }
> ```

yes, I also prefer #1574 personally.

**Comment by jasonliu747** [comment]
#1574 has been merged. You could close this issue at your discretion. @lowang-bh
