### ISSUE TITLE
Store job/container stdout/logs to a more accessible area.

### ISSUE THREAD

**Issue by adamwoolhether** [volcano-sh/volcano#1575]
#### What would you like to be added:
Functionality to specify where the job-container's logs/stdout will be saved.

#### Why is this needed:
Slurm has the `--output` flag that allows user's to specify where stdout of the script/job ran will be stored. currently, the only option is for users to use `kubectl logs <pod-name> -c <container-name>`, which requires an extra step to view, and another if they would like to store this output somewhere.

**Comment by Thor-wl** [comment]
Well, I think Volcano may not has ability to do someting about that for it only focuses more on scheduling and high performance computing platforms support. Perhaps you can submit an issue to kubernetes community for help.

**Comment by k82cn** [comment]
> currently, the only option is for users to use kubectl logs <pod-name> -c <container-name>, which requires an extra step to view, and another if they would like to store this output somewhere.

Where're you going to store those logs? One option is to store those log by volume, e.g. local path

**Comment by adamwoolhether** [comment]
> Well, I think Volcano may has no ability to do someting about that for it only focuses more on scheduling and high performance computing platforms support. Perhaps you can submit an issue to kubernetes community for help.

You're right. Many HPC jobs, users will want to see the results of the job being run. I was thinking in terms of the `--output` function of slurm, but I agree, the pod logs alone is more of a Kubernetes thing.

**Comment by adamwoolhether** [comment]
> > currently, the only option is for users to use kubectl logs  -c , which requires an extra step to view, and another if they would like to store this output somewhere.
> 
> Where're you going to store those logs? One option is to store those log by volume, e.g. local path

Yes, the idea was to store them in a mounted folder owned by the user, via nfs, hostpath, or localpath....

Another idea is to allow users view the job script's output in realtime if desired. I know this can be done with the client set's GetLogs, as demonstrated [here](https://stackoverflow.com/a/65087061/12185309).

Anyways it's not terribly important, I know you guys are busy with other areas, just an idea.
