### ISSUE TITLE
Perfect Helm Chart

### ISSUE THREAD

**Issue by swartz-k** [volcano-sh/volcano#1580]
#### What would you like to be added:
Some typo fix:
1. `helm install installer/chart --namespace <namespace> --name <specified-name>
`    is wrong path [ref](https://volcano.sh/zh/blog/quick-start-volcano/ )

Some more flexible logic:
1. Custom Docker hub in Makefile by `IMAGE_PREFIX` also editable in Chart values.yaml.
2. Grafana、Prometheus be optional, In case user has his own.
3. Deployment and something so on may be editable `replicase`, `affinity` and also prometheus annotation
4. Better labels with helm chart default helper

#### Why is this needed:
Flexible logic can adapt to more scenarios, but this may also cause confusion.

**Comment by Thor-wl** [comment]
Thanks for the feedback! We'll optimize it.
