### ISSUE TITLE
No need to add irrelevant pod to cache?

### ISSUE THREAD

**Issue by cmssczy** [volcano-sh/volcano#1584]
#### What would you like to be added:

Suppose we have more than one schedulers in our cluster.
If a pod's `scheduler-name` is not `volcano` and it has been scheduled to one node by the scheduler which it specified. This pod is still added into valcano's cache. Is this necessary? 

https://github.com/volcano-sh/volcano/blob/39e2e0244f2660b433b912b782d603e131805b53/pkg/scheduler/cache/cache.go#L422-L434

**Comment by wpeng102** [comment]
Yes，volcano scheduler need to know other scheduler dispatched pods. Because these dispatched pod occupied node resource, volcano scheduler need to know how many resources left during volcano pod scheduling.

**Comment by Thor-wl** [comment]
Multi-scheduler is common used in production environment. Community is doing something to support that. Please refer to https://github.com/volcano-sh/volcano/pull/1576 and https://github.com/volcano-sh/volcano/pull/1565

**Comment by cmssczy** [comment]
Thanks for your reply. @wpeng102  @Thor-wl 
/close
