### ISSUE TITLE
about the numaware feather, not considered memory verified in allocated

### ISSUE THREAD

**Issue by hudson741** [volcano-sh/volcano#1585]
**What happened**:

when caculate allocable res in node's numa . I found the code doesn't consider the memory allocated in the different numa zone. is it right . and  other wise , what's the different between the NumaSchedulerInfo and NumaInfo in the node_info. why they can't be only one.(ps: 感觉numa调度时，没有考虑每个numa区域的剩余内存，是否满足numa调度，只考虑了cpu。另外，代码中，node_info中存了一个NumaInfo和一个NumaSchedulerInfo。这两者的区别是啥，为何不能用一个。)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by huone1** [comment]
1. In current version, the numaware feature scope is only the cpu resource. others will be considered in the next phase.e.g Memory, GPU
2. NumaInfo structure saves the numa info on per node by CRD, NumaSchedulerInfo saves the numa info that volcano schedules pod after per scheduling session. But the default refresh period of NumaInfo structure is 3s and  the default period of scheduling session is 1s, in addition,  their processing logic is asynchronous.

**Comment by huone1** [comment]
Memory manager is not supported since k8s 1.21 on kubelet.
