### ISSUE TITLE
Request to add more metrics for spark job running on k8s scheduled by volcano

### ISSUE THREAD

**Issue by yanglilangqun** [volcano-sh/volcano#1586]
#### What would you like to be added:
1. cluster resource:  
    - [ ]  the resource usage of a node with sort function
    - [ ]  the real time resources usage of the cluster by queue， including cpu, memory, network
2. queue: 
    - [ ]  quota
    - [ ]  used resouces
3. job: 
    - [ ]  metadata：

          besides the running time,  we need  submitted time,  start time, finish time,  cpu, memory, 

          queue info

    - [ ]  a url linked to the spark UI
#### Why is this needed:
We are planning to move some spark jobs on yarn to k8s, while some important metrics are lacked compared with the metrics on yarn.

 In order to monitor the running status better,  we request to add more metrics：

**Comment by Thor-wl** [comment]
Generally I'm OK for me. Just some questions as follows:
* "the real time resources usage of the cluster by queue， including cpu, memory, network", what do you mean about network in queue? In fact, only computing resource has relationship with queue.
* "queue quota" is "queue capability".
* "job.metadata:besides the running time,  we need  submitted time,  start time, finish time,  cpu, memory, queue info" Currently, we can only get `CreationTimestamp` and `DeletionTimesstamp` in job.metada. Besides, queue info cannot be gotten from job api directly. We should do some work and get from its podgroup.
* "a url linked to the spark UI". We should take a research about how to implement it.

**Comment by k82cn** [comment]
+1, that's great!!!

**Comment by Thor-wl** [comment]
@Tammy-kunyu @yanglilangqun Please give the process fedback here when you achieve any goals.
