### ISSUE TITLE
Request to add limit to the size of single log files.

### ISSUE THREAD

**Issue by lionelJi** [volcano-sh/volcano#1588]
#### What would you like to be added:
Limit to the size of a single log file with the use of klog.

#### Why is this needed:
We have a demand to solidify the logs on disk, When we do this, the scheduler log file may grow to 300MB a day.
We can use logrotate to dump the volcano log file, but it still cannot limit the size of a single log file. Based on the volcano log printing strategy, without adding limit, the scheduler log file is prone to be too large, and there is a risk of filling up the log space.

Versions:
Kubernetes: 1.17.3
volcano: 1.2.0

OS:
Ubuntu 18.04.5

**Comment by william-wang** [comment]
@lionelJi  It's reasonable. This should be supported. Thanks for your reporting.

**Comment by Thor-wl** [comment]
> @lionelJi It's reasonable. This should be supported. Thanks for your reporting.

+1
