### ISSUE TITLE
[Discussion] The integration of Custom Job

### ISSUE THREAD

**Issue by kuizhiqing** [volcano-sh/volcano#1589]
## Topic

This issue intend to discuss the best practices for integrating a Custom Job With Volcano.

## Background

* volcano has an outstanding design especially for scheduling by defining PG and Queue etc.
* [tf-operator](https://github.com/kubeflow/tf-operator) support volcano by handling(CRUD) the volcano resource (PS/Queue) alongside the lifecycle of tfJob
* current version of [paddle-operator](https://github.com/PaddleFlow/paddle-operator) support volcano using standard spec filed *schedulerName: volcano* OR annotations which will be handle by volcano controller

## Design
Therefore, there will be mainly three solution dealing for integration，

### 1. Do less
If we intend to more decouple custom operator with volcano, it will be something like paddle-operator, or even less. In this scenario, user will handle both Custom Resource (ex. PaddleJob) and Volcano Resource (ex. PG, Queue), or leave volcano to create default ones. Overall, functionality will be ensure by volcano side, even by watching annotation and so on.

PROS
* decoupling, logic isolation, no invasion
* upgrade independent

CONS
* volcano resource expose to USER (in non default mode), which may introduce more work

### 2. Do more
Thanks to the popularity of tf-operator by kubeflow, the kubeflow is something like de facto standard which people are mimicking. The tf-operator controller will handle the creation of PG for tfjob in this context, even introducing more spec like *priorityClassName* and *queue* in tfjob spec [ref](https://github.com/kubeflow/tf-operator/issues/920).

PROS
* user friendly interface/configuration

CONS
* logic binding and something like spec invasion

### 3. Do all
Theoretically, one should embed ALL spec of PG and queue to fully support volcano functionality, OR it will always lose something.

## Conclusion

In my opinion, 2 is the more practical in current context, but I think 1 may be more technically beautiful by extending volcano itself with standard spec like annotation etc. And I'd like to contribute in this direction.

Please let me know if I misunderstand some design for volcano or others. Thx.

**Comment by k82cn** [comment]
Prefer to option 2 which is friendly to the end user.

Volcano provide several features for AI, BigData and HPC; we delegate to related community (e.g. kubeflow) to decide which features are used. So it's better for PaddleJob to export necessary feature to end user, which will make CRD easier :)

**Comment by kuizhiqing** [comment]
Thanks for your reply. Well, in this case, I'm considering an experience consistent way of using volcano  in paddle-operator.

**Comment by Thor-wl** [comment]
Agree with @k82cn
