### ISSUE TITLE
Charts installation failed

### ISSUE THREAD

**Issue by Tammy-kunyu** [volcano-sh/volcano#1590]
**What happened**:

When I try to install the charts according to https://github.com/volcano-sh/charts/blob/master/chart/volcano/README.md, the Error happens.It appears like this:
#helm install volcano-release -f values.yaml volcano-sh/volcano
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Queue" in version "scheduling.incubator.k8s.io/v1alpha1"

**Environment**:
- Volcano Version: v1.3.0
- Kubernetes version (use `kubectl version`): v1.19.1
- OS (e.g. from /etc/os-release): centos7
- helm version: v3.0.1

**Comment by Thor-wl** [comment]
It seems that "scheduling.incubator.k8s.io/v1alpha1" has already been deprecated.
