### ISSUE TITLE
Failed to create vcjob using TaskFailed event.

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#1591]
**What happened**:

create a vcjob, its task has a policy, event is `TaskFailed`, aciton is `RestartJob`,

Its creation will fail, the error is 

```shell
[centos@master volcano-demo]$ kubectl apply -f mpi.yaml
Error from server: error when creating "mpi.yaml": admission webhook "validatejob.volcano.sh" denied the request: 1 error occurred:
        * spec.tasks.policies: Invalid value: "TaskFailed": invalid policy event

 valid events are [TaskCompleted * PodFailed PodEvicted Unknown], valid actions are [RestartTask TerminateJob CompleteJob ResumeJob AbortJob RestartJob]
```

**What you expected to happen**:

Successfully created

**How to reproduce it (as minimally and precisely as possible)**:

In the way above

**Anything else we need to know?**:

My guess is that the TaskFailed field was newly added, but the webhook code was not updated. 

I will fix it.

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by huone1** [comment]
you're right, the TaskFailed is out of policyEventMap
![image](https://user-images.githubusercontent.com/71266853/124883033-85d84900-e003-11eb-975c-f9e2f5d02309.png)

**Comment by k82cn** [comment]
> you're right, the TaskFailed is out of policyEventMap, Please check other events. thanks
> ![image](https://user-images.githubusercontent.com/71266853/124883033-85d84900-e003-11eb-975c-f9e2f5d02309.png)

hm... let's add some alias for that :)

**Comment by hwdef** [comment]
@k82cn 
sorry, I don't understand what you mean by adding alias?

**Comment by k82cn** [comment]
> @k82cn
> sorry, I don't understand what you mean by adding alias?

for example, `TaskFailed` == `PodFailed` :)
