### ISSUE TITLE
Report of security issue when use ssh to mount keys

### ISSUE THREAD

**Issue by lionelJi** [volcano-sh/volcano#1597]
#### What would you like to be added:
There is a problem of management when use ssh to mound keys

#### Why is this needed:
When using ssh client software, it must be able to do public key authentication to the server. It is recommended to provide a configuration method based on ssh client public key authentication in the materials, so that it could support to enable the function of ssh client public key authentication.

**Comment by Thor-wl** [comment]
Well, Can you give more information about your scenario? I doesn't get the point with Volcano.
