### ISSUE TITLE
Add support for pod deletion cost.

### ISSUE THREAD

**Issue by holdenk** [volcano-sh/volcano#1598]
#### What would you like to be added:

Add support for pod deletion costs in the same/similar way as the default kubernetes scheduler (FEATURE STATE: Kubernetes v1.21 [alpha] - https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/ )

#### Why is this needed:

Not all pods have the same cost of pre-emption especially with semi-stateful jobs in things like Spark, Dask, and Ray.

**Comment by k82cn** [comment]
@holdenk , Volcano support task/pod priority within a job to handle this issue; when doing preemptionn, low priority task will be preempted firstly :)

xref: https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/priority/priority.go#L45

**Comment by holdenk** [comment]
So we can't dynamically change pod priority within a job and the use case here is when it's dynamic (e.g. a pod has all of it's data migrated off it).

**Comment by k82cn** [comment]
> So we can't dynamically change pod priority within a job and the use case here is when it's dynamic (e.g. a pod has all of it's data migrated off it).

Theoretically, we CAN dynamically change pod priority within a job: the Pod will not restart by controller, and task's priority will take effect in next scheduling cycle, e.g. 1s. Anyway, let's verify that :)

**Comment by holdenk** [comment]
So I don't think that's the case.

On my Kube cluster attempting to modify a running pods priority class or pod priority directly gives me this error:
```
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
#   core.PodSpec{
```

This also seems to match the documentation that pods are "mostly" immutable once scheduled.
