### ISSUE TITLE
Queue controller and related cli

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#16]
Currently, user can only create a Queue for scheduling; but it's hard to know more info about it, e.g. how many job in the queue, which plugins is used by this queue; and if the Queue is deleted, the job is still there :( It's better to have QueueController to mamange Queue's lifecycle and update its status; and have related command line for uset to get its info.

**Comment by hzxuzhonghu** [comment]
@k82cn I would make queueController in the same process with job controller, is this ok?

**Comment by k82cn** [comment]
> I would make queueController in the same process with job controller, is this ok?

That's ok to me; similar to kube-controller-manager :) BTW, we have a cache in `pkg/controller`; please reuse it if necessary :)
