### ISSUE TITLE
Rename vk-scheduler to vk-kube-batch

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#160]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**:

Currently, Volcano's scheduler is an enhanced kube-batch; it's better to keep kube-batch's name/signature :)

**Comment by asifdxtreme** [comment]
pre v0.1 it will be known as `vk-scheduler' , post v0.1 it will be known as `vk-kube-batch` ?

**Comment by k82cn** [comment]
Let's use vk-kube-batch since `0.1.1` :)
