### ISSUE TITLE
Ensure that input verification is performed on untrusted data.

### ISSUE THREAD

**Issue by ounijang** [volcano-sh/volcano#1601]
**Suggest ：**
The input data may be invalid. Therefore, verification before use will reduce the risk.

**Environment:**

Volcano Version:v1.2.0
Kubernetes version (use kubectl version):1.17.3
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):unbuntu 18.04
Kernel (e.g. uname -a):
Install tools:
Others:
I found that the code invoked was in the scheduler/app/options/options.go file.

**Comment by Thor-wl** [comment]
Can you give more details about this issue? For example, what data should be verified?
