### ISSUE TITLE
Confusion about panic in volcano

### ISSUE THREAD

**Issue by cist** [volcano-sh/volcano#1602]
Suggest ：
hi, Guys, I found some code for panic in the volcano code. Is it intentional panic and then exit the program?Is there a more elegant solution?
eg.
![image](https://user-images.githubusercontent.com/8309104/125042345-4d507200-e0cc-11eb-8702-3b30af266ca8.png)

Environment:

Volcano Version:v1.2.0
Kubernetes version (use kubectl version):1.17.8
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release):unbuntu 18.04
Kernel (e.g. uname -a):
Install tools:

**Comment by Thor-wl** [comment]
It's most likely that users give wrong values for parameters if server throws panic. A possible approach is to sort out all possible incorrect input and deal with them. But that may not be a elegant solution.
