### ISSUE TITLE
The path of kubeconfig has not been verified

### ISSUE THREAD

**Issue by Zumium** [volcano-sh/volcano#1603]
#### What would you like to be added:
The verification of the path of the kube config file, which is read from "KUBECONFIG" environment vairable or "kubeconfig" flag, needs to be added, like normalizing the path and checking whether the file actually exists.

#### Why is this needed:
The unverified inputs sometimes can be used to do malicious things like command injection.

Versions:
Kubernetes: 1.17.3
volcano: 1.2.0

OS:
Ubuntu 18.04.5

**Comment by Thor-wl** [comment]
Good advice! Thanks and we will add it.

**Comment by hwdef** [comment]
https://github.com/volcano-sh/volcano/blob/a379131657cabe03104ac9c45226edd143e8bfc4/pkg/kube/config.go#L39

Volcano uses the official library of kubernetes to open kubeconfig, and currently there is no such verification in the kubernetes source code, I think there is no need for verification.

@Zumium Do you have any other suggestions or relevant sample codes?
