### ISSUE TITLE
Suggest use https instead of http

### ISSUE THREAD

**Issue by gojosatoru3** [volcano-sh/volcano#1604]
#### What would you like to be [added:]
Suggest using https here.
[
![image](https://user-images.githubusercontent.com/87174703/125048944-044fec00-e0d3-11eb-9796-3340e5c39070.png)
](url)

#### Why is this needed:
Security.

**Comment by Thor-wl** [comment]
Thanks for the report. I'm OK about it.
/assing @Tammy-kunyu

**Comment by hwdef** [comment]
I think http is more suitable for metrics. And some other projects also use http exposure metrics, such as etcd
