### ISSUE TITLE
Suggest to make soft linkjudgment before opening the file

### ISSUE THREAD

**Issue by gojosatoru3** [volcano-sh/volcano#1605]
#### What would you like to be added & Why is this needed:

I have some suggestions for the code here.
Before using os.Open to open the file, it is best to verify the path, otherwise the attacker can change the file to a soft link and modify any file that they want to modify through this soft link to attack the system. Can you help me understand if there may be a problem here?
![image](https://user-images.githubusercontent.com/87174703/125050566-a6240880-e0d4-11eb-8060-7179619a3397.png)

Volcano Version: v1.2.0
Operating System: CentOS 7.6

**Comment by Thor-wl** [comment]
Sounds reasonable. Can you help for that?

**Comment by hwdef** [comment]
Do you have some code samples to provide? I checked the kubernetes source code, but no relevant code was found in it. If kubernetes thinks that there is no need to do related checks, I think volcano does not need related checks,too.
