### ISSUE TITLE
Suggest doing overflow checking for the counting variables in QueueStatus

### ISSUE THREAD

**Issue by Zumium** [volcano-sh/volcano#1607]
#### What would you like to be added:
The overflow checking for the counting variables in QueueStatus structure when operating them in syncQueue method.

#### Why is this needed:
The variable overflow may cause crashing or undefined behavior.

Versions:
Kubernetes: 1.17.3
volcano: 1.2.0

OS:
Ubuntu 18.04.5

**Comment by Thor-wl** [comment]
Can you give an example?
