### ISSUE TITLE
Suggest clear the generated private key information in a timely manner

### ISSUE THREAD

**Issue by ChuckGithub** [volcano-sh/volcano#1608]
If private key information is not cleared in time, sensitive information may be disclosed

Line190-194

https://github.com/volcano-sh/volcano/blob/ed9e9cd09acfcd92a9e57a08210f91a00108ae72/pkg/controllers/job/plugins/ssh/ssh.go#L191

Related Version:
Kubernetes: `1.17.8`
Volcano: `1.2.0`

OS: `Ubuntu 18.04.5`

**Comment by Thor-wl** [comment]
That's reasonable. THX.
