### ISSUE TITLE
volcano-admission pod stuck in CrashLoopBackoff. Reporting secret not found, but it is present.

### ISSUE THREAD

**Issue by adamwoolhether** [volcano-sh/volcano#1616]
**What happened**:
Installed volcano in a single-node environment, via yaml manifest. Everything except the `volcano-admission` pod starts successfully. 

**What you expected to happen**:
YAML manifest to install as normal

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl create -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml`
`kubectl -n kube-system get pods -w`

**Anything else we need to know?**:
- I'm testing volcano on a single-node environment.
- Cert signing is **not** disabled in `kube-controller-manager`
- I've reviewed [#476](https://github.com/volcano-sh/volcano/issues/476). My issue is different in that `volcano-admission-init` pod runs successfully and the secret is created.
- The logs of the admission pod are strange, reporting `unknown flag`.

$ k get pods -n volcano-system
```
NAME                                   READY   STATUS             RESTARTS   AGE
volcano-admission-f5f4fb5b6-2bhrf      0/1     CrashLoopBackOff   11         34m
volcano-admission-init-2rdpw           0/1     Completed          0          34m
volcano-controllers-5bbcc9c49f-ckg4r   1/1     Running            0          34m
volcano-scheduler-5665cdc4d9-t5jln     1/1     Running            0          34m
```

$ k logs -n volcano-system volcano-admission-f5f4fb5b6-2bhrf
```
unknown flag: --admission-conf
Usage of /vc-webhook-manager:
unknown flag: --admission-conf
..........
```

$ k describe pod -n volcano-system volcano-admission-f5f4fb5b6-2bhrf
```
.........
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    36m                  default-scheduler  Successfully assigned volcano-system/volcano-admission-f5f4fb5b6-2bhrf to aim-sms.aim
  Warning  FailedMount  36m (x2 over 36m)    kubelet            MountVolume.SetUp failed for volume "admission-certs" : secret "volcano-admission-secret" not found
  Normal   Pulled       34m (x5 over 36m)    kubelet            Container image "volcanosh/vc-webhook-manager:latest" already present on machine
  Normal   Created      34m (x5 over 36m)    kubelet            Created container admission
  Normal   Started      34m (x5 over 36m)    kubelet            Started container admission
  Warning  BackOff      75s (x165 over 36m)  kubelet            Back-off restarting failed container
```

However, the `admission-init` pod **does** create the secrets successfully:

$  k logs -n volcano-system volcano-admission-init-2rdpw
```
creating certs in dir /tmp
Generating RSA private key, 2048 bit long modulus (2 primes)
...............................+++++
...................................................................+++++
e is 65537 (0x010001)
Generating RSA private key, 2048 bit long modulus (2 primes)
........................+++++
........+++++
e is 65537 (0x010001)
Ignoring -days; not generating a certificate
Signature ok
subject=CN = volcano-admission-service.volcano-system.svc
Getting CA Private Key
secret/volcano-admission-secret created
```

$ k get secrets -n volcano-system
```
NAME                              TYPE                                  DATA   AGE
default-token-96hrs               kubernetes.io/service-account-token   3      39m
volcano-admission-secret          Opaque                                3      39m
volcano-admission-token-bs44t     kubernetes.io/service-account-token   3      39m
volcano-controllers-token-82mcc   kubernetes.io/service-account-token   3      39m
volcano-scheduler-token-6b4d2     kubernetes.io/service-account-token   3      39m
```

$ k describe secrets -n volcano-system volcano-admission-secret
```
Name:         volcano-admission-secret
Namespace:    volcano-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
ca.crt:   1208 bytes
tls.crt:  1334 bytes
tls.key:  1675 bytes
```

$ k describe secrets -n volcano-system volcano-admission-token-bs44t
```
Name:         volcano-admission-token-bs44t
Namespace:    volcano-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: volcano-admission
              kubernetes.io/service-account.uid: f24fea90-e9ed-49c7-8e19-d8287d5b03a0

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1066 bytes
namespace:  14 bytes
token: ***OMITTED***
```

**Environment**:
- Volcano Version: `v1.3.0`
- Kubernetes version: `v1.20.4`
- Cloud provider or hardware configuration: `Quanta Cloud Technology Inc. QuantaGrid D52G-4U`
- OS (e.g. from /etc/os-release): `CentOS Linux release 8.4.2105`
- Kernel: `4.18.0-305.3.1.el8.x86_64`
- Install tools: `kubeadm`
- Container Runtime: `cri-o://1.21.0`

**Comment by Thor-wl** [comment]
Thanks for your report! Let me have a check.

**Comment by wpeng102** [comment]
@adamwoolhether this issue is same as https://github.com/volcano-sh/volcano/issues/1638,  please refer comment https://github.com/volcano-sh/volcano/issues/1638#issuecomment-884621830

**Comment by adamwoolhether** [comment]
> @adamwoolhether this issue is same as #1638, please refer comment [#1638 (comment)](https://github.com/volcano-sh/volcano/issues/1638#issuecomment-884621830)

thanks!
