### ISSUE TITLE
Show controller-manager version print “controller is registered”.

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1620]
Maybe this is only a  area of improvement.

![image](https://user-images.githubusercontent.com/7522079/125721201-68b54568-043f-4172-a36b-5b8bffab3014.png)

and this is happened in init()
![image](https://user-images.githubusercontent.com/7522079/125721312-566d79e3-6aaa-42e0-9ea7-22b885811649.png)

Can change him any better?

**Environment**:
- Volcano Version: v1.3.0
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration: A800/9000
- OS (e.g. from /etc/os-release): kylin
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by william-wang** [comment]
@zishen Yes, The binary version, git SHA and built time are supposed to be enhanced to be shown.
