### ISSUE TITLE
 Task launch order support

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#1627]
#### What would you like to be added:

Task-level DAG scheduling policy

#### Why is this needed:

This feature provides the ability to customize the order in which tasks are launched

The following scenarios come to mind so far:

* mpi job. the master needs to wait for the worker to start before starting, If the master is already started, but the worker is not yet started, the master will restart, which will add unnecessary waste of resources ,in this case, mpiworker needs to be in the running state, and then create the pod for mpimaster..
* Suppose there are two tasks and task 2 needs to use the calculation results of task 1,in this case, task1 needs to be in the complete state, and then create the pod for task2.

* some ETL  applications

#### design

* Add a field that is an array named `startPolicy` in task spec
* It contains two fields, `dependOn` and `trigger`
* `dependOn` is a string indicating the name of the task that the current task depends on
* `trigger`is used to detect the status of the task in dependOn. This field can be used with the `probe` struct in kubernetes

eg:

```yaml
startPolicy:
  - dependOn: taskA, taskB
    trigger: {probe}
  - dependOn: taskC
    trigger: {probe}
     
```

**Comment by Thor-wl** [comment]
That's interesting. Are you interested in working for that or let's work together?

**Comment by shinytang6** [comment]
maybe similar to https://github.com/volcano-sh/volcano/issues/1117
l am also interested in that feature, let's work together )

**Comment by hwdef** [comment]
@Thor-wl I think both options are ok :)

**Comment by Thor-wl** [comment]
Let's give a design doc first about introduction about the scenarios/apis/algorithms/workflows.etc together. Do you think so? @hwdef @shinytang6
