### ISSUE TITLE
Use volcano-release-0.1 branch of volcano-sh/kube-batch

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#163]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

We need to update kube-batch branch to `volcano-release-0.1` for volcano release.

**Comment by asifdxtreme** [comment]
@k82cn Do we need to update the v0.1 release of Volcano with this branch of kube-batch, or the current master branch of Volcano should use `volcano-release-0.1` branch of kube-batch

**Comment by k82cn** [comment]
update the v0.1 release of Volcano with this branch of kube-batch

**Comment by asifdxtreme** [comment]
@k82cn okay, I will update this
