### ISSUE TITLE
the volcano-development.yaml has an additional configuration parameter

### ISSUE THREAD

**Issue by NaraLuwan** [volcano-sh/volcano#1638]
when i install whit yaml files,I get an error msg when I execute the following command:
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml

err msg:unknown flag: --admission-conf

And then I'm going to get rid of this argument and I'm not going to report any errors.

**Comment by shinytang6** [comment]
I think it's because of the latest image is not updated.
/cc @huone1

**Comment by wpeng102** [comment]
@NaraLuwan please use the latest code to build the admission image. Or use the version 1.3.0 installer yaml https://github.com/volcano-sh/volcano/blob/v1.3.0/installer/volcano-development.yaml

**Comment by william-wang** [comment]
@Thor-wl please help to update the lastest image on the docker hub.

**Comment by Thor-wl** [comment]
> @Thor-wl please help to update the lastest image on the docker hub.

OK.

**Comment by NaraLuwan** [comment]
@wpeng102 I tried 1.3.0 and It works fine,thx
