### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#1647]
#### What would you like to be added:

We're going to rename `master` branch to `main` branch, please follow those step to update your local environment:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by Thor-wl** [comment]
Why shell we rename the master branch?

**Comment by k82cn** [comment]
xref: https://github.com/kubernetes/enhancements/issues/2853
