### ISSUE TITLE
CI problem has been around for days that block PR merge

### ISSUE THREAD

**Issue by huone1** [volcano-sh/volcano#1648]
**What happened**:
CI problem has been around for days that block PR merge
it is a problem that the cluster resource is not enough.
![image](https://user-images.githubusercontent.com/71266853/127457502-42e0dd02-f917-4a52-8f11-9ba1ac913bac.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by william-wang** [comment]
@Thor-wl CI blocks us too many times. we need reconsider the solution that buy some machine from cloud to run ci.

**Comment by Thor-wl** [comment]
OK. It occurs by the update of tools at github action machines. I'm trying to fix it.
