### ISSUE TITLE
Daily release job failed to upload the latest images

### ISSUE THREAD

**Issue by SataQiu** [volcano-sh/volcano#1679]
**What happened**:

Docker username or password not found, daily release job failed to upload the latest images.
https://github.com/volcano-sh/volcano/runs/3317775913?check_suite_focus=true

![image](https://user-images.githubusercontent.com/9354727/129692908-6e5aa66c-4a6e-4815-9443-dbeeb3190d1d.png)

Ref: #1664, #1638

**What you expected to happen**:
Daily release job uploads the latest images successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Well, yes, Thanks for your report. I'll fix it.
/assign

**Comment by Thor-wl** [comment]
Daily release has been fixed.
/close
