### ISSUE TITLE
Info: Do not just add a e2e test

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#168]
For small features or bug fixes, if it can be tested by a UT, do not add e2e again.

As one e2e case can cause 20+ seconds, it will make the CI takes more time.

**Comment by TommyLike** [comment]
@hzxuzhonghu would you help on setting up the UT framework and moving some of the them?

**Comment by hzxuzhonghu** [comment]
>@hzxuzhonghu would you help on setting up the UT framework and moving some of the them?

sure,  but i have been working on other stuff these days. May have bandwidth in the middle of next week.

**Comment by thandayuthapani** [comment]
Have written UT cases for two files in Job package, ref https://github.com/volcano-sh/volcano/pull/201 & https://github.com/volcano-sh/volcano/pull/213
Files in Job package
  - [x]  job_controller_plugins
  - [x]  job_controller_handler
  - [ ]  job_controller_actions

**Comment by thandayuthapani** [comment]
UT for other packages are to be added, listing out other packages to which UT cases to be added.
 - [ ] pkg/cli
 - [ ] pkg/controllers/queue
 - [ ] pkg/controllers/garbagecollector
 - [ ] pkg/controllers/apis
 - [ ] pkg/controllers/cache
 - [ ] pkg/controllers/job/state

**Comment by k82cn** [comment]
@thandayuthapani , please also help to provide code coverage of each package :)

**Comment by asifdxtreme** [comment]
UT has been added for all the packages and the current coverage for UT is around [61%](https://coveralls.io/github/volcano-sh/volcano?branch=master), In my opinion we can go ahead and close this issue

**Comment by hzxuzhonghu** [comment]
Can we remove some e2e cases, which is already covered by e2e?

**Comment by asifdxtreme** [comment]
> Can we remove some e2e cases, which is already covered by e2e?

We went through all E2E test case, In our opinion all are required as of now, the test scenarios for UT are restricted to a particular functions/methods whereas E2E is tesing the complete flow for each scenario, so the both have different scope while testing. Going ahead we need to add more E2E's to cover all scenario, I don't think so we can reduce the E2E.

**Comment by TommyLike** [comment]
@asifdxtreme  I am wondering whether we need keeping the case of `MPI`, since all of the required features have been (or should) tested separately in different cases. the downloading and loading mpi images also consume some time.
```
• [SLOW TEST:16.254 seconds]
MPI E2E Test
/home/travis/gopath/src/volcano.sh/volcano/test/e2e/mpi.go:26
  will run and complete finally
  /home/travis/gopath/src/volcano.sh/volcano/test/e2e/mpi.go:27
------------------------------
```

```
Status: Downloaded newer image for volcanosh/example-mpi:0.0.1
Loading docker images into kind cluster
```

**Comment by asifdxtreme** [comment]
> @asifdxtreme I am wondering whether we need keeping the case of `MPI`, since all of the required features have been (or should) tested separately in different cases. the downloading and loading mpi images also consume some time.
> 
> ```
> • [SLOW TEST:16.254 seconds]
> MPI E2E Test
> /home/travis/gopath/src/volcano.sh/volcano/test/e2e/mpi.go:26
>   will run and complete finally
>   /home/travis/gopath/src/volcano.sh/volcano/test/e2e/mpi.go:27
> ------------------------------
> ```
> 
> ```
> Status: Downloaded newer image for volcanosh/example-mpi:0.0.1
> Loading docker images into kind cluster
> ```

One E2E with real example should defintely be there, we can find other options for MPI etc.. which takes lesser time to finish the test.
