### ISSUE TITLE
Deleting a queue with `kubectl` fails with "only queue with state `Closed` can be deleted"

### ISSUE THREAD

**Issue by prokher** [volcano-sh/volcano#1687]
**What happened**:

An attempt to delete a queue with `kubectl delete` ends with the following error:
```
Error from server: error when deleting "ex2-volcano.yaml": admission webhook "validatequeue.volcano.sh" denied the request: only queue with state `Closed` can be deleted, queue `one-q` state is `Open`
Error from server (NotFound): error when deleting "ex2-volcano.yaml": jobs.batch.volcano.sh "j1-vj" not found
```

**What you expected to happen**:

I expect queue be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Just create a new queue and try to delete it with `kubectl delete`.

**Anything else we need to know?**:

I realize I can close the queue first with `vcctl`, but I need a pure Kubernetes solution without extra CLI tools. I am going to eventually create/delete queues through Kubernetes API so I cannot rely on some external CLI utilities. I tried to edit a queue with `kubectl edit` but unfortunately could not close it this way.

**Environment**:
- Volcano Version: 1.3.0
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
  ```

**Comment by Thor-wl** [comment]
As the design of `queue`, only queues with `closed` status, which means it will no longer receive new coming jobs, can be deleted. `queue` is a concept inheriting from traditional HPC scheduling architectures and widely used for cluster resource sharing and division among departments or groups. As to default scheduler of Kubernets, it's a scheduling for common scenarios. So it contains no `queue`.

**Comment by prokher** [comment]
@Thor-wl , thank you, that is clear. The issues is that I do not know how to close a queue with `kubectl` without using `vcctl`. I assume if I can do it with `kubectl`, then I will be able to do through the Kubernetes API.

**Comment by Thor-wl** [comment]
> @Thor-wl , thank you, that is clear. The issues is that I do not know how to close a queue with `kubectl` without using `vcctl`. I assume if I can do it with `kubectl`, then I will be able to close a queue through the Kubernetes API.

Users can only close queue with `vcctl` now. `Queue` is not a native concept for Kubernetes. So there's no way to use K8s CLI to do that.

**Comment by prokher** [comment]
@Thor-wl, understood. Can I expect that there will be a possibility to close a queue with `kubectl edit`? I thought it is a Kubernetes way of doing things. User modifies Kubernetes object (e.g., through `kubectl edit`) and operator responsible for this object does it best to move it closer to the desired state.

**Comment by Thor-wl** [comment]
@prokher Yes. Perhaps it's hard to push this idea directly to Kubernetes community, but it is possible to develop a CLI plugin to support that.

**Comment by shinytang6** [comment]
Actually you can apply a `Command` crd provided by volcano to do that, vcctl is doing this way. But l believe the community has very little description of this function currently.

**Comment by prokher** [comment]
The issues is still here AFAIK.

**Comment by k82cn** [comment]
> The issues is still here AFAIK.

Emm, so what's the target solution/behaviour?

**Comment by prokher** [comment]
I would expect I can delete a queue through `kubectl delete`. If it is necessary to close it first — OK, I would expect to use `kubectl edit` for this and then delete it with `kubectl delete`.

**Comment by k82cn** [comment]
> I would expect I can delete a queue through `kubectl delete`. If it is necessary to close it first — OK, I would expect to use `kubectl edit` for this and then delete it with `kubectl delete`.

If so, let's have a kubectl plugin for volcano :)

**Comment by prokher** [comment]
It is still needed

**Comment by Thor-wl** [comment]
> It is still needed

I agree with that. It will be more friendly for users to operate the objects.

**Comment by hwdef** [comment]
What if we rename `vcctl` to `kubectl-volcano` and use it as a plugin for `kubectl`

we can close queue by 

```
kubectl volcano queue operate -a close -n test  
```

then, delete the queue

```
kubectl volcano queue delete -n test 
```
If this is cumbersome, we can optimize the command

```
kubectl volcano close queue --name test 
kubectl volcano delete queue --name test
```

**Comment by hwdef** [comment]
@prokher @k82cn @Thor-wl

**Comment by Thor-wl** [comment]
> What if we rename `vcctl` to `kubectl-volcano` and use it as a plugin for `kubectl`
> 
> we can close queue by
> 
> ```
> kubectl volcano queue operate -a close -n test  
> ```
> 
> then, delete the queue
> 
> ```
> kubectl volcano queue delete -n test 
> ```
> 
> If this is cumbersome, we can optimize the command
> 
> ```
> kubectl volcano close queue --name test 
> kubectl volcano delete queue --name test
> ```

Perhaps we can take different designs to the weekly meeting this week. It is an interesting issue. Let's get more voice from the community.

**Comment by prokher** [comment]
In our scenario, we will operate Volcano from the node which does not have `vcctl` installed. Moreover, some parts of the system will work through the Kubernetes REST API, which also knows nothing about `vcctl`. I already shared my considerations [above](https://github.com/volcano-sh/volcano/issues/1687#issuecomment-979910795):

> I would expect I can delete a queue through kubectl delete. If it is necessary to close it first — OK, I would expect to use `kubectl edit` and then delete it with kubectl delete.

Kubernetes seems to follow the declarative approach of describing its objects/resources. IMHO, to be declarative, the queue should have a boolean property `open`, which client can switch to `false` with regular `kubectl edit`.

**Comment by hwdef** [comment]
@I see. You are more expecting to manage the queue only through kubectl. We'll discuss this at our community meeting.

**Comment by hwdef** [comment]
@prokher 
I see. You are more expecting to manage the queue only through kubectl. We'll discuss this at our community meeting.

**Comment by prokher** [comment]
I still need this.

**Comment by hwdef** [comment]
The current situation is that the queue can be deleted even if it is not closed, but the vcjobs in the queue continue to exist, we need to improve this and I have two options in mind.
1. cascade the deletion of vcjobs when the queue is deleted, regardless of the state of the vcjobs under this queue, analogous to namespace
2. set a new field for the queue, such as `spce.isOpen`, by modifying this field, change the open and closed state of the queue, while restoring the previous webhook logic, the queue is not allowed to be deleted if it is not closed

What do you think?
@prokher  @Thor-wl @k82cn @william-wang @shinytang6

**Comment by prokher** [comment]
@hwdef, IMHO seems reasonable, thank you for update.

**Comment by prokher** [comment]
> > @hwdef, IMHO seems reasonable, thank you for update.
> 
> Which of these two options do you prefer?

Actually any of both a quite OK from my point of view.

**Comment by hwdef** [comment]
@prokher At present, the queue can be deleted directly, but the status of the queue cannot be controlled. The function of controlling the status of the queue will be added in the future.
