### ISSUE TITLE
Exists some jobs never to be scheduled

### ISSUE THREAD

**Issue by zen-xu** [volcano-sh/volcano#1689]
**What happened**:

Although cluster have many resources, but some jobs always be pending state.

**What you expected to happen**:

These jobs should be scheduled

**How to reproduce it (as minimally and precisely as possible)**:

It's an accidental phenomenon, only happens 2-4 times

**Anything else we need to know?**:

I found `pg`s of these jobs are not created
I can't find job name from scheduler log
If I restart the scheduler, these pending jobs will be scheduled

So I guess maybe there are something went wrong with the scheduler cache

**Environment**:
- Volcano Version: 1.0
- Kubernetes version (use `kubectl version`): 1.18
- OS (e.g. from /etc/os-release): ubuntu18.04

**Comment by Thor-wl** [comment]
Is there more details about these jobs? Any more phenomena and laws?

**Comment by zen-xu** [comment]
no useful details

**Comment by Thor-wl** [comment]
Well, let's leave this issue and update it whenever this phenomena appears again.

**Comment by zen-xu** [comment]
I found the reason.

Our k8s cluster have 210k pods (contains completed and running)
This will lead the controller hard to sync all pods, so `pg` will never to be created.

**Comment by Thor-wl** [comment]
> I found the reason.
> 
> Our k8s cluster have 210k pods (contains completed and running)
> This will lead the controller hard to sync all pods, so `pg` will never to be created.

Curious about why controller hard to sync all pods. timeout or else?

**Comment by zen-xu** [comment]
> > I found the reason.
> 
> > 
> 
> > Our k8s cluster have 210k pods (contains completed and running)
> 
> > This will lead the controller hard to sync all pods, so `pg` will never to be created.
> 
> 
> 
> Curious about why controller hard to sync all pods. too many pods lead to timeout or else?

Timeout
