### ISSUE TITLE
Unknown error is occurred while launching TFJob

### ISSUE THREAD

**Issue by FatalLin** [volcano-sh/volcano#1690]
**What happened**:
I've already enabled gane scheduling and added the privilege to the cluster role of tf-operator, then I tried to launched a tfjob, and tf-operator prints some error messages without further details repeatedly. 
<img width="1634" alt="截圖 2021-08-22 下午4 51 59" src="https://user-images.githubusercontent.com/5687317/130348710-68df30fb-42b2-432c-8c3c-2b6874255c1f.png">
<img width="1626" alt="截圖 2021-08-22 下午4 52 39" src="https://user-images.githubusercontent.com/5687317/130348713-5bb1fbd1-1fdd-4f74-a1d2-f3ba471b8f5f.png">
<img width="1633" alt="截圖 2021-08-22 下午4 52 47" src="https://user-images.githubusercontent.com/5687317/130348715-51b821ad-630b-4d26-a66b-ad091d672772.png">

**What you expected to happen**:
TFJobs should be launched smoothly.

**How to reproduce it (as minimally and precisely as possible)**:
launched a minikube and installed vocalno via yaml(kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/v1.3.0/installer/volcano-development.yaml
), then install apache submarine(https://github.com/apache/submarine.git, [add the cluster role privilege](https://github.com/apache/submarine/blob/master/helm-charts/submarine/charts/tfjob/templates/cluster-role.yaml#L17-L54), and execute the following command to install: `helm install submarine ./helm-charts/submarine/`).
after all the deployments are ready, execute `kubectl port-forward --address 0.0.0.0 service/submarine-traefik 8080:80`,
then `./submarine-cloud-v2/hack/run_frontend_e2e.sh experimentIT` to launch unit test.
the similar case should be reproduce after all is done, and you could check the log of tf-operator in default namespace.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.3
- Kubernetes version (use `kubectl version`):v1.19.4
- Cloud provider or hardware configuration: MacBook Pro (15-inch, 2018)
- OS (e.g. from /etc/os-release):Big Sur 11.5.2
- Kernel (e.g. `uname -a`):Darwin C02XH3R9JGH6 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
- Install tools: yaml
- Others:

**Comment by shinytang6** [comment]
@FatalLin It seems that you didn't install podgroup crd. If you enable gang in tf-operator, you need to install that.

**Comment by FatalLin** [comment]
@shinytang6  It seems those necessary crd had also been installed with installer to me.
<img width="1409" alt="截圖 2021-08-22 下午9 13 12" src="https://user-images.githubusercontent.com/5687317/130356574-2591370e-21bc-476d-8b3b-05cc51a834e6.png">

**Comment by shinytang6** [comment]
Sorry, @FatalLin  can you show your version of tf-operator?
l did not take a closer look, but my guess is:
1. For one job, tf-operator first create pods, and then create podgroups.
2. The pod webhook of volcano will check the pod creation until the corresponding pg ready, or it will refuse to creating pods requests.
3. The order of vcjob creation is to create podgroup first, then create pods after ready

I think this problem lies on the order of creation, the essential reason is that the integration of tf-operator and volcano is not perfect.

**Comment by FatalLin** [comment]
@shinytang6 Hmm, the tf-operator we currently used is tf_operator-v1.1.0-g92389064, do you have any suggestion which version may have better compatibility?

**Comment by shinytang6** [comment]
> @shinytang6 Hmm, the tf-operator we currently used is tf_operator-v1.1.0-g92389064, do you have any suggestion which version may have better compatibility?

maybe you can upgrade tf-operator to v1.2.0 to have a test

**Comment by FatalLin** [comment]
@shinytang6  I took your suggestion, build a tf-operator image from their 1.2 branch and run again, then I hit following errors when I enable gang scheduling. (ps and worker pods are launched successfully when I turn off gan scheduling). 
`E0824 16:13:34.730856       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 90 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x153e720, 0x245e5a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/runtime/runtime.go:48 +0x82
panic(0x153e720, 0x245e5a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).calcPGMinResources(0xc0002f7320, 0xc000000002, 0xc0003b1560, 0x1)
	/go/pkg/mod/github.com/kubeflow/common@v0.3.3/pkg/controller.v1/common/job.go:429 +0x168
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).ReconcileJobs(0xc0002f7320, 0x16db720, 0xc0000be680, 0xc0003b1560, 0xc00019e930, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/kubeflow/common@v0.3.3/pkg/controller.v1/common/job.go:300 +0x1fae
github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).syncTFJob(0xc0002f7320, 0xc000042cc0, 0x25, 0x0, 0x0, 0x0)
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:335 +0x5b2
github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).processNextWorkItem(0xc0002f7320, 0x203a22616d656800)
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:272 +0x6e0
github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).runWorker(0xc0002f7320)
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:222 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00026e350)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00026e350, 0x3b9aca00, 0x0, 0x20202020200a2c01, 0xc0000ae0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00026e350, 0x3b9aca00, 0xc0000ae0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).Run
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:208 +0x2c4
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13bd3b8]
goroutine 90 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/runtime/runtime.go:55 +0x105
panic(0x153e720, 0x245e5a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).calcPGMinResources(0xc0002f7320, 0xc000000002, 0xc0003b1560, 0x1)
	/go/pkg/mod/github.com/kubeflow/common@v0.3.3/pkg/controller.v1/common/job.go:429 +0x168
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).ReconcileJobs(0xc0002f7320, 0x16db720, 0xc0000be680, 0xc0003b1560, 0xc00019e930, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/kubeflow/common@v0.3.3/pkg/controller.v1/common/job.go:300 +0x1fae
github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).syncTFJob(0xc0002f7320, 0xc000042cc0, 0x25, 0x0, 0x0, 0x0)
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:335 +0x5b2
github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).processNextWorkItem(0xc0002f7320, 0x203a22616d656800)
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:272 +0x6e0
github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).runWorker(0xc0002f7320)
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:222 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00026e350)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00026e350, 0x3b9aca00, 0x0, 0x20202020200a2c01, 0xc0000ae0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00026e350, 0x3b9aca00, 0xc0000ae0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.16.15/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow.(*TFController).Run
	/go/src/github.com/kubeflow/tf-operator/pkg/controller.v1/tensorflow/controller.go:208 +0x2c4`
do you have any idea on it?
