### ISSUE TITLE
golint

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#1694]
the lint does not check out the golint error and passed.
#### Why is this needed:
![image](https://user-images.githubusercontent.com/21003791/130718656-b44caf7f-6cdb-49be-a5bf-fde9e4883461.png)

**Comment by Thor-wl** [comment]
@gy95 Is golint out of the checkout scope at the latest PR?

**Comment by gy95** [comment]
yes, because golint is archived, so remove it it PR
