### ISSUE TITLE
tf-operator create PodGroup error

### ISSUE THREAD

**Issue by qiankunli** [volcano-sh/volcano#1695]
tf-operator version: v0.5.3, it is a low version
volcano version: v1.3.0

tf-operator log
```
{"filename":"tensorflow/controller.go:444","job":"xdl-system.v1-tensorflow-0728-1","level":"warning","msg":"Sync PodGroup v1-tensorflow-0728-1: the server could not find the requested resource (post podgroups.scheduling.incubator.k8s.io)","time":"2021-08-25T08:32:45Z","uid":"58463664-21e2-4f7b-a8e8-6745781fb548"}
```
can volcano v1.3.0 accept groupVersion=scheduling.incubator.k8s.io/v1alpha1

公司内目前使用的 tf-operator 非常低，会创建  scheduling.incubator.k8s.io/v1alpha1 的PodGroup
我想将volcano 从v0.3 升级到 v1.3.0，v1.3.0 的volcano 只支持 scheduling.volcano.sh/v1beta1 的PodGroup，所以老版本 tf-operator 创建PodGroup 会报错

CustomResourceDefinition 有什么办法能让scheduling.incubator.k8s.io/v1alpha1 的PodGroup 当  scheduling.volcano.sh/v1beta1 的PodGroup 用嘛

**Comment by bug-developer021** [comment]
> tf-operator version: v0.5.3, it is a low version volcano version: v1.3.0
> 
> tf-operator log
> 
> ```
> {"filename":"tensorflow/controller.go:444","job":"xdl-system.v1-tensorflow-0728-1","level":"warning","msg":"Sync PodGroup v1-tensorflow-0728-1: the server could not find the requested resource (post podgroups.scheduling.incubator.k8s.io)","time":"2021-08-25T08:32:45Z","uid":"58463664-21e2-4f7b-a8e8-6745781fb548"}
> ```
> 
> can volcano v1.3.0 accept groupVersion=scheduling.incubator.k8s.io/v1alpha1
> 
> 公司内目前使用的 tf-operator 非常低，会创建 scheduling.incubator.k8s.io/v1alpha1 的PodGroup 我想将volcano 从v0.3 升级到 v1.3.0，v1.3.0 的volcano 只支持 scheduling.volcano.sh/v1beta1 的PodGroup，所以老版本 tf-operator 创建PodGroup 会报错
> 
> CustomResourceDefinition 有什么办法能让scheduling.incubator.k8s.io/v1alpha1 的PodGroup 当 scheduling.volcano.sh/v1beta1 的PodGroup 用嘛

你好！请问您怎么解决的？ 我也面临类似的问题，pytorch operator目前好像只支持`scheduling.incubator.k8s.io`，所以不得不转向volcano v0.3，但是volcano v0.3在1.20版本的k8s集群上无法成功部署。
