### ISSUE TITLE
yaml安装失败

### ISSUE THREAD

**Issue by zhuyaguang** [volcano-sh/volcano#1699]
**What happened**:

使用一键式yaml安装
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml

**What you expected to happen**:

volcano 安装OK

**How to reproduce it (as minimally and precisely as possible)**:

安装kind kubectl 后，发现volcano 安装不起来 
volcano-system 一个pod CrashLoopBackOff
![image](https://user-images.githubusercontent.com/8857976/131203910-79065f00-80f9-4c10-9886-00e976e8bea8.png)

**Anything else we need to know?**:

看下报错
 unknown flag ：--admission-conf

![image](https://user-images.githubusercontent.com/8857976/131204007-cabd65d8-3a9f-4548-ae77-d35c2bd0f750.png)

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):1.22
- Install tools:yaml
- Others:

**Comment by shinytang6** [comment]
pls refer to https://github.com/volcano-sh/volcano/issues/1663, it's a bug not fixed right now.

**Comment by Thor-wl** [comment]
Latest webhook image has been pushed to dockerhub, please have a try.

**Comment by Thor-wl** [comment]
fix: https://github.com/volcano-sh/volcano/pull/1701

**Comment by adamwoolhether** [comment]
> Latest webhook image has been pushed to dockerhub, please have a try.

i noticed the latest docker image doesn't properly schedule jobs, they're always stuck in "pending".... i used my local 1.3.0 instead of latest and it works fine.

**Comment by Thor-wl** [comment]
> > Latest webhook image has been pushed to dockerhub, please have a try.
> 
> i noticed the latest docker image doesn't properly schedule jobs, they're always stuck in "pending".... i used my local 1.3.0 instead of latest and it works fine.

Can you give an issue about the scenario description and operation steps?

**Comment by Thor-wl** [comment]
> > Latest webhook image has been pushed to dockerhub, please have a try.
> 
> i noticed the latest docker image doesn't properly schedule jobs, they're always stuck in "pending".... i used my local 1.3.0 instead of latest and it works fine.

I've submitted a test job and everything goes well.
