### ISSUE TITLE
Plugin `predicates` won't remove pod from node during the rollback of scheduling transaction

### ISSUE THREAD

**Issue by eggiter** [volcano-sh/volcano#1714]
**What happened**:
+ `Predicates.DeallocateFunc` won't remove pod from node(which defined in `predicatesPlugin.OnSessionOpen.nodeMap`) during the rollback of scheduling transaction(or say statement discarded).
+ Instead, it leaves an error log: "predicates, update pod xxx allocate from NOT EXIST node []"

**What you expected to happen**:
+ Obviously it should successfully remove the pod assigned on that node when scheduling transaction is rollbacked.

**How to reproduce it (as minimally and precisely as possible)**:
+ Turn on plugin `predicates` & `gang`.
+ Scheduling a podgroup with 2 pods, and one of the pod(let's say pod1) can be successfully scheduled(let's say on node1) and the other is unschedulable.
+ Thus the entire podgroup is gang unschedulable, and the scheduling transaction should be rollbacked.
+ This bug occurs there when `node.RemoveTask(task)` is called in func statement.unallocate.
   - It set node name of the task to empty(which i dont know why) and hence the node can not be found in `Predicates.DeallocateFunc` due to the empty nodeName.
     ```go
     ti.NodeName = "" // remove nodename from taskinfo
     ```

**Anything else we need to know?**:
+ It seams the code i cited above was introduced in PR #1517 . Why changing that and what's this all about?

**Comment by lowang-bh** [comment]
This can be removed as there is `task.NodeName = ""` already in unpipeline, unallocate.

**Comment by eggiter** [comment]
> This can be removed as there is `task.NodeName = ""` already in unpipeline, unallocate.

@lowang-bh fixed in #1716 , PTAL
