### ISSUE TITLE
Facing issues while installing Volcano using Helm

### ISSUE THREAD

**Issue by odidev** [volcano-sh/volcano#1717]
**What happened**: 

I am trying to install Volcano on the Linux/AMD64 platform using [helm charts method](https://volcano.sh/en/docs/installation/#install-with-helm), and getting below issue while executing “`helm install volcano helm/chart/volcano/ -n volcano-system`” command: 
~~~ 
Error: CustomResourceDefinition.apiextensions.k8s.io "jobs.batch.volcano.sh" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[tasks].items.properties[template].properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[tasks].items.properties[template].properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property] 
~~~ 
This is the same issue occurred here < https://github.com/volcano-sh/volcano/issues/1445 >, and the resolution was to edit the **crd_version** from **v1beta1** to **v1**. 
I made the same version change (**v1**) in the helm’s values.yaml file, and helm installation is successful now. 

Do you have any plans to edit the crd_version in the source code, for helm installation? I am happy to raise a PR for the same. 

**What you expected to happen**: Installation should be successful.

**How to reproduce it (as minimally and precisely as possible)**:  `helm install volcano helm/chart/volcano/ -n volcano-system`

**Environment**:
- Volcano Version: master branch
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): Linux/AMD64
- Install tools: Helm Charts (v3.X)

**Comment by odidev** [comment]
Hello Team, can you please review this issue?

**Comment by william-wang** [comment]
@odidev Thanks for your report. I have added to the pipeline and get you reply as soon as possible.

**Comment by Thor-wl** [comment]
ref: https://github.com/volcano-sh/volcano/pull/1919
