### ISSUE TITLE
Premption not happening between high priority and low priority jobs

### ISSUE THREAD

**Issue by Robert-Christensen-visa** [volcano-sh/volcano#1720]
**What happened**:

When submitting several jobs, some with high priority and some with low priority, the high priority jobs do not preempt the lower priority jobs.  Both jobs are running in the same queue.

**What you expected to happen**:

If a low priority job is running and a pending high priority job is queued.  There there is not sufficient capacity for both to run, I would expect the lower priority job to stop running so the higher priority job can run.

**How to reproduce it (as minimally and precisely as possible)**:

This is my `volcano-scheduler.conf`

``` yaml
actions: "enqueue, allocate, preempt"
tiers:
- plugins:
  - name: priority
- plugins:
  - name: proportion
```

I run the following script to setup the environment and run the jobs.  I am running on my local machine, which has a capacity of 12CPUs and 8GB memory.

``` bash
cat <<EOF | kubectl apply -f -
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: basic-queue
  annotations:
    "volcano.sh/hierarchy": "root/basic"
    "volcano.sh/hierarchy-weights": "1/1"
spec:
  weight: 1
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
EOF

job_template_file=$(mktemp)
cat <<EOF > ${job_template_file}
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vcjob-job-<id>
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: <priority>
  policies:
    - event: PodEvicted
      action: RestartTask
  maxRetry: 100
  queue: <queue>
  tasks:
    - replicas: 2
      name: "x"
      template:
        metadata:
          name: core
        spec:
          priorityClassName: <priority>
          terminationGracePeriodSeconds: 10
          containers:
            - image: ubuntu
              imagePullPolicy: IfNotPresent
              name: ubuntu
              command: ['sh', '-c', "sleep 600000"]
              resources:
                requests:
                  cpu: "1000m"
                  memory: "256Mi"
          restartPolicy: OnFailure
EOF

for id in $(seq 6)
do
    sed 's/<queue>/basic/g' < ${job_template_file} | \
    sed "s/<id>/low-$id/g" | \
    sed "s/<priority>/low-priority/g" | \
    kubectl apply -f -
done

sleep 5

for id in $(seq 6)
do
    sed 's/<queue>/basic/g' < ${job_template_file} | \
    sed "s/<id>/high-$id/g" | \
    sed "s/<priority>/high-priority/g" | \
    kubectl apply -f -
done
```

After the script runs and I wait for things to stabilize I look at the number of jobs running from high and low priority:

``` console
$ kubectl get pods | grep Running | cut -d- -f 1 | sort | uniq -c
  11 low
```

I only see low priority jobs running.  Never anything from the high priority.  I would expect it would be the other way around.  After some
time I would expect the high priority jobs to preempt the low priority jobs.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.3.0
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Running in docker-desktop on a mac
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Thanks for your report. I reproduced the phenomenon and preempt action did not work. I'll try to fix it.

**Comment by Thor-wl** [comment]
The root reason is that the plugins(`priority` and `prorition`) in the scheduler configurations contains no `JobStarving` function, which is only contained in `gang` and `tdm` plugins. So `preempt` action can not pick out jobs which are potential high prority jobs. You can add  `gang` plugin into configuration and have a try again.

**Comment by Thor-wl** [comment]
I think it is not so reasonable to bind `gang` plugin with `JobStarving` function. If users don't need to use `gang`, he/she can also use `preempt` action with just `priority` plugin.

**Comment by william-wang** [comment]
> I think it is not so reasonable to bind `gang` plugin with `JobStarving` function. If users don't need to use `gang`, he/she can also use `preempt` action with just `priority` plugin.

'JobStarving' function should be implemented in priority as well.

**Comment by Thor-wl** [comment]
How about have a test with master branch and the following configuration:
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```
As what I tested, it works well. @Robert-Christensen-visa

**Comment by zhiyxu** [comment]
> How about have a test with master branch and the following configuration:
> 
> ```
> apiVersion: v1
> data:
>   volcano-scheduler.conf: |
>     actions: "enqueue, allocate, preempt, backfill"
>     tiers:
>     - plugins:
>       - name: priority
>       - name: gang
>       - name: conformance
>     - plugins:
>       - name: drf
>       - name: predicates
>       - name: proportion
>       - name: nodeorder
>       - name: binpack
> ```
> 
> As what I tested, it works well. @Robert-Christensen-visa

Hello @Thor-wl the preempt action still doesn't work using default scheduling config, and I found following logs:
```
I0918 08:37:35.660140       1 gang.go:97] Can not preempt task <default/job-2-nginx-0> because job job-2 ready num(1) <= MinAvailable(1) for gang-scheduling
```
The preempt stopped due to the `gang` plugin implement `preemptableFn` func and it says, once preempting victim breaks gang scheduling policy, it would stopped.

I think it's unreasonable to consider gang scheduling when preempting, the custom only want to preempt due to priority, although breaking the gang scheduling policy of currently running pods and podgroup.

Could you please look at this issue.

**Comment by Thor-wl** [comment]
> > How about have a test with master branch and the following configuration:
> > ```
> > apiVersion: v1
> > data:
> >   volcano-scheduler.conf: |
> >     actions: "enqueue, allocate, preempt, backfill"
> >     tiers:
> >     - plugins:
> >       - name: priority
> >       - name: gang
> >       - name: conformance
> >     - plugins:
> >       - name: drf
> >       - name: predicates
> >       - name: proportion
> >       - name: nodeorder
> >       - name: binpack
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As what I tested, it works well. @Robert-Christensen-visa
> 
> Hello @Thor-wl the preempt action still doesn't work using default scheduling config, and I found following logs:
> 
> ```
> I0918 08:37:35.660140       1 gang.go:97] Can not preempt task <default/job-2-nginx-0> because job job-2 ready num(1) <= MinAvailable(1) for gang-scheduling
> ```
> 
> The preempt stopped due to the `gang` plugin implement `preemptableFn` func and it says, once preempting victim breaks gang scheduling policy, it would stopped.
> 
> I think it's unreasonable to consider gang scheduling when preempting, the custom only want to preempt due to priority, although breaking the gang scheduling policy of currently running pods and podgroup.
> 
> Could you please look at this issue.

Yes, the comments above from @william-wang and me also think so. We will separate preemtion from gang scheduling.

**Comment by k82cn** [comment]
> 'JobStarving' function should be implemented in priority as well.

let's have a new plugin for starving :)
