### ISSUE TITLE
Queues are always OVERUSED when plugin proportion is disabled

### ISSUE THREAD

**Issue by eggiter** [volcano-sh/volcano#1724]
**What happened**:
- Queues are **always overused** when there is no `UnderUsedResourceFn` is added (i.e. plugin `proportion` is disabled).
  - https://github.com/volcano-sh/volcano/commit/012c2a26068a144813866c96579bbe717a0ddf74#diff-3dcbd15d9e1bf118608b4eedcaadc5cc7bdb9f60b482ad0ca7238ada5ad9e32cR208
  ```go
  if !ssn.UnderusedResources(queue).Contains(taskRequest) {
      klog.V(3).Infof("Queue <%s> is overused when considering task <%s>, ignore it.", queue.Name, task.Name)
      continue
  }
  ```
- It was introduced in PR #1637 .

**What you expected to happen**:
- Queue is always underused when there is no `UnderUsedResourceFn` is added, i.e.: `ssn.UnderusedResources(queue).Contains(taskRequest)` returns true.
- The following scheduling cycle can continue to run.

**How to reproduce it (as minimally and precisely as possible)**:
- Do not enable plugin `proportion` and do not use any feature related to that.
  - Only turn on plugin predicates & gang, and use the default queue.
- Gang scheduling any podgroup, it will always fail due to queue overused.

**Anything else we need to know?**:
+ @Thor-wl PTAL.

**Comment by william-wang** [comment]
It make sense that proportion is not enabled at all scenario. The UnderusedResources should be enhanced.
