### ISSUE TITLE
record label `volcano.sh/queue-name: default` on pod

### ISSUE THREAD

**Issue by qiankunli** [volcano-sh/volcano#1734]
in grafana dashboard `Volcano Queue View` ，there is a Variables whose name is "queue"

![729C4749-757B-41C3-8FC5-B0B8DF749018](https://user-images.githubusercontent.com/8024725/132489290-e4892c98-5bb4-4c38-9347-aa2464cc004f.png)

for example, panel `Running job` use metric `kube_pod_volcano_container_status_running{job="kube-state-metrics",queue="$queue"}`, label=queue come from pod label `volcano.sh/queue-name`

when user create vcjob, it will create pod with label = `volcano.sh/queue-name` normally, but if user create tfjob/pytorchjob/mpijob, it will create pod without the label, leading to no data in grafana

so I suggest that volcano update pod with adding label `volcano.sh/queue-name` when bind pod with node

**Comment by alcorf-mizar** [comment]
> /assign @alcorf-mizar Please take a look. THX.
Confused account. @alcorj-mizar Please take a look.
