### ISSUE TITLE
The queue had been turned to Unknown status

### ISSUE THREAD

**Issue by fleeto** [volcano-sh/volcano#1737]
**What happened**:  I'd closed it and delete a pending job in it, then the queue will be 'Unknown'

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

A script like that:

~~~bash
#!/bin/sh

RES=110
cat <<EOF | kubectl apply -f -
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: bq-${RES}
spec:
  weight: 1
  reclaimable: false
  capability:
    cpu: 800m
EOF

cat <<EOF | kubectl apply -f -
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-${RES}
spec:
  minAvailable: 1
  schedulerName: volcano
  queue: bq-${RES}
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: sleep
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
          - image: dustise/sleep:v0.9.8
            name: sleep
            resources:
              requests:
                cpu: 150m
              limits:
                cpu: 150m
            restartPolicy: Never
EOF

vcctl job list
vcctl queue list
vcctl queue operate -n bq-${RES} -a close
vcctl job delete -N job-${RES}
vcctl queue list
~~~

**Anything else we need to know?**:

**Environment**:
- Volcano Version:

~~~plaintext
API Version: v1alpha1
Version: latest
Git SHA: 3f7a41bd7eef7901f50ed971dbcc194c017c9b70
Built At: 2020-08-14 09:44:35
Go Version: go1.14.6
Go OS/Arch: linux/arm64
~~~

- Kubernetes version (use `kubectl version`): 1.19.14
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):  Ubuntu 20.04.2 LTS 
- Kernel (e.g. `uname -a`): Linux single 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 19:28:28 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: YAML
- Others:

**Comment by Thor-wl** [comment]
I've tried to reproduce it and got something different but still not correct. When I executed to close the queue, it kept `closing`. After I deleted the vcjob, the queue turned to be `closed`. I will tried to fix it.

**Comment by Thor-wl** [comment]
I've taken this case reproduced many times again with the mater branch and everything goes well. The output can be referred to as follows.
![截图](https://user-images.githubusercontent.com/61179420/167335289-d2bc3451-ebdc-4d2c-85e6-ab8be1dd3160.PNG)
