### ISSUE TITLE
support record Legency reason

### ISSUE THREAD

**Issue by qiankunli** [volcano-sh/volcano#1739]
![image](https://user-images.githubusercontent.com/8024725/132837791-2147867e-0356-4c1f-9ffa-76e5d5a005ee.png)

上图k8s event ，有特定的几个类型，将每个类型的event 个数记录下来，那么一些错误的event 很多的话，就说明集群出问题了。
我这两天 的工作是分析 volcano pg调度延迟（从pg创建到所有pod可以执行），发现总有一些任务调度延迟超过8分钟，要仔细分析他们的原因。一般来说，pod或pg 不能开始的原因就那几个：内存不够，gpu不够等，如果每个原因作为一个metric 或metric的label，每次发生这些原因就加1，就可以方便的查看pg延迟的主要原因，进而做出决策。

**Comment by Thor-wl** [comment]
关于延时分析，可以提供系统的设计和说明文档吗

**Comment by qiankunli** [comment]
> 关于延时分析，可以提供系统的设计和说明文档吗

首先是梳理 无法为pod/task/job 分配node 的原因。假设有一个metric，label包含 reason,jobName,queueName，count类型。
allocate.go 里有许多原因导致一个task 无法bind node，进而ignore，此时task 处理逻辑 提前结束时，直接metric count加1。
这样应该可以做整体、queue维度、全局维度的延迟原因分析了。
