### ISSUE TITLE
Optimize the throughput of scheduler

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#1740]
#### What would you like to be added:
Optimize the scheduler throughput for high performance workload.

#### Why is this needed:
As more and more high performance workload are migrating to kubernetes. Current throughtput of scheduler can not meet throughput requirement for large scale job submitting scenario.

**Comment by justadogistaken** [comment]
k8s maintains the snapshot in the scheduler, and use generation and double linked list to avoid clone all information every scheduling period. Is that possible in volcano?

**Comment by k82cn** [comment]
> k8s maintains the snapshot in the scheduler, and use generation and double linked list to avoid clone all information every scheduling period. Is that possible in volcano?

That's reasonable to me :)
