### ISSUE TITLE
Request to support more NUMA alignment features

### ISSUE THREAD

**Issue by shinytang6** [volcano-sh/volcano#1749]
#### What would you like to be added:
Currently we supported cpu numa alignment in volcano, k8s has already supported memory alignment and PCI devices alignment in version 1.22, it will be great to complement these features in volcano )

ref: https://kubernetes.io/blog/2021/08/11/kubernetes-1-22-feature-memory-manager-moves-to-beta/

sub tasks

- [x] CPU NUMA alignment
- [ ] Memory NUMA alignment

**Comment by justadogistaken** [comment]
Does volcano  support numa-aware just for predicate and priority at present? But fail to apply the result to kubelet(final node-level numa placement), right?

**Comment by huone1** [comment]
> Does volcano support numa-aware just for predicate and priority at present? But fail to apply the result to kubelet(final node-level numa placement), right?

yes, it is, because the kubelet doesn't provide a interface to support to use the resource topology allocated of shceduler
