### ISSUE TITLE
Request to add run begin/end time for vcjob

### ISSUE THREAD

**Issue by HecarimV** [volcano-sh/volcano#1750]
#### What would you like to be added:
I want to get the run beginTime and endTime of the vcjob.
Maybe we can add these info into job annotations like this:
```go
Annotations:  volcano.sh/job-begintime: 2021-09-15 13:24:10
              volcano.sh/job-endtime: 2021-09-15 13:45:55
```

#### Why is this needed:
Sometimes we need to check the actual running time, but not just simply creationTimestamp or deletionTimestamp.

**Comment by shinytang6** [comment]
+1, l think these fields should be added to crd definitions of `Job.Status`

**Comment by HecarimV** [comment]
yeah!  It's more appropriate to put it in the status field. 
Both approaches are acceptable

**Comment by Thor-wl** [comment]
I agree with that, too. It's also useful for monitoring.

**Comment by k82cn** [comment]
Can we add this to job status?

**Comment by HecarimV** [comment]
> Can we add this to job status instead of annotations?

I think it's ok to add this to job status.

**Comment by HecarimV** [comment]
> Can we add this to job status instead of annotations?

I think it's ok to add this to job status.

**Comment by shinytang6** [comment]
@HecarimV Do you have time or are you interested in helping with this ?

**Comment by HecarimV** [comment]
> @HecarimV Do you have time or are you interested in helping with this ?

I'm ok to work on it :)
