### ISSUE TITLE
Cromwell workflows not working

### ISSUE THREAD

**Issue by fferrann** [volcano-sh/volcano#1761]
**What happened**: Volcano (vcctl) only accepts .yaml file format as input for creating jobs. Cromwell outputs bash script files which aren't accepted by vcctl.

**What you expected to happen**: Volcano to accept Cromwell output's as input format (i.e. bash script) as per the documentation here https://github.com/broadinstitute/cromwell/blob/develop/docs/backends/Volcano.md

**How to reproduce it (as minimally and precisely as possible)**:
Add Volcano backend to Cromwell
Create a HelloWorld workflow and submit it to Cromwell
Cromwell will try to execute the Volcano backend and this error is thrown:
Failed to run job: only support yaml file

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.20.9
- Cloud provider or hardware configuration: AKS
- OS (e.g. from /etc/os-release): Linux Ubuntu
- Kernel (e.g. `uname -a`): linux/amd64
- Install tools:
- Others:

**Comment by fferrann** [comment]
Issue is still reproducible.

**Comment by Thor-wl** [comment]
Sorry for reply late. It has not been reproduced here. Will take a try later. Besides, perhaps we should reivew the latest cromwell version and support it.

**Comment by fferrann** [comment]
Issue is valid
