### ISSUE TITLE
scheduling with update from v1.2.0 to v1.4.0

### ISSUE THREAD

**Issue by regadas** [volcano-sh/volcano#1775]
**What happened**:

volcano update from 1.2.0 to 1.4.0. With the newest version if there are not enough resources `PodGroup`s are kept in `Pending` phase and cluster autoscaler does not trigger to provision more resources. 

Did I miss smth in the latest version?

**What you expected to happen**:

I was expecting it to work as in 1.2.0

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.22.2
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Container OS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Well, pls give more details about your testing steps so that I can reproduce it. THX.

**Comment by yolgun** [comment]
Hi @Thor-wl. I am able to reproduce this issue using a GKE Kubernetes cluster with autoscaling enabled. Creating a podgroup that can't be satisfied with current resources is enough. Prior to v1.4.0, `scaleUp` is triggered which can be seen in events. After v1.4.0, this event doesn't happen.  

Not sure on how to reproduce it locally, but we have investigated it further on our side. It happens after [this PR](https://github.com/volcano-sh/volcano/pull/1672). With this, volcano has started putting custom reasons like `Undetermined` into a pod's `status.conditions.reason` field. Kubernetes Cluster Autoscaler uses the same field to detect ScaleUp needs. But it only checks `Unschedulable`. Related piece of code at the Cluster Autoscaler can be seen [here](https://github.com/kubernetes/autoscaler/blob/2542e8c884a8e25634d3b8f43243fa8706007f30/cluster-autoscaler/utils/kubernetes/listers.go#L170).

I tested it by reverting the PR on top of v1.5.0-beta and autoscaling worked as before.

I'd appreciate any help on solving this in volcano. Both autoscaling and batch-scheduling is important to our setup.

**Comment by fadi-artera** [comment]
Hello we are having the same issues and would appreciate if there's an update on this issue.

**Comment by Thor-wl** [comment]
Thanks, guys. Let me take a look at that.

**Comment by brickyard** [comment]
Could we re-open and make an update here?  Volcano is pretty much unusable with Cluster Autoscaler and Karpenter with the "Undetermined" reason.  Is there any reason why we shouldnt revert the PR to gain back compatibility with the autoscaling\cloud eco-system?  Would love to hear from the team on this.

**Comment by william-wang** [comment]
@brickyard Of course, please update here. Maybe the scheduling reason enhanced in pr#1672 missed to consider the interacting between scheduler and the autoscaler. @Thor-wl please continue to work on this to fix it. if there is not a way to take care of both the autoscaling and scheduler reason enhancement. We need to revert to keep the compatibility firstly.

**Comment by tgaddair** [comment]
This issue is still affecting Karpenter users. Can we re-open and find a way to set the pod status to `Unschedulable` instead of "Undetermined"? Is there a reason it should be (or need to be) "Undetermined"?

**Comment by tgaddair** [comment]
I think there should be no issues with reverting #1672, as the intent was to provide more information to the user. But if it breaks compatibility with cluster autoscalers, that seems like a very steep price to pay for better logging. Maybe this PR could be re-submitted by just annotating the status message with this info, instead of changing the `Unschedulable` reason?
