### ISSUE TITLE
When installing volcano by “./hack/local-up-volcano.sh” , an error is reported No such image: volcanosh/vc-controller-manager:b0e803d8cbb120d9951f2ad24dc1f9d9769f05d7

### ISSUE THREAD

**Issue by dotiiiian** [volcano-sh/volcano#1787]
<!-- This form is for bug reports ONLY!

If you're looking for a help then check our [Slack Channel](https://cloud-native.slack.com/messages/volcano) or have a look at our [dev mailing](https://groups.google.com/forum/#!forum/volcano-sh) 

**What happened**:When installing volcano by “./hack/local-up-volcano.sh” , an error is reported：

Makefile:78: recipe for target 'image_bins' failed
make: *** [image_bins] Error 1
Checking kind
Installing kind ...
go: github.com/agiledragon/gomonkey/v2@v2.1.0: Get "https://proxy.golang.org/github.com/agiledragon/gomonkey/v2/@v/v2.1.0.mod": dial tcp 142.251.43.17:443: i/o timeout
Running kind: [kind create cluster --name volcano ]
/home/ubuntu/src/volcano.sh/volcano/hack/../hack/lib/install.sh: line 22: kind: command not found

Checking whether the required images exist
Error: No such image: volcanosh/vc-controller-manager:b0e803d8cbb120d9951f2ad24dc1f9d9769f05d7
ERROR: volcanosh/vc-controller-manager:b0e803d8cbb120d9951f2ad24dc1f9d9769f05d7 does not exist

**What you expected to happen**:Successfully installed 
[
**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:]([url](`url`)) Use volcano-development.yaml to install successfully 

**Environment**:
- Volcano Version:1.3.0
- Kubernetes version (use `kubectl version`):k8s1.21.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu20.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
Can you provide your volcano version?

**Comment by dotiiiian** [comment]
volcano1.4.0 k8s1.21.3  ubuntu20.04 golang1.16.6
