### ISSUE TITLE
spf13/cobra  is too old to use, need update.

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1798]
What happened:

Active reliance on software is too old. github.com/spf13/cobra v1.0.0 is publish on 20 Oct 2019, and newest is v1.2.1
 [cobra/blob](https://github.com/spf13/cobra/blob/v1.0.0/go.sum)

Environment:

```
Volcano Version: v1.4.0
Kubernetes version (use kubectl version):1.22,1.22.1
Go: 1.17,1.17.1
```

**Comment by marffin** [comment]
Hi @zishen , I'd like to take this issue.
