### ISSUE TITLE
Whether the queue is considered to add absolute value parameters to cooperate with the proportion

### ISSUE THREAD

**Issue by zhiyuone** [volcano-sh/volcano#1807]
#### What would you like to be added:
add min resource for `Queue.Spec`.
such as `MinResource v1.ResourceList`.
It is a soft limit, unused resources can be used by other queues, but must be returned when used(same as queue.deserved), calculate the proportion when the minimum resources are satisfy.
#### Why is this needed:
> case 1:
We have `4 cpu` and `1 gpu`, and two queue (`q1`, `q2`), then we want `q1` have `half of cluster cpu` and `1 gpu`,  `q2` have `half of cluster cpu` but `none gpu`.
In this case we can set`q1.Spec.MinResource: 1 gpu`.

> case 2:
We have dynamic scaling cluster, and queue reclaim is enable. `q1` and `q2` in cluster, and each have half of cluster resource.
Before cluster scaling to upper limit, and waitting node scale up, we didn't wish tigger reclaim.

> case 3:
We add nodes to certainty queue, then we have to adjust the queue weight carefully.
Not all nodes have the same resource.

**Comment by Thor-wl** [comment]
> I am trying to implement fixed deserved resource in the queue, not proportional distribution. Each queue must have a certain amount of resource guarantee. Is better understand replace the description with `MinResource v1.ResourceList` to `queue.Spec.Guarantee v1.ResourceList` ？

OK. Reserving resource for specified queue is common scenario and we got some feedback.  I think https://github.com/volcano-sh/volcano/pull/1771 is what you want. Pls take a look.
