### ISSUE TITLE
Recommended way to combine with vGPU plugin

### ISSUE THREAD

**Issue by summerisc** [volcano-sh/volcano#1815]
I am considering adopting vGPU plugin(so that GPU can be cut into smaller pieces to let more engineers using one card at the same time) and combine that with volcano so that it can schedule resources like GPU and CPU.

Not sure if it's a common use case or if anyone faces the same siautation or can provide a recommended way to combine both resource scheduling + gpu virtualization at the same time. Any advise/experience sharing is much appreciated.

**Comment by k82cn** [comment]
which vGPU are you refering ? AFAIK, volcano can work well in that scenario :)

**Comment by summerisc** [comment]
I am referring specifically to a case like GPU sharing, so each task can allocate a portion of GPU instead of a whole GPU card. It seems volcano has a device plugin but does not have the GPU sharing feature? So just looking into other plugins to work with volcano together.
