### ISSUE TITLE
 k8S default scheduler and volcano are used at the same time, will there be conflicts in some scenes ？

### ISSUE THREAD

**Issue by veast** [volcano-sh/volcano#1827]
Hi! We want to use Volcano for some jobs and K8S default scheduler for some other jobs. May this cause problems? For example, when the scheduler selects nodes at the same time?

**Comment by shinytang6** [comment]
You can refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/multi-scheduler.md and have a try, it can help you automatically divide resources.

However, each scheduler still has global cache, which l think there will be problems when using some volcano features such like queues.

**Comment by k82cn** [comment]
> You can refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/multi-scheduler.md and have a try, it can help you automatically divide resources.

That'll help ! And suggest to schedule system daemon by default scheduler and scheduler business workload by volcano :)

> However, each scheduler still has global cache, which l think there will be problems when using some volcano features such like queues.

We should add node selector for volcano :)

**Comment by k82cn** [comment]
xref: https://github.com/volcano-sh/volcano/pull/1821

**Comment by Thor-wl** [comment]
Let me fix it.
/assign @Thor-wl

**Comment by veast** [comment]
> You can refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/multi-scheduler.md and have a try, it can help you automatically divide resources.
> 
> However, each scheduler still has global cache, which l think there will be problems when using some volcano features such like queues.

Thanks for reply! But in my case, it may be a little different from the document. 
Actually, I want to use the Volcano in gray mode to avoid uncontrollable problems firstly. Therefore, I can't devide the cluster resource. 
So in this case, are there possible conflicts when volcano and default-scheduler are used at the same time?

**Comment by veast** [comment]
> > You can refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/multi-scheduler.md and have a try, it can help you automatically divide resources.
> > However, each scheduler still has global cache, which l think there will be problems when using some volcano features such like queues.
> 
> Thanks for reply! But in my case, it may be a little different from the document. Actually, I want to use the Volcano in gray mode to avoid uncontrollable problems firstly. Therefore, I can't devide the cluster resource. So in this case, are there possible conflicts when volcano and default-scheduler are used at the same time?

Perhaps you can tell me what the impact of the conflict may be, and we can assess it.

**Comment by Thor-wl** [comment]
> > > You can refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/multi-scheduler.md and have a try, it can help you automatically divide resources.
> > > However, each scheduler still has global cache, which l think there will be problems when using some volcano features such like queues.
> > 
> > 
> > Thanks for reply! But in my case, it may be a little different from the document. Actually, I want to use the Volcano in gray mode to avoid uncontrollable problems firstly. Therefore, I can't devide the cluster resource. So in this case, are there possible conflicts when volcano and default-scheduler are used at the same time?
> 
> Perhaps you can tell me what the impact of the conflict may be, and we can assess it.

In some scenarios, one node with just a little resource may be selected both by Volcano and default scheduler at the same time. For example, Volcano and default scheduler are scheduling a pod requesting 2G memory at the same time. A node with 2G idle memory is selected both by the two schedulers. One of the pod must be rejected by kubelet.

**Comment by veast** [comment]
> > > > You can refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/multi-scheduler.md and have a try, it can help you automatically divide resources.
> > > > However, each scheduler still has global cache, which l think there will be problems when using some volcano features such like queues.
> > > 
> > > 
> > > Thanks for reply! But in my case, it may be a little different from the document. Actually, I want to use the Volcano in gray mode to avoid uncontrollable problems firstly. Therefore, I can't devide the cluster resource. So in this case, are there possible conflicts when volcano and default-scheduler are used at the same time?
> > 
> > 
> > Perhaps you can tell me what the impact of the conflict may be, and we can assess it.
> 
> In some scenarios, one node with just a little resource may be selected both by Volcano and default scheduler at the same time. For example, Volcano and default scheduler are scheduling a pod requesting 2G memory at the same time. A node with 2G idle memory is selected both by the two schedulers. One of the pod must be rejected by kubelet.

Got it! Thanks a lot :)

**Comment by Thor-wl** [comment]
@veast BTW, I don't suggest to make use of multiple schedulers in one cluster. It may brings more problems after resolving one problem.

**Comment by veast** [comment]
> @veast BTW, I don't suggest to make use of multiple schedulers in one cluster. It may brings more problems after resolving one problem.

OK, it will only last for a few days. Thanks for the heads up.
