### ISSUE TITLE
support maping queue to node group

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#1830]
#### What would you like to be added:
Different queues maps to different nodes for specified funcitons.
#### Why is this needed:
According to feedback from end users, they often want to divide the whole cluster into many parts. Each part maps to a specified function(such as online service or off-line training) and requires part of nodes. Namely, they create different queues and want them to map to part of nodes. However, Volcano queue cannot support that.

subTasks

- [x] API https://github.com/volcano-sh/apis/pull/72
- [x]  Design  https://github.com/volcano-sh/volcano/pull/2227
- [ ] Implement (#2352)

**Comment by Thor-wl** [comment]
I'll try to implement that.

**Comment by k82cn** [comment]
and it's better to have a CRD as resource pool, so we know how many nodes will be used in one queue :)

**Comment by Thor-wl** [comment]
> and it's better to have a CRD named `ResourceGroup`, so we know how many nodes will be used in a specific queue :)

Does it aims to separate node group with specfied queue?

**Comment by k82cn** [comment]
> > and it's better to have a CRD named `ResourceGroup`, so we know how many nodes will be used in a specific queue :)
> 
> Does it aims to separate node group with specfied queue?

Yes, and it's better to have a cli to check the  status of those groups.
