### ISSUE TITLE
Request to be a `Member` of Volcano community

### ISSUE THREAD

**Issue by eggiter** [volcano-sh/volcano#1838]
+ I'm requesting to be a `Member` of Volcano community.
+ My previous contributions are listed as followings:
    - #1668 
    - #1672 
    - #1685 
    - #1714 
    - #1716 
    - #1724 
    - #1726 
    - #1818 
    - #1819 
 + And my future interests include:
    - Scheduling Plugins,
    - Scheduling Actions such as `Preempt` and `Reclaim`, ...,
    - Any other fields related to Scheduling.
 + Pls consider my request, Thanks.

**Comment by Thor-wl** [comment]
Thanks for your contribution! Welcome to Volcano community!
/approve

**Comment by hwdef** [comment]
Welcome!

**Comment by kevin-wangzefeng** [comment]
Please visit https://github.com/volcano-sh to accept the invitation.

**Comment by eggiter** [comment]
> Please visit https://github.com/volcano-sh to accept the invitation.

Accepted, Thank you all!

**Comment by jasonliu747** [comment]
Welcome to the team. Please submit 10 PR/month to mantain your menbership. 😜

**Comment by Thor-wl** [comment]
> Welcome to the team. Please submit 10 PR/month to mantain your menbership. 😜

Where is your classical picture which is specified used for welcoming new members?

**Comment by jasonliu747** [comment]
@eggiter Please keep in mind, thanks for your cooperation.
![image](https://user-images.githubusercontent.com/24452340/142181314-88f87581-a59b-4f4c-af48-33bf62d307e9.png)

**Comment by Thor-wl** [comment]
> @eggiter Please keep in mind, thanks for your cooperation. ![image](https://user-images.githubusercontent.com/24452340/142181314-88f87581-a59b-4f4c-af48-33bf62d307e9.png)

Haha...Suggest to mark this picture as the official picture which is only used for welcoming new Volcano members.

**Comment by eggiter** [comment]
> Welcome to the team. Please submit 10 PR/month to mantain your menbership. 😜

I'll try my best to achieve that, but i won't promise :P

**Comment by shinytang6** [comment]
/approve
/lgtm

Welcome!
