### ISSUE TITLE
Request to be a Member of Volcano community

### ISSUE THREAD

**Issue by xiaoanyunfei** [volcano-sh/volcano#1839]
Recently， I began to study volcano and add some PR as follows:

- https://github.com/volcano-sh/volcano/pull/1823

- https://github.com/volcano-sh/volcano/pull/1824

- https://github.com/volcano-sh/apis/pull/58

- https://github.com/volcano-sh/volcano/pull/1828

- https://github.com/volcano-sh/volcano/pull/1829

 - https://github.com/volcano-sh/volcano/pull/1831

The Machine learning platform of `xiaohongshu` is builded based on `volcano`, and `volcano` will be maintained by me.

I hope to be bridge between volcano community and my company.

Thank you !

**Comment by Thor-wl** [comment]
Great! Thanks for your contribution recently.
/approve

**Comment by william-wang** [comment]
Thanks for your contribution.
/approve

**Comment by k82cn** [comment]
Thanks for the contributions, and welcome :)

/lgtm

**Comment by hwdef** [comment]
/approve
Thanks!

**Comment by shinytang6** [comment]
![image](https://user-images.githubusercontent.com/22241503/142346097-5ca6b92b-e846-4b92-93a8-4d00bc4108c3.png)

/lgtm
/approve
Welcome 🤪
