### ISSUE TITLE
Workflow does not support a specified queue

### ISSUE THREAD

**Issue by hansongChina** [volcano-sh/volcano#1840]
When creating a type of workflow CRD, annotations to add "scheduling. Volcano. Sh/queue - name: XXX"
Doesn't work

**Comment by hansongChina** [comment]
step1:create queue name test
`apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: tesst
spec:
  reclaimable: true
  weight: 1
  capability:
    cpu: "4"
    memory: "4096Mi"`
step2:create workflow 
`apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world
  labels:
    workflows.argoproj.io/workflow:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    scheduling.volcano.sh/queue-name: test
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  schedulerName: volcano
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 200Mi`
Workflow with the name "hello-world" was expected to be scheduled to the specified queue test, but it was scheduled to the default queue anyway

**Comment by Thor-wl** [comment]
/feature
support specified queue for jobs in Argo

**Comment by Thor-wl** [comment]
> Any plans to support ArgoWorkflow?

@Sharathmk99 Hi, Sharath. It is an important work item in the roadmap but not assigned to anyone. However, @hwdef @zhoumingcheng are working to develop a sub-project named `jobflow`, which acts as an efficient workflow engine and embedded to Volcano.

**Comment by Sharathmk99** [comment]
Hi @Thor-wl, Thank you for the response. I’ll look into ‘jobflow’, but we use Kubeflow to manage Machine Learning workloads and they use Argo as workflow management. 

I would be happy to help you in this feature, as this feature is very important to us. Currently with some custom changes to volcano we are able to use with Kubeflow. 

let me know if you can help with design and I can help to implement it. Thanks

**Comment by Thor-wl** [comment]
> Hi @Thor-wl, Thank you for the response. I’ll look into ‘jobflow’, but we use Kubeflow to manage Machine Learning workloads and they use Argo as workflow management.
> 
> I would be happy to help you in this feature, as this feature is very important to us. Currently with some custom changes to volcano we are able to use with Kubeflow.
> 
> let me know if you can help with design and I can help to implement it. Thanks

@Sharathmk99 Hi, Sharath. I really appreciate you can work on this feature. I will try synchronize this idea in the weekly meeting. Besides, I'll provide my effort during your work. Please feel free to let me know what exectly I can help.

**Comment by william-wang** [comment]
@Sharathmk99 It's great that you can provide effort on it. The jobflow design doc pr is #2339 on reviewing. Please give comments   for free. On the other hand, for the argo kubeflow, I think the following pr has fixed your issue. You can have a try.
https://github.com/volcano-sh/volcano/pull/1961
