### ISSUE TITLE
Scheduling failed when setting "volcano.sh/gpu-memory" for multiple containers in 1 pod

### ISSUE THREAD

**Issue by hl10105210** [volcano-sh/volcano#1858]
**What happened**:
Scheduling failed when setting "volcano.sh/gpu-memory" for multiple containers in 1 pod

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:1.4
- Kubernetes version (use `kubectl version`):v1.20.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):CentOS
- Kernel (e.g. `uname -a`):3.10.0-1160.el7.x86_64
- Install tools:
- Others:

**Comment by hl10105210** [comment]
The error message is "Allocate failed due to rpc error: code = Unknown desc = failed to find candidate pod, which is unexpected"

**Comment by william-wang** [comment]
@hl10105210 Thanks for your report. Please provide the job yaml and the reproduce steps.

**Comment by hl10105210** [comment]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "test1"
  labels:
    app: "test1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "test1"
  template:
    metadata:
      labels:
        app: "test1"
    spec:
      schedulerName: volcano
      nodeSelector:
        chiptype: nvidia
      containers:
        - name: "demo1"
          image: "image.pe.com/pe/demo1:1.0.0"
          resources:
            limits:
              "volcano.sh/gpu-memory": 1024
        - name: "demo2"
          image: "image.pe.com/pe/demo2:1.0.0"
          resources:
            limits:
              "volcano.sh/gpu-memory": 1024

**Comment by hl10105210** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: "test1"
  labels:
    app: "test1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "test1"
  template:
    metadata:
      labels:
        app: "test1"
    spec:
      schedulerName: volcano
      nodeSelector:
        chiptype: nvidia
      containers:
        - name: "demo1"
          image: "image.pe.com/pe/demo1:1.0.0"
          resources:
            limits:
              "volcano.sh/gpu-memory": 1024
        - name: "demo2"
          image: "image.pe.com/pe/demo2:1.0.0"
          resources:
            limits:
              "volcano.sh/gpu-memory": 1024`

**Comment by hl10105210** [comment]
[test1.txt](https://github.com/volcano-sh/volcano/files/7607004/test1.txt)

**Comment by Thor-wl** [comment]
Can you provide the complete log?
