### ISSUE TITLE
queue allocated exceeds capability

### ISSUE THREAD

**Issue by aidaizyy** [volcano-sh/volcano#1860]
**What happened**:
`capability indicates the upper limit of resources the queue can use. It is a hard constraint.`
But, It's not work.
There are many issues here to report this problem. The conclusion is that pg does not set min resource.
But It is not necessary to set min resource for podgroup without gang. This is not the reason why allocated exceeds capability.

**What you expected to happen**:
The allocated value of the queue should be less than or equal to the capability value.

**How to reproduce it (as minimally and precisely as possible)**:
Before allocate task, we will check if the queue is overused (OverusedFns) and if the name of the resource request is not enough in the queue (UnderusedResourcesFns).

Here only judges whether the queue can still be allocated, but does not consider the resource situation of the task.
For example.
A queue has total 10 core, 10Gi, used 9 core, 9Gi.
A new pod has 10 core, 10Gi.
It will pass the above check and will be allocated because the queue is not full yet.
Then this queue used 19 core, 19Gi, far exceeds capability.

**Environment**:
- Volcano Version: Latest

**Comment by aidaizyy** [comment]
PR: https://github.com/volcano-sh/volcano/pull/1861

**Comment by Thor-wl** [comment]
There still leaves a bug that `capability` must works with `proportion` plugin. We need to separate it with any specified plugin.

**Comment by aidaizyy** [comment]
@Thor-wl Now the only plugin that identify the deserved and limit resource of each queue is `proportion` plugin. Not using this plugin means giving up the above capabilities, which is reasonable.

If dividing deserved and limit into two plugins, I don't think it is reasonable.
We can limit the use of queue resources in other places, but how to divide resources into different queues without `proportion` plugin. These are the basic abilities of scheduling, which are indispensable

The way I thought of it is to classify the plugins. At least one plugin of this type is set, and their function is to divide resources into different queues and limit resource usage.
For example, in the future, the community will have a new plugin `X` that uses min resource to divide resources instead of weight, which can also limit resources. 
At least one of `X` or `proportion` needs to be set, because this is the basic ability of scheduling.

**Comment by elinx** [comment]
Looks like I can't reproduce this issue, is there any more details you can provide? I follow these steps:

1. create a queue with capacity 4CPUs
2. create a job using the queue with 3 replicas each has a 1 CPU request, and it succeeds
3. create a job using the same queue with 2 replicas each has a 1 CPU request, and it failed

**Comment by aidaizyy** [comment]
@elinx 
It is scheduled with pod by pod. 

There are a total of 5 pods here. When 4 pods are scheduled, the resources are full and the 5th pod will not be scheduled.

If the second job has only one pod and wants 2 cores, it is possible to reproduce the scene.

In addition, there is also an important premise that you cannot set min resource of podgroup. Otherwise, the second job will not be enqueued.
