### ISSUE TITLE
Pytorchjob pods hang on pending status with volcano scheduler

### ISSUE THREAD

**Issue by jazka** [volcano-sh/volcano#1863]
**What happened**:
The Pytorchjob pods hang on pending status with volcano scheduler. And there is no logs about this job in volcano-scheduler pod. 
The podgroup is created.

**What you expected to happen**:
The Pytorchjob pods should be scheduled normally

**How to reproduce it (as minimally and precisely as possible)**:
It's an accidental phenomenon

**Anything else we need to know?**:
The pytorchjob infos, refer to https://github.com/kubeflow/training-operator/issues/1492#issuecomment-981527879

**Environment**:
- Volcano Version: 1.4
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
Could you describe the podgroup info? @jazka

**Comment by jazka** [comment]
Sorry for late reply. 

The podgroup info as below:

https://l4x826wg3c.feishu.cn/file/boxcnEpNDeZfgfeKU9LX9yY6LVe

https://l4x826wg3c.feishu.cn/file/boxcnnvDjWG3NDwX0tMabcPVXvd

**Comment by shinytang6** [comment]
> Sorry for late reply.
> 
> The podgroup info as below:
> 
> https://l4x826wg3c.feishu.cn/file/boxcnEpNDeZfgfeKU9LX9yY6LVe
> 
> https://l4x826wg3c.feishu.cn/file/boxcnnvDjWG3NDwX0tMabcPVXvd

it's strange that the status of PodGroup is empty.. The pods will start to be scheduled once podgroup become inqueue or ready. Any related scheduler log? @jazka

**Comment by jazka** [comment]
> > Sorry for late reply.
> > The podgroup info as below:
> > https://l4x826wg3c.feishu.cn/file/boxcnEpNDeZfgfeKU9LX9yY6LVe
> > https://l4x826wg3c.feishu.cn/file/boxcnnvDjWG3NDwX0tMabcPVXvd
> 
> it's strange that the status of PodGroup is empty.. The pods will start to be scheduled once podgroup become inqueue or ready. Any related scheduler log? @jazka

Yes, it is weired that there is no any logs abount this job on scheduler pod. But the pending pods will became running if I restart the scheduler pod.

**Comment by Thor-wl** [comment]
I've overviewed all the context and it's hard to get useful information. Can you describe the podgroup for more details or provide the steps to reproduce the accident steadily?

**Comment by jazka** [comment]
What is the "more details" of podgroup? Attached before includes get/describe of podgroup。

There is no fixed step to reporduce. If the volcano is redeloyed, this scenario will miss and reappear in the future.  

Is there any way to output more logs on scheduler pod?  Or do you have container for debug, I can replace the image to get more info.

**Comment by Thor-wl** [comment]
> 

Sorry for missing some info in the picture you provided. If the status of podgroup is empty, have you got someting useful in the controller manager? That's not so reqular.

**Comment by jazka** [comment]
There are some errors in volcano-* pods. Could you help to check if it is normal?  Please check the error image from the links below.


The logs of volcano-controllers:  https://l4x826wg3c.feishu.cn/file/boxcnrEYCVWm8TU1wVLnuQpcIWb
The logs of volcano-scheduler: https://l4x826wg3c.feishu.cn/file/boxcnDGG3mxj6SV1Uif2ke7xrOe

**Comment by jazka** [comment]
Attch more logs of volcano-admission and training-operator controller:

https://l4x826wg3c.feishu.cn/file/boxcnKZvbol5VEK5r9U8dkrniXc
https://l4x826wg3c.feishu.cn/file/boxcnhEtrcTX49KJLwMgmIMaVfs

**Comment by jazka** [comment]
@Thor-wl Could you help to show me some possible ways to debug to make sure the root reason?

**Comment by jazka** [comment]
@Thor-wl I tested many times and found the volcano-scheduler do not work from logs. When I start one pod with "schedulerName: volcano", there is no more logs in volcano-scheduler pod except "PriorityClass is deprecated in v1.14+...". After restarted volcano-scheduler pod, it will output like "Added Queeue <default> for ...". 

Do you have any way to check what happened to volcano-scheduler? Does it missing related event from kubernetes?

**Comment by william-wang** [comment]
@jazka Which version of training operator do you install. and would you like to provide the job yaml?
We will try to reproduce the issue in my environment.

**Comment by jazka** [comment]
> @jazka Which version of training operator do you install. and would you like to provide the job yaml? We will try to reproduce the issue in my environment.

The training-operator version is 760ac1171dd30039a7363ffa03c77454bd714da5, the image is from public.ecr.aws/j1r0q0g6/training/training-operator:760ac1171dd30039a7363ffa03c77454bd714da5.

There is nothing special setting in job yaml，please refer to the image screenshot:
https://l4x826wg3c.feishu.cn/file/boxcnCfIzGCSJbivvNOPawwh13b
https://l4x826wg3c.feishu.cn/file/boxcnS2oGrfAn1ZfNK9RLU4OXcd

**Comment by cheimu** [comment]
Same problem here.
<img width="3007" alt="image" src="https://user-images.githubusercontent.com/13050415/155963763-98ca4125-7f5d-4492-b00e-9110a9cdaba1.png">
job yaml is https://www.kubeflow.org/docs/components/training/pytorch/#monitoring-a-pytorchjob which is exactly the same as the one from kubeflow website tutorials. <br>
training operator version is 6c115f6e00e3f2c979c6aa4bf2d93906a646b99d 

Anyway the training process can still go on, and this error only occurs at the initialization.

**Comment by Thor-wl** [comment]
@cheimu Have you tested for the latest version? @william-wang has merged the bug fix recently.
