### ISSUE TITLE
Image Locality Plugin

### ISSUE THREAD

**Issue by justadogistaken** [volcano-sh/volcano#1864]
#### What would you like to be added:
I happened to found the TODO left in volcano nodeorder. which is about ImageLocality.
```		
//TODO: Add ImageLocalityPriority Function once priorityMetadata is published
//Issue: #74132 in kubernetes ( https://github.com/kubernetes/kubernetes/issues/74132 )
```

Wonder if the "ImageLocality" is not important in batch-scheduling, so volcano never fills this TODO. That is easy to complete nowadays.

**Comment by shinytang6** [comment]
> TODO: Add ImageLocalityPriority Functio

This is needed, but no one filled it. Would you like to have a try? @justadogistaken

**Comment by Thor-wl** [comment]
It is very useful for accelerating the speed of starting pod without pulling big image. So if scheduler can be aware of the location of images on all nodes, it will be helpful.

**Comment by justadogistaken** [comment]
> without

I'd like to work on this.
