### ISSUE TITLE
Using Volcano with Kubernetes built-in `batch/v1` Job objects from unmodified applications?

### ISSUE THREAD

**Issue by adamnovak** [volcano-sh/volcano#1869]
We have a Kubernetes cluster where we'd like to enforce that `batch/v1` `Job` objects submitted later cannot starve `Job` objects submitted earlier, by being smaller and taking up space as soon as it opens. We don't necessarily have control of the process by which the `Job` objects are created; some of them are created by, for example, Gitlab. I don't think I can modify Gitlab to use anything other than the `batch/v1` `Job` as the controller for the pods it runs, although I might be able to set fields on the jobs.

It seems like one solution to this problem is to set up `kube-batch` as our default scheduler. Then all the `batch/v1` `Job` objects will go into a default `Queue`, and that `Queue` will enforce this constraint.

Now, [`kube-batch` is apparently deprecated in favor of Volcano](https://github.com/kubernetes-sigs/kube-batch/issues/948), so I'd like to do the same setup with Volcano. Hovever, all [the Volcano documentation](https://volcano.sh/en/docs/vcjob/) seems to show you issuing jobs as `batch.volcano.sh/v1alpha1` `Job` objects. This suggests that even with Volcano as the default scheduler and with a default queue configured, `batch/v1` `Job` objects will not be scheduled by Volcano and will not participate in that queue. Is that the case?

There's https://github.com/volcano-sh/volcano/issues/1469 which explains that, when you want to use your *own* custom CRD notion of a Job, you can attach the pods you create to Volcano by creating a PodGroup. However, I don't think that issue quite covers using the default built-in `batch/v1` `Job` instead of a custom-defined resource.

Note also that these jobs don't need to be co-scheduled or gang-scheduled; each `Job`-managed pod ought to be scheduled alone. All the groups would be trivial groups of size 1.

So, can Volcano be used to schedule vanilla Kubernetes `batch/v1` `Job`s with this sort of submission-order constraint in cases of contention? If so, what special steps if any must be taken?

**Comment by k82cn** [comment]
Currently, Volcano support all kind of object in k8s; Volcano will help to generate a `PodGroup` for those object; so I think make Volcano as default schedule should be ok :)

Regarding the starvation, we're going to use SLA plugin to improve it, refer to the design doc for more detail: https://github.com/volcano-sh/volcano/blob/master/docs/design/sla-plugin.md .

**Comment by adamnovak** [comment]
Thanks @k82cn!

So it sounds like `batch/v1` `Job` objects will work fine with Volcano, but I will have to configure the SLA plugin with an `sla-waiting-time` to prevent small jobs from starving big jobs forever.

**Comment by k82cn** [comment]
> So it sounds like batch/v1 Job objects will work fine with Volcano, but I will have to configure the SLA plugin with an sla-waiting-time to prevent small jobs from starving big jobs forever.

hm... I'm ok to enable SLA as default :)

/cc @Thor-wl

**Comment by Thor-wl** [comment]
> 

I agree with that. SLA as default is reasonable.

**Comment by adamnovak** [comment]
I think this is resolved. I'm still having trouble getting Volcano job objects to schedule without starvation, but if elect/reserve starts working it ought to work on Kubernetes Job objects just fine.
