### ISSUE TITLE
How to build a pipeline with the volcanoJob

### ISSUE THREAD

**Issue by summerisc** [volcano-sh/volcano#1872]
What would you like to be added:
Are there any outstanding frameworks/tools that can work with volcanoJob to build an ML pipeline? By ML pipeline, it might be something like Kubeflow pipeline, but apparently, ML pipeline doesn't support using volcanoJob as a component in a pipeline

Why is this needed:
Trying to build a pipeline with preprocessing logic, volcanoJob training, and postprocessing(if any), looking for a fit framework for that.

**Comment by k82cn** [comment]
Are you going to use kubeflow/pipeline with vcjob or prefer to use a pipeline from Volcano community?

For the pipeline of Volcano community, there're some contribute would like to donate related project to community, we're going through the checklist, xref https://docs.google.com/document/d/1YLbF8zjZBiR9PbXQPB22iuc_L0Oui5A1lddVfRnZrqs/edit# .

For the kubeflow/pipeline, there's no integration right now; and we'd like to enhance that if that's your scenario :)

**Comment by summerisc** [comment]
thanks for the prompt response! @k82cn Either way kubeflow/pipeline with vcjob or pipeline from Volcano community is a good solution. 
If you have more information about what might be the future plan for the community in terms of a pipeline similar feature that would be really helpful.

**Comment by k82cn** [comment]
> If you have more information about what might be the future plan for the community in terms of a pipeline similar feature that would be really helpful.

We're going to have pipeline feature in Volcano communtiy, so the scheduler can work together with the pipeline for the performance, e.g. data aware scheduling.
