### ISSUE TITLE
Support elastic training with pytorch

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#1876]
#### What would you like to be added:
Support elastic training with pytorch

#### Why is this needed:
Use elastic training to improve the utilization of GPU.

Tasks

- [x] allow elastic job to be enqueued in case of resource shortage
       Implementation:  #2173 
- [x] support elastic annotation in preempt/reclaim plugin
       implementaion:  #2105

**Comment by william-wang** [comment]
@qiankunli, You can add the detail infomation about this subject here. Thanks.

**Comment by k82cn** [comment]
xref: https://github.com/volcano-sh/volcano/pull/1887
