### ISSUE TITLE
Why job controller split jobs into different queues

### ISSUE THREAD

**Issue by xiaoanyunfei** [volcano-sh/volcano#1878]
#### What would you like to be added:
[job_controller.go](https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/job/job_controller.go#L143)

`jobcontroller` construct `queueList`, and split jobs into different queues.
I wonder why it is designed like this. It will case hotspot problem.
`workqueue.NewRateLimitingQueue` is thread safe， and can be safely shared among `workers`

#### Why is this needed:

I will work on storing jobs in one queue

If there is special reason for this design, tell me please.

**Comment by william-wang** [comment]
@xiaoanyunfei Launch multiple go routines to process multiple queues at the same time. The main reason is to improve the throughput of job controller.

**Comment by xiaoanyunfei** [comment]
My key point is why spliting jobs into different `NewRateLimitingQueue`, and jobs can just use one same `NewRateLimitingQueue`

**Comment by k82cn** [comment]
> My key point is why spliting jobs into different `NewRateLimitingQueue`, and jobs can just use one same `NewRateLimitingQueue`

It's try to avoid lock/unlock when get job info from `NewRateLimitingQueue`. I can-t remember the data of improvement, but the overall target is to support 10k jobs with 100k Pods :)

**Comment by k82cn** [comment]
Anyway, if this's not the major bottleneck, I'm ok to make code simple :)
