### ISSUE TITLE
podpending：When deployment rollingup, old podgroup will occupy resource.

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1907]
**What happened**:
I use volacno to schedule deployment. When I rollingup, found old pg is retain，and it still occupy resource in volcano-scheduler queue.
This leads to a situation where resources exist but cannot be scheduled.
![截图](https://user-images.githubusercontent.com/7522079/146524804-ceb875db-aaa5-4624-9e38-59710c1bdf2d.PNG)

**What you expected to happen**:
When deployment rollingup ,  volcano-scheduler queue has only one pg.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:v1.4.0
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
https://github.com/volcano-sh/volcano/pull/1891 may resolve this issue )

**Comment by zishen** [comment]
> #1891 may resolve this issue )

so good
