### ISSUE TITLE
volcano algorithm

### ISSUE THREAD

**Issue by Hugh-yw** [volcano-sh/volcano#1914]
- Volcano Version: 1.1.2
- Kubernetes version (use `kubectl version`): v1.16.15
- OS (e.g. from /etc/os-release): centos 7.7
- Kernel (e.g. `uname -a`): 3.10.0-1062.18.1.el7.x86_64

Can this binpack algorithm be cancelled? It is found that with this algorithm, our cluster size is 200, but AI related training tasks are regularly scheduled to several nodes every time. Isn't the dispersion obvious? It is expected that other nodes in the cluster will also be dispatched. Is there a scheme that can be actually implemented?

**Comment by william-wang** [comment]
@Hugh-yw 
The algorithm(plugin) is configurable in Volcano. Please follow below introduction to cancel the binpacking for your case.
https://volcano.sh/en/docs/schduler_introduction/

**Comment by Hugh-yw** [comment]
OK, thanks
