### ISSUE TITLE
Can we organize some people to develop a web UI for Volcano?

### ISSUE THREAD

**Issue by wanshicheng** [volcano-sh/volcano#1922]
#### What would you like to be added:
A web UI for watching scheduling process and resource statistics.
#### Why is this needed:
Only O&M can use the command line to view the status. No one else can get it.

**Comment by Thor-wl** [comment]
Looking forward to this work.

**Comment by k82cn** [comment]
That's ok for me to start a new repo for that; but not sure how many contributors will help on that :)

**Comment by hwdef** [comment]
Can it be shown through grafana, Or we can implement a web UI from scratch

**Comment by k82cn** [comment]
> Can it be shown through grafana, Or we can implement a web UI from scratch

Grafana is helpful on monitor or metrics; that'll be great to have a web UI for job/queue management :)

**Comment by hwdef** [comment]
We can develop a component, similar to the dashboard of kubernetes

**Comment by william-wang** [comment]
> We can develop a component, similar to the dashboard of kubernetes

That will be great. I think we can work together and start from a design doc firstly.

**Comment by hwdef** [comment]
I don’t know if there are professional UI/UX and front-end developers in the community. Generally speaking, we are all back-end development. 

I feel it’s not easy to do well. For example, the dashboard is not very well done, and not many people use it..

**Comment by wanshicheng** [comment]
First we need make a apiserver so that users can easily integrate volcano into their own systems. This also makes it easier for users to develop their own UI and then contribute to the community in return.

**Comment by k82cn** [comment]
> First we need make a apiserver so that users can easily integrate volcano into their own systems. This also makes it easier for users to develop their own UI and then contribute to the community in return.

+1, we can start to do that in a new repo :)

**Comment by Saba1119** [comment]
Is web UI developed/ ready ???
