### ISSUE TITLE
[help wanted] how to handle Pipelined status in volcano 

### ISSUE THREAD

**Issue by xing0821** [volcano-sh/volcano#1925]
I check the code and cannot found the logic process pipelined status, how can the pod(task) status updated from pipelined to allocated or binding? Maybe the pod updated by event handler and transfer from pipelined to pending?

**Comment by k82cn** [comment]
pipelined is used to wait releasing resources; the status will be updated in next scheduling cycle if the resource is free :)

**Comment by xing0821** [comment]
> pipelined is used to wait releasing resources; the status will be updated in next scheduling cycle if the resource is free :)

i can get that point but cannot found the code that handle the pipelined status... which action or event will process pipelined? 

thx for your reply!

**Comment by chanhz** [comment]
> > pipelined is used to wait releasing resources; the status will be updated in next scheduling cycle if the resource is free :)
> 
> i can get that point but cannot found the code that handle the pipelined status... which action or event will process pipelined?
> 
> thx for your reply!

[Here](https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/framework/session.go#L244) is the code where task update to status `Pipelined`: 
```go
    ...
    if err := job.UpdateTaskStatus(task, api.Pipelined); err != nil {...}
    ...

```

**Comment by foshanck** [comment]
> > pipelined is used to wait releasing resources; the status will be updated in next scheduling cycle if the resource is free :)
> 
> i can get that point but cannot found the code that handle the pipelined status... which action or event will process pipelined?
> 
> thx for your reply!

Totally agree with you. I also can't find the codes which are related to pipelined tasks got transmit to other status(.e.g allocated or binding)

Can someone point out the code location?

Sincerely thanks

**Comment by wang-mask** [comment]
+1

**Comment by flyingfang** [comment]
+1

**Comment by Akiqqqqqqq** [comment]
Pipelined的资源会预留到下一个session使用，相当于这轮把它先空出来（占着）

**Comment by bysph** [comment]
Same confused，I could not find the code that change Pipelined to Allocated.

**Comment by miaowukong** [comment]
同意[Akiqqqqqqq]的内容，ssn 中为copy的数据，task 只有在本次调度周期才是pipeline，本次只是预留这部分资源。下一次调度周期 pod 还是pending，会重新allocate资源，当然pod也不一定会用之前预留的资源。
