### ISSUE TITLE
Use Placement as resource allocation center

### ISSUE THREAD

**Issue by superleo** [volcano-sh/volcano#1927]
#### What would you like to be added:
volcano to use placement as resource allocation center.  Use two-level scheduling architect to make it possible for volcano to integrated with traditional IAAS system. And work togather with existing openstack scheduler. To support the orchastration of dyversity workloads.

#### Why is this needed:
Many datacenter has existing openstack deployed, and want to unify the resource management/allocation during import volcano. We need to integrated with it to improve resource manager experience as well as resource utilization.

**Comment by william-wang** [comment]
About Volcano working with resource manager except for Kubernetes. Please refer to the following proposal and check whether it fits your scenario as well.
#1886: https://github.com/volcano-sh/volcano/pull/1886
