### ISSUE TITLE
Provide extender framework for volcano

### ISSUE THREAD

**Issue by xing0821** [volcano-sh/volcano#1935]
#### What would you like to be added:

  can we add an extender framework such as kube-scheduler's extender. maybe we can send a RPC request or http request on each plugin functions, such as predicateFns.

#### Why is this needed:
  
  we can add some logic of scheduling out of source code. such as an Operator specific requirements of scheduling

**Comment by k82cn** [comment]
+1

**Comment by xing0821** [comment]
l am interested in that feature, maybe i can give a design doc first about extender

**Comment by shinytang6** [comment]
> can we add an extender framework such as kube-scheduler's extender. maybe we can send a RPC request or http request on each plugin functions, such as predicateFns.

That's great, looking forward to that 😃

**Comment by k82cn** [comment]
Yes, we can have an http/grpc plugin to deligate the request; so I think that's simple enough for beginner :)

**Comment by hejufang** [comment]
looking forward to that

**Comment by xing0821** [comment]
PR is https://github.com/volcano-sh/volcano/pull/1951
