### ISSUE TITLE
Request to be a Member of Volcano community 

### ISSUE THREAD

**Issue by qiankunli** [volcano-sh/volcano#1937]
Recently， I began to study volcano and add some PR as follows:

#1905 support reserved resources by guarantee field in QueueSpec
#1896 support label volcano.sh/task-priority
#1821 support reserved node
#1884 support elastic scheduler

The Machine learning platform of Ximalaya is builded based on volcano, and volcano will be maintained by me.

I hope to be bridge between volcano community and my company.

Thank you !

**Comment by Thor-wl** [comment]
Thanks for your contribution in v1.5! Welcome to Volcano community!
/lgtm

**Comment by jasonliu747** [comment]
welcome welcome very welcome! 🎉

**Comment by hwdef** [comment]
Welcome!
The work you did before was great!

**Comment by jasonliu747** [comment]
Sorry, wrong meme above. Welcome!
![image](https://user-images.githubusercontent.com/24452340/148022741-f0bfb51e-9f1a-44ec-9187-123e429e12a1.png)

**Comment by william-wang** [comment]
Welcome to volcano family. Looking forward to more contribution :)

**Comment by k82cn** [comment]
Welcome !

**Comment by kevin-wangzefeng** [comment]
Welcome on board!
