### ISSUE TITLE
[Question] Assignment namespace to jobs/pods

### ISSUE THREAD

**Issue by maprietom** [volcano-sh/volcano#194]
When I lauch a job on volcano, it create all neccesary pods for this, but I don't know how to assign the namespace for pods that create. 

Is it possible change assign namespace "on the fly"?

**Comment by k82cn** [comment]
The pods were created by job controller which should now modify/change on the fly. It's better to change the job, the job controller should help to recreate the pods; hm... I'm not quite sure whether this is supported; if not, we should enhance that :)

**Comment by hzxuzhonghu** [comment]
@maprietom The pods created by volcano job controller is in the same namespace as the volcano job.

We do not support changing the ns of the jobs. This behavior is like native k8s job.
