### ISSUE TITLE
Add individual development yamls for each version of volcano

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#1940]
#### What would you like to be added:

Add individual development yamls for each version of volcano. For example, `volcano-development-v1.4.0.yaml` for version 1.4.0 which matched branch `release-1.4.0`, and `volcano-development-latest.yaml` for latest version which matched branch `master`.

#### Why is this needed:

In volcano [Quick Start Guide](https://github.com/volcano-sh/volcano/blob/master/README.md#quick-start-guide), a `volcano-development.yaml` for latest volcano was composed for quick deployment, but this yaml may not be in common use for other published versions.
For example, when I wanted to deploy `v1.4.0` by modifying image tag in latest yaml from `:latest` to `:v1.4.0` and apply, an error was throwed like "argument `enable-healthz` is unrecognized", which would cause troubles when users supposed to apply older versions of volcano.

**Comment by hwdef** [comment]
I think this is worth considering. Are you willing to contribute to this?

**Comment by k82cn** [comment]
It's better to use yaml file in related branches; let's add a FAQ for that suggestion :)

**Comment by william-wang** [comment]
We will add the deployment file for each branch. branch 1.5 will be the first : )

**Comment by k82cn** [comment]
@hwdef , would you also help to fix the CI issue ?

**Comment by hwdef** [comment]
This issue has been resolved, please close.
@jiangkaihua @Thor-wl
