### ISSUE TITLE
When device-plugin redeploy， resources that have been used are not counted.

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#1946]
**What happened**:
When resources are used by the vcJob allocation, redeploy deviceplugin. Found  the using resource has not been calculated.
![1](https://user-images.githubusercontent.com/7522079/148354595-ada72573-dd7f-42e0-b3fe-ad707f504656.PNG)

When reshipment deviceplugin volcano restart itself, an error is as follows:

**What you expected to happen**:
 When redeploy resource device-plugin,  the count of resource is right.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:v1.4.0
- Kubernetes version (use `kubectl version`):1.17.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by william-wang** [comment]
Would you like to provide the device plugin information？ Which device plugin and version are you using?

**Comment by zishen** [comment]
> Would you like to provide the device plugin information？ Which device plugin and version are you using?

Device plugin  is what we aimed at NPU custom, similar to the GPU。

**Comment by zishen** [comment]
This issue has be reply in v1.5.0-beta https://github.com/volcano-sh/volcano/pull/1685/files.
