### ISSUE TITLE
Stop relying setting RemoveSelfLink=false feature-gate - we're locking it to true with GA graduation in 1.24

### ISSUE THREAD

**Issue by wojtek-t** [volcano-sh/volcano#1948]
Upstream Kubernetes is going to get rid of ability to set SelfLink in release 1.24 (basically graduate graduate RemoveSelfLink feature gate to stable - see the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1164-remove-selflink, for a bit more details).

It seems that volcano is still vendoring Kubernetes version that is setting it to false:
https://github.com/volcano-sh/volcano/blob/master/vendor/k8s.io/apiserver/pkg/features/kube_features.go#L127

This is one more heads'up to stop relying on it (if you do in any place).

**Comment by k82cn** [comment]
@wojtek-t , thanks for your input; do any components dependent on `SelfLink`, e.g. client-go? Currently, we did not rely on it explicitly :)

**Comment by wojtek-t** [comment]
> @wojtek-t , thanks for your input; do any components dependent on SelfLink, e.g. client-go? 

There was a place that were depending on SelfLink in client-go:
https://github.com/kubernetes/kubernetes/blob/release-1.13/staging/src/k8s.io/client-go/tools/reference/ref.go#L79
But that was eliminated in 1.15 already.

So in the release you're vendoring client-go doesn't depend on it. However, apiserver and kubectl repos do in some places (not sure if you are using them though).

**Comment by k82cn** [comment]
> > @wojtek-t , thanks for your input; do any components dependent on SelfLink, e.g. client-go?
> 
> There was a place that were depending on SelfLink in client-go: https://github.com/kubernetes/kubernetes/blob/release-1.13/staging/src/k8s.io/client-go/tools/reference/ref.go#L79 But that was eliminated in 1.15 already.
> 
> So in the release you're vendoring client-go doesn't depend on it. However, apiserver and kubectl repos do in some places (not sure if you are using them though).

Got that, thanks very much. I think what we need to do is to update k8s version :)

**Comment by wojtek-t** [comment]
> Got that, thanks very much. I think what we need to do is to update k8s version :)

yeah - that's probably desired independently of the selflink stuff :)
