### ISSUE TITLE
Error creating job in a queue

### ISSUE THREAD

**Issue by maprietom** [volcano-sh/volcano#195]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
when we create a job associated with a queue that does not exist, Volcano tells us that the job is created but the pods are not created

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: release-0.1
- Kubernetes version (use `kubectl version`): 1.12.7-gke.10
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
/assign @asifdxtreme 

We should check whether Queue exist :)

**Comment by asifdxtreme** [comment]
cc @thandayuthapani
