### ISSUE TITLE
Unable to schedule independent pod when RBAC enforced

### ISSUE THREAD

**Issue by Robert-Christensen-visa** [volcano-sh/volcano#1962]
**What happened**:

I am trying to use volcano to schedule independent pods and to add those pods to a specific queue.  This is done so volcano can keep track of resources used by the cluster.

I submit this pod:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: testns
spec:
  schedulerName: volcano
  containers:
  - name: main
    image: ubuntu:latest
    command: ["sh", "-c", "sleep 600000"]
    resources:
      limits:
        cpu: "1000m"
        memory: "256Mi"
```

The pod is submitted, but remains in the "pending" state.  When I look though the logs for the controller, it is reports a podgroup can't be created for the pod.  I also don't see a podgroup created for the pod.  I see something like this in the logs:

```
E0113 20:57:02.278172       1 pg_controller.go:135] Failed to handle Pod <testns/test-pod>: podgroups.scheduling.volcano.sh "podgroup-044f57a5-0484-451c-a1c1-8d9078bc9ef7" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
E0113 20:59:37.613273       1 pg_controller_handler.go:119] Failed to create normal PodGroup for Pod <testns/test-pod>: podgroups.scheduling.volcano.sh "podgroup-0775e3d2-940a-47b8-afc5-92023a135217" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

When an independent pod requests to use the volcano scheduler, it will try to create a podgroup for that pod.  When the podgroup is created it sets `blockOwnerDeletion=true` in the `ownerReference` field.  This requries updating the owner's finalizer list.  However, the current RBACs for Volcano do not include the ability to modify pod/finalizer.  Because of this, the podgroup can't be created.

**What you expected to happen**:

I expect if an independent pod is submitted to a cluster with `schedulerName: volcano` the pod will be scheduled.  This works on clusters where RBACs are not being enforced, such as on the local kubernetes cluster installed in docker desktop.

**How to reproduce it (as minimally and precisely as possible)**:

Submit the pod described above to a cluster that enforces RBACs.  The issue will not present itself if submitted to a local kubernetes cluster installed through docker.

**Anything else we need to know?**:

I can submit a PR for this, but I am not sure where the source of truth is for specifying the RBACs for volcano.  I think mostly all that needs to be added is permissions to allow "update" and "patch" for "pods/finalizers" to resolve this bug.

**Environment**:
- Volcano Version: v1.4.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
On prem cluster, but  I am not sure the hardware configuration is important in this case
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hwdef** [comment]
I noticed that you want to create a PR for this bug, 
You can create this PR and I will review it with other reviewers.
Thanks!

**Comment by Thor-wl** [comment]
> /cc @hwdef Can you help for that?

OK. Let me fix it.

**Comment by Thor-wl** [comment]
@Robert-Christensen-visa hey, Robert. I've tried to reproduce your scenario with volcano release v1.4.0 and v1.5.0-beta. But everything seems goes well. My environment infomation is as follows:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
And my controller logs are as follows:
```
[root@ecs-thor ~]# kubectl logs volcano-controllers-5b7bc6c7bf-b5l89 -n volcano-system --follow
2022/01/19 03:27:49 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
W0119 03:27:49.631104       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0119 03:27:49.632855       1 queue_controller.go:171] Starting queue controller.
I0119 03:27:49.632898       1 garbagecollector.go:91] Starting garbage collector
W0119 03:27:49.657988       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W0119 03:27:49.670146       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
I0119 03:27:49.733156       1 job_controller.go:252] JobController is running ...... 
I0119 03:27:49.733165       1 pg_controller.go:109] PodgroupController is running ...... 
I0119 03:27:49.733174       1 job_controller.go:256] worker 0 start ...... 
I0119 03:27:49.733186       1 job_controller.go:256] worker 2 start ...... 
I0119 03:27:49.733192       1 job_controller.go:256] worker 1 start ...... 
I0119 03:28:05.840986       1 queue_controller.go:238] Begin execute SyncQueue action for queue default, current status 
I0119 03:28:05.841008       1 queue_controller_action.go:36] Begin to sync queue default.
I0119 03:28:05.846264       1 queue_controller_action.go:82] End sync queue default.
I0119 03:28:05.846284       1 queue_controller.go:220] Finished syncing queue default (5.304288ms).
I0119 03:31:20.451851       1 queue_controller.go:238] Begin execute SyncQueue action for queue default, current status Open
I0119 03:31:20.451875       1 queue_controller_action.go:36] Begin to sync queue default.
I0119 03:31:20.451885       1 queue_controller_action.go:72] End sync queue default.
I0119 03:31:20.451889       1 queue_controller.go:220] Finished syncing queue default (45.154µs).
I0119 03:31:21.202880       1 queue_controller.go:238] Begin execute SyncQueue action for queue default, current status Open
I0119 03:31:21.202902       1 queue_controller_action.go:36] Begin to sync queue default.
I0119 03:31:21.203271       1 job_controller.go:307] Try to handle request <Queue: , Job: default/podgroup-d721ad3c-23a7-4e31-89a6-ec68369e610c, Task:, Event:, ExitCode:0, Action:, JobVersion: 0>
E0119 03:31:21.203313       1 job_controller.go:312] Failed to get job by <Queue: , Job: default/podgroup-d721ad3c-23a7-4e31-89a6-ec68369e610c, Task:, Event:, ExitCode:0, Action:, JobVersion: 0> from cache: failed to find job <default/podgroup-d721ad3c-23a7-4e31-89a6-ec68369e610c>
I0119 03:31:21.209724       1 queue_controller_action.go:82] End sync queue default.
I0119 03:31:21.209736       1 queue_controller.go:220] Finished syncing queue default (6.863856ms).
```
I watched the status of pod and poggroup as the same time. The status are as follows:
```
Every 2.0s: kubectl get podgroup -A -owide                                                                                 Wed Jan 19 11:37:13 2022

NAMESPACE   NAME                                            AGE
default     podgroup-d721ad3c-23a7-4e31-89a6-ec68369e610c   5m53s
```

```
Every 2.0s: kubectl get pod -owide                                                                             Wed Jan 19 11:37:33 2022

NAME       READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
test-pod   1/1     Running   0          6m13s   10.244.0.9   volcano-control-plane   <none>           <none>
```
Have I missed anything important?

**Comment by Robert-Christensen-visa** [comment]
@Thor-wl Are RBAC policies being enforced in your test cluster?  If found the pod is able to get scheduled on kubernetes running on my local machine (the docker kubernetes does not enforce RBACs).  In small scale testing I don't have an issue getting pods to get scheduled.  However, in production clusters RBACs are enforced.  When RBACs are enforced the controller does not have permissions to add a finalizer to the pod when the podgroup is created.  If you are running your tests on a local small scale cluster and the security setting is such that RBACs are not enforced, you will not have an issue.

**Comment by robertchristensen** [comment]
@Thor-wl I looked into this a little more to see what is going on.  It seems like others might not have an issue, but I am seeing this in the cluster I am working on.  I think it might be because we have [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) enabled.  According to the documentation referenced,

>This admission controller protects the access to the metadata.ownerReferences of an object so that only users with "delete" permission to the object can change it. This admission controller also protects the access to metadata.ownerReferences[x].blockOwnerDeletion of an object, so that only users with "update" permission to the finalizers subresource of the referenced owner can change it.

When this is enabled, update on the finalizer will be required for every subresource.  In this case, it needs update on `pod/finalizers`.  This is probably why I am seeing issues with this and you might not be seeing the issue even if you have RBACs installed.

Adding `pod/finalizers` update permissions to the finalizers subresource should fix this issue for scheduling independent pods (pods without a controller) if kubernetes has OwnerReferencesPermissionEnforcement enabled.
