### ISSUE TITLE
how can worker do sthing before stopping

### ISSUE THREAD

**Issue by zhenxiu** [volcano-sh/volcano#1966]
i apply prestop command on worker container, but this didnot work

**Comment by zhenxiu** [comment]
i use mpi

**Comment by Thor-wl** [comment]
I'm sorry for not getting it clearly. Can you describe your scenario with more details?

**Comment by zhenxiu** [comment]
when i commit mpi job，i want to do something by worker before the job complete; i set prestop commands to woker container，but this not work

**Comment by zhenxiu** [comment]
` imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
          - echo 'this is pre stop test ... '
    name: worker
    ports:
    - containerPort: 22
      name: job-port
      protocol: TCP
`
