### ISSUE TITLE
new plugin: absolute gang

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#1967]
#### What would you like to be added:

gang that can reserve resources

#### Why is this needed:

The current gang plugin only checks whether resources meet the requirements when starting scheduling, and does not reserve resources for jobs, if a job has a total of 100 pods, after 50 pods are scheduled, another job preempts the resources, then the remaining 50 pods of the job cannot be scheduled, which does not meet the requirements of gang.

This is more common in sequential startup scenarios for tasks

**Comment by shinytang6** [comment]
> #### What would you like to be added:
> gang that can reserve resources
> 
> #### Why is this needed:
> The current gang plugin only checks whether resources meet the requirements when starting scheduling, and does not reserve resources for jobs, if a job has a total of 100 pods, after 50 pods are scheduled, another job preempts the resources, then the remaining 50 pods of the job cannot be scheduled, which does not meet the requirements of gang.
> 
> This is more common in sequential startup scenarios for tasks

Does that proposed to resolve the conflict with gang and dag?
I think a more elegant way is to implement group of gang, which means splitting a gang for each task under one job.

**Comment by hwdef** [comment]
@shinytang6 
Sounds good this way, we can talk more, my idea is still very rudimentary.
The goal is to make sequential startup work better with gang.

**Comment by HecarimV** [comment]
But there is no task layer in scheduling. Maybe we can directly regard the ongoing tasks as a 'pg' and judge the gang.
Just like any other normal job, except that the check of waiting tasks needs to be skipped.

@shinytang6 @Thor-wl 
How do you like

**Comment by tFable** [comment]
> The current gang plugin only checks whether resources meet the requirements when starting scheduling, and does not reserve resources for jobs

My understanding is that this is what the `SLA` plug in does: pods of sla-expired jobs start being reserved so other, smaller jobs cannot take over the resources. Is this correct?

**Comment by hwdef** [comment]
@tFable 
Not quite right, what I want is to have a plugin that reserves resources for all gang-enabled jobs, no matter how big or small this job is.

**Comment by k82cn** [comment]
> @tFable Not quite right, what I want is to have a plugin that reserves resources for all gang-enabled jobs, no matter how big or small this job is.

Adding a parameter to gang scheduling should be enough for that :)

**Comment by tFable** [comment]
> > @tFable Not quite right, what I want is to have a plugin that reserves resources for all gang-enabled jobs, no matter how big or small this job is.
> 
> Adding a parameter to gang scheduling should be enough for that :)

Hey @k82cn, do you mean this is something that can be done today? Or you mean for future design?

**Comment by hwdef** [comment]
@k82cn 
Thanks,your implementation is better. I was wondering if my idea about reserving resources for gang-enabled jobs would work.

**Comment by k82cn** [comment]
> @k82cn Thanks,your implementation is better. I was wondering if my idea about reserving resources for gang-enabled jobs would work.

hm...., different users ask for different behaviovr, we changed this feature for several times. So I think it's better to have such a parameter for that.

IMO, it should be ok to always return `true` in `pipelineFn` when parameter was enabled.
