### ISSUE TITLE
[Discussion] Rename volcano-sh/kube-batch to volcano-sh/scheduler

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#197]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

The scheduler of volcano is built on kube-batch with some enhancement; to distinguish with the kube-batch in upstream, suggest to rename volcano-sh/kube-batch to volcano-sh/scheduler.

**Comment by k82cn** [comment]
@hex108 @jiaxuanzhou @Jeffwan , any suggestion on that?

**Comment by hex108** [comment]
I am OK with it, however it will be better if they could be one. :)

**Comment by jiaxuanzhou** [comment]
lgtm too

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Jeffwan** [comment]
Makes sense. `Scheduler` sounds like a core component in `volcano-sh` and it's very clear and straighforward

**Comment by k82cn** [comment]
thanks all, let's update it :)

@asifdxtreme , please help on that.

**Comment by k82cn** [comment]
fixed by https://github.com/volcano-sh/volcano/pull/212
