### ISSUE TITLE
[Readme] Update readme to use appropriated K8s version

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/volcano#1979]
**What happened**:
In Readme,  we recommended use volcano in Kubernetes v1.16+ and deprecated Kubernetes  version < v1.16.  But in scheduler we use v1.CSINodes api which GA in K8s 1.7	https://github.com/volcano-sh/volcano/blob/f8e992ebded9bfff79d1d2f950ea2ff2ac81f516/pkg/scheduler/cache/cache.go#L474.

Actually, if use K8s 1.6 clustere install volcano scheduler will report following error.

![image](https://user-images.githubusercontent.com/10152842/150448349-6fb284ca-cecf-4fd7-9cb2-d6b6aff649ea.png)

We need update Readme file to guide fresh man to use correct k8s version.

**Comment by Lzhang-hub** [comment]
> **What happened**: In Readme, we recommended use volcano in Kubernetes v1.16+ and deprecated Kubernetes version < v1.16. But in scheduler we use v1.CSINodes api which GA in K8s 1.17
> 
> https://github.com/volcano-sh/volcano/blob/f8e992ebded9bfff79d1d2f950ea2ff2ac81f516/pkg/scheduler/cache/cache.go#L474
> 
> .
> Actually, if use K8s 1.6 clustere install volcano scheduler will report following error.
> 
> ![image](https://user-images.githubusercontent.com/10152842/150448349-6fb284ca-cecf-4fd7-9cb2-d6b6aff649ea.png)
> 
> We need update Readme file to guide fresh man to use correct k8s version.

@wpeng102  I get the same error in k8s v1.16, with volcano 1.5.1
![image](https://user-images.githubusercontent.com/57925599/179487516-d483f612-6eca-4d17-ab79-76abb4c0f547.png)

In this condition, How can i install volcano install volcano in k8s with v1.16? or must be upgrade k8s version?  can you give some advices? Thanks!

**Comment by Thor-wl** [comment]
@Lzhang-hub Hey. Please check the CSI driver is prepared in the node. If that works, it is mostly that the kubelet is at a relatively low version. You can try to update k8s version above v1.24.0 and have a try again.
