### ISSUE TITLE
Updating the documentation

### ISSUE THREAD

**Issue by sakkshm26** [volcano-sh/volcano#1982]
#### What would you like to be added:
I would like to work on updating the documentation.
#### Why is this needed:
There are some typos in different files of the documentation.

**Comment by k82cn** [comment]
And that'll be great if you can help to build an dashboad for volcano :)

**Comment by sakkshm26** [comment]
> And that'll be great if you can help to build an dashboad for volcano :)

Alright, how can I get started with it?

**Comment by hwdef** [comment]
We can start with the design.

**Comment by sakkshm26** [comment]
Actually, I'm not familiar with Figma or any other design tool. I can definitely help with the development part though.

**Comment by k82cn** [comment]
> Actually, I'm not familiar with Figma or any other design tool. I can definitely help with the development part though.

Design is not necessary for deashboard, most of contributor are backend developers right now :) 
That'll be great to have a dashboard for volcano job/queue/task, similar to OpenShift :)

**Comment by sakkshm26** [comment]
> > Actually, I'm not familiar with Figma or any other design tool. I can definitely help with the development part though.
> 
> Design is not necessary for deashboard, most of contributor are backend developers right now :) That'll be great to have a dashboard for volcano job/queue/task, similar to OpenShift :)

Ok, is there any website from which I can take reference? Also, shall I use React.js for developing it?

**Comment by k82cn** [comment]
> > > Actually, I'm not familiar with Figma or any other design tool. I can definitely help with the development part though.
> > 
> > 
> > Design is not necessary for deashboard, most of contributor are backend developers right now :) That'll be great to have a dashboard for volcano job/queue/task, similar to OpenShift :)
> 
> Ok, is there any website from which I can take reference? Also, shall I use React.js for developing it?

here is a demo video of OpenShift: https://www.youtube.com/watch?v=ude36NiiWMc , and here are some usefull link on OpenShift dashboard: https://cloud.redhat.com/blog/openshift-4-2-the-new-cluster-overview-dashboard .

It's ok to only focus on volcano related CRDs, e.g. job/queue/jobflow and configurations.

> Also, shall I use React.js for developing it?

Aha, you're the boss :)

**Comment by k82cn** [comment]
btw, here's the repo for dashboard: https://github.com/volcano-sh/dashboard
