### ISSUE TITLE
Set user customized wait-timeout-seconds for PodGroup based gang scheduling protocol.

### ISSUE THREAD

**Issue by SimonCqk** [volcano-sh/volcano#1993]
#### What would you like to be added:

Introduce a new filed in `podGroup.spec` named with `waitTimeoutSeconds` or sth similar, then users are able to configure `waitTimeoutSeconds` dynamically.

#### Why is this needed:

As it described in [resource-reservation](https://github.com/volcano-sh/volcano/blob/master/docs/design/job-resource-reservation-design.md#todo) design doc, this feature is in TODO list, however I can not find a related filed in latest [API definition](https://github.com/volcano-sh/apis/blob/master/pkg/apis/scheduling/v1beta1/types.go), it helps to balance between large-job-starving anomaly and block too many tasks due to resource reservation, we can scale maximum-reserve-time by job replicas or total requested resource.

**Comment by Thor-wl** [comment]
Hey, I guess what you want is SLA ensurance. If that, you can take a look at [SLA plugin](https://github.com/volcano-sh/volcano/blob/master/docs/design/sla-plugin.md).

**Comment by SimonCqk** [comment]
@Thor-wl hi, thanks for replying, it seems that `SLA` plugin implements the semantics I present above, what I am curious is it coupled with `Batch Volcano Job` api ? What if a user submit a job with other api-group along with a podgroup(represents a gang entity), how can volcano guarantees its SLA ?

**Comment by Thor-wl** [comment]
> 

Yes, this abilitiy is bind to Volcano Job currently. @jiangkaihua Is there any plan to ensure SLA for other workloads?

**Comment by Thor-wl** [comment]
> Hey, I guess what you want is SLA ensurance. If that, you can take a look at [SLA plugin](https://github.com/volcano-sh/volcano/blob/master/docs/design/sla-plugin.md).

Yes, this abilitiy is bind to Volcano Job currently. @jiangkaihua Is there any plan to ensure SLA for other workloads?

**Comment by Thor-wl** [comment]
> @Thor-wl hi, thanks for replying, it seems that `SLA` plugin implements the semantics I present above, what make me curious is it coupled with `Batch Volcano Job` api ? What if a user submit a job with other api-group along with a podgroup(represents a gang entity), how can volcano guarantees its SLA ?

Yes, this abilitiy is bind to Volcano Job currently. @jiangkaihua Is there any plan to ensure SLA for other workloads?

**Comment by jiangkaihua** [comment]
Yes, I have proposed PR #1961 to solve it. When a user submitted a job with other api-podgroup like `replicaset`, `daemonset`, etc., k8s would create pods first, then invoke volcano to create `podgroup` for the pods. So `podgroup` created from k8s pods would miss annotations of origin workloads, causing configurations inserted in the form of annotations neglected, like #1901 .

So my solution is to fetch annotations from upper resources by searching pod `ownerReferences`, and filled in `podgroup` annotations, so that configurations in annotations would be available for jobs with other api-podgroups.
