### ISSUE TITLE
refresh volcano membership

### ISSUE THREAD

**Issue by xiaoanyunfei** [volcano-sh/volcano#2005]
#### What would you like to be added:
I lost my two-factor authentication app and recovery code, so I had to recovery my github account .
Then I lost volcano membership.

I'm sorry for that. Will you please refresh my membership, thank you.

my previous issue: https://github.com/volcano-sh/volcano/issues/1839

**Comment by Thor-wl** [comment]
OK. @kevin-wangzefeng  Can you help for that?
