### ISSUE TITLE
About memory and hard disk limitations in pods

### ISSUE THREAD

**Issue by GuoYingLong** [volcano-sh/volcano#2015]
Pods created by the scheduler are configured with memory and hard disk limits. Will the Pod restart when resource usage exceeds the limit?

**Comment by Thor-wl** [comment]
I'm sorry for not getting the point. What do you mean of pods created by the scheduler?

**Comment by shinytang6** [comment]
I guess you are asking whether the pod will restart if the actual resource utilization exceeds the limit? @GuoYingLong

**Comment by GuoYingLong** [comment]
Yes, it is

**Comment by GuoYingLong** [comment]
> 



> 我是你在问，如果郭真的应有超过限制，Pod是否会重新启动？@@@龙龙

**Comment by GuoYingLong** [comment]
> I guess you are asking whether the pod will restart if the actual resource utilization exceeds the limit? @GuoYingLong

Yes, it is

**Comment by shinytang6** [comment]
It depends on your pod restartPolicy, default it's set to Always, if your pod is OOM, it will restart automatically.
