### ISSUE TITLE
Tmp question, i cannot sign in volcano slack, how can i do?

### ISSUE THREAD

**Issue by zhenxiu** [volcano-sh/volcano#2017]
i use my slack mail, i got no account; i use apple id, i got system error: 
![apple_slack](https://user-images.githubusercontent.com/14161887/153788141-acec16ec-2a8c-4e19-9ba4-28cfd82dcb7d.png)

**Comment by shinytang6** [comment]
Not sure what's going on, maybe you should try with your google account again, l just succeeded in logging in )

**Comment by zhenxiu** [comment]
> Not sure what's going on, maybe you should try with your google account again, l just succeeded in logging in )

why i cannot log in with outlook

**Comment by hwdef** [comment]
This should be a slack question and shouldn't be asked here

**Comment by zhenxiu** [comment]
> This should be a slack question and shouldn't be asked here
i cannot sign up or sign in by google email
![slack_google](https://user-images.githubusercontent.com/14161887/153821985-44cc3c89-d9bb-45e7-b91c-18bad1af68c8.png)

**Comment by zhenxiu** [comment]
and where can i ask questions

**Comment by hwdef** [comment]
If you are a Chinese, you can join the WeChat group.

**Comment by zhenxiu** [comment]
> If you are a Chinese, you can join the WeChat group.



> If you are a Chinese, you can join the WeChat group.

ths, could you provide the wechat group info?

**Comment by Thor-wl** [comment]
> > If you are a Chinese, you can join the WeChat group.
> 
> > If you are a Chinese, you can join the WeChat group.
> 
> ths, could you provide the wechat group info?

Pls add the wetchat account "k8s2222" as friend and type "volcano".
