### ISSUE TITLE
Documentation for using Spark-submit is missing

### ISSUE THREAD

**Issue by lattsi** [volcano-sh/volcano#2027]
#### What would you like to be added:
My company would like to use Volcano for gang scheduling Spark application. We are using spark-submit (instead of Spark operator) to run Spark jobs. However, reading [volcano documentation](https://volcano.sh/en/docs/spark_on_volcano/), I do not see any guide to how to set it up. Could you point me to resource that contains the instruction? I'd love to contribute to the doc as well if needed.

#### Why is this needed:
[Volcation documentation](https://volcano.sh/en/docs/spark_on_volcano/) says there's a way to run Spark without spark operator but does not contain any info. It hinders adoption since a lot of users are interested in using Spark without operator as well.

Thanks.

**Comment by Thor-wl** [comment]
I'm sorry for the lack of docs. We are always keeping refresh the docs recently. Thanks for your feedback. We will try to add the guidence.
/assign @Thor-wl @renhuanyu

**Comment by lattsi** [comment]
Thanks Thor-wl. In the meantime, is there any sample / resource I can look at? For gang scheduling, it's a bit unclear to me what and where the configs should be, for instance, where should gang scheduling flag, grouping and resource limits go, for spark-submit route.

**Comment by Thor-wl** [comment]
Well, AFAK, there seems few examples in the materials about that. But I believe there must be Volcano end users who makes use of Spark submit and gang scheduling. I can help take a consultant. 
@Yikun @zen-xu Can you help for that?

**Comment by william-wang** [comment]
@Yikun Thanks YiKun's great contribution on Spark with Volcano. We can work together to make a guide doc with new added parameter and usage :)

**Comment by lattsi** [comment]
THanks for the info Yikun. Could you point me to the issue for adding Spark support for gang scheduling so I can keep track of the progress and timeline?

**Comment by Yikun** [comment]
@lattsi Hi, sorry for late reply, here is the integration test to show how we suppprted gang scheduling (resource reservation) in Spark.

https://github.com/apache/spark/pull/35640

**Comment by Yikun** [comment]
https://github.com/apache/spark/pull/35870

@lattsi Here is also a doc PR to help you understand how spark with volcano work together.

You could also help to review about it.
