### ISSUE TITLE
support creating podgroup in scheduler component

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#2028]
#### What would you like to be added:
Add a option for scheduler to support creating podgroup in scheduler component.

#### Why is this needed:
Some Volcano users only integrate scheduler component of Volcano in their systems. They have to manage the podgroup creating themselves. It is necessary to enhance Volcano scheduler to create podgroup automatically for these uses.

**Comment by hwdef** [comment]
Scheduler integrated controller work?

**Comment by william-wang** [comment]
> Scheduler integrated controller work?
Yes, only for podgroup.
