### ISSUE TITLE
Scheduler fails to start after installing Volcano via Helm

### ISSUE THREAD

**Issue by tFable** [volcano-sh/volcano#2047]
**What happened**:

After installing Volcano using Helm from [here](https://github.com/volcano-sh/volcano/tree/release-1.5/installer/helm/chart/volcano) (release 1.5 branch), the volcano-scheduler pod fails to start. The logs from the scheduler pod show

```
2022/03/03 16:03:06 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
W0303 16:03:06.178666       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: failed init default queue, with err: the server could not find the requested resource (post queues.scheduling.volcano.sh)

goroutine 1 [running]:
volcano.sh/volcano/pkg/scheduler/cache.newSchedulerCache(0x7ffec96c9671, {0x187111c, 0x0}, {0x1870537, 0x0}, {0x0, 0x0, 0x8})
        /usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/cache/cache.go:365 +0x20fc
volcano.sh/volcano/pkg/scheduler/cache.New(...)
        /usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/cache/cache.go:74
volcano.sh/volcano/pkg/scheduler.NewScheduler(0x0, {0x187111c, 0x7}, {0x7ffec96c9671, 0x29}, 0x3b9aca00, {0x1870537, 0x7}, {0x0, 0x0, ...})
        /usr/wulei/go_projects/src/volcano.sh/volcano/pkg/scheduler/scheduler.go:74 +0xf0
volcano.sh/volcano/cmd/scheduler/app.Run(0xc00049e0f0)
        /usr/wulei/go_projects/src/volcano.sh/volcano/cmd/scheduler/app/server.go:76 +0x1bf
main.main()
        /usr/wulei/go_projects/src/volcano.sh/volcano/cmd/scheduler/main.go:65 +0x1a5
```

**What you expected to happen**:
I expect the scheduler to start. This issue doesn't occur when I install volcano with
`kubectl apply -f volcano-development.yaml` using [this](https://github.com/volcano-sh/volcano/blob/release-1.5/installer/volcano-development.yaml) file.
**How to reproduce it (as minimally and precisely as possible)**:
- install Volcano via helm with
`helm install volcano ./helm/chart/volcano --namespace volcano`
- run `kubectl get pods -A` and observe the volcano-scheduler pod in failed state
**Anything else we need to know?**:
What is the recommended way to install Volcano? Is installing via the [volcano-development.yaml](https://github.com/volcano-sh/volcano/blob/release-1.5/installer/volcano-development.yaml) file supported and recommended?
**Environment**:
- Volcano Version: 1.5
- Kubernetes version (use `kubectl version`):1.23
- Cloud provider or hardware configuration:vSphere on-prem
- OS (e.g. from /etc/os-release):
`NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`
- Kernel (e.g. `uname -a`):`5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by ldd91** [comment]
Looks like the crd was not installed,you can exec "kubectl get crd |grep queues.scheduling.volcano.sh" to check if crd exits

**Comment by tFable** [comment]
Hey @ldd91 , thanks for your message.

The CRD is indeed not installed when installing Volcano via helm

```
kubectl get customresourcedefinitions.apiextensions.k8s.io -A
No resources found
```

This is not the case when installing using `kubectl apply -f volcano-development.yaml`. In this case, the CRD does get installed.

Is the Helm chart expected to install the CRD?

**Comment by ldd91** [comment]
I use https://github.com/volcano-sh/volcano/blob/master/installer/volcano-development.yaml#L8794 to  deploy volcano cluster,queue crd was installed

**Comment by tFable** [comment]
Hey @ldd91 , 

I had the same experience when installing via volcano-development.yaml. All CRDs are installed and Volcano appears to work properly.

Is the Helm chart not supposed to work, then?

t

**Comment by Thor-wl** [comment]
Hey, @tFable I used helm to install Volcano and it works for me. I noticed that the error your reported has the same root reason with https://github.com/volcano-sh/volcano/issues/2048. So I guess there is not someting wrong with helm installation. Are you sure the environment is available?

**Comment by tFable** [comment]
Hey @Thor-wl, thanks for your note.

When I install volcano via help (or via the volcano-development.yaml) is after I have uninstalled volcano using the same method. For example, the `default` queue doesn't exist at the time of the installation with either method.

Could this be some kind of race condition?

Additionally, can you confirm that installing volcano using the `volcano-development.yaml` from the `release-1.5` branch is a supported method? Or is helm preferred?

Thanks!
t

**Comment by Thor-wl** [comment]
> Hey @Thor-wl, thanks for your note.
> 
> When I install volcano via help (or via the volcano-development.yaml) is after I have uninstalled volcano using the same method. For example, the `default` queue doesn't exist at the time of the installation with either method.
> 
> Could this be some kind of race condition?
> 
> Additionally, can you confirm that installing volcano using the `volcano-development.yaml` from the `release-1.5` branch is a supported method? Or is helm preferred?
> 
> Thanks! t

Hey, @tFable AFAIK, intalling Volcano with `volcano-development.yaml` is more widely used. And I'm sure that works for `release-1.5`. Besides, helm also should be available. I will take a check about that and then reply to you here.

**Comment by tFable** [comment]
Thanks so much, @Thor-wl !
