### ISSUE TITLE
Suggest to add a phase `completed` for podgroup

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2056]

**Comment by william-wang** [comment]
It's reasonable and necesary, currenlty we have to use multiple conditional judgments to check whether the podgroup is completed.  Please  refer to #2038.

**Comment by k82cn** [comment]
Any more backgroup about this issue?

**Comment by shinytang6** [comment]
> Any more backgroup about this issue?

Give me a scene I met:
If the upper job we use is not vcjob, e.g paddlejob, when the paddlejob task is completed (**not deleted**), the corresponding podgroup will still exist, it will eventually change to the inqueue state, resulting in unnecessary resource occupation. Therefore, l hope to introduce a completed podgroup state to refer to the already completed job.

This phenomenon is kindy like https://github.com/volcano-sh/volcano/issues/1853, but the difference is that the job is not deleted but finished.

**Comment by Thor-wl** [comment]
Is there any process about the following development such as cm?
