### ISSUE TITLE
Is there any way to limit the number of sla jobs

### ISSUE THREAD

**Issue by ldd91** [volcano-sh/volcano#2060]
#### What would you like to be added:
In my scenario, we only set sla for urgent vcjob，Is there any way to limit the number of sla vcjobs?

**Comment by Thor-wl** [comment]
AFAIK, there is no way to set the number temporarily.
@jiangkaihua

**Comment by jiangkaihua** [comment]
@Thor-wl Yes, by now `sla` only support setting for all jobs in scheduler configuration, and seperate job in job annotation.

**Comment by ldd91** [comment]
Ok, Thank you for your reply
