### ISSUE TITLE
Is there any way to apply different strategies to different jobs

### ISSUE THREAD

**Issue by HecarimV** [volcano-sh/volcano#2062]
#### What would you like to be added:
The way to choose strategies for different jobs

#### Why is this needed:
The plugins  are set for all jobs in scheduler configuration. However some jobs do not hope some plugins to function.
For example, some jobs tend to use binpack strategy, some jobs are not.

**Comment by Thor-wl** [comment]
@HecarimV I'm sorry for there is not a way for Volcano to do that. All the strategies configured in the scheduler configuration are applied to all the jobs.

**Comment by HecarimV** [comment]
> @HecarimV I'm sorry for there is not a way for Volcano to do that. All the strategies configured in the scheduler configuration are applied to all the jobs.

Okay thank you. And is it possible in the future design？

**Comment by k82cn** [comment]
> > @HecarimV I'm sorry for there is not a way for Volcano to do that. All the strategies configured in the scheduler configuration are applied to all the jobs.
> 
> Okay thank you. And is it possible in the future design？

We're going to use different conf for different `Queue` :)

**Comment by HecarimV** [comment]
> > > @HecarimV I'm sorry for there is not a way for Volcano to do that. All the strategies configured in the scheduler configuration are applied to all the jobs.
> > 
> > 
> > Okay thank you. And is it possible in the future design？
> 
> We're going to use different conf for different `Queue` :)

Thanks, so that is to say, use queues to divide different types of jobs

**Comment by Thor-wl** [comment]
> Thanks, so that is to say, use queues to divide different types of jobs
Yes, you can divide the jobs into different queues according to the scheduling strategies. Basicilly, suggest to divide the vcjobs according to the business and projects.
