### ISSUE TITLE
Preemption between Jobs within Queue - Not Working

### ISSUE THREAD

**Issue by dontan001** [volcano-sh/volcano#2067]
**What happened**:
I am trying to verify how preemption works for jobs in the same queue, after experimentation we dont see the low-priority job resource is released for high-priority jobs to run when the allocated queue resource is running out.

**What you expected to happen**:
If a high-priority job comes in to the queue and all assigned resources are used, it would be good for volcano to terminate the low-priority running job to return resources for the high-priority job to run, however we dont observe this

**How to reproduce it (as minimally and precisely as possible)**:
Here is the applied volcano scheduler config
```yaml
$ kubectl -n volcano-system get configmap volcano-scheduler-configmap -oyaml
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, reclaim, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
```

Here are the queues
```yaml
$ kubectl get queues -oyaml
apiVersion: v1
items:
- apiVersion: scheduling.volcano.sh/v1beta1
  kind: Queue
  metadata:
    creationTimestamp: "2022-02-21T03:27:39Z"
    generation: 1
    name: default
    resourceVersion: "3436794"
    selfLink: /apis/scheduling.volcano.sh/v1beta1/queues/default
    uid: 58541619-9962-4eb2-bc3e-1c93894e4653
  spec:
    guarantee: {}
    reclaimable: true
    weight: 1
  status:
    reservation: {}
    state: Open
- apiVersion: scheduling.volcano.sh/v1beta1
  kind: Queue
  metadata:
    creationTimestamp: "2022-03-07T09:39:10Z"
    generation: 2
    name: test
    resourceVersion: "3664102"
    selfLink: /apis/scheduling.volcano.sh/v1beta1/queues/test
    uid: 2cbd6cab-cfc0-4653-819a-40b30a6ca432
  spec:
    capability:
      cpu: 2
    reclaimable: true
    weight: 1
  status:
    reservation: {}
    state: Open
```

Here are the defined priorityclass
```yaml
$ kubectl get pc -oyaml
apiVersion: v1
items:
- apiVersion: scheduling.k8s.io/v1
  description: volcano test only
  kind: PriorityClass
  metadata:
    creationTimestamp: "2022-03-07T07:48:46Z"
    generation: 1
    name: high-priority
    resourceVersion: "3600895"
    selfLink: /apis/scheduling.k8s.io/v1/priorityclasses/high-priority
    uid: fb2d1d35-a76f-4974-84a9-940a10b8db88
  value: 333
- apiVersion: scheduling.k8s.io/v1
  description: volcano test only
  kind: PriorityClass
  metadata:
    creationTimestamp: "2022-03-07T07:49:42Z"
    generation: 1
    name: low-priority
    resourceVersion: "3600948"
    selfLink: /apis/scheduling.k8s.io/v1/priorityclasses/low-priority
    uid: 68db6955-1f9b-40ba-b0a0-e337b8755f94
  value: 111
```

Here are the low priority job to run, and it is purposed to consume all the cpu resources
```yaml
$ cat <<EOF | kubectl create -f -
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-low
spec:
  minAvailable: 2
  schedulerName: volcano
  priorityClassName: low-priority
  queue: test
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 2
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
            - command:
              - sleep
              - 10m
              image: nginx:latest
              name: nginx
              resources:
                requests:
                  cpu: 1
                limits:
                  cpu: 1
          restartPolicy: Never
EOF          
```

After all the pods are up, I submitted the 2nd high-priority job
```yaml
$ cat <<EOF | kubectl create -f -
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-high
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  queue: test
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        spec:
          containers:
            - command:
              - sleep
              - 2m
              image: nginx:latest
              name: nginx
              resources:
                requests:
                  cpu: 1
                limits:
                  cpu: 1
          restartPolicy: Never
EOF          
```

For quite a while after the test-high job is submitted, I don't see any pod for low-priority job get evicted to return resources
The I am trying to investigate further and captured more log details from scheduler, seems the test-high job does not even get enqueued
```yaml
I0309 09:03:49.151302       1 enqueue.go:78] Try to enqueue PodGroup to 1 Queues
I0309 09:03:49.151363       1 overcommit.go:111] Sufficient resources, permit job <default/test-high> to be inqueue
I0309 09:03:49.151637       1 proportion.go:323] job test-high min resource <cpu 1000.00, memory 0.00>, queue test capability <cpu 2000.00, memory 2081755136.00> allocated <cpu 2000.00, memory 0.00>
I0309 09:03:49.151808       1 proportion.go:327] job test-high inqueue false
I0309 09:03:49.151856       1 enqueue.go:103] Leaving Enqueue ...          
```

Could you guys please help me here? thanks a lot

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ldd91** [comment]
proportion plugin do not permit pg to be inqueue because of  AddJobEnqueueableFn shows minReq + allocates +inqueue > realCapability

**Comment by dontan001** [comment]
Thank you @ldd91 for the response, that is exactly the same as what we understood from the captured log also. 

Here my question is if the high-priority job is denied to be in status inqueue, the action logic of PREEMPT will not be triggered at all, that means there is no chance the PREEMPTION could occur between jobs within queue. 
This is confusing and I can see this confuse other users as well, for example issue #1772 #2034 

Is is possible you can share us an example to disclose how the action PREEMPT work?  or how I could make the scenario above work ? 

Very appreciate

**Comment by ldd91** [comment]
In your scenario  i suggest that your put  overcommit plugin and proportion plugin in different tire,and overcommit should be ahead of proportion plugin

**Comment by ldd91** [comment]
And you should also adjust your overCommitFactor

**Comment by dontan001** [comment]
> In your scenario i suggest that your put overcommit plugin and proportion plugin in different tire,and overcommit should be ahead of proportion plugin

I can have a try, but what is theory behind the adjustment?

**Comment by dontan001** [comment]
> And you should also adjust your overCommitFactor

I assume the overcommit factor is default 1 and it is good for us,  could you please help clarify the reason behind this adjustment also? 

As per the log, seems there is no problem with overcommit at all

@Thor-wl @ldd91

**Comment by Jason-Liu-Dream** [comment]
@dontan001 maybe you can try this scheduler config
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false # important！no need guarantee the minimum  available task number 
      - name: conformance
    - plugins:
      - name: drf
        enablePreemptable: false # important！maybe ping-pong when one group tasks have same priority
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```

**Comment by shmily0000** [comment]
@Jason-Liu-Dream 
Hello, brother. After trying your cm, I still can't. My queue is 2C. Two low priority long jobs are enabled. High priority high priority ones are always in pending mode
