### ISSUE TITLE
Make sure `Open` state queue can be deleted until we support queue close in kubectl

### ISSUE THREAD

**Issue by Yikun** [volcano-sh/volcano#2068]
**What happened**:
`Open` state queue can't be deleted in kubectl, this is not very convenient for users.

We'd better to make sure `Open` state queue can be deleted until we support queue operations in kubectl

**What you expected to happen**:
`Open` state queue can be deleted 

**How to reproduce it (as minimally and precisely as possible)**:
create a queue can't be deleted by kubectl

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`): 1.23

**Comment by hwdef** [comment]
https://github.com/volcano-sh/volcano/issues/2058
https://github.com/volcano-sh/volcano/issues/1687

Please combine the content of these two issues and the discussion at the last community meeting to make a comprehensive judgment

**Comment by Thor-wl** [comment]
It may not be so reasonable for **open** queue to be deleted directly. There may be still some running and new coming jobs.
