### ISSUE TITLE
Update the Volcano imagePullPolicy

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#2070]
#### What would you like to be added:
change the "imagePullPolicy“ from "IfNotPresent" to "Aways"

#### Why is this needed:
Currently the imagePullPolicy is "IfNotPresent" in volcano-development.yaml, It is requested to be updated to "Aways".  Users do not need to delete the local image manully and pull the latest image whenever  there is new image available.

**Comment by Aju100** [comment]
Hi @william-wang I would like to work on this beginner good issue. Can you please assign to me
