### ISSUE TITLE
Update pod deleting policy when VolcanoJob's task replicas field changes

### ISSUE THREAD

**Issue by flyhighzy** [volcano-sh/volcano#2074]
#### What would you like to be added:
when volcanoJob's task replicas field decreased, we want to have pending pods deleted at first, and then the other running ones, but now VolcanoJob will delete pod by it's index in name.

#### Why is this needed:
related to [elastic-scheduler](https://github.com/volcano-sh/volcano/blob/master/docs/design/elastic-scheduler.md),  in some elastic AI training or serving scenes, we need to adjust volcanoJob's replicas field for one or more tasks according to cluster's allocatable resource. When some pods in one job are preempted by other high-priority jobs, this job can have some pending pods left, then we'll decrease this job's replicas to remove these pending pods, and keep the running pods unchanged to ensure business SLO

**Comment by Thor-wl** [comment]
This feautre is on the way. @qiankunli is working on that.
