### ISSUE TITLE
Update Admission-Controller Image in Docker Hub

### ISSUE THREAD

**Issue by thandayuthapani** [volcano-sh/volcano#208]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Admission Init container is not running since it is not able to find ./gen-admission-secret.sh
**Logs**:
Events Generated:
```
Events:
  Type     Reason     Age   From                  Message
  ----     ------     ----  ----                  -------
  Normal   Scheduled  11m   default-scheduler     Successfully assigned default/test-admission-init-2ffdd to kube-node-3
  Normal   Pulled     11m   kubelet, kube-node-3  Container image "volcanosh/vk-admission:latest" already present on machine
  Normal   Created    11m   kubelet, kube-node-3  Created container
  Warning  Failed     11m   kubelet, kube-node-3  Error: failed to start container "main": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./gen-admission-secret.sh\": stat ./gen-admission-secret.sh: no such file or directory": unknown
```

**What you expected to happen**:
Admission Controller Container should not crash
**How to reproduce it (as minimally and precisely as possible)**:
Use volcano helm deployment to deploy.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: Latest code from master branch
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
4.15.0-50-generic #54-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by TommyLike** [comment]
@thandayuthapani thanks for working on updating the image

**Comment by asifdxtreme** [comment]
<img width="830" alt="Screenshot 2019-06-11 at 7 02 06 AM" src="https://user-images.githubusercontent.com/9736066/59237187-e9ba9880-8c16-11e9-9e1a-39af865c8870.png">

volcanosh/vk-admission has been updated , @k82cn do I need to update the `volcanosh/vk-controllers` and `volcanosh/vk-kube-batch` with the latest code?

**Comment by asifdxtreme** [comment]
@k82cn can we close this issue now?

**Comment by k82cn** [comment]
@asifdxtreme , please go ahead to update all with latest code.

**Comment by asifdxtreme** [comment]
![image](https://user-images.githubusercontent.com/9736066/59579537-efb6ea80-90ea-11e9-9406-cc897fa031da.png)


All the releated images has been updated with 'latest' tag

**Comment by asifdxtreme** [comment]
@k82cn can we go ahead and close this issue?

**Comment by k82cn** [comment]
that's ok to close that.
