### ISSUE TITLE
Request to be a Member of Volcano community

### ISSUE THREAD

**Issue by Yikun** [volcano-sh/volcano#2086]
I'm requesting to be a Member of Volcano community.

My major contributions are making volcano better in bigdata field and adding Volcano native support in Spark community:

- Volcano Java/Scala SDK: Make Volcano as official extension in [fabric8io/kubernetes-client](https://github.com/fabric8io/kubernetes-client/tree/master/extensions/volcano) to bring more friendly UX for Vocano big data and Java/Scala users .
- Make [Support Customized Kubernetes Schedulers Proposal](https://lists.apache.org/thread/cz3cpp8q4pgmh7h35h6lvkwf6g3lwhcd) (aka Support Volcano/Alternative Schedulers Proposal) getting approved in Spark community: [SPARK-36057](https://issues.apache.org/jira/browse/SPARK-36057). 
- Add Volcano as native support module in [Apache Spark on K8S](https://github.com/apache/spark/commit/598461498192ab71233c03183d47b609bf375f9a), also implemented and tested resource reservation, priority, queue scheduling feature for Spark with Volcano.

Hope bring more improvements for Volcano including and not limited to big data field in future!

**Comment by k82cn** [comment]
+1

**Comment by hwdef** [comment]
+1 Thanks for your work!

**Comment by Thor-wl** [comment]
+1

**Comment by shinytang6** [comment]
+1
