### ISSUE TITLE
Job is restarted when worker task is finished eariler in EKS

### ISSUE THREAD

**Issue by hhluo01** [volcano-sh/volcano#2087]
In the kubernete clusters, we are using the auto-scaler for the resource provisioning.  We found for the pytorch distributed training job, if a node finished eariler and the scaler scale down it, the pod is marked deleted and will trigger the deletePod being called, then due to this pod eviction event, the job will be restarted and then failed.

**Comment by hhluo01** [comment]
One solution applied local is to add a condition check in the code:

https://github.com/volcano-sh/volcano/blob/master/pkg/controllers/job/job_controller_handler.go#L338

	if pod.Status.Phase == v1.PodSucceeded {
		klog.Infof("deletePod: skip processing the pod deletion event: succeeded: %s, %s",
			pod.Namespace, pod.Name)
		return
	}

It seems to fix the issue.  However, I don't know if this is the right solution.

**Comment by hhluo01** [comment]
Thank you @Thor-wl

**Comment by k82cn** [comment]
IMO, there're two points in this issue:

1. If completed Pod was deleted, the related action should ignore the event
2. Volcano should work with cluster-autoscaler on resouces provision, e.g. gang

Regarding 1, AFAIK, we used to handle this issue before; anway, let's check it again :)
Regarding 2, prefer to draft an design doc for it; I'm thinking to have a `ClusterInfo` CRD for volcano & cluster-autoscaler to communicate. And regarding cluster-autoscaler, I'm also thinking to build a new one to have more algorithms :)

If any comments, please let me know :)

**Comment by hhluo01** [comment]
Sorry, I missed the last weekly meeting.  Is there any update on this one?  Which solution will be applied?  thanks

**Comment by Thor-wl** [comment]
> Sorry, I missed the last weekly meeting. Is there any update on this one? Which solution will be applied? thanks

I'm sorry for that the last weekly meeting was cancelled for some reasons. I'll take it into this weekly meeting.

**Comment by hhluo01** [comment]
Got it, thanks!
