### ISSUE TITLE
Add Volcano doc for specific version yaml installation

### ISSUE THREAD

**Issue by Yikun** [volcano-sh/volcano#2093]
#### What would you like to be added:
```
Install with YAML files
For x86_64:
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml

For arm64:
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development-arm64.yaml
```

The website only docs how to install the latest version volcano using YAML files. better to mentioned how to install specific version volcano.

#### Why is this needed:

For users who want to install specific version volcano.

Related: futher supported doc for multiple version https://github.com/volcano-sh/volcano/issues/2080

**Comment by william-wang** [comment]
It's reasonalbe. It needs to be refined and guide user to install specific version more easier.
