### ISSUE TITLE
where can I find the details about the distributed training examples?

### ISSUE THREAD

**Issue by jxfruit** [volcano-sh/volcano#2106]
I am confused about distributed training jobs on volcano. I have following questions: 1) only tensorflow PS-worker strategy  can be supported ? How about MultiWorkerMirroredStrategy/CentralStorageStrategy? 2) How to run a distributed pytorch job? 3) where can I find the details about the distributed training examples?
tks!

**Comment by Thor-wl** [comment]
+1
Can we add an repository for examples like https://github.com/kubernetes/examples? It seems that there are only some fragements for how to make use of Volcano in specified scenarios for end users.

**Comment by k82cn** [comment]
xref: https://github.com/volcano-sh/volcano/tree/master/example

> Can we add an repository for examples like https://github.com/kubernetes/examples?

It's not only an example, it should be an official integration guidance for end user.

**Comment by jxfruit** [comment]
@Thor-wl can u  give a tutorial about distributed pytorch job? tks
