### ISSUE TITLE
Pod has been pending if another pod are terminating for a long time

### ISSUE THREAD

**Issue by ldd91** [volcano-sh/volcano#2107]
**What happened**:
There are two GPU node in my cluster:

```
kubectl get node
NAME                STATUS                     ROLES                        AGE      VERSION         USED-GPU
node1               Ready                       CPU,GPU                      10d     v1.21.7         9/10
node2               Ready                       CPU,GPU                      10d     v1.21.7         10/10
```

In node2 ,a pod name job1 use 2 GPU has been terminating for a long time for unknown reasons
when 1 submit a vcjob name job2 with 1 GPU,it always allocate to node2，but because of job1 is terminating, pod of job2 is pending for a long time

**What you expected to happen**:
job2 should allocate to node1 first

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ldd91** [comment]
According to https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/actions/allocate/allocate.go#L220  node1 and node2 can be candidateNodes,but I'm a little confused in PrioritizeNodes why node2 scored the highest.

**Comment by wpeng102** [comment]
could you append the scheduler configmap to show which plugins are enabled.

**Comment by ldd91** [comment]
@wpeng102  Thank you for your reply.
 kubectl get configmap  volcano-scheduler-configmap  -n volcano-system -o yaml
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"volcano-scheduler.conf":"actions: \"enqueue, allocate, backfill\"\ntiers:\n- plugins:\n  - name: priority\n  - name: gang\n  - name: conformance\n- plugins:\n  - name: drf\n  - name: predicates\n  - name: proportion\n  - name: nodeorder\n  - name: binpack\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"volcano-scheduler-configmap","namespace":"volcano-system"}}
  creationTimestamp: "2021-04-25T09:44:07Z"
  name: volcano-scheduler-configmap
  namespace: volcano-system
  resourceVersion: "412717546"
  uid: f0d3600b-7c99-454e-8ee8-5dc757c36e08

**Comment by k82cn** [comment]
IMO, it's reasonable to have a plugin to consider terminating time of the Pod :)

**Comment by wpeng102** [comment]
In `allocate` action, the nodes which current idle resource  and nodes which future idle resource can meet pod request are candidate nodes. IMO,  nodes which current idle resource can meet pod request should be the first candidate node,  and future idle resource nodes is the second candidate nodes.

https://github.com/volcano-sh/volcano/blob/183a1781a83fb4b76260b754f294d89b057ad747/pkg/scheduler/actions/allocate/allocate.go#L219-L223

**Comment by k82cn** [comment]
> IMO, nodes which current idle resource can meet pod request should be the first candidate node, and future idle resource nodes is the second candidate nodes.

hm... yes, we should balance the pending time & executing time of the Pod :)
