### ISSUE TITLE
lost labels/annotations in podtemplatespec

### ISSUE THREAD

**Issue by kye308** [volcano-sh/volcano#2108]
**What happened**:

Submitted vcjob object with annotations and labels in `kubernetes.PodTemplateSpec` ObjectMeta do not show up in the created pod.

**What you expected to happen**:

set annotations/labels in volcano task spec for volcano.Job object:
```
podTemplateSpec := kubernetes.PodTemplateSpec{
        Spec: podSpec,
        ObjectMeta: meta.ObjectMeta{
            Annotations: map[string]string{"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"},
            Labels:      map[string]string{"long-running-job": "true"},
        },
    }
```

submitted job does not contain these annotations or labels. But the object that was submitted with the volcano api did contain them (from debug logging)

**How to reproduce it (as minimally and precisely as possible)**:

Submit vcjob with annotations/labels in the pod template spec

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.4.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hwdef** [comment]
https://github.com/volcano-sh/volcano/pull/1649

I think this bug is fixed. You can update the crd and volcano version.

**Comment by kye308** [comment]
@hwdef what versions should we be using?

**Comment by wpeng102** [comment]
> @hwdef what versions should we be using?

V1.4.0+ version should contain this fix.

**Comment by kye308** [comment]
@wpeng102 seems like the upgrade to crd version v1 is only present in v1.5.0+

https://github.com/volcano-sh/volcano/commit/27fcaf8af1bcacd596b4e6fcd16a4f055753fb9b
