### ISSUE TITLE
GPU enhancement

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#2111]
#### What would you like to be added:

Enhance GPU support in Volcano for AI/HPC :)

#### Why is this needed:

Currently, there're several seperate requests on GPU support in Volcano; I'd like to start this thread to include all related items, and try to make them align with each other :)

**Comment by william-wang** [comment]
Tasks:

- [ ] vGPU support in scheduling(@archlitchi @william-wang )
design doc (To be added)
implemetation(To be added)
- [ ] vGPU support in device plugin(@archlitchi @william-wang )
design doc (To be added)
implemetation(To be added)
