### ISSUE TITLE
The variable name is strange, so it is hard to read code

### ISSUE THREAD

**Issue by HeGaoYuan** [volcano-sh/volcano#2120]
Hi, Volcano Team.
    Thanks for your great work firstly.
    When I read the source code in Volcano, I found the variable name is strange. Maybe everyone's habits are different. Or is there some rules that I don't know? 
    I give some examples below.
    (1) why is it named pp but not np or nop?
   https://github.com/volcano-sh/volcano/blob/db2936fd44f304862a6f1888204fb41ed44ede6d/pkg/scheduler/plugins/nodeorder/nodeorder.go#L73
    (2) why is it named pi but not ti?
    https://github.com/volcano-sh/volcano/blob/db2936fd44f304862a6f1888204fb41ed44ede6d/pkg/scheduler/cache/event_handlers.go#L63

**Comment by k82cn** [comment]
No specific rule for such kind of name, that should be ok to update them accordingly :)

**Comment by HeGaoYuan** [comment]
> No specific rule for such kind of name, that should be ok to update them accordingly :)

Thanks for your reply.
If you think it's worth to update, I can post a PR.
If you think it's trivial, I just close the Issue.

**Comment by k82cn** [comment]
> If you think it's worth to update, I can post a PR.

I'm ok to update them accordingly :)
