### ISSUE TITLE
Quick Start on official document can't work 

### ISSUE THREAD

**Issue by hermitgreen** [volcano-sh/volcano#2126]
**What happened**:

Quick Start on official document can't work 
While I create a vcjob, job maintain pending status:
![d1c53cc6b87a5aaf05b1ea75df91253e](https://user-images.githubusercontent.com/31271515/160529307-15143657-0c50-443b-a92b-f373df9effcd.jpeg)
And podgroup has None status:
![cffeebc768e900d371124dc55b7a7e5d](https://user-images.githubusercontent.com/31271515/160529378-765fb436-b6d4-4bb1-9edf-438b39c7e798.jpeg)
My queue has 200 CPUs but I only require 2
![a3f9630a489bb33519ebf6a5189ea905](https://user-images.githubusercontent.com/31271515/160529470-97c0aa0e-72f5-48d9-9176-729b2ebee597.jpeg)
And controllers log:
![c0eb58dfd505b9b6c030be31317f63dd](https://user-images.githubusercontent.com/31271515/160529568-942a9eb8-776e-439e-944f-dd97880e0747.png)
 

**What you expected to happen**:
Work properly.

**How to reproduce it (as minimally and precisely as possible)**:
https://volcano.sh/zh/docs/tutorials/

**Anything else we need to know?**:
None.

**Environment**:
- Volcano Version: 
- Kubernetes version (use `kubectl version`): 1.16.3
- Cloud provider or hardware configuration: Self
- OS (e.g. from /etc/os-release): CentOS7.9
- Kernel (e.g. `uname -a`): 4.17.11
- Install tools:
- Others:

**Comment by hwdef** [comment]
volcano version?
To be honest, the version of k8s is a bit low.
Are other components of volcano running normally?

**Comment by hermitgreen** [comment]
> volcano version? To be honest, the version of k8s is a bit low. Are other components of volcano running normally?

volcano version is latest, may 1.5.1. components seems work properly.
<img width="781" alt="image" src="https://user-images.githubusercontent.com/31271515/160546023-9cdf71e5-2d14-419f-bb04-ff17481417dd.png">

**Comment by hwdef** [comment]
do you have sufficient resources?

**Comment by hermitgreen** [comment]
> do you have sufficient resources?

Queue has 200 CPUs but I only require 2, I guess it's can't be insufficient

**Comment by hwdef** [comment]
Can you try to upgrade the version of k8s? 1.16 is a long time ago version

**Comment by hermitgreen** [comment]
> Can you try to upgrade the version of k8s? 1.16 is a long time ago version

Upgrade k8s to 1.20.10 solved this problem
