### ISSUE TITLE
Add `volcano` as minikube addons

### ISSUE THREAD

**Issue by Yikun** [volcano-sh/volcano#2128]
#### What would you like to be added:
minikube implements a local Kubernetes cluster on macOS, Linux, and Windows.
minikube addons is a marketplace for developers to share configurations for running services on minikube.

#### Why is this needed:

We could add `volcano` as a minikube addons to help user can install volcano conveniently.

https://github.com/kubernetes/minikube/tree/master/deploy/addons

**Comment by k82cn** [comment]
That's great idea!

**Comment by Yikun** [comment]
@k82cn Thanks, just share some ideas in here.

I currently haven't had enough time to see how this can be done, feel free to take over if anyone else is also interested.

**Comment by hwdef** [comment]
I will try this.

**Comment by lowang-bh** [comment]
/reopen

I think we can go on.

**Comment by hwdef** [comment]
> /reopen
> 
> I think we can go on.

You can check this PR.
https://github.com/kubernetes/minikube/pull/13876

**Comment by Rajdeep1311** [comment]
I want to learn and help. I am quite new but I would love to help
