### ISSUE TITLE
[code refine] duplicate Allocate, Pipeline, Evict function in session.go and statement.go

### ISSUE THREAD

**Issue by wpeng102** [volcano-sh/volcano#2131]
Both `session` and `statement` have Allocate, Pipeline, Evict functions. And the logic are almost same. The only different is statement introduce `operations` which support rollback.

The duplicate functions will make developer confuse and not easy to maintain.

![image](https://user-images.githubusercontent.com/10152842/160769602-b2a68f71-3a91-45ee-a5ea-dabee28a773b.png)

![image](https://user-images.githubusercontent.com/10152842/160769614-239d2fd4-f714-4ccf-aca4-431b97c6cc01.png)

![image](https://user-images.githubusercontent.com/10152842/160769628-1a397fb7-6bd5-415d-a5b5-6db9abf01638.png)

**Comment by k82cn** [comment]
It's better to use stmt in actions. Anyway, let's keep ssn for backward compatibility :)

**Comment by Thor-wl** [comment]
> > It's better to use stmt in actions. Anyway, let's keep ssn for backward compatibility :)
> 
> This also confused me when I read the code. By the way, could you explain the difference between these functions(Allocate, Pipeline, Evict) in statement and session? What's the purpose of this design?

`allocate` works to bind a pod to a node whose idle resource can satisfy the pod. `pipeline` works to bind a pod to a node whose idle resource **cannot** satisfy the pod immediately, but there are some pods which are releasing resource and exit in the node and the predictable idle resource can satisfy the pod. `evict` works to evcit some pods.

**Comment by HeGaoYuan** [comment]
@Thor-wl 
Thanks for your reply.

But what I mean is these two methods make me confuse (so are Pipeline and Evict in session and statement). What is the difference between them.

https://github.com/volcano-sh/volcano/blob/f4d3d44b0e69b56a6842d9e540519cef4cc53498/pkg/scheduler/framework/session.go#L283

https://github.com/volcano-sh/volcano/blob/f4d3d44b0e69b56a6842d9e540519cef4cc53498/pkg/scheduler/framework/statement.go#L228

**Comment by wpeng102** [comment]
> > It's better to use stmt in actions. Anyway, let's keep ssn for backward compatibility :)
> 
> This also confused me when I read the code. By the way, could you explain the difference between these functions(Allocate, Pipeline, Evict) in statement and session? What's the purpose of this design?

At the beginning, Allocate, Pipeline, Evict functions olny in `session.go`, call these function will take effect immediately. For a better performance and support decision rollback. We introduce `statement.go`. You can see the `statement` packaging a session and operations. 
https://github.com/volcano-sh/volcano/blob/f4d3d44b0e69b56a6842d9e540519cef4cc53498/pkg/scheduler/framework/statement.go#L47-L50

The `statement` allow scheduler put a decision into `operations` and when call `Commit()` to take effect. You can also call `Discard()` to rollback the above decision in some special situation.

**Comment by wpeng102** [comment]
Now, It's better to use stmt now and mark Allocate, Pipeline, Evict function in session as `deprecation`. Also need left these functions in  ssn for backward compatibility.

**Comment by HeGaoYuan** [comment]
@wpeng102 
Thanks for your explanation. I got it.
