### ISSUE TITLE
Can volcano job tasks support DAG execute?

### ISSUE THREAD

**Issue by hermitgreen** [volcano-sh/volcano#2135]
#### What would you like to be added:

Tasks can be executed in parallel if they related to upstream and upstream is success.

For example, mapping table A and table B in 2 parallel task(A and B has different schema), then reduce them in 1 task.

#### Why is this needed:

Save times if have adequate resources.

**Comment by william-wang** [comment]
Task dependency in job is supported in Volcano 1.5.  It seems suitable for your scenario.
https://github.com/volcano-sh/volcano/blob/master/docs/design/task-launch-order-within-job.md

**Comment by hermitgreen** [comment]
> Task dependency in job is supported in Volcano 1.5. It seems suitable for your scenario. https://github.com/volcano-sh/volcano/blob/master/docs/design/task-launch-order-within-job.md

Exactly what I wanted

**Comment by hermitgreen** [comment]
> Task dependency in job is supported in Volcano 1.5. It seems suitable for your scenario. https://github.com/volcano-sh/volcano/blob/master/docs/design/task-launch-order-within-job.md

Is launch order only support running state? I found
```
as long as one task becomes the specified state
```
https://github.com/volcano-sh/volcano/blob/6932ddc916eea89acce4cd99837d36b23b88d960/vendor/volcano.sh/apis/pkg/apis/batch/v1alpha1/job.go#L373
but I don't found key to specify state.

**Comment by hwdef** [comment]
Currently only supports `running` state.Other states may be supported in the future, such as the `complete` state or probe.
