### ISSUE TITLE
These codes look like redundant and useless

### ISSUE THREAD

**Issue by HeGaoYuan** [volcano-sh/volcano#2148]
These codes look like redundant and useless

https://github.com/volcano-sh/volcano/blob/ac3b31334b8b754ee2fd17af455cbeb92fde852e/pkg/scheduler/plugins/task-topology/manager.go#L55

https://github.com/volcano-sh/volcano/blob/ac3b31334b8b754ee2fd17af455cbeb92fde852e/pkg/scheduler/plugins/task-topology/manager.go#L219-L224

**Comment by jiangkaihua** [comment]
Yes, you may delete them. @HeGaoYuan
