### ISSUE TITLE
vcjob phase can get stuck in "Pending" or "Starting" even after all pods have completed

### ISSUE THREAD

**Issue by hapatrick** [volcano-sh/volcano#2160]
**What happened**:
In our system, we have repeatedly seen vcjobs get stuck in phase “Pending” or “Starting” and remain there even after all associated pods have completed successfully. From the Volcano controller logs, it seems Volcano fails to patch the vcjob’s status because the vcjob resource has unexpectedly been changed. In our system, these changes are being caused by an operator we wrote to monitor the status of vcjobs. Our operator uses the kopf framework (https://github.com/nolar/kopf). Kopf uses annotations on the Kubernetes resources it monitors to help it track changes to resources. 

Restarting the Volcano controller causes the phase of stuck vcjobs to be updated.

Sample of the Volcano controller log when this error occurs:
```
Starting to initiate Job <app/workflow-njd4q-job0>
W0406 18:52:54.638604       1 job_controller_actions.go:652] Ignore task 0 priority class : priorityclass.scheduling.k8s.io "" not found
I0406 18:52:54.638852       1 event.go:282] Event(v1.ObjectReference{Kind:"Job", Namespace:"app", Name:"workflow-njd4q-job0", UID:"aec8c14c-64e2-44a3-a928-e62217cafba5", APIVersion:"batch.volcano.sh/v1alpha1", ResourceVersion:"45929598", FieldPath:""}): type: 'Warning' reason: 'PodGroupPending' PodGroup app:workflow-njd4q-job0 unschedule,reason: 1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable
E0406 18:52:54.666228       1 job_controller_actions.go:434] Failed to update status of Job app/workflow-njd4q-job0: Operation cannot be fulfilled on jobs.batch.volcano.sh "workflow-njd4q-job0": the object has been modified; please apply your changes to the latest version and try again
I0406 18:52:54.666251       1 job_controller_actions.go:436] Finished Job <app/workflow-njd4q-job0> sync up, current version 0
W0406 18:52:54.666279       1 job_controller.go:342] Terminating Job <app/workflow-njd4q-job0> and releasing resources
I0406 18:52:54.666289       1 job_controller_actions.go:45] Killing Job <app/workflow-njd4q-job0>, current version 0
I0406 18:52:54.666330       1 job_controller_actions.go:113] Running duration is 5m16.666322492s
I0406 18:52:54.666383       1 event.go:282] Event(v1.ObjectReference{Kind:"Job", Namespace:"app", Name:"workflow-njd4q-job0", UID:"aec8c14c-64e2-44a3-a928-e62217cafba5", APIVersion:"batch.volcano.sh/v1alpha1", ResourceVersion:"45929598", FieldPath:""}): type: 'Normal' reason: 'ExecuteAction' Job failed on action SyncJob for retry limit reached
E0406 18:52:54.727051       1 job_controller_actions.go:130] Failed to update status of Job app/workflow-njd4q-job0: Operation cannot be fulfilled on jobs.batch.volcano.sh "workflow-njd4q-job0": the object has been modified; please apply your changes to the latest version and try again
I0406 18:52:54.727066       1 job_controller_actions.go:132] Finished Job <app/workflow-njd4q-job0> killing, current version 0
E0406 18:52:54.727077       1 job_controller.go:344] Failed to terminate Job<app/workflow-njd4q-job0>: Operation cannot be fulfilled on jobs.batch.volcano.sh "workflow-njd4q-job0": the object has been modified; please apply your changes to the latest version and try again
W0406 18:52:54.727084       1 job_controller.go:346] Dropping job<app/workflow-njd4q-job0> out of the queue: Operation cannot be fulfilled on jobs.batch.volcano.sh "workflow-njd4q-job0": the object has been modified; please apply your changes to the latest version and try again because max retries has reached
```

**What you expected to happen**:
I expected that if the Volcano controller fails to patch the status of the vcjob object because the resource version is out of date, it would fetch the latest version of the resource and try again.

I believe Volcano should be able to handle changes to annotations on vcjob resources made by third-party apps. In fact, the [Kubernetes API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata) anticipate that annotations *will* be used by third-party applications.

And in most cases Volcano does handle changes to annotations while a vcjob is running without any problem. It seems that the failure to update the phase only occurs when the annotation is added with very specific timing, indicating perhaps some kind of race condition.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately it is hard to reproduce because it seems to depend on specific timing. We are able to reproduce it *sometimes* by repeatedly creating a vcjob, then adding an annotation on that vcjob. This produces the error described above about 1-3 times per 100 attempts. Here is a Python script that we use to do this: https://github.com/hapatrick/volcano-bug

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.4.0 
- Kubernetes version (use `kubectl version`): 1.19.3 
- Cloud provider or hardware configuration: on-prem cluster 
- OS (e.g. from /etc/os-release): RHEL 7.6 
- Kernel (e.g. `uname -a`): 3.10.0-957.21.2.el7.x86_64 
- Install tools:
- Others:

Note: We’ve also tried this with Volcano 1.5.1 running in k3s v1.19.16+k3s1. We saw the same problem with that configuration.

**Comment by william-wang** [comment]
@hapatrick Thanks for reporting the issue and the Python script. We'll try to reproduce it firstly with the scripts.

**Comment by wpeng102** [comment]
@hapatrick you mean Kopf will update vcjob annotation right? And I want to confirm if you set `max-requeue-num` for volcano-controller command.

**Comment by hapatrick** [comment]
> 

@wpeng102 Yes, Kopf adds its own annotations to vcjob objects and updates them periodically.

We were not aware of the max-requeue-num option, so we're not using it. 

Thanks.

**Comment by hapatrick** [comment]
We have been able to install version 1.6.0 and tests show that this problem is indeed resolved.
