### ISSUE TITLE
Spark integration test always failed due to debian mirror connect failed

### ISSUE THREAD

**Issue by Yikun** [volcano-sh/volcano#2165]
Some error like:
```
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Connection timed out [IP: 199.232.46.132 80]
```

https://github.com/volcano-sh/volcano/runs/6003483623?check_suite_focus=true

**Comment by william-wang** [comment]
Should have a mirror, i also experienced this issue several times.
/assign @Yikun
