### ISSUE TITLE
If a vcjob with a task whose minAvailable = 0, the vcjob can not be scheduled

### ISSUE THREAD

**Issue by Megan96** [volcano-sh/volcano#2171]
**What happened**:
if the minAvailable of task in vcjob is 0 and then failed to create pod of task in cluster, the vcjob can not be scheduled.

**What you expected to happen**:
Even if the task whose minAvailable is 0 can't create pod, the vcjob can be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
create a vcjob with two task taskA and taskB
| task | replicas | minAvailable |
| --- | --- | --- |
| taskA | 1 | 1 |
| taskB | 0 | 0 |

there only one pending pod of taskA in cluster,  but it can't be scheduled to node.

I guess it is the problem of function [CheckTaskMinAvailable()](https://github.com/volcano-sh/volcano/blob/183a1781a83fb4b76260b754f294d89b057ad747/pkg/scheduler/api/job_info.go#L687)

In that situation,  ji.TaskMinAvailable = {taskA: 1, taskB: 0}, actual = {taskA: 1}
if there is no pod of taskB,  there is no key taskB in actual so that the job is invalid.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.5.1 
- Kubernetes version (use `kubectl version`): 1.20.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Thor-wl** [comment]
BTW, why set `minAvailable` to be `0`?

**Comment by Megan96** [comment]
> BTW, why set task B?
If the pod of taskB with replicas > 0 and minAvailable=0 can't be created,  the problem may still exist?
The example is to simulate a situation that the pod of task can't be created.
