### ISSUE TITLE
Migrate volcano-sh-bot to prow

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#218]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

It's better to migrate current volcano-sh-bot to prow for more features.

**Comment by asifdxtreme** [comment]
@shivramsrivastava

**Comment by shivramsrivastava** [comment]
Started working on this, will update soon.

I will replace the 'volcano-ci-bot' with the prow bot.
Prow needs an kuberenetes cluster to run, so i will set it up in the same machine where our volcano-bot is running.

**Comment by asifdxtreme** [comment]
@shivramsrivastava @k82cn we can re-use the k8s prow from test-infra, we don't need a new setup.....right?

**Comment by shivramsrivastava** [comment]
I don't think 'test-infra' will allow external repos to use their infra. If volcano was under sigs we could have used it. But not sure.

**Comment by k82cn** [comment]
@shivramsrivastava , thanks for the update.

@asifdxtreme , test-infra will not support volcano which is out of kuberentes for now; we have to setup a new one for volcano.

**Comment by thandayuthapani** [comment]
@k82cn We have enabled Prow Bot to volcano-sh/volcano now.  We will check it for a day or two, for any issue.  If any issue raises, we check and fix it.  If no issue comes, we will enable it for other repos also.

**Comment by k82cn** [comment]
that's great! thanks very much :)

**Comment by k82cn** [comment]
@asifdxtreme , please help to enable `need-rebase` label.

**Comment by k82cn** [comment]
and if build failed, volcano-sh-bot should append some info about that.

**Comment by asifdxtreme** [comment]
> @asifdxtreme , please help to enable `need-rebase` label.

@k82cn `need-rebase` label has been added now by @thandayuthapani and it's working fine now.
For CI failure I guess we need to write our own plugin for this, we are not able to find any opensource plugin to add labels in the PR's if CI fails

**Comment by k82cn** [comment]
please check how k8s does :)

**Comment by asifdxtreme** [comment]
> please check how k8s does :)

@k82cn If the CI job is a prow job then we can show that type of details, it might not be possible with Travis Jobs, should we move our test setup to prow?

**Comment by k82cn** [comment]
that's ok to me :)

**Comment by k82cn** [comment]
Some PRs have duplicated labels, refer to https://github.com/volcano-sh/scheduler/pulls

**Comment by asifdxtreme** [comment]
> Some PRs have duplicated labels, refer to https://github.com/volcano-sh/scheduler/pulls

@k82cn I just checked the `volcano/scheduler` labels list, there were two labels for `need-rebase` so both of them were getting added, I have removed one of it and it works fine now.

**Comment by k82cn** [comment]
do we support `/area` command, e.g. `/area scheduler`, `/area controller`

**Comment by k82cn** [comment]
and `/retest` command.

**Comment by asifdxtreme** [comment]
/area scheduler

Test

**Comment by thandayuthapani** [comment]
@k82cn If we need to migrate travis jobs to prow jobs, we need to enable plank component of prow, for which we need GCS bucket(Google Cloud Storage) to store logs for jobs.  So should I continue exploring it or stall this process?
![Screenshot from 2019-07-04 17-06-55](https://user-images.githubusercontent.com/34565833/60663909-2b3d0d00-9e7e-11e9-90d1-c0cd755033fe.png)

**Comment by asifdxtreme** [comment]
> do we support `/area` command, e.g. `/area scheduler`, `/area controller`

`/area` is supported by volcano-sh-bots, `/retest` won't work as our jobs are own travis, if we move our test jobs to prow then only `/retest` will work but to make this work we need to have GCS account to store the logs. @k82cn Should we spend time to move our test jobs to prow(it needs a GCS paid account to store the logs)

**Comment by asifdxtreme** [comment]
@k82cn Can we go ahead and close this issue as `/retest` needs a lot of effort and resource to get it done as we need to migrate test jobs to prow which need GCS paid account.
