### ISSUE TITLE
MIG slices instead of entire GPUs 

### ISSUE THREAD

**Issue by kubernetian** [volcano-sh/volcano#2181]
#### What would you like to be added:

It would be cool if volcano would be able to handle MIG slices instead of entire GPUs. We are currently successfully using volcano in our ML setup to queue model training. We are trying to switch to GPU slices (MIG) instead of entire GPUs. But when we push vcjobs with slices in we get an error that "not enough resources are available". This error does not happen when we wrap it in a "regular" Kubernetes job. 

Would be great to hear some feedback wether this is already on the roadmap or not. 

#### Why is this needed:

Transitioning from whole GPUs to GPU slices, and at this point it looks like volcano can't handle that.

**Comment by k82cn** [comment]
That's great to have such a feature in Volcano :)
