### ISSUE TITLE
add example images for arm64

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#2183]
#### What would you like to be added:

add arm64 version of  `volcanosh/example-mpi:0.0.1` and `volcanosh/dist-mnist-tf-example:0.0.1`

#### Why is this needed:

Required when running e2e in arm64 environment

**Comment by shinytang6** [comment]
l believe the dockerfile of these example images are missing 🌜

**Comment by hwdef** [comment]
> l believe the dockerfile of these example images are missing last_quarter_moon_with_face

mpi's still exists, https://github.com/volcano-sh/volcano/blob/master/example/integrations/mpi/Dockerfile.

but the tensorflow, I can not find..We may need a new sample program =.=
