### ISSUE TITLE
what‘s the difference between pytorch/tfjob and vcjob？

### ISSUE THREAD

**Issue by YuxiangJohn** [volcano-sh/volcano#2187]
Volcano is new to me. I would like to use volcano as the scheduler for my ML training job. Could anyone explain the difference between pytorchjob/tfjob and vcjob? The pytorchjob/tfjob generated by kubeflow/training-operator can be scheduled directly by volcano，so are there any implicit conversion from pytorchjob/tfjob to vcjob? Thank you~

**Comment by zhuyaguang** [comment]
+1

**Comment by Thor-wl** [comment]
PyTorch job/TF job is bind to specified computing platforms. If users want to run them with K8s, they have to work with operators. Volcano job is an abstract CRD which is nothing to do with specified platforms and works with K8s locally.

**Comment by YuxiangJohn** [comment]
> PyTorch job/TF job is bind to specified computing platforms. If users want to run them with K8s, they have to work with operators. Volcano job is an abstract CRD which is nothing to do with specified platforms and works with K8s locally.

Thank you, very clear! The vcjob is a kind of CRD maintained by volcano‘s operator. And TF/Pytorch job is another kind of CRD maintained by kubeflow training-operator, deal with TF/pytorch env and GPU resource, and turn on volcano as the prior scheduler if needed.
