### ISSUE TITLE
【summer2022】Volcano Tech Docs Supplyment and Update

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2188]
In order to make Volcano easy to use and understand, you task is to improve reading materials. The details are as follows:

- [ ] Add more introductions and user guidances about **volcano job API** including lifecycle management, job plugins and so on.
- [ ] Add more introductions and user guidances about **queue API** including resource division, quota management ans so on.
- [ ] Add more introductions and user guidances about **poggroup API** including basic abilities and how to work with operators.
- [ ] Add more introductions and user guidances about **Device Plugin**. 
- [ ] Provide a list of Volcano Rest API and SDK.
- [ ] Provide a list of Volcano key features and user guidances.
- [ ] Upload the docs mentioned above to  github repository and official website both in Chinese and English.

Notes:
* This issue is set for Summer2022. The Summer2022 official website: https://summer-ospp.ac.cn/.
* Anyone who satisfies the requirement of the activity can submit application for the issue you are interested in. Please remind that the activity is only for college and graduate students. More details please refer to https://summer-ospp.ac.cn/help/student/
* The schedule of the activity refers to https://summer-ospp.ac.cn/help/timeline/

**Comment by william-wang** [comment]
Wonderful activity ;) 
Let's track this items by sub-tasks.

**Comment by Skyler-wy** [comment]
I'm really interested in the project of Volcano Tech Docs Supplyment and Update,so i hope i can have the opportunity to participate in the project research and do it perfectly.Thank you!

**Comment by Thor-wl** [comment]
> I'm really interested in the project of Volcano Tech Docs Supplyment and Update,so i hope i can have the opportunity to participate in the project research and do it perfectly.Thank you!

Great! Please follow the schedule of the activity and submit your application in time. Thanks!
