### ISSUE TITLE
【summer2022】Volcano Installation and Deployment

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2189]
In order to make Volcano easy to use and understand, you task is to improve reading materials. The details are as follows:

- [ ] Update the helm package and make it robust.
- [ ] Add bash scripts of installation and deployment for users to make it easy to install, deployment and update. Notice that you should make sure that the script can meet different environments and clean up all the generated resources.
- [ ] Provide user guidances.

Notes:
* This issue is set for Summer2022. The Summer2022 official website: https://summer-ospp.ac.cn/.
* Anyone who satisfies the requirement of the activity can submit application for the issue you are interested in. Please remind that the activity is only for college and graduate students. More details please refer to https://summer-ospp.ac.cn/help/student/
* The schedule of the activity refers to https://summer-ospp.ac.cn/help/timeline/

**Comment by snow-315** [comment]
I am very interested in this volcano project and hope to get the opportunity to participate in this project. I'll try my best to do it.

**Comment by Thor-wl** [comment]
> I am very interested in this volcano project and hope to get the opportunity to participate in this project. I'll try my best to do it.

Great! Please follow the schedule of the activity and submit your application in time. Thanks!

**Comment by Aju100** [comment]
@Thor-wl Hi I am interested to be part of the program and contributions.
