### ISSUE TITLE
【summer2022】Volcano Function Enhancement

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2190]
Currently, there are some known bugs and stopped feature enhancement PRs in the Volcano community. Your task is to participate as much as possible in the community to help resolve these bugs and continue these stopped features.

Work includes but is not limited to:
* code optimization
* document improvement
* bug fix
* feature implementation
* code review
* …

Tips:
* You can refer to the following links for potential tasks, we also welcome new ideas!
    * https://github.com/volcano-sh/volcano/issues?q=is:open+is:issue+label:kind/bug
    * https://github.com/volcano-sh/volcano/issues?q=is:open+is:issue+label:kind/feature
* The evaluation dimensions of this task are mainly the number of PRs accepted and community participation.

**Comment by shinytang6** [comment]
> The results for this summer 2022 are as below:
> 
> 1. Support GPU Numbers Predicates  [Add GPU Numbers Predicates #1692](https://github.com/volcano-sh/volcano/pull/1692)
> 2. Support GPU number [volcano-sh devices PR 15](https://github.com/volcano-sh/devices/pull/15)
> 3. Document enhancement [volcano-sh devices PR 27](https://github.com/volcano-sh/devices/pull/27)
> 4. Support config GPU memory factor [volcano-sh devices PR 28](https://github.com/volcano-sh/devices/pull/28)

Good job. Thanks for the contributions!
