### ISSUE TITLE
k8s cluster totally not work after helm uninstall volcano

### ISSUE THREAD

**Issue by pengyuan** [volcano-sh/volcano#2191]
**What happened**:
**k8s cluster totally not work after helm uninstall volcano**

when helm install any other charts, then error occurs.

kubectl get events -w -n volcano

Error creating: Internal error occurred: failed calling webhook "mutatepod.volcano.sh": Post "https://volcano-admission-service.volcano.svc:443/pods/mutate?timeout=10s": service "volcano-admission-service" not found

**What you expected to happen**:

k8s cluster should work as before.

**How to reproduce it (as minimally and precisely as possible)**:

(helm version: 1.5.1)
helm upgrade --install volcano ./volcano -f custom.yaml --namespace volcano

helm uninstall volcano -n volcano

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 0.1
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by pengyuan** [comment]
#2079 
#2102 

it seems this problem does not resolved.

**Comment by hwdef** [comment]
Yes, you have to clean webhook manually.

**Comment by jiangxiaobin96** [comment]
try https://githubhot.com/repo/volcano-sh/volcano/issues/2079

**Comment by hwdef** [comment]
fix in https://github.com/volcano-sh/volcano/pull/2346
/close
