### ISSUE TITLE
How to run a custom tensorflow/pytorch/horovod train demo?

### ISSUE THREAD

**Issue by kongjibai** [volcano-sh/volcano#2192]
As the title, how to run a **custom** **tensorflow**/**pytorch**/**horovod** train demo with Volcano?

**Comment by hwdef** [comment]
please check 

https://github.com/volcano-sh/volcano/tree/master/example/integrations

**Comment by kongjibai** [comment]
> please check
> 
> https://github.com/volcano-sh/volcano/tree/master/example/integrations

thx, but it only have argo, mpi, mxnet, paddlepaddle and tensorflow, do not have **_pytorch_** and _horovod_.

**Comment by hwdef** [comment]
@qiankunli 

Do you have samples of pytorch and horovod?
