### ISSUE TITLE
Add job record cache between different session, convenient scheduling plug-in extension

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#2193]
#### What would you like to be added:

Can volcano-scheduler add job record cache between different session, convenient scheduling plug-in extension. Custom caching position can be in api.JobInfo.
#### Why is this needed:

Like NodeInfo struct in volcano-scheduler, it has a cache between different session. So that volcano-scheduler plugin can provide  customized modification。

```
type NodeInfo struct {
	Name string
	Node *v1.Node

	...

	// Used to store custom information
	Others     map[string]interface{}
	GPUDevices map[int]*GPUDevice
        ...
}
```

**Comment by k82cn** [comment]
It's handle by plugin to have a global variables :)
