### ISSUE TITLE
Getting 404 during `helm repo add volcano https://volcano-sh.github.io/charts`

### ISSUE THREAD

**Issue by jsolbrig** [volcano-sh/volcano#2206]
**What happened**:
When I run `helm repo add volcano https://volcano-sh.github.io/charts` I get a 404. Going to https://volcano.sh.github.io in a browser also gives a 404.

**What you expected to happen**:
The repo should get added correctly to helm.

**How to reproduce it (as minimally and precisely as possible)**:
Just run `helm repo add volcano https://volcano-sh.github.io/charts`

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jsolbrig** [comment]
Ah, I didn't realize that the Helm Chart is a bit under-developed. So, if the 404 is intentional, feel free to delete this issue.

Are there plans to flesh out the Helm Chart more? It looks like as a part of the Summer 2022 work? Are there ways that I can help with the development for this?

**Comment by Thor-wl** [comment]
> Ah, I didn't realize that the Helm Chart is a bit under-developed. So, if the 404 is intentional, feel free to delete this issue.
> 
> Are there plans to flesh out the Helm Chart more? It looks like as a part of the Summer 2022 work? Are there ways that I can help with the development for this?

Yes, it has been listed as an item of Summer 2022. Any work about installation and deployment is great!

**Comment by jsolbrig** [comment]
I'm starting to put together a helm chart for Volcano for my own purposes. Before I go too far, I have a few questions so that, maybe, my work can be useful:
- Would it be helpful if I work on putting together a more useful helm chart or is that already being worked on by others behind the scenes?
- Have any decisions been made about how a helm chart for Volcano should be structured?
- Are there any standards that Volcano would like to follow for a helm chart?
- Is there somewhere that I can get more rapid feedback than just submitting issues?

**Comment by batazor** [comment]
Is there any news?

It would be cool to be able to install an application from the helm repository

**Comment by jsolbrig** [comment]
I've got a helm chart that I put together for my own purposes. It's not great but it works. It doesn't provide configuration for everything that it could, but it's a starting point that I plan to keep developing. It's also not documented at all yet. You can find it here if you're interested: https://github.com/jsolbrig/volcano_chart 

I give no guarantees on how it will work for you. If you find problems, please let me know. You might want to try the 

I based some of the chart's conventions off of the kube-prometheus-stack chart.

@Thor-wl Do you think that what I've put together would be of interested to the Volcano project, or is there something in the works as part of Summer 2022? I'd be happy to keep working on this chart, hear feedback, and offer to maintain it.

**Comment by Thor-wl** [comment]
> I'm starting to put together a helm chart for Volcano for my own purposes. Before I go too far, I have a few questions so that, maybe, my work can be useful:
> 
> * Would it be helpful if I work on putting together a more useful helm chart or is that already being worked on by others behind the scenes?
I really appreciate your work if you can put together a helm chart for Volcano. Although it is a work item for summer 2022, this work is also meaningful.
> * Have any decisions been made about how a helm chart for Volcano should be structured?
Well, not really. 
> * Are there any standards that Volcano would like to follow for a helm chart?
Not yet now. 
> * Is there somewhere that I can get more rapid feedback than just submitting issues?
Perhaps you can make communition with approvers or members and give a kindly ping. In most cases, we will deal with the issues ASAP.

**Comment by Thor-wl** [comment]
> I've got a helm chart that I put together for my own purposes. It's not great but it works. It doesn't provide configuration for everything that it could, but it's a starting point that I plan to keep developing. It's also not documented at all yet. You can find it here if you're interested: https://github.com/jsolbrig/volcano_chart
> 
> I give no guarantees on how it will work for you. If you find problems, please let me know. You might want to try the
> 
> I based some of the chart's conventions off of the kube-prometheus-stack chart.
> 
> @Thor-wl Do you think that what I've put together would be of interested to the Volcano project, or is there something in the works as part of Summer 2022? I'd be happy to keep working on this chart, hear feedback, and offer to maintain it.

@jsolbrig Hey, please feel free to continue to do this work. I've reviewed the chart you provided above and it is really great.

**Comment by batazor** [comment]
up

**Comment by JessieAMorris** [comment]
Would still love this. Needing to install from the repository makes installing this via CI/CD a bit painful.

**Comment by wangyang0616** [comment]
Retain the current issue.
/remove-lifecycle stale

**Comment by lowang-bh** [comment]
This issue can be closed now? @wangyang0616

**Comment by wangyang0616** [comment]
Yes, the current problem has been solved. For update information on installing Volcano through helm, please refer to: [helm-charts](https://github.com/volcano-sh/helm-charts)
