### ISSUE TITLE
【community bridge 2022 Q2】Volcano scalebility enhancement

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2211]
The project is to make sure volcano works better in AI/HPC scenarios.

Your tasks may include:
1. enhance the integration of volcano with third-party operators by customizing the volcano job plugin.
2. enhance volcano GPU support, may include some work of volcano device plugin.

ref:
1. https://github.com/volcano-sh/volcano/pull/1806
2. https://github.com/volcano-sh/volcano/issues/2111
3. https://github.com/volcano-sh/devices

**Comment by anutosh491** [comment]
Hello @shinytang6  , hope you're doing well , this is Anutosh here from India . I'm an open source enthusiast and I'm currently involved with communities based on numerical and symbolic computations/algorithms in math and physics like numpy, sympy, networkx.

I am keen to take part in the LFX Mentorship program for the summer term and project interests me. But being new to the project , I would be glad if you could share any relevant resources/links I should be going through for getting to know the project and the library better . Thank you !

**Comment by shinytang6** [comment]
> Hello @shinytang6 , hope you're doing well , this is Anutosh here from India . I'm an open source enthusiast and I'm currently involved with communities based on numerical and symbolic computations/algorithms in math and physics like numpy, sympy, networkx.
> 
> I am keen to take part in the LFX Mentorship program for the summer term and project interests me. But being new to the project , I would be glad if you could suggest any relevant resources/links I should be going through as a beginner for getting to know the project and the library better . Thank you !

Sorry for the late reply, really appreciate for your interest. I recommend browsing the official website https://volcano.sh/ and design documentations https://github.com/volcano-sh/volcano/tree/master/docs first to have a basic understanding of volcano :)

**Comment by kernelpanic77** [comment]
Hello @shinytang6! 
I am Ishan from India. I am currently working computer vision based Medical-AI project. I found the volcano.sh project is extremely interesting and wanted to contribute to Scalability Enhancement Project as Part of LFX for Summer 2022. I am currently going through the [volcano documentation](https://github.com/volcano-sh/volcano/tree/master/docs) to get a better understanding of the codebase. The LFX website shows that mentee applications for this mentorship are still open. Please let me know if I can still submit my application for the project.

Looking forward to contribute to Volcano.

**Comment by shinytang6** [comment]
> Hello @shinytang6! I am Ishan from India. I am currently working in the computer vision domain, particularly in Medical-AI. Along with Distributed Systems, I also have knowledge of machine learning. I found the Volcano project extremely interesting and wanted to contribute to Scalability Enhancement Project as Part of LFX for Summer 2022. I am currently going through the [volcano documentation](https://github.com/volcano-sh/volcano/tree/master/docs) to get a better understanding of the codebase. The LFX website shows that mentee applications for this mentorship are still open. Please let me know if I can still submit my application for the project.
> 
> Looking forward to contributing to Volcano.

Thanks for your interest! yes it's still in the application period, you can follow the process of community bridge and apply for it.

**Comment by kernelpanic77** [comment]
@shinytang6 sorry for my delayed response. From what I understand about the first part of the project, we need to create plugins for deep learning frameworks to reduce the complications of setting the configurations for a machine learning task manually. More importantly, task-level scheduling would be an interesting feature for the volcano project. That sound's good. However, I understood the GPU enhancement project properly. It was also a bit difficult to understand the design documentation properly, I did not understand which part's were relevant. 

But I hope to gain more knowledge from your mentorship and look forward to contributing. 
Is there any slack workspace for the volcano? The one I saw required me to sign in.

I will submit my cover letter and resume by tonight.

**Comment by anutosh491** [comment]
> Please let me know if I can still submit my application for the project.

Today is the last day to apply , applications close tomorrow morning as per the website. Hope that helps !

**Comment by peiniliu** [comment]
Hi, 
This is Peini from the Barcelona supercomputing center. I had some experience on Volcano project, and I submitted PRs to improve the GPU number predicates/GPU device plugins. If there is a GPU machine that can be accessed to work during the summer vacation, I would really like to work on the feature. :)
Best,
Peini
