### ISSUE TITLE
redundant  webhook after uninstall

### ISSUE THREAD

**Issue by zirain** [volcano-sh/volcano#2219]
**What happened**:
```console
# helm uninstall volcano -nvolcano-system
release "volcano" uninstalled
# kubectl get mutatingwebhookconfiguration
NAME                                         WEBHOOKS   AGE
istio-revision-tag-canary                    2          11d
istio-revision-tag-default                   4          41h
istio-sidecar-injector-1-13-2                2          11d
istio-sidecar-injector-1-13-3                2          41h
volcano-admission-service-jobs-mutate        1          5m19s
volcano-admission-service-podgroups-mutate   1          5m19s
volcano-admission-service-pods-mutate        1          5m19s
volcano-admission-service-queues-mutate      1          5m19s
```

**What you expected to happen**:

there's no redundant webhook after volcano uninstalled.

**How to reproduce it (as minimally and precisely as possible)**:
1. install volcano via helm
2. uninstall volcano helm release
3. run `kubectl  get mutatingwebhookconfiguration | grep volcano`

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by shinytang6** [comment]
dup with https://github.com/volcano-sh/volcano/issues/2102

**Comment by zirain** [comment]
closed as dup
