### ISSUE TITLE
Enable all e2e cases of volcano-sh/scheduler

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#222]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**:

We disabled some e2e cases of volcano-sh/scheduler because of failure, we should get them fixed and enable those e2e cases.

**Comment by asifdxtreme** [comment]
cc @Rajadeepan

**Comment by Rajadeepan** [comment]
@k82cn  The two test cases which was skipped has been enabled by this PR https://github.com/volcano-sh/scheduler/pull/28
![image](https://user-images.githubusercontent.com/13465886/59579933-c4cd9600-90ec-11e9-8c17-80cd61d64f66.png).
The one which is skipped is the performance test case.
can this issue be closed ?
