### ISSUE TITLE
Volcano does not have release package

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#2223]
When i want to install volcano, first i need to download the code, then I can  use helm install. I can not find a chart release package. 

BTW: for release 1.1.0, it does have a release package https://github.com/volcano-sh/volcano/releases/download/v1.1.0/volcano-v1.1.0-linux-gnu.tar.gz

**Comment by k82cn** [comment]
please use docker images :)

**Comment by hzxuzhonghu** [comment]
We want to install with helm

**Comment by hzxuzhonghu** [comment]
>please use docker images :)

not sure i understand, does volcano support install with docker?


Not sure i understand

**Comment by wpeng102** [comment]
Same as https://github.com/volcano-sh/volcano/issues/1945. This is a reasonable requirement from customer. /cc @Thor-wl
