### ISSUE TITLE
GPU enhancements

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#2233]
There're several enhancements for Volcano to do for GPU scenarios, let's do more investigation on them:

- [ ] GPU sharing: https://github.com/NVIDIA/open-gpu-kernel-modules
- [ ] GPU & NUMA: https://docs.open-mpi.org/en/v5.0.x/networking/cuda.html#numa-node-issues
- [ ] vgpu

**Comment by hwdef** [comment]
Expect volcano to be more powerful in gpu and have the ability to control the source code about gpu sharing
