### ISSUE TITLE
Mutatingwebhook respect namespacing

### ISSUE THREAD

**Issue by Asciotti** [volcano-sh/volcano#2247]
Following up formally for a request for having the mutatingwebhooks to respect namespacing across a cluster. My team operates in mult-tenant clusters (each team with designated namespaces, sharing resources). We are setting up a system from ML/DS to perform multi-node training/experimentation; however, we do not want to interfere with other users/teams on these clusters.

Additionally, if you could add the webhook creation to the yaml that would be beneficial since there are numerous bugs out about `kubectl deletel ...` not cleaning up these webhooks since they arent in the config.

> Here are some improvements I need about webhook:
> 1. Instead of using code to generate webhook, it is written in yaml and deployed with yaml.This makes it easy to change > the scope of application of the webhook and to ignore some pods
> 2. If possible, narrow the scope of application of webhook, currently intercepting all pods, once volcano has a problem, > the entire cluster cannot create pods

_Originally posted by @hwdef in https://github.com/volcano-sh/volcano/issues/2079#issuecomment-1085573012_

**Comment by Asciotti** [comment]
Bump please!

**Comment by hwdef** [comment]
https://github.com/volcano-sh/volcano/pull/2251

Is this what you want?

**Comment by Asciotti** [comment]
It looks close but I think having an exclusion list versus an inclusion list might cause issues with what we have setup. We only need 1-2 namespaces allowed, so we would have to ignore all others. That is manageable. However, if a new namespace is created we wouldn't be able to quickly detect that and automatically add it to the exclusion list.

If we had an inclusion list or a dynamic wild-card specifiable exclusion list that might be more workable. I still appreciate this modification, I can think of how to work around it at least. 

I can remake this ticket or modify it to request this feature if desired - lmk.

**Comment by hwdef** [comment]
@Asciotti 
That sounds great! Can you submit a design document first, including how to use it.

**Comment by hwdef** [comment]
After https://github.com/volcano-sh/volcano/pull/2346 merge, this function can be achieved by directly modifying the yaml.
