### ISSUE TITLE
Added/Updated license for copied scripts.

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#228]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**:

Some license is in-correct to me, please help to update them:

1. https://github.com/volcano-sh/volcano/blob/master/hack/update-gencode.sh , AFAIK, we re-used this script from k8s, we should keep k8s's copyright.
1. https://github.com/volcano-sh/volcano/blob/master/hack/verify-gofmt.sh , https://github.com/volcano-sh/volcano/blob/master/hack/verify-golint.sh : we should add k8s license to those two scripts.

**Comment by asifdxtreme** [comment]
cc @Rajadeepan
