### ISSUE TITLE
Queue metric is incorrect when job is completed or deleted

### ISSUE THREAD

**Issue by bengamine** [volcano-sh/volcano#2280]
**What happened**:
All the queue related metrics (such as queue_share, queue_allocated_milli_cpu, queue_pod_group_running_count** etc.)is not updated after job is completed or be deleted. 

**What you expected to happen**:
The metrics should be updated accordingly.

**How to reproduce it (as minimally and precisely as possible)**:
case 1:
a. create a queue and a job, after the all the pod in running state, check the queue metrics is correct.
b. delete the job, and check the queue metrics, you will find the metrics is not changed.

case 2: 
a. create a queue and a job, after the all the pod in running state, check the queue metrics is correct.
b. waiting for job finished(for example: do sleep 60s for each pod)
c. check the queue metrics, you will find the metrics is not changed.

**Potential reason**:
The queue metric update is triggered in proportion plugin only when there are jobs need to be scheduled, in other scenario the metrics will not be refreshed.

**Environment**:
- Volcano Version:
1.5 and above (master branch)
- Kubernetes version (use `kubectl version`):
v1.23.5

**Comment by SunMinghui19** [comment]
![image](https://user-images.githubusercontent.com/55644074/177664561-e7c00168-8d88-4d24-a269-f41190e45375.png)
