### ISSUE TITLE
Pod in "OutOfcpu" status issue can be reproduced

### ISSUE THREAD

**Issue by bengamine** [volcano-sh/volcano#2282]
**What happened**:
The Pod in "OutOfcpu" status can be reproduced in a very simple test scenario。 

**How to reproduce it (as minimally and precisely as possible)**:
1.All jobs are selected to one node
2.create a queue
3.create job2 with minAvailable=1 and replicas=4, all the pods can be scheduled to running status
4.create job1 with minAvailable=1 and replicas=8, because of cpu resource exhaust, only 2 pods are scheduled to running status.
5.after 60s, all the pods in job1 are successed. The cpu is free for job1, 4 pods in job1 are expect to schedule to be in running status, but they are changed to "OutOfcpu" status
6.in a while, the last 2 pods are scheduled to running status.

[root@terryjzhang tmp]# kubectl get pod -n prajna                   
NAME                  READY   STATUS      RESTARTS   AGE
vc-low-job1-nginx-0   0/1     Completed   0          4d17h
vc-low-job1-nginx-1   0/1     Completed   0          4d17h
vc-low-job1-nginx-2   0/1     OutOfcpu    0          4d17h
vc-low-job1-nginx-3   0/1     OutOfcpu    0          4d17h
vc-low-job1-nginx-4   0/1     Completed   0          4d17h
vc-low-job1-nginx-5   0/1     Completed   0          4d17h
vc-low-job1-nginx-6   0/1     OutOfcpu    0          4d17h
vc-low-job1-nginx-7   0/1     OutOfcpu    0          4d17h
vc-low-job2-nginx-0   0/1     Completed   0          4d17h
vc-low-job2-nginx-1   0/1     Completed   0          4d17h
vc-low-job2-nginx-2   0/1     Completed   0          4d17h
vc-low-job2-nginx-3   0/1     Completed   0          4d17h

**Environment**:
-Volcano Version:
1.5 and above (master branch)
-Kubernetes version (use kubectl version):
v1.23.5

**Comment by bengamine** [comment]
is anyone can give a help?

**Comment by william-wang** [comment]
@bengamine Sorry for the delay. We'll have a look at this week.

**Comment by waiterQ** [comment]
@bengamine if node

**Comment by waiterQ** [comment]
@bengamine  If the nodeName is set, the scheduler ignores the Pod and the kubelet on the named node tries to place the Pod on that node. If you'd like OutOfcpu pods be pending, nodeSelector or affinity rules are better choose.
ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
hope it helpful

**Comment by bengamine** [comment]
> @bengamine If the nodeName is set, the scheduler ignores the Pod and the kubelet on the named node tries to place the Pod on that node. If you'd like OutOfcpu pods be pending, nodeSelector or affinity rules are better choose.
> ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
> hope it helpful

I didn't set the nodeName to the job, it's volcano scheduler's bahavior to schedule the pod to the node. As we have only one node in the cluster, so it's very easy to reproduce the problem.

**Comment by waiterQ** [comment]
@bengamine i have a new cluster(k8_ver:v1.23.4, volcano:v1.5.1) only one node(cpu:8) from steps below, sorry to tell i cant reproduce the problem. i believe it occur pod-in-OutOfcpu at your cluster, OutOfcpu would happen between volcano and kubelet had different allocated resource, paste logs of both when OutOfcpu happen will help locate problem more

1. create a queue queue-a 
---
    apiVersion: scheduling.volcano.sh/v1beta1
    kind: Queue
    metadata:
      name: queue-a
    spec:
      reclaimable: true
---
2. create job2
---
    apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
    metadata:
      name: job2
    spec:
      schedulerName: volcano
      queue: queue-a
      minAvailable: 1
      tasks:
        - replicas: 4
          name: "nginx"
          template:
            spec:
              containers:
                - image: nginx:1.23
                  command: ["/bin/sh", "-c", "sleep 120"]
                  imagePullPolicy: IfNotPresent
                  name: nginx
                  resources:
                    requests:
                      cpu: "1"
              restartPolicy: OnFailure
---
3. create job1
---
    apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
    metadata:
      name: job1
    spec:
      schedulerName: volcano
      queue: queue-a
      minAvailable: 1
      tasks:
        - replicas: 8
          name: "nginx"
          template:
            spec:
              containers:
                - image: nginx:1.23
                  command: ["/bin/sh", "-c", "sleep 60"]
                  imagePullPolicy: IfNotPresent
                  name: nginx
                  resources:
                    requests:
                      cpu: "1"
              restartPolicy: OnFailure
---
4. after 60s, kubectl get po
---
        $ kubectl get po
        NAME           READY   STATUS      RESTARTS   AGE
        job1-nginx-0   0/1     Completed   0          74s
        job1-nginx-1   0/1     Completed   0          74s
        job1-nginx-2   1/1     Running     0          74s
        job1-nginx-3   1/1     Running     0          74s
        job1-nginx-4   0/1     Pending     0          74s
        job1-nginx-5   0/1     Pending     0          74s
        job1-nginx-6   0/1     Pending     0          74s
        job1-nginx-7   0/1     Pending     0          74s
        job2-nginx-0   1/1     Running     0          83s
        job2-nginx-1   1/1     Running     0          83s
        job2-nginx-2   1/1     Running     0          83s
        job2-nginx-3   1/1     Running     0          83s
---
