### ISSUE TITLE
Volcano's webhooks should be more respectful of other namespaces and RBAC permissions should be reduced

### ISSUE THREAD

**Issue by jsolbrig** [volcano-sh/volcano#2286]
#### What would you like to be added:

I would like to see Volcano default to managing an explicit list of namespaces rather than managing all namespaces by default. To me, this behavior is both unexpected and problematic. It blocks deployment of other applications. It also leads to the need for less secure RBAC configuration where Volcano can manage all Pods in the cluster.

Currently Volcano's webhooks are able to ignore specific namespaces by using the `--ignored-namespaces` flag when calling `vc-webhook-manager`. That is helpful, but I think that Volcano should be more restrictive in terms of what it manages. Rather than needing to list which namespaces to ignore, it should be possible to list the namespaces that should be managed.

I propose that there should be a `--managed-namespaces` flag. It should operate the same as the `--ignored-namespaces` flag, but instead of using the `NotIn` operator in the namespaceSelector it should use `In`. `--managed-namespaces` should be mutually exclusive with `--ignored-namespaces`.

#### Questions
Why does Volcano manage all namespaces by default?
- I'm sure there is a good reason for this, but is it something that can be addressed?

Would there be side effects of this in the Volcano system? 
- If so, can they be addressed? 
- For example, would this allow creating VCJobs outside of managed namespaces (probably not good)?
- Could this be protected against using additional webhooks to block creation of VCJobs in unmanaged namespaces?

#### Why is this needed:
Generally, I think that it is a bad idea to take over the entire kubernetes cluster by default. People use clusters for many purposes and won't expect Volcano to block deployment of other applications. Currently, once Volcano is deployed, it must be patched before a new application is deployed in a new namespace.

This would also allow more restrictive RBAC for Volcano. It would allow reducing the scope of the ClusterRoles to only manage Pods in the managed namespaces rather than requiring cluster-wide access to all Pods. This would be significantly more secure.

**Comment by hwdef** [comment]
`--managed-namespaces` sound reasonable. Would you like to add this feature?

**Comment by jsolbrig** [comment]
Sure, I'll give it a shot.

**Comment by Sharathmk99** [comment]
@jsolbrig is it better to read from namespace label to either ignore the namespace or not. Like how istio does, they use label to ignore the namespace

**Comment by jsolbrig** [comment]
@Sharathmk99 That could work well. I was just grabbing on to how the current functionality works with `--ignore-namespaces`. Personally, I'd prefer an opt-in system rather than opt-out. Maybe add a `volcano.sh/monitored: "true"` to namespaces where Volcano's webhooks should take effect?

As @hwdef pointed out in a [PR](https://github.com/volcano-sh/volcano/pull/2290) that I put together, I didn't see the full scope of the problem when submitting this issue or the PR. 

When ignoring/monitoring specific namespaces, VCJobs can still get submitted to unmonitored namespaces. They do run, but they don't get handled by the webhooks. One option to handle this might be to block submission of VCJobs to unmonitored namespaces.

Thoughts?

**Comment by jsolbrig** [comment]
@Sharathmk99 Also, as mentioned in the [PR](https://github.com/volcano-sh/volcano/pull/2290) after realizing that the PR is a mess, I do think that I have a solution that can easily achieve my basic goal for now.

The most basic goal is to just get Volcano to quit blocking admission for resources from other applications. VCJobs add specific labels to the Pods that they create. I've updated `cmd/webhook-manager/app/util.go` to generate webhooks that contain an `objectSelector` like below. This seems to work to allow non-Volcano Pods to be created.

```yaml
- apiVersion: admissionregistration.k8s.io/v1
  kind: MutatingWebhookConfiguration
  metadata:
    name: volcano-admission-pods-mutate
  webhooks:
  - admissionReviewVersions:
    objectSelector:
      matchExpressions:
      - {key: volcano.sh/job-name, operator: Exists}
```

Should I submit an issue and a PR for the above change?

This doesn't block VCJobs from being created in ignored or unmanaged namespaces, though. VCJobs can still get created in the `volcano-system` namespace even if it is "ignored".

**Comment by Sharathmk99** [comment]
> @Sharathmk99 Also, as mentioned in the [PR](https://github.com/volcano-sh/volcano/pull/2290) after realizing that the PR is a mess, I do think that I have a solution that can easily achieve my basic goal for now.
> 
> The most basic goal is to just get Volcano to quit blocking admission for resources from other applications. VCJobs add specific labels to the Pods that they create. I've updated `cmd/webhook-manager/app/util.go` to generate webhooks that contain an `objectSelector` like below. This seems to work to allow non-Volcano Pods to be created.
> 
> ```yaml
> - apiVersion: admissionregistration.k8s.io/v1
>   kind: MutatingWebhookConfiguration
>   metadata:
>     name: volcano-admission-pods-mutate
>   webhooks:
>   - admissionReviewVersions:
>     objectSelector:
>       matchExpressions:
>       - {key: volcano.sh/job-name, operator: Exists}
> ```
> 
> Should I submit an issue and a PR for the above change?
> 
> This doesn't block VCJobs from being created in ignored or unmanaged namespaces, though. VCJobs can still get created in the `volcano-system` namespace even if it is "ignored".

If we don’t label vcjob, things will not work. It’s not backward compatible.

**Comment by jsolbrig** [comment]
@Sharathmk99 Has VCJob not been labeled in the past? It's currently labeled this way.
