### ISSUE TITLE
Remove Headless service

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#229]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we're using Headless service for task addressing; but it takes a really long time to get it ready. It's better to have a way to use IP directly to avoid DNS.

**Comment by TommyLike** [comment]
Is this saying we need to use static ip for our worker's pod instead of hostname?

**Comment by k82cn** [comment]
I don-t have solution right now :( , but I'd like to know what we can do for that.

**Comment by hzxuzhonghu** [comment]
Is there a reported issue?

**Comment by nicklhy** [comment]
Any updates here ?
Recently, I got endless restarts of some mpi model training jobs in a cluster with more than 300 GPUs. Can we use some tricks to wait for the DNS ready before launching the real model training job ?

**Comment by k82cn** [comment]
Do you know why "endless restarts"? One option in my mind is to add a script to check network before launching mpirun with timeout.

**Comment by nicklhy** [comment]
The exact reason has not been found yet. Do you have any recommendations for us to analyze the problem ?

By far we can launch our training scripts with 2, 4 and 10 worker nodes (8 GPU devices on each). But once we increase the number to 20 or 40, the jobs would stuck with the DNS problem. I can see they have been restarted more than 400 times in the past few days.

I searched the DNS problem with google and found this: [Racy conntrack and DNS lookup timeouts](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts). Is this linux kernel bug causing the DNS delay problem in volcano ?

PS. Our training scripts use MXNet+Horovod.

**Comment by hzxuzhonghu** [comment]
nope, it is caused by dns resolve latency. Simple fix is to detect if dns resolve is ok before launch the job.

From volcano point, the ideal way is to inject a init container, and do that detection without user interference.

**Comment by nicklhy** [comment]
@hzxuzhonghu  I see. To fix my current problem, I can use some bash commands like `nslookup` or `host` to check if dns resolve works fine.
And I guess I only need to do it on the master pod ? No need to add these commands in worker pods, right ?

**Comment by hzxuzhonghu** [comment]
Correct

**Comment by TommyLike** [comment]
how can the delay issue cause endless restart of pod?

**Comment by hzxuzhonghu** [comment]
The restart of pod is caused by the main process exit.  If k8s supports prestart hook, it is easy to do
