### ISSUE TITLE
should the logic of webhook-manager be separated into helm?

### ISSUE THREAD

**Issue by lucming** [volcano-sh/volcano#2300]
hi,just a little confused,i see some code about helm,why not create webhook through helm directly,and i see that we create webhook by running a job(webhook-manager).
in this way, if we install volcano by helm, "helm uninstall" cannot completely uninstall all resources volcano related. we have to delete the webhook separately.

**Comment by hwdef** [comment]
1. I don't quite understand why it's designed this way.
2. Webhooks deployed via helm could not be removed when helm uninstalled is being resolved. https://github.com/volcano-sh/volcano/pull/2203

**Comment by lucming** [comment]
> 2\. Webhooks deployed via helm could not be removed when helm uninstalled is being resolved. [fix(deploy): add helm pre delete hook to delete orphan resources #2203](https://github.com/volcano-sh/volcano/pull/2203)

this change can delete old webhooks when we do "helm install",but actually we want is delete all resources volcano related when we do "helm uninstall"

**Comment by hwdef** [comment]
well, You can comment below this pr to suggest changes.
But in fact, this does not solve the fundamental problem, because volcano deployed through `kubectl apply` will still have similar problems, and uninstalling the webhook is not clean.
So it's better to have a fundamental solution to the problem. This problem has been bothering us for a while.

**Comment by lucming** [comment]
okay,i will take care of this pr,I feel that the fundamental problems is that there is no uniformity in the installation of resources related to the volcano itself, some are created through yaml files and some are created through programs.can we split the logic of webhook creation from webhook-manager?

**Comment by hwdef** [comment]
@lucming 
I do not have the authority to make these decisions, please contact the maintainers in the community.

**Comment by lucming** [comment]
okay，thanks for your reply :)
