### ISSUE TITLE
How to get root cause of a job failure

### ISSUE THREAD

**Issue by Akiqqqqqqq** [volcano-sh/volcano#2306]
#### What would you like to be added:
We want a feature or solution that can tell us the root cause of a job failure more easily, either by logic inside the pod, or by outside factors like k8s or cluster network.

#### Why is this needed:
We're currently providing ML users vj to run their training tasks. We mainly provide mpi jobs whith classic policy of:

policies:
  - events
     - TaskCompleted
        action: CompleteJob
  - events:
     - PodFailed
        action: TerminateJob

However, often when a job fails, which obviously caused by one of the pods failing, and the ML users call us to help locate the cause of failure, we cannot tell the root cause immediately. We cannot tell whether the logic inside the pod fails the pod, or the pod itself failed due to OOM ,node goes down  or networking problem. And often what we do is by looking into pods log, and volcano job controller log, or Grafana. It has been troublesome. Is there any solution to this? 
For now all we came out is by adding a event record when a pod failed event trigger the job fails, so that we can tell which pod fails first.

**Comment by william-wang** [comment]
@qiankunli As you have been developing and maintaining the ML platform for your algorithm engineers. Are there any best practices from your side?
