### ISSUE TITLE
Whether the gang scheduling supports custom scheduling algorithms

### ISSUE THREAD

**Issue by qiuming520** [volcano-sh/volcano#2317]
Whether the scheduler supports custom scheduling algorithms？
such as CRD+Operator

**Comment by Thor-wl** [comment]
Volcano supports custom scheduling algorithms. Perhaps you can give more details about your requirements.

**Comment by qiuming520** [comment]
Thank you for reply. @Thor-wl 
Our team is working on the direction of the k8s cluster management platform, and the current direction is single-cluster scheduling and multi-cluster scheduling. Among them, the single-cluster scheduling component hopes that the scheduling algorithm can be customized in combination with the project scenario (GPU, spark), and the observability is strong. Other inconvenience to say.

**Comment by Thor-wl** [comment]
Got it. You can implement custom `actions` and `plugins` to define your algorithms, then configure them in the scheduler configuration. We are tring to make more introdcution about that by providing a series of open courses. The work is in process. Other user guidances can be referred to (here)[https://github.com/volcano-sh/volcano/tree/master/docs/user-guide].
