### ISSUE TITLE
Usage plugin supports more metrics

### ISSUE THREAD

**Issue by autumn0207** [volcano-sh/volcano#2323]
#### What would you like to be added:
Usage plugin provide a more open interface and support more metrics.

#### Why is this needed:
Not only cpu or memory resources affect the running tasks, but also  other shared resources such as I/O, LLC , memory bandwidth. And almost all the metrics data of above resources can be pulled from Prometheus. If `Usage Plugin` can consider the usage of more resource in the scheduling process,  the scheduling result will be more effective.

**Comment by william-wang** [comment]
@autumn0207 usage plugin is a alpha plugin which only supports cpu and memory so far.  It's reasonable to take more kinds of resources into account such as bandwidth, I/O and so forth.  In your case,  which kinds of prometheus indices do you want to support firstly? and do you have interesting to contribute this features, we can work together for that.
