### ISSUE TITLE
Gang scheduling job with high-priority not preempting lower priority jobs 

### ISSUE THREAD

**Issue by talcoh2x** [volcano-sh/volcano#2337]
we run gang scheduling job with high-priority but we dont see that the default priory jobs releasing once we don't enough resources. 

expected:
we expect that in such cases lower priority jobs are getting deleted. 

Volcano version 1.6.0
K8s version 1.22/1.21

**Comment by william-wang** [comment]
Thanks for your reporting, It seems the same issue with #2321, we are dealing with it.

**Comment by william-wang** [comment]
@talcoh2x Would you like to provide the job yaml?

**Comment by snirkop89** [comment]
sure:
I tried a few variations (found them in the issue here), both yielded the same result - which preemption doesn't occur:
```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: volcano
    meta.helm.sh/release-namespace: volcano-system
  creationTimestamp: "2022-06-29T11:24:44Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: volcano-scheduler-configmap
  namespace: volcano-system
  resourceVersion: "5116689"
  uid: a60fff7a-6da2-4f7b-922c-da3447fae82f

```

```
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: volcano
    meta.helm.sh/release-namespace: volcano-system
  creationTimestamp: "2022-06-29T11:24:44Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: volcano-scheduler-configmap
  namespace: volcano-system
  resourceVersion: "5116689"
  uid: a60fff7a-6da2-4f7b-922c-da3447fae82f
```

**Comment by Thor-wl** [comment]
@snirkop89 Hi, Snir. I've taken a look at the bug and preemption was broken indeed. There are several reasons about that. Firstly, the podgroup for job with high priority cannot convert from `pending` to `inqueue`. So the job has no chance to get resources. You can configure the scheduler as follows to disable `jobEnqueued` functions.
```yaml
    actions: "enqueue, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: overcommit
        enableJobEnqueued: false  ## disable jobEnqueued function for overcommit plugin 
      - name: drf
      - name: predicates
      - name: proportion
        enableJobEnqueued: false  ## disable jobEnqueued function for proportion plugin
      - name: nodeorder
      - name: binpack
```
As what I tested locally, it can make podgroup with high priority enter `inqueue` status. But preeption was still not working. I'll give more feedback as soon as the root reason is found.

**Comment by zhypku** [comment]
@Thor-wl Hi, I'm also studying the preemption behavior of Volcano, and found the same problem. It seems that the JobStarvingFn of the gang plugin forbids preemption from a job where `ji.CheckTaskMinAvailablePipelined()` is false.
![image](https://user-images.githubusercontent.com/22696877/180144482-9f46d13c-0fe9-4126-b9bf-4aa1e8641971.png)
![image](https://user-images.githubusercontent.com/22696877/180144670-b8cc3aa3-c7bb-4d93-82f2-385125386134.png)
I did find the log from the scheduler's log (in my test , the job default/priority-job has a higher priority but is waiting).
`I0721 03:40:52.353591       1 job_info.go:773] Job default/priority-job Task default-nginx occupied 0 less than task min avaliable`
Then I disabled the JobStarvingFn from the gang plugin by setting `enableJobStarving: false`. Then the preemption worked. So is this a by-design feature or a bug? Why a false return value of `CheckTaskMinAvailablePipelined` prohibits preemption?

**Comment by Thor-wl** [comment]
> @Thor-wl Hi, I'm also studying the preemption behavior of Volcano, and found the same problem. It seems that the JobStarvingFn of the gang plugin forbids preemption from a job where `ji.CheckTaskMinAvailablePipelined()` is false. ![image](https://user-images.githubusercontent.com/22696877/180144482-9f46d13c-0fe9-4126-b9bf-4aa1e8641971.png) ![image](https://user-images.githubusercontent.com/22696877/180144670-b8cc3aa3-c7bb-4d93-82f2-385125386134.png) I did find the log from the scheduler's log (in my test , the job default/priority-job has a higher priority but is waiting). `I0721 03:40:52.353591 1 job_info.go:773] Job default/priority-job Task default-nginx occupied 0 less than task min avaliable` Then I disabled the JobStarvingFn from the gang plugin by setting `enableJobStarving: false`. Then the preemption worked. So is this a by-design feature or a bug? Why a false return value of `CheckTaskMinAvailablePipelined` prohibits preemption?

Thanks for the feedback. That's what I also found yesterday. IMO, it's not something as expected. I'm tracking which commit and when this behavior is introduced.

**Comment by HecarimV** [comment]
https://github.com/volcano-sh/volcano/blob/1b2630605b3f6669b5db9a77abd12d08f923e6d3/pkg/scheduler/actions/preempt/preempt.go#L124-L126
Pods with `Preemptable` = false will not be preempted, but it seems that `task.Preemptable` is false by default if we don't set annotation or label.
https://github.com/volcano-sh/volcano/blob/1b2630605b3f6669b5db9a77abd12d08f923e6d3/pkg/scheduler/api/pod_info.go#L101
@Thor-wl  I don't know if this could be the problem.

**Comment by Thor-wl** [comment]
> https://github.com/volcano-sh/volcano/blob/1b2630605b3f6669b5db9a77abd12d08f923e6d3/pkg/scheduler/actions/preempt/preempt.go#L124-L126
> 
> 
> Pods with `Preemptable` = false will not be preempted, but it seems that `task.Preemptable` is false by default if we don't set annotation or label.
> https://github.com/volcano-sh/volcano/blob/1b2630605b3f6669b5db9a77abd12d08f923e6d3/pkg/scheduler/api/pod_info.go#L101
> 
> 
> @Thor-wl I don't know if this could be the problem.
> Similar reclaim action may have problem as well, #2340
> https://github.com/volcano-sh/volcano/blob/1b2630605b3f6669b5db9a77abd12d08f923e6d3/pkg/scheduler/actions/reclaim/reclaim.go#L135-L137

In order to keep compatible with the former versions, `task.Preemptable` should be `true` by default. @wpeng102 BTW, is this behavior introuduced from TDM plugin?

**Comment by snirkop89** [comment]
That's great to hear. Thank you for the fast response and feedback.

**Comment by Thor-wl** [comment]
> That's great to hear. Thank you for the fast response and feedback.

No worries. The fix is under discussion.

**Comment by snirkop89** [comment]
Hi, is there an update about this?

**Comment by talcoh2x** [comment]
@william-wang  @Thor-wl  
Hi Guys do you have something new to update we are really stuck and need help

**Comment by talcoh2x** [comment]
Hi, there is something new  to update ?

**Comment by talcoh2x** [comment]
@zhypku  Hi, can you share with us the Volcano configuration you have and worked for you ? I mean the preemption flow
