### ISSUE TITLE
Release-1.6 Volcano Scheduler can't schedule all resource

### ISSUE THREAD

**Issue by compactcfusr** [volcano-sh/volcano#2389]
**What happened**:
When we upgraded volcano from 1.4 to 1.6, we found PendingJob increase.
At first we thought it was volcano that limited the scheduling speed, and restarting took a long time to recover.
But we found Pending Jobs not reduced two hours later.
So we have to rollback volcano from 1.6 to 1.4
After rollback we found dirty pg leaded to inqueue pg backlog  because pg in 1.6 attach uuid suffix.We cleared the dirty and Volcano recovered. 

Duration two hours, cpu and memory usage like following:
CPU Usage:
![image](https://user-images.githubusercontent.com/15198859/181462223-392cc6fb-ef0d-44ca-9125-354feacaf7e9.png)
Memory Usage
![image](https://user-images.githubusercontent.com/15198859/181462345-c927e442-01c5-4c67-b85a-4baff41ea657.png)

It seems like Volcano Scheduler will not schedule when usage reach 60%.

**What you expected to happen**:

We hope CPU and Memory usage can reach 100%

**How to reproduce it (as minimally and precisely as possible)**:
we still not reproduce this scene, only know upgraded volcano from 1.4 to 1.6

**Anything else we need to know?**:

**Environment**:
- Volcano Version:  release-1.4
- Kubernetes version (use `kubectl version`): v1.20.10
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux 4.15.0-42
- Install tools: tekton 
- Others:

**Comment by Thor-wl** [comment]
@compactcfusr Please provide your scheudler configuration.

**Comment by compactcfusr** [comment]
> 

**volcano-admission-configmap**
 
- apiVersion: v1
  data:
    volcano-admission.conf: |
      #resourceGroups:
      #- resourceGroup: management                    # set the resource group name
      #  object:
      #    key: namespace                             # set the field and the value to be matched
      #    value:
      #    - mng-ns-1
      #  schedulerName: default-scheduler             # set the scheduler for patching
      #  tolerations:                                 # set the tolerations for patching
      #  - effect: NoSchedule
      #    key: taint
      #    operator: Exists
      #  labels:
      #    volcano.sh/nodetype: management           # set the nodeSelector for patching
      #- resourceGroup: cpu
      #  object:
      #    key: annotation
      #    value:
      #    - "volcano.sh/resource-group: cpu"
      #  schedulerName: volcano
      #  labels:
      #    volcano.sh/nodetype: cpu
      #- resourceGroup: gpu                          # if the object is unsetted, default is:  the key is annotation,
      #  schedulerName: volcano                      # the annotation key is fixed and is "volcano.sh/resource-group", The corresponding value is the resourceGroup field
      #  labels:
      #    volcano.sh/nodetype: gpu
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"volcano-admission.conf":"#resourceGroups:\n#- resourceGroup: management                    # set the resource group name\n#  object:\n#    key: namespace                             # set the field and the value to be matched\n#    value:\n#    - mng-ns-1\n#  schedulerName: default-scheduler             # set the scheduler for patching\n#  tolerations:                                 # set the tolerations for patching\n#  - effect: NoSchedule\n#    key: taint\n#    operator: Exists\n#  labels:\n#    volcano.sh/nodetype: management           # set the nodeSelector for patching\n#- resourceGroup: cpu\n#  object:\n#    key: annotation\n#    value:\n#    - \"volcano.sh/resource-group: cpu\"\n#  schedulerName: volcano\n#  labels:\n#    volcano.sh/nodetype: cpu\n#- resourceGroup: gpu                          # if the object is unsetted, default is:  the key is annotation,\n#  schedulerName: volcano                      # the annotation key is fixed and is \"volcano.sh/resource-group\", The corresponding value is the resourceGroup field\n#  labels:\n#    volcano.sh/nodetype: gpu\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"volcano-admission-configmap","namespace":"volcano-system"}}
    creationTimestamp: "2021-11-04T08:21:05Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:volcano-admission.conf: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-11-04T08:21:05Z"
    name: volcano-admission-configmap
    namespace: volcano-system
    resourceVersion: "604471"
    uid: 2fef3c4a-3df7-46cc-b8a8-2bf860af4f8c


**volcano-scheduler-configmap**

- apiVersion: v1
  data:
    volcano-scheduler-shopee.conf: |
      actions: "enqueue, allocate, backfill"
      - plugins:
        - name: priority
        - name: gang
        - name: conformance
      - plugins:
        - name: drf
        - name: predicates
        - name: proportion
        - name: nodeorder
        - name: binpack
        - name: numa-aware # add it to enable numa-aware plugin
          arguments:
            weight: 10
        - name: nodeorder
          arguments:
            leastrequested.weight: 10
            balancedresource.weight: 10
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"volcano-scheduler-shopee.conf":"actions: \"enqueue, allocate, backfill\"\ntiers:\n- plugins:\n  - name: priority\n  - name: gang\n  - name: conformance\n- plugins:\n  - name: drf\n  - name: predicates\n  - name: proportion\n  - name: numa-aware\n    arguments:\n      weight: 10\n  - name: nodeorder\n    arguments:\n      leastrequested.weight: 10\n      balancedresource.weight: 10\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"volcano-scheduler-configmap","namespace":"volcano-system"}}
    creationTimestamp: "2021-11-04T08:21:05Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
        f:metadata:
          f:annotations: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2021-11-04T08:21:05Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubectl.kubernetes.io/last-applied-configuration: {}
      manager: kubectl
      operation: Update
      time: "2022-07-21T03:29:59Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:volcano-scheduler-shopee.conf: {}
      manager: kubectl-edit
      operation: Update
      time: "2022-07-21T06:14:39Z"
    name: volcano-scheduler-configmap
    namespace: volcano-system
    resourceVersion: "2297845691"
    uid: c7d13ea9-db2c-49bf-b807-5ba36fcb5eb0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by Thor-wl** [comment]
Thanks for you feedback and fix. I've been aware of the reason. I'll urage the merge of the fix ASAP.

**Comment by compactcfusr** [comment]
> I'll urage the merge of the fix ASAP

Thanks for your help.It is fixed by @Akiqqqqqqq(https://github.com/volcano-sh/volcano/pull/2400) and we hope it can be helpful.Glad to be able to do out bit.
