### ISSUE TITLE
gang scheduling condition

### ISSUE THREAD

**Issue by Ddingtt** [volcano-sh/volcano#2396]
https://github.com/volcano-sh/volcano/blob/e843edd74493ce6b9253cdef2ff9e291c9e981b9/pkg/scheduler/plugins/gang/gang.go#L218
we run non-gang scheduling job but also take these conditions in podgroup.

![image](https://user-images.githubusercontent.com/16216183/181743985-be4399db-33a6-4e5e-b408-67c67ff4c6a7.png)

**Comment by Thor-wl** [comment]
@Ddingtt Hey. This description is too simple to help analyses what happened and how we can help you. Suggest to follow the issue specification and give more details. Thanks.
