### ISSUE TITLE
Delay Launcher Until Workers Are Running (MPI)

### ISSUE THREAD

**Issue by KeithBallard** [volcano-sh/volcano#2402]
With MPI jobs, it is preferred that the launcher container does not start until the workers are up and running.  Otherwise, the MPI call is guaranteed to fail.  Our workaround has been adding:
```
# Read the lists of worker hostnames and try to ssh into each, forcing this container
# to wait until all workers are up and running before continuing.
for host in $(cat /etc/volcano/worker.host); do ssh $host date; while test $? -gt 0; do echo "Could not reach host '$host', trying again in 5s."; sleep 5; ssh $host date; done; echo "$host is ready."; done;
```
to the launcher's command string, which keeps trying to ssh into the workers one by one until all succeed.  This essentially previous any following commands from running on the process until the workers are available.  However, it would be convenient if volcano wants to cater to MPI jobs to have occur in the background automatically.

**Comment by Thor-wl** [comment]
@KeithBallard Hey. Please have a try with [MPI plugin](https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_mpi_plugin.md) and [task dependency](https://github.com/volcano-sh/volcano/blob/master/docs/design/task-launch-order-within-job.md).

**Comment by nysal** [comment]
I have volcano scheduling mpi jobs in my cluster. The shipped `example/integrations/mpi/mpi-example.yaml` works well. I tried running with the mpi plugin instead and hit issues with the master pod failing name resolution of the worker pods. The YAML used was the one in `docs/user-guide/how_to_use_mpi_plugin.md`. The worker pods are running, but the master cannot resolve their names.

**Comment by KeithBallard** [comment]
I had some similar issues but eventually found workarounds.  

First, regarding the mpi plugin, @nysal .  It worked fine for me with:
```
plugins:
    mpi: ["--master=launcher","--worker=worker","--port=22"]  ## MPI plugin register
```
And ensuring the tasks names are exactly "launcher" and "worker".

Second, there are two issues with the dependency syntax:
1. The syntax is wrong in the documentation.  It should be:
```
dependsOn:
        name:
          - worker
```
2. The `minAvailable` value for the spec creates issues.  It must be set to exactly how many workers there are (NOT including the launcher task). Otherwise, it will hang forever and the workers will stay pending.  This of course should be rethought since you would want there to be enough slots for the launcher too.  Workers running without a launcher is a lot of wasted resources.

**Comment by nysal** [comment]
@KeithBallard are you using v1.6 or a recent master branch build?

**Comment by KeithBallard** [comment]
> 

I am using v1.6
