### ISSUE TITLE
About the parameter configuration of nodeorder plug-in node scoring

### ISSUE THREAD

**Issue by shmily0000** [volcano-sh/volcano#2404]
According to the introduction of nodeorder plug-in, the plug-in can score nodes through multiple dimensions. Looking at the code description inside, there are seven parameters, such as mostrequested.weight, leastrequested.weight, balancedresource Several parameters of weight can be configured to make it score different points for different nodes, so that I can make the job run evenly on all nodes, or give priority to the nodes with the lowest utilization rate such as CPU memory or the nodes with the highest utilization rate. And I read the notes in nodeorder, saying that it is added by multiplying the weight by the score, but when I only add leastrequest When wet is set to a positive integer greater than one, and the others are set to zero, it seems that he will really give priority to the node with the lowest utilization. However, when I only put mostrequested When weight is set to a positive integer greater than one, and other settings are zero, it does not seem to take effect, and it still runs on the node with the lowest node utilization. And when I only put balancedresource When the weight is set to be greater than one, and the other is set to zero, it is not found that it will be very evenly tiled on each node.

Here is the parameter configuration when I try: either change most to 100, or change balanced to 100。

actions: "reclaim, allocate, backfill, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
        arguments:
          leastrequested.weight: 100
          mostrequested.weight: 0
          nodeaffinity.weight: 0
          podaffinity.weight: 0
          balancedresource.weight: 0
          tainttoleration.weight: 0
          imagelocality.weight: 0

In addition, I saw that the general configuration in the previous post did not mention the scenario, but the parameters seemed to be inconsistent with the current ones. Cm files learned in other posts:

actions: "enqueue, reserve, allocate, backfill, preempt"
tiers:
- plugins:
  - name: reserveresource
    arguments:
      reserve.cpu: 1
      reserve.memory: 2Gi
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: predicates
  - name: nodeorder
    arguments:
      nodeaffinity.weight: 20
      podaffinity.weight: 20
      bizaffinity.weight: 100
      resourcefit.weight: 20
      leastrequested.weight: 0
      balancedresource.weight: 1
      imagelocality.weight: 1
      similaraffinity.weight: 1

It seems that the parameters are different, and when I use my own configuration, I don't seem to see the scores given to each node by checking the scheduler's log.

volcano：1.6.0
K8s version: 1.23/1.23

Can you give me some help? This plug-in doesn't seem to see the documents used. Can you give me the parameter configuration of two scenarios, scenario 1 (jobs run evenly on all nodes) and scenario 2 (jobs run first on nodes with low resource utilization), and then I will further learn how to use scoring for us according to your parameters. It would be better if I could mention the calculation method by the way.

**Comment by hwdef** [comment]
> /cc @hwdef Can you help for that?

ok,I will take a look.

**Comment by shmily0000** [comment]
@hwdef Hello, how is the progress on the use and problems of this plug-in? Thank you

**Comment by hwdef** [comment]
> @hwdef Hello, how is the progress on the use and problems of this plug-in? Thank you

Sorry for being a bit busy lately, I'll put this issue at the top of the to-do list.Reply as soon as possible

**Comment by zhifanggao** [comment]
Hit the same problem . Any progress about this issue?
