### ISSUE TITLE
Volcano Job does Not Support Number of Request CPUs as a Decimal

### ISSUE THREAD

**Issue by compactcfusr** [volcano-sh/volcano#2406]
**What happened**:

Create VolcanoJob does Not Support Number of Request CPUs as a decimal.

Error Message as following:
> I0802 11:59:07.825995       1 calculate.go:201] 333db330-457c-41ac-a9b4-0ff12d44e681/fd812b5e-af2b-4f2f-a296-f640214f3e08 job 4165-wzl-test-quota1-test/wzl-test-sj5, allocatable: 30, 60Gi, req: 500m, 1Gi
I0802 11:59:07.826055       1 job_sched.go:306] schedule sj: <4165-wzl-test-quota1-test/wzl-test-sj5>
I0802 11:59:07.834917       1 job_sched.go:244] schedule job 4165-wzl-test-quota1-test/wzl-test-sj5 failed, err: admission **webhook "validatejob.volcano.sh"** denied the request: **the cpu request isn't  an integer in spec.task[0] container[0]**.

**What you expected to happen**:
Our Needs： Create VolcanoJob does Support Number of Request CPUs as a decimal.
Reason： We would like to stress test, but we have limited hardware resources.So it is to waste to create a vj using 1C.

**How to reproduce it (as minimally and precisely as possible)**:
Create the volcano job and point the Job.Spec.Tasks[x].Template.Spec.Containers[x].Resources.Requests[v1.ResourceCPU] as decimal(for example: 0.5).

**Anything else we need to know?**:
if it's a bug, I have create a pull request: https://github.com/volcano-sh/volcano/pull/2405. Please help to review.Thanks.

**Environment**:
Volcano Version: release-1.4
Kubernetes version (use kubectl version): v1.20.10
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release): ubuntu 16.04
Kernel (e.g. uname -a): Linux 4.15.0-42
Install tools: tekton
Others:

**Comment by Thor-wl** [comment]
Thanks for your feedback. Let me take a check.

**Comment by compactcfusr** [comment]
Sorry, it seem like my wrong usage.I have try creating decimal request cpu by set Qos policy brustable, it succeed.
Therefore, I'll close this PR.
