### ISSUE TITLE
sparkapplication uses volcano as batchScheduler FAILED

### ISSUE THREAD

**Issue by huangyufeng0507** [volcano-sh/volcano#2407]
I run the official demo spark-pi.yaml, and assign the parameter that batchScheduler: "Volcano". However, when i exec kubectl describe pod of driver pod or executor pod, it displays that these pods are scheduler by "default-scheduler". I am confused about it, is it supposed to be volcano rather than "default-scheduler"?

**Comment by huangyufeng0507** [comment]
![image](https://user-images.githubusercontent.com/91405051/182531011-1c129f06-d01a-49a7-b0af-4d36329fe229.png)
This is the info of an executor pod, i think it suppose to show volcano ranther than default-scheduler.

**Comment by Thor-wl** [comment]
Execuse me. Are you sure you have already setup Volcano successfully?

**Comment by huangyufeng0507** [comment]
> Execuse me. Are you sure you have already setup Volcano successfully?

Thanks for reply. I solved this problem after enabling webhook!

**Comment by Thor-wl** [comment]
OK. If that, I will close this issue.
