### ISSUE TITLE
statefulset-controller  create Pod nats-0 in StatefulSet nats failed error: Internal error occurred: failed calling webhook "mutatepod.volcano.sh": webhook returned response.patchType but not response.patch

### ISSUE THREAD

**Issue by wujianqiangwjq** [volcano-sh/volcano#2414]
statefulset-controller  create Pod nats-0 in StatefulSet natsa failed error: Internal error occurred: failed calling webhook "mutatepod.volcano.sh": webhook returned response.patchType but not response.patch

**Comment by elinx** [comment]
#2225 
Did this solve your problem?
