### ISSUE TITLE
【community bridge】Pick out reasonable victim pods for rescheduling plugin

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2425]
As what [Rescheduling Desgin Doc](https://github.com/volcano-sh/volcano/blob/master/docs/design/rescheduling.md) says and [rescheduling plugin](https://github.com/volcano-sh/volcano/pull/2184) implemented currently, it is a little bit rough to evict selected victims without difference. In fact, we should consider more factors such as pod priority, critical pod and so on. In order to make rescheduling reasonable, your tasks are as follows.
* Provide a complete design with documentation.
* Implement the design align with code of conduct.
* Provide a full test in classical scenarios with UT and E2E.

mentor: [Thor-wl](https://github.com/Thor-wl)

**Comment by rainstarwz** [comment]
@Thor-wl Hi ! I'm interested in this issue. Let me know what should I do?

**Comment by Thor-wl** [comment]
> @Thor-wl Hi ! I'm interested in this issue. Let me know what should I do?

Great. Please send me a brief resume.

**Comment by 0saurabh0** [comment]
Hi @Thor-wl I would love to work on this. Anything for getting started.
 I've applied for this project in this term of LFX mentorship and also I've sent you my resume as mentioned.

**Comment by 0saurabh0** [comment]
@Thor-wl  Is there any documentation of volcano, where I can learn more ?
