### ISSUE TITLE
【community bridge】Avoid hot nodes in scheduling based on real workload

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2426]
In [v1.6.0](https://github.com/volcano-sh/volcano/releases/tag/v1.6.0), Volcano has supported [Dynamic Scheduling Based on Real Node Load](https://github.com/volcano-sh/volcano/blob/master/docs/design/usage-based-scheduling.md). But there still be some gaps. For example, in production environment, since the load of a Pod does not rise immediately after it is created, this leads to a problem like Scheduling hotspots that is a large number of Pods are scheduled on the same node for a short time. The scheduler should avoid the hot nodes which may be under a huge resource pressure. In order to achieve the goal, your tasks are as follows.

* Give an algorithm and design about how to avoid hot nodes and balance node resource pressure.
* Implement your idea aligin with code of conduct.
* Provide a full test with UT and E2E.

mentor: [william-wang](https://github.com/william-wang)

**Comment by zeel-pathak** [comment]
Hey @Thor-wl, I would love to work on this issue under LFX Mentorship.

I have already applied for the mentorship with volcano on LFX, 
Looking forward to work with such an amazing community.

**Comment by zeel-pathak** [comment]
I tried joining the SLACK group, but it requires an invitation, So Is there any other way I can interact with the community?

**Comment by Thor-wl** [comment]
@zeel-pathak Hey. Thanks for your participation. The mentor of this issue is @william-wang. Please contact with him and get future information.

**Comment by zeel-pathak** [comment]
Thanks for the info @Thor-wl, Should I contact him in the current thread or via Email?

**Comment by zeel-pathak** [comment]
Hey @william-wang, I guess you are the mentor for this issue under LFX Mentorship, Where can I join the community? your help would be appreciated.

**Comment by zeel-pathak** [comment]
Hey @william-wang , @Thor-wl submitted application for this project. Can't wait to work on this project. Looking forward to work with you as mentee. Hope to get selected and together we will rock & roll.
🤜🤛

**Comment by zeel-pathak** [comment]
Hey @william-wang & @Thor-wl, I have submitted my application but the results for the volcano are not out, the results of all other projects are out.

I am really waiting for a response from your side, and also I can not find any further information on the LFX mentorship page.

I tried contacting you guys on CNCF slack, but there was no update.

Your response will be highly appreciated.
