### ISSUE TITLE
【community bridge】Implement pod filter chain for rescheduling

### ISSUE THREAD

**Issue by Thor-wl** [volcano-sh/volcano#2428]
As what [Rescheduling Desgin Doc](https://github.com/volcano-sh/volcano/blob/master/docs/design/rescheduling.md) says and https://github.com/volcano-sh/volcano/pull/2184 implemented currently, all pods will be regared as potential victims. It is not so reasonable for some scenarios. For example, team1 and team2 share a k8s cluster and each team maps to a queue(queue1 and queue2). They want to run their own business without interference. If team1 enables rescheduling, only pods in queue1 should be regared as potential victims. In order to do that, your tasks are as follows.

* Provide a complete design with documentation.
* Implement the design align with code of conduct.
* Provide a full test in classical scenarios with UT and E2E.

mentor:[Thor-wl](https://github.com/Thor-wl)

**Comment by anonymousr007** [comment]
Hello Sir,

I am Rishabh, an undergraduate computer engineering student at Delhi Technological University. I am interested in this project of Mentorship of LFX. Can you please share further information? How can we be selected for mentorship and also contribute to this project?

Skills: C, C++, Python, Golang (Intermediate)
DevOps: Linux, Computer Networks, Yaml, Kubernetes (Basics), Docker (Basics).

Thanks & Regards
Rishabh

**Comment by Thor-wl** [comment]
> Hello Sir,
> 
> I am Rishabh, an undergraduate computer engineering student at Delhi Technological University. I am interested in this project of Mentorship of LFX. Can you please share further information? How can we be selected for mentorship and also contribute to this project?
> 
> Skills: C, C++, Python, Golang (Intermediate) DevOps: Linux, Computer Networks, Yaml, Kubernetes (Basics), Docker (Basics).
> 
> Thanks & Regards Rishabh

@anonymousr007 Hi. Please send a resume to me. My email is 13164644535@163.com. Thanks.

**Comment by anonymousr007** [comment]
> > Hello Sir,
> > I am Rishabh, an undergraduate computer engineering student at Delhi Technological University. I am interested in this project of Mentorship of LFX. Can you please share further information? How can we be selected for mentorship and also contribute to this project?
> > Skills: C, C++, Python, Golang (Intermediate) DevOps: Linux, Computer Networks, Yaml, Kubernetes (Basics), Docker (Basics).
> > Thanks & Regards Rishabh
> 
> @anonymousr007 Hi. Please send a resume to me. My email is [13164644535@163.com](mailto:13164644535@163.com). Thanks.

Hello sir, I sent my resume to you. Thanks.

**Comment by Thor-wl** [comment]
> Hello sir, I sent my resume to you. Thanks.

OK. Received. Thanks.

**Comment by anonymousr007** [comment]
> > Hello sir, I sent my resume to you. Thanks.
> 
> OK. Received. Thanks.

Please share further information. Thanks.

**Comment by anonymousr007** [comment]
Hello Sir, I submitted my cover letter and resume to the official LFX Mentorship Portal. Please share some tasks or some resources to learn more about this project. Thanks.
