### ISSUE TITLE
【community bridge】Integrate Volcano with Ray

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#2429]
Some Vocano users are using Ray (https://github.com/ray-project/ray) at the same time. e.g. Cruise. We want to make Volcano and Ray play together more effectively. 

- Investigate the integration solution for Volcano, KubeRay, Ray autoscaling etc.
- Implement the feature align with code of conduct.
- Provide a integration guide.
- Provide a full test in classical scenarios with UT and E2E.

mentor: [william-wang](https://github.com/william-wang)

**Comment by tgaddair** [comment]
Hey @william-wang, we just added support for Volcano in the official KubeRay operator (Ray on Kubernetes) in https://github.com/ray-project/kuberay/pull/755 ([docs](https://ray-project.github.io/kuberay/guidance/volcano-integration/)).

What do you think about updating the Volcano docs to include references to KubeRay? I'd be happy to put together a PR for this.
