### ISSUE TITLE
【community bridge】Support hot update daemon log level

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#2430]
When some glitches happends in production env and need to figure out the cause, one option is to change the log level and reproduce the issue to get more verbosed log. The log level threshold is hard coded into deployment yaml file right now, the volcano component like scheduler will restart when the log level changed and the issue may can't reporduce anymore.

- Provide the design doc
- Implement the feature align with code of conduct.
- Provide a full test in classical scenarios with UT and E2E.

mentor: [william-wang](https://github.com/william-wang)

**Comment by nitishchauhan0022** [comment]
Hi @william-wang I am interested in working on this issue. Could you please share some resources to getting started with this issue?
