### ISSUE TITLE
Using Volcano Jobflow: the image built locally can not work!!!

### ISSUE THREAD

**Issue by huangyufeng0507** [volcano-sh/volcano#2449]
![image](https://user-images.githubusercontent.com/91405051/185338572-d5cadb20-80c5-454a-b870-0f5bb60e9e43.png)
The dockerfile shows a line that ENTRYPOINT [/manager], then i delete this line, rebuild the image and run /manager in container to verify the file manager whether actually works, but it meets this problem.

**Comment by hwdef** [comment]
repeat with https://github.com/BoCloud/JobFlow/issues/19

When jobflow is merged into volcano, there is no such problem. So this issue should open in volcano-sh/volcano.
we will answer in bocloud/jobflow.

/close
