### ISSUE TITLE
Increase the default weights of several arguments in nodeorder plugin

### ISSUE THREAD

**Issue by kerthcet** [volcano-sh/volcano#2452]
#### What would you like to be added:
Currently in plugin nodeorder, we have default weights for these kubernetes upstream plugins, but the weights seem problematic. 

The default weights of these plugins are all equal to 1, but actually they should not. Imagine that, an end-user explicitly prefer the pod1 to be allocated on nodeA to couple with pod2 for podAffinity policy, but due to the lower utilization of nodeB, pod1 will be scheduled to nodeB then, it's not as expected.

So I'd like to increase the default weights for several upstream plugins:
1. nodeAffinity weight 1 -> 2
2. podAffinity weight 1 -> 2
3. tainttoleration.weight 1 -> 3

```
//  - plugins:
//    - name: nodeorder
//      arguments:
//        leastrequested.weight: 1
//        mostrequested.weight: 0
//        nodeaffinity.weight: 1
//        podaffinity.weight: 1
//        balancedresource.weight: 1
//        tainttoleration.weight: 1
//        imagelocality.weight: 1
```

The risk is it's a break change which will result in the different scheduling results, but I think it's more reasonable. By the way, the idea is accepted by the upstream Kubernetes.

#### Why is this needed:

Better scheduling results.

**Comment by kerthcet** [comment]
cc @Thor-wl for thoughts.

**Comment by william-wang** [comment]
Thanks for your report. It seems reasonable to do this change. 
> The risk is it's a break change which will result in the different scheduling results, but I think it's more reasonable. By the way, the idea is accepted by the upstream Kubernetes.

Is there any reference for this?

**Comment by kerthcet** [comment]
No documents but we can refer to the code here
https://github.com/kubernetes/kubernetes/blob/6dd8b86124e7e4f36f4a3d1939b6ee616ad40c58/pkg/scheduler/apis/config/v1/default_plugins.go#L28-L57

**Comment by kerthcet** [comment]
Any thoughts @william-wang

**Comment by Thor-wl** [comment]
@kerthcet Thanks for the invitation. I think that's reasonable to optimize the weights of the parameters. BTW, can you give more advice about the values of others' argument according to the real scenarios?

**Comment by kerthcet** [comment]
Keep them consistent with upstream kubernetes is more convinced to me, that will not surprise users too much when migrating from kubernetes to volcano. So the changes are great enough to me.
