### ISSUE TITLE
volcano support checkpoint

### ISSUE THREAD

**Issue by 18707602767** [volcano-sh/volcano#2454]
#### What would you like to be added:
Hope volcano can support checkpoint. When the job is interrupted due to external reasons, it can continue to run according to the checkpoint.

#### Why is this needed:
some lengthy calculations can run for days.If the calculation node dies, we have to restart from the beginning.Having a checkpoint created, we can at least restart from this point of calculation.

**Comment by william-wang** [comment]
May I know which kind of computing engine e.g spark are you using? Usually the chickpoint function is implemented in upper layer framework, e.g pytorch.
