### ISSUE TITLE
Use nvidia-smi to ban error gpu make UnexpectedAdmissionError with  failed to find gpu id, which is unexpected

### ISSUE THREAD

**Issue by WingkaiHo** [volcano-sh/volcano#2473]
**What happened**:
If you have use nvidia-smi to ban error gpu, before add machine to k8s ,such as

```
nvidia-smi drain -p <id> -m 0
```

It add this machine to k8s, use gpu-share scheduler it. It will schedule fail with  error `Warning UnexpectedAdmissionError kubelet Allocate failed due to rpc error: code = Unknown desc = failed to find gpu id, which is unexpected` some time

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Use nvidia-smi to ban gpu which path is /dev/nvidia0, and this machine, use gpu share schudler, commond
```
nvidia-smi drain -p <id> -m 0
```
add node k8s, run volcano gpu-share device plugin.   

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.5
- Kubernetes version (use `kubectl version`): 1.22.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):  4.14.83
- Install tools: 
- Others:

**Comment by WingkaiHo** [comment]
https://github.com/volcano-sh/devices/pull/29

**Comment by WingkaiHo** [comment]
I think space of volcano-schduler gpu ids are  0 -  GpuDeviceCount - 1;  but if you use nvidai-smi to ban error gpu, the gpu ids space of is not start 0 or not continuous

**Comment by HariVamsiK** [comment]
Hey @WingkaiHo I want to work on this issue.

**Comment by WingkaiHo** [comment]
@HariVamsiK it fix in https://github.com/volcano-sh/devices/pull/29
