### ISSUE TITLE
Volcano gpu-share plugin patch all suitalbe for pod

### ISSUE THREAD

**Issue by WingkaiHo** [volcano-sh/volcano#2491]
**What happened**:
When update volcano master,  check scheduler to gpu-share pod. The volcano device-plugin patch gpu to pod fail. I found annotations 
 `volcano.sh/gpu-index: "5,6"`  

**What you expected to happen**:
gpu-share only patch on gpu id for pod

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by WingkaiHo** [comment]
https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/predicates/predicates.go#L197

retrun all suitable gpu ids for pod. But pod need only one gpu id.

**Comment by HariVamsiK** [comment]
Hey @WingkaiHo I would like to work on this issue. It would help me in my academics.
