### ISSUE TITLE
metrics exposure for volcano job succeeded state and failed state

### ISSUE THREAD

**Issue by Saba1119** [volcano-sh/volcano#2493]
#### What would you like to be added:
currently there is no metrics for **volcano jobs succeeded state and failed state** ,only volcano podgroup pending,inqueue,running and unknown state is available.those metrics are

volcano_queue_pod_group_inqueue_count
volcano_queue_pod_group_pending_count
volcano_queue_pod_group_running_count
volcano_queue_pod_group_unknown_count

#### Why is this needed:

if this metrics are available in volcano then it will be useful for visualization in grafana dashboard

**Comment by lppsuixn** [comment]
need this.

**Comment by hwdef** [comment]
still need

**Comment by DsLipku** [comment]
still need

**Comment by Prepmachine4** [comment]
Can I try it as my first contribution to the volcana?

**Comment by Monokaix** [comment]
> Can I try it as my first contribution to the volcana?

Yeah，you can try it.

**Comment by Prepmachine4** [comment]
@Monokaix Please  review the code, thank you.

**Comment by Prepmachine4** [comment]
@Monokaix Please review the code again, thank you.
