### ISSUE TITLE
podgroup lifecycle management enhancement

### ISSUE THREAD

**Issue by elinx** [volcano-sh/volcano#2518]
#### What would you like to be added:
For native k8s workload case, design an enhanced podgroup lifecycle management system instead of depending on `ownerreference` based GC mechanism.

#### Why is this needed:
When deploying native k8s workload like depolyment, volcano just simply creates a podgroup for the pods in it by getting pods' owner and setting podgroup's owner to the replicaset accordingly, i.e. one replicaset one podgroup life bonding together. Meanwhile, in the rolling update case, the old replicaset has a chance won't be deleted which causes the old podgroup not to be deleted, and a new replicaset/podgroup pair is created while the old podgroup still occupied a number of resources in the specific queue, which may in the end cause new podgroups can't be enqueued.

What's more, in deleting deployment scenario, podgroup and pods are all recycled using k8s's GC, which causes the whole pod deleting time to be postponed by almost 40% in the one pod per deployment case compared to the kube-scheduler.

Any suggestions?

**Comment by shinytang6** [comment]
FYI: already have some discussions in https://github.com/volcano-sh/volcano/issues/1853

**Comment by william-wang** [comment]
There is solution for this issue and the design had ever been shared on weekly meeting. We need to resource to implement it.
https://github.com/volcano-sh/volcano/blob/master/docs/design/Enhance-Generate-PodGroup-OwnerReferences-for-Normal-Pod.md
