### ISSUE TITLE
Include CI testing for Linux/ARM64 platform

### ISSUE THREAD

**Issue by odidev** [volcano-sh/volcano#2519]
#### What would you like to be added:

I am working with Volcano on Linux/ARM64 platform. 

Volcano has already released multi-arch docker images now, that supports ARM64. 
I can see some e2e tests running via GitHub Actions for x64.  
May I know, would it be feasible for you to run/include those tests for Linux/ARM64 as well in the CI? 

Kindly share your opinion. I will be happy to contribute if required.

**Comment by odidev** [comment]
FYI, since GitHub Actions does not support Linux/ARM64 natively, there is a repo “WorksOnArm” that provides free access to ARM64 based clusters. 

Works on Arm is an initiative that provides free access to Arm based clusters (on Equinix). This is for the purpose of giving open-source projects access to Arm HW to support build-test loops. To apply for access, you must open an issue with the project linked below. 

https://github.com/WorksOnArm/equinix-metal-arm64-cluster 

Please keep in mind, this is for access to Arm based HW. The actual maintenance of the build systems deployed on the Arm cluster would still need to be done by the project.

**Comment by hwdef** [comment]
I think this is necessary.

**Comment by odidev** [comment]
@hwdef, I am working with Volcano on Linux/ARM64 platform.  

To run some e2e tests running via GitHub Actions for ARM64.I need volcanosh/example-mpi docker image for arm64 architecture. I have built the arm64 image form this volcano/example/integrations/mpi/Dockerfile file.  

After building the image, I have tried to run e2e test2, those tests were running successfully. Could you please let me know if there are any plans to release the arm64 image for example-mpi file?

**Comment by hwdef** [comment]
> 



> @hwdef, I am working with Volcano on Linux/ARM64 platform.
> 
> To run some e2e tests running via GitHub Actions for ARM64.I need volcanosh/example-mpi docker image for arm64 architecture. I have built the arm64 image form this volcano/example/integrations/mpi/Dockerfile file.
> 
> After building the image, I have tried to run e2e test2, those tests were running successfully. Could you please let me know if there are any plans to release the arm64 image for example-mpi file?

oh, sorry, I don't have permission to publish volcano images to docker hub , please find other maintainers.
@william-wang @jiangkaihua @wangyang0616 @Thor-wl

**Comment by odidev** [comment]
@william-wang @jiangkaihua @wangyang0616 @Thor-wl, I am working with Volcano on Linux/ARM64 platform. 

To run some e2e tests running via GitHub Actions for ARM64.I need volcanosh/example-mpi docker image for arm64 architecture. I have built the arm64 image form this volcano/example/integrations/mpi/Dockerfile file. 

After building the image, I have tried to run e2e test2, those tests were running successfully. Could you please let me know if there are any plans to release the arm64 image for example-mpi file?

**Comment by Thor-wl** [comment]
Good issue! Hope to see this suggestion to be put into practice.

**Comment by odidev** [comment]
> @william-wang @jiangkaihua @wangyang0616 @Thor-wl, I am working with Volcano on Linux/ARM64 platform.
> 
> To run some e2e tests running via GitHub Actions for ARM64.I need volcanosh/example-mpi docker image for arm64 architecture. I have built the arm64 image form this volcano/example/integrations/mpi/Dockerfile file.
> 
> After building the image, I have tried to run e2e test2, those tests were running successfully. Could you please let me know if there are any plans to release the arm64 image for example-mpi file?

@william-wang @jiangkaihua @wangyang0616, Could you please share your feedback regarding the above issue.

**Comment by wangyang0616** [comment]
> @william-wang @jiangkaihua @wangyang0616, Could you please share your feedback regarding the above issue.

**Comment by wangyang0616** [comment]
> FYI, since GitHub Actions does not support Linux/ARM64 natively, there is a repo “WorksOnArm” that provides free access to ARM64 based clusters.
> 
> Works on Arm is an initiative that provides free access to Arm based clusters (on Equinix). This is for the purpose of giving open-source projects access to Arm HW to support build-test loops. To apply for access, you must open an issue with the project linked below.
> 
> https://github.com/WorksOnArm/equinix-metal-arm64-cluster
> 
> Please keep in mind, this is for access to Arm based HW. The actual maintenance of the build systems deployed on the Arm cluster would still need to be done by the project.

This is a great idea and would be a great benefit to the project if it could be implemented.

At the same time, I also have some questions that are not very clear. How to apply for and maintain arm resources, what is the approximate resource quota, etc. If you know more information, thank you very much for sharing.

**Comment by odidev** [comment]
> > @william-wang @jiangkaihua @wangyang0616, Could you please share your feedback regarding the above issue.
> 
> I think this is a very good proposal. We can push the arm version of the example-mpi image to the Volcanosh warehouse, which is convenient for arm platform developers to carry out verification activities.
> 
> The amd64 and arm64 architecture images can be pushed through cross-compilation. The command is as follows:
> 
> ```
> docker buildx build -t volcanosh/example-mpi:0.0.2 . -f ./example/integrations/mpi/Dockerfile --output=type="registry" --platform "linux/amd64,linux/arm64"
> ```
> 
> In addition, I think we should also look together to see if there are other mirrors that have similar requirements, we can sort them out, and gradually update them to the volcanosh warehouse.
> 
> **Some of the image information I have organized are as follows：**
> 
> * example-mpi
> * example-tf
> * dist-mnist-tf-example
> * mxnet-train-mnist-cpu
> 
> **The corresponding versions after the upgrade are:**
> 
> * example-mpi:0.0.2
> * example-tf:0.0.5
> * dist-mnist-tf-example:0.0.2
> * mxnet-train-mnist-cpu:v1.1
> 
> In addition to the images listed above, if there are other images that need to provide arm64 versions, you can add them together.

@ [wangyang0616](https://github.com/wangyang0616) , I was running the pipelien using e2e-sequence.yaml file, while running the pipeliene, error is thrown as this **volcanosh/dist-mnist-tf-example** and **example-tf** image not found. 

 You have updated the version for this image but by updating the version it is not running, it shows error as no manifest found.   

Could you please release the docker image for linux arm64. It would be really helpful. 

`Error response from daemon: manifest for volcanosh/dist-mnist-tf-example:0.0.2 not found: manifest unknown: manifest unknown`

**Comment by wangyang0616** [comment]
@odidev The above is the image version that is planned to be uploaded, but it has not been officially pushed to dockerhub. 

It is currently the Chinese New Year holiday, and the community contributors are basically on vacation. I will come next week to confirm with the community contributors about pushing the mirror image.

**Comment by odidev** [comment]
@wangyang0616, Could you please share your feedback regarding the above issue.

**Comment by wangyang0616** [comment]
I just looked at the code of volcano e2e, and there are four test images that need to be used
- `busybox:1.24` is not involved this time
- `nginx:1.14` is not involved this time
- `volcanosh/example-mpi:0.0.1` needs to provide arm version
- `volcanosh/dist-mnist-tf-example:0.0.1` needs to provide arm version

For the aforementioned `example-tf`, `mxnet-train-mnist-cpu`, they are not used in e2e, so the image will not be upgraded this time.

- `volcanosh/example-mpi:0.0.1` already provides `volcanosh/example-mpi:0.0.2`, support amd64 and arm

- `volcanosh/dist-mnist-tf-example:0.0.1` is downloaded from the TensorFlow mirror warehouse, and Volcano has not been modified in any way. What I know is that TensorFlow should not support arm mirroring, so this mirroring cannot do amd64 and arm supports both.

@odidev 
You can try whether `volcanosh/example-mpi:0.0.2` can meet expectations. In addition, the arm version support of `volcanosh/dist-mnist-tf-example` is beyond my ability, I am very sorry
