### ISSUE TITLE
[Discussion] Using multiple volcano scheduler/admission/controllers

### ISSUE THREAD

**Issue by Aakcht** [volcano-sh/volcano#2520]
#### What would you like to be added:

Possibility to use multiple volcano scheduler/admission/controllers .

#### Why is this needed:

Increases volcano high availability.

I'm not sure if it is supported now - I checked by manually increasing number of replicas for  volcano scheduler/admission/controllers and didn't notice any issues, but helm chart does not allow to specify component replicas.

**Comment by hwdef** [comment]
I think volcano already support high availability.

**Comment by Aakcht** [comment]
@hwdef in this case I think it would be nice to have the possibility to configure the number of replicas for volcano components in helm chart. I might submit a PR for this later if no one minds.
