### ISSUE TITLE
Nominate to join the volcano community

### ISSUE THREAD

**Issue by kerthcet** [volcano-sh/volcano#2535]
Hi volcano folks, I'm a contributor currently working on batch processing, I'd like to join the volcano community for further contributions.

Following the [requirements](https://github.com/volcano-sh/volcano/blob/master/community-membership.md#member):
So far, I submitted [15 PRs](https://github.com/volcano-sh/volcano/pulls?q=is%3Apr+author%3Akerthcet), 14 merged.
Besides, I also help to review several PRs. 

Hope to be sponsored by your guys. @william-wang @Thor-wl @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
big +1

**Comment by kerthcet** [comment]
I have no idea whether this is still valid now, but hoping to get response from your guys. cc @Thor-wl

**Comment by hzxuzhonghu** [comment]
ping @william-wang

**Comment by Thor-wl** [comment]
Sorry to the late reply. Thanks for your contributions. That really makes sense a lot.
/lgtm

**Comment by shinytang6** [comment]
+1, welcome!

**Comment by wangyang0616** [comment]
+1, welcome！

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/volcano-sh to accept and join.

**Comment by kevin-wangzefeng** [comment]
Welcome on board, and looking forward to more of your contributions.
