### ISSUE TITLE
high priority task cannot preemt low priority task

### ISSUE THREAD

**Issue by nkflash** [volcano-sh/volcano#2547]
https://github.com/volcano-sh/volcano/issues/2232 still exist

1) create one queue, with 3 GPU card in cap.(this is only one node in cluster which has 8 cards)
2) submit lower priority job which require 2 GPU cards, wait until job running
3) submit higher priority job which require 2 GPU cards,  expect high job running and lower job should evict

result: high priority job pod always pending

config file like:
  volcano-scheduler.conf: |
    actions: "enqueue, reclaim, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enableJobStarving: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
        enableJobEnqueued: false
      - name: nodeorder
      - name: binpack

![image](https://user-images.githubusercontent.com/42488903/197495140-7c6c761d-f144-4763-8a8b-3db510ff24bc.png)

above check incorrect, ssn.Overused only sum current allocated resources.
The logic should like: (current allocated resources + preemptor requested's resource) to check if queue overused

**Comment by william-wang** [comment]
@nkflash I will work on this issue :)

**Comment by jinzhejz** [comment]
hi @nkflash, which version do you use? After PR https://github.com/volcano-sh/volcano/pull/2105, pod could not be preempted by default and need to add annotation `volcano.sh/preemptable=true` to pod to enable preemption.

**Comment by nkflash** [comment]
> hi @nkflash, which version do you use? After PR #2105, pod could not be preempted by default and need to add annotation `volcano.sh/preemptable=true` to pod to enable preemption.

I already set volcano.sh/preemptable=true to enable preemption

**Comment by shmily0000** [comment]
@nkflash Hello friend, I also ran into this problem. Can you give an example of the vcjob you added.

**Comment by nkflash** [comment]
> @nkflash Hello friend, I also ran into this problem. Can you give an example of the vcjob you added.

See below comment

**Comment by shmily0000** [comment]
@nkflash OK, thank you brother, but the vcjob I tested myself still doesn't seem to work. The scheduler uses your configuration, the node is 8cpu, and the following is my configuration, which seems to be consistent with the po template you provided. I'm a bit troubled here. Can you help me to check whether the configuration is wrong
low priority job：
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-1
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: low
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        metadata:
          annotations:
            volcano.sh/preemptable: "true"
        spec:
          containers:
            - command:
              - sleep
              - 120m
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 6
                limits:
                  cpu: 6
          restartPolicy: Never
high priority job：
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: job-preempt
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 1
      name: nginx
      policies:
      - event: TaskCompleted
        action: CompleteJob
      template:
        metadata:
          annotations:
            volcano.sh/preemptable: "true"
        spec:
          containers:
            - command:
              - sleep
              - 120m
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                requests:
                  cpu: 6
                limits:
                  cpu: 6
          restartPolicy: Never

Is there any other operation here？ Thanks a lot

**Comment by nkflash** [comment]
> @nkflash OK, thank you brother, but the vcjob I tested myself still doesn't seem to work. The scheduler uses your configuration, the node is 8cpu, and the following is my configuration, which seems to be consistent with the po template you provided. I'm a bit troubled here. Can you help me to check whether the configuration is wrong low priority job： apiVersion: batch.volcano.sh/v1alpha1 kind: Job metadata: name: job-1 spec: minAvailable: 1 schedulerName: volcano priorityClassName: low policies: - event: PodEvicted action: RestartJob tasks: - replicas: 1 name: nginx policies: - event: TaskCompleted action: CompleteJob template: metadata: annotations: volcano.sh/preemptable: "true" spec: containers: - command: - sleep - 120m image: nginx:latest imagePullPolicy: IfNotPresent name: nginx resources: requests: cpu: 6 limits: cpu: 6 restartPolicy: Never high priority job： apiVersion: batch.volcano.sh/v1alpha1 kind: Job metadata: name: job-preempt spec: minAvailable: 1 schedulerName: volcano priorityClassName: high policies: - event: PodEvicted action: RestartJob tasks: - replicas: 1 name: nginx policies: - event: TaskCompleted action: CompleteJob template: metadata: annotations: volcano.sh/preemptable: "true" spec: containers: - command: - sleep - 120m image: nginx:latest imagePullPolicy: IfNotPresent name: nginx resources: requests: cpu: 6 limits: cpu: 6 restartPolicy: Never
> 
> Is there any other operation here？ Thanks a lot

need config scheduler like:
actions: "enqueue, reclaim, allocate, preempt, backfill"
tiers:
- plugins:
- name: priority
- name: gang
enableJobStarving: false
- name: conformance
- plugins:
- name: overcommit
- name: drf
- name: predicates
- name: proportion
enableJobEnqueued: false
- name: nodeorder
- name: binpack

**Comment by shmily0000** [comment]
@nkflash OK, my friend, but it seems that the configuration of these two arguments still does not take effect
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, reclaim, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enableJobStarving: false
        enableReclaimable: false
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
      - name: predicates
      - name: proportion
        enableJobEnqueued: false
      - name: nodeorder
      - name: binpack
kind: ConfigMap

In this case, the podgroup of my high priority vcjob will report that resource in cluster is overridden, but will not stop the low priority vcjob to seize resources.

**Comment by nkflash** [comment]
> @nkflash OK, my friend, but it seems that the configuration of these two arguments still does not take effect apiVersion: v1 data: volcano-scheduler.conf: | actions: "enqueue, reclaim, allocate, preempt, backfill" tiers: - plugins: - name: priority - name: gang enableJobStarving: false enableReclaimable: false enablePreemptable: false - name: conformance - plugins: - name: overcommit - name: drf - name: predicates - name: proportion enableJobEnqueued: false - name: nodeorder - name: binpack kind: ConfigMap
> 
> In this case, the podgroup of my high priority vcjob will report that resource in cluster is overridden, but will not stop the low priority vcjob to seize resources.

It due to this bug. For current code, only low priority job occupy resources more then queue weight, then high job could preempt low job.

**Comment by shmily0000** [comment]
@nkflash OK, my friend, that means that if the weight of the two queues is 1 and there are 8 CPUs in total, the low priority jobs occupy more than 4 CPUs. Can I create a high priority job to preempt? Let me try

**Comment by nkflash** [comment]
> @nkflash OK, my friend, that means that if the weight of the two queues is 1 and there are 8 CPUs in total, the low priority jobs occupy more than 4 CPUs. Can I create a high priority job to preempt? Let me try

yes

**Comment by shmily0000** [comment]
@nkflash Thank you very much, my friend. It's OK to try this just now, but under this configuration (the weight of the 8 cpu queue is one-to-one), the first five 1 cpus are running a high priority 3 cpus, and the high priority will suspend the fifth job. If you run a job in another queue later, will your recycle there take effect. I tried this. It seems that the job is still running and will not recycle resources.

**Comment by nkflash** [comment]
> your recycle there tak

sure, it will take effect(you need config reclaimable: true in each queue)

**Comment by shmily0000** [comment]
@nkflash OK,thank you， my friend, this recyclable file is enabled in the queue. The configuration is the same as the previous configuration, but it is not really recycled. It seems that the previous volcano document only needs to configure this and recycling action. Here are my two queues.

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"name":"test"},"spec":{"reclaimable":true,"weight":1}}
  creationTimestamp: "2022-11-01T03:04:22Z"
  generation: 1
  name: test
  resourceVersion: "704753"
  uid: 629a64ee-5fff-4fe0-bcbd-af59ffd94eda
spec:
  reclaimable: true
  weight: 1

apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  creationTimestamp: "2022-06-22T03:40:40Z"
  generation: 1
  name: default
  resourceVersion: "704629"
  uid: 913a6529-c52a-4fd3-aaa2-d1eb3a714a69
spec:
  guarantee: {}
  reclaimable: true
  weight: 1

**Comment by nkflash** [comment]
> @nkflash OK,thank you， my friend, this recyclable file is enabled in the queue. The configuration is the same as the previous configuration, but it is not really recycled. It seems that the previous volcano document only needs to configure this and recycling action. Here are my two queues.
> 
> apiVersion: scheduling.volcano.sh/v1beta1 kind: Queue metadata: annotations: kubectl.kubernetes.io/last-applied-configuration: | {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"name":"test"},"spec":{"reclaimable":true,"weight":1}} creationTimestamp: "2022-11-01T03:04:22Z" generation: 1 name: test resourceVersion: "704753" uid: 629a64ee-5fff-4fe0-bcbd-af59ffd94eda spec: reclaimable: true weight: 1
> 
> apiVersion: scheduling.volcano.sh/v1beta1 kind: Queue metadata: creationTimestamp: "2022-06-22T03:40:40Z" generation: 1 name: default resourceVersion: "704629" uid: 913a6529-c52a-4fd3-aaa2-d1eb3a714a69 spec: guarantee: {} reclaimable: true weight: 1

Not sure which part is incorrect, the same conf work on my env....
Maybe another bug...

**Comment by shmily0000** [comment]
@nkflash OK, friend, I'll go to see if there are other solutions for this. Thank you very much

**Comment by shmily0000** [comment]
@nkflash hi，friend,
Just now, I tried to reclaim. There was a 3cpu and a 2cpu job in the default queue with a weight of one to one, so one queue was 4CPU, and the other queue was 2CPU. After the recycle was triggered, all the jobs in the original default queue were pending. I felt a little strange. I should not recycle one. In addition, after a period of time, the vcjob that executes the recycle action will become a failed status, saying that it is difficult to create a podgroup again

**Comment by jinzhejz** [comment]
@nkflash I will work on this issue, thanks

**Comment by william-wang** [comment]
@jinzhejz any update on this?

**Comment by nkflash** [comment]
> 

Do you use my config?
name: gang
enableJobStarving: false
enableReclaimable: false
enablePreemptable: false

name: proportion
enableJobEnqueued: false

For noe  only low priority job occupy resources more than queue weight, then high job could preempt low job.
If the low priority job used resource lower than weight, the high priority job submit to cluster can not schedule(preempt lower job), due to the code which I post.

**Comment by wangyang0616** [comment]
Retain the current issue.
/remove-lifecycle stale

**Comment by Monokaix** [comment]
Fixed by https://github.com/volcano-sh/volcano/pull/3230
