### ISSUE TITLE
recommend: Remove bot that checks issue and PR for staleness.

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#2569]
Problems don't go away automatically, and I think we close too many pending problems.
@william-wang @jiangkaihua @shinytang6

**Comment by william-wang** [comment]
It make sense, Let me try whether we can change to a longer time for staleness.

**Comment by hwdef** [comment]
This issue still needs to be taken into consideration.
Black humorously, this issue is also going to be closed by CI.
