### ISSUE TITLE
Add `allocated` field in queue status to indicate allocated resources of queue.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#2571]
#### What would you like to be added:
- a new filed in `queue.status` called `allocated`, which indicated already allocated resources in a queue, like:

```shell
    "status": {
        "allocated": {
            "cpu": "3",
            "ephemeral-storage": "6442450944",
            "memory": "600Mi"
        },
        "reservation": {},
        "running": 1,
        "state": "Open"
    }
```

#### Why is this needed:

- In our scenario, volcano queue was involved in to split manage cluster resources. We configure `Capability` field to restrict the upper limit of each queue, a hard restriction according to which we cloud calculate cost allocation. But in some cases, we did not know whether should we apply workload to one queue, because we were unaware of allocated resources in the queue and idle resources left within `Capability`, causing jobs pending and autoScaler enlarge the cluster meaninglessly.

- So we want to add a new field `Allocated` in `queue.Status`, so that we can watch allocated resources in a queue, and apply jobs according used resources.

**Comment by wangyang0616** [comment]
The PR corresponding to the current issue has been incorporated into the main line. I understand that this issue can be closed, right? @jiangkaihua
