### ISSUE TITLE
【function】Request a new feature suggestion

### ISSUE THREAD

**Issue by cubxxw** [volcano-sh/volcano#2578]
I know volcano is based on kubernetes, but I'm curious if it supports the lighter k3s. I'd like to be able to build it on top of k3s, but there's no good solution🎉 @holdenk

**Comment by hwdef** [comment]
Doesn't it work on k3s now?

**Comment by william-wang** [comment]
@cubxxw You can have a try, Volcano should support k3s right now idealy. If anything working wrong on k3s, please file issue here :)
