### ISSUE TITLE
Add Event Handler for RS to GC Podgroup. New Solution to Fix Issue 2143

### ISSUE THREAD

**Issue by RamezesDong** [volcano-sh/volcano#2585]
#### What would you like to be added:
For issue #2143  when deployment update, it will create new replicaset and volcano controller will create new podgroup for replicaset. After several times update, the Deployment has many Inqueue podgroups.  A new solution that is different from [Enhance Generate PodGroup OwnerReferences for Normal Pod](https://github.com/volcano-sh/volcano/blob/master/docs/design/Enhance-Generate-PodGroup-OwnerReferences-for-Normal-Pod.md#enhance-generate-podgroup-ownerreferences-for-normal-pod), add an event handler for rs to `gc` podgroup when rs' replicas set to zero.
#### Why is this needed:
One solution to this problem is #2151 , which change the `ownerReference` of podgroup from rs to deployment. We develop a hack version of this solution, but some problems still exist. When deployment's replicas are set to zero, the podgroup has alive still! So, this solution is incomplete and ugly to design. 

Overall, We think that it is the clear and easy-to-understand solution to add event handler for rs.

**Comment by bysph** [comment]
@RamezesDong  Hello, I noticed that the newly created pod group phase will be "Completed" after this modification(originally "Running"). Is this expected behavior?

**Comment by bysph** [comment]
> @RamezesDong Hello, I noticed that the newly created pod group phase will be "Completed" after this modification(originally "Running"). Is this expected behavior?

This will effect the result of e2e test case
