### ISSUE TITLE
Add hosts list into environment

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#260]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

In `svc` plugin, we only provide host files in `/etc/volcano`, and user has to translate those files in to a list of hosts as arguments. It's better to include such an env in all pods of job.

**Comment by thandayuthapani** [comment]
@k82cn If my understanding is correct, if there are multiple .host files for a job, we have to export multiple environment variables respective to each .host file?

**Comment by k82cn** [comment]
yes
