### ISSUE TITLE
Enable COVERALLS for Volcano

### ISSUE THREAD

**Issue by asifdxtreme** [volcano-sh/volcano#261]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Volcano needs to show the coverage report for each PR 

**What you expected to happen**:
COVERALLS should be enabled for Volcano repo(only admins of the repo can enable this)
**How to reproduce it (as minimally and precisely as possible)**:
1. Go to https://coveralls.io/ and login using github credentials
2. Go to https://coveralls.io/repos/new and sync repository list
3. Search for Volcano repo and enable the coverage report for Volcano.

**Comment by k82cn** [comment]
> Search for Volcano repo and enable the coverage report for Volcano.

I already give the permission, but I can not find volcano-sh :( let's try others.

**Comment by asifdxtreme** [comment]
The coveralls has been enabled for this repo now https://coveralls.io/github/volcano-sh/volcano

**Comment by hzxuzhonghu** [comment]
@asifdxtreme @k82cn The https://coveralls.io/ website id down, which blocks volcano pr merge.

Can we skip coverage temporarily?
