### ISSUE TITLE
JobInfo.GetMinResources cannot return extended resources

### ISSUE THREAD

**Issue by stingshen** [volcano-sh/volcano#2615]
**What happened**:

JobInfo.GetMinResources cannot return extended resources.

**What you expected to happen**:

JobInfo.GetMinResources can return extended resources such as nvidia.com/gpu

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable proportion plugin and start volcano scheduler.
2. Create a vcjob with extended resources, such as nvidia.com/gpu.
3. JobInfo.GetMinResources can't return nvidia.com/gpu.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`): 1.25.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15.0-56-generic
- Install tools:
- Others:

**Comment by stingshen** [comment]
> Some do not understand the place want to ask, this to the user performance on the main impact is what aspect.
> 
> During task scheduling, the portion cannot perform enqueue interception on jobs whose usage of extended resources exceeds the upper limit. Is it correct?

Yes. Proportion plugin attr.inqueue doesn't count ERs.

**Comment by stingshen** [comment]
> Is it the same problem as [#2564](https://github.com/volcano-sh/volcano/issues/2564)?

The problem is related but not the same. The problem described in issue is about the return value of `JobInfo.GetMinResources()`, and the problem described in #2564 is about quota calculation.

**Comment by hwdef** [comment]
still need

**Comment by stingshen** [comment]
fixed
