### ISSUE TITLE
Support multiple events in lifecycle policy

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#266]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, `spec.policy` only support one event or `*` which is not enough. It's better to support an event list for it. It need to handle conflict, but duplication is not necessary to me.

**Comment by asifdxtreme** [comment]
@k82cn the related PR's for this feature has been merged, Can we go ahead and close this issue?
