### ISSUE TITLE
Enhancement volcano's reschedule support multi metrics system

### ISSUE THREAD

**Issue by Shoothzj** [volcano-sh/volcano#2679]
Hello, community. 

I would like to propose an improvement for the rescheduling plugin in Volcano. At present, the rescheduling capability of Volcano only supports Prometheus, which poses some limitations. In order to allow users to utilize other metrics systems with Volcano's rescheduling feature, we can enhance the plugin to support additional systems by extracting proper interfaces and making it easier for users to adapt to their own private systems.

The proposed solution involves three steps:

- [x] Extraction of proper interfaces to decouple the metrics system.

- [x] Introduction of a "metrics.type" field that represents different metrics systems, such as Prometheus, Elasticsearch, and Influx.

- [x] Priority will be given to implementing the most popular metrics systems first, including Elasticsearch and Prometheus.

Any feedback or reply would be greatly appreciated. Thank you!

**Comment by william-wang** [comment]
It's great to support volcano to work with more popular metrics system and make scheduling decision. Please move forward and It's better to start from a design doc :)
