### ISSUE TITLE
JobStatus still running when the pod is pending

### ISSUE THREAD

**Issue by helloxjade** [volcano-sh/volcano#2684]
**What happened**:
I submitted a volcano job with only one pod, the pod's status is pending, the minavaliable is 1, but the vj's status is Running

**What you expected to happen**:
when the pod's num less than minavalable, the vj's status should not be running

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:  v1.4.0
- Kubernetes version (use `kubectl version`):  v1.19
- Cloud provider or hardware configuration:  
- OS (e.g. from /etc/os-release):    CentOS Linux release 7.6.1810
- Kernel (e.g. `uname -a`):  x86_64
- Install tools:
- Others:

**Comment by helloxjade** [comment]
status:
  controlledResources:
    plugin-env: env
  minAvailable: 1
  pending: 1
  state:
    lastTransitionTime: "2023-02-15T01:01:16Z"
    phase: Running
  taskStatusCount:
    task1:
      phase:
        Pending: 1

**Comment by wangyang0616** [comment]
@helloxjade Is it convenient to provide the yaml file of vcjob, I try to reproduce it locally.

**Comment by helloxjade** [comment]
> 

I  run the volcano job by code, here is the generated yaml , but the image is private.


apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  creationTimestamp: "2023-02-15T01:01:13Z"
  generation: 1
  managedFields:
  - apiVersion: batch.volcano.sh/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:leinao.ai/kind: {}
          f:leinao.ai/ssh-svc: {}
          f:leinao.ai/userid: {}
          f:platform-user: {}
          f:vendor: {}
      f:spec:
        .: {}
        f:minAvailable: {}
        f:plugins:
          .: {}
          f:env: {}
        f:queue: {}
        f:schedulerName: {}
        f:tasks: {}
        f:ttlSecondsAfterFinished: {}
    manager: job-server
    operation: Update
    time: "2023-02-15T01:01:13Z"
  - apiVersion: batch.volcano.sh/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:minAvailable: {}
        f:runningDuration: {}
        f:state:
          .: {}
          f:lastTransitionTime: {}
          f:phase: {}
        f:version: {}
    manager: vc-controller-manager
    operation: Update
    time: "2023-02-17T01:13:38Z"
  name: mmyolo-4034
  namespace: bita-user
  resourceVersion: "165735186"
  selfLink: /apis/batch.volcano.sh/v1alpha1/namespaces/bita-user/jobs/mmyolo-4034
  uid: 321b6186-66bc-4aa9-b94c-1cae50d3df6f
spec:
  maxRetry: 3
  minAvailable: 1
  plugins:
    env: []
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 1
    name: task1
    replicas: 1
    template:
      metadata:
        annotations:
          volcano.sh/task-topology-affinity: task1
          volcano.sh/task-topology-task-order: task1
        creationTimestamp: null
        labels:
          leinao.ai/kind: training
          leinao.ai/userid: bdcd436f48f24848a9e581226de0853b
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: node-role.kubernetes.io/cpu
                  operator: In
                  values:
                  - "true"
              weight: 100
        containers:
        - args:
          - service ssh start && sleep 86400
          command:
          - sh
          - -c
          env:
          - name: NVIDIA_VISIBLE_DEVICES
          - name: CURRENT_VC_TASK_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['volcano.sh/task-spec']
          - name: VC_TASK_NAMES
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['volcano.sh/task-topology-task-order']
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: BASE_URL
            value: /ssh/mmyolo-4034
          image: registry.hub.com:5000/user-images/db_sunju
          imagePullPolicy: Always
          name: task1
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
          volumeMounts:
          - mountPath: /annotation
            name: mount-dataset-0
          - mountPath: /personal
            name: mount-dataset-1
          - mountPath: /data/sunjun/workdir
            name: mount-dataset-2
          - mountPath: /data/sunjun/GeneralHumanAttributeR
            name: mount-dataset-3
          - mountPath: /data/sunjun/GeneralHumanAttribute
            name: mount-dataset-4
          - mountPath: /data/sunjun/Fish
            name: mount-dataset-5
          - mountPath: /output
            name: mount-output
          - mountPath: /root/.ssh/authorized_keys
            name: ln-sunjun
            subPath: authorized_keys
          - mountPath: /dev/shm
            name: mount-share-memory
        imagePullSecrets:
        - name: registry-secret
        nodeSelector:
          kubernetes.io/arch: amd64
          node-role.kubernetes.io/training: "true"
        restartPolicy: Never
        volumes:
        - hostPath:
            path: /annotation
            type: Directory
          name: mount-dataset-0
        - hostPath:
            path: /personal
            type: Directory
          name: mount-dataset-1
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/workdir
            type: Directory
          name: mount-dataset-2
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/GeneralHumanAttributeR
            type: Directory
          name: mount-dataset-3
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/GeneralHumanAttribute
            type: Directory
          name: mount-dataset-4
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/Fish
            type: Directory
          name: mount-dataset-5
        - hostPath:
            path: /projects/bdcd436f48f24848a9e581226de0853b/mmyolo/outputs/65
            type: DirectoryOrCreate
          name: mount-output
        - emptyDir:
            medium: Memory
            sizeLimit: 8Gi
          name: mount-share-memory
        - emptyDir: {}
          name: mount-app
        - name: ln-sunjun
          secret:
            defaultMode: 384
            secretName: ln-sunjun
  ttlSecondsAfterFinished: 604800

**Comment by helloxjade** [comment]
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  creationTimestamp: "2023-02-15T01:01:13Z"
  generation: 1
  managedFields:
  - apiVersion: batch.volcano.sh/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:leinao.ai/kind: {}
          f:leinao.ai/ssh-svc: {}
          f:leinao.ai/userid: {}
          f:platform-user: {}
          f:vendor: {}
      f:spec:
        .: {}
        f:minAvailable: {}
        f:plugins:
          .: {}
          f:env: {}
        f:queue: {}
        f:schedulerName: {}
        f:tasks: {}
        f:ttlSecondsAfterFinished: {}
    manager: job-server
    operation: Update
    time: "2023-02-15T01:01:13Z"
  - apiVersion: batch.volcano.sh/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:minAvailable: {}
        f:runningDuration: {}
        f:state:
          .: {}
          f:lastTransitionTime: {}
          f:phase: {}
        f:version: {}
    manager: vc-controller-manager
    operation: Update
    time: "2023-02-17T01:13:38Z"
  name: mmyolo-4034
  namespace: bita-user
  resourceVersion: "165735186"
  selfLink: /apis/batch.volcano.sh/v1alpha1/namespaces/bita-user/jobs/mmyolo-4034
  uid: 321b6186-66bc-4aa9-b94c-1cae50d3df6f
spec:
  maxRetry: 3
  minAvailable: 1
  plugins:
    env: []
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 1
    name: task1
    replicas: 1
    template:
      metadata:
        annotations:
          volcano.sh/task-topology-affinity: task1
          volcano.sh/task-topology-task-order: task1
        creationTimestamp: null
        labels:
          leinao.ai/kind: training
          leinao.ai/userid: bdcd436f48f24848a9e581226de0853b
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: node-role.kubernetes.io/cpu
                  operator: In
                  values:
                  - "true"
              weight: 100
        containers:
        - args:
          - service ssh start && sleep 86400
          command:
          - sh
          - -c
          env:
          - name: NVIDIA_VISIBLE_DEVICES
          - name: CURRENT_VC_TASK_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['volcano.sh/task-spec']
          - name: VC_TASK_NAMES
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['volcano.sh/task-topology-task-order']
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: BASE_URL
            value: /ssh/mmyolo-4034
          image: registry.hub.com:5000/user-images/db_sunju
          imagePullPolicy: Always
          name: task1
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
          volumeMounts:
          - mountPath: /annotation
            name: mount-dataset-0
          - mountPath: /personal
            name: mount-dataset-1
          - mountPath: /data/sunjun/workdir
            name: mount-dataset-2
          - mountPath: /data/sunjun/GeneralHumanAttributeR
            name: mount-dataset-3
          - mountPath: /data/sunjun/GeneralHumanAttribute
            name: mount-dataset-4
          - mountPath: /data/sunjun/Fish
            name: mount-dataset-5
          - mountPath: /output
            name: mount-output
          - mountPath: /root/.ssh/authorized_keys
            name: ln-sunjun
            subPath: authorized_keys
          - mountPath: /dev/shm
            name: mount-share-memory
        imagePullSecrets:
        - name: registry-secret
        nodeSelector:
          kubernetes.io/arch: amd64
          node-role.kubernetes.io/training: "true"
        restartPolicy: Never
        volumes:
        - hostPath:
            path: /annotation
            type: Directory
          name: mount-dataset-0
        - hostPath:
            path: /personal
            type: Directory
          name: mount-dataset-1
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/workdir
            type: Directory
          name: mount-dataset-2
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/GeneralHumanAttributeR
            type: Directory
          name: mount-dataset-3
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/GeneralHumanAttribute
            type: Directory
          name: mount-dataset-4
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/Fish
            type: Directory
          name: mount-dataset-5
        - hostPath:
            path: /projects/bdcd436f48f24848a9e581226de0853b/mmyolo/outputs/65
            type: DirectoryOrCreate
          name: mount-output
        - emptyDir:
            medium: Memory
            sizeLimit: 8Gi
          name: mount-share-memory
        - emptyDir: {}
          name: mount-app
        - name: ln-sunjun
          secret:
            defaultMode: 384
            secretName: ln-sunjun
  ttlSecondsAfterFinished: 604800

**Comment by helloxjade** [comment]
> @helloxjade Is it convenient to provide the yaml file of vcjob, I try to reproduce it locally.

I run the job by code, this is the generated yanl, you need to remov sth to run it again, and the image is private, you can update 

`apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  creationTimestamp: "2023-02-15T01:01:13Z"
  generation: 1
  managedFields:
  - apiVersion: batch.volcano.sh/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:leinao.ai/kind: {}
          f:leinao.ai/ssh-svc: {}
          f:leinao.ai/userid: {}
          f:platform-user: {}
          f:vendor: {}
      f:spec:
        .: {}
        f:minAvailable: {}
        f:plugins:
          .: {}
          f:env: {}
        f:queue: {}
        f:schedulerName: {}
        f:tasks: {}
        f:ttlSecondsAfterFinished: {}
    manager: job-server
    operation: Update
    time: "2023-02-15T01:01:13Z"
  - apiVersion: batch.volcano.sh/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:minAvailable: {}
        f:runningDuration: {}
        f:state:
          .: {}
          f:lastTransitionTime: {}
          f:phase: {}
        f:version: {}
    manager: vc-controller-manager
    operation: Update
    time: "2023-02-17T01:13:38Z"
  name: mmyolo-4034
  namespace: bita-user
  resourceVersion: "165735186"
  selfLink: /apis/batch.volcano.sh/v1alpha1/namespaces/bita-user/jobs/mmyolo-4034
  uid: 321b6186-66bc-4aa9-b94c-1cae50d3df6f
spec:
  maxRetry: 3
  minAvailable: 1
  plugins:
    env: []
  queue: default
  schedulerName: volcano
  tasks:
  - maxRetry: 3
    minAvailable: 1
    name: task1
    replicas: 1
    template:
      metadata:
        annotations:
          volcano.sh/task-topology-affinity: task1
          volcano.sh/task-topology-task-order: task1
        creationTimestamp: null
        labels:
          leinao.ai/kind: training
          leinao.ai/userid: bdcd436f48f24848a9e581226de0853b
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: node-role.kubernetes.io/cpu
                  operator: In
                  values:
                  - "true"
              weight: 100
        containers:
        - args:
          - service ssh start && sleep 86400
          command:
          - sh
          - -c
          env:
          - name: NVIDIA_VISIBLE_DEVICES
          - name: CURRENT_VC_TASK_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['volcano.sh/task-spec']
          - name: VC_TASK_NAMES
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['volcano.sh/task-topology-task-order']
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: BASE_URL
            value: /ssh/mmyolo-4034
          image: registry.hub.com:5000/user-images/db_sunju
          imagePullPolicy: Always
          name: task1
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
          volumeMounts:
          - mountPath: /annotation
            name: mount-dataset-0
          - mountPath: /personal
            name: mount-dataset-1
          - mountPath: /data/sunjun/workdir
            name: mount-dataset-2
          - mountPath: /data/sunjun/GeneralHumanAttributeR
            name: mount-dataset-3
          - mountPath: /data/sunjun/GeneralHumanAttribute
            name: mount-dataset-4
          - mountPath: /data/sunjun/Fish
            name: mount-dataset-5
          - mountPath: /output
            name: mount-output
          - mountPath: /root/.ssh/authorized_keys
            name: ln-sunjun
            subPath: authorized_keys
          - mountPath: /dev/shm
            name: mount-share-memory
        imagePullSecrets:
        - name: registry-secret
        nodeSelector:
          kubernetes.io/arch: amd64
          node-role.kubernetes.io/training: "true"
        restartPolicy: Never
        volumes:
        - hostPath:
            path: /annotation
            type: Directory
          name: mount-dataset-0
        - hostPath:
            path: /personal
            type: Directory
          name: mount-dataset-1
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/workdir
            type: Directory
          name: mount-dataset-2
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/GeneralHumanAttributeR
            type: Directory
          name: mount-dataset-3
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/GeneralHumanAttribute
            type: Directory
          name: mount-dataset-4
        - hostPath:
            path: /datasets/bdcd436f48f24848a9e581226de0853b/Fish
            type: Directory
          name: mount-dataset-5
        - hostPath:
            path: /projects/bdcd436f48f24848a9e581226de0853b/mmyolo/outputs/65
            type: DirectoryOrCreate
          name: mount-output
        - emptyDir:
            medium: Memory
            sizeLimit: 8Gi
          name: mount-share-memory
        - emptyDir: {}
          name: mount-app
        - name: ln-sunjun
          secret:
            defaultMode: 384
            secretName: ln-sunjun
  ttlSecondsAfterFinished: 604800
`

**Comment by helloxjade** [comment]
> @helloxjade Is it convenient to provide the yaml file of vcjob, I try to reproduce it locally.

I accidentally closed the issue.

**Comment by wangyang0616** [comment]
I have tried many times locally with volcano 1.4 and kubernetes v1.19, but the problem has not been reproduced. Can you help me provide more information to analyze the problem.

- Whether the current problem is inevitable or occasional
- The problem occurred directly when the vcjob was created, or did operations such as restart, preemption, and eviction occur in the middle of the pod
- Is the pod not yet scheduled, or has it been scheduled to the node, but it is not started on the node?

Happy to hear from you.
