### ISSUE TITLE
Status of Jobs pods can become "OutOfCpu" when many pods are created and completed in a short time on the same node schedule by batch.volcano.sh/v1alpha1.

### ISSUE THREAD

**Issue by GEEKZX** [volcano-sh/volcano#2700]
What happened?
Status of pods can become "OutOfCpu" when many jobs are created and completed in a short time on the same node schedule by batch.volcano.sh/v1alpha1.

What did you expect to happen?
Status of pods should become "Running", "Pending" or "Completed". When node resources are not satisfied, The jobs pods should not be scheduled.

Anything else we need to know?
We found this issue in volcano v1.7.0   k8s version v1.23.15
Pods QoS is Burstable
Error message: 
              status:
                message: 'Pod Node didn''t have enough resource: cpu, requested: 56033, used: 34036, capacity: 90000'
                phase: Failed
                reason: OutOfcpu
**Environment**:
- Volcano Version:  v1.7.0
- Kubernetes version (use `kubectl version`): v1.23.15
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS
- Kernel (e.g. `uname -a`):Linux k8s-master 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by wangyang0616** [comment]
Looking at the log description, the sum of requested and used exceeds the capacity. 

In our system, only the volcano is scheduling tasks, or are both the volcano and kube-scheduler scheduling their own tasks? Is it possible that in a scheduling cycle, the two schedulers At the same time, the task is scheduled to be changed to the node node, causing the node to apply for resources exceeding the upper limit.

By the way, do we have a pod on a node in the OutOfcpu state, or are multiple pods in this error state?

**Comment by wangyang0616** [comment]
It would be better if you can provide the log information of the volcano-scheduler, we will be able to troubleshoot the problem more easily, thanks @GEEKZX

**Comment by GEEKZX** [comment]
We found no scheduling logs in pod kube-scheduler-k8s-master, all tasks is scheduling by volcano in our Cluster ,  we have 40 node , when we submit 5000 job at the same time, a small amount pod can become "OutOfCpu" distributed on different nodes

**Comment by lowang-bh** [comment]
This is usually caused by multiple schedulers, eg, kube-scheduler and volcano, and both of them scheduling a pod to the same node, and kubelet finds that the resource is not enough and events a "outOfCpu" or "OutOfMemeory". Usually, we need a coordinate to solve this problem .

**Comment by hwdef** [comment]
keep activate
