### ISSUE TITLE
volcano support another GPU sharing scheme: mGPU(https://www.volcengine.com/docs/6419/145065)

### ISSUE THREAD

**Issue by fjding** [volcano-sh/volcano#2711]
#### What would you like to be added:
Hi, In cloud-native environments, volcano has become the standard for batch scheduling, more and more cloud users use volcano as a batch scheduler in ByteDance Volcano Engine, But the GPU sharing scheme (mGPU) of Volcano Engine does not match the Volcano scheduler GPU scheme. We want to raise a PR to let the Volcano scheduler support ByteDance Volcano Engine mGPU scheduling. In this way, users of the volcano engine can directly use the mGPU scheduling capability after installing volcano scheduler.

mGPU Link: https://www.volcengine.com/docs/6419/145065

**Comment by hwdef** [comment]
What work needs to be done to adapt mgpu?

Currently, Volcano's support for GPUs is already scalable. Please see if the current design can meet the demand

https://github.com/volcano-sh/volcano/pull/2643

**Comment by fjding** [comment]
Thanks for you replay，the device api is well designed，I think this device api can satisfy the expansion of mgpu schedule. The implementation of mgpu is different from the nvida gpushare currently volcano supported, so I want to confirm two issues:
1. When will the official version of this device api be released?
2. If we extend the mgpu, we will create a directory named pkg/scheduler/api/devices/mgpu/gpushare. After our development is completed, can it be merged into the master branch of volcano and released as a GA version?

**Comment by hwdef** [comment]
> Thanks for you replay，the device api is well designed，I think this device api can satisfy the expansion of mgpu schedule. The implementation of mgpu is different from the nvida gpushare currently volcano supported, so I want to confirm two issues:
> 
>     1. When will the official version of this device api be released?
> 
>     2. If we extend the mgpu, we will create a directory named pkg/scheduler/api/devices/mgpu/gpushare. After our development is completed, can it be merged into the master branch of volcano and released as a GA version?

1. If there is no accident, it will be three months after the release of version 1.7, that is, in April.
2. This requires the maintainer to make a decision.

**Comment by fjding** [comment]
Can this issue be discussed at the weekly meeting?
Who can I contact for help?

**Comment by hwdef** [comment]
@wangyang0616 
Can you offer any help?

**Comment by hwdef** [comment]
could you please offer an email or wechat?

**Comment by fjding** [comment]
> could you please offer an email or wechat?

Thanks，My wechat id：fj_ding

**Comment by wangyang0616** [comment]
> Can this issue be discussed at the weekly meeting? Who can I contact for help?

Please provide some help, thanks!  @william-wang @archlitchi

**Comment by wangyang0616** [comment]
> 1. If there is no accident, it will be three months after the release of version 1.7, that is, in April.
I agree with @hwdef , the community plans to release the v1.8 version in April, and will release this part of the function

> 2. This requires the maintainer to make a decision.
Please provide some help, thanks! @william-wang @archlitchi
