### ISSUE TITLE
Task topology

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#272]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

When high performance workload running on Kubernetes, the performance is greatly affected by pod affinity/anti-affinity, e.g. ps/worker mode of Tensorflow. The default scheduler support pod affinity/anti-affinity, but there're some weaknesses:

- The default scheduler will check PodAffinity/PodAntiAffinity against all running pods which impacts schedule performance/throughput
- The default scheduler only check current pod, the coming pods may not have enough resources to meet affinity

Reference:

- [Optimus: An Efficient Dynamic Resource Scheduler for Deep Learning Clusters](https://dl.acm.org/citation.cfm?id=3190517)
- [Pod Affinity and anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)

**Comment by gaocegege** [comment]
Yeah, I know there are some disadvantages. And it is the reason for me to have a try on volcano scheduler.

I'd appreciate it if you have a proposal to improve it

Thanks :clinking_glasses: :beers:

**Comment by hzxuzhonghu** [comment]
move this feature to 0.3
