### ISSUE TITLE
please provide k8s version vs volcano version

### ISSUE THREAD

**Issue by lightnine** [volcano-sh/volcano#2725]
#### What would you like to be added:
can you provide the relationship between k8s version and volcano version, like these
```
k8s version     volcano version
1.16                  >= 1.2
```
#### Why is this needed:
because some volcano versions can not be installing in some k8s version

**Comment by hwdef** [comment]
I did this before, I think it can be improved
https://github.com/volcano-sh/volcano/pull/2370

**Comment by lightnine** [comment]
> 

Thank you and i saw it. But what should i pick vocalno version when the version of k8s is 1.16?

**Comment by hwdef** [comment]
oh, it is too old...i guess it might be 1.0..

**Comment by lightnine** [comment]
> 

ok

**Comment by lowang-bh** [comment]
Have added the version table.

/close
