### ISSUE TITLE
[kubeflow integration] The queue name of generated podgroup is always default

### ISSUE THREAD

**Issue by ckyuto** [volcano-sh/volcano#2744]
**What happened**:
I'm using training-operator 1.5 and volcano 1.7.  I'd like to send my job to the customized queue instead of default. I followed a couple of examples I can search but no matter which queue name I put it is always become default in the generated podgroup. Does anyone know how to set it?

This is my tfjob:
```
apiVersion: v1
items:
- apiVersion: kubeflow.org/v1
  kind: TFJob
  metadata:
    annotations:
      meta.helm.sh/release-name: tfjob-test1
      meta.helm.sh/release-namespace: ns2
    creationTimestamp: "2023-03-20T09:31:06Z"
    generation: 1
    labels:
      app: tfjob
      app.kubernetes.io/managed-by: Helm
      chart: tfjob-0.0.0
      createdBy: TFJob
      xxxxx/xxxx: tfjob-test1
    name: tfjob-test1
    namespace: ns2
    resourceVersion: "655848"
    uid: 2a5f62e3-1bc5-45cf-b83f-eadf2740c956
  spec:
    runPolicy:
      cleanPodPolicy: Running
      schedulingPolicy:
        priorityClass: test-priorityClass
        queue: queue2
    tfReplicaSpecs:
      Worker:
        replicas: 1
        template:
          metadata:
            annotations:
              xx: xxxx
            labels:
              xxx: xxx
          spec:
            containers:
            - args:
              - -c
              - sleep 10000
              command:
              - bash
              image: kubeflow/tf-dist-mnist-test:latest
              name: tensorflow
            schedulerName: volcano
            volumes:
            ....
```
And this is the generated podgroup. You can see the queue become default, not queue2.

```
apiVersion: v1
items:
- apiVersion: scheduling.volcano.sh/v1beta1
  kind: PodGroup
  metadata:
    creationTimestamp: "2023-03-20T09:31:06Z"
    generation: 451
    name: podgroup-2a5f62e3-1bc5-45cf-b83f-eadf2740c956
    namespace: ns2
    ownerReferences:
    - apiVersion: kubeflow.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: TFJob
      name: tfjob-test1
      uid: 2a5f62e3-1bc5-45cf-b83f-eadf2740c956
    resourceVersion: "671735"
    uid: 38a4b76b-2345-41b5-b8d4-64e4c3990e7d
  spec:
    minMember: 1
    minResources:
      count/pods: "1"
      pods: "1"
    queue: default
  status:
    conditions:
    - lastTransitionTime: "2023-03-20T17:43:33Z"
      reason: tasks in gang are ready to be scheduled
      status: "True"
      transitionID: ccbb1774-f7e9-407f-8a35-9e498868d9f6
      type: Scheduled
    phase: Running
    succeeded: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**What you expected to happen**:
The value of the queue of the generated podgroup should be the one I specified.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.7
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: training-operator: 1.5
- Others:

**Comment by ameya-parab** [comment]
@ckyuto - how was this resolved?
