### ISSUE TITLE
Publish Volcano's chart package on Artifact Hub

### ISSUE THREAD

**Issue by wangyang0616** [volcano-sh/volcano#2763]
#### What would you like to be added:
Publish Volcano's chart package on Artifact Hub, users can directly retrieve and install Volcano through the helm command.

#### Why is this needed:
The current user installs Volcano through helm is too heavy, and needs to download the code before using helm to install.

**Comment by patrungel** [comment]
Is this one still relevant? I could set up publishing.

**Comment by lowang-bh** [comment]
I think this issue can be closed now. Chart is at https://github.com/volcano-sh/helm-charts
