### ISSUE TITLE
Create a Github workflow to publish Helm Charts

### ISSUE THREAD

**Issue by vara-bonthu** [volcano-sh/volcano#2766]
#### What would you like to be added:
- Create a new Github workflow to publish Helm Charts for each release
- Allow users to easily deploy the Helm chart with one command 
- e.g., `helm install --name volcano-release -f values.yaml volcano/volcano`

#### Why is this needed:
- This will make it easy to deploy the Helm Chart either using any IaC tools like Terraform or Argo CD.

**Comment by wangyang0616** [comment]
It's a very worthwhile job and I agree very much.

Can we add this ability when version 1.8 is released ? 
cc @william-wang

**Comment by vara-bonthu** [comment]
Thanks for creating this Helm Chart 🚀 Closing this issue
