### ISSUE TITLE
high priority job of two tasks cannot preempt low priority job of one task

### ISSUE THREAD

**Issue by zhaizhch** [volcano-sh/volcano#2772]
**What happened**:
high priority job of two tasks cannot preempt low priority job of one task

**What you expected to happen**:
higher priority job preempt lower priority job 

**What actually happened**:
high priority job pod is always pending, low priority job pod is always running

**How to reproduce it (as minimally and precisely as possible)**:
1. create one queue. (this is only one node in cluster which has 8 cards)
2. submit lower priority job which has only one task that require 8 GPU, wait until job running
3. submit higher priority job which has two tasks that each one require 2 GPU

**Anything else we need to know?**:
config file like:
volcano-scheduler.conf: |
    actions: "enqueue, reclaim, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enableJobStarving: false
        enableReclaimable: false
        enablePreemptable: false
        enableJobPipelined: true
      - name: conformance
      - name: sla
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
        enableJobEnqueued: false
      - name: nodeorder
      - name: binpack
        arguments:
          binpack.weight: 17
          binpack.cpu: 1
          binpack.memory: 1
          binpack.resources: nvidia.com/gpu, baidu.com/xpu, cambricon.com/mlu
          binpack.resources.nvidia.com/gpu: 5
          binpack.resources.baidu.com/xpu: 5
          binpack.resources.cambricon.com/mlu: 5
**Environment**:
- Volcano Version:
1.6
- Kubernetes version (use `kubectl version`):
1.24.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nkflash** [comment]
@william-wang

**Comment by zhaizhch** [comment]
the higher priority job's master task will preempt the lower priority job's task, and update the preemptee's status to releasing. 
![image](https://user-images.githubusercontent.com/32723829/231050898-349ffb60-9141-4dad-84c7-c2db9efe89ad.png)
the higher priority job's worker task cannot preempt job, because the preemptee is empty(because the lower priority task's status is releasing, seted by first step ).
![image](https://user-images.githubusercontent.com/32723829/231051306-79890378-3ac3-485e-a6a4-a07ed0257490.png)
the higher job is not jobPipeLined (plugin gang), so can't commit the evict.
![image](https://user-images.githubusercontent.com/32723829/231051525-7abca89d-2cde-4b6e-a002-1170cd4900ec.png)

**Comment by wangyang0616** [comment]
victim is empty here, resulting in the second task scheduling of the high-priority job, not finding the corresponding preempted person, and exiting, resulting in the overall preemption failure.
https://github.com/volcano-sh/volcano/blob/bed4a044b5f931fcb566b7ccbe2292207f7db346/pkg/scheduler/util/scheduler_helper.go#L175-L177

Even if the victim here is empty, it should continue to run. As I wrote in the comment information submitted in the PR, the first round of expulsion of a large task (CPU: 8) may satisfy multiple tasks (CPU: 2) Scheduling

**Comment by wangyang0616** [comment]
@zhaizhch You can use my PR to verify, if there are still problems, we can continue to discuss.

**Comment by LivingCcj** [comment]
we also meet the same problem. The preemtor task will  give up the node  with no victims, even if the node has enough resources to place the task，the [PR 2775](https://github.com/volcano-sh/volcano/pull/2775) solved the problem very well.
