### ISSUE TITLE
Any good first issue for new contributors?

### ISSUE THREAD

**Issue by halegreen** [volcano-sh/volcano#2789]
#### What would you like to be added:
label for `good first issue` is empty,  is there any issue for new contributors to begin with ? 

#### Why is this needed:
any issue for new contributors to begin with

**Comment by lowang-bh** [comment]
There are some words spelling errors in comments, and also some ambiguous variable name in code.  I think you can start with fixing it.

**Comment by Monokaix** [comment]
`good first issue` has been added, you can filter issues by choose this selector.
