### ISSUE TITLE
[question] Why not update task role's min member to its replicas, but set it to its replicas in creating podgroup?

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2792]
I am not sure this is as design or a issue. Can somebody help me to undestand it?

when create new podgroup, if ` task.MinAvailable == nil`, then `minTaskMember[task.Name] = task.Replica`
https://github.com/volcano-sh/volcano/blob/31b47aa9f143e70360dde4f00ceaf6c51ffeb9ab/pkg/controllers/job/job_controller_actions.go#L667

```go
minTaskMember := map[string]int32{}
for _, task := range job.Spec.Tasks {
      if task.MinAvailable != nil {
	      minTaskMember[task.Name] = *task.MinAvailable
      } else {
	      minTaskMember[task.Name] = task.Replicas
      }
}
```

But when updating job,  it skip to set role's  min member when `task.MinAvailable == nil `
https://github.com/volcano-sh/volcano/blob/31b47aa9f143e70360dde4f00ceaf6c51ffeb9ab/pkg/controllers/job/job_controller_actions.go#L721

```go
	if pg.Spec.MinTaskMember == nil {
		pgShouldUpdate = true
		pg.Spec.MinTaskMember = make(map[string]int32)
	}

	for _, task := range job.Spec.Tasks {
		if task.MinAvailable == nil {
			continue
		}
...
	}
```
#### What would you like to be added:

```go
	for _, task := range job.Spec.Tasks {
		cnt := task.Replicas
		if task.MinAvailable != nil {
			cnt = *task.MinAvailable
		} 

		if taskMember, ok := pg.Spec.MinTaskMember[task.Name]; !ok {
			pgShouldUpdate = true
			pg.Spec.MinTaskMember[task.Name] = cnt
		} else {
			if taskMember == cnt{
				continue
			}

			pgShouldUpdate = true
			pg.Spec.MinTaskMember[task.Name] = cnt
		}
	}
```

**Comment by wangyang0616** [comment]
I understand your modification is correct.
