### ISSUE TITLE
Wrong Release Date for Volcano 1.7.0 on Website

### ISSUE THREAD

**Issue by gengwg** [volcano-sh/volcano#2795]
**What happened**:

The date for Volcano 1.7.0 release on the website is wrong. It says, Jan 2, 2006. I think it should be some date 2023.

![image](https://user-images.githubusercontent.com/3356786/232235122-e3c987aa-b3cd-4660-bba7-69c04f4a29d3.png)

**What you expected to happen**:

I think it should be some date 2023.

**How to reproduce it (as minimally and precisely as possible)**:

https://volcano.sh/en/blog/volcano-1.7.0-release-en/

**Anything else we need to know?**:

no

**Environment**:
- Volcano Version: This is a problem of your website. Not volcano itself.
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gengwg** [comment]
Turns out its Jan 2, 2006 everywhere. Definitely a bug.

https://volcano.sh/en/blog/ruitian2-en/

![image](https://user-images.githubusercontent.com/3356786/232235351-3326b9a0-feba-4a3c-98c8-3e003c34703e.png)

**Comment by wangyang0616** [comment]
Yes, this is a problem, I have found the original text of the website article see: [Volcano-1.7.0-release-en](https://github.com/volcano-sh/website/blob/master/content/en/blog/Volcano-1.7.0-release-en.md), but I can't find a place where I can set or update the date of the article.

**Comment by wangyang0616** [comment]
associate: [In the official website blog, the time displayed in the article is wrong #302](https://github.com/volcano-sh/website/issues/302)

**Comment by wangyang0616** [comment]
The problem has been fixed, see: [#303](https://github.com/volcano-sh/website/pull/303)

**Comment by gengwg** [comment]
Sorry was busy. Thanks a lot for the fix!

![image](https://user-images.githubusercontent.com/3356786/235594474-272733fd-a8c4-4704-914e-8aecc1740604.png)
