### ISSUE TITLE
feat: add leader election options

### ISSUE THREAD

**Issue by CharlesQQ** [volcano-sh/volcano#2798]
#### What would you like to be added:
`volcano-controller-manager`/`volcano-scheduler`: Introduced `--leader-elect-lease-duration`, `--leader-elect-renew-deadline` and `--leader-elect-retry-period` flags to specify leader election behavious.
#### Why is this needed:
allow user change leader election action

**Comment by lowang-bh** [comment]
`--leader-elect` will enable leader elect.

**Comment by wangyang0616** [comment]
Yes, Volcano currently supports `leader-elect` for election, but it does not provide user-defined related behavior parameters. 

Have you encountered any election-related problems in some scenarios? Can you describe it in detail?

**Comment by CharlesQQ** [comment]
> Volcano currently supports `leader-elect` for election, but it does not provide user-defined related behavior parameters.
> 
> Have you encountered any election-related problems in some scenarios? Can you describe it in detail?
here are volcano default parameters, that means in 10 seconds, master can fetch and update configmap lock 2 times, if after try more than 2 times and still update lock resource failed because of network problems, volcano will changed master; But, We thinks in this scenarios, master process should not exit; so uses hope to defined  `renewDeadline` by themself  may be.
```
	leaseDuration = 15 * time.Second
	renewDeadline = 10 * time.Second
	retryPeriod   = 5 * time.Second
```
