### ISSUE TITLE
gomonkey@v2.1.0 doesn't support arm64, need to upgrade to v2.2.0 or higher

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2804]
gomockey `undefined: buildJmpDirective` relative issue has been solved,  FYI:
https://github.com/agiledragon/gomonkey/issues/38
https://github.com/agiledragon/gomonkey/pull/55

**What happened**:
`go test -timeout 30s  -run ^TestSyncJobFunc$ volcano.sh/volcano/pkg/controllers/job`
```text
# github.com/agiledragon/gomonkey/v2
go/src/github.com/volcano/vendor/github.com/agiledragon/gomonkey/v2/patch.go:163:10: undefined: buildJmpDirective
FAIL	volcano.sh/volcano/pkg/controllers/job [build failed]
FAIL
```
**What you expected to happen**:

Succeed to run unit-test

**How to reproduce it (as minimally and precisely as possible)**:
`go test -timeout 30s  -run ^TestSyncJobFunc$ volcano.sh/volcano/pkg/controllers/job`
or `make unit-test`

**Anything else we need to know?**:

Just open code on macbook m1/m2, the lint will tells the error or run `make unit-test` on m1/m2

After upgrade this package, there is another issue `permission denied`,

**Environment**:
- Volcano Version:  master branch
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
see  issue https://github.com/agiledragon/gomonkey/issues/38 and mr https://github.com/agiledragon/gomonkey/pull/55

**Comment by xiefan-github** [comment]
update gomonkey v2.1.0 to v2.2.0
```shell
go test -timeout 30s  -run ^TestSyncJobFunc$ volcano.sh/volcano/pkg/controllers/job
--- FAIL: TestSyncJobFunc (0.00s)
    --- FAIL: TestSyncJobFunc/SyncJob_success_Case (0.00s)
panic: permission denied [recovered]
        panic: permission denied
```

**Comment by lowang-bh** [comment]
> update gomonkey v2.1.0 to v2.2.0
> 
> ```shell
> go test -timeout 30s  -run ^TestSyncJobFunc$ volcano.sh/volcano/pkg/controllers/job
> --- FAIL: TestSyncJobFunc (0.00s)
>     --- FAIL: TestSyncJobFunc/SyncJob_success_Case (0.00s)
> panic: permission denied [recovered]
>         panic: permission denied
> ```

Can not solve this. It has no permit to change darwin's machine instruction. You can run make unit-test in docker.

**Comment by lowang-bh** [comment]
Please check those solutions: 
https://github.com/agiledragon/gomonkey/issues/10
https://github.com/agiledragon/gomonkey/issues/70

**Comment by lowang-bh** [comment]
> update gomonkey v2.1.0 to v2.2.0

@xiefan-github This upgrade solves issue `the buildJmpDirective not support on ARM64` so that it can build successfully.

The permission denied is another issue. I usally run `make unit-test` in a docker on macos to pass this problem.

**Comment by xiefan-github** [comment]
it seems to work for me [sleep 1s ](https://github.com/agiledragon/gomonkey/issues/70#issuecomment-1558475808)

**Comment by lowang-bh** [comment]
> it seems to work for me [sleep 1s ](https://github.com/agiledragon/gomonkey/issues/70#issuecomment-1558475808)

which one ?

**Comment by xiefan-github** [comment]
sorry it has two change, you can get it https://github.com/agiledragon/gomonkey/issues/70#issuecomment-1558475808

**Comment by xiefan-github** [comment]
> I usally run `make unit-test` in a docker on macos to pass this problem.

can you give me a docker command？pls

**Comment by lowang-bh** [comment]
> agiledragon/gomonkey#70 (comment)



> > I usally run `make unit-test` in a docker on macos to pass this problem.
> 
> can you give me a docker command？pls

`docker run --rm -it -v ./:/go/src/volcano.sh/ -w /go/src/volcano.sh/ golang:1.19.4 make unit-test`
