### ISSUE TITLE
auto-scaling queue weight when new nodes scaling up

### ISSUE THREAD

**Issue by zhoushuke** [volcano-sh/volcano#2816]
#### What would you like to be added:
add new nodes to specify queue, auto-scaling queue's weight
 
#### Why is this needed:
thinking about this case, use cpu for example:
theres are 2 nodes(100 cpu per node) in cluster, nodeA with label label-1, another is nodeB with label-2
having two queues, queueA with affinity.require label is nodeA(all  jobs in queueA only run in nodeA), set queueA weight==1(can use 100cpu), the same queueB with affinity.require label is nodeB(only run in nodeB) ,weight==1(can also use 100 cpu).
now add a new nodeC(100 cpu),by default, two weight still 1:1, this will lead two queues can use 150 cpu
if I want to add nodeC to queueA,
 first, I need label nodeC with label-1,but I must update queueA's weight to2 by hand, 
 is there any method to realize： queueA's weight auto-scaling when I set new node's label the same to the queue.affinity , insteading of updating it by hand.

**Comment by wangyang0616** [comment]
The queue divides resources by weight, which is a configuration directly facing users. The weight value of the queue is automatically adjusted through the tagged node information. Personally, I think this may not be a good solution.

**Comment by zhoushuke** [comment]
> 

tks, think about it twice ,it's make sense.
close this issue
