### ISSUE TITLE
[Suggestion] remove those inactive reviewers

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2852]
#### What would you like to be added:

I feel the pr review is so slow, and some reviewers has been inactive months or years.  Is there any rules to clean inactive members/reviewers?

**Comment by xiao-jay** [comment]
You can only become a reviewer if you make more contributions to the volcano project. If you remove him, is it denying their contribution during that time?So I think there is no need to remove the review role as long as  don’t make mistakes.

**Comment by lowang-bh** [comment]
I think anyone  can contribute code at anytime。 But those PRs assign to those inactive reviewers are hung up。
