### ISSUE TITLE
Remove vendor

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#2858]
**What happened**:

**What you expected to happen**:

Down vendor by `go mod` instead of including it in source code.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by william-wang** [comment]
It make sense to remove the vendor now.

**Comment by xiao-jay** [comment]
/assign
I am willing to solve this problem.
