### ISSUE TITLE
Update abbreviation of Volcano from vk-* to vc-*

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#286]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup

**Description**:

Currently, we're using vk as abbreviation of Volcano which is same with 'virtual kubelet'; it's better to use vc as abbreviation of Volcano. 

Or if any other abbreviation suggestion, please share here :)

**Comment by asifdxtreme** [comment]
@k82cn 
what do we do with the exsisting docker images then, do we need to create a new repo for the new docker images?

**Comment by k82cn** [comment]
create new images as vc-controllers, vc-schedulers, vc-admissions; and keep old image there.
