### ISSUE TITLE
Is there a way to get list of in-queued jobs of a queue?

### ISSUE THREAD

**Issue by CZYCW** [volcano-sh/volcano#2900]
Hi Team, I am working on apply volcano scheduler to my Kubeflow training operator. I just wonder whether there is a way to know the list of jobs that are queued by the default queue (through CRD api/cli) ?

The functionality for getting the list of queue jobs could large enhance the user experience for a scheduling system. 

Thank you!

**Comment by hwdef** [comment]
Not yet supported

**Comment by CZYCW** [comment]
Got it. Thank you!

**Comment by Wonki4** [comment]
Excuse me, Any changes about this feature?
