### ISSUE TITLE
kubeflow need contributors to maintain volcano gang-schedule feature

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2903]
#### What would you like to be added:

We need to pay more attentions to some scenario where  volcano is used.

eg: https://github.com/kubeflow/training-operator/issues/1827

**Comment by hwdef** [comment]
Are you interested in doing this, if you don't want to do it, I will do it

**Comment by lowang-bh** [comment]
I am taking it.

**Comment by hwdef** [comment]
> I am working on it, we can coorbrate on adding the e2e test if you want .

I don't think I have much free time, if you can, please do them all.

**Comment by lowang-bh** [comment]
Hi, @hwdef , can you help to review the comments about `volcanoCtl.calculatePGMinResources` at https://github.com/kubeflow/mpi-operator/pull/566/files
