### ISSUE TITLE
vGPU bug

### ISSUE THREAD

**Issue by lengrongfu** [volcano-sh/volcano#2907]
**What happened**:

One of my nodes has a GPU card with 12G video memory. After I installed the device-plugin, I have seen `volcano.sh/vgpu-number=10` in the node. And set `predicate.VGPUEnable=true`.

then exec as follows command:
```
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod12
spec:
  schedulerName: volcano
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          volcano.sh/vgpu-number: 2 # requesting 2 vGPUs
          volcano.sh/vgpu-memory: 2000
          #volcano.sh/vgpu-memory-percentage: 50 #Each vGPU containers 50% device memory of that GPU. Can not be used with nvidia.com/gpumem
    - name: ubuntu-container0
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
    - name: ubuntu-container1
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          volcano.sh/vgpu-number: 2 # requesting 2 vGPUs
          volcano.sh/vgpu-memory: 3000 
EOF
```

`pod` status is `pending`, ` Warning  FailedScheduling  77s   volcano  0/1 nodes are unavailable: 1 no enough gpu cards on node .`

**What you expected to happen**:

Can be running pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: main
- Kubernetes version (use `kubectl version`): 1.25
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
what about kubect describe node shows?

**Comment by archlitchi** [comment]
Because there is only one GPU in your cluster, we can only mount 1 GPU per container, so if your container requests more than 1 GPU, then it can't be scheduled.

**Comment by archlitchi** [comment]
This field declares how many gpu devices can be seen (by nvidia-smi) inside your container. Each gpu device has "vgpu-memory" defined device limit.

**Comment by archlitchi** [comment]
yes, k8s-vgpu-scheduler have implemented this field and can be configured.

**Comment by archlitchi** [comment]
yes, of course
