### ISSUE TITLE
Hi, how can I join the slack channel

### ISSUE THREAD

**Issue by zxcware** [volcano-sh/volcano#2919]
Hi team,

I work at an auto drive startup. We're evaluating systems to manage ML batch job and Volcano is pretty inspiring. How can I join the slack channel so that we can discuss problems and exchange ideas?

Thanks,
Sean

**Comment by hwdef** [comment]
If you are Chinese, you can join the WeChat group.

**Comment by xiao-jay** [comment]
Can you display the WeChat group QR code? I also want to join.

**Comment by hwdef** [comment]
请加微信号 k8s2222，华为云小助手2号，让她拉你入群

**Comment by zhoushuke** [comment]
@hwdef after added k8s2222 for requesting to join, but this account no response.

**Comment by hwdef** [comment]
> @hwdef after added k8s2222 for requesting to join, but this account no response.

When did you add it? Just a moment please

**Comment by xiao-jay** [comment]
@hwdef I will add  this wechat contact information is in readme, This issue maybe can close?

**Comment by hwdef** [comment]
> /assign @hwdef I will add this wechat contact information is in readme, This issue maybe can close?

I agree
