### ISSUE TITLE
default:job-1 unschedule,reason: 1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable

### ISSUE THREAD

**Issue by just-JL** [volcano-sh/volcano#2930]
**What happened**:
when i follow https://volcano.sh/zh/docs/tutorials/ , vcjob status is pending because of default:job-1 unschedule,reason: 1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable. But the podgroup is running. it is confused.
![image](https://github.com/volcano-sh/volcano/assets/31644915/5a8e512e-6c4f-40b8-8fe4-9063d6df87b5)

**What you expected to happen**:
vcjob can running.
**How to reproduce it (as minimally and precisely as possible)**:
just follow https://volcano.sh/zh/docs/tutorials/

**Environment**:
- Volcano Version: v1.7.0
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by TimRazumov** [comment]
@ just-JL hi! How did you solve this problem?

**Comment by googs1025** [comment]
@just-JL  Hi, when you close an issue, if you solved it yourself, you can try to share it or explain the reason before closing the issue, so that others can try your method to solve the problems they encountered ~
