### ISSUE TITLE
CI: E2E Spark Integration Test / E2E about Spark Integration test FAILED

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#2931]
**What happened**:
CI E2E Spark Integration Test / E2E about Spark Integration test always falied.
**What you expected to happen**:
CI can work
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
logs: https://github.com/volcano-sh/volcano/actions/runs/5329115703/jobs/9654474287?pr=2929
**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wangyang0616** [comment]
[#2938](https://github.com/volcano-sh/volcano/pull/2938) has fixed this issue\
/close
