### ISSUE TITLE
OSPP: Supports PDB strategy in preemption and rescheduling scenarios

### ISSUE THREAD

**Issue by wang-mask** [volcano-sh/volcano#2947]
## Background
This is a [2023 Open Source Summer Project](https://summer-ospp.ac.cn/org/prodetail/233ba0295?list=org&navpage=org).

A **PodDisruptionBudget (PDB)** is a Kubernetes resource that allows you to define policies for the disruption of pods during maintenance or other events. It ensures that a certain number or percentage of pods are available at any given time, preventing too many pods from being simultaneously unavailable.

At present, **Volcano directly calls the delete interface when performing pod eviction, without considering the pdb policy set by the task pod, resulting in violations of pdb constraints.**

## Target
Referring to the support for PDB in the official scheduler of K8s, implement a plugin in Volcano that takes into account PDB constraints in **recall, preempt, and shuffle actions**, and prioritizes the expulsion of pods that do not violate the PDB policy or pods that do not violate the PDB policy at all during the preemption process.

## Task
- Write design description
- Development
- Test
- Write use document

**Deadline**: September 30, 2023
**Mentor**: @wangyang0616 
**Student**: @wang-mask
**Related issues**: https://github.com/volcano-sh/volcano/issues/2754

*Further details to be supplemented in the future!*

**Comment by wangyang0616** [comment]
You are welcome to participate in community contributions and look forward to the details of the scheme design.

**Comment by wang-mask** [comment]
Here is the [design doc](https://docs.google.com/document/d/1yWw6QMqofN7meS89_3MjU8zPwtlH9XCI99Q0sYNSWwY/edit?usp=sharing).

**Comment by wang-mask** [comment]
Here is the development [PRs](https://github.com/volcano-sh/volcano/pull/3113).
