### ISSUE TITLE
[suggestion] some suggestions

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2949]
#### What would you like to be added:

1. speed up merging those PRs which don't impact on current logic, such as docs/logs/comments enhancement(eg. #2817). 
2. bug fixes should add additional unittest to cover current changes,  as well as those cases which will fail without current fix
3. each new feature shall be reviewed by at least 2~3 reviewers' LGTM, to avoid domain expertise bias
4. the pending discussions should be solved before merged

#### Why is this needed:
1. encourage new contributors to commit more prs with high passion to continue on committing more, to expand our community. 
2. to prove current fix success and avoid future changes impacting the fix, this should be a standard way.
3. some issues were later on detected after merging, while often it's caused by insufficient review before merging. 
4. when the discussion is pending and not resolved/closed, it means people have different opinions. Thus, a conclusion should be made and then finally conduct the merge.

**Comment by hwdef** [comment]
It depends on Huawei.

**Comment by xiao-jay** [comment]
Add a suggestion,
The PR proposer has not been working on this PR for a long time,such as #2820 .

What would you like to be added:

Close these PR that have not been contributed for a long time and are not important,or can propose an issue and wait for next one to solve the issue.

**Comment by Monokaix** [comment]
Yeah, good ssuggestions, should be adopted!
