### ISSUE TITLE
UT didn't really run because of kubeclient init failed

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2957]
**What happened**:
https://github.com/volcano-sh/volcano/blob/9427174e0eefc18d321d34ba844fe3f80ff491a5/pkg/scheduler/plugins/predicates/predicates_test.go#L68-L71

<img width="904" alt="image" src="https://github.com/volcano-sh/volcano/assets/21003791/260891ac-2843-4dd3-be93-e4ba93bee930">

**What you expected to happen**:

UT should use k8s's fakeclient

**How to reproduce it (as minimally and precisely as possible)**:

add log before return
```go
	klog.Errorf("exiting test...")
```

**Anything else we need to know?**:

all cases in predicate and nodeorder plugin which need k8s client

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
Please merge PR https://github.com/volcano-sh/volcano/pull/2866 first which use k8s's clientset interface, and then use a fakeclient to fix the unit-test.

**Comment by wangyang0616** [comment]
I think the ut processing in this place is not good. Is it more reasonable not to rely on k8sclient?

**Comment by lowang-bh** [comment]
> I think the ut processing in this place is not good. Is it more reasonable not to rely on k8sclient?

It is flexible after replace those client with interface. No matter k8s fake client or self-implemented  client is ok.

**Comment by lowang-bh** [comment]
same as #2810
