### ISSUE TITLE
Failed to create or update queue without item status.allocated in config

### ISSUE THREAD

**Issue by Christina935** [volcano-sh/volcano#2963]
**What happened**:
when create queue in cluster, the controller reports the error
`Failed to update status of Queue test: Queue.scheduling.volcano.sh test is invalid: status.allocated: Required value`
when submit job to queue,  error is  `admission webhook "validationjob.volcano.sh" denied the request: can only submit job to queue with state Open`

the error may is caused by the definition of crd
https://github.com/volcano-sh/volcano/blob/1933d46bdc4434772518ebb74c4281671ddeffa1/config/crd/bases/scheduling.volcano.sh_queues.yaml#L188-L189

it may need to change the item `allocated` as an optional item
```go
// Allocated is allocated resources in queue
// +optional
Allocated v1.ResourceList
```

**What you expected to happen**:
create or update queue successfully and then we can submit job to queue

**How to reproduce it (as minimally and precisely as possible)**:
create queue in cluster and then submit job
update the capability of queue when there is no job in queue

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.7.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Monokaix** [comment]
Has been fixed in latest version.
