### ISSUE TITLE
diffferent value of variable in returned err will cause event message too long

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#2975]
When one schedule cycle finishes, scheduler will sum up the unschedule reason and merge same reson. If there are different value of a variable in scheduler error, the unschedule event message will be too long.

**What happened**:
https://github.com/volcano-sh/volcano/blob/5302995a1d000df718fee5f3044df64bcb773d8d/pkg/scheduler/actions/allocate/allocate.go#L100-L118
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
@wangyang0616

**Comment by lowang-bh** [comment]
Another little issue,  extender example has broken.

<img width="1015" alt="image" src="https://github.com/volcano-sh/volcano/assets/21003791/035b267a-e21a-4d5e-9ad4-5a6de08ab253">

**Comment by Ash-KODES** [comment]
hey, I am interested in getting into the volcano project,
Can I look into this ?, I think this will help me to understand some flows of the project.

**Comment by lowang-bh** [comment]
Of cause, welcome!

**Comment by wangyang0616** [comment]
Yes, each filter node will execute all configured plugins, and finally summarize the results, which will have a certain performance impact compared to the previous implementation logic.

The current modification is mainly to solve the plugin's predicate compatibility with allocate and preempt functions. If there is a better solution, look forward to communicating with you.
