### ISSUE TITLE
 in CheckTaskReady function why ji.MinAvailable < ji.TaskMinAvailableTotal ？

### ISSUE THREAD

**Issue by BrushXiaoMinGuo** [volcano-sh/volcano#2978]
**Hello, I am interested in volcanoes and studying them. However, I have some confusion when reading the source code**:

**i think MinAvailable equal TaskMinAvailableTotal，but why in   CheckTaskReady function ji.MinAvailable < ji.TaskMinAvailableTotal**:

func (ji *JobInfo) CheckTaskReady() bool {
	if ji.MinAvailable < ji.TaskMinAvailableTotal {
		return true
	}
	...

**I'm looking forward to your response.**:

**Comment by lowang-bh** [comment]
TaskMinAvailableTotal is introduced after MinAvailable. 
There is some design gap, I think. 
I have a summery about it in docs #2945

**Comment by BrushXiaoMinGuo** [comment]
I get it, thank you
