### ISSUE TITLE
When using the high-availability mode, when Volcano is uninstalled, two resources will remain.

### ISSUE THREAD

**Issue by gj199575** [volcano-sh/volcano#2979]
this issue is releated to https://github.com/volcano-sh/volcano/pull/2980
#### What would you like to be added:
change resourcelock.New(resourcelock.ConfigMapsLeasesResourceLock to  resourcelock.New(resourcelock.LeasesResourceLock

#### Why is this needed:
it will use fewer resource

beofore this PR

kubectl get cm -A
kube-system          vc-controller-manager                      0      171d
kube-system          volcano                                    0      171d
kubectl get leases -A
kube-system          vc-controller-manager      volcano-controller-6bdcc5ccdf-qt7sx_0aeaadca-4c71-4cc3-945b-19a06db5e6b1    171d
kube-system          volcano                    volcano-scheduler-1_5d9b01e2-01c5-4d85-ab48-9f931ec77efc                    171d

after this  PR
only left leases
kubectl get leases -A
kube-system          vc-controller-manager      volcano-controller-6bdcc5ccdf-qt7sx_0aeaadca-4c71-4cc3-945b-19a06db5e6b1    171d
kube-system          volcano                    volcano-scheduler-1_5d9b01e2-01c5-4d85-ab48-9f931ec77efc                    171d

**Comment by lowang-bh** [comment]
this issue can close now. @gj199575
