### ISSUE TITLE
请教一些混合部署场景的问题

### ISSUE THREAD

**Issue by wuyueandrew** [volcano-sh/volcano#2981]
Hi，
我们现在有一个k8s集群来部署微服务和作业，现在的场景是需要把集群节点划分为微服务节点和作业节点两组来满足不同类型的容器调度，请问volcano有开箱即用的方式么，如果没有的话自己定制action和plugin是否能满足需求？
另外，如果后续需要继续划分ml推理节点出来，继续扩展是否复杂？
感谢

**Comment by Thor-wl** [comment]
@wuyueandrew Hello, 不完全了解业务细节，仅就当前描述表达些许看法，或许不完全对你有用，仅供参考：

**Comment by wuyueandrew** [comment]
@Thor-wl  感谢回复和建议
1.对于没有分集群的部署，一方面考虑到运维复杂性，一套集群运维起来比多套集群方便，其次是有些微服务和作业/ml推理之间是需要通信的，一个集群内比较方便，最后是不排除以后会有互相混部以提高利用率的考虑。
2.我简单看了下pr，应该能很好满足我们目前需求，会在部署测试后再评估。
最后，再次感谢

**Comment by wuyueandrew** [comment]
暂时关闭
