### ISSUE TITLE
Creating jobs through JobFlow and JobTemplate was unsuccessful

### ISSUE THREAD

**Issue by Mufengzhe** [volcano-sh/volcano#2983]
**What happened**:
When I want to create JobFlow and JobTempate using examples in the `volcano/example/jobflow `directory of the volcano project, the JobTemplate and JobFlow are successfully created, but the job object resources under JobFlow are not created；And the log information in the controller is: ` Failed to create jobs of JobFlow default/test: jobs.batch.volcano.sh is forbidden: User "system:serviceaccount:volcano-system:volcano-controllers" cannot create resource "jobs" in API group "batch.volcano.sh" in the namespace "default"`
**What you expected to happen**:
The jobs object under JobFlow is successfully created, and the resource information can be found by using `kubectl get po`
**How to reproduce it (as minimally and precisely as possible)**:
```
# deploy jobTemplate first
cd volcano
kubectl apply -f example/jobflow/JobTemplate.yaml
# deploy jobFlow second
kubectl apply -f example/jobflow/JobFlow.yaml

# check them
kubectl get jt
kubectl get jf
kubectl get po
```
**Anything else we need to know?**:
The configuration file in the example/jobflow directory is used
**Environment**:
- Volcano Version: v1.8.0-alpha.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:

**Comment by lowang-bh** [comment]
what is the output of `kubectl get clusterrole volcano-controllers -o yaml`?

**Comment by lowang-bh** [comment]
It will works after PR https://github.com/volcano-sh/volcano/pull/2951 merged. You can validate it use that mr.

**Comment by Mufengzhe** [comment]
This problem was solved, but I had other unexpected errors when I proceeded to the next step. When I execute the `kubectl apply -f example/jobflow/JobFlow.yaml `, I find that job-a starts to create, but the pod state has always been `ContainerCreating`, when I check the log, I find that it has been pulling image, and when I check the controller,  the log print content is `
I0724 02:28:57.686263       1 jobflow_controller_action.go:115] No test-b Job found！
I0724 02:28:57.686274       1 jobflow_controller_action.go:115] No test-b Job found！
I0724 02:28:57.686283       1 jobflow_controller_action.go:115] No test-c Job found！
E0724 02:28:57.688560       1 jobflow_controller_action.go:69] Failed to update status of JobFlow default/test: jobflows.flow.volcano.sh "test" is forbidden: User "system:serviceaccount:volcano-system:volcano-controllers" cannot update resource "jobflows/status" in API group "flow.volcano.sh" in the namespace "default"`. 
I'm not sure if pulling images all the time is related to this error, Is this a bug or a problem with my environment

**Comment by Mufengzhe** [comment]
I added the following to the `ClusterRole.volcano-scheduler.rules` in the volcano-depolyment.yaml file to solve the above problem
![image](https://github.com/volcano-sh/volcano/assets/33545088/8f084aa4-6f8e-4700-9c0a-013a63aa4af1)

**Comment by lowang-bh** [comment]
The following is also need.
```
  - apiGroups: [ "flow.volcano.sh" ]
    resources: [ "jobflows/status", "jobs/finalizers","jobtemplates/status", "jobtemplates/finalizers"  ]
    verbs: [ "update", "patch" ]
```

**Comment by Mufengzhe** [comment]
I tried, only need to add this for `volcano-controllers`, other modifications are not needed, looking forward to modifying the code
```
  - apiGroups: [ "flow.volcano.sh" ]
    resources: [ "jobflows/status", "jobs/finalizers","jobtemplates/status", "jobtemplates/finalizers"  ]
    verbs: [ "update", "patch" ]
```

**Comment by lowang-bh** [comment]
Have fixed
/close
