### ISSUE TITLE
Optimize log output when resources are not enough

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#2993]
#### What would you like to be added:
Optimize the scheduler's logs when resources are low by printing exactly what kind of resources are low.
#### Why is this needed:
easier to identify the reasons for insufficient resources.

#### kubernetes scheduler VS volcano
kubernetese scheduler:
![image](https://github.com/volcano-sh/volcano/assets/13084946/aad7b8da-0c84-44f4-866c-3c2875efa8ad)

volcano:
![image](https://github.com/volcano-sh/volcano/assets/13084946/3201a843-28bb-4a02-85f1-00c7464bf8fa)

volcano just print `NotEnoughResources`

**Comment by srikanth-iyengar** [comment]
Hello @hwdef, could you please let me know if I can choose this issue as my first task to work on for Volcano?

**Comment by hwdef** [comment]
Yes you can fix this, our goal is that the error prompts in case of insufficient resources are consistent with the native scheduler of kubernetes.

**Comment by srikanth-iyengar** [comment]
@hwdef Can you please confirm if my approach is correct or not
i.e. quering the Kubernetes cluster for available memory and CPU. By comparing these metrics with the job's resource allocation requests we can find which is causing the issue and will log the same

**Comment by hwdef** [comment]
> @hwdef Can you please confirm if my approach is correct or not i.e. quering the Kubernetes cluster for available memory and CPU. By comparing these metrics with the job's resource allocation requests we can find which is causing the issue and will log the same

By and large this is correct, but I don't think you need to actively query the k8s for available cpu, memory remaining, volcano should already be maintaining these in cache. And we don't just need to know the cpu and memory ones, there are also extended resources such as nvidia.com/gpu

**Comment by srikanth-iyengar** [comment]
Ohk got it,
Will start working on this

**Comment by lowang-bh** [comment]
Hi @srikanth-iyengar , you can refer to the following desplayed, deployment with 2 pods.

pod first scheduled failed
<img width="878" alt="image" src="https://github.com/volcano-sh/volcano/assets/21003791/36369c0e-2c2d-4d58-a537-21f85a0768a7">


another pod's message:
<img width="857" alt="image" src="https://github.com/volcano-sh/volcano/assets/21003791/6cd305a7-23f4-407a-b6bf-21af36d5f714">

podgroup message:
<img width="848" alt="image" src="https://github.com/volcano-sh/volcano/assets/21003791/df88dfa9-fd8e-4503-8d61-e5718dbb6af2">

**Comment by srikanth-iyengar** [comment]
![image](https://github.com/volcano-sh/volcano/assets/88551109/84ffa5db-7e07-4d9f-9e14-15e0b48488d6)
Will this solution resolve the issue of resource unavailability log?

**Comment by srikanth-iyengar** [comment]
> Hi @srikanth-iyengar , you can refer to the following display, deployment with 2 pods.
> 
> pod first scheduled failed <img alt="image" width="878" src="https://user-images.githubusercontent.com/21003791/260297737-36369c0e-2c2d-4d58-a537-21f85a0768a7.png">
> 
> another pod's message: <img alt="image" width="857" src="https://user-images.githubusercontent.com/21003791/260297619-6cd305a7-23f4-407a-b6bf-21af36d5f714.png">
> 
> podgroup message: <img alt="image" width="848" src="https://user-images.githubusercontent.com/21003791/260297635-df88dfa9-fd8e-4503-8d61-e5718dbb6af2.png">

Thanks for the info @lowang-bh

**Comment by srikanth-iyengar** [comment]
Hey @hwdef and @lowang-bh, could one of you provide a heads-up if everything is looking good in the PR?
