### ISSUE TITLE
Enhance usage plugin

### ISSUE THREAD

**Issue by gj199575** [volcano-sh/volcano#3042]
#### What would you like to be added:
First optimize the usage plugin configuration of Volcano.
before that 

     - name: usage
       arguments:
          thresholds:
            CPUUsageAvg.5m: 80
            MEMUsageAvg.5m: 90

after that
  - name: usage
       arguments:
         usage.weight: 10
         type: average
         thresholds:
           cpu: 70
           mem: 70
         period: 10m

Second, make it easier for users to use the usage plugin
before
You must first define the rules of Pro, as follows

groups:
   - name: cpu_mem_usage_active
     interval: 30s
     rules:
     - record: mem_usage_active
       expr: 100*(1-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)
   - name: cpu-usage-1m
     interval: 1m
     rules:
     - record: cpu_usage_avg_5m
       expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
   - name: mem-usage-1m
     interval: 1m
     rules:
     - record: mem_usage_avg_5m
       expr: avg_over_time(mem_usage_active[5m])

after that
You don't need to define general rules, you can use the usage plugin directly

#### Why is this needed:
Make Volcano more user-friendly

**Comment by william-wang** [comment]
Please add more description of your requirement :)

**Comment by Monokaix** [comment]
fixed by https://github.com/volcano-sh/volcano/issues/3175
