### ISSUE TITLE
[good first issue]enrich the unit-test for some package

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3053]
#### What would you like to be added:

There are many packages which don't have unit-test, such as:
- actions: 
  - [x] enqueue
  - [x] backfill

- plugins: 
  - [x] gang
  - [ ] extender
  - [x] overcommit
  - [x] resourcequota
  - [x] usage
- others, include some PRs:

UTs should include positive cases and reverse cases.

#### Why is this needed:

1. to avoid future changes impacting those function, and make code more strong

#### Benefits

1. you can familiar with the coding logic and get started with volcano

#### how to assign

assign only one package to yourself in each pr.

**Comment by lowang-bh** [comment]
/ good first issue
/ help wanted

**Comment by Subhasish-Behera** [comment]
@lowang-bh  I would like to work on unit-tests for `resourcequota`

**Comment by rayoluo** [comment]
@lowang-bh I would like to work on the rest unit-tests

**Comment by lowang-bh** [comment]
Thanks all of you.
/assign @Subhasish-Behera  plugins resourcequota
/assign @rayoluo actions enqueue/backfill; plugins gang/extender/overcommit/usage

**Comment by lowang-bh** [comment]
@Subhasish-Behera @rayoluo Any updates on this issue?

**Comment by Subhasish-Behera** [comment]
@lowang-bh, I'm still working on this issue. Would it be possible to discuss the codebase with you in more detail via email or Slack?

**Comment by Subhasish-Behera** [comment]
@lowang-bh Just filed a PR for the `resourcequota` plugin. any feedback about the PR is welcome.

(cc @william-wang @Monokaix )

**Comment by lowang-bh** [comment]
Now we can use the base UT lib in https://github.com/volcano-sh/volcano/pull/3343 to do the test.
Examples shows at PR #3340  #3341 #3342

**Comment by googs1025** [comment]
@lowang-bh  Hello, may I ask if this will allocate a specific part?

**Comment by lowang-bh** [comment]
> @lowang-bh Hello, may I ask if this will allocate a specific part?

Welcome! You can work on those packages which have no UTs covered.

**Comment by MondayCha** [comment]
@googs1025 Hello, I'm currently looking into Issue #3075 and noticed that there's some overlap with current Issue #3320 regarding _enqueue_ and _backfill_. 

I was wondering if you're planning to address these actions in a future PR?

**Comment by googs1025** [comment]
@MondayCha Hi, hello, I am currently working on other packages. You can work on the action package.

**Comment by googs1025** [comment]
@MondayCha hi, Are you still working on this?

**Comment by MondayCha** [comment]
> @MondayCha hi, Are you still working on this?

Sorry I haven't started yet. I'm still trying to understand the relevant code and might attempt it next week. 

If you need to do enqueue and backfill, I will avoid it.

**Comment by JesseStutler** [comment]
Maybe need to refactor the current implementation of building pod, priorityclass, queue...? See here: https://github.com/volcano-sh/volcano/issues/3075#issuecomment-2368050656, current function like BuildPod's scalability is not so good, maybe to refactor implementation like in k8s repository?  https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller_test.go#L7791-L7821
