### ISSUE TITLE
Predicate function retrun value is not compatiable with old plugins

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3086]
There are other plugins dynamically loaded to volcano. eg. huawei's acend gpu, https://gitee.com/ascend/ascend-for-volcano

**What happened**:

https://github.com/volcano-sh/volcano/blob/b95d0f15e0ff2af9a7c9ae9a037a4c4c9e7300aa/pkg/scheduler/api/types.go#L170C6-L170C17
```
// PredicateFn is the func declaration used to predicate node for task.
type PredicateFn func(*TaskInfo, *NodeInfo) ([]*Status, error)
```

npu plugin
https://gitee.com/ascend/ascend-for-volcano/blame/master/huawei_npu.go
```
	// if npu no meet the task require,the task will failed.so need to intercept in advance
	ssn.AddPredicateFn(tp.Name(), func(taskInfo *api.TaskInfo, nodeInfo *api.NodeInfo) error {
		return sHandler.NodePredicate(taskInfo, nodeInfo, ssn.Configurations)
	})
```

**What you expected to happen**:

Should be compatiable with other extender plugins

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Introduced by refact PR [#2916](https://github.com/volcano-sh/volcano/pull/2916)

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by william-wang** [comment]
Let's do this in v1.9

**Comment by lowang-bh** [comment]
@Monokaix we need to fix  it in new realease.
