### ISSUE TITLE
The limitation  of  vgpu memory using by  resource  volcano.sh/vgpu-memory-percentage is not  useful

### ISSUE THREAD

**Issue by CharJayLee** [volcano-sh/volcano#3089]
**What happened**:
The limitation  of  vgpu memory using by  resource  volcano.sh/vgpu-memory-percentage is not  useful
**What you expected to happen**:
The limitation  of  vgpu memory using by  resource  volcano.sh/vgpu-memory-percentage should be  useful
**How to reproduce it (as minimally and precisely as possible)**:
The total memory of  per gpu card is 32G  
$ cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod12
spec:
  schedulerName: volcano
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          volcano.sh/vgpu-number: 2 # requesting 2 vGPUs
          volcano.sh/vgpu-memory-percentage: 10 #Each vGPU containers 10% device memory of that GPU. 
    - name: ubuntu-container0
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
EOF
 you can check the  memory of two vgpu which allocate to  the  container  . The  value of  memory is not  10% of  32G , and it is not correct .
![image](https://github.com/volcano-sh/volcano/assets/19263605/356ba891-5761-4d9b-86e5-44c2283dd91d)
  

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.8.0
- Kubernetes version (use `kubectl version`): v1.25
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by archlitchi** [comment]
i haven't enable "gpumem-percentage" field in this version yet, i plan to do it with "gpucores" in v1.9

**Comment by william-wang** [comment]
The gpumem-percentage has not been implemented yet, so close the issue.
