### ISSUE TITLE
framework.go:40] Failed to get plugin nodegroup.

### ISSUE THREAD

**Issue by chenxj1997** [volcano-sh/volcano#3091]
1.8.0 set nodegroup but filed 

apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
      - name: nodegroup
        enablePredicate: true
        enableNodeOrder: true
kind: ConfigMap

What should we do？？

**Comment by wuyueandrew** [comment]
同问，#2227 只增加了nodegroup doc，相关代码不存在
