### ISSUE TITLE
Volcano install failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#310]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

 /kind bug

**What happened**:

install volcano as readme, but i meet the following error.

```
$ helm install volcano/volcano --namespace kube-system --name volcano
Error: namespaces "kube-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "kube-system
```

**What you expected to happen**:

1. install successfully 

1. allow user to set volcano flags 

1. provide a simple install yaml

**How to reproduce it (as minimally and precisely as possible)**:

install volcano following  https://github.com/volcano-sh/volcano/blob/master/README.md

**Anything else we need to know?**:

my kubernetes cluster is created by `kind`

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
We should make sure the readme/tutorial correct :)

**Comment by hzxuzhonghu** [comment]
I have opened #325 to track contributor experience improvement stuff.

**Comment by hzxuzhonghu** [comment]
We need a more simple way to install, one command `kubectl apply -f  xxx.yaml`. 

Helm is complicated, it requires users to install helm and tiller first.

**Comment by xieydd** [comment]
what is the version of helm ? Tiller of helm v3 is gone, how about maintaining xxx.yaml and helm repo.

**Comment by asifdxtreme** [comment]
With the current master branch code I am getting this error for `jobs.batch.volcano.sh`
```
kubectl create -f batch_v1alpha1_job.yaml 
The CustomResourceDefinition "jobs.batch.volcano.sh" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[plugins].additionalProperties: Forbidden: additionalProperties cannot be set to false
* spec.validation.openAPIV3Schema.properties[status].properties[ControlledResources].additionalProperties: Forbidden: additionalProperties cannot be set to false

```

**Comment by hzxuzhonghu** [comment]
@asifdxtreme What's your k8s version?

**Comment by asifdxtreme** [comment]
> @asifdxtreme What's your k8s version?

```
kubectl version --short
Client Version: v1.15.0
Server Version: v1.10.0
```

**Comment by TommyLike** [comment]
Works well on my environment:
```
 ⚡ root@husheng: kb version --short
Client Version: v1.15.0
Server Version: v1.15.0
```

**Comment by wingerted** [comment]
Seems RBAC problem ?

**Comment by k82cn** [comment]
@TommyLike , @hzxuzhonghu , when can we get this done?

**Comment by TommyLike** [comment]
> @TommyLike , @hzxuzhonghu , when can we get this done?

@k82cn , For this issue itself. it's the RBAC issue which needs us to install tiller with enough rights to handle resource, it's something like:
```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
```
But for the issue which @asifdxtreme or the volcano user @Swati Agrawal, we need more detail to find out the root cause. It can be the kubernetes version mismatch, helm binary version requirement or something else.

**Comment by TommyLike** [comment]
> With the current master branch code I am getting this error for `jobs.batch.volcano.sh`
> 
> ```
> kubectl create -f batch_v1alpha1_job.yaml 
> The CustomResourceDefinition "jobs.batch.volcano.sh" is invalid: 
> * spec.validation.openAPIV3Schema.properties[spec].properties[plugins].additionalProperties: Forbidden: additionalProperties cannot be set to false
> * spec.validation.openAPIV3Schema.properties[status].properties[ControlledResources].additionalProperties: Forbidden: additionalProperties cannot be set to false
> ```

This a similar issue to this OpenAPI issue https://github.com/kubernetes/apiextensions-apiserver/issues/26.

**Comment by TommyLike** [comment]
> > With the current master branch code I am getting this error for `jobs.batch.volcano.sh`
> > ```
> > kubectl create -f batch_v1alpha1_job.yaml 
> > The CustomResourceDefinition "jobs.batch.volcano.sh" is invalid: 
> > * spec.validation.openAPIV3Schema.properties[spec].properties[plugins].additionalProperties: Forbidden: additionalProperties cannot be set to false
> > * spec.validation.openAPIV3Schema.properties[status].properties[ControlledResources].additionalProperties: Forbidden: additionalProperties cannot be set to false
> > ```
> 
> This a similar issue to this OpenAPI issue [kubernetes/apiextensions-apiserver#26](https://github.com/kubernetes/apiextensions-apiserver/issues/26).

We used to use kind 0.2.0 to running our E2E tests, which means the oldest version of kubernetes that have been tested should be 1.13.4. https://github.com/kubernetes-sigs/kind/releases/tag/0.2.0

**Comment by TommyLike** [comment]
@hzxuzhonghu please try the latest installation guide in master branch.

**Comment by hzxuzhonghu** [comment]
This can be closed now.
