### ISSUE TITLE
除了使用Vcctl还有什么方法可以修改queue的状态吗

### ISSUE THREAD

**Issue by jyn244636695** [volcano-sh/volcano#3103]
**What happened**:
我们需要一个功能去修改Queue的状态，但是kubectl的edit无法对queue的state字段修改生效。
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
我们尝试了使用Vcctl工具是可行的，但是有没有不适用vcctl的方法？

**Comment by hwdef** [comment]
vcctl实际上是创建了一个command资源，你可以使用kubectl创建这个资源。
