### ISSUE TITLE
Default queue with zero allocated in the status

### ISSUE THREAD

**Issue by wengyao04** [volcano-sh/volcano#3112]
**What happened**:
Hi, I try to integrate volcano with kubeflow training operator and use it as the gang scheduler for our PytorchJobs. We install the latest kubeflow training operator and latest volcano.

After I install the volcano, the default queue is like
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  creationTimestamp: "2023-09-12T02:06:30Z"
  generation: 1
  name: default
  resourceVersion: "193127718"
  uid: 587dbcf9-3029-4d74-ad6b-88614249f948
spec:
  guarantee: {}
  reclaimable: true
  weight: 1
status:
  allocated:
    cpu: "0"
    memory: "0"
  reservation: {}
  state: Open
```
The allocated resource list are all zero, that causes all my job pods are in pending state, but our cluster have lots of free cpu/memory/gpus.

I look at the controller logs
```
I0912 02:06:30.246475       1 queue_controller.go:246] Begin execute SyncQueue action for queue default, current status
I0912 02:06:30.246522       1 queue_controller_action.go:35] Begin to sync queue default.
E0912 02:06:30.261244       1 queue_controller_action.go:79] Failed to update status of Queue default: Queue.scheduling.volcano.sh "default" is invalid: status.allocated: Required value.
I0912 02:06:30.261286       1 queue_controller_action.go:80] End sync queue default.
I0912 02:06:30.261312       1 queue_controller.go:228] Finished syncing queue default (14.874797ms).
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`): 1.24.x
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): `Linux tt-0101546 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: helm
- Others:

**Comment by wengyao04** [comment]
Hi, I miss understand the queue controller logic. I try again and have to wait a little bit, and the pod is running and queue status is updated
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  creationTimestamp: "2023-09-12T03:26:01Z"
  generation: 1
  name: default
  resourceVersion: "193166543"
  uid: 1be5de03-cfe3-4928-9536-636e49c581f0
spec:
  guarantee: {}
  reclaimable: true
  weight: 1
status:
  allocated:
    cpu: "4"
    ephemeral-storage: "8388608"
    memory: 32Gi
  reservation: {}
  state: Open
```

**Comment by lowang-bh** [comment]
`queue_controller_action.go:79] Failed to update status of Queue default: Queue.scheduling.volcano.sh "default" is invalid: status.allocated: Required value`

This log is confused. We need to improve it.

**Comment by Monokaix** [comment]
/close
fixed by https://github.com/volcano-sh/volcano/pull/3206
