### ISSUE TITLE
Preemption fails when queue resources are insufficient and node resources are sufficient

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#3161]
**How to reproduce it (as minimally and precisely as possible)**:

one node has 12 CPU
queue-a capacity is 4 CPU
low-priority-job request 3 CPU
high-priority-job request 3 CPU

1. create low-priority job
2. create high-priority job
3. It can be observed that low-priority job are not preempted

**What you expected to happen**:

Low-priority job are evicted and high-priority job run normally

**Anything else we need to know?**:

preempt will break in here

https://github.com/volcano-sh/volcano/blob/5ab580c83982e4809ca2988552b42aada8ea193c/pkg/scheduler/actions/preempt/preempt.go#L275C34-L275C34

**Environment**:
- Volcano Version: 1.18
- Kubernetes version (use `kubectl version`): 1.27

**Comment by lowang-bh** [comment]
comment on  https://github.com/volcano-sh/volcano/pull/2234#issuecomment-1773986531

**Comment by william-wang** [comment]
/ assign @Monokaix

**Comment by Monokaix** [comment]
> comment on [#2234 (comment)](https://github.com/volcano-sh/volcano/pull/2234#issuecomment-1773986531)

You're right, change `Overused` to `AddAllocatableFn` is a way to fix this.

**Comment by lowang-bh** [comment]
Hi, @hwdef , please help to validate your issue with PR #3230

**Comment by hwdef** [comment]
I think this issue has not been fixed
