### ISSUE TITLE
volcano controller print too much events

### ISSUE THREAD

**Issue by hwdef** [volcano-sh/volcano#3178]
**What happened**:

volcano controller print too much events

**What you expected to happen**:

Reduce the output of events

**How to reproduce it (as minimally and precisely as possible)**:

A running podgroup that outputs 100w events, which increases the pressure on the apiserver

![image](https://github.com/volcano-sh/volcano/assets/13084946/04d957f3-8594-46d0-930b-7a8a580a8bfb)

**Environment**:
- Volcano Version: 1.7

**Comment by lowang-bh** [comment]
I remember that it has been fixed in pr #3115  and merged to release 1.8 (https://github.com/volcano-sh/volcano/pull/3117/files)

**Comment by hwdef** [comment]
> I remember that it has been fixed in pr #3115 and merged to release 1.8 (https://github.com/volcano-sh/volcano/pull/3117/files)

yes, you are right. Thanks!

**Comment by GhangZh** [comment]
This pr [#3115]https://github.com/volcano-sh/volcano/pull/3115 only reduces the number of scheduled events, but the number of unscheduled events is just as high, which can lead to a very large number of events if the cluster is scheduled with volcano.
