### ISSUE TITLE
Update job schedulerName does not take any effect

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#318]
I created a volcano job with incorrect schedulerName `kube-batch`. And i found all the jobs pending, this is expected. 

But when i updated the schedulerName to `volcano`, it did not recreate the pods. 

Should we explicitly say that we do not support update in docs, or allow updating before the job really running?

/kind feature

**Comment by TommyLike** [comment]
Not only the scheduler name, as well as plugins, container spec and etc. All of them are not supported.  Agree that we may mention this in document that it's not supported for job update operation.

**Comment by hzxuzhonghu** [comment]
Where do you think we should put the notes?

**Comment by k82cn** [comment]
let's create a doc named `known-issues.md`.

**Comment by k82cn** [comment]
@hzxuzhonghu , how about the known-issues?

**Comment by hzxuzhonghu** [comment]
IMO, add a FAQ under https://github.com/volcano-sh/volcano/wiki, and link it to readme is a good choice

**Comment by k82cn** [comment]
Wiki is ok to me.

**Comment by hzxuzhonghu** [comment]
Yeah, i have no permission to write anyway

**Comment by k82cn** [comment]
if so, please create a file for that; we cann-t open permission to everyone.

**Comment by k82cn** [comment]
@hzxuzhonghu , what's next step? This's there for a long time.

**Comment by hzxuzhonghu** [comment]
Volcano Job update should be prohibited when it is running, however, when it is pending, we can allow update.  The intercept can be done in admission webhook.

**Comment by k82cn** [comment]
how about current status?

**Comment by hzxuzhonghu** [comment]
We have added check for job update,  this is denied by admission controller.
