### ISSUE TITLE
fix：When queue resources are insufficient or about to be insufficient, instances cannot be generated.

### ISSUE THREAD

**Issue by LY-today** [volcano-sh/volcano#3198]
**What happened**:
When queue resources are insufficient or about to be insufficient, instances cannot be generated

**What you expected to happen**:
Instances can also be generated when queue resources are insufficient or about to be insufficient.

**How to reproduce it (as minimally and precisely as possible)**:
When the currently allocated amount of a certain resource in the queue plus the resource application amount of the new task is greater than the upper limit of the resource configured in the queue, the phenomenon that the instance cannot be created can be stably reproduced.

**Anything else we need to know?**:
- vcJob event：Warning  PodGroupPending  38s   vc-controller-manager  PodGroup default:dlp-stage-ecu-test6 unschedule,reason: 1/0 tasks in gang unschedulable: pod group is not ready, 1 minAvailable
- podGroup event：Normal   Unschedulable  92s (x13 over 105s)  volcano  queue resource quota insufficient

**Environment**:
- Volcano Version:
v1.7.0
- Kubernetes version (use `kubectl version`):
v1.18.2
- Cloud provider or hardware configuration:
none
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux  3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
none
- Others:
none

**Comment by Monokaix** [comment]
Hi, what does the instance mean? pod or anything else?

**Comment by LY-today** [comment]
> Hi, what does the instance mean? pod or anything else?

Hi，pod

**Comment by LY-today** [comment]
> > > Hi, what does the instance mean? pod or anything else?
> > 
> > 
> > Hi，pod
> 
> If queue has no sufficient resources, new task will not be scheduled, which I think it's normal: )

**Comment by LY-today** [comment]
> > > > Hi, what does the instance mean? pod or anything else?
> > > 
> > > 
> > > Hi，pod
> > 
> > 
> > If queue has no sufficient resources, new task will not be scheduled, which I think it's normal: )

Maybe my description is wrong. It's not that it cannot be scheduled and pending appears, but that no instance is generated. This is what I think is unreasonable

**Comment by LY-today** [comment]
@Monokaix The core of the problem is not that instances cannot be scheduled and pending occurs when resources are scarce, but that no instances are created at all.

**Comment by william-wang** [comment]
@LY-today Did you configured the enqueue action in scheduler-configmap and enalbe the `delay pod creation` feature. Please add your scheduler configmap if possible. Here is the introduction of `delay pod creation` feature.
https://github.com/volcano-sh/volcano/blob/master/docs/design/delay-pod-creation.md

**Comment by LY-today** [comment]
> @LY-today您是否在 Scheduler-configmap 中配置了排队操作并启用了该`delay pod creation`功能。如果可能，请添加您的调度程序配置映射。这里是功能的介绍`delay pod creation`。 https://github.com/volcano-sh/volcano/blob/master/docs/design/delay-pod-creation.md

Thanks for your feedback, I tested it and found the solution

**Comment by LY-today** [comment]
@william-wang For this scenario, it can be solved if I directly close the enqueue action. I would like to ask whether other problems may be introduced after closing it?
The impact of apiserver pressure and slow scheduling is acceptable. Are there other effects?

**Comment by lowang-bh** [comment]
> The impact of apiserver pressure and slow scheduling is acceptable. Are there other effects?

If there is no enqueue action, podgroup will not be enqueue and job won't be scheduled.

**Comment by william-wang** [comment]
> @william-wang For this scenario, it can be solved if I directly close the enqueue action. I would like to ask whether other problems may be introduced after closing it? The impact of apiserver pressure and slow scheduling is acceptable. Are there other effects?

@LY-today There is no other effects without enqueue.

**Comment by LY-today** [comment]
> > apiserver压力和调度缓慢的影响是可以接受的。还有其他影响吗？
> 
> 在release-1.6之前，如果没有enqueue操作，podgroup将不会入队，作业也不会被调度。
> 
> 该版本之后，支持无入队操作的调度。仅供参考：[91981bf48](https://github.com/volcano-sh/volcano/commit/dad6ec78b198a4d42160f2274eb5f1dfe3db4b18)

Thank you for your feedback

**Comment by LY-today** [comment]
> > @william-wang For this scenario, it can be solved if I directly close the enqueue action. I would like to ask whether other problems may be introduced after closing it? The impact of apiserver pressure and slow scheduling is acceptable. Are there other effects?
> 
> @LY-today There is no other effects without enqueue.

Thank you for your feedback
