### ISSUE TITLE
[Question] develop process for charts related changes?

### ISSUE THREAD

**Issue by TommyLike** [volcano-sh/volcano#323]
/kind feature

**Background**:
Now we have seperated repos for volcano and volcano chart. Considering it's possible that the one feature may change them both at the same time. What is the standard process when developing those features. for example: #165

**Comment by TommyLike** [comment]
One of the solutions that I can think of is:
1. Develop and Merge functionality codes with UT and existing E2E tests update.
2. Update charts based on new feature.
3. Add E2E tests regarding new features and fix issues(if required.)

**Comment by k82cn** [comment]
IMO, we should maintainer Charts in volcano, and sync it to volcano-sh/charts when release.

**Comment by TommyLike** [comment]
> IMO, we should maintainer Charts in volcano, and sync it to volcano-sh/charts when release.

that would be much better.

**Comment by TommyLike** [comment]
> IMO, we should maintainer Charts in volcano, and sync it to volcano-sh/charts when release.

So for the convenience of development, should we add the charts code back into volcano repo and sync them into chart repo when releasing? @k82cn @hzxuzhonghu @asifdxtreme ?

**NOTE**:  We may generate release yaml as [istio](https://istio.io/docs/setup/kubernetes/#installing-istio) does now for a simpler approach, but it might not conflict to the chart support.

**Comment by k82cn** [comment]
> should we add the charts code back into volcano repo and sync them into chart repo when releasing?

Yes, similar to staging pkg in k8s.

**Comment by k82cn** [comment]
so what's our next step?

**Comment by TommyLike** [comment]
> so what's our next step?

Sync the latest chart templates into local folder and set up the guidance how and when to sync the latest code back to chart when releasing?

**Comment by TommyLike** [comment]
> > so what's our next step?
> 
> Sync the latest chart templates into local folder and set up the guidance how and when to sync the latest code back to chart when releasing?

Opened a new PR to adding helm charts back #334 . Once again, this is used to reduce the complexity of developing new features. We don't need to open seperated PRs for one feature changes now.

**Comment by k82cn** [comment]
what's next step?

**Comment by TommyLike** [comment]
> what's next step?

Update the readme document and setup up the guidance for how & when to sync the templates.

**Comment by TommyLike** [comment]
chart is now in main repo. refer #347 for more requirements
