### ISSUE TITLE
There is a dead lock in the helm chart

### ISSUE THREAD

**Issue by zhifanggao** [volcano-sh/volcano#3237]
**What happened**:
install chart failed sometimes
**What you expected to happen**:
install  chart  successfully 
**How to reproduce it (as minimally and precisely as possible)**:
just install the helm chart in a cluster

**Anything else we need to know?**:

**Environment**:
- Volcano Version:1.7.0
- Kubernetes version (use `kubectl version`): v1.26.2
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):CentOS-7
- Kernel (e.g. `uname -a`):3.10.0-1160.el7.x86_64 
- Install tools: helm 
- Others:

It seems like the secret "volcano-admission-secret" is created by job `volcano-admission-init`。但是该job 需要 service volcano-admission-service，该service对应的deployment是volcano-admission, 该deployment又依赖于volcano-admission-secret。

I think it is a dead lock. sometimes installation will be failed

**Comment by Monokaix** [comment]
Is volcano deployment stucking in ContainerCreating state? volcano-admission will be running after volcano-admission-init completed in my env.
"volcano-admission-secret" is truly created by job volcano-admission-init, but it seems just use `volcano-admission-service` to sign  certificate and set `CN` field and do not need access the service, so seems there is no cycle dependency: )

**Comment by zhifanggao** [comment]
> Is volcano deployment stucking in ContainerCreating state? volcano-admission will be running after volcano-admission-init completed in my env. "volcano-admission-secret" is truly created by job volcano-admission-init, but it seems just use `volcano-admission-service` to sign certificate and set `CN` field and do not need access the service, so seems there is no cycle dependency: )

yes， the `volcano-admission `deployment is stucking in ContainerCreating state,  volcano-admission-init is not comleted ,error message likes this:

```
[root@node-10-21-10-161 volcano]# kubectl -n mpc describe job  mpc-kdp-volcano-9jjjw-admission-init
Events:
  Type     Reason        Age                  From            Message
  ----     ------        ----                 ----            -------
  Warning  FailedCreate  93s (x5 over 3m43s)  job-controller  Error creating: Internal error occurred: failed calling webhook "mutatepod.volcano.sh": failed to call webhook: Post "https://mpc-kdp-volcano-9jjjw-admission-service.mpc.svc:443/pods/mutate?timeout=10s": no endpoints available for service "mpc-kdp-volcano-9jjjw-admission-service"

```
for there is no `volcano-admission` pod in running state, so ep of service `volcano-admission-service` is null,   at the sametime the``volcano-admission` pod's error message is volume-cert Volume mount failed

**Comment by zhifanggao** [comment]
And check the job yaml

```
command: ["./gen-admission-secret.sh", "--service", "{{ .Release.Name }}-admission-service", "--namespace",
                    "{{ .Release.Namespace }}", "--secret", "{{.Values.basic.admission_secret_name}}"]
```

It looks like it use the service `volcano-admission-service`, once the service has no ep, I think  This command will be failed

**Comment by zhifanggao** [comment]
> Please paste the command output `kubectl get mutatingwebhookconfiguration volcano-admission-service-pods-mutate -oyaml` in your env.

Sorry, I can not reproduce it now . for my environment can not be reproduced it now. I pastes another environment which volcano installed failed either

```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: volcano
    meta.helm.sh/release-namespace: volcano-system
  creationTimestamp: "2023-10-08T07:14:29Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: volcano-admission-service-pods-mutate
  resourceVersion: "33940525"
  uid: 0d61051a-6dc8-4ce7-a8e0-33a91f28f7b2
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: volcano-admission-service
      namespace: volcano-system
      path: /pods/mutate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutatepod.volcano.sh
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - volcano-system
      - kube-system
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: NoneOnDryRun
  timeoutSeconds: 10
```

**Comment by Monokaix** [comment]
It seems that the volcano-admission-init call the webhook itself and volcano-admission endpoint is not ready.
volcano related pod should not call webhook and we have filter it in deployment yaml in https://github.com/volcano-sh/volcano/blob/d1e92ba95a69e9c56ea28975f74066595cbd69cb/installer/helm/chart/volcano/templates/webhooks.yaml#L20C1-L26C26
 it's filtered by namespace, pod in kube-system and volcano-system is filtered but you deploy volcano in default namespace, so the filter doesn't take effect, you can re -deploy it in  kube-system or volcano-system, and it's expected to work: )

**Comment by zhifanggao** [comment]
> It seems that the volcano-admission-init call the webhook itself and volcano-admission endpoint is not ready. volcano related pod should not call webhook and we have filtered it in deployment yaml in https://github.com/volcano-sh/volcano/blob/d1e92ba95a69e9c56ea28975f74066595cbd69cb/installer/helm/chart/volcano/templates/webhooks.yaml#L20C1-L26C26 it's filtered by namespace, pod in kube-system and volcano-system is filtered but you deploy volcano in mpc namespace, so the filter doesn't take effect, you can re-deploy it in kube-system or volcano-system, and it's expected to work: )
> 
> So it's not caused by secret cycle, but wrong admission webhook.

It is not reasonable , the code in https://github.com/volcano-sh/volcano/blob/d1e92ba95a69e9c56ea28975f74066595cbd69cb/installer/helm/chart/volcano/templates/webhooks.yaml#L20C1-L26C26 filtered the kube-system and release namespace

**Comment by zhifanggao** [comment]
> It seems that the volcano-admission-init call the webhook itself and volcano-admission endpoint is not ready. volcano related pod should not call webhook and we have filtered it in deployment yaml in https://github.com/volcano-sh/volcano/blob/d1e92ba95a69e9c56ea28975f74066595cbd69cb/installer/helm/chart/volcano/templates/webhooks.yaml#L20C1-L26C26 it's filtered by namespace, pod in kube-system and volcano-system is filtered but you deploy volcano in mpc namespace, so the filter doesn't take effect, you can re-deploy it in kube-system or volcano-system, and it's expected to work: )
> 
> So it's not caused by secret cycle, but wrong admission webhook.

and I redeployed it in volcano-system failed 
<img width="1311" alt="截屏2023-11-30 12 06 14" src="https://github.com/volcano-sh/volcano/assets/110591357/335f960d-6053-4115-9371-831586cd265b">


```
[root@node-10-21-10-161 volcano]# kubectl -n volcano-system get job volcano-system-kdp-volcano-drhfv-admission-init -oyaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    meta.helm.sh/release-name: volcano-system-kdp-volcano-drhfv
    meta.helm.sh/release-namespace: volcano-system
  creationTimestamp: "2023-11-30T04:00:34Z"
  generation: 1
  labels:
    app: volcano-admission-init
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: kdp-volcano-drhfv
    helm.toolkit.fluxcd.io/namespace: 0-mpc
  name: volcano-system-kdp-volcano-drhfv-admission-init
  namespace: volcano-system
  resourceVersion: "60618650"
  uid: 2b6fff90-fabb-4e22-bbf4-07e025f7d31a
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 2b6fff90-fabb-4e22-bbf4-07e025f7d31a
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 2b6fff90-fabb-4e22-bbf4-07e025f7d31a
        job-name: volcano-system-kdp-volcano-drhfv-admission-init
    spec:
      containers:
      - command:
        - ./gen-admission-secret.sh
        - --service
        - volcano-system-kdp-volcano-drhfv-admission-service
        - --namespace
        - volcano-system
        - --secret
        - volcano-admission-secret
        image: 10.21.10.197:5000/mpc/kdp/vc-webhook-manager:v1.7.0
        imagePullPolicy: IfNotPresent
        name: main
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: volcano-system-kdp-volcano-drhfv-admission
      serviceAccountName: volcano-system-kdp-volcano-drhfv-admission
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: "2023-11-30T04:00:51Z"
    lastTransitionTime: "2023-11-30T04:00:51Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 4
  ready: 0
  startTime: "2023-11-30T04:00:34Z"
  uncountedTerminatedPods: {}
[root@node-10-21-10-161 volcano]#
```

**Comment by Monokaix** [comment]
can you paste volcano-admission-init log?

**Comment by zhifanggao** [comment]
> can you paste volcano-admission-init log?

```
[root@node-10-21-10-161 crd]# kubectl logs volcano-system-kdp-volcano-lbmrm-admission-init-84t54  -n volcano-system
creating certs in dir /tmp
484BAF1CF87F0000:error:06800097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:crypto/asn1/a_mbstr.c:106:maxsize=64
req: Error adding subject name attribute "/CN=volcano-system-kdp-volcano-lbmrm-admission-service.volcano-system.svc"
[root@node-10-21-10-161 crd]#
```

**Comment by Monokaix** [comment]
can you also paste your helm install command? The service name is consistent with `Release.Name`.

**Comment by Monokaix** [comment]
> use `volcano-admission-service` to sign certificate and set `CN` field and do not need access the service

Right, but just like I said before, volcano-admission-init just use volcano-admission-service to sign certificate and set CN field and do not need access the service, the previous err is because of webhook, if we filtered volcano related pod, it can work, so it doesn’t look like a dependency issue: )

**Comment by zhifanggao** [comment]
> > use `volcano-admission-service` to sign certificate and set `CN` field and do not need access the service
> 
> Right, but just like I said before, volcano-admission-init just use volcano-admission-service to sign certificate and set CN field and do not need access the service, the previous err is because of webhook, if we filtered volcano related pod, it can work, so it doesn’t look like a dependency issue: )

Yes, it is . Thanks lot . I will close this issue
