### ISSUE TITLE
docker images used by volcano-sh/charts CI are outdated

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#324]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

Currently, the images used by https://github.com/volcano-sh/charts CI is always pulled from dockerhub and with latest TAG. 

Ref: https://github.com/volcano-sh/charts/blob/master/Makefile

But these images are not updated realtime, so i think we should build images when running volcano-sh/charts CI.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
AFAIK, we push the latest image into kind cluster for e2e test; what we need to do is to avoid download image from dockerhub.

**Comment by TommyLike** [comment]
this is related to my question of #323 , if the chart files can be moved back into volcano repo, then everything would be ok @k82cn

**Comment by k82cn** [comment]
what's next step?

**Comment by hzxuzhonghu** [comment]
duplicate let's keep #323
