### ISSUE TITLE
`json: unsupported type: func() error` occurred when using scheduler extender

### ISSUE THREAD

**Issue by zhixian82** [volcano-sh/volcano#3240]
**What happened**:
i register a scheduler extender to volcano. it works well in volcano version v1.7.0
and recently i upgrade my volcano to v1.8.1, when using scheduler extender，i found an error in the scheduler log: "json: unsupported type: func() error"

after studying the scheduler code，i found the error was occurred in the following line:
https://github.com/volcano-sh/volcano/blob/v1.8.1/pkg/scheduler/plugins/extender/extender.go#L166
https://github.com/volcano-sh/volcano/blob/v1.8.1/pkg/scheduler/plugins/extender/extender.go#L293

and then i found a func field was added to TaskInfo struct:
https://github.com/volcano-sh/volcano/blob/v1.8.1/pkg/scheduler/api/job_info.go#L136

and the Others field in the NodeInfo struct contains some func:
https://github.com/volcano-sh/volcano/blob/v1.8.1/pkg/scheduler/api/node_info.go#L346

and from[ json.Marshal](https://pkg.go.dev/encoding/json#Marshal)

```
Channel, complex, and function values cannot be encoded in JSON. Attempting to encode such a value causes Marshal to return an UnsupportedTypeError.
```

**Environment**:
- Volcano Version: v1.8.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
Yes, there is a compatibility need to fix. Also see issue https://github.com/volcano-sh/volcano/issues/3086
