### ISSUE TITLE
Contributor experience improvement

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#325]
In order to improve the contributor experience, we need many more docs:

- [ ] contributor guide: about how to contribute to valocano

- [ ] development guide: how to setup a development environment

- [ ] Testing: How to run kinds of tests, include ut, e2e.

- [ ] Code Conventions: coding style advice

**Comment by TommyLike** [comment]
ADD: volcano usecase document(Maybe add document for our sample document?)

**Comment by TommyLike** [comment]
> 2. volcano install improvement

/assign myself

**Comment by k82cn** [comment]
> volcano usecase document (Maybe add document for our sample document?)

Two improvements is necessary: contributor experience and user experience; that's more about user experiences. Both of them are important, but let's open another issue for user experiences.

**Comment by TommyLike** [comment]
> > volcano usecase document (Maybe add document for our sample document?)
> 
> Two improvements are necessary: contributor experience and user experience; that's more about user experiences. Both of them are important, but let's open another issue for user experiences.

# 335
