### ISSUE TITLE
Volcano website document have big question !

### ISSUE THREAD

**Issue by samzong** [volcano-sh/volcano#3252]
**What happened**:

- volcano website docs https://volcano.sh/en/docs/ is lag far behind current repo docs.
- both English and Chinese
- I wanted to make some contributions, but found PR to be inefficient https://github.com/volcano-sh/website/pull/314

**What you expected to happen**:

- Documentation is crucial for people who want to understand and learn about volcano.
- It should be ensured that the documents in the current warehouse are as consistent as possible. Not everyone will go to the current warehouse to view the documents
- Abandon website's repo OR make it great, I want to contribute to it.

**Comment by kerthcet** [comment]
Talked with @william-wang before, this is a great opportunity. 😃

**Comment by zhaizhch** [comment]
It's very important to update it for us to learn volcano!!!!

**Comment by Monokaix** [comment]
/close 
xref: https://github.com/volcano-sh/website/pull/319
