### ISSUE TITLE
volcano monitoring deploy have grafana dashboard failed

### ISSUE THREAD

**Issue by jeffreyyjp** [volcano-sh/volcano#3253]
**What happened**:
After [deploy volcano monitoring system ](https://github.com/volcano-sh/volcano?tab=readme-ov-file#install-monitoring-system), I found grafana pod has error: **logger=provisioning.dashboard type=file name=dashboards t=2023-12-07T10:07:21.415049184Z level=error msg="failed to load dashboard from " file=/var/lib/grafana/dashboards/volcano-globcal-overview-dashboard.json error="invalid character '{' in string escape code"**
And I checked the dashboard json in https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/templates/grafana.yaml#L49, and then validate the json on json website checker, there are errors below:
![image](https://github.com/volcano-sh/volcano/assets/17985592/38a21ecc-815d-4f84-835b-9119534ca3fb)

**What you expected to happen**:
Grafana dashboard json should be correct
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.8.1
- Kubernetes version (use `kubectl version`): v1.23
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:

**Comment by jeffreyyjp** [comment]
I tried to format the json, and get below:
![image](https://github.com/volcano-sh/volcano/assets/17985592/596273d8-f36c-4969-a670-a9fa8851f1ff)
![image](https://github.com/volcano-sh/volcano/assets/17985592/e984d3a1-4f1b-4557-98b9-295e358e6409)
![image](https://github.com/volcano-sh/volcano/assets/17985592/8843e001-b4de-4f45-923b-5fba9029f527)
![image](https://github.com/volcano-sh/volcano/assets/17985592/6cab254c-9beb-40d1-9bc3-64dac1c9facf)

**Comment by Monokaix** [comment]
Hi,  how about manually set double backslash of legendFormat like this？You can set all legendFormat field and test whether it works, if it can help, we will fix this.
`"legendFormat": "\\{\\{queue\\}\\}",`

**Comment by Monokaix** [comment]
Hi, I will fix this.
