### ISSUE TITLE
extender.go:168 Predicate failed with error json: unsupported type: func() error

### ISSUE THREAD

**Issue by We1less1111** [volcano-sh/volcano#3256]
I start my extender plugin, I found when json.Marshal(&PredicateRequest{Task: task, Node: node}) always with error like below.
Maybe when serialized , error can occur?
```
 extender.go:168] Predicate failed with error json: unsupported type: func() error.
######
json.Marshal(&PredicateRequest{Task: task, Node: node}) 
type TaskInfo struct {
        .....
	CustomBindErrHandler func() error
	....
}
```

**Comment by Shiva953** [comment]
Yes. Functions in go are NOT serializable by default since they represent executable code rather than data.

One of the two changes might be relevant here

1. Either exclude the `CustomBindErrHandler` field by using the `json:"-"` tag: 

```go
CustomBindErrHandler func() error `json:"-"`
```

2. or use a serializable type like string:

```go
CustomBindErrHandlerInfo string `json:"customBindErrHandlerInfo"`
```
and then define CustomBindErrHandlerInfo accordingly.

**Comment by We1less1111** [comment]
> Yes. Functions in go are NOT serializable by default since they represent executable code rather than data.
> 
> One of the two changes might be relevant here
> 
> 1. Either exclude the `CustomBindErrHandler` field by using the `json:"-"` tag:
> 
> ```go
> CustomBindErrHandler func() error `json:"-"`
> ```
> 
> 2. or use a serializable type like string:
> 
> ```go
> CustomBindErrHandlerInfo string `json:"customBindErrHandlerInfo"`
> ```
> 
> and then define `CustomBindErrHandlerInfo` accordingly.
> 
> I would like working on this issue btw.

I hope that the official can update this part of the code, otherwise extenders will be not supported??
```
pkg/scheduler/plugins/extender/extender.go
func (ep *extenderPlugin) OnSessionOpen(ssn *framework.Session) {
	if ep.config.onSessionOpenVerb != "" {
		err := ep.send(ep.config.onSessionOpenVerb, &OnSessionOpenRequest{
			Jobs:           ssn.Jobs,
			Nodes:          ssn.Nodes,
			Queues:         ssn.Queues,
			NamespaceInfo:  ssn.NamespaceInfo,
			RevocableNodes: ssn.RevocableNodes,
		}, nil)
.....
if ep.config.prioritizeVerb != "" {
		ssn.AddBatchNodeOrderFn(ep.Name(), func(task *api.TaskInfo, nodes []*api.NodeInfo) (map[string]float64, error) {
			resp := &PrioritizeResponse{}
			err := ep.send(ep.config.prioritizeVerb, &PrioritizeRequest{Task: task, Nodes: nodes}, resp)
....
```

**Comment by Shiva953** [comment]
> > Yes. Functions in go are NOT serializable by default since they represent executable code rather than data.
> > One of the two changes might be relevant here
> > 
> > 1. Either exclude the `CustomBindErrHandler` field by using the `json:"-"` tag:
> > 
> > ```go
> > CustomBindErrHandler func() error `json:"-"`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. or use a serializable type like string:
> > 
> > ```go
> > CustomBindErrHandlerInfo string `json:"customBindErrHandlerInfo"`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then define `CustomBindErrHandlerInfo` accordingly.
> > I would like working on this issue btw.
> 
> I hope that the official can update this part of the code, otherwise extenders will be not supported??
> 
> ```
> pkg/scheduler/plugins/extender/extender.go
> func (ep *extenderPlugin) OnSessionOpen(ssn *framework.Session) {
> 	if ep.config.onSessionOpenVerb != "" {
> 		err := ep.send(ep.config.onSessionOpenVerb, &OnSessionOpenRequest{
> 			Jobs:           ssn.Jobs,
> 			Nodes:          ssn.Nodes,
> 			Queues:         ssn.Queues,
> 			NamespaceInfo:  ssn.NamespaceInfo,
> 			RevocableNodes: ssn.RevocableNodes,
> 		}, nil)
> .....
> if ep.config.prioritizeVerb != "" {
> 		ssn.AddBatchNodeOrderFn(ep.Name(), func(task *api.TaskInfo, nodes []*api.NodeInfo) (map[string]float64, error) {
> 			resp := &PrioritizeResponse{}
> 			err := ep.send(ep.config.prioritizeVerb, &PrioritizeRequest{Task: task, Nodes: nodes}, resp)
> ....
> ```

I think the root cause of this problem lies in `pkg/scheduler/api/job_info.go` : 
https://github.com/volcano-sh/volcano/blob/29e2bbf52a0a164c1991d6576c27baa0b5a786f2/pkg/scheduler/api/job_info.go#L136

**Comment by lowang-bh** [comment]
https://github.com/volcano-sh/volcano/pull/3162 already support this one. @Shiva953
