### ISSUE TITLE
Can we add more dynamic support for node selector (like regular matching)?

### ISSUE THREAD

**Issue by noobzzw** [volcano-sh/volcano#3261]
#### What would you like to be added:
Node selector allow volcano to schedule workloads based on the Nodes with specific label, the current Volcano node selector can only select a fixed node label and label value at startup，can we add some more flexible configurations, such as supporting regular matching for label value or label key

#### Why is this needed:
Many times, the addition of a new department implies the need to create a new dedicated resource pool. Each exclusive resource pool will have its own node label and label value. Whenever a new resource pool is added, it requires restarting Volcnao and adding the corresponding node label and value to the startup parameters, which appears to be less elegant.

**Comment by Monokaix** [comment]
Hi, you mean volcano-scheduler param `node-selector`? Seems that you have two requirement, the first is support regular matching and the second is hot-update of this param.

**Comment by noobzzw** [comment]
> Hi, you mean volcano-scheduler param `node-selector`? Seems that you have two requirement, the first is support regular matching and the second is hot-update of this param.
Hi, I'm sorry for the misunderstanding a few days ago. In my scenario, I realized that I can use a fixed label and key to allow the Volcano Scheduler to schedule on that node. By using different labels and keys, all pods within the department can be scheduled to specific nodes. However, I would like to know your opinion on whether enhancing the flexibility of the node-selector is a reasonable suggestion.

**Comment by Monokaix** [comment]
> > Hi, you mean volcano-scheduler param `node-selector`? Seems that you have two requirement, the first is support regular matching and the second is hot-update of this param.
> 
> Hi, I'm sorry for the misunderstanding a few days ago. In my scenario, I realized that I can use a fixed label and key to allow the Volcano Scheduler to schedule on that node. By using different labels and keys, all pods within the department can be scheduled to specific nodes. However, I would like to know your opinion on whether enhancing the flexibility of the node-selector is a reasonable suggestion.

I think restarting volcano when node selector changed is reasonable because volcano should keep a clean cache when node information changed.

**Comment by noobzzw** [comment]
> > > Hi, you mean volcano-scheduler param `node-selector`? Seems that you have two requirement, the first is support regular matching and the second is hot-update of this param.
> > 
> > 
> > Hi, I'm sorry for the misunderstanding a few days ago. In my scenario, I realized that I can use a fixed label and key to allow the Volcano Scheduler to schedule on that node. By using different labels and keys, all pods within the department can be scheduled to specific nodes. However, I would like to know your opinion on whether enhancing the flexibility of the node-selector is a reasonable suggestion.
> 
> I think restarting volcano when node selector changed is reasonable because volcano should keep a clean cache when node information changed.

Thank you for your response. I will close this issue accordingly.
