### ISSUE TITLE
[ut enhancement] Replace ut's scheduler cache with mockSchedulerCache

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3270]
#### What would you like to be added:

Use mockSchedulerCache return by `NewDefaultMockSchedulerCache ` in PR https://github.com/volcano-sh/volcano/pull/3269

#### Why is this needed:

1. simplify the code in UT
2. fixes some UTs which doesn't run actually

### Plan to enhance UTs

- [x] 1. support mockSchedulerCache, have done in https://github.com/volcano-sh/volcano/pull/3269 
- [x] 2. Unify the UT validation process by defining a UT test struct, which include all resource need to do test, such as pg, pods, nodes, queues, and expect results for binding, pipelined, evicted.
  - [x] 2.1 define a CommonStruct, a init func to load conf, and a `func runTest` to do test and validation
  - [x] 2.2 rewrite each package's UT

Finaly, in future commiter only need to concern about UT design when submit a pr

**Comment by lowang-bh** [comment]
Now, we have a UTFramwork package as MR#3343

We can continue on the refact of UTs. Just do as examples PR #3341 #3342

**Comment by googs1025** [comment]
Is this issue still active?

**Comment by lowang-bh** [comment]
> Is this issue still active?

Yes, you can continue working on the left packages.
