### ISSUE TITLE
Bug in volcano scheduler metrics for queue pod group count 

### ISSUE THREAD

**Issue by hy00nc** [volcano-sh/volcano#3293]
**What happened**:

When there is only one job (pod group) running on a queue, and if that job is deleted the metrics does not get updated.
That said, `queue_pod_group_running_count` is `1` when a job is running, and if that job is deleted for some reason, it still remains 1, not updated to 0. Same for other metrics like `queue_pod_group_pending_count`..

**What you expected to happen**:

I expect the `queue_pod_group_running_count` turn to `0`, since the running job has been deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Remove all the existing volcano job or pod groups if any, then follow the instructions below:
1. Try creating a VolcanoJob that sleeps infinitely -> Check if the `queue_pod_group_running_count` has been updated to 1.
2. Try deleting that VolcanoJob -> Check the `queue_pod_group_running_count` if it is still 1.

**Environment**:
- Volcano Version: v1.8.0

**Comment by hy00nc** [comment]
Seems the the metrics updating is not triggered when there is zero job in [here](https://github.com/volcano-sh/volcano/blob/67cabf78a6a50751287eecedd8e050c5977ebb40/pkg/scheduler/plugins/proportion/proportion.go#L168-L178).
Perhaps we have to add a code to set default value zero for all the queue-related metrics and then trigger the metrics update if there is any job.

**Comment by lowang-bh** [comment]
> Seems the metrics update is not triggered when there is zero job

Yeah，current code can not trigger metrics update if no jobs in queue.

**Comment by Monokaix** [comment]
> > Seems the metrics update is not triggered when there is zero job
> 
> Yeah，current code can not trigger metrics update if no jobs in queue.

Maybe we can move these codes to `OnSessionClose` to cover all queues' metrics.
https://github.com/volcano-sh/volcano/blob/67cabf78a6a50751287eecedd8e050c5977ebb40/pkg/scheduler/plugins/proportion/proportion.go#L168-L178

**Comment by lowang-bh** [comment]
It will still has same problems, because those queues who has no jobs in them will not be iterated using `for _, attr := range pp.queueOpts`

**Comment by Monokaix** [comment]
> It will still has same problems, because those queues who has no jobs in them will not be iterated using `for _, attr := range pp.queueOpts`

If no job in queue, itwill be zero, right？

**Comment by lowang-bh** [comment]
> > It will still has same problems, because those queues who has no jobs in them will not be iterated using `for _, attr := range pp.queueOpts`
> 
> If no job in queue, it will be zero, right？

no, those queues don't include in pp.queueOpts.

**Comment by Monokaix** [comment]
> > > It will still has same problems, because those queues who has no jobs in them will not be iterated using `for _, attr := range pp.queueOpts`
> > 
> > 
> > If no job in queue, it will be zero, right？
> 
> no, those queues aren't included in pp.queueOpts.

I mean that queue not present in pp.queueOpts indicates its job number is zero and we can update them to zero directly.

**Comment by ipsum-0320** [comment]
Has this problem been resolved? I am willing to tackle it.
