### ISSUE TITLE
how to set disable 'weight' param for queue setting?

### ISSUE THREAD

**Issue by rewonderful** [volcano-sh/volcano#3305]
I want to  disable 'weight' in queue settings, only use the hard restriction 'capability'.
It is straight when only have hard restriction while soft restriction makes it confused when find out why pods not scheduled, is there any way to disable 'weight' ?
<img width="923" alt="image" src="https://github.com/volcano-sh/volcano/assets/17673536/09fbe49c-3216-4d6c-a572-f82ea1ae3979">

**Comment by Monokaix** [comment]
The queue capability is an independent and complete feature set, and it can maximize cluster resource utilization, you can check volcano scheduler logs to find queue's deseved resources and then find why pod not scheduled.
Also you can set queue's `spec.reclaimable` false to disable queue reclaim and then it will be more intuitive.

**Comment by Monokaix** [comment]
You can replace `proportion` plugin with `capacity` now: )
