### ISSUE TITLE
when Create Queue ,Queue has no status

### ISSUE THREAD

**Issue by chron-xie** [volcano-sh/volcano#3314]
normal-queue.yaml
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: normal-queue
spec:
  reclaimable: true
  weight: 2
  capability:
    cpu: "2"
    memory: "2Gi"
```

when run ` kubectl apply -f  normal-queue.yaml` 
hints: queue.scheduling.volcano.sh/normal-queue created, But queue has no status

check queue information  `kubectl get queue normal-queue -o yaml`
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  creationTimestamp: "2024-01-31T07:51:35Z"
  generation: 1
  name: normal-queue
  resourceVersion: "1521600"
  uid: 70380811-9566-4152-86da-205c1b9b8e6d
spec:
  capability:
    cpu: "2"
    memory: 2Gi
  reclaimable: true
  weight: 2
```

volcano-controller pod logs:

-----log begin-------
I0131 07:45:10.614660       1 queue_controller_action.go:35] Begin to sync queue normal-queue.
E0131 07:45:10.619276       1 queue_controller_action.go:79] Failed to update status of Queue normal-queue: Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value.
I0131 07:45:10.619295       1 queue_controller_action.go:80] End sync queue normal-queue.
I0131 07:45:10.619305       1 queue_controller.go:224] Finished syncing queue normal-queue (4.693172ms).
I0131 07:45:10.619315       1 queue_controller.go:258] Error syncing queue request Queue: normal-queue, Job: /, Task:, Event:OutOfSync, ExitCode:0, Action:SyncQueue, JobVersion: 0 for sync queue normal-queue failed for Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value, event is OutOfSync, action is SyncQueue.
I0131 07:45:20.859710       1 queue_controller.go:242] Begin execute SyncQueue action for queue normal-queue, current status 
I0131 07:45:20.859744       1 queue_controller_action.go:35] Begin to sync queue normal-queue.
E0131 07:45:20.864528       1 queue_controller_action.go:79] Failed to update status of Queue normal-queue: Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value.
I0131 07:45:20.864554       1 queue_controller_action.go:80] End sync queue normal-queue.
I0131 07:45:20.864565       1 queue_controller.go:224] Finished syncing queue normal-queue (4.870691ms).
I0131 07:45:20.864576       1 queue_controller.go:258] Error syncing queue request Queue: normal-queue, Job: /, Task:, Event:OutOfSync, ExitCode:0, Action:SyncQueue, JobVersion: 0 for sync queue normal-queue failed for Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value, event is OutOfSync, action is SyncQueue.
I0131 07:45:41.344706       1 queue_controller.go:242] Begin execute SyncQueue action for queue normal-queue, current status 
I0131 07:45:41.344737       1 queue_controller_action.go:35] Begin to sync queue normal-queue.
E0131 07:45:41.348947       1 queue_controller_action.go:79] Failed to update status of Queue normal-queue: Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value.
I0131 07:45:41.348961       1 queue_controller_action.go:80] End sync queue normal-queue.
I0131 07:45:41.348967       1 queue_controller.go:224] Finished syncing queue normal-queue (4.276124ms).
I0131 07:45:41.348974       1 queue_controller.go:258] Error syncing queue request Queue: normal-queue, Job: /, Task:, Event:OutOfSync, ExitCode:0, Action:SyncQueue, JobVersion: 0 for sync queue normal-queue failed for Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value, event is OutOfSync, action is SyncQueue.
I0131 07:46:22.310096       1 queue_controller.go:242] Begin execute SyncQueue action for queue normal-queue, current status 
I0131 07:46:22.310153       1 queue_controller_action.go:35] Begin to sync queue normal-queue.
E0131 07:46:22.314979       1 queue_controller_action.go:79] Failed to update status of Queue normal-queue: Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value.
I0131 07:46:22.314996       1 queue_controller_action.go:80] End sync queue normal-queue.
I0131 07:46:22.315003       1 queue_controller.go:224] Finished syncing queue normal-queue (4.92911ms).
I0131 07:46:22.315011       1 queue_controller.go:258] Error syncing queue request Queue: normal-queue, Job: /, Task:, Event:OutOfSync, ExitCode:0, Action:SyncQueue, JobVersion: 0 for sync queue normal-queue failed for Queue.scheduling.volcano.sh "normal-queue" is invalid: status.allocated: Required value, event is OutOfSync, action is SyncQueue.
---------log end--------

**Environment**:
- Volcano Version:  v1.7.0
- Kubernetes version (use `kubectl version`): v1.26
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):  Ubuntu 20.04.6 
- Kernel (e.g. `uname -a`):  Linux k8s-master-gpu-1 5.4.0-166-generic 
- Install tools: 
- Others:

**Comment by halcyon-r** [comment]
@chron-xie Hello, I encountered a similar problem. Have you found the reason for this problem?
