### ISSUE TITLE
mpimaster应该分配多大内存合适

### ISSUE THREAD

**Issue by HelloDylan** [volcano-sh/volcano#3323]
请问使用volcano发起mpi job的时候mpimaster是否参与计算呢，如果不参与计算的话，一般给mpimaster多大的内存才合适，我这边尝试给512mb，发现有时候会出现oom

**Comment by hwdef** [comment]
This is about your program, not volcano.

**Comment by HelloDylan** [comment]
什么情况下会呢，rand 0是代表第一个worker，还是master呢

**Comment by HelloDylan** [comment]
抱歉，我的问题，mpiexec命令忘记加--host参数，导致代码跑在master上面
