### ISSUE TITLE
Why is it necessary to set enablePreemptable to 'false' to succeed in preemption?

### ISSUE THREAD

**Issue by bsyonline** [volcano-sh/volcano#3332]
**What happened**:
i'm testing preemption，i used 3 priorityClass: high，med，low。
first，i start vcjob in the order high-low-med，then high-job running，low-job and med-job pendding（because the resource can only run one job at a time）
the second step, i delete high-job and then med-job is running (it is correct)
the third step，i restart high-job，i expect high-job is running and med-job is pendding but is not, high-job cat not preempt successed.
my volcano-scheduler.conf is:
actions: "enqueue, allocate, preempt, backfill"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: overcommit
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
  - name: binpack

so,i change the scheduler config like this:
actions: "enqueue, allocate, preempt, backfill"
tiers:
- plugins:
  - name: priority
  - name: gang
    enablePreemptable: false
  - name: conformance
- plugins:
  - name: overcommit
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
  - name: binpack

add enablePreemptable and set false. 
when volcano restarted, rerun the above case，now high-job can preempt succeed .

why must set enablePreemptable is false explicitly? Literally speaking, isn't 'enablePreemptable: true' more reasonable?

**Environment**:
- Volcano Version: 1.7
- Kubernetes version (use `kubectl version`): 1.23.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
Because only extra tasks which are more than minAvailable in a job can be evicted when gang plugin enable peemptable.
![image](https://github.com/volcano-sh/volcano/assets/21003791/f28f1cde-d4ac-4050-9591-ed59057e2ee8)

**Comment by bsyonline** [comment]
> Because only extra tasks which are more than minAvailable in a job can be evicted when gang plugin enable peemptable. ![image](https://private-user-images.githubusercontent.com/21003791/309132393-f28f1cde-d4ac-4050-9591-ed59057e2ee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTIxMjYsIm5iZiI6MTcwOTc5MTgyNiwicGF0aCI6Ii8yMTAwMzc5MS8zMDkxMzIzOTMtZjI4ZjFjZGUtZDRhYy00MDUwLTk1OTEtZWQ1OTA1N2UyZWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2MTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMGY2ZDhhMDVjZTZlM2MyZDliMGY1YmZkZmQ1NTNkMTQ3MTVlN2I0MDQ2ODUyNTE1OTkyMWFmOWIxNTY3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EE-X340gbT-W9a4cIW2SkQ7kebwQqi2oPkGFqkO0AUI)

thanks for your replay

**Comment by Monokaix** [comment]
A little addition: setting it to false means turning off the impact of gang on preemption. In most scenarios, there is no need to consider gang when preempting.

**Comment by Monokaix** [comment]
If there is no problem, this issue will be closed.
