### ISSUE TITLE
User experience improvement

### ISSUE THREAD

**Issue by TommyLike** [volcano-sh/volcano#335]
/kind feature

- [ ] 1. Add document for volcano usecases explanation.
- [x] 2. Provide a convenient way for end user to install and use volcano(**finished**).
- [x] 3. Add system requirements for volcano

**Comment by hzxuzhonghu** [comment]
I deployed  yaml generated by `make generate-yaml` from master.

But unfortunately, a pod failed to start.  
```
kubectl  -n volcano-system logs volcano-admission-fd4b955cf-nsn4r 
flag provided but not defined: -webhook-namespace
Usage of /vc-admission:
  -alsologtostderr
    	log to standard error as well as files

```

 @asifdxtreme I have an idea, we have to push the latest image every day built from the master branch. This can be done by a bot. wdyt ? cc @k82cn @TommyLike

**Comment by hzxuzhonghu** [comment]
cc @SrinivasChilveri we need to update volcano website

**Comment by TommyLike** [comment]
> I deployed yaml generated by `make generate-yaml` from master.
> 
> But unfortunately, a pod failed to start.
> 
> ```
> kubectl  -n volcano-system logs volcano-admission-fd4b955cf-nsn4r 
> flag provided but not defined: -webhook-namespace
> Usage of /vc-admission:
>   -alsologtostderr
>     	log to standard error as well as files
> ```
> 
> @asifdxtreme I have an idea, we have to push the latest image every day built from the master branch. This can be done by a bot. wdyt ? cc @k82cn @TommyLike

For your case @hzxuzhonghu , I think we need mention in the document. `make generate-yaml` will use the latest image in default. therefore he need load the latest images (maybe from local built)  into his cluster. or specify the image tag when execute command:
```
make TAG=xxxx generate-yaml
```
```

**Comment by TommyLike** [comment]
When installing volcano helm chart v1 with repo. the default image tag in value file is latest. it's possible that the image would mismatch with the release yaml files. Personally I think we need update the image tag value or other necessay values when publish. 
@asifdxtreme  Do you mind: 
1. update the v1 zip file to use the v1 image in default
2. and if possible integrate the helm chart publish workflow into our Travis Build process #334?  


cc @hzxuzhonghu  @k82cn

**Comment by k82cn** [comment]
We only need to manage released images. If using master branch, user need to build images himself; it's too heavy to mange latest images :)

**Comment by TommyLike** [comment]
>  2. Provide a convenient way for end user to install and use volcano.

This is done via #346
