### ISSUE TITLE
scheduler crashes occasionally

### ISSUE THREAD

**Issue by Wang-Kai** [volcano-sh/volcano#3370]
**What happened**:

The volcano scheduler crashes occasionally, which due to IgnoredDevicesList slice isn’t concurrency secure.

<img width="1318" alt="image" src="https://github.com/volcano-sh/volcano/assets/13144386/26873b51-a6f9-4232-a6a6-89ae358071c4">

**What you expected to happen**:

Don't panic

**How to reproduce it (as minimally and precisely as possible)**:

The demo like this:

```go
package main

import (
	"strings"
	"time"
)

func main() {
	var vals []string
	go func() {
		for {
			for _, v := range vals {
				strings.Compare(v, "a")
			}
		}
	}()

	go func() {
		for {
			vals = []string{}
			vals = append(vals, "a", "b")
		}
	}()
	time.Sleep(time.Hour)
}
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v1.8.2
- Kubernetes version (use `kubectl version`): v1.20
- Cloud provider or hardware configuration: 128C 256G
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9
- Kernel (e.g. `uname -a`):Linux 5.10.0
- Install tools: kubectl
- Others:

**Comment by Monokaix** [comment]
fixed by https://github.com/volcano-sh/volcano/pull/3325
