### ISSUE TITLE
E2E Test Scenarios for Command Line vcctl --help option

### ISSUE THREAD

**Issue by thandayuthapani** [volcano-sh/volcano#338]
List of missing Test Scenarios to be added to test vkctl help option
- [x] Command: vcctl --help
- [x] Command: vcctl job --help
- [x] Command: vcctl job list --help
- [x] Command: vcctl job suspend -n {$JobName} --help
- [x] Command: vcctl job resume -n {$JobName} --help
- [x] Command: vcctl job run --help

**Comment by k82cn** [comment]
we should change vkctl to vcctl
