### ISSUE TITLE
Can the Devices interface add a scoring function

### ISSUE THREAD

**Issue by ZDWWWWW** [volcano-sh/volcano#3381]
#### What would you like to be added:
For the Devices interface add a scoring function.

#### Why is this needed:
I can learn how to implement my own device from the following design documents.
[https://github.com/volcano-sh/volcano/blob/master/docs/design/device-sharing.md](url)
[https://github.com/volcano-sh/volcano/blob/master/docs/user-guide/how_to_use_vgpu.md](url)

The current devices interface only provides the FilterNode function, which will predicate suitable nodes for me. For my current scenario, it is necessary to select the best node from the suitable nodes, and the current devices interface does not seem to provide such a function. So I want to know if adding a scoring function to the devices interface is necessary.

**Comment by Monokaix** [comment]
There is already a pr https://github.com/volcano-sh/volcano/pull/3210 enhanced this, and @archlitchi is working on this: )

**Comment by Monokaix** [comment]
related PR: https://github.com/volcano-sh/volcano/pull/3471
