### ISSUE TITLE
docs: build custom-plugin in docker not working

### ISSUE THREAD

**Issue by Vacant2333** [volcano-sh/volcano#3385]
**What happened**:
run [this command](https://github.com/Vacant2333/volcano/blob/a5363c86d89ac4109e2c5f2cdd5f9a72e466a8dd/example/custom-plugin/README.md?plain=1#L9) for build the example `custom-plugin`:

```bash
docker run -v `pwd`:/work golang:1.14-alpine sh -c "cd /work && apk add musl-dev gcc && go build -buildmode=plugin magic.go"
```

will cause:
![5077b9783c348f9a248a4e2e9ab08191](https://github.com/volcano-sh/volcano/assets/19872346/ee979063-622b-48d4-98bb-45f998383aa4)

and i find out that we have the `go.mod` file before:
https://github.com/volcano-sh/volcano/pull/1218/files#diff-98b4a278f2b96122392377740a91e7d348ecbf1323e06be2265c3e3ecf4f09bb

but we remove the `go.mod` at this pr:
https://github.com/volcano-sh/volcano/pull/1988

im not sure **how to resoulve** this problem, i have try update the command like:
```bash
docker run -v `pwd`:/work golang:1.20-alpine sh -c "cd /work && apk add musl-dev gcc git && go mod init custom-plugin && go mod tidy && go build -buildmode=plugin magic.go"
```

but it will cause:
<img width="1016" alt="image" src="https://github.com/volcano-sh/volcano/assets/19872346/46b2ac75-2bf0-4ed8-8c83-909963e240a8">

or maybe we can run this command at `/volcano`, just like:
```bash
docker run -v `pwd`:/volcano golang:1.20.1-alpine sh -c "cd /volcano/example/custom-plugin && apk add musl-dev gcc && go mod tidy && go build -buildmode=plugin magic.go"
```

i didnt find a good way to resoulve this problem, can u tell me a good way to fix it, and **im happy to raise a pr to fix it**!

**What you expected to happen**:
Build `custom-plugin` in docker

**How to reproduce it (as minimally and precisely as possible)**:

```bash
cd example/custom-plugin
docker run -v `pwd`:/work golang:1.20-alpine sh -c "cd /work && apk add musl-dev gcc git && go mod download && go build -buildmode=plugin magic.go"
```

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): MacOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Monokaix** [comment]
I think docker build command should change to something like `docker run -v `pwd`:/work golang:1.20-alpine sh -c "cd /work && apk add musl-dev gcc && go build -buildmode=plugin example/custom-plugin/magic.go` and we should also change readme file to let user run a complete example.

**Comment by Vacant2333** [comment]
> I think docker build command should change to something like `docker run -v `pwd`:/work golang:1.20-alpine sh -c "cd /work && apk add musl-dev gcc && go build -buildmode=plugin example/custom-plugin/magic.go` and we should also change readme file to let user run a complete example.

agree! i will raise a pr to fix it
