### ISSUE TITLE
compare task order with uid as the default sort method, when task index parsed failed, such as "pod1" vs "pod2"

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3386]
#### What would you like to be added:

sort task with uid, such as "pod1" before "pod2", as default

#### Why is this needed:
The origin code has this feature but it is removed in pr https://github.com/volcano-sh/volcano/pull/1898
I think this is necessary and it is more clear which one has higher priority when `GetPodIndexUnderTask` failed.

**Comment by Monokaix** [comment]
you mean just compare pod name directly?

**Comment by lowang-bh** [comment]
> you mean just compare pod name directly?

No, add it as the last default sort method like the origin code, when all other method failed to find out the result.

![image](https://github.com/volcano-sh/volcano/assets/21003791/e21cb3fb-6eb4-41c7-bb4e-10e9b1683a3e)

**Comment by Monokaix** [comment]
You can work on that: )

**Comment by ipsum-0320** [comment]
I want to give it a try! /assign
