### ISSUE TITLE
queue is put back before a job's resource allocating

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3407]
**What happened**:
In allocate action, a queue is put back to queues priority queue before the job's resource allocated, which will cause the queue is sorted not as expected as drf/proportion plugin really want to do.

https://github.com/volcano-sh/volcano/blob/b53d6d8c55c66ed98ca9d875b6ba9e0f6baef286/pkg/scheduler/actions/allocate/allocate.go#L155-L164

**What you expected to happen**:

Put back the queue to priority queue after job's resource allocating finished.

**How to reproduce it (as minimally and precisely as possible)**:
1. create two queues with same weight, queue-1 has a running job-a, queue-2 has no running jobs
2. submit a  job-b whose resource request is large than job-a, to queue-1 and queue-2,  and then submit another job-c whose request is same as job-a to queue-2; As queue-2's share is 0 and job in queue'2 will be pop from queues and allocated first (now all is as expected)
4. next step, job-b in queue-1 should be allocated before job-c in queue-2 (which is expected), because queue-1's share value is smaller than queue-2's .

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by panoswoo** [comment]
> submit a job-b whose resource request is large than job-a, to queue-1 and queue-2,
I have a query. Is it possible to submit A job to TWO queues?

**Comment by panoswoo** [comment]
> 2. submit a  job-b whose resource request is large than job-a, to queue-1 and queue-2,  

I have a query. Is it possible to submit a job to two queues simultaneously?

**Comment by lowang-bh** [comment]
> > 2. submit a  job-b whose resource request is large than job-a, to queue-1 and queue-2,
> 
> I have a query. Is it possible to submit a job to two queues simultaneously?

You can use a yaml to submit, and increase the  scheduling cycle time in start  up  parameters.

**Comment by Monokaix** [comment]
What's the expected result？allocate job-c first then job-b？

**Comment by lowang-bh** [comment]
> What's the expected result？allocate job-c first then job-b？

Please see the detail testcase in PR #3413
