### ISSUE TITLE
[good first issue]fix reclaim ut error

### ISSUE THREAD

**Issue by guoqinwill** [volcano-sh/volcano#3414]
**What happened**:
During the CI execution, an error occurred in the reclaim test of unit tests. This issue was introduced after this PR：https://github.com/volcano-sh/volcano/commit/4c129c964d8332d5e0b5e28336dc1cc9793832d2
![image](https://github.com/volcano-sh/volcano/assets/151122323/36a198e0-cc7d-430c-9abf-df78bd79d2fd)

**What you expected to happen**:
Running unit tests pass

**How to reproduce it (as minimally and precisely as possible)**:
When submitting a PR, unit tests randomly encounter errors.

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
have fixed by #3408
