### ISSUE TITLE
Enhance issue template

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3420]
#### What would you like to be added:

Add another issue template like `Question` 
#### Why is this needed:
There are only two types issue bug & feature in volcano, when users have questions about volcnao, they usually choose a bug type, but usually it's only some questions instead of a bug, so we should classify issues more clearly.

We can refer to https://github.com/karmada-io/karmada/blob/master/.github/ISSUE_TEMPLATE/question.md

**Comment by Aryakoste** [comment]
Hello @Monokaix. I would like to work on this issue.

**Comment by hwdef** [comment]
We can use github's discussion function, issue is only used to track bugs

**Comment by Monokaix** [comment]
> We can use github's discussion function, issue is only used to track bugs

It's a choice, but some users are usded to use issue and a label bug is added, which causes too many bug issues but actually not.
