### ISSUE TITLE
nodegroup plugins don't use

### ISSUE THREAD

**Issue by ffz12** [volcano-sh/volcano#3424]
**What happened**:

When using the nodegroup plugin, the plugin is not recognized after it is added to the configmap of the volcano-scheduler-configmap. Check the volcano-scheduler-pod and the error E0418 07:21:42.912033 1 framework.go:40] Failed to get plugin nodegroup.

**What you expected to happen**:

The nodegroup plug-in can be used normally.

**How to reproduce it (as minimally and precisely as possible)**:

1、Installed volcano
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml

2、Modify the volcanic-scheduler-configmap configuration file as follows:
kind: ConfigMap
apiVersion: v1
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system 
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill, reclaim, preempt"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: nodegroup
      - name: binpack
     

3、Change the log printing level of Volcanic-Scheduler to 2

4、The volcanic-Scheduler related pod is restarted

 kubectl get po -n volcano-system | grep sche|awk '{print $1}'|xargs kubectl delete po  -n volcano-system

5、View the logs of Volcanic-Scheduler

kubectl get po -n volcano-system | grep sche|awk '{print $1}'|xargs kubectl logs  -n volcano-system

E0418 07:50:00.053934       1 framework.go:40] Failed to get plugin nodegroup.
E0418 07:50:01.071860       1 framework.go:40] Failed to get plugin nodegroup.
E0418 07:50:02.089626       1 framework.go:40] Failed to get plugin nodegroup.
E0418 07:50:03.118339       1 framework.go:40] Failed to get plugin nodegroup.
E0418 07:50:04.134342       1 framework.go:40] Failed to get plugin nodegroup.
E0418 07:50:05.150473       1 framework.go:40] Failed to get plugin nodegroup.

**Anything else we need to know?**:
Reference code location：
https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/nodegroup/nodegroup.go
147 lines
//
// User should specify arguments in the config in this format:
//
//  actions: "reclaim, allocate, backfill, preempt"
//  tiers:
//  - plugins:
//    - name: priority
//    - name: gang
//    - name: conformance
//  - plugins:
//    - name: drf
//    - name: predicates
//    - name: proportion
//    - name: nodegroup

**Environment**:
- Volcano Version:  latest
- Kubernetes version (use `kubectl version`):  v1.23.10
- Cloud provider or hardware configuration:   
- OS (e.g. from /etc/os-release):   CentOS Linux release 7.9.2009 
- Kernel (e.g. `uname -a`):   3.10.0-1160.45.1.el7.x86_64
- Install tools:  
- Others:
-

**Comment by lowang-bh** [comment]
Please try the latest code in master branch.

**Comment by lowang-bh** [comment]
https://github.com/volcano-sh/volcano/pull/3402 has fixed it.

**Comment by ffz12** [comment]
Have been solved
