### ISSUE TITLE
Migrate vgpu to a seperate project

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3427]
#### What would you like to be added:
Migrate vgpu related features to external, and volcano just supports scheduling capabilities.

#### Why is this needed:
In order to support vgpu deeply as a whole solution, the vgpu feature will be migrated to a dedicated project here. https://github.com/Project-HAMi/HAMi-core

**Comment by Superskyyy** [comment]
Just a question, how about Ascend vNPU? There's an Ascend-device Plugin hosted in HAMi org too.
