### ISSUE TITLE
export the logs of Volcano components when the e2e test workflow fails

### ISSUE THREAD

**Issue by panoswoo** [volcano-sh/volcano#3429]
#### What would you like to be added:
print the logs of volcano components in clean up stage
https://github.com/volcano-sh/volcano/blob/ab2def642f6e5e594b9fbdf0176f3426270826ed/hack/run-e2e-kind.sh#L75-L86
, the logs of volcano components are generated by
https://github.com/volcano-sh/volcano/blob/ab2def642f6e5e594b9fbdf0176f3426270826ed/hack/run-e2e-kind.sh#L68-L73
when e2e test is failed
https://github.com/volcano-sh/volcano/blob/ab2def642f6e5e594b9fbdf0176f3426270826ed/hack/run-e2e-kind.sh#L160-L163

#### Why is this needed:

when the e2e test is failed, we need those logs for troube shorting

**Comment by Monokaix** [comment]
You're welcome to do that.

**Comment by calvin0327** [comment]
@panoswoo @Monokaix  Is this at work? I can do this

**Comment by panoswoo** [comment]
> @panoswoo @Monokaix Is this at work? I can do this

sorry, I have already started this
