### ISSUE TITLE
a potential security risk

### ISSUE THREAD

**Issue by HouqiyuA** [volcano-sh/volcano#3437]
I found that the ClusterRole of the project has the permission to patch the node, which poses certain security risks, so I would like to ask whether this project requires the permission to patch the node. If it is not necessary, it should be deleted.

**Comment by Monokaix** [comment]
Yeah，it's used here https://github.com/volcano-sh/volcano/blob/9ac82ff0d8acdc26e75eb67ff80c5171f4461227/pkg/scheduler/api/devices/nvidia/vgpu/utils.go#L84
