### ISSUE TITLE
totalResource calculation error in proportion plugin

### ISSUE THREAD

**Issue by bysph** [volcano-sh/volcano#3444]
# Issue Description:

I found proportion plugin has some issues:
1. **It does not consider node label isolation scenarios**: such as impala nodes being unavailable for use by the spark queue, but are still factored into the calculation of available resources for the flink queue.  (I think the node-group plugin may also fails to consider this)
2. **it does not filter out cordoned nodes**
3. **it does not consider about nodeSelectors**: some nodes does not managed by volcano will also be included in the calculation.
4. **It does not consider multi-scheduler scenarios**: for example, in the case of the "deserved" parameter calculated through the cluster's overall allocatable resources, in a multi-scheduler setting, Volcano's available resource amount is actually less, resulting in each queue's "deserved" being larger than actual, rendering the constraints ineffective.  (This scenario might be fine, as handling multiple schedulers can indeed be challenging)

**These issues may result in an inflated `deserved` value for all queues, potentially rendering the `guarantee` ineffective.**

**Description of case 1 (node label isolation scenarios)：**
![image](https://github.com/volcano-sh/volcano/assets/48900209/3e0a3428-e979-4bf7-b887-d2589162556c)

# Expected Behavior:
The total resource of the queue needs to be recalculated, rather than being calculated uniformly based on the total resources of the entire cluster.

# Steps to Reproduce:
for example of case 2:
1. Set a nodeSelector for nodes in the cluster.
2. Use the proportion plugin to manage resources.
3. Enter vscode debug mode to see the value of `ssn.TotalResource` or the list of `ssn.Nodes`

# Additional Information:
Volcano Version: v1.8.2
Kubernetes Version: v1.19.3

# Proposed Solution:  

The total resources of the queue need to be recalculated as follows:
1. Sum up the allocated resources of all available nodes (nodeLabels and nodegroup).
2. Deduct resources from cordoned nodes.

And the "deserved" value also needs to be recalculated:
1. Accumulate weights for the same `nodegroup`, then calculate proportionally.
.....

**Comment by bysph** [comment]
@lowang-bh Hi, Could you help confirm this issue? thx~

**Comment by bysph** [comment]
I found proportion plugin has some issues:
1. It does not consider multi-scheduler scenarios: for example, in the case of the "deserved" parameter calculated through the cluster's overall allocatable resources, in a multi-scheduler setting, Volcano's available resource amount is actually less, resulting in each queue's "deserved" being larger than actual, rendering the constraints ineffective. 
2. It also fails to consider node label isolation scenarios: such as impala nodes being unavailable for use by the flink queue, but are still factored into the calculation of available resources for the flink queue. Additionally:it does not filter out cordoned nodes, which should be excluded from the calculation of queue available resources even when set to disallow scheduling.

**Comment by bysph** [comment]
> I found proportion plugin has some issues:
> 
> 1. It does not consider multi-scheduler scenarios: for example, in the case of the "deserved" parameter calculated through the cluster's overall allocatable resources, in a multi-scheduler setting, Volcano's available resource amount is actually less, resulting in each queue's "deserved" being larger than actual, rendering the constraints ineffective.
> 2. It also fails to consider node label isolation scenarios: such as impala nodes being unavailable for use by the flink queue, but are still factored into the calculation of available resources for the flink queue.
> 3. Additionally:it does not filter out cordoned nodes, which should be excluded from the calculation of queue available resources even when set to disallow scheduling.

@Monokaix  @lowang-bh  Hi, Could you help confirm this issue? thx~

**Comment by bysph** [comment]
![image](https://github.com/volcano-sh/volcano/assets/48900209/a0cf21c6-6866-4911-b266-357845a68d63)

**Comment by Monokaix** [comment]
> 3. it does not consider about nodeSelectors: some nodes does not managed by volcano will also be included in the calculation.

You mean what node-selector specified？

**Comment by bysph** [comment]
> > 3. it does not consider about nodeSelectors: some nodes does not managed by volcano will also be included in the calculation.
> 
> You mean what node-selector specified？

Yes，and I find `AddPod` will add all nodes to cache, althrough `AddNode` filter them out.
![image](https://github.com/volcano-sh/volcano/assets/48900209/1c17c137-cbcd-4d29-b033-c807d8acd91f)

**Comment by bysph** [comment]
> > > 3. it does not consider about nodeSelectors: some nodes does not managed by volcano will also be included in the calculation.
> > 
> > 
> > You mean what node-selector specified？
> 
> Yes，I found that `AddPod` will add all nodes to cache, althrough `AddNode` filter them out. ![image](https://private-user-images.githubusercontent.com/48900209/326349068-1c17c137-cbcd-4d29-b033-c807d8acd91f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNzM0ODgsIm5iZiI6MTcxNDM3MzE4OCwicGF0aCI6Ii80ODkwMDIwOS8zMjYzNDkwNjgtMWMxN2MxMzctY2JjZC00ZDI5LWIwMzMtYzgwN2Q4YWNkOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDA2NDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZDc0ZmNjMTM3OGRkYzNjOTY2YTdlOWFlYjBjYTMwZTIyOTYzMmExZGFhZWJlMGI3ODgwZWE1NWZiZDJmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qTvWwLuVVuocXgMt6f4ZyQDvTWHIauv3SXoRIBDw8VA)

Sorry, the response here is incorrect; the nodeselector issue may be caused by the csinode informer.
![image](https://github.com/volcano-sh/volcano/assets/48900209/6331ad7c-562b-4808-ae2b-000050b89c97)

**Comment by Monokaix** [comment]
/close
Fixed by https://github.com/volcano-sh/volcano/pull/3594
