### ISSUE TITLE
Meet nil pointer panic when evict

### ISSUE THREAD

**Issue by bibibox** [volcano-sh/volcano#3445]
**What happened**:
i met panic when i use volcano, it shows there is a nil pointer deference when excuting the cache's function Evict:

> I0426 15:46:20.501883       8 cache.go:219] Evicting pod default/job-b-test-2, because of preempted by <default/job-c-test-3> on node <192.168.119.140>
I0426 15:46:20.501952       8 cache.go:283] Updating pod condition for default/job-c-test-4 to (PodScheduled==False)
I0426 15:46:20.508069       8 cache.go:997] Retry to delete Job <default/job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb:default/job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb>
I0426 15:46:20.515660       8 cache.go:283] Updating pod condition for default/job-c-test-5 to (PodScheduled==False)
I0426 15:46:20.520710       8 event_handlers.go:442] Deleted pod <default/job-b-test-5> from cache.
I0426 15:46:20.521612       8 event_handlers.go:442] Deleted pod <default/job-b-test-6> from cache.
I0426 15:46:20.522028       8 event_handlers.go:442] Deleted pod <default/job-b-test-4> from cache.
E0426 15:46:20.522644       8 cache.go:300] Error while updating PodGroup with error: Operation cannot be fulfilled on podgroups.scheduling.volcano.sh "job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb": StorageError: invalid object, Code: 4, Key: /registry/scheduling.volcano.sh/podgroups/default/job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: ddbffa02-e5b8-4206-90d6-e45574532636, UID in object meta:
E0426 15:46:20.522665       8 job_updater.go:99] Failed to update job <default/job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb>: Operation cannot be fulfilled on podgroups.scheduling.volcano.sh "job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb": StorageError: invalid object, Code: 4, Key: /registry/scheduling.volcano.sh/podgroups/default/job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: ddbffa02-e5b8-4206-90d6-e45574532636, UID in object meta:
I0426 15:46:20.524832       8 event_handlers.go:442] Deleted pod <default/job-b-test-3> from cache.
I0426 15:46:20.525039       8 event_handlers.go:442] Deleted pod <default/job-b-test-7> from cache.
E0426 15:46:20.525431       8 cache.go:239] Failed to update pod <default/job-b-test-2> status: Operation cannot be fulfilled on pods "job-b-test-2": the object has been modified; please apply your changes to the latest version and try again
I0426 15:46:20.528526       8 cache.go:997] Retry to delete Job <default/job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb:default/job-b-0624b522-3e50-4c51-aee7-38f47c28f8eb>
I0426 15:46:20.532081       8 cache.go:283] Updating pod condition for default/job-c-test-3 to (PodScheduled==False)
E0426 15:46:20.555482       8 cache.go:1452] error occurred in updating Queue <default>: Operation cannot be fulfilled on queues.scheduling.volcano.sh "default": the object has been modified; please apply your changes to the latest version and try again
E0426 15:46:20.555504       8 session.go:218] failed to update queue <default> status: Operation cannot be fulfilled on queues.scheduling.volcano.sh "default": the object has been modified; please apply your changes to the latest version and try again
I0426 15:46:20.555508       8 session.go:240] Close Session d929179d-caaf-4c47-b25b-0c9c7b010a91
E0426 15:46:20.555549       8 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 2743 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x561e2dbc0460?, 0x561e2f881ac0})
        k8s.io/apimachinery@v0.29.0/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x561e2f97bf60?})
        k8s.io/apimachinery@v0.29.0/pkg/util/runtime/runtime.go:49 +0x75
panic({0x561e2dbc0460, 0x561e2f881ac0})
        runtime/panic.go:884 +0x213
volcano.sh/volcano/pkg/scheduler/cache.(*SchedulerCache).Evict(0xc000726280, 0xc00188a5a0?, {0xc000753b40, 0x3d})
        volcano.sh/volcano@v1.9.0-alpha.0.0.20240425023141-ffd0588b539a/pkg/scheduler/cache/cache.go:865 +0x51c
volcano.sh/volcano/pkg/scheduler/framework.(*Statement).evict(0xc000ab5c20, 0xc001302420, {0xc000753b40?, 0x0?})
        volcano.sh/volcano@v1.9.0-alpha.0.0.20240425023141-ffd0588b539a/pkg/scheduler/framework/statement.go:100 +0x53
volcano.sh/volcano/pkg/scheduler/framework.(*Statement).Commit(0xc000ab5c20)
        volcano.sh/volcano@v1.9.0-alpha.0.0.20240425023141-ffd0588b539a/pkg/scheduler/framework/statement.go:383 +0x453
volcano.sh/apollo/pkg/scheduler/actions/preempt.(*Action).Execute(0xc00074af90, 0xc0013301e0)
        volcano.sh/apollo/pkg/scheduler/actions/preempt/preempt.go:102 +0x499
volcano.sh/volcano/pkg/scheduler.(*Scheduler).runOnce(0xc000001380)
        volcano.sh/volcano@v1.9.0-alpha.0.0.20240425023141-ffd0588b539a/pkg/scheduler/scheduler.go:126 +0x34f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008c7f00?)
        k8s.io/apimachinery@v0.29.0/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x561e2e017cc0, 0xc00081ff20}, 0x1, 0xc0000a9920)
        k8s.io/apimachinery@v0.29.0/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
        k8s.io/apimachinery@v0.29.0/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
        k8s.io/apimachinery@v0.29.0/pkg/util/wait/backoff.go:161 +0x25
created by volcano.sh/volcano/pkg/scheduler.(*Scheduler).Run
        volcano.sh/volcano@v1.9.0-alpha.0.0.20240425023141-ffd0588b539a/pkg/scheduler/scheduler.go:92 +0x19b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x561e2cbd849c]

**What you expected to happen**:
Don't be panic

**How to reproduce it (as minimally and precisely as possible)**:

Cluster specification: 8 cores.
VjobA: replicas=8, minAvailable=2, 1 core/pod.
VjobB: replicas=4, minAvailable=2, 1 core/pod.
VjobC: replicas=31, minAvailable=2, 1 core/pod.

Test Steps:
Submit VjobA.
Submit VjobB.
Submit VjobC.
Delete VjobA.
Delete VjobB.
Delete VjobC.

When deleting VjobABC，the panic happend

**Anything else we need to know?**:
it's a very rare situation

**Environment**:
- Volcano Version: 1.9.0
- Kubernetes version (use `kubectl version`): 1.29
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by lowang-bh** [comment]
`pkg/scheduler/cache/cache.go:865` 
https://github.com/volcano-sh/volcano/blob/ffd0588b539a9a4a2074579a113a441266055e1e/pkg/scheduler/cache/cache.go#L857-L871

/close
