### ISSUE TITLE
README document update follow ups

### ISSUE THREAD

**Issue by TommyLike** [volcano-sh/volcano#347]
Since we changed the guide how to install volcano now. We have to completes these things below:

- [x] Setup a cron task for Travis to build the latest images and push daily.
- [x] Add a Travis Job to verify the file `installer/volcano-development` is identical to the generated file via command `make generate-yaml`.
- [x] Add individual document to guide user how to install volcano via github releases (ref: travis release task) and helm repo.
- [x] Update the helm chart zip file to use the 0.1 image rather than the latest image. https://github.com/volcano-sh/charts/blob/master/package/volcano-0.1.tgz
- [x] Support release helm chart to [repo](https://github.com/volcano-sh/charts) when releasing in script automatically.

**Comment by TommyLike** [comment]
@hzxuzhonghu  @k82cn  please add the todos if you think that is still missing.

@asifdxtreme thanks.

**Comment by TommyLike** [comment]
@asifdxtreme do we created the cronjob for daily build? https://hub.docker.com/r/volcanosh/vc-controllers/tags

**Comment by asifdxtreme** [comment]
![image](https://user-images.githubusercontent.com/9736066/61682193-4b9a1200-ad2e-11e9-94c1-0cf1df7f7a00.png)
it is schedlued to run in another 6 hours, last it was ran 18 hours ago(at that time the PR was not merged), I guess travis is using PST time to run the nightly builds

**Comment by TommyLike** [comment]
@asifdxtreme thanks

**Comment by asifdxtreme** [comment]
> @asifdxtreme thanks

![image](https://user-images.githubusercontent.com/9736066/61722006-1f5eaf80-ad87-11e9-8486-080d5a056e38.png)
The images are getting updated, it will usually update around 18:00 CST everyday

**Comment by asifdxtreme** [comment]
> * [ ]  Support release helm chart to [repo](https://github.com/volcano-sh/charts) when releasing in script automatically.

@TommyLike IMO we should keep this as manual step, these changes might need a manual intervention to decide whether the changes needs to be upstreamed to volcano/charts

**Comment by TommyLike** [comment]
> > * [ ]   Support release helm chart to [repo](https://github.com/volcano-sh/charts) when releasing in script automatically.
> 
> @TommyLike IMO we should keep this as manual step, these changes might need a manual intervention to decide whether the changes needs to be upstreamed to volcano/charts

I am ok with this. Will close this.
