### ISSUE TITLE
OSPP 2024 introduction and apply

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3474]
#### What would you like to be added:

Introduce Volcano projects of OSPP 2024.
Here are volcano related projects:
https://summer-ospp.ac.cn/org/orgdetail/3bad8469-f54d-4a44-9f29-c81fa24d3864
#### Why is this needed:

- Anyone who satisfies the requirement of the activity can submit application for the issue you are interested in. Please remind that the activity is only for college and graduate students. More details please refer to https://summer-ospp.ac.cn/help/student/
- OSPP official site: https://portal.summer-ospp.ac.cn/

**Comment by Monokaix** [comment]
Tracked here:
https://docs.google.com/document/d/1DR1MBhtwhFsmXsil7qojh7F2pDiIKmhmvwhWcZ_GI1Y/

**Comment by hwdef** [comment]
Hierarchical Queue

project:
https://summer-ospp.ac.cn/org/prodetail/243ba0509?list=org&navpage=org

proposal:
https://github.com/volcano-sh/volcano/pull/3591

**Comment by Monokaix** [comment]
All projects are complete.
