### ISSUE TITLE
Avoid unnecessary API update and re-enqueue action

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3490]
#### What would you like to be added:

- Currently, when update a resource, volcano haven't compare them before update, which leads to unnecessary update to API server.
- Volcano controller use workqueue to process resources like queue，job, we should check whether a resource exists when processing it to avoid invalid processing and retrying.

#### Why is this needed:
Lower API server pressure
Avoid unnecessary enent process and enhance performance

**Comment by Monokaix** [comment]
Here are some codes need to be modified：

1. Check whether newJob and original job are deep equal, update job only when it changed https://github.com/volcano-sh/volcano/blob/70a483b66653ee402babdc733505a92fff890f5f/pkg/controllers/job/job_controller_actions.go#L473
2. Skip retry and return nil if err is NotFoundErr https://github.com/volcano-sh/volcano/blob/70a483b66653ee402babdc733505a92fff890f5f/pkg/controllers/garbagecollector/garbagecollector.go#L236
3. Check whether it's NotFoundErr https://github.com/volcano-sh/volcano/blob/70a483b66653ee402babdc733505a92fff890f5f/pkg/controllers/job/job_controller_actions.go#L140

**Comment by wangyysde** [comment]
/assign 
I want to try this.

**Comment by Monokaix** [comment]
> /assign I want to try this.

Thanks and welcome!

**Comment by wangyysde** [comment]
@Monokaix  
https://github.com/volcano-sh/volcano/blob/70a483b66653ee402babdc733505a92fff890f5f/pkg/controllers/garbagecollector/garbagecollector.go#L217 
Here is skipped retry and returned nil if err is NotFoundErr, is right?

**Comment by Monokaix** [comment]
> @Monokaix
> 
> https://github.com/volcano-sh/volcano/blob/70a483b66653ee402babdc733505a92fff890f5f/pkg/controllers/garbagecollector/garbagecollector.go#L217
> 
> 
> Here is skipped retry and returned nil if err is NotFoundErr, is right?

It's right here.

**Comment by lowang-bh** [comment]
Here line307 also need to do comapre and  then update:
https://github.com/volcano-sh/volcano/blob/2e673bc13708e19a1ef39b92e30f9c1f7a59c2ed/pkg/controllers/job/job_controller_actions.go#L299-L312
