### ISSUE TITLE
The pipelined task may cause cluster autoscaler scale up more nodes

### ISSUE THREAD

**Issue by bibibox** [volcano-sh/volcano#3499]
**What happened**:
When one pod preempts other pods on the node, volcano will mark the related task as pipelined status in the cache, and update pod condition to UnSchedulable. The k8s ClusterAutoScaler will consider this pod as unschedulable and scale up one node for it.

**What you expected to happen**:
The k8s ClusterAutoScaler should not scale up node in this scene.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a cluster with volcano and k8s autoscaler, the cluster has a free 4U4G node, and the node pool is also 4U4G
2. create a low priority deploy with 4 replica, make the node occupied
3. create a high priority deploy with 4 replica, to preempt the low priority pods
4. we can see the autoscaler scale up 2 nodes, but just need scale up 1 node indeed

**Anything else we need to know?**:

**Environment**: 
- Volcano Version: 1.9.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: k8s cluster autoscaler 1.29.13

**Comment by william-wang** [comment]
@bibibox please update the `How to reproduce it` section to provide reproducing step info. Thanks.
