### ISSUE TITLE
Volcano support SidecarContainer

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3513]
#### What would you like to be added:
Add sidecarContainer support for volcano scheduler, which needs volcano scheduler re-compute pod resource requests.

#### Why is this needed:
SideCarContainer is a beta feature and is enabled by default in k8s v1.29, volcano has not yet adapt the feature, this may cause the scheduler to undercalculate the resources for the pod, and then the kubelet admit failed after the pod is scheduled to the node, because the sidecarcontainer is a new kind of initcontainer, so the pod initialization request resources need to be recalculated.

Refer to:

1. https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers#resources-calculation-for-scheduling-and-pod-admission
2. https://github.com/kubernetes/kubernetes/pull/116429

**Comment by 7h3-3mp7y-m4n** [comment]
hey, I would like to work on this

**Comment by babugeet** [comment]
hey I would like to work on this

**Comment by Monokaix** [comment]
> hey, I would like to work on this /assign

You're welcome to do that! And please pay a little attention that this feature is planned to release in next version v1.10, and we should make it merged before that: )

**Comment by Monokaix** [comment]
> hey I would like to work on this

Very thanks but a little pity that @7h3-3mp7y-m4n has picked this issue first, you can take a look at other issues that you can contribute to: )

**Comment by 7h3-3mp7y-m4n** [comment]
> > hey, I would like to work on this /assign
> 
> You're welcome to do that! And please pay a little attention that this feature is planned to release in next version v1.10, and we should make it merged before that: )

Okay, I try my best to complete it ASAP

**Comment by Monokaix** [comment]
Hi, there are some main changes need to be done

- task's initResReq need to be re-calculate and consider sidecar containers, related code https://github.com/volcano-sh/volcano/blob/34836851e6317807267230b1b9508194f81a6f67/pkg/scheduler/api/job_info.go#L114 and https://github.com/volcano-sh/volcano/blob/34836851e6317807267230b1b9508194f81a6f67/pkg/scheduler/api/pod_info.go#L59
- add a featuregate `SidecarContainers` in pkg/features to open or close this feature, which should be coordinate with k8s.
- add ut test with `predict` plugin enabled to test resource fit function, please refer to https://github.com/volcano-sh/volcano/blob/34836851e6317807267230b1b9508194f81a6f67/pkg/scheduler/actions/allocate/allocate.go#L292
