### ISSUE TITLE
NodeSelector not filtering nodes correctly in volcano-scheduler v1.8.2+

### ISSUE THREAD

**Issue by 1wolfalone1** [volcano-sh/volcano#3516]
**What happened**:
I attempted to configure multiple schedulers in Volcano and encountered unexpected behavior with different versions of the volcano-scheduler image.

When I set the volcano-scheduler image to version 1.8.2 (or the default latest in the Helm deployment),
![image](https://github.com/volcano-sh/volcano/assets/101981881/12b567ee-14e8-464c-a887-d647d3f17990)
I configured a nodeSelector with volcano.sh/nodegroup-name=g2, which should match two nodes: agent2 and agent3.
![image](https://github.com/volcano-sh/volcano/assets/101981881/29c43276-3e81-4fee-9266-bc57b5cb7b87)
![image](https://github.com/volcano-sh/volcano/assets/101981881/acc6e733-1782-4465-8800-1a92e4226047)
However, the Volcano scheduler logs indicated that it was collecting all nodes in the cluster instead of just those matching the configured node selector.
![image](https://github.com/volcano-sh/volcano/assets/101981881/3ed963fa-5e83-4eb6-857f-8bc499ba0ae5)

This led me to believe there might be an error in my configuration. However, downgrading the volcano-scheduler image to version 1.8.1 or below (within the Helm deployment) resolved the issue.
![image](https://github.com/volcano-sh/volcano/assets/101981881/a84c3943-7fb0-4219-9e71-b187fa562002)
The logs confirmed this behavior, showing that only nodes agent2 and agent3 were collected, and resource calculation for the scheduler in proportion plugins functioned correctly.
![image](https://github.com/volcano-sh/volcano/assets/101981881/b6dc0858-1f59-43f3-8a1f-933dbfc1d197)
**What you expected to happen**:
The ability to create multiple schedulers with a nodeSelector should function correctly from version 1.8.2 of the volcano-scheduler image onwards.

**Environment**:
- Volcano Version: 1.9.0
- Kubernetes version (use `kubectl version`): 1.30.1
- Cloud provider or hardware configuration: k3s and ubuntu 20 vm
- OS (e.g. from /etc/os-release): ubuntu
- Install tools: helm

**Comment by Monokaix** [comment]
Did you also use nodegroup plugin or just multi schedulers?

**Comment by 1wolfalone1** [comment]
As a test, I'm currently using multi-schedulers with a node selector in that example. If this approach proves successful, I'll then activate the node group later.

**Comment by Monokaix** [comment]
There is truly a probelm in versiob v1.8.2，same issue https://github.com/volcano-sh/volcano/issues/3444 , will fix it later: )

**Comment by Prepmachine4** [comment]
I am interested in this issue, can you assign it to me?

**Comment by Monokaix** [comment]
> I am interested in this issue, can you assign it to me?

Thanks for your warming! It has been fixed by https://github.com/volcano-sh/volcano/pull/3594，you can still select other good first issue to contribute: )
