### ISSUE TITLE
Fix the queue jobs preemption error

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#354]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
The error is frequently reported when using job preemption in some cases.

**What you expected to happen**:
Error should not happen when using job preemption feature. The message is like:

```
E0712 11:23:32.825789       1 event_handlers.go:220] Failed to update pod qj-1-8w2ml in cache: errors:  1: failed to find task <default/qj-1-8w2ml> on host <test-virtualbox>
E0712 11:23:32.829026       1 event_handlers.go:252] Failed to delete pod qj-1-8w2ml from cache: errors:  1: failed to find task <default/qj-1-8w2ml> in job <default/qj-1>, 2: failed to find task <default/qj-1-8w2ml> on host <test-virtualbox>
```

**How to reproduce it (as minimally and precisely as possible)**:
1. enable preempt action.
2. submit a first job with 4 tasks.  Make the job occupy all cluster resource.
3. submit the second job with 4 tasks to preempt the first job.
The cause is that the succeeded status task is not treated in DeletePod function.

**Environment**:
- Volcano Version: master

**Comment by hzxuzhonghu** [comment]
@william-wang Can you paste all related logs ?
