### ISSUE TITLE
when using spark with volcano ,queue allocated exceeds capability

### ISSUE THREAD

**Issue by Bmyymwtao** [volcano-sh/volcano#3558]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Volcano Version: v1.9.0
- Kubernetes version (use `kubectl version`): 5.12.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):centos7
- Kernel (e.g. `uname -a`):
- Install tools:helm
- Others:
-

I created a test queue:
yaml:
![image](https://github.com/volcano-sh/volcano/assets/74750747/feb86e62-b036-4f51-b8f3-731006182f3c)
capability: 5CPU 10G

The podgroup I used to submit the spark task：
![image](https://github.com/volcano-sh/volcano/assets/74750747/cc9f327f-d591-4aa9-b020-6e7f0dd49436)

My spark commit statement:
shell: 
/data/module/spark-3.3.2-bin-hadoop3/bin/spark-submit \
  --master k8s://https://xxxx:6443 \
  --class org.apache.spark.examples.streaming.NetworkWordCount \
  --name spark-wc-test \
  --deploy-mode cluster \
  --conf spark.executor.memory=2g \
  --conf spark.executor.cores=2 \
  --conf spark.driver.memory=1g \
  --conf spark.kubernetes.container.image=spark:v3.3.2-dynamic-vol-rc02 \
  --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
  --conf spark.kubernetes.namespace=test \
  --conf spark.kubernetes.executor.podNamePrefix=sparkwc \
  --conf spark.kubernetes.kubeconfig=~/.kube/config \
  --conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=/home/hadoop/yt/volcano/podgroup-test.yaml \
  --conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
  --conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
  local:///opt/spark/examples/jars/spark-examples_2.12-3.3.2.jar csprod01 12138

When I submit a task:
![image](https://github.com/volcano-sh/volcano/assets/74750747/14260401-3234-447e-a058-697cc9c64348)

If the same resource I'm submitting a task for has exceeded the resource I set in my queue, I want it to be in a pending state.
but when i submit:
![image](https://github.com/volcano-sh/volcano/assets/74750747/1edbcbde-ae36-42cc-876b-94a820535368)
queue allocated exceeds capability,I want it to be in a pending state but is running.
May I ask if this is a bug or my configuration is wrong

**Comment by lowang-bh** [comment]
Please paste your config.

**Comment by Bmyymwtao** [comment]
> 请粘贴您的配置。
test_queue.yaml:
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
spec:
  reclaimable: false
  weight: 1
  capability:
    cpu: "5"
    memory: "10240Mi"

**Comment by Bmyymwtao** [comment]
> 请粘贴您的配置。
test_queue.yaml:
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: test
spec:
  reclaimable: false
  weight: 1
  capability:
    cpu: "5"
    memory: "10240Mi"

podgroup.yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  generation: 5
  name: test
  namespace: pjl
spec:
  minMember: 1
  minResources:
    cpu: "3"
    memory: "6144Mi"
  queue: test

spark-shell:
/data/module/spark-3.3.2-bin-hadoop3/bin/spark-submit \
  --master k8s://https://xxxxx:6443 \
  --class org.apache.spark.examples.streaming.NetworkWordCount \
  --name spark-wc-test \
  --deploy-mode cluster \
  --conf spark.executor.memory=2g \
  --conf spark.executor.cores=2 \
  --conf spark.driver.memory=1g \
  --conf spark.kubernetes.container.image=spark:v3.3.2-vol-rc02 \
  --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
  --conf spark.kubernetes.namespace=pjl \
  --conf spark.kubernetes.executor.podNamePrefix=sparkwc \
  --conf spark.kubernetes.kubeconfig=~/.kube/config \
  --conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=/home/hadoop/yt/volcano/podgroup-test.yaml \
  --conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
  --conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
  local:///opt/spark/examples/jars/spark-examples_2.12-3.3.2.jar csprod01 12138

What seems to be the problem?

**Comment by Bmyymwtao** [comment]
> 请粘贴您的配置。
volcano-scheduler-configmap is default:
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: volcano
    meta.helm.sh/release-namespace: pjl
  creationTimestamp: "2024-06-27T07:18:58Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: volcano-scheduler-configmap
  namespace: pjl
  resourceVersion: "35749706"
  uid: fbd974b1-d45f-4d94-94f6-bded38e0b175

**Comment by PigNatovsky** [comment]
I think that scheduler conf will be more useful - actions and tiers with plugins (You can find them in config map in Volcano namespace).

**Comment by PigNatovsky** [comment]
I think that scheduler conf will be more useful - actions and tiers with plugins (You can find them in config map in Volcano namespace).

**Comment by Bmyymwtao** [comment]
> I think that scheduler conf will be more useful - actions and tiers with plugins (You can find them in config map in Volcano namespace).

That's it
volcano-scheduler-configmap is default:
apiVersion: v1
data:
volcano-scheduler.conf: |
actions: "enqueue, allocate, backfill"
tiers:
- plugins:
- name: priority
- name: gang
enablePreemptable: false
- name: conformance
- plugins:
- name: overcommit
- name: drf
enablePreemptable: false
- name: predicates
- name: proportion
- name: nodeorder
- name: binpack
kind: ConfigMap
metadata:
annotations:
meta.helm.sh/release-name: volcano
meta.helm.sh/release-namespace: pjl
creationTimestamp: "2024-06-27T07:18:58Z"
labels:
app.kubernetes.io/managed-by: Helm
name: volcano-scheduler-configmap
namespace: pjl
resourceVersion: "35749706"
uid: fbd974b1-d45f-4d94-94f6-bded38e0b175

**Comment by Bmyymwtao** [comment]
I use the exact same configuration : docs/user-guide/how_to_use_capacity_plugin.md

**Comment by Bmyymwtao** [comment]
I use the exact same configuration : docs/user-guide/how_to_use_capacity_plugin.md
but it still didn't work as described in the documentation。

**Comment by lowang-bh** [comment]
Maybe I know why. The overused check is only supported in proportion plugin, capacity plugin has no overused check.

**Comment by Bmyymwtao** [comment]
> Maybe I know why. The overused check is only supported in proportion plugin, capacity plugin has no overused check.
> 
> Be relative to [resource compare only consider requested dimension #3537](https://github.com/volcano-sh/volcano/issues/3537)

But I tried both plugins separately, and neither worked.
I checked  my configurations according to the user-guide and the website and couldn't find the problem.
Did I have to configure all the queues to be filled with k8s resources？ But that's not what I expected

**Comment by Bmyymwtao** [comment]
> Maybe I know why. The overused check is only supported in proportion plugin, capacity plugin has no overused check.
> 
> Be relative to [resource compare only consider requested dimension #3537](https://github.com/volcano-sh/volcano/issues/3537)
proportion plugin . The example I tested with nginx works, but the spark native task still doesn't

**Comment by Bmyymwtao** [comment]
> > Maybe I know why. The overused check is only supported in proportion plugin, capacity plugin has no overused check.
> > Be relative to [resource compare only consider requested dimension #3537](https://github.com/volcano-sh/volcano/issues/3537)
> > proportion plugin . The example I tested with nginx works, but the spark native task still doesn't

I did not use the spark official website configuration
remove
"--conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=/home/hadoop/yt/volcano/podgroup-test.yaml
--conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep
--conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep"
add
"  --conf spark.kubernetes.scheduler.name=volcano \
  --conf spark.kubernetes.driver.annotation.scheduling.volcano.sh/queue-name=yt-queue \
  --conf spark.kubernetes.executor.annotation.scheduling.volcano.sh/queue-name=yt-queue \"
Meet expectations

**Comment by Bmyymwtao** [comment]
> > > Maybe I know why. The overused check is only supported in proportion plugin, capacity plugin has no overused check.
> > > Be relative to [resource compare only consider requested dimension #3537](https://github.com/volcano-sh/volcano/issues/3537)
> > > proportion plugin . The example I tested with nginx works, but the spark native task still doesn't
> 
> I did not use the spark official website configuration remove "--conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=/home/hadoop/yt/volcano/podgroup-test.yaml --conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep --conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep" add " --conf spark.kubernetes.scheduler.name=volcano --conf spark.kubernetes.driver.annotation.scheduling.volcano.sh/queue-name=yt-queue --conf spark.kubernetes.executor.annotation.scheduling.volcano.sh/queue-name=yt-queue " Meet expectations
 use the spark official website configuration is ok
/data/module/spark-3.3.2-bin-hadoop3/bin/spark-submit \
  --master k8s://https://xxxxx:6443 \
  --class org.apache.spark.examples.streaming.NetworkWordCount \
  --name spark-wc-test1 \
  --deploy-mode cluster \
  --conf spark.executor.memory=2g \
  --conf spark.executor.cores=2 \
  --conf spark.driver.memory=1g \
  --conf spark.kubernetes.container.image=spark:v3.3.2-dynamic-vol-rc02 \
  --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
  --conf spark.kubernetes.namespace=pjl \
  --conf spark.kubernetes.executor.podNamePrefix=sparkwc \
  --conf spark.kubernetes.kubeconfig=~/.kube/config \
  --conf spark.kubernetes.scheduler.name=volcano \
  --conf spark.kubernetes.scheduler.volcano.podGroupTemplateFile=/home/hadoop/yt/volcano/podgroup-test.yaml \
  --conf spark.kubernetes.driver.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
  --conf spark.kubernetes.executor.pod.featureSteps=org.apache.spark.deploy.k8s.features.VolcanoFeatureStep \
  local:///opt/spark/examples/jars/spark-examples_2.12-3.3.2.jar csprod01 12138
I missed it earlier:
--conf spark.kubernetes.scheduler.name=volcano \
