### ISSUE TITLE
upgrade kube-state-metrics version to v1.9.8/v2.12.0 from v1.9.7

### ISSUE THREAD

**Issue by lengrongfu** [volcano-sh/volcano#3564]
#### What would you like to be added:

Current use `quay.io/coreos/kube-state-metrics:v1.9.7` this image ,but it only having `amd64` arch, i want in `arm64` machine running it , so we can upgrade this image version.

**Comment by Monokaix** [comment]
Hi, actually volcano has some custom metrics that modified in this repo https://github.com/volcano-sh/kube-state-metrics, so I think we use images built from that repo is better.

**Comment by lengrongfu** [comment]
> Hi, actually volcano has some custom metrics that modified in this repo https://github.com/volcano-sh/kube-state-metrics, so I think we use images built from that repo is better.

This project having no code submission for 4 years and volcano use image is `quay.io/coreos/kube-state-metrics:v1.9.7`, how is this done?

**Comment by Monokaix** [comment]
> > Hi, actually volcano has some custom metrics that modified in this repo https://github.com/volcano-sh/kube-state-metrics, so I think we use images built from that repo is better.
> 
> This project having no code submission for 4 years and volcano use image is `quay.io/coreos/kube-state-metrics:v1.9.7`, how is this done?

It's forked from upstream kube-state-metrics which is based versiob v2.0.0 and image has been uploaded to dockerhub: )
