### ISSUE TITLE
grafana监控无法显示Dashboard大部分指标

### ISSUE THREAD

**Issue by bigcatpan** [volcano-sh/volcano#3573]
当前环境：
k8s版本：1.20.5
volcano版本：1.6.0
监控部署yaml：https://github.com/volcano-sh/volcano/blob/release-1.6/installer/volcano-monitoring-latest.yaml

问题描述：
grafana部署后无法显示Queue View Dashboard指标，问题指标已经圈出，如下图所示：
![volcano](https://github.com/volcano-sh/volcano/assets/9636565/28837bac-8d3f-4fcc-a582-46529dac1567)

原因分析：
查看grafana配置使用了以下指标：
kube_pod_volcano_container_status_running
kube_pod_volcano_container_resource_requests
但是调用prometheus接口并未发现有采集到这些指标数据，应该是源头问题。

**Comment by Monokaix** [comment]
Please use the latest monitor yaml https://github.com/volcano-sh/volcano/blob/master/installer/volcano-monitoring-latest.yaml to re-deploy: )

**Comment by Monokaix** [comment]
xref: https://github.com/volcano-sh/volcano/pull/3262

**Comment by bigcatpan** [comment]
> xref: #3262

**Comment by bigcatpan** [comment]
问题描述：
hi，用最新的yaml部署还是一样的问题，调用prometheus接口还是没有看到相关指标
原因分析：
查看issue#1587也有类似的问题，是不是镜像的问题呢？最新版本的镜像是image:quay.io/coreos/kube-state-metrics:v1.9.7，跟1.6是一样的 ，麻烦看下谢谢。

**Comment by hwdef** [comment]
请尝试使用 https://github.com/volcano-sh/kube-state-metrics

**Comment by Monokaix** [comment]
Please use image `volcanosh/kube-state-metrics:v2.0.0-beta` and try again: )

**Comment by kinoxyz1** [comment]
> 问题描述： hi，用最新的yaml部署还是一样的问题，调用prometheus接口还是没有看到相关指标 原因分析： 查看[issue](https://github.com/volcano-sh/volcano/issues/1587)也有类似的问题，是不是镜像的问题呢？最新版本的镜像是image:quay.io/coreos/kube-state-metrics:v1.9.7，跟1.6是一样的，麻烦看下谢谢。

你好，我也遇到了同样的问题，请问你这边解决了吗
