### ISSUE TITLE
The volcano controller may have memory leak issues in large-scale clusters

### ISSUE THREAD

**Issue by Wang-Kai** [volcano-sh/volcano#3597]
**What happened**:

The volcano controller has memory leak issues in large-scale clusters

<img width="1221" alt="企业微信截图_1b4b6a2f-dc27-4679-84b7-24bba33cf72d" src="https://github.com/user-attachments/assets/4602b3b6-29a1-4cb8-8e8c-9327998047c3">

![image](https://github.com/user-attachments/assets/0519de04-c13d-4c6a-8ba0-e0c2eb1aafee)

**What you expected to happen**:

The volcano controller keeps running at a stable memory level

**How to reproduce it (as minimally and precisely as possible)**:

Build a cluster with 100,000 CPU cores and create 20,000 pods. Each pod will automatically terminate after running for 1 minute after startup. Continue this operation for 1 day.

**Anything else we need to know?**:

Both the scheduler and the controller will update the queue CRD. Each time the pg changes, the controller will update the statistics of each state in the queue. After each scheduling, the scheduler will update the allocated field of the queue to record the amount of resources allocated. Both components update the queue, resulting in frequent conflict errors. When the controller encounters such an error, it will trigger AddRateLimited, resulting in accumulation and memory leaks.

**Environment**: linux
- Volcano Version: v1.8.2
- Kubernetes version (use `kubectl version`): v1.20
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`):  Linux 5.10.0-103-bili-colo x86_64
- Install tools:
- Others:

**Comment by Monokaix** [comment]
> it will trigger AddRateLimited, resulting in accumulation and memory leaks.

Is forget and done method called？

**Comment by Monokaix** [comment]
When the queue status is finally updated after retry with conflict, the queue will be dropped in cache and memory will be reduced, right?

**Comment by Wang-Kai** [comment]
> When the queue status is finally updated after retry with conflict, the queue will be dropped in cache and memory will be reduced, right?

From the monitoring point of view, the memory size only increases and does not decrease until the program OOM.

Because pg changes very frequently, if the scheduler modifies the queue and causes conflicts, AddRateLimited will be frequently triggered, but the processing rate is only 10. It is suspected that this is the reason for the memory leak.

At present, the production environment of bilibili company has removed the update statistics of queue CRD, and the problem has been solved in the end. How do we find a suitable way to contribute to the community?

**Comment by Monokaix** [comment]
An optional way is put update `status.allocated` into queue controller.
