### ISSUE TITLE
Garbage Collector is supposed to clean up Aborted volcanojobs

### ISSUE THREAD

**Issue by Antsypc** [volcano-sh/volcano#3604]
**What happened**: garbagecollector controller does not clean up any Aborted volcanojobs where the `.status.state.phase` is `Aborted`.

**What you expected to happen**: Aborted jobs should be cleaned up.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a volcanojob with `.spec.ttlSecondsAfterFinished` specified.
2. abort this job.
3. `kubectl get vj xxx`, you will see that thee job's `.status.state.phase` is `Aborted`.
4. wait for `ttlSecondsAfterFinished` seconds.
5. however, this job still exists.

**Anything else we need to know?**: The bug seems to occur in the following code. https://github.com/volcano-sh/volcano/blob/v1.10.0-alpha.0/pkg/controllers/garbagecollector/garbagecollector.go#L266

```go
func isJobFinished(job *v1alpha1.Job) bool {
	return job.Status.State.Phase == v1alpha1.Completed ||
		job.Status.State.Phase == v1alpha1.Failed ||
		job.Status.State.Phase == v1alpha1.Terminated
}
```

The condition `job.Status.State.Phase == v1alpha1.Aborted` should not be omitted.

**Environment**:
- Volcano Version: 1.4 to 1.9, up to now

**Comment by Monokaix** [comment]
I think it's reasonable: )

**Comment by kyooosukedn** [comment]
Would like to try on this :)

**Comment by googs1025** [comment]
> Would like to try on this :)
@kyooosukedn
Oh! Do you want to try this topic? Then I'll give it to you first. I can help review it.

**Comment by kyooosukedn** [comment]
#3637

**Comment by googs1025** [comment]
I think the key question is: how do we distinguish between "Aborted", "Terminated", and "Failed"? Are these three states defined as the final state of the Job? I can't easily distinguish the difference between these three states of the Job in the code. Why do we need to divide them into three?

**Comment by googs1025** [comment]
So we must confirm one thing, which states are the final states. And these final states can be recycled by Garbage Collector

**Comment by Monokaix** [comment]
@Antsypc Can you describe that under what will you abort a job，and can the job be resumed by command `vcctl job resume`?

**Comment by Monokaix** [comment]
<img width="755" alt="image" src="https://github.com/user-attachments/assets/23dc7bfb-e297-4ed1-bb81-0e3c2df12c5f">

Aha, aborted job can be resumed: )

**Comment by Monokaix** [comment]
> > <img alt="image" width="755" src="https://private-user-images.githubusercontent.com/16742217/352934187-23dc7bfb-e297-4ed1-bb81-0e3c2df12c5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ2ODQsIm5iZiI6MTcyMjI2NDM4NCwicGF0aCI6Ii8xNjc0MjIxNy8zNTI5MzQxODctMjNkYzdiZmItZTI5Ny00ZWQxLWJiODEtMGUzYzJkZjEyYzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE0NDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDVlZjgzMDliYzQ1ZTc3NWZmMjc4ZTBkMjUyZDdhNWExNjM0MWI0Y2VhOWIxNmUxYzk3NmUyNTM4YWViZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kuN7X89c9RhEsVvl1HGJHqmU9h2KrrvFKwQYusYdrVc">
> > Aha, aborted job can be resumed: )
> 
> Based on this result, I think the aborted state is not a final state.

Yeah！

**Comment by Monokaix** [comment]
@Antsypc `Aborted` is not a final state and can be resumed so we will close this.
