### ISSUE TITLE
MPI Job in Volcano gets Terminated

### ISSUE THREAD

**Issue by mehmetihsansevinc** [volcano-sh/volcano#3606]
Hello,

I have a K8S cluster on **arm64 Rocky Linux** servers and Volcano is running. I'm trying to run MPI Job for a demonstration but the Job goes into terminated state without creating pods. When i check the controller logs, it tells there is not a desired queue state which the state is Open.

Created a Queue with "Open" status and resource specs and named as "mehmet".
`apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: mehmet
  creationTimestamp: "2024-05-24T08:33:54Z"
  generation: 1
  resourceVersion: "4967164"
  uid: e0132cfe-e4f6-4705-883c-814e72a902a9
spec:
  guarantee: {}
  reclaimable: true
  weight: 1
status:
  state: Open
  allocated:
    cpu: "1"
    memory: "1Gi"
`
Log:
`event.go:285] Event(v1.ObjectReference{Kind:"Queue", Namespace:"", Name:"mehmet", UID:"51224025-3de4-4596-8556-3ad82160b930", APIVersion:"scheduling.volcano.sh/v1beta1", ResourceVersion:"13876618", FieldPath:""}): type: 'Warning' reason: 'SyncQueue' SyncQueue queue failed for sync queue mehmet failed for Queue.scheduling.volcano.sh "mehmet" is invalid: status.allocated: Required value, event is OutOfSync, action is SyncQueue`

The default queue is tried to be patched queue-patch.yaml:
`status:
  state: Open
  allocated:
    cpu: "1"
    memory: "1Gi"
`
Nothing changed with the queue:
`kubectl patch queue mehmet --type='merge' -p "$(cat queue-patch.yaml)"`

`apiVersion: v1
items:
- apiVersion: scheduling.volcano.sh/v1beta1
  kind: Queue
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"creationTimestamp":"2024-05-24T08:33:54Z","generation":1,"name":"default","resourceVersion":"4967164","uid":"e0132cfe-e4f6-4705-883c-814e72a902a9"},"spec":{"guarantee":{},"reclaimable":true,"weight":1},"status":{"allocated":{"cpu":"1","memory":"1Gi"},"state":"Open"}}
    creationTimestamp: "2024-05-24T08:33:54Z"
    generation: 1
    name: default
    resourceVersion: "13875831"
    uid: e0132cfe-e4f6-4705-883c-814e72a902a9
  spec:
    guarantee: {}
    reclaimable: true
    weight: 1
- apiVersion: scheduling.volcano.sh/v1beta1
  kind: Queue
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"creationTimestamp":"2024-05-24T08:33:54Z","generation":1,"name":"mehmet","resourceVersion":"4967164","uid":"e0132cfe-e4f6-4705-883c-814e72a902a9"},"spec":{"guarantee":{},"reclaimable":true,"weight":1},"status":{"allocated":{"cpu":"1","memory":"1Gi"},"state":"Open"}}
    creationTimestamp: "2024-07-16T08:27:12Z"
    generation: 1
    name: mehmet
    resourceVersion: "13876618"
    uid: 51224025-3de4-4596-8556-3ad82160b930
  spec:
    guarantee: {}
    reclaimable: true
    weight: 1
kind: List
metadata:
  resourceVersion: ""
`
Could not proceed after this step. Did someone faced with this problem?

**Comment by Monokaix** [comment]
Hi, what's the volcano version you deployed? Please use latest version v1.9 and try another time.

**Comment by mehmetihsansevinc** [comment]
Hi, the version that we are using is v1.3.0. According to your suggestion we'll use the v1.9.0 and keep the issue informed.

**Comment by Monokaix** [comment]
> Hi, the version that we are using is v1.3.0. According to your suggestion we'll use the v1.9.0 and keep the issue informed.

Yeah it's a known issue and has been fixed by https://github.com/volcano-sh/volcano/pull/3206.

**Comment by mehmetihsansevinc** [comment]
With the version 1.9.0 problem has been solved. Thanks
