### ISSUE TITLE
Migrate manifests from {extensions/v1beta1,apps/v1beta1,apps/v1beta2} to apps/v1 

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#361]
xref: https://github.com/kubernetes/kubernetes/issues/43214

Kubenetes 1.16 will remove all the API above. We should make sure we migrate all `DaemonSets, Deployments, ReplicaSets, and StatefulSets ` to apps/v1 before k8s 1.16 is released.

**Comment by hzxuzhonghu** [comment]
@Rajadeepan Can you help on this?

**Comment by k82cn** [comment]
@hzxuzhonghu , please help on this one.

**Comment by hzxuzhonghu** [comment]
This is done.
