### ISSUE TITLE
queue-controller无法同步queue资源

### ISSUE THREAD

**Issue by yalbaba** [volcano-sh/volcano#3617]
报错信息：
Failed to update status of Queue cr-q9jn7grcejmlmq5s: Queue.scheduling.volcano.sh "cr-q9jn7grcejmlmq5s" is invalid: status.allocated: Required value

问题：
工程从1.4的volcano升级到1.7，如今1.7版本新增了字段status.allocated，那升级如何兼容呢？

**Comment by Monokaix** [comment]
it's fixed by https://github.com/volcano-sh/volcano/pull/3206, you can try to version v1.9.0
