### ISSUE TITLE
Installing volcano repeatedly via helm will cause the scheduler pod to panic

### ISSUE THREAD

**Issue by Kyrie336** [volcano-sh/volcano#3645]
**What happened**:
Installing volcano repeatedly via helm will cause the scheduler pod to panic

uninstall volcano via helm does't clean k8s secrets.

**What you expected to happen**:
no panic

**How to reproduce it (as minimally and precisely as possible)**:
1. volcano normal running
```
kubectl get pod -n volcano
NAME                                            READY   STATUS      RESTARTS   AGE
chart-1722418489-admission-5cc86f558-4tq5p      1/1     Running     0          93s
chart-1722418489-admission-init-55b6v           0/1     Completed   0          93s
chart-1722418489-controllers-6c869d7f48-bmv7h   1/1     Running     0          93s
chart-1722418489-scheduler-759494645b-pvfpc     1/1     Running     0          93s
```
2. uninstall volcano
```
helm uninstall -n volcano chart-1722418489
release "chart-1722418489" uninstalled
```

3.  secrets volcano-admission-secret  already exist
```
kubectl get secrets -n volcano
NAME                                                      TYPE                                  DATA   AGE
default-token-kj98q                                       kubernetes.io/service-account-token   3      61d
volcano-admission-secret                                  Opaque                                3      2m35s
```

4. install volcano
`helm install . --create-namespace -n volcano --generate-name`

5. scheduler pod start to restart
```
kubectl get pod -n volcano
NAME                                           READY   STATUS      RESTARTS      AGE
chart-1722418707-admission-5f84dfcb66-2g2j6    1/1     Running     0             91s
chart-1722418707-admission-init-pvdgj          0/1     Completed   0             91s
chart-1722418707-controllers-78db9f847-9864f   1/1     Running     0             91s
chart-1722418707-scheduler-8674646b44-zjwx7    1/1     Running     1 (21s ago)   91s
```

6. get admission pod logs
`http: TLS handshake error from 172.23.6.40:37365: remote error: tls: bad certificate`

7. get admission-init pod logs
`kubectl logs -n volcano chart-1722418707-admission-init-pvdgj
The secret volcano-admission-secret -n volcano already exists. Do not create it again.
`

**Anything else we need to know?**:

**Environment**:
- Volcano Version: release version v1.9.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Monokaix** [comment]
What if you delete the secret before reinstall volcano?

**Comment by Kyrie336** [comment]
> What if you delete the secret before reinstall volcano?

if delete the secret，reinstall volcano will work fine.

**Comment by Monokaix** [comment]
That's becasue you used `--generate-name` flag everytime and it will generate a new admission service name related to chart name everytime, at the same time, secret is not deleted when uninstall with helm, so when you re-install volcano with helm it will use and old chart name, and the CN name is releated to chart name, so the CA certificate will authenticate failed.
 So you should specify a chart name instead of using `--generate-name,  refer to https://github.com/volcano-sh/helm-charts to install volcano with helm.

**Comment by Kyrie336** [comment]
> That's becasue you used `--generate-name` flag everytime and it will generate a new admission service name related to chart name everytime, at the same time, secret is not deleted when uninstall with helm, so when you re-install volcano with helm it will use and old chart name, and the CN name is releated to chart name, so the CA certificate will authenticate failed. So you should specify a chart name instead of using `--generate-name`, refer to [https://github.com/volcano-sh/helm-charts](https://bgithub.xyz/volcano-sh/helm-charts) to install volcano with helm.

I think volcano should support helm's installation parameters instead of using fixed installation commands. Also, if two volcano charts with different names are installed in the cluster, it will cause problems, which I think is a bug

**Comment by Monokaix** [comment]
> > That's becasue you used `--generate-name` flag everytime and it will generate a new admission service name related to chart name everytime, at the same time, secret is not deleted when uninstall with helm, so when you re-install volcano with helm it will use and old chart name, and the CN name is releated to chart name, so the CA certificate will authenticate failed. So you should specify a chart name instead of using `--generate-name`, refer to [https://github.com/volcano-sh/helm-charts](https://bgithub.xyz/volcano-sh/helm-charts) to install volcano with helm.
> 
> I think volcano should support helm's installation parameters instead of using fixed installation commands. Also, if two volcano charts with different names are installed in the cluster, it will cause problems, which I think is a bug
First I want to know in which case will you deploy two charts? And as far as I know install two volcano charts will have other conflicts too: )

**Comment by Monokaix** [comment]
But I think we can continure have a deep dive to solve that.

**Comment by Monokaix** [comment]
You can try this https://github.com/volcano-sh/volcano/pull/3653 : )
