### ISSUE TITLE
[suggestion for reviewers]keep volcano extendable interfaces not changed when review code

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3646]
### What is the problem you're trying to solve

There are some interfaces in volcano scheduler such as Bind, Evict, etc. And also session's interface functions such as `AddPredicateFn`, `AddJobReadyFn`, `AddJobEnqueueableFn`, `AddBatchNodeOrderFn`, etc.
There are already be used in some other downstream projects, such as [ascend-for-volcano](https://gitee.com/ascend/ascend-for-volcano).

### Describe the solution you'd like

Keep carefully when review those changes and there should be an necessary reason for the changes.

**Comment by googs1025** [comment]
Maybe we need to have a release-node mechanism like the k8s community, and summarize it when releasing a new version.

**Comment by Monokaix** [comment]
> Maybe we need to have a release-node mechanism like the k8s community, and summarize it when releasing a new version.

Volcano will release changelogs with new version, is there any difference with it？

**Comment by googs1025** [comment]
> > Maybe we need to have a release-node mechanism like the k8s community, and summarize it when releasing a new version.
> 
> Volcano will release changelogs with new version, is there any difference with it？

Oh! If there is a change log, I understand it should mean the same thing.

**Comment by googs1025** [comment]
Also, I'm curious about something. How does the Volcano interface impact downstream projects? Do downstream projects introduce the Volcano API or some other mechanism? If downstream projects are adopting a specific version of the Volcano API, I believe they just need to upgrade to match the version (similar to how we adapt to Kubernetes). If I'm mistaken in my understanding, please correct me.

分享

**Comment by lowang-bh** [comment]
Yes they can upgrade and do work to adapt to our changes. Maybe we also need to consider compatibility when do some modify.
