### ISSUE TITLE
volcano should work with oidc clusters

### ISSUE THREAD

**Issue by snappyyouth** [volcano-sh/volcano#3662]
### What is the problem you're trying to solve

I will like to add support to scheduler such that also clusters that use oidc authentication will work.
![image](https://github.com/user-attachments/assets/6d71a7c2-89bc-4777-98d5-afa7f401b852)

### Describe the solution you'd like

add oidc's auth provider in the /cmd/scheduler/main.go

_ "k8s.io/client-go/plugin/pkg/client/auth"

**Comment by Monokaix** [comment]
Hi, please support more information about your use case.

**Comment by snappyyouth** [comment]
my kubeconfig is like this.
![image](https://github.com/user-attachments/assets/e4450f61-4cd1-4948-aa6d-024d5233e334)

**Comment by snappyyouth** [comment]
My partial kubeconfig looks like this.

![image](https://github.com/user-attachments/assets/e4450f61-4cd1-4948-aa6d-024d5233e334)
