### ISSUE TITLE
Suggest Removing copyright year from generated go files 

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3668]
### What is the problem you're trying to solve

When using code-generator to generate files, the boilerplate is used and it contains YEAR field in copyright, so when we generate new files in current year, the year will be rendered, but the previous files will also be affected, which is unacceptable, and from kubernetes's practice,  see https://github.com/kubernetes/gengo/issues/24, there are no YEAR field in license header, so I suggest remove the YEAR field too, cause it has nothing to do with the license.

### Describe the solution you'd like

Remove copyright year from generated go files, currently only API repo https://github.com/volcano-sh/apis has this problem, we can first start with the API repo.

### Additional context

This pr https://github.com/volcano-sh/apis/pull/134 is doing this when updating code generation scripts.

**Comment by hwdef** [comment]
It makes sense
