### ISSUE TITLE
Add securityContext support at container level in helm chart templates

### ISSUE THREAD

**Issue by schauaib** [volcano-sh/volcano#3685]
### What is the problem you're trying to solve

In the chart template files, the admission.yaml manifest does not support the "securityContext" section at container level, both for the deployment and job definition. 

### Describe the solution you'd like

Add following to admission.yaml:
```
...
---
apiVersion: apps/v1
kind: Deployment
...
spec:
...
  template:
  ...
    spec:
    ...
      containers:
          ...
          securityContext:
            {{- toYaml .Values.custom.default_csc | nindent 12 }}
          ...
...
---
apiVersion: batch/v1
kind: Job
...
spec:
...
  template:
    spec:
    ...
      containers:
          ...
          securityContext:
            {{- toYaml .Values.custom.default_csc | nindent 12 }}
          ...
...
```

This way, one could define the "default_csc" section in helm's values.yaml file to customize securityContext, in order to match its k8s cluster security constraints.

**Comment by Monokaix** [comment]
Does volcano scheduler and controller also need this?

**Comment by schauaib** [comment]
You're absolutely right, I also had to patch templates/controllers.yaml & templates/scheduler.yaml manifest the same way
