### ISSUE TITLE
victims log print a lot of details

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3687]
### What is the problem you're trying to solve

victim pods has print the detail yaml, which is not necessary.

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/030e212b-2910-4ba4-b824-cbc31877ad43">

### Describe the solution you'd like

just need basic task info like preemtor
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/11860cd8-dc6e-417f-a86c-997e7554ea71">

**Comment by rissh** [comment]
Hey,

I want to give it a try and work on this issue. Can you please assign me this issue?
Please don't hesitate to give me any suggestions or guidance as I work on this task. I'm open to feedback and would appreciate any insights you have.

Thank you!

**Comment by rissh** [comment]
@lowang-bh ,
Thank you for assigning me this issue. Could you please point me to the files related to it? I'm still getting familiar with Volcano.

**Comment by lowang-bh** [comment]
> Could you please point me to the files related to it? I'm still getting familiar with Volcano.

https://github.com/volcano-sh/volcano/blob/60a7f75367a37188a94bfb2bd28960fe5374b178/pkg/scheduler/plugins/gang/gang.go#L102

**Comment by rissh** [comment]
Thanks, man! I will up the PR soon.
