### ISSUE TITLE
Incorrect construction of `PredicateResponse` object

### ISSUE THREAD

**Issue by ilyee** [volcano-sh/volcano#3701]
### Description

In release branch [release-1.8](https://github.com/volcano-sh/volcano/tree/release-1.8), there is a string assignment like this:

https://github.com/volcano-sh/volcano/blob/675b8df0335ab18dedb547319e4096ee9a6091af/example/extender/extender.go#L72-L75

but the struct of `extender.PredicateResponse` turns out to be:

https://github.com/volcano-sh/volcano/blob/675b8df0335ab18dedb547319e4096ee9a6091af/pkg/scheduler/plugins/extender/argument.go#L24-L26

obviously something is wrong here, maybe we should use:

```golang
	resp := &extender.PredicateResponse{}
	if req.Task.BestEffort && len(req.Node.Tasks) > 10 {
		resp.Status = []*api.Status{
			{
				Code:   api.Unschedulable,
				Reason: "Too many tasks on the node",
			},
		}
	}
```

This makes golint fail

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Construct `extender.PredicateResponse` object correctly in [example/extender/extender.go](https://github.com/volcano-sh/volcano/blob/release-1.8/example/extender/extender.go)

### What version of Volcano are you using?

1.8.2

**Comment by lowang-bh** [comment]
master has fixed it. https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/extender/argument.go
