### ISSUE TITLE
helm chart - remove hard coded nodeSelector for kubestatemetrics portion

### ISSUE THREAD

**Issue by dmildh-absci** [volcano-sh/volcano#3735]
### Description

If you don't have the node label of control-plane on your cluster the metrics pod will not start.  Consider making this a variable so you can provide your own node selector or provide affinity rules.

https://github.com/volcano-sh/volcano/blob/master/installer/helm/chart/volcano/templates/kubestatemetrics.yaml#L187-L190

### Steps to reproduce the issue

Run the helm chart with  Values.custom.metrics_enable = true

### Describe the results you received and expected

The kube-state-metrics pod should start for clusters that are not using the control-plane label

### What version of Volcano are you using?

volcano version: "1.5" appVersion: "0.1"

**Comment by lekaf974** [comment]
@Monokaix opened this pr waiting for feedback
