### ISSUE TITLE
the headless svc of vcjob created later than pods

### ISSUE THREAD

**Issue by tedli** [volcano-sh/volcano#3753]
### Description

1. create a vcjob
2. replicas container entry set to `nslookup <hostname>.<jobname> && sleep infinite`
3. the nslookup may fail due to at the time pod start, the headless has not yet been created

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

vcjob controller create watch and wait headless svc of vcjob ready, then create replica pods of job.

### What version of Volcano are you using?

v1.10.0

**Comment by Monokaix** [comment]
H，you mean should creating headless svc after pods are ready?

**Comment by tedli** [comment]
Hi @Monokaix ,
Thanks for reply.
No, exactly the opposite.
My problem is that, when pods started, the headless svc may occasionally not yet been created. So inside pod, something like `dig` or `nslookup` to find ip replicas will fail.
My output of kubectl, is like this,
```
NAME    AGE
vcjob   12s    <-- svc

NAME                   AGE
vcjob-worker-0         46s    <-- pod

If the output goes like this, it means headless svc created after pod, result in nslookup of svc name `vcjob-worker-0.vcjob` fail.

**Comment by Monokaix** [comment]
Ok, but if svc is created first but pod is not ready, svc parsing will also fail because the pod IP is not ready yet？

**Comment by tedli** [comment]
Hi @Monokaix ,
Thanks for reply.
Of course. look up svc won't got unready pod ip. but how to tell a pod is ready, it's up to the user, the user can adjust the health check logic with the pod probe to make sure it's ready.
However user has no access to control when volcano creates the headless svc. In most time, lookup headless svc works as expect, occasionally the lookup fails because at that time, the svc had not been created.
Also, it will be convenient, it add some extra field to vcjob or plugin, to let vcjob controller create the headless svc with a `service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"` annotation.
Anyway, the headless svc is used to discover other replica instance, not for service consumption.

**Comment by Monokaix** [comment]
So if just let svc create first before pod created，can your problem be solved?

**Comment by tedli** [comment]
Hi @Monokaix 
Thanks for reply.
Yes.

**Comment by Monokaix** [comment]
Can you give more detail about your use case? In most case, we created pods first and  then created svc, no matter headless svc or clusterIP when using kubectl, so IMO, svc created after pod is a normal case, right?

**Comment by tedli** [comment]
Hi, @Monokaix 
Thanks for reply.
Yes, I checked the controller logic too, indeed svc created first before pods. and in my cluster, headless svc of vcjob works as expect in most times, occasionally it fails.
I think maybe something goes wrong with my k8s. controller create svc success, but at k8s apiserver side, the svc not commited yet.
I added some wating logic to work around.
```bash
# ......
master_ip=$(nslookup ${master} | awk '/^Address: / { print $2 }' | tail -n+1)
while [ -z ${master_ip} ]; do
  sleep 1
  master_ip=$(nslookup ${master} | awk '/^Address: / { print $2 }' | tail -n+1)
done
# ......
```
I'm going to close this issue. I will let informed if I got other details.

**Comment by Monokaix** [comment]
> Hi, @Monokaix Thanks for reply. Yes, I checked the controller logic too, indeed svc created first before pods. and in my cluster, headless svc of vcjob works as expect in most times, occasionally it fails. I think maybe something goes wrong with my k8s. controller create svc success, but at k8s apiserver side, the svc not commited yet. I added some wating logic to work around.
> 
> ```shell
> # ......
> master_ip=$(nslookup ${master} | awk '/^Address: / { print $2 }' | tail -n+1)
> while [ -z ${master_ip} ]; do
>   sleep 1
>   master_ip=$(nslookup ${master} | awk '/^Address: / { print $2 }' | tail -n+1)
> done
> # ......
> ```
> 
> I'm going to close this issue. I will let informed if I got other details.

That's ok.
