### ISSUE TITLE
All the documents related to Volcano are scattered at multiple places

### ISSUE THREAD

**Issue by asifdxtreme** [volcano-sh/volcano#376]
All the documents related to Volcano should be at one place in one repo so that we can avoid the duplication of the documents and it should be easy for user to find out the relevant documents.

So IMO we should move all the documents to https://github.com/volcano-sh/website/tree/master/content/en/docs and in our Readme we should give the reference of this instead of actual contents. The [website documentation](https://volcano.sh/docs/) is a good way to handle all the docs and it also gives the option of search which will he helpful for users to find the relevant stuff.

/cc @k82cn @kevin-wangzefeng @hzxuzhonghu

**Comment by k82cn** [comment]
If want to use webiste, please polish it firstly.

**Comment by asifdxtreme** [comment]
> If want to use webiste, please polish it firstly.

okay I am working on the website to make it better, I will slowly migrate all the docs to website and once the website is in good shape then we can delete the docs from this repo and just keep 1 copy of the docs in the website.

/assign
