### ISSUE TITLE
Volcano Supports K8s v1.31

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3765]
### What is the problem you're trying to solve

Volcano does not support k8s v1.31

### Describe the solution you'd like

K8s v1.31 has officially released，volcano should support v1.31

### Additional context

K8 v1.31 changelog https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.31.md#changelog-since-v1300

**Comment by Monokaix** [comment]
Please refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/adapt-k8s-todo.md to start.
Volumebinding part is a little complex so this feature will be splited into two tasks.
Task list

- [ ] basic adapt except volumebinding part
- [ ] volumebinding part, should sync from k8s v1.31

**Comment by vie-serendipity** [comment]
Hi, @Monokaix  I interested to work on this

**Comment by Monokaix** [comment]
> Hi, @Monokaix I interested to work on this

That's great! You can do the first task: )

**Comment by vie-serendipity** [comment]
I made a PR to adapt the volcano apis to Kubernetes 1.31 first, https://github.com/volcano-sh/apis/pull/137

**Comment by Monokaix** [comment]
> I made a PR to adapt the volcano apis to Kubernetes 1.31 first, [volcano-sh/apis#137](https://github.com/volcano-sh/apis/pull/137)

Well done! you can also follow the adapt doc to submit a pr to volcano repo.
And can you complete it within two week？this feature is a little urgent, hope you can understand: )

**Comment by vie-serendipity** [comment]
> And can you complete it within two week？this feature is a little urgent, hope you can understand: )

Sure, I'll get it done ASAP.

**Comment by Monokaix** [comment]
/close
https://github.com/volcano-sh/volcano/pull/3767
