### ISSUE TITLE
Endless eviction found when replica of all job is 1

### ISSUE THREAD

**Issue by lminzhw** [volcano-sh/volcano#377]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Cluster in Volcano e2e test have 4 node that can assigned 12 pod with 1CPU in total.

I run a case that create 24 volcano job with 1 task requires 1 CPU. Obviously, half of them could not be scheduled by lack of resource.

But, I found no pod can stay in `Running` state for a long time and it will be evicted by action `relcaim`. Because those 12 unscheduled pod evict the 12 running one, and the new created pod do like this.

The eviction is endless.

**What you expected to happen**:
12 scheduled pod can run to completion.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master on 20190723
- Kubernetes version (use `kubectl version`): server v1.13.2

**Comment by TommyLike** [comment]
Related to this? https://github.com/kubernetes-sigs/kube-batch/issues/828

**Comment by lminzhw** [comment]
> Related to this? [kubernetes-sigs/kube-batch#828](https://github.com/kubernetes-sigs/kube-batch/issues/828)

Yes, It is the decision of `gang` plugin. But, I think the behavior of `gang` is not wrong, job with only one pod can be evicted normally.

What I concerned is that the eviction should not occur endless. And the job should have its chance to run to completion.

Moreover, I found that when `gang` plugin make a decision, the `proportion` plugin would be skipped. I think any plugin like `proportion` should, at least, be able to protect some pod survive from eviction.

**Comment by hzxuzhonghu** [comment]
The reclaim and preempt is too violent, I think of :
1. for task (with job.MinAvailable = 1 ) should not become a candidate simply.  
2. Tasks that have been running for a long time should not be reclaimed too.

**Comment by sivanzcw** [comment]
#538 will resolve the issue
