### ISSUE TITLE
During the process of using Volcano, I first created a PodGroup named fixed-pg, and then I created a Job named test-vcjob, hoping to add test-vcjob to fixed-pg. However, I found that this Job always creates a new PodGroup instead of joining the existing one.

### ISSUE THREAD

**Issue by tsingst** [volcano-sh/volcano#3793]
### Please describe your problem in detail

apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  name: fixed-pg
  namespace: default
spec:
  minMember: 1
  priorityClassName: high-priority
  queue: fixed-queue

### Any other relevant information

apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  podGroup: fixed-pg
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: nginx
              imagePullPolicy: IfNotPresent
              name: job-nginx
              resources:
                requests:
                  cpu: "1"
          restartPolicy: OnFailure

**Comment by Monokaix** [comment]
vcjob is not supported to set pg manually, it will always create a pg.

**Comment by tsingst** [comment]
Tks. And then i have another question:

**Comment by tsingst** [comment]
What is the purpose of pre-created PodGroups (PG) in Volcano?

**Comment by tsingst** [comment]
What is the purpose of pre-created PodGroups (PG) in Volcano?

**Comment by Monokaix** [comment]
> What is the purpose of pre-created PodGroups (PG) in Volcano?

It's ususally used for bare pods, such as spark job submitted to k8s, and user should create a podGroup manually to manage   
 a group of pods.

**Comment by tsingst** [comment]
What is the purpose of pre-created PodGroups (PG) in Volcano?
