### ISSUE TITLE
How to Demonstrate Performance Benefits of Using Volcano Scheduler?

### ISSUE THREAD

**Issue by SherlockShemol** [volcano-sh/volcano#3809]
### Please describe your problem in detail

Hi, I'm new here and I have some basic questions:

- How can I demonstrate the performance benefits of using Volcano as a scheduler? Should I run benchmark tests to assess this?
- If I modify some scheduling strategies, how can I determine if the modified strategy is more efficient than the previous one?
- I’m interested in contributing to the project. Could you please suggest where I should start, and if there are any small issues that are currently open and suitable for a new contributor?

Thank you for your help!

**Comment by hwdef** [comment]
1. please check https://github.com/volcano-sh/volcano/pull/3730
2. same as above
3. some issue has `good first issue` https://github.com/volcano-sh/volcano/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

ps: You can also try adding some features you need

Thanks!

**Comment by SherlockShemol** [comment]
> 1. please check [feat: add benchmark code #3730](https://github.com/volcano-sh/volcano/pull/3730)
> 
>     2. same as above
> 
>     3. some issue has `good first issue` https://github.com/volcano-sh/volcano/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
> 
> 
> ps: You can also try adding some features you need
> 
> Thanks!

Thanks so much!
