### ISSUE TITLE
Deprecate --lock-object-namespace, BUT DOES NOT provide --leader-elect-resource-namespace

### ISSUE THREAD

**Issue by openxxs** [volcano-sh/volcano#3818]
### Description

scheduler and controller flags mark --lock-object-namespace is deprecated, recommend us use --leader-elect-resource-namespace instead. BUT there is no --leader-elect-resource-namespace in the Flags.

### Steps to reproduce the issue

Start scheduler or controller container with --leader-elect-resource-namespace flag.

### Describe the results you received and expected

acquire leader lease failed when we use two schedulers.

### What version of Volcano are you using?

v1.10.0

### Any other relevant information

k8s 1.28

**Comment by Monokaix** [comment]
Can you paste your command flag of volcano schduler or controller? And did you have also set `--leader-elect=true`?

**Comment by openxxs** [comment]
`          args:
            - '--scheduler-name=volcano-offline'
            - '--logtostderr'
            - '--scheduler-conf=/volcano.scheduler/volcano-scheduler.conf'
            - '--enable-healthz=true'
            - '--enable-metrics=true'
            - '--default-queue=default-offline'
            - '--leader-elect=true'
            - '--lock-object-namespace=volcano-system'
            - '-v=3'
            - '--node-selector=xxx.xxx.com/node-role:common'
            - '--queue-selector=queue-scene:offline'
            - '--default-queue=default-offline'
            - '--kube-api-qps=2000'
            - '--kube-api-burst=1000'
            - 2>&1`
I use --lock-object-namespace instead now, but lease named volcano-offline (define by --scheduler-name) does not created.

I read the source code, confuse --leader-elect-resource-namespace flag is missing:
![image](https://github.com/user-attachments/assets/e4b36e47-24a8-494c-841a-bbb48fc220ae)

**Comment by Monokaix** [comment]
The new option is derived from k8s lib and defined here: https://github.com/volcano-sh/volcano/blob/8b2f9184ce4c617c04d78d10014853874c8c22cb/cmd/scheduler/main.go#L63

**Comment by openxxs** [comment]
![image](https://github.com/user-attachments/assets/945c374e-bf11-4063-b3a9-4f2e28fa70a5)
in my case, 
s.LeaderElection.ResourceName = commonutil.GenerateComponentName(s.SchedulerNames) 
does not work, just create "volcano" leases.
![image](https://github.com/user-attachments/assets/a05355d5-7d5f-44b5-856d-7ed281f7cb64)
use --leader-elect-resource-name=volcano-online for online scheduler and --leader-elect-resource-name=volcano-offline for offline scheduler,
"volcano-online" and "volcano-offline" leases are created finally.

**Comment by Monokaix** [comment]
Seems your problem solved, but please note that volcano supports unified scheduling of both online and offline workloads, it's recommended to use one scheduler: )
