### ISSUE TITLE
any plan to upgrade grpc lib in next release?

### ISSUE THREAD

**Issue by gjkyk-dev** [volcano-sh/volcano#3836]
### Please describe your problem in detail

We are using the latest 1.10.0 release, but got caught in a vulnerability scan which reports an issue in google.golang.org/grpc:v1.57.0 included in the package, wondering if there is any plan to upgrade the library in next release?

Here is the vulnerability found in this specific version: https://github.com/advisories/GHSA-m425-mq94-257g

**Comment by Monokaix** [comment]
The master branch has already upgraded to v1.65.0, so next release version will cover this.
