### ISSUE TITLE
如何实现任务插队？

### ISSUE THREAD

**Issue by caiyuanji** [volcano-sh/volcano#3848]
### Please describe your problem in detail

按照 scheduler 的处理流程，当一个调度周期开始，volcano 从 api server 获取 job 并缓存，然后opensession 逐步执行调度，在该调度周期没有结束时，如果用户有一个更紧急的 job ，如何实现快速插队？

### Any other relevant information

k8s v1.26.2

**Comment by hwdef** [comment]
The first thing to make clear is that the scheduling cycle defaults to once per second.
At the beginning of each scheduling cycle, the cache is snapshot, and this snapshot is unchangeable.
Therefore, it is impossible to jump in the queue during the scheduling period.

And I don’t think there is any urgent job that requires jumping in line within one second.
More urgent job can be scheduled in advance in the next cycle.
How to achieve this? You can modify the priority of a job.

**Comment by caiyuanji** [comment]
Thank you very much.
