### ISSUE TITLE
seems default queue creation during deployment is missing

### ISSUE THREAD

**Issue by SrinivasChilveri** [volcano-sh/volcano#388]
/kind bug

**What happened**:
```
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# vi example/job.yaml 
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# kubectl create -f ./example/job.yaml 
Error from server: error when creating "./example/job.yaml": admission webhook "validatejob.volcano.sh" denied the request: Job not created with error: queues.scheduling.incubator.k8s.io "default" not found
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# ./_output/
bin/     release/ 
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# ./_output/bin/
helm          helm-v2.13.0  linux/        
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# ./_output/bin/
helm          helm-v2.13.0  linux/        
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# ./_output/bin/linux/amd64/vcctl queue list
No resources found
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# ./_output/bin/linux/amd64/vcctl job  list
No resources found
root@root1-HP-EliteBook-840-G2:/home/root1/SriniCH/workspace/src/volcano.sh/volcano# 
```

**What you expected to happen**:

it should create the job

**How to reproduce it (as minimally and precisely as possible)**:
local deploy with minikube

**Anything else we need to know?**:

**Environment**:
- Volcano Version: latest code of commit 9d675f1db11b3fce145872c4b9ec69a12cd01712
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): Linux root1-HP-EliteBook-840-G2 4.8.0-54-lowlatency #57~16.04.1-Ubuntu SMP PREEMPT Wed May 24 18:53:23 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by thandayuthapani** [comment]
https://github.com/volcano-sh/volcano/blob/master/installer/README.md , README in installer directory has those steps to create default queue while deploying volcano.
```
Volcano scheduler utilize queues.scheduling.incubator.k8s.io to share resource, therefore default queue is required before usage.

kubectl apply -f default-queue.yaml

```

**Comment by SrinivasChilveri** [comment]
I had tried with the ./hack/local-up-volcano.sh  , so expecting this also take care by the script. 

and in script 


function install-volcano {
  # TODO: add a graceful way waiting for all crd ready
  kubectl apply -f ${RELEASE_FOLDER}/${YAML_FILENAME}
}

function uninstall-volcano {
  kubectl delete -f ${VK_ROOT}/installer/helm/chart/volcano/templates/default-queue.yaml
  kubectl delete -f ${RELEASE_FOLDER}/${YAML_FILENAME}
}

installing  no queue deployment but for uninstall its there...

I felt something missed...

**Comment by TommyLike** [comment]
@thandayuthapani  @shivramsrivastava,  xuzhonghu made a change to create default queue in scheduler recently: https://github.com/volcano-sh/volcano/commit/5075d634d191b53c216c48217396e109ddf0d9c7

**Comment by SrinivasChilveri** [comment]
@TommyLike  @hzxuzhonghu  @thandayuthapani , the problem is

in scheduler we are creating SchedulingV1alpha2 queue as shown below

if _, err := kbClient.SchedulingV1alpha2().Queues().Create(&defaultQue); err != nil && !apierrors.IsAlreadyExists(err) {
		panic(fmt.Sprintf("failed init default queue, with err: %v", err))
	}


but in admit job we are checking for the SchedulingV1alpha1().Queues()
so its failing we need to fix it.


// Check whether Queue already present or not
	if _, err := KubeBatchClientSet.SchedulingV1alpha1().Queues().Get(job.Spec.Queue, metav1.GetOptions{}); err != nil {
		msg = msg + fmt.Sprintf("Job not created with error: %v", err)
	}

**Comment by TommyLike** [comment]
@shivramsrivastava  it's here : https://github.com/volcano-sh/volcano/pull/364/files#diff-bc85b8e52ed48d401d5fe93f868f85b7R154

**Comment by SrinivasChilveri** [comment]
As this is taken care in yet to merge PR
https://github.com/volcano-sh/volcano/pull/364 , 
so closing the issue.
