### ISSUE TITLE
data race in configmgr_test.go

### ISSUE THREAD

**Issue by lowang-bh** [volcano-sh/volcano#3884]
### Description

<img width="954" alt="image" src="https://github.com/user-attachments/assets/ce996d46-909b-4a5d-a17d-c395e8d3d848" />

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

need to add rwlock

### What version of Volcano are you using?

master

### Any other relevant information

https://github.com/volcano-sh/volcano/actions/runs/12234141826/job/34125702223?pr=3862

**Comment by jxs1211** [comment]
I want to take it.

**Comment by jxs1211** [comment]
I try to reproduce the issue like:
```go
➜  volcano git:(feat/custom-bestNodeFns) ✗ go test -run ^TestStart$ -parallel 16 -race volcano.sh/volcano/pkg/agent/config -v -count 2
=== RUN   TestStart
I1214 11:51:19.060520    6272 shared_informer.go:313] Waiting for caches to sync for 
I1214 11:51:19.161349    6272 shared_informer.go:320] Caches are synced for 
I1214 11:51:19.162023    6272 configmgr.go:157] "Start configuration manager"
I1214 11:51:19.162123    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
I1214 11:51:19.162931    6272 configmgr.go:182] "Successfully started configuration manager"
I1214 11:51:19.163067    6272 configmgr.go:211] "Successfully notified listeners"
I1214 11:51:19.163164    6272 configmgr.go:211] "Successfully notified listeners"
I1214 11:51:20.164446    6272 configmgr.go:157] "Start configuration manager"
I1214 11:51:20.164585    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
I1214 11:51:20.164885    6272 configmgr.go:182] "Successfully started configuration manager"
E1214 11:51:20.164999    6272 configmgr.go:203] "Failed to notify listeners" err="error"
E1214 11:51:20.165141    6272 configmgr.go:203] "Failed to notify listeners" err="error"
I1214 11:51:20.165247    6272 configmgr.go:211] "Successfully notified listeners"
I1214 11:51:20.165363    6272 configmgr.go:211] "Successfully notified listeners"
--- PASS: TestStart (2.11s)
=== RUN   TestStart
I1214 11:51:21.166024    6272 shared_informer.go:313] Waiting for caches to sync for 
I1214 11:51:21.267217    6272 shared_informer.go:320] Caches are synced for 
I1214 11:51:21.268164    6272 configmgr.go:157] "Start configuration manager"
I1214 11:51:21.268391    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
I1214 11:51:21.268884    6272 configmgr.go:182] "Successfully started configuration manager"
I1214 11:51:21.269117    6272 configmgr.go:211] "Successfully notified listeners"
I1214 11:51:21.269289    6272 configmgr.go:211] "Successfully notified listeners"
I1214 11:51:22.270287    6272 configmgr.go:157] "Start configuration manager"
I1214 11:51:22.270415    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
I1214 11:51:22.270679    6272 configmgr.go:182] "Successfully started configuration manager"
E1214 11:51:22.270790    6272 configmgr.go:203] "Failed to notify listeners" err="error"
E1214 11:51:22.270899    6272 configmgr.go:203] "Failed to notify listeners" err="error"
I1214 11:51:22.271021    6272 configmgr.go:211] "Successfully notified listeners"
I1214 11:51:22.271134    6272 configmgr.go:211] "Successfully notified listeners"
--- PASS: TestStart (2.11s)
PASS
ok      volcano.sh/volcano/pkg/agent/config     5.528s
➜  volcano git:(feat/custom-bestNodeFns) ✗ 
```
but can't make it, I check the test case which will create a listener for each test case, so from case level the data race should not happen , and in each test case `Start` will call `SyncConfig` once and then `s.Stop` will wait the goroutinue call the `SyncConfig` twice(based on the sourceQueueObjects) sequentially, so I'm not sure why the data race happen here. Correct me if I'm wrong.

**Comment by zedongh** [comment]
> I try to reproduce the issue like:
> 
> ```go
> ➜  volcano git:(feat/custom-bestNodeFns) ✗ go test -run ^TestStart$ -parallel 16 -race volcano.sh/volcano/pkg/agent/config -v -count 2
> === RUN   TestStart
> I1214 11:51:19.060520    6272 shared_informer.go:313] Waiting for caches to sync for 
> I1214 11:51:19.161349    6272 shared_informer.go:320] Caches are synced for 
> I1214 11:51:19.162023    6272 configmgr.go:157] "Start configuration manager"
> I1214 11:51:19.162123    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> I1214 11:51:19.162931    6272 configmgr.go:182] "Successfully started configuration manager"
> I1214 11:51:19.163067    6272 configmgr.go:211] "Successfully notified listeners"
> I1214 11:51:19.163164    6272 configmgr.go:211] "Successfully notified listeners"
> I1214 11:51:20.164446    6272 configmgr.go:157] "Start configuration manager"
> I1214 11:51:20.164585    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> I1214 11:51:20.164885    6272 configmgr.go:182] "Successfully started configuration manager"
> E1214 11:51:20.164999    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> E1214 11:51:20.165141    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> I1214 11:51:20.165247    6272 configmgr.go:211] "Successfully notified listeners"
> I1214 11:51:20.165363    6272 configmgr.go:211] "Successfully notified listeners"
> --- PASS: TestStart (2.11s)
> === RUN   TestStart
> I1214 11:51:21.166024    6272 shared_informer.go:313] Waiting for caches to sync for 
> I1214 11:51:21.267217    6272 shared_informer.go:320] Caches are synced for 
> I1214 11:51:21.268164    6272 configmgr.go:157] "Start configuration manager"
> I1214 11:51:21.268391    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> I1214 11:51:21.268884    6272 configmgr.go:182] "Successfully started configuration manager"
> I1214 11:51:21.269117    6272 configmgr.go:211] "Successfully notified listeners"
> I1214 11:51:21.269289    6272 configmgr.go:211] "Successfully notified listeners"
> I1214 11:51:22.270287    6272 configmgr.go:157] "Start configuration manager"
> I1214 11:51:22.270415    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> I1214 11:51:22.270679    6272 configmgr.go:182] "Successfully started configuration manager"
> E1214 11:51:22.270790    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> E1214 11:51:22.270899    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> I1214 11:51:22.271021    6272 configmgr.go:211] "Successfully notified listeners"
> I1214 11:51:22.271134    6272 configmgr.go:211] "Successfully notified listeners"
> --- PASS: TestStart (2.11s)
> PASS
> ok      volcano.sh/volcano/pkg/agent/config     5.528s
> ➜  volcano git:(feat/custom-bestNodeFns) ✗ 
> ```
> 
> but can't make it, I check the test case which will create a listener for each test case, so from case level the data race should not happen , and in each test case `Start` will call `SyncConfig` once and then `s.Stop` will wait the goroutinue call the `SyncConfig` twice(based on the sourceQueueObjects) sequentially, so I'm not sure why the data race happen here. Correct me if I'm wrong.

Data race from go routine listener process write `l.called` and test assert read the `l.called`.

The `s.Stop()` method only stopped the event source, but not ensure all event been proceed by listener.

**Comment by jxs1211** [comment]
> > I try to reproduce the issue like:
> > ```go
> > ➜  volcano git:(feat/custom-bestNodeFns) ✗ go test -run ^TestStart$ -parallel 16 -race volcano.sh/volcano/pkg/agent/config -v -count 2
> > === RUN   TestStart
> > I1214 11:51:19.060520    6272 shared_informer.go:313] Waiting for caches to sync for 
> > I1214 11:51:19.161349    6272 shared_informer.go:320] Caches are synced for 
> > I1214 11:51:19.162023    6272 configmgr.go:157] "Start configuration manager"
> > I1214 11:51:19.162123    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> > I1214 11:51:19.162931    6272 configmgr.go:182] "Successfully started configuration manager"
> > I1214 11:51:19.163067    6272 configmgr.go:211] "Successfully notified listeners"
> > I1214 11:51:19.163164    6272 configmgr.go:211] "Successfully notified listeners"
> > I1214 11:51:20.164446    6272 configmgr.go:157] "Start configuration manager"
> > I1214 11:51:20.164585    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> > I1214 11:51:20.164885    6272 configmgr.go:182] "Successfully started configuration manager"
> > E1214 11:51:20.164999    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> > E1214 11:51:20.165141    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> > I1214 11:51:20.165247    6272 configmgr.go:211] "Successfully notified listeners"
> > I1214 11:51:20.165363    6272 configmgr.go:211] "Successfully notified listeners"
> > --- PASS: TestStart (2.11s)
> > === RUN   TestStart
> > I1214 11:51:21.166024    6272 shared_informer.go:313] Waiting for caches to sync for 
> > I1214 11:51:21.267217    6272 shared_informer.go:320] Caches are synced for 
> > I1214 11:51:21.268164    6272 configmgr.go:157] "Start configuration manager"
> > I1214 11:51:21.268391    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> > I1214 11:51:21.268884    6272 configmgr.go:182] "Successfully started configuration manager"
> > I1214 11:51:21.269117    6272 configmgr.go:211] "Successfully notified listeners"
> > I1214 11:51:21.269289    6272 configmgr.go:211] "Successfully notified listeners"
> > I1214 11:51:22.270287    6272 configmgr.go:157] "Start configuration manager"
> > I1214 11:51:22.270415    6272 configmgr.go:79] "Configmap already exists" name="volcano-agent-configuration" namespace="kube-system"
> > I1214 11:51:22.270679    6272 configmgr.go:182] "Successfully started configuration manager"
> > E1214 11:51:22.270790    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> > E1214 11:51:22.270899    6272 configmgr.go:203] "Failed to notify listeners" err="error"
> > I1214 11:51:22.271021    6272 configmgr.go:211] "Successfully notified listeners"
> > I1214 11:51:22.271134    6272 configmgr.go:211] "Successfully notified listeners"
> > --- PASS: TestStart (2.11s)
> > PASS
> > ok      volcano.sh/volcano/pkg/agent/config     5.528s
> > ➜  volcano git:(feat/custom-bestNodeFns) ✗ 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but can't make it, I check the test case which will create a listener for each test case, so from case level the data race should not happen , and in each test case `Start` will call `SyncConfig` once and then `s.Stop` will wait the goroutinue call the `SyncConfig` twice(based on the sourceQueueObjects) sequentially, so I'm not sure why the data race happen here. Correct me if I'm wrong.
> 
> Data race from go routine listener process write `l.called` and test assert read the `l.called`.
> 
> The `s.Stop()` method only stopped the event source, but not ensure all event been proceed by listener. So it may happenned execute assert with listener process SyncConfig background

Gotcha, the last item may be popped out to do write operation, but at the same time when the `s.Stop` will release the holding to do read operation when catched the queue is empty, that where the date race happens, I saw your PR to fix it by adding `wg.WaitStopped` to guarantee the write operation is completed before reading.
