### ISSUE TITLE
[Umbrella] Proposed to add a descheduler component to enhance descheduling capabilities

### ISSUE THREAD

**Issue by Monokaix** [volcano-sh/volcano#3889]
### What is the problem you're trying to solve

Resource utilization and load balancing are issues that users are more concerned about, these are very dependent on the capabilities of the scheduler. Volcano now provides stable scheduling capabilities, but scheduling is usually static, and node resources will change dynamically, so it is necessary to re-scheduler and the scheduler cooperates to achieve the best use effect and meet user resource utilization and load balancing needs.

Some previous discussions are here:
https://github.com/volcano-sh/volcano/issues/3300, https://github.com/volcano-sh/volcano/issues/3023

### Describe the solution you'd like

Although volcano now has a rescheduling plugin that supports rescheduling, ref https://github.com/volcano-sh/volcano/issues/1955, https://github.com/volcano-sh/volcano/pull/1923, there are the following problems:

1. There are relatively few plug-in algorithms and currently only supports utilization-based rescheduling.
2. Rescheduling is a relatively dangerous behavior because it may affect business stability and SLA. Therefore, some strict and fine-grained verification needs to be done before rescheduling and eviction, such as whether the node resources are sufficient and the node affinity is considered, as well as pod replica constraints, etc., so as to ensure that the rescheduling behavior is safe and the newly created pods can be scheduled correctly. However, the current rescheduling cannot provide fine-grained pre-eviction control and inspection.
3. The currently existing rescheduling component https://github.com/kubernetes-sigs/descheduler is very powerful. We can carry out further development based on it and support more functions, such as rescheduling based on real loads to solve the problem  mentioned in #3300
4. Re-scheduling and scheduling are two independent behaviors. Adding a re-scheduling plugin to the scheduler will cause code coupling and mixed structures, making subsequent maintenance difficult.

### Additional context

The design detail: https://docs.google.com/document/d/1AsCpmjLzJ2iDS1LFcVJDmMryIzemGhN0toiuHXLbyhc/edit?tab=t.0#heading=h.55km60qjnsi, which is derived from  #3300

**Comment by hwdef** [comment]
+1 
I think this is a good suggestion.

**Comment by JesseStutler** [comment]
+1
good idea!

**Comment by Monokaix** [comment]
Hi, team
I would recommend putting the scheduler in a separate repository named `descheduler` for a couple of reasons:

- Currently volcano descheduler is mostly inherited from upstream framework, and descheduling is a seperate feature and can be used as an independent component, so users can just deploy descheduler and no coupling with volcano scheduler.
- Both volcano main repository and scheduler have their own compatibility matrices with k8s, so putting them in separate repositories won't conflict with volcano main repository dependencies, which makes it easier for them to maintain their own repositories and be compatible with k8s.
- Compared to volcano scheduler, descheduler is not yet mature, so put it in a separate repository will not affect the volcano scheduler's functions, wait until the descheduler is mature and have more users, we can consider migrating to the main library again.

So what do you think?

**Comment by william-wang** [comment]
+1
Agree with you. It's better to maintainer it in a seperate repo currently.

**Comment by kevin-wangzefeng** [comment]
+1 to maintain descheduler implementation in a new repo.
I'd suggest also clarify the feature planning and release management guidance in the new repo, to help all community members better understand the relationship with the main repo.

**Comment by bogo-y** [comment]
> Hi, team I would recommend putting the descheduler in a separate repository named for a couple of reasons:`descheduler`
> 
> * Currently volcano descheduler is mostly inherited from upstream framework, and descheduling is a seperate feature and can be used as an independent component, so users can just deploy descheduler and no coupling with volcano scheduler.
> * Both volcano main repository and scheduler have their own compatibility matrices with k8s, so putting them in separate repositories won't conflict with volcano main repository dependencies, which makes it easier for them to maintain their own repositories and be compatible with k8s.
> * Compared to volcano scheduler, descheduler is not yet mature, so put it in a separate repository will not affect the volcano scheduler's functions, wait until the descheduler is mature and have more users, we can consider migrating to the main library again.
> 
> So what do you think?

Agree with you and I will pay attention to https://github.com/volcano-sh/descheduler too.

**Comment by Monokaix** [comment]
> > Hi, team I would recommend putting the descheduler in a separate repository named for a couple of reasons:`descheduler`
> > 
> > * Currently volcano descheduler is mostly inherited from upstream framework, and descheduling is a seperate feature and can be used as an independent component, so users can just deploy descheduler and no coupling with volcano scheduler.
> > * Both volcano main repository and scheduler have their own compatibility matrices with k8s, so putting them in separate repositories won't conflict with volcano main repository dependencies, which makes it easier for them to maintain their own repositories and be compatible with k8s.
> > * Compared to volcano scheduler, descheduler is not yet mature, so put it in a separate repository will not affect the volcano scheduler's functions, wait until the descheduler is mature and have more users, we can consider migrating to the main library again.
> > 
> > So what do you think?
> 
> Agree with you and I will pay attention to https://github.com/volcano-sh/descheduler too.

Yeah, the deschduler is ready now! https://github.com/volcano-sh/descheduler

**Comment by Antsypc** [comment]
In some scenarios, it's better to consider both which pods need to be evicted and how to schedule them later. For example, the problem mentioned in this issue, [GPU fragmentation and rescheduling](https://github.com/volcano-sh/volcano/issues/3948).

So, there might be some limitations, moving descheduler to a separate repo.

Is there any solutions to the issue above?
