### ISSUE TITLE
The Gang and Drf preemption work together more reasonable

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#390]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
I'd like to use drf plugin to share resource among jobs in the same queue.
However the drf preemptionFn has no chance to be called as it is in Tier 2.

The Gang preemptionFn is always called to execute preemption. The DRF preemptionFn is only be called when Gang preemptionFn find no victims.  This is not reasonable for many use cases.

- Job(min>1) preempt job(min==1) forever
- Job(min==1) preempt job(min==1) each other forever
- Jobs(min==1) are expected to use drf to share resource. However the Gang preemptionFn is called.

**What you expected to happen**:
When there are variables of jobs( both min>1 & min==1) in cluster. The preemption can be more reasonable while Gang and Drf are both enabled.

**Environment**:
- Volcano Version: latest

**Comment by k82cn** [comment]
@william-wang , is there any potential solution for that case?

**Comment by william-wang** [comment]
Actually, I have not got a good solution so far. There are two potential solutions. 

1.  Chane the default configuraiion and move drf plugin to Tier 1 when preemt enabled.
  - call gang.preemptionFn against  preemptees (min>1) to get victims1 
  - call drf.preemptionFn against all preemptees to get victims2 
  - get intersection from victims1 and victims2

2. Change current tier/plugin design principal. Continue to execute tier 2 plugin even when victims has already been got from tier1. Then get the victim intersection from tier1 gang preemptionFn and tier2 drf preemptionFn.

If there is a plugin that combine the drf and gang together for preemption. That's might be better :)

**Comment by william-wang** [comment]
@k82cn 
After evaluation, I suggest move drf plugin to Tier1. Please correct me if the idea is insufficient.
The reason is 
- After move to tier1, there is no conflict with other plugins in Tier1. Please see the attachment.
- The drf plugin preemptionFn will benifit the Gang preemption in some cases.
Currently, the Gang preemptionFn does not have a good termination condition for preemption.
For example, 
A job: 1000 tasks, 900 completed, min=10
B job: 100 tasks, 10 completed, min=10
Job A and JobB both meet preemptor and preemptee conditions. They preempt each other. This is
not efficient.

How do you think about moving drf to Tier1 solution?

**Comment by william-wang** [comment]
[PluginFn.docx](https://github.com/volcano-sh/volcano/files/3450877/PluginFn.docx)
