### ISSUE TITLE
Priority preemption does not take effect

### ISSUE THREAD

**Issue by comons** [volcano-sh/volcano#3916]
### Description

![1734948147830](https://github.com/user-attachments/assets/7f536f3e-03ab-4833-90c0-79a7c927f6e5)

### Steps to reproduce the issue

1.I configured the plug-in shown in the figure
2. This is priority config
![1734948256686](https://github.com/user-attachments/assets/5819add7-07c7-4e8d-85d6-b9d16c430926)
3.This is the configuration of the queue
![1734948362585](https://github.com/user-attachments/assets/2c285d89-fc64-4008-bd7d-1f8a2f5164e9)
4.But in the end, the higher-priority task (podgroup-job-high) does not preempt the lower-priority task (podgroup-job-low).

### Describe the results you received and expected

I want someone to help me with this

### What version of Volcano are you using?

volcano preempt bug

**Comment by zedongh** [comment]
According the document: Preemption design under the same queue.

## Preempt
### Overview
The preempt action is used for resource preemption between jobs in a queue , or between tasks in a job.The preempt action is a preemption step in the scheduling process, which >is used to deal with high-priority scheduling problems. It is used for preemption between >jobs in the same queue, or between tasks under the same job.

### Scenario
1. **Preemption between jobs in the same queue**: Multiple departments in a company share a cluster, and each department can be mapped into a Queue. **Resources of different** **departments cannot be preempted from each other.** This mechanism can well guarantee the isolation of resources of departments..In complex scheduling scenarios, basic resources (CPUs, disks, GPUs, memory, network bandwidth) are allocated based on services: In computing-intensive scenarios, such as AI and high-performance scientific computing, queues require more computing resources, such as CPUs, GPUs, and memory. Big data scenarios, such as the Spark framework, have high requirements on disks. Different queues share resources. If AI jobs preempts all CPU resources, jobs in queues of other scenarios will starve. Therefore, the queue-based resource allocation is used to ensure service running.
2. Preemption between tasks in the same job: Usually, there can be multiple tasks in the same Job. For example, in complex AI application scenarios, a parameter server and multiple workers need to be set inside the TF-job, and preemption between multiple workers is supported by preemption within such scenarios.

**Comment by lowang-bh** [comment]
two solutions:
1. set minMember less than your low-priority job‘s total pods number 
2. set enablePreemptable to false in gang plugin

**Comment by comons** [comment]
1.The high-priority job count is one and low-priority job count is two. 
2. I tried to remove the action: enqueue . And then, The preempt action is correct.

**Comment by hwdef** [comment]
Yes, `enqueue` is conflict with `preempt`
