### ISSUE TITLE
Add tutorial & README

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#4]
We need to update tutorial & README accordingly for volcano.

**Comment by asifdxtreme** [comment]
@k82cn okay, will add it accordingly

**Comment by asifdxtreme** [comment]
Relevant docs has been added via PR's https://github.com/volcano-sh/website/pull/26 https://github.com/volcano-sh/website/pull/23  
@k82cn Do we need to add more docs to the website or we can go ahead and close this issue?

Current preview of the website is here https://asif-volcano.netlify.com/docs/

**Comment by asifdxtreme** [comment]
The document and tutorial has been updated, I am going ahead to close this issue, feel free to reopen it anytime if any concerns.
