### ISSUE TITLE
ssh plugin adds user flag

### ISSUE THREAD

**Issue by chenyangxueHDU** [volcano-sh/volcano#403]
> /kind feature

**What happened**:
The ssh plugin has --no-root flag for common user ssh, but I need to cp/link .ssh dir to user home dir.

**What you expected to happen**:
I would like to add --user flag to mount ssh configmap to user home dir, like --user=someone, mount .ssh to /home/users/someone/.ssh

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
hm... how to change the ownership of `.ssh`?

**Comment by hzxuzhonghu** [comment]
Currently, the permission is 0600, which is decided by ssh.

@chenyangxueHDU Do you mean you want to use a specific user instead of root in your docker images?

**Comment by TommyLike** [comment]
I guess he is asking whether volcano could mount the ssh config file into a user default folder, for instance `/home/user1/.ssh/`. This is not supported now, see https://github.com/volcano-sh/volcano/blob/1a856a19c44c41257d71de52e0a10c66bc001af9/pkg/controllers/job/plugins/ssh/ssh.go#L97

cc @k82cn  @hzxuzhonghu

**Comment by chenyangxueHDU** [comment]
> hm... how to change the ownership of `.ssh`?

Yes, it's the problem. I think we can pass uid/gid, then we can change the ownership

**Comment by chenyangxueHDU** [comment]
> Currently, the permission is 0600, which is decided by ssh.
> 
> @chenyangxueHDU Do you mean you want to use a specific user instead of root in your docker images?

yes, I use the `runuser` to run the command.

**Comment by chenyangxueHDU** [comment]
> I guess he is asking whether volcano could mount the ssh config file into a user default folder, for instance `/home/user1/.ssh/`. @chenyangxueHDU This is not supported now, see
> 
> https://github.com/volcano-sh/volcano/blob/1a856a19c44c41257d71de52e0a10c66bc001af9/pkg/controllers/job/plugins/ssh/ssh.go#L97
> 
> cc @k82cn @hzxuzhonghu

I know, so it is a feature

**Comment by hzxuzhonghu** [comment]
It makes sense, we can provide a user flag for ssh plugin to allow users pass a user,  and make `root` as the default value. 

And we should also prevent users from setting `RunAsUser` non root without providing the user name.

**Comment by chenyangxueHDU** [comment]
> It makes sense, we can provide a user flag for ssh plugin to allow users pass a user, and make `root` as the default value.
> 
> And we should also prevent users from setting `RunAsUser` non root without providing the user name.

Yes

**Comment by k82cn** [comment]
That's OK to me to have such feature, some HPC user would like to run application as no-root user.

**Comment by TommyLike** [comment]
what if I provide a non-exists user?

**Comment by hzxuzhonghu** [comment]
Good question， the answer is job will definitely fail.
We can not detect whether the user exists by the volcano job template. This should be guaranteed by users.

**Comment by zrss** [comment]
/cc

i'd like the ssh plugin can define the ssh key file path too

such as `/opt/platform/.ssh` or something else

**Comment by hzxuzhonghu** [comment]
OK
