### ISSUE TITLE
Enhance Binpack for dominant resources

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#410]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

In binpack plugin, we consider all resources almost equally (with weight); but there's a problem that  the cpu/mem maybe exhausted but GPUs are idle, and those GPU can not be used because GPU apps also need some cpu/mem to run.

The solution in my mind is to also consider dominant resource of node; and the binpack plugin should consider the dominant resource of Pod and Node together.

**Comment by hzxuzhonghu** [comment]
Is #380 addressed this?

**Comment by lminzhw** [comment]
> Is #380 addressed this?

No, #380 support the basic binpack policy, but the problem in this issue still exist.

**Comment by jeffgx619** [comment]
Do we have any update for this ? We have the same use-case as well. Currently, we pre-reserve several CPU resources for GPUs.

**Comment by k82cn** [comment]
Hope we can have this in 0.3; if you have any proposal, please feel free to share it :)
