### ISSUE TITLE
Update PodGroup's status by PodGroupController

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#425]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, the PodGroupController will manage PodGroup's lifecycle, it's better to let PodGroupController to update PodGroup's status instead of scheduler; that'll also help to reduce scheduler's QPS :) Because of DelayPodCreation, the `InQueue` state has to be updated by scheduler.

**Comment by hzxuzhonghu** [comment]
In podgroup controller we can update status.Phase , but i am afraid we cannot update Conditions.

https://github.com/volcano-sh/volcano/blob/95de4ef151ba707358d5d979bdb3d647934e73bb/pkg/scheduler/framework/session.go#L111-L122

**Comment by k82cn** [comment]
hm... yes, it seems updating `phase` is unnecessary for controller :)
