### ISSUE TITLE
Skip jobs that have successfully completed the specified number of pods or already reached its parallelism

### ISSUE THREAD

**Issue by yuanchen8911** [volcano-sh/volcano#428]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

The current scheduler does not check if a job has successfully completed the specified number of pods defined in the job file by 'completions'. As a result, it repeatedly performs many unnecessary operations. Also, it does not check the job's parallelism parameter, which can cause inefficiency too. 

**What you expected to happen**:

During each scheduling session, first check if a job has successfully completed the specified number of pods or if its active pods reaches the parallelism. If so, skip the job. If the number of active pods exceeds its parallelism, we may need to delete some pods.  

This may require the following changes.
- Add two new fields to JobInfo: Completions, Parallelism
- Add a new value to PodGroup.Status.Phase: Completed
- Modify the logic in scheduler/framework/session.go, scheduler/api/job_info.go, apis/scheduling/types.go and maybe actions as needed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
@yuanchen8911 , which kind of workload requires this feature, e.g. Spark, TF?

**Comment by yuanchen8911** [comment]
My point is that **the batch scheduler should check the _completions_ and _parallelism_ parameters as the K8S scheduler does**. Otherwise, what's the point of having the two parameter in a job description file? https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go

"_Job specifies a number of completions.  This type of job signals success by having that number of successes.  Since we do not start more pods than there are remaining completions, there should not be any remaining active pods once this count is reached_."

Also, the K8S scheduler never launches more pods if the active pod of a job reaches its parallelism and deletes additional pods if the number of active pods is greater than the parallelism.

As a general scheduler, i think batch scheduler should support a variety of workloads other than spark, TF and MPI. It's not unusual for machine learning algorithms to launch more parallel workers and to be considered completed as long as a certain number of workers finish executions. Generally speaking, the completion parameter is a useful feature for speculative execution.

**Comment by k82cn** [comment]
> the batch scheduler should check the completions and parallelism parameters as the K8S scheduler does.

That dependent on job controler to handle that, e.g. create pods based on parallelism parameters. Scheduler only care about the pod that created.

> As a general scheduler, i think batch scheduler should support a variety of workloads other than spark, TF and MPI.

Agree with that, so is there any specific framework we can not cover right now? Generally, it's better to update/change API based on requirements, e.g. specific framework or user scenario :)
