### ISSUE TITLE
vcctl only reads the ~/.kube/config and neglects $KUBECONFIG

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#448]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
When I created a local k8s cluster using `~/kubernetes/hack/local-up-cluster.sh`, the guideline suggested me to `export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig` instead of creating a new config in `~/.kube/`. Then the `vcctl` command line reported `Failed to list job: stat /root/.kube/config: no such file or directory` and failed to execute.
After I copyed the config file referred to $KUBECONFIG to `~/.kube/` , `vcctl` run correctly. So I doubt that the `vcctl` command line is set to read `~/.kube/config` only and neglects the enviroment variable $KUBECONFIG.

**What you expected to happen**:
When `vcctl` cannot find `~/.kube/config`, it shall get $KUBECONFIG as an alternative.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Volcano Version: release-0.2
- Kubernetes version (use `kubectl version`): v1.15.3
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
duplicate with #353

**Comment by tall49er** [comment]
I would like to work on it.

**Comment by tall49er** [comment]
So it just need to look for KUBECONFIG if default config file is missed. Is that correct?

**Comment by hzxuzhonghu** [comment]
/assign @tall49er 

correct
