### ISSUE TITLE
Can we make env plugin work in the initContainers?

### ISSUE THREAD

**Issue by chenyangxueHDU** [volcano-sh/volcano#453]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What happened**:
when i use env plugin, there is no `VK_TASK_INDEX` env in the initContainers.
**What you expected to happen**:
initContainers also have `VK_TASK_INDEX` env
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:v0.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
/kind bug

Yes, we should also support that :)

**Comment by hzxuzhonghu** [comment]
@chenyangxueHDU Why do u need this in initcontainer?

**Comment by chenyangxueHDU** [comment]
> @chenyangxueHDU Why do u need this in initcontainer?

before the job container running, i will `mkdir` on the `glusterfs` in the initContainers, and only one pod will do this.

**Comment by hzxuzhonghu** [comment]
There is no difference for you to `mkdir` in initcontainer or in normal container, assume you have 2 pods per task, each pod share the same pod template. In other word, you will have 2 init containers too.
