### ISSUE TITLE
'vcctl job run' executes with no arguments

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#454]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
when I use the command line `vcctl job run` , I forget to add arguments such as `-N job-name` and enter, then the `vcctl` executes the job `test` automatically as below:
![捕获](https://user-images.githubusercontent.com/54176503/65028173-34faea80-d96e-11e9-9c4c-0de9cb669403.PNG)

**What you expected to happen**:
report my command lacks arguments and stop

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: release-0.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
oh, we provide default job name here; I think we should reject empty job name.
