### ISSUE TITLE
installer: admission init job is unnecessary

### ISSUE THREAD

**Issue by angao** [volcano-sh/volcano#455]
I found admission init job is unnecessary in `installer/volcano-deployment.yaml` file, why not using init container in volcano-admission deployment instead of admission init job?

**Comment by angao** [comment]
@k82cn

**Comment by TommyLike** [comment]
@angao  thanks, it's not unnecessary, it's used to generate the secret that will be used for admission service, feel free to update the yaml if you feel it's a better solution then.

**Comment by k82cn** [comment]
> why not using init container in volcano-admission deployment instead of admission init job?

We used to discuss this: if admission pod failed, the secretes will be re-created by initContainer  which is not necessary. Anyway, I'm ok to move it to initContainer :)

**Comment by hzxuzhonghu** [comment]
From my understanding, we should not move this to init container, try to think when we scale up the admission controllers.

**Comment by angao** [comment]
> try to think when we scale up the admission controllers
@hzxuzhonghu   which scenarios the admission controller will scale up?

**Comment by angao** [comment]
> if admission pod failed, the secretes will be re-created by initContainer which is not necessary

yes, I agree. So both are ok.
