### ISSUE TITLE
List Volcano in Operator Hub

### ISSUE THREAD

**Issue by asifdxtreme** [volcano-sh/volcano#458]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
Can we list Volcano in https://operatorhub.io/ , this will add visibility for Volcano

**Comment by k82cn** [comment]
that'll be great !

**Comment by asifdxtreme** [comment]
> that'll be great !

https://operatorhub.io/contribute ... Seems some work needs to be done to list it on the website, it will be great if someone from the community can take up this work.
