### ISSUE TITLE
Pod with initcontainer resource request can not be scheduled

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#461]
When create a pod with initcontainer and normal containers, and the init container has resource requests, but the normal container has not set it. In such case, the pod will be pending forever.

**Comment by k82cn** [comment]
I think we already cover for this case, any clue on code?

**Comment by hzxuzhonghu** [comment]
Yes,  the below logic set deserved to zero.

```
			if attr.request.Less(attr.deserved) {
				attr.deserved = helpers.Min(attr.deserved, attr.request)
				meet[attr.queueID] = struct{}{}
				glog.V(4).Infof("queue <%s> is meet", attr.name)

			}
```

and in allocate , the queue is overused.

```
		for queueId := range queueInNamespace {
			currentQueue := ssn.Queues[queueId]
			if ssn.Overused(currentQueue) {
				glog.V(3).Infof("Namespace <%s> Queue <%s> is overused, ignore it.", namespace, currentQueue.Name)
				delete(queueInNamespace, queueId)
				continue
			}

			if queue == nil || ssn.QueueOrderFn(currentQueue, queue) {
				queue = currentQueue
			}
		}
```
/cc @lminzhw

**Comment by hzxuzhonghu** [comment]
We are not sure how scheduler considers init container resource request during the schedule.

**Comment by k82cn** [comment]
We need to check resource with `initContainers`; if there's not enough resource to start, we should not schedule it.

**Comment by hzxuzhonghu** [comment]
It is not that,  i suggest u have a look at the above code

**Comment by yuyue9284** [comment]
This cause the mpi job example in mpi-operator repo failed (https://github.com/kubeflow/mpi-operator/blob/master/examples/v1alpha2/tensorflow-benchmarks.yaml) when gang scheduling is enabled.
