### ISSUE TITLE
Dynamic resource allocation support

### ISSUE THREAD

**Issue by yuanchen8911** [volcano-sh/volcano#469]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Our batch jobs (e.g., Spark)  needs to dynamically request and release pod (executor) resources at runtime.  Do volcano's Podgroup and batch scheduler support dynamic resource allocation and how?  It seems the Spark operator implementation simply kills the existing application and restarts new one. It's apparently undesirable . 

**What you expected to happen**:

A job can dynamically update the resource configuration and the scheduler incrementally adjusts the number of pods accordingly without killing the job.

**Comment by k82cn** [comment]
xref https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/641

**Comment by y1k333** [comment]
Hi @k82cn, we are also working on a project trying to achieve gang scheduling for TensorFlow jobs. We want to write our own scheduler plugin(or modify the current gang plugin) such that the scheduler plugin can receive job specific info(e.g., the job can speed up to 1.0x with 1 worker, 1.9x with 2 workers...) from job level plugin configuration and dynamically create pods(number of workers) based on the arguments and the cluster load. I assume this feature is similar to the spark feature requested above, right? If not, please also take this feature into consideration for the v0.3 of Volcano.

**Comment by k82cn** [comment]
@y1k333 , that's interesting requirements :) so are you going to also improve job controller with plugins?

**Comment by umialpha** [comment]
Hi @y1k333 , I am strongly interesting in your ideas. I have almost the same requirements. Do you have any update? I haven't found any update for dynamically scale tensorflow jobs workers without restarting the process.

**Comment by dirtyValera** [comment]
@k82cn @y1k333 @yuanchen8911, I'm also curious if this feature was introduced. If not, is there any idea of how you solved it?
