### ISSUE TITLE
Meet an error when using go mod to manage volcano

### ISSUE THREAD

**Issue by MonkeyLi** [volcano-sh/volcano#470]
/kind bug

**What happened**:
Using go mod to define the dependency, excute "go mod tidy". And when it download the volcano module and try to unzip it, it occurs an error

"-> unzip XXXX\go\pkg\mod\cache\download\volcano.sh\volcano\@v\v0.0.0-20190927155439-9cdbf7e814f8.zip: malformed file path "example/huawei-connection/Volcano：基于云原生的高密计算解决方案.pptx": invalid char '：'"

**Environment**:
- Volcano Version: volcano.sh/volcano v0.0.0-20190927155439-9cdbf7e814f8
- Go Version: go version go1.12.6 windows/amd64
- OS (e.g. from /etc/os-release):  Win10

**Comment by k82cn** [comment]
@MonkeyLi , are you using master branch? It seems because of Chinese characters in file name, let me update it :)

**Comment by k82cn** [comment]
@MonkeyLi , please have a try :)

**Comment by MonkeyLi** [comment]
@k82cn It is solved, thanks

**Comment by k82cn** [comment]
Great! I'm going to close this issue :)
