### ISSUE TITLE
Add support for mpi slots in plugin

### ISSUE THREAD

**Issue by lminzhw** [volcano-sh/volcano#475]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:
Xref: https://github.com/volcano-sh/volcano/issues/474
The slots info could only be added to `mpiexec` by using shell command.

**What you expected to happen**:
Have a plugin to handle the slots or others info. 
Finally, the `mpiexec` command can use the host info directly but not generate it by shell command.

**Comment by hzxuzhonghu** [comment]
Should we introduce a new plugin for mpi? And following that we can also implement similar plugins for specific job.

**Comment by k82cn** [comment]
> Should we introduce a new plugin for mpi?

hm.... let's build a new plugin for mpi; we may refactor those plugins later to make them powerful, but let's build a new one for now :)

**Comment by hzxuzhonghu** [comment]
got it

**Comment by hzxuzhonghu** [comment]
@nicklhy #483 Added support for slots in mpi plugin

**Comment by jasonliu747** [comment]
@hzxuzhonghu any further update on this plugin? I saw  #483 instead of being merged, was closed.

**Comment by hzxuzhonghu** [comment]
@jasonliu747 It is long hanging there without progress, so I closed it. But if you are interested, we can reevaluate.

**Comment by jasonliu747** [comment]
@hzxuzhonghu please do :)
/cc @k82cn
