### ISSUE TITLE
How to select container runtime singularity?

### ISSUE THREAD

**Issue by malixian** [volcano-sh/volcano#481]
if you give me some example i will be very appreciate

**Comment by k82cn** [comment]
we do not have example for singularity right now; please refer to https://github.com/sylabs/singularity-cri for more detail :)

**Comment by malixian** [comment]
so you mean that just replace runtime with singularity-cri?

**Comment by k82cn** [comment]
> so you mean that just replace runtime with singularity-cri?

Yes :)
