### ISSUE TITLE
add mpi version into example mpi image tag

### ISSUE THREAD

**Issue by lminzhw** [volcano-sh/volcano#487]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

xref: https://github.com/open-mpi/ompi/issues/2224 , user @zrss met error caused by wrong mpi version when using https://github.com/volcano-sh/volcano/blob/master/example/integrations/mpi/mpi-example.yaml .

**What you expected to happen**:

Maybe we should add mpi version in docker image tag and example yaml file ?
```
              image: volcanosh/example-mpi:0.0.1
```

**Comment by k82cn** [comment]
Added a comments/description should be enough.
