### ISSUE TITLE
Can Volcano job support volumeClaimTemplates

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#509]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

old version:

https://github.com/volcano-sh/volcano/blob/master/docs/design/job-api.md#job-inputoutput

... (hope to keep the docs up to date)

new version:

https://github.com/volcano-sh/volcano/pull/498

currently, it can only set the pvc volume, that means all vj pods share the same pvc, as for now i know some platforms don't support this way to use pvc (such as Huawei CCE/EVS)

and we have this case, AI dev can select the number of instances, the resource request and the volume capacity of each instance

obviously, it need volcano to support each instance (pod) bind a independent pvc (with a limited capacity size)

maybe, volcano can ref statefulset **volumeClaimTemplate** impl

https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#creating-a-statefulset

**Comment by zrss** [comment]
kindly ping @lminzhw @k82cn

**Comment by hzxuzhonghu** [comment]
we can define different kind of pods by task, each task can contain multiple pods, and each of them share the same pod spec and same pvc. 

```
type JobSpec struct {
   ...

   // Tasks specifies the task specification of Job
   // +optional
   Tasks []TaskSpec `json:"tasks,omitempty" protobuf:"bytes,5,opt,name=tasks"`
}
```


> we have this case, AI dev can select the number of instance, the resource request and the volume capacity of each instance

>obviously, it need volcano to support each instance (pod) bind a independent pvc (with a limited capacity size)

Can you elaborate on your case?

**Comment by zrss** [comment]
emm ... to clarify

we can define diff tasks, but ref the tf distributed mode, it just has the `ps` and `worker` task, usually, train scripts run at the worker instances, and download the partial dataset from S3 (or Huawei OBS)

the dataset is diff between workers instance, so in this view, it still needs diff pvc in the same task ?

**Comment by hzxuzhonghu** [comment]
IC,  you are worried about the io performance sharing the same pv. Fair point, we should have a look in order not to break the compatibility.

**Comment by zrss** [comment]
yes, and maybe the share filesystem (or NFS) like Huawei SFS is suitable for sharing, but the disk (as Huawei EVS) is not aim to do that

**Comment by k82cn** [comment]
For now, we did not support that; but that makes sense to me. I think that's ok to add this feature :)

**Comment by zrss** [comment]
and i suppose the lifecycle of pvc/pv is not the same with volcano job (maybe it has the option, when i delete the volcano job without deleting the relative storage resource)

there has a case about AI re-training, and AI dev can recover the checkpoint (saved at the pvc/pv volume) from previous training

**Comment by k82cn** [comment]
@hzxuzhonghu , please help on this one :)

**Comment by pandaji** [comment]
Hi good day! Is there any update on this? Thanks!

**Comment by Thor-wl** [comment]
> Hi good day! Is there any update on this? Thanks!

Well, not yet. But i think that's meaningful. I'll take it into the roadmap.

**Comment by pandaji** [comment]
Thanks! @Thor-wl I think this document exactly describes what is needed . :)
https://github.com/volcano-sh/volcano/blob/master/docs/design/dedicated-volume.md

**Comment by Thor-wl** [comment]
> Thanks! @Thor-wl I think this document exactly describes what is needed . :)
> https://github.com/volcano-sh/volcano/blob/master/docs/design/dedicated-volume.md

Yes, we will realize it according the design in the feature.
