### ISSUE TITLE
Can i add a plugin out of volcano code

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#514]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:

i'd like a way to add my plugin into volcano out of volcano code, and avoid rebuilding the volcano to make it work ...

https://github.com/volcano-sh/volcano/tree/master/pkg/controllers/job/plugins

**Comment by k82cn** [comment]
hm... I think we need to build an http extender for that, as Go does not support dynamic load.

**Comment by hzxuzhonghu** [comment]
Isn't that admission webhook? Users can do whatever they want to implement these interface

```
// PluginInterface interface
type PluginInterface interface {
	// The unique name of Plugin.
	Name() string

	// for all pod when createJobPod
	OnPodCreate(pod *v1.Pod, job *vkv1.Job) error

	// do once when syncJob
	OnJobAdd(job *vkv1.Job) error

	// do once when killJob
	OnJobDelete(job *vkv1.Job) error
}
```

**Comment by hzxuzhonghu** [comment]
I mean to intercept Job creation, pod creation and Job deletion

**Comment by zrss** [comment]
@hzxuzhonghu , thx for the reply, it will be very useful if there is doc about how to do that in volcano

**Comment by hzxuzhonghu** [comment]
Inject whatever you want to a pod and create any assisting resources when pod/job created, this is easy to be done by mutating webhook controller.
