### ISSUE TITLE
Volcano job with InitContainer the status is confuse

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#521]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

**What happened**:

2 ps and 2 worker, but 2 ps with the `sleep 10000` init container, and from the status of vj, i don't know it has some pods wait at the `Init` status

![image](https://user-images.githubusercontent.com/8072378/68638382-59251300-053c-11ea-862b-73ec74a6b0ac.png)

```
phase: Inqueue
```

![image](https://user-images.githubusercontent.com/8072378/68638432-8245a380-053c-11ea-81b0-ff74be235ec7.png)

**What you expected to happen**:

add a status of Init ? or how can i know there are some pods wait at Init status from the status of vj job

the number of `pending` == `Init` ?

**Comment by hzxuzhonghu** [comment]
make sense, would you like to help fix it?

**Comment by zrss** [comment]
add a init status ? if i have time, i will do ~
