### ISSUE TITLE
Does batch scheduler support multiple cluster connected with virtual-kubelet?

### ISSUE THREAD

**Issue by carmark** [volcano-sh/volcano#524]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
For now, we did not support that :(

Also got similar requirements , that's great to have this feature to support virtual kubelet :)

**Comment by carmark** [comment]
@k82cn @lminzhw any update?

**Comment by lminzhw** [comment]
> @k82cn @lminzhw any update?

Sorry for my late response. I am now writing design document and I'll create pull request for review after doc finished.

**Comment by carmark** [comment]
@lminzhw That's great, thanks.

**Comment by k82cn** [comment]
xef https://github.com/cncf/soc#enhance-volcano-scheduler-to-support-virtual-kubelet
