### ISSUE TITLE
How to use "vcctl” command

### ISSUE THREAD

**Issue by zoux86** [volcano-sh/volcano#531]
i install volcano by run the command:
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
And it works. i can create the example/job.yaml

but when i run vcctl, it shows "vcctl: command not found".
So i want to know vcctl only works when i install from code ??

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
If you're using this from code, it's better to build `vcctl` from the code :)

BTW, the `volcano-development.yaml` will use release docker images for your system :)

**Comment by zoux86** [comment]
@k82cn  Thank, i installed volcano from code，and it works.
