### ISSUE TITLE
tekton integration

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#532]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Do the investigation on integration for Volcano and Tekton base on the discussion https://volcano-sh.slack.com/archives/CGET876H5/p1573752503048100 .

**Comment by k82cn** [comment]
xref: https://github.com/tektoncd/pipeline

**Comment by danielfbm** [comment]
@k82cn  hi~  is there any planning to support tekton? thanks
