### ISSUE TITLE
Tier of plugin enhancement

### ISSUE THREAD

**Issue by sivanzcw** [volcano-sh/volcano#539]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind feature

Description:

Volcano uses plugin mechanism to manage various functions. During the scheduling process of task, the system decides what to do next based on the execution result of each plug-in function. For example, when judging whether a pod can be bound to a node, the system need registered plugins to arbitrate whether the node is suitable for the scheduling of pod and calls the `PredicateFn` function registered by each plugin, if all plugin functions return `true`, the system thinks that the pod can be dispatched to the node and perform subsequent scheduling actions. Otherwise, the system considers that the node is not suitable for the scheduling of the pod and terminates the scheduling process of the pod on the node. 

Currently, plugins exist at different tiers. When plugins arbitrates for something, the system traverses tiers of plugin one by one until conclusion of the arbitration is reached at one of the tiers. At this time, the system needs to decide whether the arbitration process should be terminated or the next tier of plugin should be considered. In most scenarios, the arbitration results need to be made by all plugins, but there may still be some scenarios that the arbitration process should be end if plugins in the forefront tier have a decisive role and these plugins have already made the results.

The system lacks a mechanism to determine whether the arbitration process needs to be terminated if conclusion has been reached in the forefront tier.

**Comment by k82cn** [comment]
Personally, I'd like to introduce `&`, `|` and `()` logic into configuration; so we can cover all cases of plugins :)
