### ISSUE TITLE
Remove commit mechanism for pipeline in allocate action

### ISSUE THREAD

**Issue by sivanzcw** [volcano-sh/volcano#540]
/kind feature

Description:

The `allocate` action uses the `commit mechanism`. Only when the job meets the requirements of `gang`, the operations performed in the `allocate` action will be executed. Otherwise, all actions will be rolled back.

The `commit mechanism` in `allocate` action for `pipeline`  action should be canceled:

* When judging whether the job meets the requirements of `gang`, it does not calculate the task with `pipelined` state. That is to say, in the `commit mechanism`, th pipeline action is not considered.

* When the `preempt` action or the `reclaim` action is enabled, in the previous scheduling period, the pod named `poda` with `pending` state successfully evicts a running pod named `podb`, and `poda` was pipelined to the node where the `podb` is running. In the next cycle, when the `allocate` action is performed. Because the job where `poda` is located does not meet the requirements of gang, and cannot perform the pipelined action, in this scheduling period, `poda` is still in the `pending` state, and will evict other pods.

**Comment by k82cn** [comment]
I think we should cancel the pipeline if gang scheduling failed; the releasing resource should be reused by other jobs.
