### ISSUE TITLE
Add event on actions

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#56]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we only record event for `Command`s; it's better to also record an event for each actions of jobs.

**Comment by asifdxtreme** [comment]
This feature has been added by the above PR, @Rajadeepan  @k82cn can we go ahead and close this issue?

**Comment by k82cn** [comment]
Great! let's close that.
