### ISSUE TITLE
Whether dependency management has been changed from dep to mod. Now Kubernetes is using mod

### ISSUE THREAD

**Issue by mingzhuyang** [volcano-sh/volcano#596]
Whether dependency management has been changed from dep to mod. Now Kubernetes is using mod

**Comment by k82cn** [comment]
hm... we're still using `dep` right now; I'm ok to change it to mod :)

**Comment by k82cn** [comment]
@fengzixu , are you still working on this issue?

**Comment by fengzixu** [comment]
@k82cn sorry for a little busy recently. I will do it next week. Is it ok?

**Comment by k82cn** [comment]
We already update pkg management to `go mod`.

BTW, I like you icon,  the "辉耀" of Dota :)
