### ISSUE TITLE
[cross-platform support]: volcano-batch support for windows-based kube clusters

### ISSUE THREAD

**Issue by nagarjunk** [volcano-sh/volcano#598]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
Very recently, Amazon announced [windows support](https://aws.amazon.com/about-aws/whats-new/2019/10/windows-nodes-supported-by-amazon-eks/) support on their EKS Cluster & Microsoft'a own [AKS](https://docs.microsoft.com/en-in/azure/aks/windows-container-cli) will support windows-based cluster very soon (by Q2-2020), when 

- can we expect \the entire Volcano-Batch (V-B) product suite (_admission, controllers, scheduler, crd's, batch-job, etc_) would be made available for Windows-based ecosystem?
- can we see a developer preview images (for windows) pre-hosted within Microsoft's container registry?

**What you expected to happen**:
We are trying to evaluate V-B installation on both Cloud-Providers (AWS/Azure), and wanted to check if our HPC use-case (which is windows-based app) can be supported by V-B, when its deployed on a pure-windows cluster or a heterogeneous cluster

**How to reproduce it (as minimally and precisely as possible)**:
Currently all the V-B images (admission, controller, scheduler) are triggered over bash, and this includes even the [CSR request](https://github.com/volcano-sh/volcano/blob/master/installer/dockerfile/admission/gen-admission-secret.sh) handled by admission component

**Anything else we need to know?**:

**Environment**:
- Volcano Version: _latest (image from volcanosh organization)_
- Kubernetes version (use `kubectl version`): _1.14.8_
- Cloud provider or hardware configuration: _AWS (EKS) & Azure (AKS)_
- OS (e.g. from /etc/os-release): _ubuntu_
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
_Installed the complete product suite directly on public kubernetes cluster, which created kube-relevant API objects (crd's, batch job, admission, controllers, scheduler, queue)_

**Comment by k82cn** [comment]
hm... we do not have any plan for windows as not such kind of requirement; but I'd like to put it into our backlog per your request for v0.3 or v0.4 release :)
