### ISSUE TITLE
Feature:re-integrating the scheduling part through the scheduler framework

### ISSUE THREAD

**Issue by mingzhuyang** [volcano-sh/volcano#602]
The kubernetes scheduler framework supports defining new extension points through Plugin. Can Volcano consider re-integrating the scheduling part through the scheduler framework. Solve that users can only choose one of kubernetes scheduler and volcano scheduler.i can do this

**Comment by k82cn** [comment]
I'm ok to have a try if you can help; but I do not think scheduler framework is enough for our policy/algorithm. I think there're two major gaps: 1.) scheduler framework still does scheduling in pod level, but volcano does scheduling in job/podgroup level, e.g. drf, job preemption, gang. 2.) the action in volcano is similar to the plugin point of scheduler framework, but it's more flexible :)
