### ISSUE TITLE
$(VK_TASK_INDEX) does not work in vj yaml

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#611]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/kind feature

**What happened**:

vj yaml

```
              env:
              - name: BATCH_CURRENT_HOST
                value: $(VK_TASK_INDEX)
```

but it can't be resolved inside the container

```
[root@pool-train-hzs-34984 Downloads]# kubectl exec  -ti  tensorflow-benchmark-ps-0  bash
root@tensorflow-benchmark-ps-0:/opt/tf-benchmarks/scripts/tf_cnn_benchmarks# env | grep BA
BATCH_CURRENT_HOST=$(VK_TASK_INDEX)
```

**Comment by k82cn** [comment]
Why not use VK_TASK_INDEX directly?

**Comment by hzxuzhonghu** [comment]
This is not a k8s downward api, the `VK_TASK_INDEX` env is populated before the creation of pod.

**Comment by zrss** [comment]
> Why not use VK_TASK_INDEX directly?

#612 

At first, I'd like to use this environment variable to generate the port number ... but it doesn't work ...
