### ISSUE TITLE
the svc plugin auto generate the port info for each pod

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#612]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

currently, the svc plugin provides the comm address (ipv4),  but the programm also needs the port to fullfill the comm (ref the tf ps/worker mode)

```
tf.train.ClusterSpec({
    "worker": [
        "worker0.example.com:2222",
        "worker1.example.com:2222",
        "worker2.example.com:2222"
    ],
    "ps": [
        "ps0.example.com:2222",
        "ps1.example.com:2222"
    ]})
```

i suppose the svc plugin generates an increasing PORT number env `VK_GENERATED_PORT` for the pod from (30000 - 3000X), for convenience

**Comment by hzxuzhonghu** [comment]
The main blocker is that job controller does not know which port the task uses. PS: We can not rely on the container port.
