### ISSUE TITLE
shadow job in volcano should be deleted when there is no pod 

### ISSUE THREAD

**Issue by davidstack** [volcano-sh/volcano#618]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
when we create deployment or job use volcano, volcano will create an shadowgroup and  volcano job in memory,when these deployment or job is deleted, the shadowgroup and job in memory is not deleted now.
**What you expected to happen**:
delete these shadowgroup and volcano job in memory
**How to reproduce it (as minimally and precisely as possible)**:
create pod ,job ,deployment using volcano schedule,and delete pod,job ,the jobs number in memory will not descrease

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidstack** [comment]
@k82cn i have some code to clean this unused memory 
1. add isShadowGroup in Job struct
2.add podId and JobId map in ScheduCache

may be i can make a pull request

**Comment by k82cn** [comment]
@davidstack , that'll be great if you can help on this one! I'll help to review :)

**Comment by davidstack** [comment]
@k82cn  unlike kube-batch, volcano does not support to schedule k8s native deployment ? pod does must have annotion "scheduling.k8s.io/group-name".
`
func (sc *SchedulerCache) getOrCreateJob(pi *schedulingapi.TaskInfo) *schedulingapi.JobInfo {
	if len(pi.Job) == 0 {
		if pi.Pod.Spec.SchedulerName != sc.schedulerName {
			klog.V(4).Infof("Pod %s/%s will not not scheduled by %s, skip creating PodGroup and Job for it",
				pi.Pod.Namespace, pi.Pod.Name, sc.schedulerName)
		}
		return nil
	}
`

**Comment by k82cn** [comment]
we still support native deployment; but we use admission controller to create podgroup for them, so we can account those podgroup in the queue :)

**Comment by davidstack** [comment]
got it ,the pod Annotations will be update by pg_controller_handler

**Comment by k82cn** [comment]
yes :)

I'm going to close this issue; if any other comments, please feel free to re-open it :)
