### ISSUE TITLE
RFVE: Support GPU topology

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#623]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/area scheduling
/priority important-soon

**Description**:

GPU topology is important to the performance of running tasks, it necessary to imporve both scheduler and kubelet for GPU topology.

**Comment by Rui-Tang** [comment]
I found one relevent project on this year's google summer of code project.
https://summerofcode.withgoogle.com/archive/2019/projects/6336863634194432/

**Comment by carmark** [comment]
@k82cn @Rui-Tang You may refer [this project](https://github.com/gpucloud/k8s-device-plugin/tree/master/docs) as a example.

**Comment by k82cn** [comment]
@carmark , thanks very much for the info :) I'd like to build something based on that example :)

**Comment by Jeffwan** [comment]
I was taking days off recently and didn't get a chance to attend the meeting. 

Topology Manager integration with device plugin is in the latest kubernetes. Do we plan to leverage this or do something different? 
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-integration-with-the-topology-manager

**Comment by carmark** [comment]
@Jeffwan The official topology manager for Device Plugin is just for the devices with socket information.  But for different devices and topology, we may need more information and more detailed scheduler for better performance, such as GPUs, select the two GPUs in a Socket or in a PIX or in a PHB?

![image](https://user-images.githubusercontent.com/1132167/71495516-3bf89980-2889-11ea-851a-325e3c74a44f.png)

**Comment by Jeffwan** [comment]
> @Jeffwan The official topology manager for Device Plugin is just for the devices with socket information. But for different devices and topology, we may need more information and more detailed scheduler for better performance, such as GPUs, select the two GPUs in a Socket or in a PIX or in a PHB?
> 
> ![image](https://user-images.githubusercontent.com/1132167/71495516-3bf89980-2889-11ea-851a-325e3c74a44f.png)

Yeah. It makes sense.

**Comment by tianzichenone** [comment]
How is this issue going?

**Comment by jiangxiaobin96** [comment]
How about using `nvml.DeviceGetTopologyCommonAncestor` to build gpu tree

**Comment by jiangxiaobin96** [comment]
And I don't think using device-plugin to build gpu tree is a good way. Although device-plugin can use with volcano cooperatively, we still need to judge if the gpu resource in node is enough in function `predicate`. So why not build gpu tree in volcano directly and device-plugin just need to bind specific one gpu.

**Comment by shinytang6** [comment]
> And I don't think using device-plugin to build gpu tree is a good way. Although device-plugin can use with volcano cooperatively, we still need to judge if the gpu resource in node is enough in function `predicate`. So why not build gpu tree in volcano directly and device-plugin just need to bind specific one gpu.

nvml needs to run on a specific node, how to build a topo tree in volcano directly？

**Comment by shinytang6** [comment]
> How is this issue going?

Not so much, https://github.com/volcano-sh/volcano/pull/1779 does some research on GPU topology, but there is no specific plan

**Comment by jiangxiaobin96** [comment]
> > And I don't think using device-plugin to build gpu tree is a good way. Although device-plugin can use with volcano cooperatively, we still need to judge if the gpu resource in node is enough in function `predicate`. So why not build gpu tree in volcano directly and device-plugin just need to bind specific one gpu.
> 
> nvml needs to run on a specific node and then get topo info, how to build a topo tree in volcano directly？

or if we can input the gpu topology by string.

**Comment by shinytang6** [comment]
> > > And I don't think using device-plugin to build gpu tree is a good way. Although device-plugin can use with volcano cooperatively, we still need to judge if the gpu resource in node is enough in function `predicate`. So why not build gpu tree in volcano directly and device-plugin just need to bind specific one gpu.
> > 
> > 
> > nvml needs to run on a specific node and then get topo info, how to build a topo tree in volcano directly？
> 
> or if we can input the gpu topology by string.

not quite understand what you mean, do you mean that configure gpu topology of each node by configuration in volcano?

**Comment by jiangxiaobin96** [comment]
maybe can refer to Tencent work with [Gaia scheduler](https://ieeexplore.ieee.org/document/8672301) 
![image](https://user-images.githubusercontent.com/26225317/147557268-892b0ad1-a621-49dd-95bf-eb26f7915ac6.png)
Although input directly by string like "PXB PXB PHB ..." is not a clever approach

**Comment by dantegarden** [comment]
Do we already implemented this feature? GPU topology aware is important in AI scenes
