### ISSUE TITLE
RFVE: Support GPU share

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#624]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/priority important-soon
/area scheduling

**Description**:

There're several scenarios require GPU share, e.g. inference workload, dev environment; it's better to support that by default.

**Comment by Rui-Tang** [comment]
Hi, I found two relevent projects. 
https://github.com/AliyunContainerService/gpushare-device-plugin
https://github.com/AliyunContainerService/gpushare-scheduler-extender

**Comment by Rui-Tang** [comment]
These two projects share GPU by sharing GPU memory

**Comment by k82cn** [comment]
I known those two projects, that'll be great if we can build gpushare-scheduler-extender as a plugin of Volcano :)

/cc @cheyang

**Comment by k82cn** [comment]
and that should be fine to import the code from that repo, similar to what we have done to the algorithm of default scheduler :)

**Comment by Jeffwan** [comment]
@k82cn We will probably release a simple vGPU device plugin later. The GPU share idea is pretty straightforward, map physical GPU to virtual GPUs and advertise custom resources to APIServer. Ali's solution need extra extender to handle complex case for multi-GPU nodes. For us, I think we probably ask user only use it on single chip node which simplify the case a lot. I will collect more feedbacks and share here. 

I would say for some of the cloud providers who doesn't allow users to change master scheduler configurations, extender support in volcano (secondary scheduler) will help

**Comment by k82cn** [comment]
> I would say for some of the cloud providers who doesn't allow users to change master scheduler configurations, extender support in volcano (secondary scheduler) will help

Are you going to use volcano as default scheduler in your cluster? I'm ok to support extender in volcano :)

**Comment by k82cn** [comment]
> We will probably release a simple vGPU device plugin later

Will you open source it? If so, we'd like to leverage it in volcano :)

**Comment by Jeffwan** [comment]
> > I would say for some of the cloud providers who doesn't allow users to change master scheduler configurations, extender support in volcano (secondary scheduler) will help
> 
> Are you going to use volcano as default scheduler in your cluster? I'm ok to support extender in volcano :)

I mean on AWS, users can not use scheduler extender since user can not touch default scheduler configs. If volcano provides some scheduling support for custom resources, these users can adopt it as an alternative. 

> > We will probably release a simple vGPU device plugin later
> 
> Will you open source it? If so, we'd like to leverage it in volcano :)

It's in internal discussion and I will try to move it forward asap. What I understand is volcano aims to provides a generic scheduling solution for these kinds of custom resources? Using `gpushare-scheduler-extender` as an example, it does some bin pack and filter some cases that virtual GPU resources are across two different physical GPUs.

**Comment by k82cn** [comment]
> 
> 
> > > I would say for some of the cloud providers who doesn't allow users to change master scheduler configurations, extender support in volcano (secondary scheduler) will help
> > 
> > 
> > Are you going to use volcano as default scheduler in your cluster? I'm ok to support extender in volcano :)
> 
> I mean on AWS, users can not use scheduler extender since user can not touch default scheduler configs. If volcano provides some scheduling support for custom resources, these users can adopt it as an alternative.

Great! We do need to support gpu share, and that'll be great to be an alternative for your serivce :)

> 
> > > We will probably release a simple vGPU device plugin later
> > 
> > 
> > Will you open source it? If so, we'd like to leverage it in volcano :)
> 
> It's in internal discussion and I will try to move it forward asap. It's similar like `gpushare-device-plugin` but simpler. What I understand is volcano aims to provides a generic scheduling solution for these kinds of custom resources? Using `gpushare-scheduler-extender` as an example, it does some bin pack and filter some cases that virtual GPU resources are across two different physical GPUs.

Vocano aimt to be a batch system, similar to Slurm/YARN; we will include more components in this project, including device-plugin if necessary. As we'd like to provides an e2e solution for batch workload :)

**Comment by k82cn** [comment]
There's a really long discussion in upstream: https://github.com/kubernetes/kubernetes/issues/52757

**Comment by Jeffwan** [comment]
That's true. Our solution is based on https://github.com/kubernetes/kubernetes/issues/52757#issuecomment-402772200

**Comment by xiaogaozi** [comment]
https://github.com/kubernetes/kubernetes/issues/52757#issuecomment-596104168 provide a new solution from Tencent Cloud team
