### ISSUE TITLE
Provide another way to sign certificates for volcano admission controller

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#649]
/kind feature

Currently, we use this script to create a csr and use kubernetes to sign the certificate, 
https://github.com/volcano-sh/volcano/blob/master/installer/dockerfile/webhook-manager/gen-admission-secret.sh

However, there are at least two users reported failure installing volcano with certificate not found. https://volcano-sh.slack.com/archives/CGEDAT353/p1577347378003400, this is mainly caused by vendor customized k8s.

So i would propose to provide another way to generate a certificate, maybe with `openssl` or `CFSSL `

**Comment by k82cn** [comment]
@hzxuzhonghu , I'd like to know the root cause of the issue? for example, does k8s support current way? how can we sure openssl & cfssl can resolve the problem?

**Comment by hzxuzhonghu** [comment]
BY the tool, we donot rely on k8s to sign a certificate, so definitely this can be resolved

**Comment by k82cn** [comment]
what''s next steps?

**Comment by hzxuzhonghu** [comment]
@RainbowMango Are you still interested in this ？

**Comment by hzxuzhonghu** [comment]
This is done in #709
