### ISSUE TITLE
Gang is not working if there's resource fragmentation

### ISSUE THREAD

**Issue by Jeffwan** [volcano-sh/volcano#665]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Assume I have 10 nodes and every node has 6 cpus and 10G memory. Overall, the cluster has 60 cpus and 100G memory. My spark job spec is like this. 

```
  executor:
    instances: 12
    cores: 4
    memory: "8000m"
```
in total, the resources job requested is fewer than cluster available resources, Based on current scheduler code, it's also enqueueable. This pod group has been updated to inqueue and then be scheduled. 

https://github.com/volcano-sh/volcano/blob/f04dff0e310ae2712afb7bd2849670aae67b57a6/pkg/scheduler/actions/enqueue/enqueue.go#L120-L122

```
Spec:
  Min Member:  1
  Min Resources:
    Cpu:     48
    Memory:  96
```

But the real world case is one node can only fit one executor, the rest (6-4) cpu and (10 - 8) memory will be wasted and there will be 2 executors in pending status eventually. 

**What you expected to happen**:

I would like to have some simulation before scheduler mark it `inqueue=true`. I think there're few ways to do this. 

1. Is it possible to check resources in gang plugin as well? 
2. Can we run a scheduling logic to check if there's resource fragmentation issue like this and use it in above code snippet? Like 

`if ssn.JobEnqueueable(job) && ssn.JobSchedulable(job) && pgResource.LessEqual(nodesIdleRes) {`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I'd like to take the work, please give some advice and I will make the change. 

**Environment**:
- Volcano Version: development
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: EKS 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
Even though we can intercept it by enqueue, but we make it by `allocate` action. Isn't that?

**Comment by Jeffwan** [comment]
> Even though we can intercept it by enqueue, but we make it by `allocate` action. Isn't that?

That's true. `allocate` would be easier since it does real scheduling. Based on current code structure, seems `enqueue` is another to add the check, similarly like `ssn.JobEnqueueable` or `pgResource.LessEqual(nodesIdleRes)`. Let me have a double check on the code base.

**Comment by k82cn** [comment]
`enqueue` is used to avoid creating too many Pods; and that's hard to simulate it before scheduling :)
I think we may check whether the PodGroup is ready after several scheduling cycle or timeout; if it's not "ready" for a long time, restart it by PodGroup controller.
