### ISSUE TITLE
Prepare 0.1 Release

### ISSUE THREAD

**Issue by asifdxtreme** [volcano-sh/volcano#67]
- [x] Make Release branch
- [x] Run the test 
- [x] Release Notes ( may be not required as this is the first release)
- [x] Make and push docker images to https://hub.docker.com/u/volcanosh  
- [x] Publish Release in Github Releases

**Comment by k82cn** [comment]
@asifdxtreme , we're going to have first release at May 12; please help to make sure all items of milestone v0.1 is done and follow the related process to release it.

**Comment by asifdxtreme** [comment]
@k82cn Is the current code in master repo ready for release v0.1 ?

**Comment by k82cn** [comment]
that's ok, let's have our first release :)
If any issue/enhancement, we're going to have a new release :)

**Comment by asifdxtreme** [comment]
Release is done successfull https://github.com/volcano-sh/volcano/releases/tag/v0.1
