### ISSUE TITLE
Gang of JobInfos design doc

### ISSUE THREAD

**Issue by umialpha** [volcano-sh/volcano#674]
Gang of PodGroup

**Function detail**

**New API Object Struct**

```
type GangJobInfo struct {
    UID GangJobID
    Name      string
    Priority int32
    Jobs           jobsMap
}

func (g *GangJobInfo) ready() {
}
```

**YAML DEF**

```
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: GangPodGroup # This is a bad name, any suggestion?
metadata:
  name: gangPodGroup
spec:
  groups: ["podGroup1", "podGroup2", "podGroup3"]
```

**Interaction**
    **allocate**
    Currently the allocate flow is as follows.
    Namespace -> Queue -> Job -> Task.
    If GangPodGroup is brought in, the flow will be changed to 
    Namespace -> Queue -> **GangJobInfo** -> Job -> Task.

    pseudo-code

        for {
            if namespaces.empty() {
                break
            }
            namespace := namespaces.pop().(api.NamespaceName)
            queueInNamespace := ganJobInfoMaps[namespace]
            queue := selectCurrentQueue()
            gangJobInfos := queueInNamespace[queue.UID]

            gangJobInfo := gangJobInfos.pop().(*api.GangJobInfo)
            jobs := gangJobInfo.jobs
            for !jobs.empty() {
                job := jobs.pop().(*api.JobInfo)
                tasks := job.pendingTasks
                for !tasks.empty() {
                    AllocateForTask(task)
                    if job.ready() {
                        break
                    }
                }
                if !job.ready() {
                    stmt.discard()
                    break
                }
            }
            if gangJobInfo.ready() {
                stmt.commit()
            } else {
                stmt.discard()
            }
            namespaces.Push(namespace)
        }

**Compatibility**

If we do not specify this new feature, there are two options.
    1. GangJobInfo has only one JobInfo by default.
    2. `allocation` action omits the  **GangJobInfo** phase.

**Comment by k82cn** [comment]
Prefer to add `subGroups` section to `PodGroup` instead of a new kind :)

**Comment by umialpha** [comment]
> Prefer to add `subGroups` section to `PodGroup` instead of a new kind :)

It's ok for me to use `subGroups`. I use a new kind only for feature extend.
What your opinion for the rest part?  especially the `allocate` action part.

**Comment by k82cn** [comment]
the other part seems good :)

**Comment by k82cn** [comment]
btw, please help to create an design doc in [docs/design](https://github.com/volcano-sh/volcano/tree/master/) :)

**Comment by k82cn** [comment]
@umialpha , are you working on this ?

**Comment by umialpha** [comment]
yep, I was on Spring Festival and come back to work today. I will continue
my work :)

Klaus Ma <notifications@github.com>

**Comment by umialpha** [comment]
update:
I just finish the main logic. I am working on the unit test, e2e test, design doc.

**Comment by k82cn** [comment]
@umialpha , are you still working on this one? If anything would like to discuss, please join our slack at https://cloud-native.slack.com/messages/volcano :)

**Comment by umialpha** [comment]
Hi, Currently I am not working on this because I thought it was not a high priority requirement.
But I am still interesting in this item.
