### ISSUE TITLE
Remove scheduling.v1alpha1 and scheduling.v1alpha2 API

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#692]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we have three versions of scheduling CRDs: `scheduling.sigs.dev/v1alpha2`, `scheduling.incubator.k8s.io/v1alpha1` and `scheduling.volcano.sh/v1beta1`; that makes us hard to maintain those API in components.

So I'd like to **REMOVE** `scheduling.sigs.dev/v1alpha2`, `scheduling.incubator.k8s.io/v1alpha1` and provide tools for migration.

**Comment by k82cn** [comment]
/assign @thandayuthapani

@thandayuthapani , would you help on this one?

**Comment by thandayuthapani** [comment]
Yes @k82cn. I will work on this weekend for this issue.

**Comment by hzxuzhonghu** [comment]
Doesn't this make volcano incompatible?
