### ISSUE TITLE
RFVE: Add capacity plugin

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#696]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/area scheduling
/priority important-soon
/assign

**Description**:

Currently, we support `enqueue` action to control the capacity of queue and cluster; it's better to move this checking into plugin by `EnqueueableFn`. And we will add more features into the capacity plugin, e.g. threshold on borrowing and lending. The potential feature interaction is `proportion` plugin, design document is required.

**Comment by zionwu** [comment]
@k82cn Currently the capacity of the queue is the resource limit for it. In our use case, we want to have the resource request for the queue, which is the guaranteed resource for the queue.  With the capacity and the request,  the scheduler can have similar behavior as the YARN Capacity scheduler:
- The sum of request resource of all queues should be less or equal to the resource of the cluster.
- Each queue is guaranteed to have request resource when the system is busy with a lot of jobs for every queue. If it is used by other queue,  it can reclaim its resources from other queue.
-  scheduler should be either configured to use capacity plugin or proportion plugin.

What do you think?  Thanks in  advance.

**Comment by k82cn** [comment]
hm..., did more investigation recently: I think the `proportion` is similar to `capacity` scheduler, the capacity of each queue is `weight / sum of all weight`, and we already support reclaim between queue based on sharing. I'll add a design document to on what we have and what we miss; and plan related features to enhance that.

BTW, I'm thinking to rename `proportion` to `capacity` to make is easier to understand :)

**Comment by zionwu** [comment]
Great, I got it,  thank you!
