### ISSUE TITLE
Generate CA ERROR

### ISSUE THREAD

**Issue by EDGsheryl** [volcano-sh/volcano#704]
./gen-admission-secret.sh can not generate an expect result.

![image](https://user-images.githubusercontent.com/24578192/74645819-95a78100-51b3-11ea-82a2-15a523b05c7b.png)

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I use `kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml` to deploy a volcano server in my Kubernetes. And I found that the secret goes wrong. 

Besides, I can't find gen-admission-secret.sh in your repo. I think it's a risk point for your project.

**Environment**:
- Volcano Version: latest
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
`
- OS (e.g. from /etc/os-release):
`NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
`
- Kernel (e.g. `uname -a`):
`Linux super5 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by k82cn** [comment]
thanks for your input :)

/cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
installer/dockerfile/webhook-manager/gen-admission-secret.sh This is the install script.
We use k8s to sign the certificates, mostly the failure is because of your k8s cluster not configured well. We have investigated with a guy from Unisound, who met the same issue.

And we plan to provide another way to provide certificates: https://github.com/volcano-sh/volcano/issues/649

**Comment by k82cn** [comment]
> And we plan to provide another way to provide certificates: #649

When can we get this handled?
