### ISSUE TITLE
optimize the pod postfix naming style to make its length shorter

### ISSUE THREAD

**Issue by nicklhy** [volcano-sh/volcano#721]
/kind feature

**What happened**:
I just upgrade volcano from v0.2 to the latest master branch (by executing `kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
`). However, I soon noticed some of my previous model training yaml files can not be launched successfully now. By executing `kubectl describe jobs.batch.volcano.sh -n mdt ${JobName}`, I can see that the error is caused by the size overflow of some pods' names:
```shell
 Warning  FailedCreate  7s               vc-controller-manager  Error creating pods: [failed to create pod volcano-mpi-softmax-job-mpiworker-1, err: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.Ty
peMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Pod \"volcano-mpi-softmax-job-mpiworker-1\"
 is invalid: [spec.volumes[3].name: Invalid value: \"volcano-mpi-softmax-job-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh\": must be no more than 63 characters, spec.containers[0].volumeMounts[3].name: Not fo
und: \"volcano-mpi-softmax-job-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh\"]", Reason:"Invalid", Details:(*v1.StatusDetails)(0xc0008009c0), Code:422}} failed to create pod volcano-mpi-softmax-job-mpiworker-
0, err: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"
Failure", Message:"Pod \"volcano-mpi-softmax-job-mpiworker-0\" is invalid: [spec.volumes[3].name: Invalid value: \"volcano-mpi-softmax-job-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh\": must be no more than 
63 characters, spec.containers[0].volumeMounts[3].name: Not found: \"volcano-mpi-softmax-job-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh\"]", Reason:"Invalid", Details:(*v1.StatusDetails)(0xc000875020), Code
:422}} failed to create pod volcano-mpi-softmax-job-mpimaster-0, err: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersio
n:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Pod \"volcano-mpi-softmax-job-mpimaster-0\" is invalid: [spec.volumes[0].name: Invalid value: \"volcano-mpi-softmax-job-0cd
bfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh\": must be no more than 63 characters, spec.containers[0].volumeMounts[0].name: Not found: \"volcano-mpi-softmax-job-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh\"]", Rea
son:"Invalid", Details:(*v1.StatusDetails)(0xc000704ba0), Code:422}}]
```
The job name in my yaml file is "volcano-mpi-softmax-job" (which makes no trouble in Volcano V0.2), but the pod name "volcano-mpi-softmax-job-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh" breaks the 63 characters size limit of k8s pod name.

Sure I can solve this problem by making my job name "volcano-mpi-softmax-job" to a shorter one. However, I guess it would be much better if we can squeeze the postfix part "-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh" and free up some space for the user defined job name?

**How to reproduce it (as minimally and precisely as possible)**:

Just change the job name in "mpi-example.yaml" from "lm-mpi-job" to "lm-mpi-job-very-long-version" and launch it.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: the latest master branch
- Kubernetes version (use `kubectl version`): v1.15.2
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2

**Comment by hzxuzhonghu** [comment]
> volcano-mpi-softmax-job-0cdbfd01-7a0e-45e6-bf17-a580fa3a0a46-ssh

I donot remember gen so many random strs, could you please provide your job yaml?

**Comment by hzxuzhonghu** [comment]
IC, you used the ssh plugin
```
func (sp *sshPlugin) secretName(job *batch.Job) string {
	return fmt.Sprintf("%s-%s-%s", job.Name, job.UID, sp.Name())
}
```

Whatever, we should validate this

**Comment by k82cn** [comment]
> IC, you used the ssh plugin
> 
> ```
> func (sp *sshPlugin) secretName(job *batch.Job) string {
> 	return fmt.Sprintf("%s-%s-%s", job.Name, job.UID, sp.Name())
> }
> ```
> 
> Whatever, we should validate this

We should find another way to generate its name :)

**Comment by k82cn** [comment]
fixed by https://github.com/volcano-sh/volcano/pull/726
