### ISSUE TITLE
pod status of tfjob always pending after #693

### ISSUE THREAD

**Issue by merryzhou** [volcano-sh/volcano#727]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
we use volcano to schedule tfjobs, but all pods status are always pending, after some research ,we found that in #693： volcano no longer support scheduling.v1alpha1 and scheduling.v1alpha2 API。
but podgroup created by tf-operator is  scheduling.v1alpha1 version

so will volcano no longer compatible with tfjobs?  

**What you expected to happen**:
volcano can  scheduler tfjobs 、mpijobs。。

**Environment**:
- Volcano Version:
![image](https://user-images.githubusercontent.com/2818395/75618392-742d9880-5ba8-11ea-82b3-de7b67fa6a11.png)

**Comment by k82cn** [comment]
> so will volcano no longer compatible with tfjobs?

We'll continue to support tfjobs: for current tfjobs, it's better to use volcano:0.3, and we'll raise PR in tf-operator to correct that.

**Comment by YuxiJin-tobeyjin** [comment]
Not only tf-operator, other operators such as pytorch-operator, mpi-operator all have  the same problems.

**Comment by hzxuzhonghu** [comment]
We plan to release 0.4 in the next week in order to support kubeflow. And by then, i can file a pr in kubeflow.

**Comment by k82cn** [comment]
That was fixed in `kubeflow/common v3.0` and main branch of `kubeflow/tf-operator` :)
