### ISSUE TITLE
Is it reasonable to finish the scheduling of job when task of the job with higher priority predicated failed

### ISSUE THREAD

**Issue by sivanzcw** [volcano-sh/volcano#730]
The `allocate` action schedules tasks under the job in order according to the priority of task. If a task scheduled failed for node predicate failure, the scheduling loop for the job will terminate. This may cause that the scheduling failure of higher priority pod blocks the schedule of lower priority pod at the `job` level.

```
for !tasks.Empty() {
	task := tasks.Pop().(*api.TaskInfo)

	......

	predicateNodes, fitErrors := util.PredicateNodes(task, allNodes, predicateFn)
	if len(predicateNodes) == 0 {
		job.NodesFitErrors[task.UID] = fitErrors
		break
	}

	......
}
```

**Comment by k82cn** [comment]
> This may cause that the scheduling failure of higher priority pod blocks the schedule of lower priority pod at the job level.

That's expected; we need to make sure high priority pods are scheduled firstly. We will add more attributes for that, e.g. minAvailable for different tasks.
