### ISSUE TITLE
Design new command lines for Volcano.

### ISSUE THREAD

**Issue by jiangkaihua** [volcano-sh/volcano#737]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature
> /area CLI

**Description**:
By now the command line 'vcctl' is split into simple commands, like `vjob`, `vsub`, `vadmin`, etc. What else commands do we need to make it simpler in use?

[Design docs](https://github.com/volcano-sh/volcano/blob/master/docs/design/command-line-enhancement.md)

**Comment by carmark** [comment]
shall the command line follow  slurm or lsf?

**Comment by jiangkaihua** [comment]
> shall the command line follow slurm or lsf?

I think so, the format of slurm/LSF command lines are familiar to k8s users, like `srun` and `brun`, so a similar cmd `vrun` will be easily understood and in use.
