### ISSUE TITLE
Feature Request: Need a mechanism to avoid starvation (obey job priority)

### ISSUE THREAD

**Issue by xiaogaozi** [volcano-sh/volcano#748]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

In a share cluster may mixed with different type jobs, e.g. high priority job, low priority job. User always expect high priority job be scheduled first. But in some case when there are insufficient resources could be allocated to high priority job, Volcano scheduler will ignore this job and try to schedule low priority job. In the worst case, high priority job will keep waiting until low priority job release sufficient resources (i.e. starvation). This is not acceptable for user.

**What you expected to happen**:

High priority job could be scheduled before low priority job. Scheduler should try the best to avoid starvation.

**How to reproduce it (as minimally and precisely as possible)**:

Mix high and low priority jobs in a cluster

**Anything else we need to know?**:

Some previous related discussion and design from kube-batch and Volcano community:

- https://github.com/kubernetes-sigs/kube-batch/pull/686
- https://github.com/kubernetes-sigs/kube-batch/pull/847
- https://github.com/volcano-sh/volcano/issues/13
- https://github.com/volcano-sh/volcano/pull/298

**Environment**:
- Volcano Version: v0.3
- Kubernetes version (use `kubectl version`): v1.14.6
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xiaogaozi** [comment]
Should be noted that `preempt` action may resolve this problem in some case. But we may also need a new mechanism (e.g. reservation) when preemption is not acceptable.

**Comment by Gouthamkreddy1234** [comment]
Reservations will be a part future releases of v1.x (v1.0 was released in June 30 which currently does not have reservations yet). Please check this roadmap for more info - [https://github.com/volcano-sh/volcano/blob/c388b818c4dada8d63a76dbc7cf53db75bf7e26a/docs/community/roadmap.md](https://github.com/volcano-sh/volcano/blob/c388b818c4dada8d63a76dbc7cf53db75bf7e26a/docs/community/roadmap.md)

**Comment by Gouthamkreddy1234** [comment]
This feature will be a part of v1.1 and is being discussed here - [https://github.com/volcano-sh/volcano/issues/947](https://github.com/volcano-sh/volcano/issues/947)

**Comment by Thor-wl** [comment]
> This feature will be a part of v1.1 and is being discussed here - #947

This feature has been released in v1.1 on Oct 30.

**Comment by Thor-wl** [comment]
> This feature will be a part of v1.1 and is being discussed here - #947

The only thing to note is to configure volcano as follows:
`
    actions: "enqueue, elect, allocate, reserve, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
      - name: conformance
      - name: reservation
    - plugins:
      - name: drf
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
`

**Comment by k82cn** [comment]
@Thor-wl , is it ok to close for this issue?

**Comment by Thor-wl** [comment]
> @Thor-wl , is it ok to close for this issue?

Yes, resource reservation feature implementation is ready since v1.1.0. Please refer to https://github.com/volcano-sh/volcano/blob/master/docs/design/sla-plugin.md and https://github.com/volcano-sh/volcano/blob/master/docs/design/job-resource-reservation-design.md  for more details.
