### ISSUE TITLE
Example job fails on Openshit 4.3

### ISSUE THREAD

**Issue by raz-bn** [volcano-sh/volcano#773]
/kind bug

Hey I deployed Volcano on Openshift 4.3 and I am trying to create the example job from the repo
https://github.com/volcano-sh/volcano/blob/master/example/job.yaml

**What happened**:
Job stack on pending 
logs:

```
Type            Reason                                          Age                             Form                                            Message
-------         -------                                         -------                         -------                                         -------

Warning         PluginError                                     48s (x16 over 3m33s)            vc-controller-manager                           Execute plugin when job add failed, err: create secret for job <default/test-      job> with ssh plugin failed for secrets "test-job-ssh" is     forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

After a bit of searching the web it seems like an Openshift related issue which can be resolve by modifying the volcano-contorllers clusterrole.This is how the issue has been solved in the argo project:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-cluster-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflows/finalizers"]
  verbs: ["get", "list", "watch", "update", "patch"
```

However, I am not sure how to implement it in the volcano context since I can not find any mentions of finalizers in the project.Can you provide any details on how to solve it?

**Comment by raz-bn** [comment]
After Investigating father I found the solution. 
The current deployment has in it the volcano-controllers clusterrole which contains this rule:
```
- apiGroups: ["batch.volcano.sh"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "update", "delete"]
```
Modifying this role to be:
```
- apiGroups: ["batch.volcano.sh"]
    resources: ["jobs", "jobs/finalizers"]
    verbs: ["get", "list", "watch", "update", "delete"]
```
solved the issue. 

This change is one of few I had to make in order to deploy Volcano in Openshift 4.3.
Maybe in the near future, I will create a pull reqeuest for Openshift deployment.

**Comment by hzxuzhonghu** [comment]
It seems openshift treat finalizer as an important subresource

**Comment by k82cn** [comment]
hm... I think we can update deployment file or have a FAQ for that :)

**Comment by raz-bn** [comment]
> 
> 
> It seems openshift treat finalizer as an important subresource

I saw you updated the deployment file to add the finalizers. 
Take note that in order to fully deploy Volcano on Openshift you need to run those two CLI commands:
```

oc adm policy add-scc-to-user privileged -z volcano-admission -n volcano-system
oc patch deployment volcano-admission -n volcano-system -p '{"spec": {"template": {"spec": {"securityContext": {"runAsUser": 0}}}}}'
```

which I am pretty sure you can add to the deployment YAML as well.

**Comment by hzxuzhonghu** [comment]
I think this is openshift specific requirement, maybe FAQ is a good place

**Comment by k82cn** [comment]
> I think this is openshift specific requirement, maybe FAQ is a good place

+1, let's add FAQ for that :)

**Comment by hzxuzhonghu** [comment]
done https://github.com/volcano-sh/volcano/wiki/FAQ

**Comment by k82cn** [comment]
> done https://github.com/volcano-sh/volcano/wiki/FAQ

prefer to have a faq.md for each release :)
