### ISSUE TITLE
Is there a way that Volcano/K8S can inject specific nic ip address to the svc file

### ISSUE THREAD

**Issue by zrss** [volcano-sh/volcano#777]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:

Currently, volcano svc plugin can only inject a svc-url to the svc file, and the svc-url is resolved to the pod ip (or host ip, when the hostNetwork mode is enabled)

and i have some infiniband machines, it haves eth0/ib0/bond0/... i.e. multiples nics, i'd like there is a way to inject other nics ip to the svc file, such as ib0's ipv4 addr

**What you expected to happen**:

maybe, i can add the ib0's ip to the node annoation or somewhere, volcano can aware of it, and inject it to the svc file right after scheduling

**Comment by hzxuzhonghu** [comment]
Do you mean you have multi pod ips?

**Comment by zrss** [comment]
yes, to clarify, hostNetwork mode, and has multi ips

**Comment by carmark** [comment]
@zrss I did use multus as the  default cni plugin, so the pod can have more than one IP, such as overlay IP address and an underlay IP.  The IP information would be stored in Pod's annotation, so we can get that from the annotation.

**Comment by zrss** [comment]
@carmark , thx car ~ i'd like to see the power of `multus`

**Comment by hzxuzhonghu** [comment]
We can only get the pod ip/node info after the pod scheduled and run. It is very tough to be aware of which nic to use, because each node may have different nics. 

>maybe, i can add the ib0's ip to the node annoation or somewhere, volcano can aware of it, and inject it to the svc file right after scheduling

So I don't think this is viable

**Comment by zrss** [comment]
IPoIB can't be injected to the network namespace of container ...
