### ISSUE TITLE
Delete an success  pod, will cause volcano recreate an new pod to do repeat task

### ISSUE THREAD

**Issue by gaopeiliang** [volcano-sh/volcano#791]
**What happened**:
when job is running , one pod task successful completed, and delete pod some reason, then another new pod will be create to repeat do same task ....

**What you expected to happen**:
ignore successful completed delete pod event ,, and not create new same pod.... 

**How to reproduce it (as minimally and precisely as possible)**:
1.  running job  , with  short running pod successful completed and one long running pod..
2.  delete short running pod when completed ....

it will created an new short running pod to do same work

**Anything else we need to know?**:

**Environment**:

- Volcano Version:
release-0.4

- Kubernetes version (use `kubectl version`):
1.14
- OS (e.g. from /etc/os-release):
ubuntu:16

- Kernel (e.g. `uname -a`):
Linux 4.9.70-040970-generic 

- Install tools:
- Others:

**Comment by gaopeiliang** [comment]
`
func (cc *Controller) deletePod(obj interface{}) {
        ........

        if err := cc.cache.DeletePod(pod); err != nil {
		klog.Errorf("Failed to delete Pod <%s/%s>: %v in cache",
			pod.Namespace, pod.Name, err)
	}

	key := jobhelpers.GetJobKeyByReq(&req)
	queue := cc.getWorkerQueue(key)
	queue.Add(req)
}
// here  received delete pod event => delete cache  ,,  (but this pod is an successful completed and deleted some reason）

func (cc *Controller) processNextReq(count uint32) bool {
           ........
           cloneJOBINFO
           running => syncJob
           ........
}  

func (cc *Controller) syncJob(jobInfo *apis.JobInfo, updateStatus state.UpdateStatusFn) error {

          	for i := 0; i < int(ts.Replicas); i++ {
			podName := fmt.Sprintf(jobhelpers.PodNameFmt, job.Name, name, i)
			if pod, found := pods[podName]; !found {
				newPod := createJobPod(job, tc, i)
                               
                               // here will created new , because it not find in cache , even though it has 
                              //  successful completed ..... 
				if err := cc.pluginOnPodCreate(job, newPod); err != nil {
					return err
				}
				podToCreate = append(podToCreate, newPod)
			} else {
				delete(pods, podName)
				if pod.DeletionTimestamp != nil {
					klog.Infof("Pod <%s/%s> is terminating", pod.Namespace, pod.Name)
					atomic.AddInt32(&terminating, 1)
					continue
				}

				classifyAndAddUpPodBaseOnPhase(pod, &pending, &running, &succeeded, &failed, &unknown)
			}
		}
}

`

**Comment by hzxuzhonghu** [comment]
@gaopeiliang Yeah, that's the current behavior, we can cache the completed pods and in the sync handler, we ignore them during reconcile.

Would appreciate it if you can help.

**Comment by k82cn** [comment]
Good catch ! We did not check task's status in this case :)

**Comment by vincent-pli** [comment]
So, if check the `status` of `pod`, not lunch the request if the `status.phase` is `Succeeded`, could this fix the issue?

**Comment by k82cn** [comment]
hm... I think we should handle this in syncJob func :)

**Comment by vincent-pli** [comment]
@k82cn 
I think handle in syncJob maybe cannot fix the issue:
see the sample:
https://github.com/volcano-sh/volcano/blob/bab40f1afa834b000cfcd80ea8e67c748eb13253/example/job.yaml#L8-L10

The `PodEvicted` event will cause action: `RestartJob`, cannot get to `syncJob`.
The "delete after success" is not a `Evicted` actually.

**Comment by hzxuzhonghu** [comment]
In this case, we should ignore the delete event.

**Comment by k82cn** [comment]
> The PodEvicted event will cause action: RestartJob, cannot get to syncJob. The "delete after success" is not a Evicted actually.

👍 , yes; so maybe we only record an event and ignore this action :)

**Comment by vincent-pli** [comment]
@k82cn @hzxuzhonghu 
Thanks for clarify, I'm new for this project, maybe I missing something.
So I wonder to know why insist on launching `request` with `PodEvictedEvent` in a scenario not `Evicted`?  Is no-launch case issue somewhere, thanks.

**Comment by k82cn** [comment]
oh, that's ok to me for other options :) Please help to open a PR for that, we can discuss detail there.

**Comment by gaopeiliang** [comment]
what happen if we ignore all delete pod event ?
```
func (cc *Controller) deletePod(obj interface{}){
        .........

	//if err := cc.cache.DeletePod(pod); err != nil {
	//	klog.Errorf("Failed to delete Pod <%s/%s>: %v in cache",
	//		pod.Namespace, pod.Name, err)
	//}
      
       ......
}
```

maybe it would work ......

**Comment by vincent-pli** [comment]
@gaopeiliang 
It will stop create a new pod but will introduce new issue, when delete related `job` then create again, the previous deleted `task`(pod) will never create again, I guess it cause by ignore delete cache...

When avoid emit `PodEvicted` event, the issue not fixed, since we get another request: 
```
<Queue: , Job: default/test-job, Task:, Event:Unknown, ExitCode:0, Action:, JobVersion: 0>
```
it will trigger `syncJob`.
The request emit by `event handler` of `podGroup` update, that's because some one update `PodGroup` when delete success pod, I still checking who did this... maybe scheduler? need help.

**Comment by gaopeiliang** [comment]
what is the meaning delete related job then create again? create an new job?

**Comment by vincent-pli** [comment]
@gaocegege 
yes, delete then create same job, but based on my test, the previous deleted task gone, never back.

**Comment by gaopeiliang** [comment]
```
func (cc *Controller) deletePod(obj interface{}){
       ......
        
	if pod.Status.Phase != v1.PodSucceeded {
		if err := cc.cache.DeletePod(pod); err != nil {
			klog.Errorf("Failed to delete Pod <%s/%s>: %v in cache",
				pod.Namespace, pod.Name, err)
		}
	}
     ......
}
```
even though it make code  not clean
