### ISSUE TITLE
Enable more linter checks

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#792]
We should introduce https://github.com/golangci/golangci-lint to make volcano better.

I donot think i have enough bandwidth, if anyone interested, please feel free to take over.

**Comment by masihtehrani** [comment]
> We should introduce https://github.com/golangci/golangci-lint to make volcano better.
> 
> I donot think i have enough bandwidth, if anyone interested, please feel free to take over.

I added Golangci-lit to the project you can use with `make lint`. 
I fix some lint but it needed help to fix the whole project.

**Comment by hzxuzhonghu** [comment]
@masihtehrani Thanks, IMO, We can split the golangci-lint into several prs according to packages.

And ignore the others, after all fixes done, we can enable check on all pkgs/files

**Comment by masihtehrani** [comment]
> @masihtehrani Thanks, IMO, We can split the golangci-lint into several prs according to packages.
> 
> And ignore the others, after all fixes done, we can enable check on all pkgs/files

I added make lint just for two small pkg `kube` & `version` & first big package `apis`
just run with `make lint`
I don't add in Travis

**Comment by hzxuzhonghu** [comment]
Thanks, we need to cover the whole project
