### ISSUE TITLE
Arm architecture support

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#816]
## Project Description
Migrate to run volcano on arm64 platform
## Difficulty
low
## Mentor
Zhonghu Xu(@hzxuzhonghu): zhhxu2011@163.com
## Output
- build volcano binaries for arm
- build docker image for arm
- arm ci with travis
## Tech. Requirement
- docker
- go
- travis
## Related Repo
- https://github.com/volcano-sh/volcano

**Comment by odidev** [comment]
Hi Team,
I am also interested in adding arm64 support to this package. May I please ask if there is any progress in this activity so far?

**Comment by k82cn** [comment]
@odidev , any background or use case?

**Comment by snsie** [comment]
Providing multi-arch images would likely benefit many users. 

Students involved in AI research is one example. I fall under this category and am working with a cluster consisting of Raspberry Pis + two PCs. Raspberry Pis provide a cost-efficient solution for users who are experimenting with distributed training paradigms. Purchasing a cluster of PCs would be unfeasible for many students who don't have sufficient grant funding. 

Macs are also switching to arm, which accounts for about 10% of the OS market. (from wikipedia)

**Comment by k82cn** [comment]
@snsie , thanks for your feedback, that's reasonable :)

**Comment by rhenwood-arm** [comment]
@k82cn - I'm working with @odidev on projects that are important components for cloud native developers. We were interested initially in using Travis-CI with AArch64 support to check nothing breaks on AArch64.

**Comment by k82cn** [comment]
I'm not sure whether Travis-CI have free support on AArch64 as we do not have budget for CI right now :)
Overall, I'd like to support AArch64 for Volcano .

**Comment by rhenwood-arm** [comment]
@k82cn Travis-CI have zero cost AArch64 (and x86) CI :)

**Comment by k82cn** [comment]
that's great, any guidance to enable that?

**Comment by Thor-wl** [comment]
@Thor-wl

**Comment by Thor-wl** [comment]
https://github.com/volcano-sh/volcano/pull/1000
