### ISSUE TITLE
Job GC

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#82]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Make sure "completed" & "terminated" jobs will be removed later.

**Comment by hzxuzhonghu** [comment]
Isn't this the current behavior? 

The `finishedState` will execute `KillJob` action.

**Comment by k82cn** [comment]
> The `finishedState` will execute KillJob action.

The finished job is still there; we need to make sure they're GCed instead of deleting it manually, refer to ttl
