### ISSUE TITLE
Job validatation does not accept fractional GPU

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#822]
**What happened**:
Volano job validation does not accept a fractional GPU and report error.

**What you expected to happen**:
Job webhook validation should accept fractional GPU for sharing scenario.

**How to reproduce it (as minimally and precisely as possible)**:
$ cat test-gpu-job-01.yaml 
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-gpu-job-01
spec:
  minAvailable: 1
  schedulerName: volcano
  plugins:
    env: []
    ssh: []
    svc: []
  maxRetry: 5
  tasks:
    - replicas: 1
      name: "default-nginx"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: 100.79.1.215:20202/paas_cce_y00416048/nginx:latest
              imagePullPolicy: IfNotPresent
              name: nginx
              resources:
                limits:
                  nvidia.com/gpu: 0.4
          imagePullSecrets:
          - name: default-secret
          restartPolicy: OnFailure
$ kubectl apply -f test-gpu-job-01.yaml 
Error from server: error when creating "test-gpu-job-01.yaml": admission webhook "validatejob.volcano.sh" denied the request: spec.task[0].template.spec.containers[0].resources.limits[nvidia.com/gpu]: Invalid value: resource.Quantity{i:resource.int64Amount{value:5, scale:-1}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}: must be an integer.

**Environment**:
- Volcano Version: 0.4
- Kubernetes version (use `kubectl version`): 1.13
- Cloud provider or hardware configuration: Huawei Cloud
- OS (e.g. from /etc/os-release): Linux amd64 and ARM

**Comment by hzxuzhonghu** [comment]
This is fixed
