### ISSUE TITLE
Observed a panic: invalid argument to Intn（when batchNodeOrder function return err)

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#838]
> /kind bug
**What happened**:
I added a schedule plugin ，and used a function named batchNodeOrder. This funciton return a error when nodes unmeet required. But, the volcano-schedule crash.

**What you expected to happen**:
Add the job backup to queue, and run ok

**How to reproduce it (as minimally and precisely as possible)**:
```
			node := ssn.BestNodeFn(task, nodeScores)
			if node == nil {
				node = util.SelectBestNode(nodeScores)
			}
```
After these, add the node judge.  

**Anything else we need to know?**:

**Environment**:
- Volcano Version:  0.4
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration: arm64
- OS (e.g. from /etc/os-release): unbuntu 13.2
- Kernel (e.g. `uname -a`):
- Install tools:
![volcano-shedule-crash](https://user-images.githubusercontent.com/7522079/83109259-adb46800-a0f3-11ea-9d98-d34d93f4ba1f.PNG)

**Comment by k82cn** [comment]
We should check whether there's any `candidateNodes` before selecting the best one.

/help-wanted

**Comment by zishen** [comment]
> We should check whether there's any `candidateNodes` before selecting the best one.
> 
> /help-wanted

Yes，I have use AddPredicateFn to avoid this issue.
But I still hope the problem can be fixed。
