### ISSUE TITLE
Improve stability and reliability

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#842]
In order to do this, we need to supplement ut and e2e cases. And i have drafted a doc:
https://docs.google.com/spreadsheets/d/1pUQwlJMPbSZ2U0m-z-3HRRwrR6x4K2o_XyNE1mMZQZ8/edit?usp=sharing

Please note this is not complete, feel free to add.

**Comment by k82cn** [comment]
@Thor-wl , would you help on that? @hzxuzhonghu , please share this doc with write permission and update content to English :)

**Comment by Thor-wl** [comment]
@hzxuzhonghu @k82cn OK

**Comment by hzxuzhonghu** [comment]
done
