### ISSUE TITLE
Bump k8s 1.18.3

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#849]
Need to bump to k8s dependencies currently we depend on 1.16 and there is a conflict for project to import volano if the project depends on new version like 1.18.

**Comment by k82cn** [comment]
That's great, please also help to correct version number, e.g. https://github.com/volcano-sh/volcano/blob/master/go.mod#L48 .

**Comment by hzxuzhonghu** [comment]
Fixed by #855
