### ISSUE TITLE
Distributed horovod training failed

### ISSUE THREAD

**Issue by silenceli** [volcano-sh/volcano#859]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
```
# cmd
horovodrun -np 7 -H jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-master-0.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1,jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-worker-0.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1,jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-worker-1.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1,jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-worker-2.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1 python /opt/ml/job/tensorflow_mnist.py

# err_msg
Filtering local host names.
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Launched horovodrun server.
Attempted to launch horovod task servers.
Waiting for the hosts to acknowledge.
ERROR: Task 1 declared addresses {'lo': [('127.0.0.1', 55651)], 'eth0': [('192.168.101.5', 55651)]}, but has connected from a different address 192.168.101.0. This is not supported. Is the server behind NAT?
ERROR: Task 3 declared addresses {'lo': [('127.0.0.1', 20497)], 'eth0': [('192.168.101.4', 20497)]}, but has connected from a different address 192.168.101.0. This is not supported. Is the server behind NAT?
Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 876, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 792, in _run
    settings, fn_cache=fn_cache)
  File "/usr/local/lib/python3.6/site-packages/horovod/run/util/cache.py", line 120, in wrap_f
    results = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 239, in _driver_fn
    settings.num_hosts)]
  File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 238, in <listcomp>
    settings.verbose) for index in range(
  File "/usr/local/lib/python3.6/site-packages/horovod/run/task/task_service.py", line 72, in __init__
    retries=retries)
  File "/usr/local/lib/python3.6/site-packages/horovod/run/common/service/task_service.py", line 143, in __init__
    retries=retries)
  File "/usr/local/lib/python3.6/site-packages/horovod/run/common/util/network.py", line 174, in __init__
    'Linux.'.format(service_name=service_name, addresses=addresses))
horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to horovodrun task service #1 on any of the following addresses: {}.

One possible cause of this problem is that horovodrun currently requires every host to have at least one routable network interface with the same name across all of the hosts. You can run "ifconfig -a" on every host and check for the common routable interface. To fix the problem, you can rename interfaces on Linux.
```

**How to reproduce it (as minimally and precisely as possible)**:
```
# yaml file
{
  "kind": "Job",
  "spec": {
    "tasks": [
      {
        "policies": [
          {
            "action": "CompleteJob",
            "event": "TaskCompleted"
          },
          {
            "action": "TerminateJob",
            "event": "PodFailed"
          }
        ],
        "name": "master",
        "template": {
          "spec": {
            "terminationGracePeriodSeconds": 7500,
            "restartPolicy": "Never",
            "serviceAccountName": "jarvis-k8s-vcjob-default-service-account",
            "volumes": [
              {
                "emptyDir": {},
                "name": "app-volume"
              },
              {
                "hostPath": {
                  "path": "/data/k8s-jarvis/slaves/00000000-0000-0000-0000-000000000000-000/frameworks/00000000-0000-0000-0000-000000000000-0000/executors/",
                  "type": "DirectoryOrCreate"
                },
                "name": "log-volume"
              },
              {
                "emptyDir": {},
                "name": "nfs-volume"
              }
            ],
            "initContainers": [
              {
                "image": "docker-registry.qiyi.virtual/jarvis-runtime/jarvis-k8s-training-runtime:v1.1",
                "volumeMounts": [
                  {
                    "mountPath": "/opt/ml/bin",
                    "name": "app-volume"
                  },
                  {
                    "mountPath": "/opt/ml/nfs-root",
                    "name": "nfs-volume"
                  }
                ],
                "name": "runtime"
              }
            ],
            "containers": [
              {
                "securityContext": {
                  "capabilities": {
                    "add": [
                      "SYS_ADMIN"
                    ]
                  }
                },
                "name": "master",
                "image": "docker-registry.qiyi.virtual/jarvis-image/conda-tensorflow-1.14-py36-horovod:dev-04",
                "args": [
                  "bash",
                  "-c",
                  "/opt/ml/bin/start.sh"
                ],
                "volumeMounts": [
                  {
                    "mountPath": "/opt/ml/bin",
                    "name": "app-volume"
                  },
                  {
                    "mountPath": "/opt/ml/nfs-root",
                    "name": "nfs-volume"
                  },
                  {
                    "mountPath": "/mnt/mesos/sandbox",
                    "name": "log-volume",
                    "subPathExpr": "$(K8S_POD_UID)/runs/$(K8S_POD_UID)"
                  }
                ],
                "command": [
                  "/opt/ml/bin/dumb-init",
                  "--"
                ],
                "ports": [
                  {
                    "containerPort": 2222,
                    "name": "tfjob-port"
                  }
                ],
                "resources": {
                  "requests": {
                    "qiyi.com/fuse": 1,
                    "cpu": 4,
                    "nvidia.com/gpu": 1,
                    "memory": "8192.0Mi"
                  },
                  "limits": {
                    "qiyi.com/fuse": 1,
                    "cpu": 4,
                    "nvidia.com/gpu": 1,
                    "memory": "8192.0Mi"
                  }
                }
              }
            ],
            "nodeSelector": {
              "cluster-name": "jarvis-k8s-online02-gpu-training"
            }
          },
          "metadata": {
            "labels": {
              "group": "jarvis-public",
              "creator": "lihao04",
              "distributed": "True",
              "vcjob_name": "jarvis-vcjob-7f2e2b6d9e40126e1be1fd785ca2ea20",
              "cluster_name": "jarvis-k8s-online02-gpu-training",
              "role": "master",
              "task-spec": "master",
              "jarvis-qrn-type": "k8s-training",
              "team_name": "jarvis-dev-team"
            },
          }
        },
        "replicas": 1
      },
      {
        "policies": [
          {
            "action": "TerminateJob",
            "event": "PodFailed"
          }
        ],
        "name": "worker",
        "template": {
          "spec": {
            "terminationGracePeriodSeconds": 7500,
            "restartPolicy": "Never",
            "serviceAccountName": "jarvis-k8s-vcjob-default-service-account",
            "volumes": [
              {
                "emptyDir": {},
                "name": "app-volume"
              },
              {
                "hostPath": {
                  "path": "/data/k8s-jarvis/slaves/00000000-0000-0000-0000-000000000000-000/frameworks/00000000-0000-0000-0000-000000000000-0000/executors/",
                  "type": "DirectoryOrCreate"
                },
                "name": "log-volume"
              },
              {
                "emptyDir": {},
                "name": "nfs-volume"
              }
            ],
            "initContainers": [
              {
                "image": "docker-registry.qiyi.virtual/jarvis-runtime/jarvis-k8s-training-runtime:v1.1",
                "volumeMounts": [
                  {
                    "mountPath": "/opt/ml/bin",
                    "name": "app-volume"
                  },
                  {
                    "mountPath": "/opt/ml/nfs-root",
                    "name": "nfs-volume"
                  }
                ],
                "name": "runtime"
              }
            ],
            "containers": [
              {
                "securityContext": {
                  "capabilities": {
                    "add": [
                      "SYS_ADMIN"
                    ]
                  }
                },
                "name": "worker",
                "image": "docker-registry.qiyi.virtual/jarvis-image/conda-tensorflow-1.14-py36-horovod:dev-04",
                "args": [
                  "bash",
                  "-c",
                  "/opt/ml/bin/start.sh"
                ],
                "volumeMounts": [
                  {
                    "mountPath": "/opt/ml/bin",
                    "name": "app-volume"
                  },
                  {
                    "mountPath": "/opt/ml/nfs-root",
                    "name": "nfs-volume"
                  },
                  {
                    "mountPath": "/mnt/mesos/sandbox",
                    "name": "log-volume",
                    "subPathExpr": "$(K8S_POD_UID)/runs/$(K8S_POD_UID)"
                  }
                ],
                "command": [
                  "/opt/ml/bin/dumb-init",
                  "--"
                ],
                "ports": [
                  {
                    "containerPort": 2222,
                    "name": "tfjob-port"
                  }
                ],
                "resources": {
                  "requests": {
                    "qiyi.com/fuse": 1,
                    "cpu": 4,
                    "nvidia.com/gpu": 1,
                    "memory": "8192.0Mi"
                  },
                  "limits": {
                    "qiyi.com/fuse": 1,
                    "cpu": 4,
                    "nvidia.com/gpu": 1,
                    "memory": "8192.0Mi"
                  }
                }
              }
            ],
            "nodeSelector": {
              "cluster-name": "jarvis-k8s-online02-gpu-training"
            }
          },
          "metadata": {
            "labels": {
              "group": "jarvis-public",
              "creator": "lihao04",
              "distributed": "True",
              "vcjob_name": "jarvis-vcjob-7f2e2b6d9e40126e1be1fd785ca2ea20",
              "cluster_name": "jarvis-k8s-online02-gpu-training",
              "role": "worker",
              "task-spec": "other",
              "jarvis-qrn-type": "k8s-training",
              "team_name": "jarvis-dev-team"
            },
          }
        },
        "replicas": 3
      }
    ],
    "schedulerName": "volcano",
    "queue": "training-jarvis-dev-team-jarvis-k8s-online02-gpu-training",
    "policies": [
      {
        "action": "RestartJob",
        "event": "PodEvicted"
      }
    ],
    "plugins": {
      "svc": [],
      "env": [],
      "ssh": []
    },
    "minAvailable": 4
  },
  "apiVersion": "batch.volcano.sh/v1alpha1",
  "metadata": {
    "labels": {
      "cluster_name": "jarvis-k8s-online02-gpu-training",
      "group": "jarvis-public",
      "creator": "lihao04",
      "jarvis-qrn-type": "k8s-training",
      "team_name": "jarvis-dev-team",
      "distributed": "True"
    },
    "namespace": "training-jarvis-dev-team-jarvis-k8s-online02-gpu-training",
    "name": "jarvis-vcjob-7f2e2b6d9e40126e1be1fd785ca2ea20",
    "annotations": {
      "job_name": "horovod-demo200612101105",
      "qrn": "qrn:qcc:jarvis:cn-bj:jarvis-public:trainingjob:horovod-demo200612101105"
    }
  }
}
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 0.3
- Kubernetes version (use `kubectl version`): 1.16.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
@silenceli I am not an expert of horovod, just looking through some of the related code from it. 
In my view, this is because horovod requires see the server's real ip address. But from your logs, i think the master can not see the worker's real ip address, likely because of NAT.

So check the network of your cluster, this is not volcano's issue.

**Comment by k82cn** [comment]
@Thor-wl , Lei please help to run silenceli@'s example, I'd like to know why it does not work :)

**Comment by Thor-wl** [comment]
> @Thor-wl , Lei please help to run silenceli@'s example, I'd like to know why it does not work :)

OK

**Comment by Thor-wl** [comment]
> **Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug
> 
> **What happened**:
> 
> ```
> # cmd
> horovodrun -np 7 -H jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-master-0.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1,jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-worker-0.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1,jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-worker-1.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1,jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5-worker-2.jarvis-vcjob-161be0ee11a5b1ce69f82f48b2f5e8d5:1 python /opt/ml/job/tensorflow_mnist.py
> 
> # err_msg
> Filtering local host names.
> Checking ssh on all remote hosts.
> SSH was successful into all the remote hosts.
> Testing interfaces on all the hosts.
> Launched horovodrun server.
> Attempted to launch horovod task servers.
> Waiting for the hosts to acknowledge.
> ERROR: Task 1 declared addresses {'lo': [('127.0.0.1', 55651)], 'eth0': [('192.168.101.5', 55651)]}, but has connected from a different address 192.168.101.0. This is not supported. Is the server behind NAT?
> ERROR: Task 3 declared addresses {'lo': [('127.0.0.1', 20497)], 'eth0': [('192.168.101.4', 20497)]}, but has connected from a different address 192.168.101.0. This is not supported. Is the server behind NAT?
> Traceback (most recent call last):
>   File "/usr/local/bin/horovodrun", line 21, in <module>
>     run_commandline()
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 876, in run_commandline
>     _run(args)
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 792, in _run
>     settings, fn_cache=fn_cache)
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/util/cache.py", line 120, in wrap_f
>     results = func(*args, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 239, in _driver_fn
>     settings.num_hosts)]
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/run.py", line 238, in <listcomp>
>     settings.verbose) for index in range(
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/task/task_service.py", line 72, in __init__
>     retries=retries)
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/common/service/task_service.py", line 143, in __init__
>     retries=retries)
>   File "/usr/local/lib/python3.6/site-packages/horovod/run/common/util/network.py", line 174, in __init__
>     'Linux.'.format(service_name=service_name, addresses=addresses))
> horovod.run.common.util.network.NoValidAddressesFound: Horovodrun was unable to connect to horovodrun task service #1 on any of the following addresses: {}.
> 
> One possible cause of this problem is that horovodrun currently requires every host to have at least one routable network interface with the same name across all of the hosts. You can run "ifconfig -a" on every host and check for the common routable interface. To fix the problem, you can rename interfaces on Linux.
> ```
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> ```
> # yaml file
> {
>   "kind": "Job",
>   "spec": {
>     "tasks": [
>       {
>         "policies": [
>           {
>             "action": "CompleteJob",
>             "event": "TaskCompleted"
>           },
>           {
>             "action": "TerminateJob",
>             "event": "PodFailed"
>           }
>         ],
>         "name": "master",
>         "template": {
>           "spec": {
>             "terminationGracePeriodSeconds": 7500,
>             "restartPolicy": "Never",
>             "serviceAccountName": "jarvis-k8s-vcjob-default-service-account",
>             "volumes": [
>               {
>                 "emptyDir": {},
>                 "name": "app-volume"
>               },
>               {
>                 "hostPath": {
>                   "path": "/data/k8s-jarvis/slaves/00000000-0000-0000-0000-000000000000-000/frameworks/00000000-0000-0000-0000-000000000000-0000/executors/",
>                   "type": "DirectoryOrCreate"
>                 },
>                 "name": "log-volume"
>               },
>               {
>                 "emptyDir": {},
>                 "name": "nfs-volume"
>               }
>             ],
>             "initContainers": [
>               {
>                 "image": "docker-registry.qiyi.virtual/jarvis-runtime/jarvis-k8s-training-runtime:v1.1",
>                 "volumeMounts": [
>                   {
>                     "mountPath": "/opt/ml/bin",
>                     "name": "app-volume"
>                   },
>                   {
>                     "mountPath": "/opt/ml/nfs-root",
>                     "name": "nfs-volume"
>                   }
>                 ],
>                 "name": "runtime"
>               }
>             ],
>             "containers": [
>               {
>                 "securityContext": {
>                   "capabilities": {
>                     "add": [
>                       "SYS_ADMIN"
>                     ]
>                   }
>                 },
>                 "name": "master",
>                 "image": "docker-registry.qiyi.virtual/jarvis-image/conda-tensorflow-1.14-py36-horovod:dev-04",
>                 "args": [
>                   "bash",
>                   "-c",
>                   "/opt/ml/bin/start.sh"
>                 ],
>                 "volumeMounts": [
>                   {
>                     "mountPath": "/opt/ml/bin",
>                     "name": "app-volume"
>                   },
>                   {
>                     "mountPath": "/opt/ml/nfs-root",
>                     "name": "nfs-volume"
>                   },
>                   {
>                     "mountPath": "/mnt/mesos/sandbox",
>                     "name": "log-volume",
>                     "subPathExpr": "$(K8S_POD_UID)/runs/$(K8S_POD_UID)"
>                   }
>                 ],
>                 "command": [
>                   "/opt/ml/bin/dumb-init",
>                   "--"
>                 ],
>                 "ports": [
>                   {
>                     "containerPort": 2222,
>                     "name": "tfjob-port"
>                   }
>                 ],
>                 "resources": {
>                   "requests": {
>                     "qiyi.com/fuse": 1,
>                     "cpu": 4,
>                     "nvidia.com/gpu": 1,
>                     "memory": "8192.0Mi"
>                   },
>                   "limits": {
>                     "qiyi.com/fuse": 1,
>                     "cpu": 4,
>                     "nvidia.com/gpu": 1,
>                     "memory": "8192.0Mi"
>                   }
>                 }
>               }
>             ],
>             "nodeSelector": {
>               "cluster-name": "jarvis-k8s-online02-gpu-training"
>             }
>           },
>           "metadata": {
>             "labels": {
>               "group": "jarvis-public",
>               "creator": "lihao04",
>               "distributed": "True",
>               "vcjob_name": "jarvis-vcjob-7f2e2b6d9e40126e1be1fd785ca2ea20",
>               "cluster_name": "jarvis-k8s-online02-gpu-training",
>               "role": "master",
>               "task-spec": "master",
>               "jarvis-qrn-type": "k8s-training",
>               "team_name": "jarvis-dev-team"
>             },
>           }
>         },
>         "replicas": 1
>       },
>       {
>         "policies": [
>           {
>             "action": "TerminateJob",
>             "event": "PodFailed"
>           }
>         ],
>         "name": "worker",
>         "template": {
>           "spec": {
>             "terminationGracePeriodSeconds": 7500,
>             "restartPolicy": "Never",
>             "serviceAccountName": "jarvis-k8s-vcjob-default-service-account",
>             "volumes": [
>               {
>                 "emptyDir": {},
>                 "name": "app-volume"
>               },
>               {
>                 "hostPath": {
>                   "path": "/data/k8s-jarvis/slaves/00000000-0000-0000-0000-000000000000-000/frameworks/00000000-0000-0000-0000-000000000000-0000/executors/",
>                   "type": "DirectoryOrCreate"
>                 },
>                 "name": "log-volume"
>               },
>               {
>                 "emptyDir": {},
>                 "name": "nfs-volume"
>               }
>             ],
>             "initContainers": [
>               {
>                 "image": "docker-registry.qiyi.virtual/jarvis-runtime/jarvis-k8s-training-runtime:v1.1",
>                 "volumeMounts": [
>                   {
>                     "mountPath": "/opt/ml/bin",
>                     "name": "app-volume"
>                   },
>                   {
>                     "mountPath": "/opt/ml/nfs-root",
>                     "name": "nfs-volume"
>                   }
>                 ],
>                 "name": "runtime"
>               }
>             ],
>             "containers": [
>               {
>                 "securityContext": {
>                   "capabilities": {
>                     "add": [
>                       "SYS_ADMIN"
>                     ]
>                   }
>                 },
>                 "name": "worker",
>                 "image": "docker-registry.qiyi.virtual/jarvis-image/conda-tensorflow-1.14-py36-horovod:dev-04",
>                 "args": [
>                   "bash",
>                   "-c",
>                   "/opt/ml/bin/start.sh"
>                 ],
>                 "volumeMounts": [
>                   {
>                     "mountPath": "/opt/ml/bin",
>                     "name": "app-volume"
>                   },
>                   {
>                     "mountPath": "/opt/ml/nfs-root",
>                     "name": "nfs-volume"
>                   },
>                   {
>                     "mountPath": "/mnt/mesos/sandbox",
>                     "name": "log-volume",
>                     "subPathExpr": "$(K8S_POD_UID)/runs/$(K8S_POD_UID)"
>                   }
>                 ],
>                 "command": [
>                   "/opt/ml/bin/dumb-init",
>                   "--"
>                 ],
>                 "ports": [
>                   {
>                     "containerPort": 2222,
>                     "name": "tfjob-port"
>                   }
>                 ],
>                 "resources": {
>                   "requests": {
>                     "qiyi.com/fuse": 1,
>                     "cpu": 4,
>                     "nvidia.com/gpu": 1,
>                     "memory": "8192.0Mi"
>                   },
>                   "limits": {
>                     "qiyi.com/fuse": 1,
>                     "cpu": 4,
>                     "nvidia.com/gpu": 1,
>                     "memory": "8192.0Mi"
>                   }
>                 }
>               }
>             ],
>             "nodeSelector": {
>               "cluster-name": "jarvis-k8s-online02-gpu-training"
>             }
>           },
>           "metadata": {
>             "labels": {
>               "group": "jarvis-public",
>               "creator": "lihao04",
>               "distributed": "True",
>               "vcjob_name": "jarvis-vcjob-7f2e2b6d9e40126e1be1fd785ca2ea20",
>               "cluster_name": "jarvis-k8s-online02-gpu-training",
>               "role": "worker",
>               "task-spec": "other",
>               "jarvis-qrn-type": "k8s-training",
>               "team_name": "jarvis-dev-team"
>             },
>           }
>         },
>         "replicas": 3
>       }
>     ],
>     "schedulerName": "volcano",
>     "queue": "training-jarvis-dev-team-jarvis-k8s-online02-gpu-training",
>     "policies": [
>       {
>         "action": "RestartJob",
>         "event": "PodEvicted"
>       }
>     ],
>     "plugins": {
>       "svc": [],
>       "env": [],
>       "ssh": []
>     },
>     "minAvailable": 4
>   },
>   "apiVersion": "batch.volcano.sh/v1alpha1",
>   "metadata": {
>     "labels": {
>       "cluster_name": "jarvis-k8s-online02-gpu-training",
>       "group": "jarvis-public",
>       "creator": "lihao04",
>       "jarvis-qrn-type": "k8s-training",
>       "team_name": "jarvis-dev-team",
>       "distributed": "True"
>     },
>     "namespace": "training-jarvis-dev-team-jarvis-k8s-online02-gpu-training",
>     "name": "jarvis-vcjob-7f2e2b6d9e40126e1be1fd785ca2ea20",
>     "annotations": {
>       "job_name": "horovod-demo200612101105",
>       "qrn": "qrn:qcc:jarvis:cn-bj:jarvis-public:trainingjob:horovod-demo200612101105"
>     }
>   }
> }
> ```
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Volcano Version: 0.3
> * Kubernetes version (use `kubectl version`): 1.16.2
> * Cloud provider or hardware configuration:
> * OS (e.g. from /etc/os-release):
> * Kernel (e.g. `uname -a`):
> * Install tools:
> * Others:

@silenceli please make an introduction of your trainning environment network configuration

**Comment by Thor-wl** [comment]
@silenceli Please make an introduction of your trainning environment network configuration

**Comment by silenceli** [comment]
It's a mistake that I configure the wrong docker/flannel network

**Comment by nicklhy** [comment]
> It's a mistake that I configure the wrong docker/flannel network

Got the same problem. Could you share how you solved this problem ?

**Comment by SimZhou** [comment]
Got an similar issue:

```bash
# cmd
horovodrun --verbose -np 4 -H job-170013380772780309415-yihua-zhou-master-0.job-170013380772780309415-yihua-zhou:1,job-170013380772780309415-yihua-zhou-worker-0.job-170013380772780309415-yihua-zhou:1,job-170013380772780309415-yihua-zhou-worker-1.job-170013380772780309415-yihua-zhou:1,job-170013380772780309415-yihua-zhou-worker-2.job-170013380772780309415-yihua-zhou:1 -p 6666 python -c "import horovod.torch as hvd; hvd.init(); print(hvd.rank(), hvd.local_rank(), hvd.size())"

# err_msg
Filtering local host names.
Remote host found: job-170013380772780309415-yihua-zhou-worker-0.job-170013380772780309415-yihua-zhou job-170013380772780309415-yihua-zhou-worker-1.job-170013380772780309415-yihua-zhou job-170013380772780309415-yihua-zhou-worker-2.job-170013380772780309415-yihua-zhou
Checking ssh on all remote hosts.
SSH was successful into all the remote hosts.
Testing interfaces on all the hosts.
Interfaces on all the hosts were successfully checked.
Common interface found: eth0
mpirun --allow-run-as-root --tag-output -np 4 -H job-170013380772780309415-yihua-zhou-master-0.job-170013380772780309415-yihua-zhou:1,job-170013380772780309415-yihua-zhou-worker-0.job-170013380772780309415-yihua-zhou:1,job-170013380772780309415-yihua-zhou-worker-1.job-170013380772780309415-yihua-zhou:1,job-170013380772780309415-yihua-zhou-worker-2.job-170013380772780309415-yihua-zhou:1 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib -mca plm_rsh_args "-p 6666" -mca btl_tcp_if_include eth0 -x NCCL_SOCKET_IFNAME=eth0  -x CUDAToolkit_ROOT -x CUDA_HOME -x DEBIAN_FRONTEND -x HOME -x HOROVOD_CUDA_HOME -x HOROVOD_NCCL_HOME -x HOSTNAME -x JobID -x KUBERNETES_PORT -x KUBERNETES_PORT_443_TCP -x KUBERNETES_PORT_443_TCP_ADDR -x KUBERNETES_PORT_443_TCP_PORT -x KUBERNETES_PORT_443_TCP_PROTO -x KUBERNETES_SERVICE_HOST -x KUBERNETES_SERVICE_PORT -x KUBERNETES_SERVICE_PORT_HTTPS -x LC_CTYPE -x LD_LIBRARY_PATH -x LOG_FILE -x MASTER_ADDR -x MASTER_PORT -x MKL_NUM_THREADS -x NCCL_DEBUG -x NCCL_IB_DISABLE -x NCCL_SOCKET_IFNAME -x NUMEXPR_NUM_THREADS -x NVIDIA_DRIVER_CAPABILITIES -x NVIDIA_VISIBLE_DEVICES -x OMP_NUM_THREADS -x OPENBLAS_NUM_THREADS -x PARENT_ENV -x PATH -x PWD -x PYTORCH_VERSION -x RANK -x SHLVL -x TERM -x TZ -x USER -x VC_MASTER_HOSTS -x VC_MASTER_NUM -x VC_WORKER_HOSTS -x VC_WORKER_NUM -x VECLIB_NUM_THREADS -x WORLD_SIZE -x _  python -c 'import horovod.torch as hvd; hvd.init(); print(hvd.rank(), hvd.local_rank(), hvd.size())'
ssh: Could not resolve hostname job-170013380772780309415-yihua-zhou-worker-2: Name or service not known
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   job-170013380772780309415-yihua-zhou-master-0
  target node:  job-170013380772780309415-yihua-zhou-worker-0

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
[job-170013380772780309415-yihua-zhou-master-0:00811] 1 more process has sent help message help-errmgr-base.txt / no-path
[job-170013380772780309415-yihua-zhou-master-0:00811] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
