### ISSUE TITLE
Refactor predicates & nodeorders

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#864]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Description**:

1. Move Snapshot & SchedulerFramework into `pkg/scheduler/plugins/util`, as they 're not part of Volcano framework.
2. It's better implement FrameworkHandler by Volcano.ClusterInfo instead of copying it from upstrewam.

**Comment by k82cn** [comment]
@hzxuzhonghu , do you have time on this one? We'd better to correct that before this release.

**Comment by Thor-wl** [comment]
releated PR: https://github.com/volcano-sh/volcano/pull/923

**Comment by hzxuzhonghu** [comment]
This is done
