### ISSUE TITLE
Object update failed with operation cannot be fulfilled , object has been modify

### ISSUE THREAD

**Issue by gaopeiliang** [volcano-sh/volcano#871]
**What happened**:

Sometimes I see some error in log
```
E0618 11:17:04.722733       1 queue_controller_action.go:75] Failed to update status of Queue default: Operation cannot be fulfilled on queues.scheduling.sigs.dev "default": the object has been modified; please apply your changes to the latest version and try again.

```

and sometimes I see Job stay Pending status  when all pod job has completed ！
```
          name: corefiles
status:
  controlledResources:
    plugin-env: env
    plugin-svc: svc
  minAvailable: 20
  state:
    lastTransitionTime: "2020-06-16T00:14:45Z"
    phase: Pending

--------   

0/1     Completed           0          23m     （20）


------  
Status:
  Controlled Resources:
    Plugin - Env:  env
    Plugin - Svc:  svc
  Min Available:   20
  State:
    Last Transition Time:  2020-06-16T00:14:45Z
    Phase:                 Pending
Events:
  Type    Reason         Age                 From                   Message
  ----    ------         ----                ----                   -------
  Normal  ExecuteAction  17m (x10 over 21m)  vc-controller-manager  Job failed on action SyncJob for retry limit reached

```
   

**What you expected to happen**:
Job status turn to next status until completed  when job has completed

**Environment**:
- Volcano Version:   release-0.4
- Kubernetes version (use `kubectl version`):  1.14
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):   ubuntu:16
- Kernel (e.g. `uname -a`):  Linux 4.9.70-040970-generic

**Comment by gaopeiliang** [comment]
![image](https://user-images.githubusercontent.com/11383058/85017771-a20e0b80-b19e-11ea-8493-9101d2a668bf.png)

I see log info ,,  status execute failed with object has been modify !

```
	if err := st.Execute(action); err != nil {
		if queue.NumRequeues(req) < maxRetries {
			klog.V(2).Infof("Failed to handle Job <%s/%s>: %v",
				jobInfo.Job.Namespace, jobInfo.Job.Name, err)
			// If any error, requeue it.
			queue.AddRateLimited(req)
			return true
		}
		cc.recordJobEvent(jobInfo.Job.Namespace, jobInfo.Job.Name, batchv1alpha1.ExecuteAction, fmt.Sprintf(
			"Job failed on action %s for retry limit reached", action))
		klog.Warningf("Dropping job<%s/%s> out of the queue: %v because max retries has reached", jobInfo.Job.Namespace, jobInfo.Job.Name, err)
	}

```

default_worker = 3,,  maybe I should increase worker number ,, we have job pod about 5-6k,, someone know what happend,, need help !!!!

**Comment by k82cn** [comment]
@Thor-wl , please help to check that :)

**Comment by gaopeiliang** [comment]
Maybe we have an slow ETCD cluster,,,,,  move to an SSD ETCD cluster .....

**Comment by zen-xu** [comment]
We have meet the same problem many times, and our `etcd` is on the **ssd cluster**.

**Comment by Thor-wl** [comment]
releated PR: https://github.com/volcano-sh/volcano/pull/919, the PR has been synchronized in master and release-0.4

**Comment by Thor-wl** [comment]
@assign @silenceli
