### ISSUE TITLE
multi-preemptor-jobs who are in different priority  flakes

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#911]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

multi-preemptor-jobs who are in different priority  fails https://travis-ci.com/github/volcano-sh/volcano/jobs/358016983

**Comment by Thor-wl** [comment]
> /assign @Thor-wl

It seems the travis-ci link cannot be opened. What was the phenomenon then？

**Comment by hzxuzhonghu** [comment]
You need to join volcano group. Please open a new issue
