### ISSUE TITLE
volcano provide the ability to scale down task replicas to zero

### ISSUE THREAD

**Issue by freeben09** [volcano-sh/volcano#915]

**Comment by william-wang** [comment]
The custoomer is using volcano job scaling right now. There is a case is like this. The task in the same job need to know each other, if they change the replicas from 2 to 3, the new added task can not be recogenized by other two tasks. Customer want the ability to scale to zero.  
@hzxuzhonghu please help to evaluate whether it is a common customer request and supportable.

**Comment by k82cn** [comment]
I think we already support this feature :)
