### ISSUE TITLE
Cli client  create queue missing Reclaimable fields

### ISSUE THREAD

**Issue by QizhouYang** [volcano-sh/volcano#925]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature
/kind bug

**What happened**:
vcctl queue  create --help
creates queue

Usage:
  vcctl queue create [flags]

Flags:
  -h, --help                help for create
      --kubeconfig string   (optional) absolute path to the kubeconfig file (default "/root/.kube/config")
  -s, --master string       the address of apiserver
  -n, --name string         the name of queue (default "test")
      --scheduler string    the scheduler for this job (default "volcano")
  -S, --state string        the state of queue (default "Open")
  -w, --weight int32        the weight of the queue (default 1)

**What you expected to happen**:
vcctl queue  create --help
creates queue

Usage:
  vcctl queue create [flags]

Flags:
  -h, --help                help for create
      --kubeconfig string   (optional) absolute path to the kubeconfig file (default "/root/.kube/config")
  -s, --master string       the address of apiserver
  -n, --name string         the name of queue (default "test")
      --scheduler string    the scheduler for this job (default "volcano")
  -S, --state string        the state of queue (default "Open")
  -w, --weight int32        the weight of the queue (default 1)
  **-r, -- reclaimable  boolean  the reclaimable  of the queue (default true)**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
we're going to abandon `vcctl`, and replace it with `vjob, `vadmin` and so on :)

**Comment by QizhouYang** [comment]
OK，Thx！

**Comment by k82cn** [comment]
@QizhouYang , I'm not sure whether `vadmin` have similar issue :)
