### ISSUE TITLE
Allow multi sync job works run in parallel

### ISSUE THREAD

**Issue by hzxuzhonghu** [volcano-sh/volcano#93]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

Currently, there is only one goroutine worker syncing jobs. For large scale jobs, this will be a bottle neck.

**Comment by TommyLike** [comment]
Do you mind to re-upload your patch again 😄

**Comment by hzxuzhonghu** [comment]
Sure, will try to find the commit
