### ISSUE TITLE
Deploy FOSSA license scanning for this repo

### ISSUE THREAD

**Issue by idvoretskyi** [volcano-sh/volcano#936]
FOSSA license scanning for this repo should be enabled:
https://github.com/fossas/fossa-cli

cc @caniszczyk

**Comment by idvoretskyi** [comment]
@k82cn @kevin-wangzefeng @hzxuzhonghu can you please enable the GitHub actions for this repo so CNCF could enable the FOSSA scanning here (or add me temporarily to the org so I could handle this)?

A good sample of how this is done for the different CNCF projects is here - https://github.com/kedacore/keda/blob/master/.github/workflows/fossa.yml

**Comment by k82cn** [comment]
ok, sure, let me enable it :)

**Comment by idvoretskyi** [comment]
@k82cn can you please review and merge the remaining PRs:

https://github.com/volcano-sh/website/pull/42
https://github.com/volcano-sh/mocks/pull/1
https://github.com/volcano-sh/volcano-ansible/pull/2

**Comment by k82cn** [comment]
> @k82cn can you please review and merge the remaining PRs:
> 
> [volcano-sh/website#42](https://github.com/volcano-sh/website/pull/42)
> [volcano-sh/mocks#1](https://github.com/volcano-sh/mocks/pull/1)
> [volcano-sh/volcano-ansible#2](https://github.com/volcano-sh/volcano-ansible/pull/2)

Sure, I'll merge them.
