### ISSUE TITLE
Make charts as submod of Volcano

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#939]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/help wanted

**Description**:

Currently, we publish helm chart at https://github.com/volcano-sh/charts and keep helm charts up-to-date at 
 https://github.com/volcano-sh/volcano/tree/master/installer , and they already mismatched. It's better to make charts as submod of volcano to keep them sync.

**Comment by nrchakradhar** [comment]
@k82cn I can work on this if some more information is provided as to what changes are needed as this is would be my first issue in volcano. Do we want to create PRs automatically in  https://github.com/volcano-sh/charts OR, something else.

**Comment by k82cn** [comment]
We'd like to use the feature of git submod to handle that, refer to https://www.git-scm.com/book/en/v2/Git-Tools-Submodules for more information :)
