### ISSUE TITLE
Question: can volcano change resource require/limit number, or add resource type by no change yaml?

### ISSUE THREAD

**Issue by zishen** [volcano-sh/volcano#940]
> /kind feature

**What happened**:
Application apply a vcjob yaml, and it requires resource called A. But due to the system env, I want to change A to B，and change A's number both.
Can volcano do this？ If can, how?

**What you expected to happen**:

volcano can change resource require/limit number, or add resource type by no change in yaml.

I change the volcano-schedule struct value :
```
task.InitResreq.ScalarResources, task.Resreq.ScalarResources, job.TotalRequest.ScalarResources, job.Allocated.ScalarResources 
or nod.idle, node.used
```
but does not work.

**Anything else we need to know?**:

**Environment**:
- Volcano Version: v.4.0
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration: arm64/x86
- OS (e.g. from /etc/os-release): ubuntu18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zishen** [comment]
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
Currently, we only support job scale up/down. This is not supported, and i think it is not very tricky if we want to do this. 
The feasible way is:

1. check the pod template update
2. delete all running pods
3. update podgroup or so
4. re-run all needed pods

**Comment by zishen** [comment]
> Currently, we only support job scale up/down. This is not supported, and i think it is not very tricky if we want to do this.
> The feasible way is:
> 
> 1. check the pod template update
> 2. delete all running pods
> 3. update podgroup or so
> 4. re-run all needed pods

ok, thanks a lot. we do this in device-plugin as gpu. And this works.
