### ISSUE TITLE
support scheduling monitor

### ISSUE THREAD

**Issue by daixiang0** [volcano-sh/volcano#962]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

In some case, scheduling may have some time to wait, maybe resources limit, maybe pre-job not finish, maybe too much job in queue. It is helpful for users to know their jobs's status(queued, wait or so on).

Also, it is very useful to analyze scheduing bottleneck.

The monitor should show following info:
- queue status
- job status

It would be cool if all data in realtime like `top` does.

**Comment by daixiang0** [comment]
ping @k82cn

**Comment by k82cn** [comment]
> ping @k82cn

That's reasonable to me :)

**Comment by Thor-wl** [comment]
This feature has been launched in v1.1.0 and will be contiue upgraded
