### ISSUE TITLE
V0.4 & V0.1 Statement Discard when schedule failed not correct result nodeinfo.pods add but not sub. 

### ISSUE THREAD

**Issue by Lhfxxqx510** [volcano-sh/volcano#979]
**Is this a BUG REPORT or FEATURE REQUEST?**:

stmt.Discard called unpipeline and unallocate to delete pipelined or allocted task in job when job schedule failed , in unpipeline and unallocate function will remove nodeinfo.pods for node from task.NodeName, but task.NodeName is set as "" before call DeallocateFunc with args task. 

/kind bug

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 0.4 & 1.0 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Lhfxxqx510** [comment]
What happened:   for a job after many times allocate and discard, the job's task will not find predicate node, because AddPredicateFn will return NodePodNumberExceeded which means nodeInfo.Pos is more than node.Allocatable.MaxTaskNum。
this is caused by nodeInfo only add task when allocate ,but not sub task when unallocate.

**Comment by hzxuzhonghu** [comment]
@Lhfxxqx510  Which plugin do you mean? If it is `predicate`, I think we do it here https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/predicates/predicates.go#L165

**Comment by Lhfxxqx510** [comment]
@hzxuzhonghu   https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/predicates/predicates.go#L140  nodeName := event.Task.NodeName    nodeName alwys is  "",  and this is set by https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/framework/statement.go#L165 && https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/framework/statement.go#L332

**Comment by hzxuzhonghu** [comment]
Thanks, IC

Can you test it by moving L332 after DeallocateFunc


https://github.com/volcano-sh/volcano/blob/91e94ae75083316e14d7ecd529860849f5fa41b8/pkg/scheduler/framework/statement.go#L332-L339

**Comment by Lhfxxqx510** [comment]
I Modify  L332 to 
  //task.NodeName = "" 
 for _, eh := range s.ssn.eventHandlers { 
 	if eh.DeallocateFunc != nil { 
 		eh.DeallocateFunc(&Event{ 
 			Task: task, 
 		}) 
 	} 
 } 
task.NodeName = "" 

and modify  L204 to   //task.NodeName = ""
add   task.NodeName = "" to L225

It works correctly.

**Comment by hzxuzhonghu** [comment]
Thanks for the verification, could you please file a pr?
