### ISSUE TITLE
Job plugin function 'OnJobAdd' is called multiple times

### ISSUE THREAD

**Issue by william-wang** [volcano-sh/volcano#983]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

We add a customized job plugin and implement the OnJobAdd function. 
The OnJobAdd function is supposed to be called only once when the job is added.
The fact is the OnJobAdd function is called mutiples times and cause a wrong behavior.

The cause is the new created job keeps in 'Pending' for a period of time. So each time it returns false and will be initiated again according to following logic.
```
func isInitiated(job *batch.Job) bool {
	if job.Status.State.Phase == "" || job.Status.State.Phase == batch.Pending || job.Status.State.Phase == batch.Restarting {
		return false
	}
	return true
}
```

**What you expected to happen**:
The function should be called only once as expected.

**How to reproduce it (as minimally and precisely as possible)**:
configure a job controller plugin and implement the JobOnAdd func.

**Anything else we need to know?**:

**Environment**: Linux
- Volcano Version: volcano 0.4 
- Kubernetes version (use `kubectl version`): K8S 1.13
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by hzxuzhonghu** [comment]
We can not ensure `OnJobAdd ` called only once.  Actually the name is confusing. It should be renamed to OnJobInit or something

**Comment by k82cn** [comment]
> We can not ensure `OnJobAdd ` called only once. Actually the name is confusing. It should be renamed to OnJobInit or something

why? we should only get `add` event once.

**Comment by hzxuzhonghu** [comment]
Think of a simple scene: If we got a restart, or leader lost, A new `Add` event will triggered

**Comment by k82cn** [comment]
> Think of a simple scene: If we got a restart, or leader lost, A new `Add` event will triggered

let's handle it similar to informer callback.
