### ISSUE TITLE
[tech-debat] gpu-operator integration

### ISSUE THREAD

**Issue by k82cn** [volcano-sh/volcano#985]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:

Should we use an operator to manage accelerator device plugins and related components. xref https://github.com/NVIDIA/gpu-operator .

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Jeffwan** [comment]
@k82cn 
gpu-operator simplify the stack and user doesn't have to install driver. It's kind of an alternative to current stack. 

current:  nvidia driver(node level) + device plugin (k8s level) + DCGM monitoring (application level) 
gpu-operator: all in on stack

From volcano's perspective, I thought this layer is transparent?

**Comment by k82cn** [comment]
Yes, that's helpful for user to deploy gpu stack; maybe do some integration with it :)
