### ISSUE TITLE
How to set minAvailable in task level 

### ISSUE THREAD

**Issue by weiranzhixin** [volcano-sh/volcano#988]
* vcjob has 2 tasks: task_a, task_b
* task_a has 2 replicas, task_b has 3 replicas
* expected minAvailable  resource is : 1 replica of task_a, 2 replica of task_b

* when 1 replica of task_a, 2 replica of task_b succeeded, then complete the job
* the status of job is completed

**Comment by weiranzhixin** [comment]
can volcano act like this described in the issue ?

**Comment by k82cn** [comment]
I think this is a new feature to volcano :) 

/cc @hzxuzhonghu @Thor-wl

**Comment by hzxuzhonghu** [comment]
@weiranzhixin Can you elaborate on your use case?

**Comment by weiranzhixin** [comment]
* for ps and  worker scene,  we want to complete the whole job when expected numbers of workers  succeeded.
* expected numbers of workers  may be lower than the replicas of worker task

**Comment by k82cn** [comment]
> * for ps and  worker scene,  we want to complete the whole job when expected numbers of workers  succeeded.
> * expected numbers of workers  may be lower than the replicas of worker task

That's interesting! Will it get correct result if just part of worker finished?

**Comment by hzxuzhonghu** [comment]
@weiranzhixin I have consulted several guys working on tensorflow,  they do not know this kind of usage. So can you give us some more context?

**Comment by Thor-wl** [comment]
@weiranzhixin I've taken the feature into v1.2 feature discussion.
