### ISSUE TITLE
Questions about volcano and Kubernetes Scheduer Framework

### ISSUE THREAD

**Issue by kinderyj** [volcano-sh/volcano#993]
> /kind questions

When volcano works with Kubernetes' default-scheduler, the same resource on a node may be allocated by the volcano and default-scheduler at the same time.  How does volcano handle this issue?

By the way, Kubernetes provides Kubernetes Scheduer Framework for developers to extends the scheduler's ability, is it possible for volcano to use the Kubernetes Scheduer Framework?
 
Thanks a lot!

**Comment by nrchakradhar** [comment]
I am also interested in this discussion. Are there any discussions happening?
I see that @k82cn was reviewer for [KEP scheduling framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md).
In K8S 1.19 there has been some work done and the final target as mentioned seems to be 1.21
https://github.com/kubernetes/enhancements/issues/1451#issuecomment-655568616
Do we need to track sig-scheduling OR some mailing list in volcano. Please suggest.

**Comment by Thor-wl** [comment]
It does a problem about resource allocation confliction when default-scheduler works with Volcano. There's lack of a mechanism how to ensure resource usage synchronization for more than one scheduler when scheduling. But if that happens, kubelet will find the problem in time and reject the later task. In practice, we do not suggest work like this.

**Comment by k82cn** [comment]
> By the way, Kubernetes provides Kubernetes Scheduer Framework for developers to extends the scheduler's ability, is it possible for volcano to use the Kubernetes Scheduer Framework?

Nop, the framework in Volcano is better, it provides more mechanism for different scenarios.

**Comment by dafu-wu** [comment]
> 

@k82cn  Could you compare the pros and cons of the next two frameworks in detail? Or more specifically, why the vol framework is better？
